troop_options['5fb1ba31e1af06001770dc6b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1150,
    endDate=1420,
  }
}
troop_options['5fb1ba31e1af06001770dc6e'] = {
  min=1,
  max=1,
  dateRange={
    startDate=1150,
    endDate=1420,
  }
}
troop_options['5fb1ba31e1af06001770dc71'] = {
  min=5,
  max=14,
  dateRange={
    startDate=1150,
    endDate=1420,
  }
}
troop_options['5fb1ba31e1af06001770dc73'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1150,
    endDate=1420,
  }
}
troop_options['5fb1ba31e1af06001770dc75'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1150,
    endDate=1420,
  }
}
-- allies
