troop_options['615351b503385c0016b88b42'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1260,
    endDate=1275,
  }
}
troop_options['615351b503385c0016b88b45'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1260,
    endDate=1275,
  }
}
troop_options['615351b503385c0016b88b47'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1260,
    endDate=1275,
  }
}
troop_options['615351b503385c0016b88b49'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1260,
    endDate=1275,
  }
}
troop_options['615351b503385c0016b88b4c'] = {
  min=1,
  max=3,
  dateRange={
    startDate=1260,
    endDate=1275,
  }
}
troop_options['615351b503385c0016b88b4e'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1260,
    endDate=1275,
  }
}
-- allies
