g_str_5fb1ba3de1af06001770f30a_general='5fb1ba3de1af06001770f30a_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f30a_general]={
  id=g_str_5fb1ba3de1af06001770f30a_general,
  name='Elephants General',
  min=2,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
  troop_option_id="5fb1ba3de1af06001770f309",
}
g_str_5fb1ba3de1af06001770f30a='5fb1ba3de1af06001770f30a'
g_base_definitions[g_str_5fb1ba3de1af06001770f30a]={
  id=g_str_5fb1ba3de1af06001770f30a,
  name='Elephants',
  min=2,
  max=3,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba3de1af06001770f309",
}
g_str_5fb1ba3de1af06001770f30d='5fb1ba3de1af06001770f30d'
g_base_definitions[g_str_5fb1ba3de1af06001770f30d]={
  id=g_str_5fb1ba3de1af06001770f30d,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Better horsemen, some with barding',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3de1af06001770f30c",
}
g_str_5fb1ba3de1af06001770f30f='5fb1ba3de1af06001770f30f'
g_base_definitions[g_str_5fb1ba3de1af06001770f30f]={
  id=g_str_5fb1ba3de1af06001770f30f,
  name='Bad Horse',
  min=1,
  max=2,
  description='Inferior horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba3de1af06001770f30e",
}
g_str_5fb1ba3de1af06001770f311='5fb1ba3de1af06001770f311'
g_base_definitions[g_str_5fb1ba3de1af06001770f311]={
  id=g_str_5fb1ba3de1af06001770f311,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Guard spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3de1af06001770f310",
}
g_str_5fb1ba3de1af06001770f311_elephant_screen='5fb1ba3de1af06001770f311_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f311_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f311_elephant_screen,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Guard spearmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3de1af06001770f310",
}
g_str_5fb1ba3de1af06001770f311_elephant_screen_elephant_screen_counter='5fb1ba3de1af06001770f311_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3de1af06001770f311_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3de1af06001770f311_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=1,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3de1af06001770f314='5fb1ba3de1af06001770f314'
g_base_definitions[g_str_5fb1ba3de1af06001770f314]={
  id=g_str_5fb1ba3de1af06001770f314,
  name='Raiders',
  min=1,
  max=3,
  description='Swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba3de1af06001770f313",
}
g_str_5fb1ba3de1af06001770f314_elephant_screen='5fb1ba3de1af06001770f314_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f314_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f314_elephant_screen,
  name='Raiders',
  min=1,
  max=3,
  description='Swordsmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba3de1af06001770f313",
}
g_str_5fb1ba3de1af06001770f314_elephant_screen_elephant_screen_counter='5fb1ba3de1af06001770f314_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3de1af06001770f314_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3de1af06001770f314_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=1,
  max=3,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3de1af06001770f317='5fb1ba3de1af06001770f317'
g_base_definitions[g_str_5fb1ba3de1af06001770f317]={
  id=g_str_5fb1ba3de1af06001770f317,
  name='Light Foot',
  min=0,
  max=4,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3de1af06001770f316",
}
g_str_5fb1ba3de1af06001770f317_elephant_screen='5fb1ba3de1af06001770f317_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f317_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f317_elephant_screen,
  name='Light Foot',
  min=0,
  max=4,
  description='Javelinmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba3de1af06001770f316",
}
g_str_5fb1ba3de1af06001770f317_elephant_screen_elephant_screen_counter='5fb1ba3de1af06001770f317_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3de1af06001770f317_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3de1af06001770f317_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3de1af06001770f31a='5fb1ba3de1af06001770f31a'
g_base_definitions[g_str_5fb1ba3de1af06001770f31a]={
  id=g_str_5fb1ba3de1af06001770f31a,
  name='Bow Levy',
  min=6,
  max=12,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3de1af06001770f319",
}
g_str_5fb1ba3de1af06001770f31a_elephant_screen='5fb1ba3de1af06001770f31a_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f31a_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f31a_elephant_screen,
  name='Bow Levy',
  min=6,
  max=12,
  description='Bowmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3de1af06001770f319",
}
g_str_5fb1ba3de1af06001770f31a_elephant_screen_elephant_screen_counter='5fb1ba3de1af06001770f31a_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3de1af06001770f31a_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3de1af06001770f31a_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=6,
  max=12,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3de1af06001770f31d='5fb1ba3de1af06001770f31d'
g_base_definitions[g_str_5fb1ba3de1af06001770f31d]={
  id=g_str_5fb1ba3de1af06001770f31d,
  name='Horde',
  min=0,
  max=2,
  description='Camp followers',
  troop_type="Horde",
  troop_option_id="5fb1ba3de1af06001770f31c",
}
g_str_5fb1ba3de1af06001770f31f='5fb1ba3de1af06001770f31f'
g_base_definitions[g_str_5fb1ba3de1af06001770f31f]={
  id=g_str_5fb1ba3de1af06001770f31f,
  name='Skirmishers',
  min=0,
  max=1,
  description='Forest and hill tribe skirmishing bowmen or Kashmiri slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3de1af06001770f31e",
}
g_str_5fb1b9efe1af06001770a0b4_camp='5fb1b9efe1af06001770a0b4_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a0b4_camp]={
  id=g_str_5fb1b9efe1af06001770a0b4_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba0fe1af06001770addd='5fb1ba0fe1af06001770addd'
g_base_definitions[g_str_5fb1ba0fe1af06001770addd]={
  id=g_str_5fb1ba0fe1af06001770addd,
  name='Horse Bow',
  min=2,
  max=3,
  description='Hun horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba0fe1af06001770addc",
}
g_str_5fb1ba0fe1af06001770addf='5fb1ba0fe1af06001770addf'
g_base_definitions[g_str_5fb1ba0fe1af06001770addf]={
  id=g_str_5fb1ba0fe1af06001770addf,
  name='Elephants',
  min=0,
  max=1,
  description='Indian war elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba0fe1af06001770adde",
}
g_str_5fb1ba0fe1af06001770ade1='5fb1ba0fe1af06001770ade1'
g_base_definitions[g_str_5fb1ba0fe1af06001770ade1]={
  id=g_str_5fb1ba0fe1af06001770ade1,
  name='Horde',
  min=0,
  max=1,
  description='Indian throng',
  troop_type="Horde",
  troop_option_id="5fb1ba0fe1af06001770ade0",
}
g_str_5fb1ba17e1af06001770b87c='5fb1ba17e1af06001770b87c'
g_base_definitions[g_str_5fb1ba17e1af06001770b87c]={
  id=g_str_5fb1ba17e1af06001770b87c,
  name='Elephants',
  min=1,
  max=1,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba17e1af06001770b87b",
}
g_str_5fb1ba17e1af06001770b87e='5fb1ba17e1af06001770b87e'
g_base_definitions[g_str_5fb1ba17e1af06001770b87e]={
  id=g_str_5fb1ba17e1af06001770b87e,
  name='Raiders',
  min=1,
  max=3,
  description='Valperra swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba17e1af06001770b87d",
}
g_str_5fb1ba17e1af06001770b880='5fb1ba17e1af06001770b880'
g_base_definitions[g_str_5fb1ba17e1af06001770b880]={
  id=g_str_5fb1ba17e1af06001770b880,
  name='Bow Levy',
  min=0,
  max=1,
  description='Villikal bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba17e1af06001770b87f",
}
