-- 5fb1b9ede1af060017709f7b Seljuk Eastern Sultanates  1092 to 1194 AD

army['5fb1b9ede1af060017709f7b']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
      'Steppe',
    },
    name='Seljuk Eastern Sultanates  1092 to 1194 AD',
    id='5fb1b9ede1af060017709f7b',
    dateRange={
      startDate=1092,
      endDate=1194,
    },
  },
  g_base_definitions[g_str_615351b003385c0016b87e94_general],
  g_base_definitions[g_str_615351b003385c0016b87e94_general_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87e94],
  g_base_definitions[g_str_615351b003385c0016b87e94_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87e97_general],
  g_base_definitions[g_str_615351b003385c0016b87e97_general_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87e97],
  g_base_definitions[g_str_615351b003385c0016b87e97_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87e98_general],
  g_base_definitions[g_str_615351b003385c0016b87e98_general_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87e98],
  g_base_definitions[g_str_615351b003385c0016b87e98_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87e9b_general],
  g_base_definitions[g_str_615351b003385c0016b87e9b],
  g_base_definitions[g_str_615351b003385c0016b87e9d],
  g_base_definitions[g_str_615351b003385c0016b87e9f],
  g_base_definitions[g_str_615351b003385c0016b87ea2],
  g_base_definitions[g_str_615351b003385c0016b87ea2_mounted_mobile_infantry],
  g_base_definitions[g_str_615351b003385c0016b87ea2_dismounted_mobile_infantry],
  g_base_definitions[g_str_615351b003385c0016b87ea5],
  g_base_definitions[g_str_615351b003385c0016b87ea7],
  g_base_definitions[g_str_5fb1b9ede1af060017709f7b_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f7b_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f7b"] = army["5fb1b9ede1af060017709f7b"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Seljuk Eastern Sultanates  1092 to 1194 AD"] = army["5fb1b9ede1af060017709f7b"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Seljuk Eastern Sultanates  1092 to 1194 AD"] = army["5fb1b9ede1af060017709f7b"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Seljuk Eastern Sultanates  1092 to 1194 AD"] = army["5fb1b9ede1af060017709f7b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Seljuk Eastern Sultanates  1092 to 1194 AD"] = army["5fb1b9ede1af060017709f7b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f7b"] = {}
army_dates["5fb1b9ede1af060017709f7b"]["1092 AD to 1194 AD"] = {
  startDate=1092,
  endDate=1194
}
army_dates["5fb1b9ede1af060017709f7b"]["1092 AD to 1099 AD"] = {
  startDate=1092,
  endDate=1099
}
army_dates["5fb1b9ede1af060017709f7b"]["1100 AD to 1116 AD"] = {
  startDate=1100,
  endDate=1116
}
army_dates["5fb1b9ede1af060017709f7b"]["1117 AD to 1128 AD"] = {
  startDate=1117,
  endDate=1128
}
army_dates["5fb1b9ede1af060017709f7b"]["1129 AD to 1141 AD"] = {
  startDate=1129,
  endDate=1141
}
army_dates["5fb1b9ede1af060017709f7b"]["1142 AD to 1157 AD"] = {
  startDate=1142,
  endDate=1157
}
army_dates["5fb1b9ede1af060017709f7b"]["1158 AD to 1163 AD"] = {
  startDate=1158,
  endDate=1163
}
army_dates["5fb1b9ede1af060017709f7b"]["1164 AD to 1186 AD"] = {
  startDate=1164,
  endDate=1186
}
army_dates["5fb1b9ede1af060017709f7b"]["1187 AD to 1194 AD"] = {
  startDate=1187,
  endDate=1194
}
