-- 5fb1b9e0e1af060017709798 Sangam Era Sinhalese  175 BC to 300 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ae1af06001770d061_general='5fb1ba2ae1af06001770d061_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770d061_general]={
  id=g_str_5fb1ba2ae1af06001770d061_general,
  name='Elephants General',
  min=1,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
}
g_str_5fb1ba2ae1af06001770d061='5fb1ba2ae1af06001770d061'
g_base_definitions[g_str_5fb1ba2ae1af06001770d061]={
  id=g_str_5fb1ba2ae1af06001770d061,
  name='Elephants',
  min=1,
  max=1,
  description='War elephants',
  troop_type="Elephants",
}
g_str_5fb1ba2ae1af06001770d063='5fb1ba2ae1af06001770d063'
g_base_definitions[g_str_5fb1ba2ae1af06001770d063]={
  id=g_str_5fb1ba2ae1af06001770d063,
  name='Bow Levy',
  min=8,
  max=16,
  description='Militia bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba2ae1af06001770d065='5fb1ba2ae1af06001770d065'
g_base_definitions[g_str_5fb1ba2ae1af06001770d065]={
  id=g_str_5fb1ba2ae1af06001770d065,
  name='Archers',
  min=0,
  max=1,
  description='Better militia bowmen with large hide shields',
  troop_type="Archers",
}
g_str_5fb1ba2ae1af06001770d067='5fb1ba2ae1af06001770d067'
g_base_definitions[g_str_5fb1ba2ae1af06001770d067]={
  id=g_str_5fb1ba2ae1af06001770d067,
  name='Light Foot',
  min=0,
  max=3,
  description='Wild tribesmen',
  troop_type="Light Foot",
}
g_str_5fb1ba2ae1af06001770d068='5fb1ba2ae1af06001770d068'
g_base_definitions[g_str_5fb1ba2ae1af06001770d068]={
  id=g_str_5fb1ba2ae1af06001770d068,
  name='Rabble',
  min=0,
  max=3,
  description='Wild tribesmen',
  troop_type="Rabble",
}
g_str_5fb1ba2ae1af06001770d06a='5fb1ba2ae1af06001770d06a'
g_base_definitions[g_str_5fb1ba2ae1af06001770d06a]={
  id=g_str_5fb1ba2ae1af06001770d06a,
  name='Archers',
  min=1,
  max=3,
  description='Villikal bowmen',
  troop_type="Archers",
}
g_str_5fb1b9e0e1af060017709798_camp='5fb1b9e0e1af060017709798_camp'
g_base_definitions[g_str_5fb1b9e0e1af060017709798_camp]={
  id=g_str_5fb1b9e0e1af060017709798_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e0e1af060017709798']={
  data={
    name='Sangam Era Sinhalese  175 BC to 300 AD'
  },
  g_base_definitions[g_str_5fb1ba2ae1af06001770d061_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d061],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d063],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d065],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d067],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d068],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d06a],
  g_base_definitions[g_str_5fb1b9e0e1af060017709798_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af060017709798"] = army["5fb1b9e0e1af060017709798"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Sangam Era Sinhalese  175 BC to 300 AD"] = army["5fb1b9e0e1af060017709798"]
