troop_options['615351b003385c0016b87dcd'] = {
  min=9,
  max=12,
  dateRange={
    startDate=950,
    endDate=1085,
  }
}
troop_options['615351b003385c0016b87dd0'] = {
  min=0,
  max=2,
  dateRange={
    startDate=950,
    endDate=1085,
  }
}
troop_options['615351b003385c0016b87dd2'] = {
  min=0,
  max=2,
  dateRange={
    startDate=950,
    endDate=1085,
  }
}
troop_options['615351b003385c0016b87dd4'] = {
  min=0,
  max=2,
  dateRange={
    startDate=950,
    endDate=1085,
  }
}
-- allies
