troop_options['615351ac03385c0016b8741e'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b87420'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b87423'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b87425'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b87427'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b87429'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b8742b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b87430'] = {
  min=4,
  max=6,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
troop_options['615351ac03385c0016b87432'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1194,
    endDate=1266,
  }
}
-- allies
