troop_options['5fb1ba28e1af06001770caf3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-700,
    endDate=10,
  }
}
troop_options['5fb1ba28e1af06001770caf5'] = {
  min=9,
  max=16,
  dateRange={
    startDate=-700,
    endDate=10,
  }
}
troop_options['5fb1ba28e1af06001770caf7'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-700,
    endDate=10,
  }
}
troop_options['5fb1ba28e1af06001770caf9'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-700,
    endDate=10,
  }
}
-- allies
-- 5fb1b9dde1af060017709630 Illyrian  700 BC to 10 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba28e1af06001770caf4_general='5fb1ba28e1af06001770caf4_general'
g_base_definitions[g_str_5fb1ba28e1af06001770caf4_general]={
  id=g_str_5fb1ba28e1af06001770caf4_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba28e1af06001770caf3",
}
g_str_5fb1ba28e1af06001770caf4='5fb1ba28e1af06001770caf4'
g_base_definitions[g_str_5fb1ba28e1af06001770caf4]={
  id=g_str_5fb1ba28e1af06001770caf4,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba28e1af06001770caf3",
}
g_str_5fb1ba28e1af06001770caf6_general='5fb1ba28e1af06001770caf6_general'
g_base_definitions[g_str_5fb1ba28e1af06001770caf6_general]={
  id=g_str_5fb1ba28e1af06001770caf6_general,
  name='Light Foot General',
  min=9,
  max=1,
  description='Light infantry and their armed slaves',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770caf5",
}
g_str_5fb1ba28e1af06001770caf6='5fb1ba28e1af06001770caf6'
g_base_definitions[g_str_5fb1ba28e1af06001770caf6]={
  id=g_str_5fb1ba28e1af06001770caf6,
  name='Light Foot',
  min=9,
  max=16,
  description='Light infantry and their armed slaves',
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770caf5",
}
g_str_5fb1ba28e1af06001770caf8='5fb1ba28e1af06001770caf8'
g_base_definitions[g_str_5fb1ba28e1af06001770caf8]={
  id=g_str_5fb1ba28e1af06001770caf8,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen or slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba28e1af06001770caf7",
}
g_str_5fb1ba28e1af06001770cafa='5fb1ba28e1af06001770cafa'
g_base_definitions[g_str_5fb1ba28e1af06001770cafa]={
  id=g_str_5fb1ba28e1af06001770cafa,
  name='Rabble',
  min=0,
  max=3,
  description='Javelinmen and shielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba28e1af06001770caf9",
}
g_str_5fb1ba28e1af06001770cafb_general='5fb1ba28e1af06001770cafb_general'
g_base_definitions[g_str_5fb1ba28e1af06001770cafb_general]={
  id=g_str_5fb1ba28e1af06001770cafb_general,
  name='Light Foot General',
  min=0,
  max=1,
  description='Javelinmen and shielded javelinmen',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770caf9",
}
g_str_5fb1ba28e1af06001770cafb='5fb1ba28e1af06001770cafb'
g_base_definitions[g_str_5fb1ba28e1af06001770cafb]={
  id=g_str_5fb1ba28e1af06001770cafb,
  name='Light Foot',
  min=0,
  max=3,
  description='Javelinmen and shielded javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770caf9",
}
g_str_5fb1b9dde1af060017709630_camp='5fb1b9dde1af060017709630_camp'
g_base_definitions[g_str_5fb1b9dde1af060017709630_camp]={
  id=g_str_5fb1b9dde1af060017709630_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dde1af060017709630_camp_pack_train='5fb1b9dde1af060017709630_camp_pack_train'
g_base_definitions[g_str_5fb1b9dde1af060017709630_camp_pack_train]={
  id=g_str_5fb1b9dde1af060017709630_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dde1af060017709630']={
  data={
    name='Illyrian  700 BC to 10 AD',
    id='5fb1b9dde1af060017709630',
    army_id='5fb1b9dde1af060017709630'
  },
  g_base_definitions[g_str_5fb1ba28e1af06001770caf4_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770caf4],
  g_base_definitions[g_str_5fb1ba28e1af06001770caf6_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770caf6],
  g_base_definitions[g_str_5fb1ba28e1af06001770caf8],
  g_base_definitions[g_str_5fb1ba28e1af06001770cafa],
  g_base_definitions[g_str_5fb1ba28e1af06001770cafb_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cafb],
  g_base_definitions[g_str_5fb1b9dde1af060017709630_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709630_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af060017709630"] = army["5fb1b9dde1af060017709630"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Illyrian  700 BC to 10 AD"] = army["5fb1b9dde1af060017709630"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Illyrian  700 BC to 10 AD"] = army["5fb1b9dde1af060017709630"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Illyrian  700 BC to 10 AD"] = army["5fb1b9dde1af060017709630"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Illyrian  700 BC to 10 AD"] = army["5fb1b9dde1af060017709630"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Illyrian  700 BC to 10 AD"] = army["5fb1b9dde1af060017709630"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af060017709630"] = {}
army_dates["5fb1b9dde1af060017709630"]["700 BC to 10 AD"] ="5fb1b9dde1af060017709630"
