-- 5fb1b9dde1af06001770961d Rise of Macedon  359 to 336 BC

army['5fb1b9dde1af06001770961d']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Rise of Macedon  359 to 336 BC',
    id='5fb1b9dde1af06001770961d',
    dateRange={
      startDate=-359,
      endDate=-336,
    },
  },
  g_base_definitions[g_str_5fb1ba27e1af06001770ca7c_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca7c],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca7e],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca80],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca82],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca83_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca83],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca86_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca86],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca89],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca8b],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca8d],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca91],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca94],
  g_base_definitions[g_str_5fb1b9dde1af06001770961d_camp],
  g_base_definitions[g_str_5fb1b9dde1af06001770961d_camp_fortified],
  g_base_definitions[g_str_5fb1b9dde1af06001770961d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af06001770961d"] = army["5fb1b9dde1af06001770961d"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Rise of Macedon  359 to 336 BC"] = army["5fb1b9dde1af06001770961d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Rise of Macedon  359 to 336 BC"] = army["5fb1b9dde1af06001770961d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af06001770961d"] = {}
army_dates["5fb1b9dde1af06001770961d"]["359 BC to 336 BC"] = {
  startDate=-359,
  endDate=-336
}
army_dates["5fb1b9dde1af06001770961d"]["359 BC to 358 BC"] = {
  startDate=-359,
  endDate=-358
}
army_dates["5fb1b9dde1af06001770961d"]["357 BC"] = {
  startDate=-357,
  endDate=-357
}
army_dates["5fb1b9dde1af06001770961d"]["356 BC to 353 BC"] = {
  startDate=-356,
  endDate=-353
}
army_dates["5fb1b9dde1af06001770961d"]["352 BC to 336 BC"] = {
  startDate=-352,
  endDate=-336
}
