g_str_5fb1ba28e1af06001770cbdc_general='5fb1ba28e1af06001770cbdc_general'
g_base_definitions[g_str_5fb1ba28e1af06001770cbdc_general]={
  id=g_str_5fb1ba28e1af06001770cbdc_general,
  name='Knights General',
  min=1,
  max=1,
  description='Macedonian charging horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba28e1af06001770cbdb",
}
g_str_5fb1ba28e1af06001770cbdc='5fb1ba28e1af06001770cbdc'
g_base_definitions[g_str_5fb1ba28e1af06001770cbdc]={
  id=g_str_5fb1ba28e1af06001770cbdc,
  name='Knights',
  min=1,
  max=1,
  description='Macedonian charging horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba28e1af06001770cbdb",
}
g_str_5fb1ba28e1af06001770cbde='5fb1ba28e1af06001770cbde'
g_base_definitions[g_str_5fb1ba28e1af06001770cbde]={
  id=g_str_5fb1ba28e1af06001770cbde,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Paionian, Greek, or Thracian horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba28e1af06001770cbdd",
}
g_str_5fb1ba28e1af06001770cbe0='5fb1ba28e1af06001770cbe0'
g_base_definitions[g_str_5fb1ba28e1af06001770cbe0]={
  id=g_str_5fb1ba28e1af06001770cbe0,
  name='Pikes',
  min=2,
  max=4,
  description='Phalanx',
  troop_type="Pikes",
  troop_option_id="5fb1ba28e1af06001770cbdf",
}
g_str_5fb1ba28e1af06001770cbe3='5fb1ba28e1af06001770cbe3'
g_base_definitions[g_str_5fb1ba28e1af06001770cbe3]={
  id=g_str_5fb1ba28e1af06001770cbe3,
  name='Pikes',
  min=2,
  max=8,
  description='Macedonian Phalanx',
  troop_type="Pikes",
  troop_option_id="5fb1ba28e1af06001770cbe1",
}
g_str_5fb1ba28e1af06001770cbe5='5fb1ba28e1af06001770cbe5'
g_base_definitions[g_str_5fb1ba28e1af06001770cbe5]={
  id=g_str_5fb1ba28e1af06001770cbe5,
  name='Light Foot',
  min=0,
  max=2,
  description='Mercenary Greek foot',
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770cbe4",
}
g_str_5fb1ba28e1af06001770cbe7='5fb1ba28e1af06001770cbe7'
g_base_definitions[g_str_5fb1ba28e1af06001770cbe7]={
  id=g_str_5fb1ba28e1af06001770cbe7,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Greek coastal city hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba28e1af06001770cbe6",
}
g_str_5fb1ba28e1af06001770cbea='5fb1ba28e1af06001770cbea'
g_base_definitions[g_str_5fb1ba28e1af06001770cbea]={
  id=g_str_5fb1ba28e1af06001770cbea,
  name='Skirmishers',
  min=0,
  max=1,
  description='Mercenary skirmishing bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba28e1af06001770cbe9",
}
g_str_5fb1ba28e1af06001770cbec='5fb1ba28e1af06001770cbec'
g_base_definitions[g_str_5fb1ba28e1af06001770cbec]={
  id=g_str_5fb1ba28e1af06001770cbec,
  name='Light Foot',
  min=2,
  max=8,
  description='Thracian peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770cbeb",
}
g_str_5fb1ba28e1af06001770cbee='5fb1ba28e1af06001770cbee'
g_base_definitions[g_str_5fb1ba28e1af06001770cbee]={
  id=g_str_5fb1ba28e1af06001770cbee,
  name='Light Foot',
  min=0,
  max=4,
  description='Illyrian or Paionian javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770cbed",
}
g_str_5fb1ba28e1af06001770cbf1='5fb1ba28e1af06001770cbf1'
g_base_definitions[g_str_5fb1ba28e1af06001770cbf1]={
  id=g_str_5fb1ba28e1af06001770cbf1,
  name='Elephants',
  min=0,
  max=1,
  description='Captured Antigonid war elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba28e1af06001770cbef",
}
g_str_5fb1ba28e1af06001770cbf4='5fb1ba28e1af06001770cbf4'
g_base_definitions[g_str_5fb1ba28e1af06001770cbf4]={
  id=g_str_5fb1ba28e1af06001770cbf4,
  name='Light Foot',
  min=1,
  max=2,
  description='Lykian or Pamphylian vassal javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba28e1af06001770cbf2",
}
g_str_5fb1b9dee1af060017709671_camp='5fb1b9dee1af060017709671_camp'
g_base_definitions[g_str_5fb1b9dee1af060017709671_camp]={
  id=g_str_5fb1b9dee1af060017709671_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dee1af060017709671_camp_fortified='5fb1b9dee1af060017709671_camp_fortified'
g_base_definitions[g_str_5fb1b9dee1af060017709671_camp_fortified]={
  id=g_str_5fb1b9dee1af060017709671_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba0ce1af06001770ab1c='5fb1ba0ce1af06001770ab1c'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab1c]={
  id=g_str_5fb1ba0ce1af06001770ab1c,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='Line horsemen and javelin-armed light horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba0ce1af06001770ab1b",
}
g_str_5fb1ba0ce1af06001770ab1e='5fb1ba0ce1af06001770ab1e'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab1e]={
  id=g_str_5fb1ba0ce1af06001770ab1e,
  name='Pikes',
  min=1,
  max=3,
  description='Phalanx',
  troop_type="Pikes",
  troop_option_id="5fb1ba0ce1af06001770ab1d",
}
g_str_5fb1ba0ce1af06001770ab20='5fb1ba0ce1af06001770ab20'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab20]={
  id=g_str_5fb1ba0ce1af06001770ab20,
  name='Light Foot',
  min=0,
  max=1,
  description='Mercenary Greek peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0ce1af06001770ab1f",
}
g_str_5fb1ba0ce1af06001770ab22='5fb1ba0ce1af06001770ab22'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab22]={
  id=g_str_5fb1ba0ce1af06001770ab22,
  name='Skirmishers',
  min=0,
  max=1,
  description='Asiatic skirmishing bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0ce1af06001770ab21",
}
g_str_5fb1ba0ce1af06001770ab24='5fb1ba0ce1af06001770ab24'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab24]={
  id=g_str_5fb1ba0ce1af06001770ab24,
  name='Light Foot',
  min=0,
  max=1,
  description='Various Anatolian light infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0ce1af06001770ab23",
}
g_str_5fb1ba0ce1af06001770ab26='5fb1ba0ce1af06001770ab26'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab26]={
  id=g_str_5fb1ba0ce1af06001770ab26,
  name='Elephants',
  min=0,
  max=1,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba0ce1af06001770ab25",
}
