-- 5fb1b9e9e1af060017709cfa Early Renaissance German Princes  1494 to 1518 AD

army['5fb1b9e9e1af060017709cfa']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
      'Arable',
    },
    name='Early Renaissance German Princes  1494 to 1518 AD',
    id='5fb1b9e9e1af060017709cfa',
    dateRange={
      startDate=1494,
      endDate=1518,
    },
  },
  g_base_definitions[g_str_615351ac03385c0016b873b1_general],
  g_base_definitions[g_str_615351ac03385c0016b873b1],
  g_base_definitions[g_str_615351ac03385c0016b873b3],
  g_base_definitions[g_str_615351ac03385c0016b873b5],
  g_base_definitions[g_str_615351ac03385c0016b873b7],
  g_base_definitions[g_str_615351ac03385c0016b873b9],
  g_base_definitions[g_str_615351ac03385c0016b873bb],
  g_base_definitions[g_str_615351ac03385c0016b873be],
  g_base_definitions[g_str_615351ac03385c0016b873c1],
  g_base_definitions[g_str_615351ac03385c0016b873c4],
  g_base_definitions[g_str_615351ac03385c0016b873c5_general],
  g_base_definitions[g_str_615351ac03385c0016b873c5],
  g_base_definitions[g_str_615351ac03385c0016b873c8_general],
  g_base_definitions[g_str_615351ac03385c0016b873c8],
  g_base_definitions[g_str_615351ac03385c0016b873ca],
  g_base_definitions[g_str_5fb1b9e9e1af060017709cfa_camp],
  g_base_definitions[g_str_5fb1b9e9e1af060017709cfa_camp_fortified],
  g_base_definitions[g_str_5fb1b9e9e1af060017709cfa_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709cfa"] = army["5fb1b9e9e1af060017709cfa"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Early Renaissance German Princes  1494 to 1518 AD"] = army["5fb1b9e9e1af060017709cfa"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Early Renaissance German Princes  1494 to 1518 AD"] = army["5fb1b9e9e1af060017709cfa"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Renaissance German Princes  1494 to 1518 AD"] = army["5fb1b9e9e1af060017709cfa"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Early Renaissance German Princes  1494 to 1518 AD"] = army["5fb1b9e9e1af060017709cfa"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Renaissance German Princes  1494 to 1518 AD"] = army["5fb1b9e9e1af060017709cfa"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709cfa"] = {}
army_dates["5fb1b9e9e1af060017709cfa"]["1494 AD to 1518 AD"] = {
  startDate=1494,
  endDate=1518
}
