troop_options['615351b303385c0016b88565'] = {
  min=5,
  max=8,
  dateRange={
    startDate=-788,
    endDate=-588,
  }
}
troop_options['615351b303385c0016b88567'] = {
  min=8,
  max=12,
  dateRange={
    startDate=-788,
    endDate=-588,
  }
}
troop_options['615351b303385c0016b88569'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-788,
    endDate=-588,
  }
}
troop_options['615351b303385c0016b8856b'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-788,
    endDate=-588,
  }
}
-- allies
