troop_options['5fb1ba29e1af06001770cec8'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-152,
    endDate=-104,
  }
}
troop_options['5fb1ba29e1af06001770ceca'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-152,
    endDate=-104,
  }
}
troop_options['5fb1ba29e1af06001770cecc'] = {
  min=2,
  max=8,
  dateRange={
    startDate=-152,
    endDate=-104,
  }
}
troop_options['5fb1ba29e1af06001770cece'] = {
  min=0,
  max=5,
  dateRange={
    startDate=-152,
    endDate=-104,
  }
}
troop_options['5fb1ba29e1af06001770ced0'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-152,
    endDate=-104,
  }
}
-- allies
