-- 5fb1b9f0e1af06001770a0c4 Later Tamil Indian  301 to 1370 AD

army['5fb1b9f0e1af06001770a0c4']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      0,
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Later Tamil Indian  301 to 1370 AD',
    id='5fb1b9f0e1af06001770a0c4',
    dateRange={
      startDate=301,
      endDate=1370,
    },
  },
  g_base_definitions[g_str_615351b203385c0016b883d6_general],
  g_base_definitions[g_str_615351b203385c0016b883d6],
  g_base_definitions[g_str_615351b203385c0016b883d9],
  g_base_definitions[g_str_615351b203385c0016b883db],
  g_base_definitions[g_str_615351b203385c0016b883db_elephant_screen],
  g_base_definitions[g_str_615351b203385c0016b883df],
  g_base_definitions[g_str_615351b203385c0016b883e1],
  g_base_definitions[g_str_615351b203385c0016b883e2],
  g_base_definitions[g_str_615351b203385c0016b883e4],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a0c4_camp],
  g_base_definitions[g_str_6153519a03385c0016b84878],
  g_base_definitions[g_str_6153519a03385c0016b8487a],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a0c4"] = army["5fb1b9f0e1af06001770a0c4"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Later Tamil Indian  301 to 1370 AD"] = army["5fb1b9f0e1af06001770a0c4"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Later Tamil Indian  301 to 1370 AD"] = army["5fb1b9f0e1af06001770a0c4"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Later Tamil Indian  301 to 1370 AD"] = army["5fb1b9f0e1af06001770a0c4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Tamil Indian  301 to 1370 AD"] = army["5fb1b9f0e1af06001770a0c4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a0c4"] = {}
army_dates["5fb1b9f0e1af06001770a0c4"]["301 AD to 1370 AD"] = {
  startDate=301,
  endDate=1370
}
army_dates["5fb1b9f0e1af06001770a0c4"]["301 AD to 544 AD"] = {
  startDate=301,
  endDate=544
}
army_dates["5fb1b9f0e1af06001770a0c4"]["545 AD to 641 AD"] = {
  startDate=545,
  endDate=641
}
army_dates["5fb1b9f0e1af06001770a0c4"]["642 AD to 660 AD"] = {
  startDate=642,
  endDate=660
}
army_dates["5fb1b9f0e1af06001770a0c4"]["661 AD to 979 AD"] = {
  startDate=661,
  endDate=979
}
army_dates["5fb1b9f0e1af06001770a0c4"]["980 AD to 1279 AD"] = {
  startDate=980,
  endDate=1279
}
army_dates["5fb1b9f0e1af06001770a0c4"]["1280 AD to 1370 AD"] = {
  startDate=1280,
  endDate=1370
}
