-- 5fb1b9f3e1af06001770a2b7 Khitan Liao  907 to 1125 AD

army['5fb1b9f3e1af06001770a2b7']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Steppe',
      'Arable',
    },
    name='Khitan Liao  907 to 1125 AD',
    id='5fb1b9f3e1af06001770a2b7',
    dateRange={
      startDate=907,
      endDate=1125,
    },
  },
  g_base_definitions[g_str_615351b403385c0016b88a5c_general],
  g_base_definitions[g_str_615351b403385c0016b88a5c],
  g_base_definitions[g_str_615351b403385c0016b88a5e],
  g_base_definitions[g_str_615351b403385c0016b88a60],
  g_base_definitions[g_str_615351b403385c0016b88a62],
  g_base_definitions[g_str_615351b403385c0016b88a64],
  g_base_definitions[g_str_615351b403385c0016b88a66],
  g_base_definitions[g_str_615351b403385c0016b88a67],
  g_base_definitions[g_str_615351b403385c0016b88a69],
  g_base_definitions[g_str_615351b403385c0016b88a6b],
  g_base_definitions[g_str_615351b403385c0016b88a6d],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_fortified],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2b7"] = army["5fb1b9f3e1af06001770a2b7"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Khitan Liao  907 to 1125 AD"] = army["5fb1b9f3e1af06001770a2b7"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Khitan Liao  907 to 1125 AD"] = army["5fb1b9f3e1af06001770a2b7"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Khitan Liao  907 to 1125 AD"] = army["5fb1b9f3e1af06001770a2b7"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2b7"] = {}
army_dates["5fb1b9f3e1af06001770a2b7"]["907 AD to 1125 AD"] = {
  startDate=907,
  endDate=1125
}
army_dates["5fb1b9f3e1af06001770a2b7"]["907 AD to 950 AD"] = {
  startDate=907,
  endDate=950
}
army_dates["5fb1b9f3e1af06001770a2b7"]["951 AD to 979 AD"] = {
  startDate=951,
  endDate=979
}
army_dates["5fb1b9f3e1af06001770a2b7"]["980 AD to 981 AD"] = {
  startDate=980,
  endDate=981
}
army_dates["5fb1b9f3e1af06001770a2b7"]["982 AD to 1120 AD"] = {
  startDate=982,
  endDate=1120
}
army_dates["5fb1b9f3e1af06001770a2b7"]["1121 AD to 1125 AD"] = {
  startDate=1121,
  endDate=1125
}
