-- 5fb1b9d9e1af060017709313 Early Kassites, Nairi, or Hurrians  1779 to 950 BC

army['5fb1b9d9e1af060017709313']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Kassites, Nairi, or Hurrians  1779 to 950 BC',
    id='5fb1b9d9e1af060017709313',
    dateRange={
      startDate=-1779,
      endDate=-950,
    },
  },
  g_base_definitions[g_str_6153519e03385c0016b84f04_general],
  g_base_definitions[g_str_6153519e03385c0016b84f04],
  g_base_definitions[g_str_6153519e03385c0016b84f06_general],
  g_base_definitions[g_str_6153519e03385c0016b84f06],
  g_base_definitions[g_str_6153519e03385c0016b84f07_general],
  g_base_definitions[g_str_6153519e03385c0016b84f07],
  g_base_definitions[g_str_6153519e03385c0016b84f09],
  g_base_definitions[g_str_6153519e03385c0016b84f0c],
  g_base_definitions[g_str_6153519e03385c0016b84f0e],
  g_base_definitions[g_str_6153519e03385c0016b84f10],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709313"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Kassites, Nairi, or Hurrians  1779 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Early Kassites, Nairi, or Hurrians  1779 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Kassites, Nairi, or Hurrians  1779 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709313"] = {}
army_dates["5fb1b9d9e1af060017709313"]["1779 BC to 950 BC"] = {
  startDate=-1779,
  endDate=-950
}
