troop_options['5fb1ba37e1af06001770e6f2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['5fb1ba37e1af06001770e6f6'] = {
  min=7,
  max=12,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['5fb1ba37e1af06001770e6fa'] = {
  min=0,
  max=3,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['5fb1ba37e1af06001770e6fd'] = {
  min=0,
  max=1,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['5fb1ba37e1af06001770e6ff'] = {
  min=0,
  max=1,
  dateRange={
    startDate=961,
    endDate=1054,
  }
}
-- allies
-- 5fb1b9eae1af060017709ddd Rus  860 to 1054 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba37e1af06001770e6f3_general='5fb1ba37e1af06001770e6f3_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general]={
  id=g_str_5fb1ba37e1af06001770e6f3_general,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Druzhina',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry='5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry'
g_str_5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry='5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Druzhina\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Druzhina\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry,
  general=true,
  mobile_infantry=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f3='5fb1ba37e1af06001770e6f3'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3]={
  id=g_str_5fb1ba37e1af06001770e6f3,
  name='Elite Foot',
  min=0,
  max=1,
  description='Druzhina',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry='5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry'
g_str_5fb1ba37e1af06001770e6f3_mounted_mobile_infantry='5fb1ba37e1af06001770e6f3_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry,
  name='Elite Foot',
  min=0,
  max=1,
  description='Druzhina\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba37e1af06001770e6f3_mounted_mobile_infantry,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_mounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f3_mounted_mobile_infantry,
  name='Elite Foot',
  min=0,
  max=1,
  description='Druzhina\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f4_general='5fb1ba37e1af06001770e6f4_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general]={
  id=g_str_5fb1ba37e1af06001770e6f4_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Druzhina',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry='5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry'
g_str_5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry='5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Druzhina\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry,
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Druzhina\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry,
  general=true,
  mobile_infantry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f4='5fb1ba37e1af06001770e6f4'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4]={
  id=g_str_5fb1ba37e1af06001770e6f4,
  name='Bad Horse',
  min=0,
  max=1,
  description='Druzhina',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry='5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry'
g_str_5fb1ba37e1af06001770e6f4_mounted_mobile_infantry='5fb1ba37e1af06001770e6f4_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Druzhina\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba37e1af06001770e6f4_mounted_mobile_infantry,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_mounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f4_mounted_mobile_infantry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Druzhina\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba37e1af06001770e6f2",
}
g_str_5fb1ba37e1af06001770e6f7_general='5fb1ba37e1af06001770e6f7_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general]={
  id=g_str_5fb1ba37e1af06001770e6f7_general,
  name='Spears General',
  min=7,
  max=1,
  description='Spearmen',
  general=true,
  troop_type="Spears",
  troop_option_id="5fb1ba37e1af06001770e6f6",
}
g_str_5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry='5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry'
g_str_5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry='5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry,
  name='Spears General',
  min=0,
  max=1,
  description='Spearmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry,
  general=true,
  troop_type="Spears",
  troop_option_id="5fb1ba37e1af06001770e6f6",
}
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry,
  name='Spears General',
  min=0,
  max=1,
  description='Spearmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry,
  general=true,
  mobile_infantry=true,
  troop_type="Spears",
  troop_option_id="5fb1ba37e1af06001770e6f6",
}
g_str_5fb1ba37e1af06001770e6f7='5fb1ba37e1af06001770e6f7'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7]={
  id=g_str_5fb1ba37e1af06001770e6f7,
  name='Spears',
  min=7,
  max=12,
  description='Spearmen',
  troop_type="Spears",
  troop_option_id="5fb1ba37e1af06001770e6f6",
}
g_str_5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry='5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry'
g_str_5fb1ba37e1af06001770e6f7_mounted_mobile_infantry='5fb1ba37e1af06001770e6f7_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry,
  name='Spears',
  min=0,
  max=5,
  description='Spearmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba37e1af06001770e6f7_mounted_mobile_infantry,
  troop_type="Spears",
  troop_option_id="5fb1ba37e1af06001770e6f6",
}
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_mounted_mobile_infantry]={
  id=g_str_5fb1ba37e1af06001770e6f7_mounted_mobile_infantry,
  name='Spears',
  min=0,
  max=5,
  description='Spearmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Spears",
  troop_option_id="5fb1ba37e1af06001770e6f6",
}
g_str_5fb1ba37e1af06001770e6fb='5fb1ba37e1af06001770e6fb'
g_base_definitions[g_str_5fb1ba37e1af06001770e6fb]={
  id=g_str_5fb1ba37e1af06001770e6fb,
  name='Skirmishers',
  min=0,
  max=3,
  description='Bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba37e1af06001770e6fa",
}
g_str_5fb1ba37e1af06001770e6fe='5fb1ba37e1af06001770e6fe'
g_base_definitions[g_str_5fb1ba37e1af06001770e6fe]={
  id=g_str_5fb1ba37e1af06001770e6fe,
  name='Light Foot',
  min=0,
  max=1,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba37e1af06001770e6fd",
}
g_str_5fb1ba37e1af06001770e701='5fb1ba37e1af06001770e701'
g_base_definitions[g_str_5fb1ba37e1af06001770e701]={
  id=g_str_5fb1ba37e1af06001770e701,
  name='Horse Bow',
  min=0,
  max=1,
  description='Alan, Turk, or Bulgar mercenary horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba37e1af06001770e6ff",
}
g_str_5fb1b9eae1af060017709ddd_camp='5fb1b9eae1af060017709ddd_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp]={
  id=g_str_5fb1b9eae1af060017709ddd_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9eae1af060017709ddd_camp_pack_train='5fb1b9eae1af060017709ddd_camp_pack_train'
g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp_pack_train]={
  id=g_str_5fb1b9eae1af060017709ddd_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9eae1af060017709ddd']={
  data={
    name='Rus  860 to 1054 AD',
    id='5fb1b9eae1af060017709ddd',
    army_id='5fb1b9eae1af060017709ddd'
  },
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fb],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fe],
  g_base_definitions[g_str_5fb1ba37e1af06001770e701],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709ddd"] = army["5fb1b9eae1af060017709ddd"]
army['5fb1b9eae1af060017709ddd_860_960']={
  data={
    name='Rus 860 AD to 960 AD',
    id='5fb1b9eae1af060017709ddd_860_960',
    army_id='5fb1b9eae1af060017709ddd'
  },
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fb],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fe],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp_pack_train],
}
army['5fb1b9eae1af060017709ddd_961_1054']={
  data={
    name='Rus 961 AD to 1054 AD',
    id='5fb1b9eae1af060017709ddd_961_1054',
    army_id='5fb1b9eae1af060017709ddd'
  },
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fb],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fe],
  g_base_definitions[g_str_5fb1ba37e1af06001770e701],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp_pack_train],
}
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709ddd"] = {}
army_dates["5fb1b9eae1af060017709ddd"]["860 AD to 1054 AD"] ="5fb1b9eae1af060017709ddd"
army_dates["5fb1b9eae1af060017709ddd"]["860 AD to 960 AD"] ="5fb1b9eae1af060017709ddd_860_960"
army_dates["5fb1b9eae1af060017709ddd"]["961 AD to 1054 AD"] ="5fb1b9eae1af060017709ddd_961_1054"
