-- 5fb1b9f6e1af06001770a452 Fiji, Samoa, or Tonga  1100 to 1785 AD

army['5fb1b9f6e1af06001770a452']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Forest',
    },
    name='Fiji, Samoa, or Tonga  1100 to 1785 AD',
    id='5fb1b9f6e1af06001770a452',
    dateRange={
      startDate=1100,
      endDate=1785,
    }
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fe42_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe42],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe44],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a452_camp],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a452_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a452"] = army["5fb1b9f6e1af06001770a452"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Fiji, Samoa, or Tonga  1100 to 1785 AD"] = army["5fb1b9f6e1af06001770a452"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Fiji, Samoa, or Tonga  1100 to 1785 AD"] = army["5fb1b9f6e1af06001770a452"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a452"] = {}
army_dates["5fb1b9f6e1af06001770a452"]["1100 AD to 1785 AD"] = {
  startDate=1100,
  endDate=1785
}
