troop_options['615351ae03385c0016b87942'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b87944'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b87946'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b87948'] = {
  min=1,
  max=3,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b8794a'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b8794c'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b8794e'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b87950'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b87953'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b87955'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b87958'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
troop_options['615351ae03385c0016b8795b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1068,
    endDate=1071,
  }
}
-- allies
