-- 5fb1b9dde1af060017709640 Thracian Hill Tribes  700 BC to 46 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba28e1af06001770cb19']= {
  min=0,
  max=1,
  description='Horsemen',
}
g_troop_entry['5fb1ba28e1af06001770cb1a']= {
  troop_option='5fb1ba28e1af06001770cb19',
  troopTypeCode='JCV',
}
g_troop_option['5fb1ba28e1af06001770cb1b']= {
  min=6,
  max=15,
  description='Peltasts',
  core='all',
}
g_troop_entry['5fb1ba28e1af06001770cb1c']= {
  troop_option='5fb1ba28e1af06001770cb1b',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba28e1af06001770cb1d']= {
  min=0,
  max=2,
  description='Peltasts armed with long spear',
}
g_troop_entry['5fb1ba28e1af06001770cb1e']= {
  troop_option='5fb1ba28e1af06001770cb1d',
  troopTypeCode='LSP',
}
g_troop_option['5fb1ba28e1af06001770cb1f']= {
  min=1,
  max=4,
  description='Skirmishing bowmen or slingers',
}
g_troop_entry['5fb1ba28e1af06001770cb20']= {
  troop_option='5fb1ba28e1af06001770cb1f',
  troopTypeCode='SKM',
}
g_troop_option['5fb1ba28e1af06001770cb21']= {
  min=0,
  max=4,
  description='Gymnetes (naked men armed with javelins or stones)',
}
g_troop_entry['5fb1ba28e1af06001770cb22']= {
  troop_option='5fb1ba28e1af06001770cb21',
  troopTypeCode='RBL',
}
g_str_5fb1ba28e1af06001770cb1a_general='5fb1ba28e1af06001770cb1a_general'
g_base_definitions[g_str_5fb1ba28e1af06001770cb1a_general]={
  id=g_str_5fb1ba28e1af06001770cb1a_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba28e1af06001770cb1a='5fb1ba28e1af06001770cb1a'
g_base_definitions[g_str_5fb1ba28e1af06001770cb1a]={
  id=g_str_5fb1ba28e1af06001770cb1a,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba28e1af06001770cb1c_general='5fb1ba28e1af06001770cb1c_general'
g_base_definitions[g_str_5fb1ba28e1af06001770cb1c_general]={
  id=g_str_5fb1ba28e1af06001770cb1c_general,
  name='Light Foot General',
  min=6,
  max=1,
  description='Peltasts',
  general=true,
  troop_type="Light Foot",
}
g_str_5fb1ba28e1af06001770cb1c='5fb1ba28e1af06001770cb1c'
g_base_definitions[g_str_5fb1ba28e1af06001770cb1c]={
  id=g_str_5fb1ba28e1af06001770cb1c,
  name='Light Foot',
  min=6,
  max=15,
  description='Peltasts',
  troop_type="Light Foot",
}
g_str_5fb1ba28e1af06001770cb1e='5fb1ba28e1af06001770cb1e'
g_base_definitions[g_str_5fb1ba28e1af06001770cb1e]={
  id=g_str_5fb1ba28e1af06001770cb1e,
  name='Light Spear',
  min=0,
  max=2,
  description='Peltasts armed with long spear',
  troop_type="Light Spear",
}
g_str_5fb1ba28e1af06001770cb20_general='5fb1ba28e1af06001770cb20_general'
g_base_definitions[g_str_5fb1ba28e1af06001770cb20_general]={
  id=g_str_5fb1ba28e1af06001770cb20_general,
  name='Skirmishers General',
  min=1,
  max=1,
  description='Skirmishing bowmen or slingers',
  general=true,
  troop_type="Skirmishers",
}
g_str_5fb1ba28e1af06001770cb20='5fb1ba28e1af06001770cb20'
g_base_definitions[g_str_5fb1ba28e1af06001770cb20]={
  id=g_str_5fb1ba28e1af06001770cb20,
  name='Skirmishers',
  min=1,
  max=4,
  description='Skirmishing bowmen or slingers',
  troop_type="Skirmishers",
}
g_str_5fb1ba28e1af06001770cb22='5fb1ba28e1af06001770cb22'
g_base_definitions[g_str_5fb1ba28e1af06001770cb22]={
  id=g_str_5fb1ba28e1af06001770cb22,
  name='Rabble',
  min=0,
  max=4,
  description='Gymnetes (naked men armed with javelins or stones)',
  troop_type="Rabble",
}
g_str_5fb1b9dde1af060017709640_camp='5fb1b9dde1af060017709640_camp'
g_base_definitions[g_str_5fb1b9dde1af060017709640_camp]={
  id=g_str_5fb1b9dde1af060017709640_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dde1af060017709640_camp_fortified='5fb1b9dde1af060017709640_camp_fortified'
g_base_definitions[g_str_5fb1b9dde1af060017709640_camp_fortified]={
  id=g_str_5fb1b9dde1af060017709640_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
army['5fb1b9dde1af060017709640']={
  data={
    name='Thracian Hill Tribes  700 BC to 46 AD',
    id='5fb1b9dde1af060017709640',
    army_id='5fb1b9dde1af060017709640'
  },
  g_base_definitions[g_str_5fb1ba28e1af06001770cb1a_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb1a],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb1c_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb1c],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb1e],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb20_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb20],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb22],
  g_base_definitions[g_str_5fb1b9dde1af060017709640_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709640_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af060017709640"] = army["5fb1b9dde1af060017709640"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Thracian Hill Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709640"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Thracian Hill Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709640"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Thracian Hill Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709640"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Thracian Hill Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709640"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Thracian Hill Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709640"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af060017709640"] = {}
army_dates["5fb1b9dde1af060017709640"]["700 BC to 46 AD"] ="5fb1b9dde1af060017709640"
