g_str_5fb1ba41e1af06001770f9f4_general='5fb1ba41e1af06001770f9f4_general'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f4_general]={
  id=g_str_5fb1ba41e1af06001770f9f4_general,
  name='Elite Cavalry General',
  min=1,
  max=1,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  general=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9f3",
}
g_str_5fb1ba41e1af06001770f9f4='5fb1ba41e1af06001770f9f4'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f4]={
  id=g_str_5fb1ba41e1af06001770f9f4,
  name='Elite Cavalry',
  min=1,
  max=3,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9f3",
}
g_str_5fb1ba41e1af06001770f9f6='5fb1ba41e1af06001770f9f6'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f6]={
  id=g_str_5fb1ba41e1af06001770f9f6,
  name='Horse Bow',
  min=1,
  max=4,
  description='Khitan ordo foragers and orderlies',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f5",
}
g_str_5fb1ba41e1af06001770f9f8='5fb1ba41e1af06001770f9f8'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f8]={
  id=g_str_5fb1ba41e1af06001770f9f8,
  name='Horse Bow',
  min=1,
  max=2,
  description='Khitan tribal horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f7",
}
g_str_5fb1ba41e1af06001770f9fa='5fb1ba41e1af06001770f9fa'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fa]={
  id=g_str_5fb1ba41e1af06001770f9fa,
  name='Horse Bow',
  min=0,
  max=2,
  description='Jurchen prisoner fierce sacrificial vanguard horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f9",
}
g_str_5fb1ba41e1af06001770f9fc='5fb1ba41e1af06001770f9fc'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fc]={
  id=g_str_5fb1ba41e1af06001770f9fc,
  name='Horde',
  min=0,
  max=5,
  description='Chinese militia levy',
  troop_type="Horde",
  troop_option_id="5fb1ba41e1af06001770f9fb",
}
g_str_5fb1ba41e1af06001770f9fe='5fb1ba41e1af06001770f9fe'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fe]={
  id=g_str_5fb1ba41e1af06001770f9fe,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Chinese swordsmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba41e1af06001770f9fd",
}
g_str_5fb1ba41e1af06001770f9ff='5fb1ba41e1af06001770f9ff'
g_base_definitions[g_str_5fb1ba41e1af06001770f9ff]={
  id=g_str_5fb1ba41e1af06001770f9ff,
  name='Raiders',
  min=1,
  max=2,
  description='Chinese swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba41e1af06001770f9fd",
}
g_str_5fb1ba41e1af06001770fa01='5fb1ba41e1af06001770fa01'
g_base_definitions[g_str_5fb1ba41e1af06001770fa01]={
  id=g_str_5fb1ba41e1af06001770fa01,
  name='Bow Levy',
  min=1,
  max=2,
  description='Chinese crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba41e1af06001770fa00",
}
g_str_5fb1ba41e1af06001770fa03='5fb1ba41e1af06001770fa03'
g_base_definitions[g_str_5fb1ba41e1af06001770fa03]={
  id=g_str_5fb1ba41e1af06001770fa03,
  name='Bad Horse',
  min=0,
  max=1,
  description='Chinese horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa02",
}
g_str_5fb1ba41e1af06001770fa05='5fb1ba41e1af06001770fa05'
g_base_definitions[g_str_5fb1ba41e1af06001770fa05]={
  id=g_str_5fb1ba41e1af06001770fa05,
  name='Artillery',
  min=0,
  max=1,
  description='Chinese stone-throwers and bolt-shooters',
  troop_type="Artillery",
  troop_option_id="5fb1ba41e1af06001770fa04",
}
g_str_5fb1b9f3e1af06001770a2b7_camp='5fb1b9f3e1af06001770a2b7_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b7_camp_fortified='5fb1b9f3e1af06001770a2b7_camp_fortified'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_fortified]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train='5fb1b9f3e1af06001770a2b7_camp_pack_train'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba41e1af06001770f9f4_general='5fb1ba41e1af06001770f9f4_general'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f4_general]={
  id=g_str_5fb1ba41e1af06001770f9f4_general,
  name='Elite Cavalry General',
  min=1,
  max=1,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  general=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9f3",
}
g_str_5fb1ba41e1af06001770f9f4='5fb1ba41e1af06001770f9f4'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f4]={
  id=g_str_5fb1ba41e1af06001770f9f4,
  name='Elite Cavalry',
  min=1,
  max=3,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9f3",
}
g_str_5fb1ba41e1af06001770f9f6='5fb1ba41e1af06001770f9f6'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f6]={
  id=g_str_5fb1ba41e1af06001770f9f6,
  name='Horse Bow',
  min=1,
  max=4,
  description='Khitan ordo foragers and orderlies',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f5",
}
g_str_5fb1ba41e1af06001770f9f8='5fb1ba41e1af06001770f9f8'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f8]={
  id=g_str_5fb1ba41e1af06001770f9f8,
  name='Horse Bow',
  min=1,
  max=2,
  description='Khitan tribal horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f7",
}
g_str_5fb1ba41e1af06001770f9fa='5fb1ba41e1af06001770f9fa'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fa]={
  id=g_str_5fb1ba41e1af06001770f9fa,
  name='Horse Bow',
  min=0,
  max=2,
  description='Jurchen prisoner fierce sacrificial vanguard horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f9",
}
g_str_5fb1ba41e1af06001770f9fc='5fb1ba41e1af06001770f9fc'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fc]={
  id=g_str_5fb1ba41e1af06001770f9fc,
  name='Horde',
  min=0,
  max=5,
  description='Chinese militia levy',
  troop_type="Horde",
  troop_option_id="5fb1ba41e1af06001770f9fb",
}
g_str_5fb1ba41e1af06001770f9fe='5fb1ba41e1af06001770f9fe'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fe]={
  id=g_str_5fb1ba41e1af06001770f9fe,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Chinese swordsmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba41e1af06001770f9fd",
}
g_str_5fb1ba41e1af06001770f9ff='5fb1ba41e1af06001770f9ff'
g_base_definitions[g_str_5fb1ba41e1af06001770f9ff]={
  id=g_str_5fb1ba41e1af06001770f9ff,
  name='Raiders',
  min=1,
  max=2,
  description='Chinese swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba41e1af06001770f9fd",
}
g_str_5fb1ba41e1af06001770fa01='5fb1ba41e1af06001770fa01'
g_base_definitions[g_str_5fb1ba41e1af06001770fa01]={
  id=g_str_5fb1ba41e1af06001770fa01,
  name='Bow Levy',
  min=1,
  max=2,
  description='Chinese crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba41e1af06001770fa00",
}
g_str_5fb1ba41e1af06001770fa03='5fb1ba41e1af06001770fa03'
g_base_definitions[g_str_5fb1ba41e1af06001770fa03]={
  id=g_str_5fb1ba41e1af06001770fa03,
  name='Bad Horse',
  min=0,
  max=1,
  description='Chinese horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa02",
}
g_str_5fb1ba41e1af06001770fa05='5fb1ba41e1af06001770fa05'
g_base_definitions[g_str_5fb1ba41e1af06001770fa05]={
  id=g_str_5fb1ba41e1af06001770fa05,
  name='Artillery',
  min=0,
  max=1,
  description='Chinese stone-throwers and bolt-shooters',
  troop_type="Artillery",
  troop_option_id="5fb1ba41e1af06001770fa04",
}
g_str_5fb1b9f3e1af06001770a2b7_camp='5fb1b9f3e1af06001770a2b7_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b7_camp_fortified='5fb1b9f3e1af06001770a2b7_camp_fortified'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_fortified]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train='5fb1b9f3e1af06001770a2b7_camp_pack_train'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba41e1af06001770f9f4_general='5fb1ba41e1af06001770f9f4_general'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f4_general]={
  id=g_str_5fb1ba41e1af06001770f9f4_general,
  name='Elite Cavalry General',
  min=1,
  max=1,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  general=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9f3",
}
g_str_5fb1ba41e1af06001770f9f4='5fb1ba41e1af06001770f9f4'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f4]={
  id=g_str_5fb1ba41e1af06001770f9f4,
  name='Elite Cavalry',
  min=1,
  max=3,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9f3",
}
g_str_5fb1ba41e1af06001770f9f6='5fb1ba41e1af06001770f9f6'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f6]={
  id=g_str_5fb1ba41e1af06001770f9f6,
  name='Horse Bow',
  min=1,
  max=4,
  description='Khitan ordo foragers and orderlies',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f5",
}
g_str_5fb1ba41e1af06001770f9f8='5fb1ba41e1af06001770f9f8'
g_base_definitions[g_str_5fb1ba41e1af06001770f9f8]={
  id=g_str_5fb1ba41e1af06001770f9f8,
  name='Horse Bow',
  min=1,
  max=2,
  description='Khitan tribal horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f7",
}
g_str_5fb1ba41e1af06001770f9fa='5fb1ba41e1af06001770f9fa'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fa]={
  id=g_str_5fb1ba41e1af06001770f9fa,
  name='Horse Bow',
  min=0,
  max=2,
  description='Jurchen prisoner fierce sacrificial vanguard horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9f9",
}
g_str_5fb1ba41e1af06001770f9fc='5fb1ba41e1af06001770f9fc'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fc]={
  id=g_str_5fb1ba41e1af06001770f9fc,
  name='Horde',
  min=0,
  max=5,
  description='Chinese militia levy',
  troop_type="Horde",
  troop_option_id="5fb1ba41e1af06001770f9fb",
}
g_str_5fb1ba41e1af06001770f9fe='5fb1ba41e1af06001770f9fe'
g_base_definitions[g_str_5fb1ba41e1af06001770f9fe]={
  id=g_str_5fb1ba41e1af06001770f9fe,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Chinese swordsmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba41e1af06001770f9fd",
}
g_str_5fb1ba41e1af06001770f9ff='5fb1ba41e1af06001770f9ff'
g_base_definitions[g_str_5fb1ba41e1af06001770f9ff]={
  id=g_str_5fb1ba41e1af06001770f9ff,
  name='Raiders',
  min=1,
  max=2,
  description='Chinese swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba41e1af06001770f9fd",
}
g_str_5fb1ba41e1af06001770fa01='5fb1ba41e1af06001770fa01'
g_base_definitions[g_str_5fb1ba41e1af06001770fa01]={
  id=g_str_5fb1ba41e1af06001770fa01,
  name='Bow Levy',
  min=1,
  max=2,
  description='Chinese crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba41e1af06001770fa00",
}
g_str_5fb1ba41e1af06001770fa03='5fb1ba41e1af06001770fa03'
g_base_definitions[g_str_5fb1ba41e1af06001770fa03]={
  id=g_str_5fb1ba41e1af06001770fa03,
  name='Bad Horse',
  min=0,
  max=1,
  description='Chinese horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa02",
}
g_str_5fb1ba41e1af06001770fa05='5fb1ba41e1af06001770fa05'
g_base_definitions[g_str_5fb1ba41e1af06001770fa05]={
  id=g_str_5fb1ba41e1af06001770fa05,
  name='Artillery',
  min=0,
  max=1,
  description='Chinese stone-throwers and bolt-shooters',
  troop_type="Artillery",
  troop_option_id="5fb1ba41e1af06001770fa04",
}
g_str_5fb1b9f3e1af06001770a2b7_camp='5fb1b9f3e1af06001770a2b7_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b7_camp_fortified='5fb1b9f3e1af06001770a2b7_camp_fortified'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_fortified]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train='5fb1b9f3e1af06001770a2b7_camp_pack_train'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train]={
  id=g_str_5fb1b9f3e1af06001770a2b7_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
