-- 5fb1b9f3e1af06001770a2d4 Jurchen Jin  1126 to 1199 AD

army['5fb1b9f3e1af06001770a2d4']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
      'Arable',
    },
    name='Jurchen Jin  1126 to 1199 AD',
    id='5fb1b9f3e1af06001770a2d4',
    dateRange={
      startDate=1126,
      endDate=1199,
    }
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770fa74_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa74],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa76],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa78_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa78],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa79],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa7b],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2d4_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2d4_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2d4"] = army["5fb1b9f3e1af06001770a2d4"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Jurchen Jin  1126 to 1199 AD"] = army["5fb1b9f3e1af06001770a2d4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Jurchen Jin  1126 to 1199 AD"] = army["5fb1b9f3e1af06001770a2d4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2d4"] = {}
army_dates["5fb1b9f3e1af06001770a2d4"]["1126 AD to 1199 AD"] = {
  startDate=1126,
  endDate=1199
}
army_dates["5fb1b9f3e1af06001770a2d4"]["1126 AD"] = {
  startDate=1126,
  endDate=1126
}
army_dates["5fb1b9f3e1af06001770a2d4"]["1127 AD to 1129 AD"] = {
  startDate=1127,
  endDate=1129
}
army_dates["5fb1b9f3e1af06001770a2d4"]["1130 AD to 1152 AD"] = {
  startDate=1130,
  endDate=1152
}
army_dates["5fb1b9f3e1af06001770a2d4"]["1153 AD to 1199 AD"] = {
  startDate=1153,
  endDate=1199
}
