-- 5fb1b9f6e1af06001770a476 Quechua or Aymara  1200 to 1540 AD

army['5fb1b9f6e1af06001770a476']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
      'Dry',
    },
    name='Quechua or Aymara  1200 to 1540 AD',
    id='5fb1b9f6e1af06001770a476',
    dateRange={
      startDate=1200,
      endDate=1540,
    },
  },
  g_base_definitions[g_str_615351b703385c0016b88edf],
  g_base_definitions[g_str_615351b703385c0016b88ee1],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a476_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a476"] = army["5fb1b9f6e1af06001770a476"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Quechua or Aymara  1200 to 1540 AD"] = army["5fb1b9f6e1af06001770a476"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Quechua or Aymara  1200 to 1540 AD"] = army["5fb1b9f6e1af06001770a476"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a476"] = {}
army_dates["5fb1b9f6e1af06001770a476"]["1200 AD to 1540 AD"] = {
  startDate=1200,
  endDate=1540
}
