-- 5fb1b9eae1af060017709dd4 Medieval Swedish  1391 to 1523 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba37e1af06001770e6e0_general='5fb1ba37e1af06001770e6e0_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_general]={
  id=g_str_5fb1ba37e1af06001770e6e0_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Fraelse and Smaasvenner',
  general=true,
}
g_str_5fb1ba37e1af06001770e6e0_general_dismounted='5fb1ba37e1af06001770e6e0_general_dismounted'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_general_dismounted]={
  id=g_str_5fb1ba37e1af06001770e6e0_general_dismounted,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Fraelse and Smaasvenner\nDeployment dismounted from Bad Horse General',
  points=4,
  general=true,
}
g_5fb1ba37e1af06001770e6e0_general_dismounted=g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_general_dismounted]
g_str_5fb1ba37e1af06001770e6e0_general_mounted='5fb1ba37e1af06001770e6e0_general_mounted'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_general_mounted]={
  id=g_str_5fb1ba37e1af06001770e6e0_general_mounted,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Fraelse and Smaasvenner\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba37e1af06001770e6e0_general_dismounted,
  general=true,
}
g_str_5fb1ba37e1af06001770e6e0='5fb1ba37e1af06001770e6e0'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e0]={
  id=g_str_5fb1ba37e1af06001770e6e0,
  name='Bad Horse',
  min=0,
  max=2,
  description='Fraelse and Smaasvenner',
}
g_str_5fb1ba37e1af06001770e6e0_dismounted='5fb1ba37e1af06001770e6e0_dismounted'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_dismounted]={
  id=g_str_5fb1ba37e1af06001770e6e0_dismounted,
  name='Elite Foot',
  min=0,
  max=2,
  description='Fraelse and Smaasvenner\nDeployment dismounted from Bad Horse',
  points=4,
}
g_5fb1ba37e1af06001770e6e0_dismounted=g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_dismounted]
g_str_5fb1ba37e1af06001770e6e0_mounted='5fb1ba37e1af06001770e6e0_mounted'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_mounted]={
  id=g_str_5fb1ba37e1af06001770e6e0_mounted,
  name='Bad Horse',
  min=0,
  max=2,
  description='Fraelse and Smaasvenner\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba37e1af06001770e6e0_dismounted,
}
g_str_5fb1ba37e1af06001770e6e3_general='5fb1ba37e1af06001770e6e3_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e3_general]={
  id=g_str_5fb1ba37e1af06001770e6e3_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Skyttar armored crossbowmen on horses',
  general=true,
}
g_str_5fb1ba37e1af06001770e6e3='5fb1ba37e1af06001770e6e3'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e3]={
  id=g_str_5fb1ba37e1af06001770e6e3,
  name='Bad Horse',
  min=0,
  max=1,
  description='Skyttar armored crossbowmen on horses',
}
g_str_5fb1ba37e1af06001770e6e5_general='5fb1ba37e1af06001770e6e5_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e5_general]={
  id=g_str_5fb1ba37e1af06001770e6e5_general,
  name='Elite Foot General',
  min=3,
  max=1,
  description='Allmoge peasant infantry armed with mixed polearms',
  general=true,
}
g_str_5fb1ba37e1af06001770e6e5='5fb1ba37e1af06001770e6e5'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e5]={
  id=g_str_5fb1ba37e1af06001770e6e5,
  name='Elite Foot',
  min=3,
  max=6,
  description='Allmoge peasant infantry armed with mixed polearms',
}
g_str_5fb1ba37e1af06001770e6e8='5fb1ba37e1af06001770e6e8'
g_base_definitions[g_str_5fb1ba37e1af06001770e6e8]={
  id=g_str_5fb1ba37e1af06001770e6e8,
  name='Archers',
  min=3,
  max=6,
  description='Allmoge peasant crossbowmen',
}
g_str_5fb1ba37e1af06001770e6eb='5fb1ba37e1af06001770e6eb'
g_base_definitions[g_str_5fb1ba37e1af06001770e6eb]={
  id=g_str_5fb1ba37e1af06001770e6eb,
  name='Skirmishers',
  min=0,
  max=1,
  description='Handgunners',
}
g_str_5fb1ba37e1af06001770e6ed='5fb1ba37e1af06001770e6ed'
g_base_definitions[g_str_5fb1ba37e1af06001770e6ed]={
  id=g_str_5fb1ba37e1af06001770e6ed,
  name='Light Foot',
  min=0,
  max=1,
  description='Finnish infantry',
}
g_str_5fb1b9eae1af060017709dd4_camp='5fb1b9eae1af060017709dd4_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709dd4_camp]={
  name='Camp',
  id=g_str_5fb1b9eae1af060017709dd4_camp,
  min=1,
  max=1,
}
army['5fb1b9eae1af060017709dd4']={
  data={
    name='Medieval Swedish  1391 to 1523 AD'
  },
  g_base_definitions[g_str_5fb1b9eae1af060017709dd4_camp],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6ef],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f0],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_general_mounted],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_general_dismounted],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e0],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_mounted],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e0_dismounted],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e3_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e3],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e5_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e5],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6e8],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6eb],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6ed],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dd4"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
