-- 5fb1b9ede1af060017709f47 Other Dynastic Bedouin  890 to 1150 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3ae1af06001770ed25_general='5fb1ba3ae1af06001770ed25_general'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed25_general]={
  id=g_str_5fb1ba3ae1af06001770ed25_general,
  name='Javelin Cavalry General',
  min=6,
  max=1,
  description='Bedouin "Arabitai"',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba3ae1af06001770ed25='5fb1ba3ae1af06001770ed25'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed25]={
  id=g_str_5fb1ba3ae1af06001770ed25,
  name='Javelin Cavalry',
  min=6,
  max=12,
  description='Bedouin "Arabitai"',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba3ae1af06001770ed27='5fb1ba3ae1af06001770ed27'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed27]={
  id=g_str_5fb1ba3ae1af06001770ed27,
  name='Skirmishers',
  min=0,
  max=2,
  description='Bedouin skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba3ae1af06001770ed29='5fb1ba3ae1af06001770ed29'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed29]={
  id=g_str_5fb1ba3ae1af06001770ed29,
  name='Bad Horse',
  min=0,
  max=1,
  description='Bedouin camel-mounted scouts',
  troop_type="Bad Horse",
}
g_str_5fb1ba3ae1af06001770ed29_light_camelry='5fb1ba3ae1af06001770ed29_light_camelry'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed29_light_camelry]={
  id=g_str_5fb1ba3ae1af06001770ed29_light_camelry,
  name='Bad Horse Light camelry',
  min=0,
  max=1,
  description='Bedouin camel-mounted scouts\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
}
g_str_5fb1ba3ae1af06001770ed2c='5fb1ba3ae1af06001770ed2c'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed2c]={
  id=g_str_5fb1ba3ae1af06001770ed2c,
  name='Horde',
  min=0,
  max=2,
  description='Ahdath militia',
  troop_type="Horde",
}
g_str_5fb1ba3ae1af06001770ed2f='5fb1ba3ae1af06001770ed2f'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed2f]={
  id=g_str_5fb1ba3ae1af06001770ed2f,
  name='Horde',
  min=0,
  max=2,
  description='Syrian peasants',
  troop_type="Horde",
}
g_str_5fb1b9ede1af060017709f47_camp='5fb1b9ede1af060017709f47_camp'
g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp]={
  id=g_str_5fb1b9ede1af060017709f47_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ede1af060017709f47_camp_pack_train='5fb1b9ede1af060017709f47_camp_pack_train'
g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp_pack_train]={
  id=g_str_5fb1b9ede1af060017709f47_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9ede1af060017709f47']={
  data={
    name='Other Dynastic Bedouin  890 to 1150 AD'
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed25_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed25],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed27],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed29],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed29_light_camelry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed2c],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed2f],
  g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f47"] = army["5fb1b9ede1af060017709f47"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Other Dynastic Bedouin  890 to 1150 AD"] = army["5fb1b9ede1af060017709f47"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Other Dynastic Bedouin  890 to 1150 AD"] = army["5fb1b9ede1af060017709f47"]
