-- 5fb1b9e3e1af060017709995 Alföld Early Lombard  489 to 567 AD

army['5fb1b9e3e1af060017709995']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Alföld Early Lombard  489 to 567 AD',
    id='5fb1b9e3e1af060017709995',
    dateRange={
      startDate=489,
      endDate=567,
    }
  },
  g_base_definitions[g_str_5fb1ba2ee1af06001770d751_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d751_general_mounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d751_general_dismounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d751],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d751_mounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d751_dismounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d754],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d756],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d758],
  g_base_definitions[g_str_5fb1b9e3e1af060017709995_camp],
  g_base_definitions[g_str_5fb1b9e3e1af060017709995_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af060017709995"] = army["5fb1b9e3e1af060017709995"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Alföld Early Lombard  489 to 567 AD"] = army["5fb1b9e3e1af060017709995"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Alföld Early Lombard  489 to 567 AD"] = army["5fb1b9e3e1af060017709995"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Alföld Early Lombard  489 to 567 AD"] = army["5fb1b9e3e1af060017709995"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af060017709995"] = {}
army_dates["5fb1b9e3e1af060017709995"]["489 AD to 567 AD"] = {
  startDate=489,
  endDate=567
}
army_dates["5fb1b9e3e1af060017709995"]["489 AD to 495 AD"] = {
  startDate=489,
  endDate=495
}
army_dates["5fb1b9e3e1af060017709995"]["496 AD to 525 AD"] = {
  startDate=496,
  endDate=525
}
army_dates["5fb1b9e3e1af060017709995"]["526 AD to 552 AD"] = {
  startDate=526,
  endDate=552
}
army_dates["5fb1b9e3e1af060017709995"]["553 AD to 557 AD"] = {
  startDate=553,
  endDate=557
}
army_dates["5fb1b9e3e1af060017709995"]["558 AD to 561 AD"] = {
  startDate=558,
  endDate=561
}
army_dates["5fb1b9e3e1af060017709995"]["562 AD to 567 AD"] = {
  startDate=562,
  endDate=567
}
