-- 5fb1b9ede1af060017709fc1 Khwarizmian  1186 to 1246 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3be1af06001770ef07='5fb1ba3be1af06001770ef07'
g_base_definitions[g_str_5fb1ba3be1af06001770ef07]={
  id=g_str_5fb1ba3be1af06001770ef07,
  name='Elite Cavalary',
  min=1,
  max=3,
  description='Khwarizmian lancers',
}
g_str_5fb1ba3be1af06001770ef0b='5fb1ba3be1af06001770ef0b'
g_base_definitions[g_str_5fb1ba3be1af06001770ef0b]={
  id=g_str_5fb1ba3be1af06001770ef0b,
  name='Horse Bow',
  min=3,
  max=7,
  description='Qangli and similar horse archers',
}
g_str_5fb1ba3be1af06001770ef0f='5fb1ba3be1af06001770ef0f'
g_base_definitions[g_str_5fb1ba3be1af06001770ef0f]={
  id=g_str_5fb1ba3be1af06001770ef0f,
  name='Elite Cavalary',
  min=1,
  max=1,
  description='Kurdish horsemen',
}
g_str_5fb1ba3be1af06001770ef12='5fb1ba3be1af06001770ef12'
g_base_definitions[g_str_5fb1ba3be1af06001770ef12]={
  id=g_str_5fb1ba3be1af06001770ef12,
  name='Bow Levy',
  min=1,
  max=2,
  description='Militia bowmen',
}
g_str_5fb1ba3be1af06001770ef15='5fb1ba3be1af06001770ef15'
g_base_definitions[g_str_5fb1ba3be1af06001770ef15]={
  id=g_str_5fb1ba3be1af06001770ef15,
  name='Horde',
  min=0,
  max=2,
  description='Persian or Tajik levy foot or armed slaves',
}
g_str_5fb1ba3be1af06001770ef17='5fb1ba3be1af06001770ef17'
g_base_definitions[g_str_5fb1ba3be1af06001770ef17]={
  id=g_str_5fb1ba3be1af06001770ef17,
  name='Horse Bow',
  min=1,
  max=4,
  description='Turkoman horse archers',
}
g_str_5fb1ba3be1af06001770ef1a='5fb1ba3be1af06001770ef1a'
g_base_definitions[g_str_5fb1ba3be1af06001770ef1a]={
  id=g_str_5fb1ba3be1af06001770ef1a,
  name='Rabble',
  min=0,
  max=2,
  description='Qangli foot',
}
g_str_5fb1ba3be1af06001770ef1c='5fb1ba3be1af06001770ef1c'
g_base_definitions[g_str_5fb1ba3be1af06001770ef1c]={
  name='Elite Cavalary General',
  id=g_str_5fb1ba3be1af06001770ef1c,
  min=1,
  max=1,
}
g_str_5fb1b9ede1af060017709fc1_camp='5fb1b9ede1af060017709fc1_camp'
g_base_definitions[g_str_5fb1b9ede1af060017709fc1_camp]={
  name='Camp',
  id=g_str_5fb1b9ede1af060017709fc1_camp,
  min=1,
  max=1,
}
army['5fb1b9ede1af060017709fc1']={
  data={
    name='Khwarizmian  1186 to 1246 AD'
  },
  g_base_definitions[g_str_5fb1b9ede1af060017709fc1_camp],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef1c],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef07],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef0b],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef0f],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef12],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef15],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef17],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef1a],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709fc1"] = army["5fb1b9ede1af060017709fc1"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Khwarizmian  1186 to 1246 AD"] = army["5fb1b9ede1af060017709fc1"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Khwarizmian  1186 to 1246 AD"] = army["5fb1b9ede1af060017709fc1"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Khwarizmian  1186 to 1246 AD"] = army["5fb1b9ede1af060017709fc1"]
