troop_options['5fb1ba3ce1af06001770f21a'] = {
  min=3,
  max=7,
  dateRange={
    startDate=500,
    endDate=1000,
  }
}
troop_options['5fb1ba3ce1af06001770f21c'] = {
  min=1,
  max=5,
  dateRange={
    startDate=500,
    endDate=1000,
  }
}
troop_options['5fb1ba3ce1af06001770f21e'] = {
  min=2,
  max=4,
  dateRange={
    startDate=500,
    endDate=1000,
  }
}
troop_options['5fb1ba3ce1af06001770f220'] = {
  min=0,
  max=2,
  dateRange={
    startDate=500,
    endDate=1000,
  }
}
-- allies
-- 5fb1b9efe1af06001770a074 Tarim Basin Citystates  500 to 1000 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3ce1af06001770f21b_general='5fb1ba3ce1af06001770f21b_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f21b_general]={
  id=g_str_5fb1ba3ce1af06001770f21b_general,
  name='Elite Cavalary General',
  min=3,
  max=1,
  description='Dihqan armored horsemen',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f21a",
}
g_str_5fb1ba3ce1af06001770f21b='5fb1ba3ce1af06001770f21b'
g_base_definitions[g_str_5fb1ba3ce1af06001770f21b]={
  id=g_str_5fb1ba3ce1af06001770f21b,
  name='Elite Cavalary',
  min=3,
  max=7,
  description='Dihqan armored horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f21a",
}
g_str_5fb1ba3ce1af06001770f21d='5fb1ba3ce1af06001770f21d'
g_base_definitions[g_str_5fb1ba3ce1af06001770f21d]={
  id=g_str_5fb1ba3ce1af06001770f21d,
  name='Horse Bow',
  min=1,
  max=5,
  description='Dihqan horsemen with lesser armor, or scout or local nomad horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3ce1af06001770f21c",
}
g_str_5fb1ba3ce1af06001770f21f='5fb1ba3ce1af06001770f21f'
g_base_definitions[g_str_5fb1ba3ce1af06001770f21f]={
  id=g_str_5fb1ba3ce1af06001770f21f,
  name='Bow Levy',
  min=2,
  max=4,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3ce1af06001770f21e",
}
g_str_5fb1ba3ce1af06001770f221='5fb1ba3ce1af06001770f221'
g_base_definitions[g_str_5fb1ba3ce1af06001770f221]={
  id=g_str_5fb1ba3ce1af06001770f221,
  name='Horde',
  min=0,
  max=2,
  description='Levy spearmen',
  troop_type="Horde",
  troop_option_id="5fb1ba3ce1af06001770f220",
}
g_str_5fb1b9efe1af06001770a074_camp='5fb1b9efe1af06001770a074_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a074_camp]={
  id=g_str_5fb1b9efe1af06001770a074_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9efe1af06001770a074_camp_pack_train='5fb1b9efe1af06001770a074_camp_pack_train'
g_base_definitions[g_str_5fb1b9efe1af06001770a074_camp_pack_train]={
  id=g_str_5fb1b9efe1af06001770a074_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9efe1af06001770a074']={
  data={
    name='Tarim Basin Citystates  500 to 1000 AD',
    id='5fb1b9efe1af06001770a074',
    army_id='5fb1b9efe1af06001770a074'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f21b_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f21b],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f21d],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f21f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f221],
  g_base_definitions[g_str_5fb1b9efe1af06001770a074_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a074_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a074"] = army["5fb1b9efe1af06001770a074"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Tarim Basin Citystates  500 to 1000 AD"] = army["5fb1b9efe1af06001770a074"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tarim Basin Citystates  500 to 1000 AD"] = army["5fb1b9efe1af06001770a074"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a074"] = {}
army_dates["5fb1b9efe1af06001770a074"]["500 AD to 1000 AD"] ="5fb1b9efe1af06001770a074"
