-- 5fb1b9dbe1af0600177094f5 Early Hoplite Greek: Siciliot, Italiot, or Ionian  669 to 449 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba25e1af06001770c5ce_general='5fb1ba25e1af06001770c5ce_general'
g_base_definitions[g_str_5fb1ba25e1af06001770c5ce_general]={
  id=g_str_5fb1ba25e1af06001770c5ce_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba25e1af06001770c5ce='5fb1ba25e1af06001770c5ce'
g_base_definitions[g_str_5fb1ba25e1af06001770c5ce]={
  id=g_str_5fb1ba25e1af06001770c5ce,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba25e1af06001770c5d0_general='5fb1ba25e1af06001770c5d0_general'
g_base_definitions[g_str_5fb1ba25e1af06001770c5d0_general]={
  id=g_str_5fb1ba25e1af06001770c5d0_general,
  name='Heavy Foot General',
  min=6,
  max=1,
  description='Hoplites',
  general=true,
  troop_type="Heavy Foot",
}
g_str_5fb1ba25e1af06001770c5d0='5fb1ba25e1af06001770c5d0'
g_base_definitions[g_str_5fb1ba25e1af06001770c5d0]={
  id=g_str_5fb1ba25e1af06001770c5d0,
  name='Heavy Foot',
  min=6,
  max=16,
  description='Hoplites',
  troop_type="Heavy Foot",
}
g_str_5fb1ba25e1af06001770c5d2='5fb1ba25e1af06001770c5d2'
g_base_definitions[g_str_5fb1ba25e1af06001770c5d2]={
  id=g_str_5fb1ba25e1af06001770c5d2,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen and slingers',
  troop_type="Skirmishers",
}
g_str_5fb1ba25e1af06001770c5d4='5fb1ba25e1af06001770c5d4'
g_base_definitions[g_str_5fb1ba25e1af06001770c5d4]={
  id=g_str_5fb1ba25e1af06001770c5d4,
  name='Rabble',
  min=0,
  max=2,
  description='Javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba25e1af06001770c5d6='5fb1ba25e1af06001770c5d6'
g_base_definitions[g_str_5fb1ba25e1af06001770c5d6]={
  id=g_str_5fb1ba25e1af06001770c5d6,
  name='Light Foot',
  min=0,
  max=2,
  description='Sicel tribesmen',
  troop_type="Light Foot",
}
g_str_5fb1ba25e1af06001770c5d9='5fb1ba25e1af06001770c5d9'
g_base_definitions[g_str_5fb1ba25e1af06001770c5d9]={
  id=g_str_5fb1ba25e1af06001770c5d9,
  name='Light Foot',
  min=0,
  max=6,
  description='Sicel tribesmen',
  troop_type="Light Foot",
}
g_str_5fb1ba25e1af06001770c5db='5fb1ba25e1af06001770c5db'
g_base_definitions[g_str_5fb1ba25e1af06001770c5db]={
  id=g_str_5fb1ba25e1af06001770c5db,
  name='Warband',
  min=0,
  max=1,
  description='War dogs',
  troop_type="Warband",
}
g_str_5fb1b9dbe1af0600177094f5_camp='5fb1b9dbe1af0600177094f5_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094f5_camp]={
  id=g_str_5fb1b9dbe1af0600177094f5_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9dbe1af0600177094f5']={
  data={
    name='Early Hoplite Greek: Siciliot, Italiot, or Ionian  669 to 449 BC'
  },
  g_base_definitions[g_str_5fb1ba25e1af06001770c5ce_general],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5ce],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5d0_general],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5d0],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5d2],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5d4],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5d6],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5d9],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5db],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094f5_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094f5"] = army["5fb1b9dbe1af0600177094f5"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Hoplite Greek: Siciliot, Italiot, or Ionian  669 to 449 BC"] = army["5fb1b9dbe1af0600177094f5"]
