g_str_5fb1ba41e1af06001770f9df_general='5fb1ba41e1af06001770f9df_general'
g_base_definitions[g_str_5fb1ba41e1af06001770f9df_general]={
  id=g_str_5fb1ba41e1af06001770f9df_general,
  name='Elite Cavalry General',
  min=3,
  max=1,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  general=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9de",
}
g_str_5fb1ba41e1af06001770f9df='5fb1ba41e1af06001770f9df'
g_base_definitions[g_str_5fb1ba41e1af06001770f9df]={
  id=g_str_5fb1ba41e1af06001770f9df,
  name='Elite Cavalry',
  min=3,
  max=6,
  description='Khitan ordo soldiers riding armored horses and tribal noble horsemen',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba41e1af06001770f9de",
}
g_str_5fb1ba41e1af06001770f9e1='5fb1ba41e1af06001770f9e1'
g_base_definitions[g_str_5fb1ba41e1af06001770f9e1]={
  id=g_str_5fb1ba41e1af06001770f9e1,
  name='Horse Bow',
  min=2,
  max=7,
  description='Khitan ordo foragers and orderlies',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9e0",
}
g_str_5fb1ba41e1af06001770f9e3='5fb1ba41e1af06001770f9e3'
g_base_definitions[g_str_5fb1ba41e1af06001770f9e3]={
  id=g_str_5fb1ba41e1af06001770f9e3,
  name='Horse Bow',
  min=2,
  max=4,
  description='Khitan tribal horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9e2",
}
g_str_5fb1ba41e1af06001770f9e5='5fb1ba41e1af06001770f9e5'
g_base_definitions[g_str_5fb1ba41e1af06001770f9e5]={
  id=g_str_5fb1ba41e1af06001770f9e5,
  name='Horse Bow',
  min=0,
  max=2,
  description='Jurchen prisoner fierce sacrificial vanguard horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770f9e4",
}
g_str_5fb1b9f3e1af06001770a2b0_camp='5fb1b9f3e1af06001770a2b0_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b0_camp]={
  id=g_str_5fb1b9f3e1af06001770a2b0_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b0_camp_fortified='5fb1b9f3e1af06001770a2b0_camp_fortified'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b0_camp_fortified]={
  id=g_str_5fb1b9f3e1af06001770a2b0_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2b0_camp_pack_train='5fb1b9f3e1af06001770a2b0_camp_pack_train'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2b0_camp_pack_train]={
  id=g_str_5fb1b9f3e1af06001770a2b0_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba18e1af06001770ba9d='5fb1ba18e1af06001770ba9d'
g_base_definitions[g_str_5fb1ba18e1af06001770ba9d]={
  id=g_str_5fb1ba18e1af06001770ba9d,
  name='Archers',
  min=0,
  max=1,
  description='Crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba18e1af06001770ba9c",
}
g_str_5fb1ba18e1af06001770ba9f='5fb1ba18e1af06001770ba9f'
g_base_definitions[g_str_5fb1ba18e1af06001770ba9f]={
  id=g_str_5fb1ba18e1af06001770ba9f,
  name='Bow Levy',
  min=0,
  max=1,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba18e1af06001770ba9e",
}
g_str_5fb1ba18e1af06001770baa1='5fb1ba18e1af06001770baa1'
g_base_definitions[g_str_5fb1ba18e1af06001770baa1]={
  id=g_str_5fb1ba18e1af06001770baa1,
  name='Light Spear',
  min=1,
  max=1,
  description='Spearmen, with or without shields',
  troop_type="Light Spear",
  troop_option_id="5fb1ba18e1af06001770baa0",
}
g_str_5fb1ba18e1af06001770baa2='5fb1ba18e1af06001770baa2'
g_base_definitions[g_str_5fb1ba18e1af06001770baa2]={
  id=g_str_5fb1ba18e1af06001770baa2,
  name='Heavy Foot',
  min=1,
  max=1,
  description='Spearmen, with or without shields',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba18e1af06001770baa0",
}
g_str_5fb1ba18e1af06001770baa4='5fb1ba18e1af06001770baa4'
g_base_definitions[g_str_5fb1ba18e1af06001770baa4]={
  id=g_str_5fb1ba18e1af06001770baa4,
  name='Raiders',
  min=1,
  max=1,
  description='Vanguard swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba18e1af06001770baa3",
}
g_str_5fb1ba18e1af06001770baa6='5fb1ba18e1af06001770baa6'
g_base_definitions[g_str_5fb1ba18e1af06001770baa6]={
  id=g_str_5fb1ba18e1af06001770baa6,
  name='Warband',
  min=0,
  max=1,
  description='Southern tribal auxiliaries',
  troop_type="Warband",
  troop_option_id="5fb1ba18e1af06001770baa5",
}
g_str_5fb1ba18e1af06001770baa7='5fb1ba18e1af06001770baa7'
g_base_definitions[g_str_5fb1ba18e1af06001770baa7]={
  id=g_str_5fb1ba18e1af06001770baa7,
  name='Light Foot',
  min=0,
  max=1,
  description='Southern tribal auxiliaries',
  troop_type="Light Foot",
  troop_option_id="5fb1ba18e1af06001770baa5",
}
