-- 5fb1b9f1e1af06001770a1d0 Southern Xiongnu  304 to 439 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3fe1af06001770f6a3_general='5fb1ba3fe1af06001770f6a3_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6a3_general]={
  id=g_str_5fb1ba3fe1af06001770f6a3_general,
  name='Cataphracts General',
  min=1,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba3fe1af06001770f6a2",
}
g_str_5fb1ba3fe1af06001770f6a3='5fb1ba3fe1af06001770f6a3'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6a3]={
  id=g_str_5fb1ba3fe1af06001770f6a3,
  name='Cataphracts',
  min=1,
  max=2,
  description='Noble horsemen',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba3fe1af06001770f6a2",
}
g_str_5fb1ba3fe1af06001770f6a4_general='5fb1ba3fe1af06001770f6a4_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6a4_general]={
  id=g_str_5fb1ba3fe1af06001770f6a4_general,
  name='Knights General',
  min=1,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba3fe1af06001770f6a2",
}
g_str_5fb1ba3fe1af06001770f6a4='5fb1ba3fe1af06001770f6a4'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6a4]={
  id=g_str_5fb1ba3fe1af06001770f6a4,
  name='Knights',
  min=1,
  max=2,
  description='Noble horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba3fe1af06001770f6a2",
}
g_str_5fb1ba3fe1af06001770f6a6='5fb1ba3fe1af06001770f6a6'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6a6]={
  id=g_str_5fb1ba3fe1af06001770f6a6,
  name='Horse Bow',
  min=4,
  max=11,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3fe1af06001770f6a5",
}
g_str_5fb1ba3fe1af06001770f6a8='5fb1ba3fe1af06001770f6a8'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6a8]={
  id=g_str_5fb1ba3fe1af06001770f6a8,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3fe1af06001770f6a7",
}
g_str_5fb1ba3fe1af06001770f6aa='5fb1ba3fe1af06001770f6aa'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6aa]={
  id=g_str_5fb1ba3fe1af06001770f6aa,
  name='Horde',
  min=0,
  max=2,
  description='Serfs, slaves or camp followers',
  troop_type="Horde",
  troop_option_id="5fb1ba3fe1af06001770f6a9",
}
g_str_5fb1ba3fe1af06001770f6ab='5fb1ba3fe1af06001770f6ab'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6ab]={
  id=g_str_5fb1ba3fe1af06001770f6ab,
  name='Rabble',
  min=0,
  max=2,
  description='Serfs, slaves or camp followers',
  troop_type="Rabble",
  troop_option_id="5fb1ba3fe1af06001770f6a9",
}
g_str_5fb1b9f1e1af06001770a1d0_camp='5fb1b9f1e1af06001770a1d0_camp'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1d0_camp]={
  id=g_str_5fb1b9f1e1af06001770a1d0_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f1e1af06001770a1d0_camp_pack_train='5fb1b9f1e1af06001770a1d0_camp_pack_train'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1d0_camp_pack_train]={
  id=g_str_5fb1b9f1e1af06001770a1d0_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba17e1af06001770b9f3='5fb1ba17e1af06001770b9f3'
g_base_definitions[g_str_5fb1ba17e1af06001770b9f3]={
  id=g_str_5fb1ba17e1af06001770b9f3,
  name='Light Foot',
  min=2,
  max=9,
  description='Spearmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba17e1af06001770b9f2",
}
g_str_5fb1ba17e1af06001770b9f5='5fb1ba17e1af06001770b9f5'
g_base_definitions[g_str_5fb1ba17e1af06001770b9f5]={
  id=g_str_5fb1ba17e1af06001770b9f5,
  name='Bow Levy',
  min=1,
  max=3,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba17e1af06001770b9f4",
}
army['5fb1b9f1e1af06001770a1d0']={
  data={
    name='Southern Xiongnu  304 to 439 AD',
    id='5fb1b9f1e1af06001770a1d0',
    army_id='5fb1b9f1e1af06001770a1d0'
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6a3_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6a3],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6a4_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6a4],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6a6],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6a8],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6aa],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f6ab],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1d0_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1d0_camp_pack_train],
  g_base_definitions[g_str_5fb1ba17e1af06001770b9f3],
  g_base_definitions[g_str_5fb1ba17e1af06001770b9f5],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1d0"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Southern Xiongnu  304 to 439 AD"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Southern Xiongnu  304 to 439 AD"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Southern Xiongnu  304 to 439 AD"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1d0"] = {}
army_dates["5fb1b9f1e1af06001770a1d0"]["304 AD to 439 AD"] ="5fb1b9f1e1af06001770a1d0"
