-- 5fb1b9e9e1af060017709d84 Corvinus Hungarian  1442 to 1526 AD

army['5fb1b9e9e1af060017709d84']={
  data={
    name='Corvinus Hungarian  1442 to 1526 AD',
    id='5fb1b9e9e1af060017709d84',
    dateRange={
      startDate=1442,
      endDate=1526,
    }
  },
  g_base_definitions[g_str_5fb1ba35e1af06001770e589_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e589],
  g_base_definitions[g_str_5fb1ba35e1af06001770e58c],
  g_base_definitions[g_str_5fb1ba35e1af06001770e58f_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e58f],
  g_base_definitions[g_str_5fb1ba35e1af06001770e591],
  g_base_definitions[g_str_5fb1ba35e1af06001770e593],
  g_base_definitions[g_str_5fb1ba35e1af06001770e596],
  g_base_definitions[g_str_5fb1ba35e1af06001770e598],
  g_base_definitions[g_str_5fb1ba35e1af06001770e59b],
  g_base_definitions[g_str_5fb1ba35e1af06001770e59e],
  g_base_definitions[g_str_5fb1ba35e1af06001770e5a0],
  g_base_definitions[g_str_5fb1ba35e1af06001770e5a2],
  g_base_definitions[g_str_5fb1ba35e1af06001770e5a3],
  g_base_definitions[g_str_5fb1ba35e1af06001770e5a6],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d84_camp],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d84_camp_fortified],
  g_base_definitions[g_str_5fb1ba13e1af06001770b3f5],
  g_base_definitions[g_str_5fb1ba13e1af06001770b3f6],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d84"] = army["5fb1b9e9e1af060017709d84"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Corvinus Hungarian  1442 to 1526 AD"] = army["5fb1b9e9e1af060017709d84"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Corvinus Hungarian  1442 to 1526 AD"] = army["5fb1b9e9e1af060017709d84"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Corvinus Hungarian  1442 to 1526 AD"] = army["5fb1b9e9e1af060017709d84"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Corvinus Hungarian  1442 to 1526 AD"] = army["5fb1b9e9e1af060017709d84"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d84"] = {}
army_dates["5fb1b9e9e1af060017709d84"]["1442 AD to 1526 AD"] = {
  startDate=1442,
  endDate=1526
}
army_dates["5fb1b9e9e1af060017709d84"]["1442 AD to 1446 AD"] = {
  startDate=1442,
  endDate=1526
}
army_dates["5fb1b9e9e1af060017709d84"]["1447 AD to 1466 AD"] = {
  startDate=1442,
  endDate=1526
}
army_dates["5fb1b9e9e1af060017709d84"]["1467 AD to 1471 AD"] = {
  startDate=1442,
  endDate=1526
}
army_dates["5fb1b9e9e1af060017709d84"]["1472 AD to 1490 AD"] = {
  startDate=1442,
  endDate=1526
}
army_dates["5fb1b9e9e1af060017709d84"]["1491 AD to 1526 AD"] = {
  startDate=1442,
  endDate=1526
}
