-- 5fb1b9e8e1af060017709c63 Jacquerie  1358 to 1358 AD

army['5fb1b9e8e1af060017709c63']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Jacquerie  1358 to 1358 AD',
    id='5fb1b9e8e1af060017709c63',
    dateRange={
      startDate=1358,
      endDate=1358,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e0c4_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0c4],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0c6],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0c8],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0ca],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0cc],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c63_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c63"] = army["5fb1b9e8e1af060017709c63"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Jacquerie  1358 to 1358 AD"] = army["5fb1b9e8e1af060017709c63"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Jacquerie  1358 to 1358 AD"] = army["5fb1b9e8e1af060017709c63"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Jacquerie  1358 to 1358 AD"] = army["5fb1b9e8e1af060017709c63"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c63"] = {}
army_dates["5fb1b9e8e1af060017709c63"]["1358 AD"] = {
  startDate=1358,
  endDate=1358
}
