troop_options['5fb1ba23e1af06001770c3cf'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3d1'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3d3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3d5'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3d8'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3db'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3dd'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3e0'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3e3'] = {
  min=0,
  max=8,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3e5'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
troop_options['5fb1ba23e1af06001770c3e7'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-680,
    endDate=-609,
  }
}
-- allies
