troop_options['5fb1ba3fe1af06001770f655'] = {
  min=1,
  max=3,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f657'] = {
  min=0,
  max=1,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f659'] = {
  min=1,
  max=2,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f65b'] = {
  min=2,
  max=6,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f65e'] = {
  min=0,
  max=1,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f660'] = {
  min=2,
  max=6,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f663'] = {
  min=2,
  max=6,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f667'] = {
  min=1,
  max=6,
  dateRange={
    startDate=351,
    endDate=394,
  }
}
troop_options['5fb1ba3fe1af06001770f66a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=383,
    endDate=383,
  }
}
-- allies
