-- 5fb1b9dbe1af0600177094a4 Early Villanovan Italian  1000 to 801 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba24e1af06001770c4e7='5fb1ba24e1af06001770c4e7'
g_base_definitions[g_str_5fb1ba24e1af06001770c4e7]={
  id=g_str_5fb1ba24e1af06001770c4e7,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='2-horse battle-platform',
  general=true,
}
g_str_5fb1ba24e1af06001770c4e7='5fb1ba24e1af06001770c4e7'
g_base_definitions[g_str_5fb1ba24e1af06001770c4e7]={
  id=g_str_5fb1ba24e1af06001770c4e7,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle-platform',
}
g_str_5fb1ba24e1af06001770c4e9='5fb1ba24e1af06001770c4e9'
g_base_definitions[g_str_5fb1ba24e1af06001770c4e9]={
  id=g_str_5fb1ba24e1af06001770c4e9,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
}
g_str_5fb1ba24e1af06001770c4e9='5fb1ba24e1af06001770c4e9'
g_base_definitions[g_str_5fb1ba24e1af06001770c4e9]={
  id=g_str_5fb1ba24e1af06001770c4e9,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Horsemen',
}
g_str_5fb1ba24e1af06001770c4eb='5fb1ba24e1af06001770c4eb'
g_base_definitions[g_str_5fb1ba24e1af06001770c4eb]={
  id=g_str_5fb1ba24e1af06001770c4eb,
  name='Warband',
  min=10,
  max=14,
  description='Spearmen',
}
g_str_5fb1b9dbe1af0600177094a4_camp='5fb1b9dbe1af0600177094a4_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094a4_camp]={
  name='Camp',
  id=g_str_5fb1b9dbe1af0600177094a4_camp,
  min=1,
  max=1,
}
army['5fb1b9dbe1af0600177094a4']={
  data={
    name='Early Villanovan Italian  1000 to 801 BC'
  },
  g_base_definitions[g_str_5fb1b9dbe1af0600177094a4_camp],
  g_base_definitions[g_str_5fb1ba24e1af06001770c4ed],
  g_base_definitions[g_str_5fb1ba24e1af06001770c4ee],
  g_base_definitions[g_str_5fb1ba24e1af06001770c4e7],
  g_base_definitions[g_str_5fb1ba24e1af06001770c4e7],
  g_base_definitions[g_str_5fb1ba24e1af06001770c4e9],
  g_base_definitions[g_str_5fb1ba24e1af06001770c4e9],
  g_base_definitions[g_str_5fb1ba24e1af06001770c4eb],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094a4"] = army["5fb1b9dbe1af0600177094a4"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Villanovan Italian  1000 to 801 BC"] = army["5fb1b9dbe1af0600177094a4"]
