-- 5fb1b9e1e1af060017709849 Early German  115 BC to 250 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2be1af06001770d2ae_general='5fb1ba2be1af06001770d2ae_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general]={
  id=g_str_5fb1ba2be1af06001770d2ae_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2be1af06001770d2ae_general_dismounted='5fb1ba2be1af06001770d2ae_general_dismounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general_dismounted]={
  id=g_str_5fb1ba2be1af06001770d2ae_general_dismounted,
  name='Warriors General',
  min=1,
  max=1,
  description='Horsemen\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  general=true,
  troop_type="Warriors",
}
g_5fb1ba2be1af06001770d2ae_general_dismounted=g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general_dismounted]
g_str_5fb1ba2be1af06001770d2ae_general_mounted='5fb1ba2be1af06001770d2ae_general_mounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general_mounted]={
  id=g_str_5fb1ba2be1af06001770d2ae_general_mounted,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2be1af06001770d2ae_general_dismounted,
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2be1af06001770d2ae='5fb1ba2be1af06001770d2ae'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ae]={
  id=g_str_5fb1ba2be1af06001770d2ae,
  name='Javelin Cavalry',
  min=1,
  max=4,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2be1af06001770d2ae_dismounted='5fb1ba2be1af06001770d2ae_dismounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_dismounted]={
  id=g_str_5fb1ba2be1af06001770d2ae_dismounted,
  name='Warriors',
  min=1,
  max=4,
  description='Horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
  troop_type="Warriors",
}
g_5fb1ba2be1af06001770d2ae_dismounted=g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_dismounted]
g_str_5fb1ba2be1af06001770d2ae_mounted='5fb1ba2be1af06001770d2ae_mounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_mounted]={
  id=g_str_5fb1ba2be1af06001770d2ae_mounted,
  name='Javelin Cavalry',
  min=1,
  max=4,
  description='Horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2be1af06001770d2ae_dismounted,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2be1af06001770d2b1_general='5fb1ba2be1af06001770d2b1_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d2b1_general]={
  id=g_str_5fb1ba2be1af06001770d2b1_general,
  name='Warriors General',
  min=6,
  max=1,
  description='Fierce fighters',
  general=true,
  troop_type="Warriors",
}
g_str_5fb1ba2be1af06001770d2b1='5fb1ba2be1af06001770d2b1'
g_base_definitions[g_str_5fb1ba2be1af06001770d2b1]={
  id=g_str_5fb1ba2be1af06001770d2b1,
  name='Warriors',
  min=6,
  max=13,
  description='Fierce fighters',
  troop_type="Warriors",
}
g_str_5fb1ba2be1af06001770d2b3='5fb1ba2be1af06001770d2b3'
g_base_definitions[g_str_5fb1ba2be1af06001770d2b3]={
  id=g_str_5fb1ba2be1af06001770d2b3,
  name='Raiders',
  min=0,
  max=1,
  description='Fighters armed with sword, shield, and wooden club',
  troop_type="Raiders",
}
g_str_5fb1ba2be1af06001770d2b5='5fb1ba2be1af06001770d2b5'
g_base_definitions[g_str_5fb1ba2be1af06001770d2b5]={
  id=g_str_5fb1ba2be1af06001770d2b5,
  name='Rabble',
  min=2,
  max=4,
  description='Foot skirmishers armed with many fire-hardened untipped throwing spears',
  troop_type="Rabble",
}
g_str_5fb1ba2be1af06001770d2b7='5fb1ba2be1af06001770d2b7'
g_base_definitions[g_str_5fb1ba2be1af06001770d2b7]={
  id=g_str_5fb1ba2be1af06001770d2b7,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1b9e1e1af060017709849_camp='5fb1b9e1e1af060017709849_camp'
g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp]={
  id=g_str_5fb1b9e1e1af060017709849_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af060017709849_camp_fortified='5fb1b9e1e1af060017709849_camp_fortified'
g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp_fortified]={
  id=g_str_5fb1b9e1e1af060017709849_camp_fortified,
  name='Fortified Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af060017709849_camp_pack_train='5fb1b9e1e1af060017709849_camp_pack_train'
g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp_pack_train]={
  id=g_str_5fb1b9e1e1af060017709849_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e1e1af060017709849']={
  data={
    name='Early German  115 BC to 250 AD'
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b1_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b1],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b3],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b5],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b7],
  g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709849"] = army["5fb1b9e1e1af060017709849"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early German  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709849"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Early German  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709849"]
