-- 5fb1b9dfe1af060017709752 Arabo-Aramaean Hatra  150 BC to 240 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ae1af06001770cf75='5fb1ba2ae1af06001770cf75'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf75]={
  id=g_str_5fb1ba2ae1af06001770cf75,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
}
g_str_5fb1ba2ae1af06001770cf75='5fb1ba2ae1af06001770cf75'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf75]={
  id=g_str_5fb1ba2ae1af06001770cf75,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
}
g_str_5fb1ba2ae1af06001770cf76='5fb1ba2ae1af06001770cf76'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf76]={
  id=g_str_5fb1ba2ae1af06001770cf76,
  name='Cataphracts General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
}
g_str_5fb1ba2ae1af06001770cf76='5fb1ba2ae1af06001770cf76'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf76]={
  id=g_str_5fb1ba2ae1af06001770cf76,
  name='Cataphracts',
  min=0,
  max=1,
  description='Horsemen',
}
g_str_5fb1ba2ae1af06001770cf78='5fb1ba2ae1af06001770cf78'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf78]={
  id=g_str_5fb1ba2ae1af06001770cf78,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Horse archers',
  general=true,
}
g_str_5fb1ba2ae1af06001770cf78='5fb1ba2ae1af06001770cf78'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf78]={
  id=g_str_5fb1ba2ae1af06001770cf78,
  name='Horse Bow',
  min=1,
  max=4,
  description='Horse archers',
}
g_str_5fb1ba2ae1af06001770cf7a='5fb1ba2ae1af06001770cf7a'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf7a]={
  id=g_str_5fb1ba2ae1af06001770cf7a,
  name='Bad Horse',
  min=0,
  max=1,
  description='Scouts on camels',
}
g_str_5fb1ba2ae1af06001770cf7d='5fb1ba2ae1af06001770cf7d'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf7d]={
  id=g_str_5fb1ba2ae1af06001770cf7d,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Swordsmen',
}
g_str_5fb1ba2ae1af06001770cf7f='5fb1ba2ae1af06001770cf7f'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf7f]={
  id=g_str_5fb1ba2ae1af06001770cf7f,
  name='Light Foot',
  min=1,
  max=4,
  description='Javelinmen',
}
g_str_5fb1ba2ae1af06001770cf81='5fb1ba2ae1af06001770cf81'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf81]={
  id=g_str_5fb1ba2ae1af06001770cf81,
  name='Archers',
  min=5,
  max=16,
  description='Bowmen',
}
g_str_5fb1ba2ae1af06001770cf82='5fb1ba2ae1af06001770cf82'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf82]={
  id=g_str_5fb1ba2ae1af06001770cf82,
  name='Bow Levy',
  min=5,
  max=16,
  description='Bowmen',
}
g_str_5fb1ba2ae1af06001770cf84='5fb1ba2ae1af06001770cf84'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf84]={
  id=g_str_5fb1ba2ae1af06001770cf84,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
}
g_str_5fb1ba2ae1af06001770cf87='5fb1ba2ae1af06001770cf87'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf87]={
  id=g_str_5fb1ba2ae1af06001770cf87,
  name='Cataphracts General',
  min=0,
  max=1,
  description='Fully armored camels and riders',
  general=true,
}
g_str_5fb1ba2ae1af06001770cf87='5fb1ba2ae1af06001770cf87'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf87]={
  id=g_str_5fb1ba2ae1af06001770cf87,
  name='Cataphracts',
  min=0,
  max=1,
  description='Fully armored camels and riders',
}
g_str_5fb1ba2ae1af06001770cf8b='5fb1ba2ae1af06001770cf8b'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf8b]={
  id=g_str_5fb1ba2ae1af06001770cf8b,
  name='Artillery',
  min=0,
  max=1,
  description='Stone-throwers',
}
g_str_5fb1ba2ae1af06001770cf8e='5fb1ba2ae1af06001770cf8e'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf8e]={
  id=g_str_5fb1ba2ae1af06001770cf8e,
  name='Raiders',
  min=0,
  max=1,
  description='Roman auxiliaries',
}
g_str_5fb1b9dfe1af060017709752_camp='5fb1b9dfe1af060017709752_camp'
g_base_definitions[g_str_5fb1b9dfe1af060017709752_camp]={
  name='Camp',
  id=g_str_5fb1b9dfe1af060017709752_camp,
  min=1,
  max=1,
}
army['5fb1b9dfe1af060017709752']={
  data={
    name='Arabo-Aramaean Hatra  150 BC to 240 AD'
  },
  g_base_definitions[g_str_5fb1b9dfe1af060017709752_camp],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf90],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf91],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf92],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf75],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf75],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf76],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf76],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf78],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf78],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf7a],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf7d],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf7f],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf81],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf82],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf84],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf87],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf87],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf8b],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf8e],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709752"] = army["5fb1b9dfe1af060017709752"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Arabo-Aramaean Hatra  150 BC to 240 AD"] = army["5fb1b9dfe1af060017709752"]
