troop_options['5fb1ba38e1af06001770e981'] = {
  min=3,
  max=6,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e983'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e985'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e988'] = {
  min=4,
  max=8,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e98a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e98c'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e98e'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e990'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1301,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e992'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1380,
    endDate=1489,
  }
}
troop_options['5fb1ba38e1af06001770e995'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1380,
    endDate=1489,
  }
}
-- allies
