-- 5fb1b9f5e1af06001770a39a Oaxaca  500 BC to 1100 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba43e1af06001770fd18='5fb1ba43e1af06001770fd18'
g_base_definitions[g_str_5fb1ba43e1af06001770fd18]={
  id=g_str_5fb1ba43e1af06001770fd18,
  name='Light Spear',
  min=8,
  max=16,
  description='Nobles armed with long spears and clubs or small shields',
}
g_str_5fb1ba43e1af06001770fd1a='5fb1ba43e1af06001770fd1a'
g_base_definitions[g_str_5fb1ba43e1af06001770fd1a]={
  id=g_str_5fb1ba43e1af06001770fd1a,
  name='Raiders',
  min=0,
  max=2,
  description='Suit-wearers armed with long spears and clubs or small shields',
}
g_str_5fb1ba43e1af06001770fd1c='5fb1ba43e1af06001770fd1c'
g_base_definitions[g_str_5fb1ba43e1af06001770fd1c]={
  id=g_str_5fb1ba43e1af06001770fd1c,
  name='Light Foot',
  min=0,
  max=2,
  description='Garrison troops armed with mixed weapons',
}
g_str_5fb1ba43e1af06001770fd1e='5fb1ba43e1af06001770fd1e'
g_base_definitions[g_str_5fb1ba43e1af06001770fd1e]={
  id=g_str_5fb1ba43e1af06001770fd1e,
  name='Horde',
  min=0,
  max=6,
  description='Poorly-armed commoners',
}
g_str_5fb1ba43e1af06001770fd20='5fb1ba43e1af06001770fd20'
g_base_definitions[g_str_5fb1ba43e1af06001770fd20]={
  id=g_str_5fb1ba43e1af06001770fd20,
  name='Skirmishers',
  min=0,
  max=4,
  description='Peasant skirmishing slingers',
}
g_str_5fb1ba43e1af06001770fd22='5fb1ba43e1af06001770fd22'
g_base_definitions[g_str_5fb1ba43e1af06001770fd22]={
  name='Light Spear General',
  min=1,
  max=1,
}
g_str_5fb1b9f5e1af06001770a39a_camp='5fb1b9f5e1af06001770a39a_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a39a_camp]={
  name='Camp',
  min=1,
  max=1,
}
army['5fb1b9f5e1af06001770a39a']={
  data={
    name='Oaxaca  500 BC to 1100 AD'
  },
  g_base_definitions[g_str_5fb1b9f5e1af06001770a39a_camp],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd22],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd18],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd1a],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd1c],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd1e],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd20],
}
