troop_options['5fb1ba38e1af06001770e967'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1277,
    endDate=1280,
  }
}
troop_options['5fb1ba38e1af06001770e969'] = {
  min=3,
  max=6,
  dateRange={
    startDate=1277,
    endDate=1280,
  }
}
troop_options['5fb1ba38e1af06001770e96b'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1277,
    endDate=1280,
  }
}
troop_options['5fb1ba38e1af06001770e96d'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1277,
    endDate=1280,
  }
}
troop_options['5fb1ba38e1af06001770e96f'] = {
  min=2,
  max=8,
  dateRange={
    startDate=1277,
    endDate=1280,
  }
}
-- allies
