-- 5fb1b9d8e1af0600177092d8 Melukhkhan and Pre-Vedic Indian  2700 to 1500 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba1ee1af06001770be37_general='5fb1ba1ee1af06001770be37_general'
g_base_definitions[g_str_5fb1ba1ee1af06001770be37_general]={
  id=g_str_5fb1ba1ee1af06001770be37_general,
  name='Light Spear General',
  min=1,
  max=1,
  description='Spearmen',
  general=true,
  troop_type="Light Spear",
}
g_str_5fb1ba1ee1af06001770be37='5fb1ba1ee1af06001770be37'
g_base_definitions[g_str_5fb1ba1ee1af06001770be37]={
  id=g_str_5fb1ba1ee1af06001770be37,
  name='Light Spear',
  min=1,
  max=8,
  description='Spearmen',
  troop_type="Light Spear",
}
g_str_5fb1ba1ee1af06001770be38_general='5fb1ba1ee1af06001770be38_general'
g_base_definitions[g_str_5fb1ba1ee1af06001770be38_general]={
  id=g_str_5fb1ba1ee1af06001770be38_general,
  name='Heavy Foot General',
  min=1,
  max=1,
  description='Spearmen',
  general=true,
  troop_type="Heavy Foot",
}
g_str_5fb1ba1ee1af06001770be38='5fb1ba1ee1af06001770be38'
g_base_definitions[g_str_5fb1ba1ee1af06001770be38]={
  id=g_str_5fb1ba1ee1af06001770be38,
  name='Heavy Foot',
  min=1,
  max=8,
  description='Spearmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba1ee1af06001770be3b_general='5fb1ba1ee1af06001770be3b_general'
g_base_definitions[g_str_5fb1ba1ee1af06001770be3b_general]={
  id=g_str_5fb1ba1ee1af06001770be3b_general,
  name='Raiders General',
  min=0,
  max=1,
  description='Close fighters',
  general=true,
  troop_type="Raiders",
}
g_str_5fb1ba1ee1af06001770be3b='5fb1ba1ee1af06001770be3b'
g_base_definitions[g_str_5fb1ba1ee1af06001770be3b]={
  id=g_str_5fb1ba1ee1af06001770be3b,
  name='Raiders',
  min=0,
  max=1,
  description='Close fighters',
  troop_type="Raiders",
}
g_str_5fb1ba1ee1af06001770be3d='5fb1ba1ee1af06001770be3d'
g_base_definitions[g_str_5fb1ba1ee1af06001770be3d]={
  id=g_str_5fb1ba1ee1af06001770be3d,
  name='Bow Levy',
  min=2,
  max=10,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba1ee1af06001770be3f='5fb1ba1ee1af06001770be3f'
g_base_definitions[g_str_5fb1ba1ee1af06001770be3f]={
  id=g_str_5fb1ba1ee1af06001770be3f,
  name='Rabble',
  min=0,
  max=3,
  description='Kulli highlanders',
  troop_type="Rabble",
}
g_str_5fb1ba1ee1af06001770be41='5fb1ba1ee1af06001770be41'
g_base_definitions[g_str_5fb1ba1ee1af06001770be41]={
  id=g_str_5fb1ba1ee1af06001770be41,
  name='Skirmishers',
  min=5,
  max=7,
  description='Peasant slingers',
  troop_type="Skirmishers",
}
g_str_5fb1b9d8e1af0600177092d8_camp='5fb1b9d8e1af0600177092d8_camp'
g_base_definitions[g_str_5fb1b9d8e1af0600177092d8_camp]={
  name='Camp',
  id=g_str_5fb1b9d8e1af0600177092d8_camp,
  min=1,
  max=1,
}
army['5fb1b9d8e1af0600177092d8']={
  data={
    name='Melukhkhan and Pre-Vedic Indian  2700 to 1500 BC'
  },
  g_base_definitions[g_str_5fb1b9d8e1af0600177092d8_camp],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be37_general],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be37],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be38_general],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be38],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be3b_general],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be3b],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be3d],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be3f],
  g_base_definitions[g_str_5fb1ba1ee1af06001770be41],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092d8"] = army["5fb1b9d8e1af0600177092d8"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Melukhkhan and Pre-Vedic Indian  2700 to 1500 BC"] = army["5fb1b9d8e1af0600177092d8"]
