troop_options['5fb1ba2ae1af06001770cfba'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-312,
    endDate=633,
  }
}
troop_options['5fb1ba2ae1af06001770cfbc'] = {
  min=1,
  max=6,
  dateRange={
    startDate=-312,
    endDate=633,
  }
}
troop_options['5fb1ba2ae1af06001770cfbf'] = {
  min=4,
  max=11,
  dateRange={
    startDate=-312,
    endDate=633,
  }
}
troop_options['5fb1ba2ae1af06001770cfc1'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-312,
    endDate=633,
  }
}
troop_options['5fb1ba2ae1af06001770cfc4'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-312,
    endDate=633,
  }
}
troop_options['5fb1ba2ae1af06001770cfc6'] = {
  min=0,
  max=5,
  dateRange={
    startDate=-312,
    endDate=633,
  }
}
-- allies
