g_str_5fb1ba43e1af06001770fd3e_general='5fb1ba43e1af06001770fd3e_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd3e_general]={
  id=g_str_5fb1ba43e1af06001770fd3e_general,
  name='Heavy Foot General',
  min=0,
  max=1,
  description='Ah Camul guard',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba43e1af06001770fd3c",
}
g_str_5fb1ba43e1af06001770fd3e='5fb1ba43e1af06001770fd3e'
g_base_definitions[g_str_5fb1ba43e1af06001770fd3e]={
  id=g_str_5fb1ba43e1af06001770fd3e,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Ah Camul guard',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba43e1af06001770fd3c",
}
g_str_5fb1ba43e1af06001770fd41='5fb1ba43e1af06001770fd41'
g_base_definitions[g_str_5fb1ba43e1af06001770fd41]={
  id=g_str_5fb1ba43e1af06001770fd41,
  name='Bow Levy',
  min=1,
  max=1,
  description='Toltec-Chichimec mercenary bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba43e1af06001770fd3f",
}
g_str_5fb1ba43e1af06001770fd43_general='5fb1ba43e1af06001770fd43_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd43_general]={
  id=g_str_5fb1ba43e1af06001770fd43_general,
  name='Heavy Foot General',
  min=1,
  max=1,
  description='nobles',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba43e1af06001770fd42",
}
g_str_5fb1ba43e1af06001770fd43='5fb1ba43e1af06001770fd43'
g_base_definitions[g_str_5fb1ba43e1af06001770fd43]={
  id=g_str_5fb1ba43e1af06001770fd43,
  name='Heavy Foot',
  min=1,
  max=3,
  description='nobles',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba43e1af06001770fd42",
}
g_str_5fb1ba43e1af06001770fd45_general='5fb1ba43e1af06001770fd45_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd45_general]={
  id=g_str_5fb1ba43e1af06001770fd45_general,
  name='Light Foot General',
  min=8,
  max=1,
  description='Formed infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd44",
}
g_str_5fb1ba43e1af06001770fd45='5fb1ba43e1af06001770fd45'
g_base_definitions[g_str_5fb1ba43e1af06001770fd45]={
  id=g_str_5fb1ba43e1af06001770fd45,
  name='Light Foot',
  min=8,
  max=15,
  description='Formed infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd44",
}
g_str_5fb1ba43e1af06001770fd47='5fb1ba43e1af06001770fd47'
g_base_definitions[g_str_5fb1ba43e1af06001770fd47]={
  id=g_str_5fb1ba43e1af06001770fd47,
  name='Skirmishers',
  min=0,
  max=3,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd46",
}
g_str_5fb1ba43e1af06001770fd49='5fb1ba43e1af06001770fd49'
g_base_definitions[g_str_5fb1ba43e1af06001770fd49]={
  id=g_str_5fb1ba43e1af06001770fd49,
  name='Skirmishers',
  min=0,
  max=1,
  description='Road weasel scouts',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd48",
}
g_str_5fb1b9f5e1af06001770a3b8_camp='5fb1b9f5e1af06001770a3b8_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3b8_camp]={
  id=g_str_5fb1b9f5e1af06001770a3b8_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
