troop_options['5fb1ba1fe1af06001770bf7a'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-3000,
    endDate=-1690,
  }
}
troop_options['5fb1ba1fe1af06001770bf7d'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-1689,
    endDate=-1541,
  }
}
troop_options['5fb1ba1fe1af06001770bf81'] = {
  min=4,
  max=8,
  dateRange={
    startDate=-3000,
    endDate=-1541,
  }
}
troop_options['5fb1ba1fe1af06001770bf83'] = {
  min=4,
  max=8,
  dateRange={
    startDate=-3000,
    endDate=-1541,
  }
}
troop_options['5fb1ba1fe1af06001770bf86'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-3000,
    endDate=-1541,
  }
}
troop_options['5fb1ba1fe1af06001770bf88'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-3000,
    endDate=-1541,
  }
}
troop_options['5fb1ba1fe1af06001770bf8a'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-3000,
    endDate=-1541,
  }
}
troop_options['5fb1ba1fe1af06001770bf8d'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-3000,
    endDate=-1541,
  }
}
troop_options['5fb1ba1fe1af06001770bf8f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-3000,
    endDate=-1541,
  }
}
-- allies
