-- 5fb1b9d8e1af0600177092ec Nomadic Amurru  3000 to 2001 BC

army['5fb1b9d8e1af0600177092ec']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
    },
    name='Nomadic Amurru  3000 to 2001 BC',
    id='5fb1b9d8e1af0600177092ec',
    dateRange={
      startDate=-3000,
      endDate=-2001,
    }
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8a_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8a],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8e],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be90],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be91],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092ec_camp],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092ec_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092ec"] = army["5fb1b9d8e1af0600177092ec"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Nomadic Amurru  3000 to 2001 BC"] = army["5fb1b9d8e1af0600177092ec"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Nomadic Amurru  3000 to 2001 BC"] = army["5fb1b9d8e1af0600177092ec"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d8e1af0600177092ec"] = {}
army_dates["5fb1b9d8e1af0600177092ec"]["3000 BC to 2001 BC"] = {
  startDate=-3000,
  endDate=-2001
}
army_dates["5fb1b9d8e1af0600177092ec"]["3000 BC to 2701 BC"] = {
  startDate=-3000,
  endDate=-2701
}
army_dates["5fb1b9d8e1af0600177092ec"]["2700 BC to 2201 BC"] = {
  startDate=-2700,
  endDate=-2201
}
army_dates["5fb1b9d8e1af0600177092ec"]["2200 BC"] = {
  startDate=-2200,
  endDate=-2200
}
army_dates["5fb1b9d8e1af0600177092ec"]["2199 BC to 2113 BC"] = {
  startDate=-2199,
  endDate=-2113
}
army_dates["5fb1b9d8e1af0600177092ec"]["2112 BC to 2029 BC"] = {
  startDate=-2112,
  endDate=-2029
}
army_dates["5fb1b9d8e1af0600177092ec"]["2028 BC"] = {
  startDate=-2028,
  endDate=-2028
}
army_dates["5fb1b9d8e1af0600177092ec"]["2027 BC to 2026 BC"] = {
  startDate=-2027,
  endDate=-2026
}
army_dates["5fb1b9d8e1af0600177092ec"]["2025 BC to 2018 BC"] = {
  startDate=-2025,
  endDate=-2018
}
army_dates["5fb1b9d8e1af0600177092ec"]["2017 BC to 2004 BC"] = {
  startDate=-2017,
  endDate=-2004
}
army_dates["5fb1b9d8e1af0600177092ec"]["2003 BC to 2001 BC"] = {
  startDate=-2003,
  endDate=-2001
}
-- 5fb1b9d8e1af0600177092ec Nomadic Amurru  3000 to 2001 BC

army['5fb1b9d8e1af0600177092ec']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
    },
    name='Nomadic Amurru  3000 to 2001 BC',
    id='5fb1b9d8e1af0600177092ec',
    dateRange={
      startDate=-3000,
      endDate=-2001,
    }
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8a_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8a],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8e],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be90],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be91],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092ec_camp],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092ec_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092ec"] = army["5fb1b9d8e1af0600177092ec"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Nomadic Amurru  3000 to 2001 BC"] = army["5fb1b9d8e1af0600177092ec"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Nomadic Amurru  3000 to 2001 BC"] = army["5fb1b9d8e1af0600177092ec"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d8e1af0600177092ec"] = {}
army_dates["5fb1b9d8e1af0600177092ec"]["3000 BC to 2001 BC"] = {
  startDate=-3000,
  endDate=-2001
}
army_dates["5fb1b9d8e1af0600177092ec"]["3000 BC to 2701 BC"] = {
  startDate=-3000,
  endDate=-2701
}
army_dates["5fb1b9d8e1af0600177092ec"]["2700 BC to 2201 BC"] = {
  startDate=-2700,
  endDate=-2201
}
army_dates["5fb1b9d8e1af0600177092ec"]["2200 BC"] = {
  startDate=-2200,
  endDate=-2200
}
army_dates["5fb1b9d8e1af0600177092ec"]["2199 BC to 2113 BC"] = {
  startDate=-2199,
  endDate=-2113
}
army_dates["5fb1b9d8e1af0600177092ec"]["2112 BC to 2029 BC"] = {
  startDate=-2112,
  endDate=-2029
}
army_dates["5fb1b9d8e1af0600177092ec"]["2028 BC"] = {
  startDate=-2028,
  endDate=-2028
}
army_dates["5fb1b9d8e1af0600177092ec"]["2027 BC to 2026 BC"] = {
  startDate=-2027,
  endDate=-2026
}
army_dates["5fb1b9d8e1af0600177092ec"]["2025 BC to 2018 BC"] = {
  startDate=-2025,
  endDate=-2018
}
army_dates["5fb1b9d8e1af0600177092ec"]["2017 BC to 2004 BC"] = {
  startDate=-2017,
  endDate=-2004
}
army_dates["5fb1b9d8e1af0600177092ec"]["2003 BC to 2001 BC"] = {
  startDate=-2003,
  endDate=-2001
}
-- 5fb1b9d8e1af0600177092ec Nomadic Amurru  3000 to 2001 BC

army['5fb1b9d8e1af0600177092ec']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
    },
    name='Nomadic Amurru  3000 to 2001 BC',
    id='5fb1b9d8e1af0600177092ec',
    dateRange={
      startDate=-3000,
      endDate=-2001,
    }
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8a_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8a],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be8e],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be90],
  g_base_definitions[g_str_5fb1ba1fe1af06001770be91],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092ec_camp],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092ec_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092ec"] = army["5fb1b9d8e1af0600177092ec"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Nomadic Amurru  3000 to 2001 BC"] = army["5fb1b9d8e1af0600177092ec"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Nomadic Amurru  3000 to 2001 BC"] = army["5fb1b9d8e1af0600177092ec"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d8e1af0600177092ec"] = {}
army_dates["5fb1b9d8e1af0600177092ec"]["3000 BC to 2001 BC"] = {
  startDate=-3000,
  endDate=-2001
}
army_dates["5fb1b9d8e1af0600177092ec"]["3000 BC to 2701 BC"] = {
  startDate=-3000,
  endDate=-2701
}
army_dates["5fb1b9d8e1af0600177092ec"]["2700 BC to 2201 BC"] = {
  startDate=-2700,
  endDate=-2201
}
army_dates["5fb1b9d8e1af0600177092ec"]["2200 BC"] = {
  startDate=-2200,
  endDate=-2200
}
army_dates["5fb1b9d8e1af0600177092ec"]["2199 BC to 2113 BC"] = {
  startDate=-2199,
  endDate=-2113
}
army_dates["5fb1b9d8e1af0600177092ec"]["2112 BC to 2029 BC"] = {
  startDate=-2112,
  endDate=-2029
}
army_dates["5fb1b9d8e1af0600177092ec"]["2028 BC"] = {
  startDate=-2028,
  endDate=-2028
}
army_dates["5fb1b9d8e1af0600177092ec"]["2027 BC to 2026 BC"] = {
  startDate=-2027,
  endDate=-2026
}
army_dates["5fb1b9d8e1af0600177092ec"]["2025 BC to 2018 BC"] = {
  startDate=-2025,
  endDate=-2018
}
army_dates["5fb1b9d8e1af0600177092ec"]["2017 BC to 2004 BC"] = {
  startDate=-2017,
  endDate=-2004
}
army_dates["5fb1b9d8e1af0600177092ec"]["2003 BC to 2001 BC"] = {
  startDate=-2003,
  endDate=-2001
}
