g_str_5fb1ba34e1af06001770e2ea_general='5fb1ba34e1af06001770e2ea_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ea_general]={
  id=g_str_5fb1ba34e1af06001770e2ea_general,
  name='Knights General',
  min=2,
  max=1,
  description='Men-at-arms, ministeriales and mercenaries',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e2e9",
}
g_str_5fb1ba34e1af06001770e2ea='5fb1ba34e1af06001770e2ea'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ea]={
  id=g_str_5fb1ba34e1af06001770e2ea,
  name='Knights',
  min=2,
  max=5,
  description='Men-at-arms, ministeriales and mercenaries',
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e2e9",
}
g_str_5fb1ba34e1af06001770e2ed='5fb1ba34e1af06001770e2ed'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ed]={
  id=g_str_5fb1ba34e1af06001770e2ed,
  name='Bad Horse',
  min=0,
  max=1,
  description='Armored crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba34e1af06001770e2ec",
}
g_str_5fb1ba34e1af06001770e2ef='5fb1ba34e1af06001770e2ef'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ef]={
  id=g_str_5fb1ba34e1af06001770e2ef,
  name='Horde',
  min=0,
  max=4,
  description='Feudal retainers or heerban',
  troop_type="Horde",
  troop_option_id="5fb1ba34e1af06001770e2ee",
}
g_str_5fb1ba34e1af06001770e2f1='5fb1ba34e1af06001770e2f1'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f1]={
  id=g_str_5fb1ba34e1af06001770e2f1,
  name='Bow Levy',
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e2f0",
}
g_str_5fb1ba34e1af06001770e2f3='5fb1ba34e1af06001770e2f3'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f3]={
  id=g_str_5fb1ba34e1af06001770e2f3,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e2f2",
}
g_str_5fb1ba34e1af06001770e2f6='5fb1ba34e1af06001770e2f6'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f6]={
  id=g_str_5fb1ba34e1af06001770e2f6,
  name='Archers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e2f5",
}
g_str_5fb1ba34e1af06001770e2f7='5fb1ba34e1af06001770e2f7'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f7]={
  id=g_str_5fb1ba34e1af06001770e2f7,
  name='Skirmishers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e2f5",
}
g_str_5fb1ba34e1af06001770e2fb='5fb1ba34e1af06001770e2fb'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fb]={
  id=g_str_5fb1ba34e1af06001770e2fb,
  name='Horse Bow',
  min=0,
  max=1,
  description='Hungarian horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba34e1af06001770e2f9",
}
g_str_5fb1ba34e1af06001770e2fd='5fb1ba34e1af06001770e2fd'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fd]={
  id=g_str_5fb1ba34e1af06001770e2fd,
  name='Bow Levy',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e2fc",
}
g_str_5fb1ba34e1af06001770e2fe='5fb1ba34e1af06001770e2fe'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fe]={
  id=g_str_5fb1ba34e1af06001770e2fe,
  name='Archers',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e2fc",
}
g_str_5fb1ba34e1af06001770e300='5fb1ba34e1af06001770e300'
g_base_definitions[g_str_5fb1ba34e1af06001770e300]={
  id=g_str_5fb1ba34e1af06001770e300,
  name='Heavy Foot',
  min=0,
  max=2,
  description='City militia spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e2ff",
}
g_str_5fb1ba34e1af06001770e303='5fb1ba34e1af06001770e303'
g_base_definitions[g_str_5fb1ba34e1af06001770e303]={
  id=g_str_5fb1ba34e1af06001770e303,
  name='Skirmishers',
  min=0,
  max=1,
  description='City militia skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e302",
}
g_str_5fb1ba34e1af06001770e307='5fb1ba34e1af06001770e307'
g_base_definitions[g_str_5fb1ba34e1af06001770e307]={
  id=g_str_5fb1ba34e1af06001770e307,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba34e1af06001770e305",
}
g_str_5fb1ba34e1af06001770e30a='5fb1ba34e1af06001770e30a'
g_base_definitions[g_str_5fb1ba34e1af06001770e30a]={
  id=g_str_5fb1ba34e1af06001770e30a,
  name='War Wagons',
  min=0,
  max=2,
  description='Hussite-style war wagons',
  troop_type="War Wagons",
  troop_option_id="5fb1ba34e1af06001770e308",
}
g_str_5fb1b9e9e1af060017709ce7_camp='5fb1b9e9e1af060017709ce7_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709ce7_camp]={
  id=g_str_5fb1b9e9e1af060017709ce7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709ce7_camp_fortified='5fb1b9e9e1af060017709ce7_camp_fortified'
g_base_definitions[g_str_5fb1b9e9e1af060017709ce7_camp_fortified]={
  id=g_str_5fb1b9e9e1af060017709ce7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba34e1af06001770e2ea_general='5fb1ba34e1af06001770e2ea_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ea_general]={
  id=g_str_5fb1ba34e1af06001770e2ea_general,
  name='Knights General',
  min=2,
  max=1,
  description='Men-at-arms, ministeriales and mercenaries',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e2e9",
}
g_str_5fb1ba34e1af06001770e2ea='5fb1ba34e1af06001770e2ea'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ea]={
  id=g_str_5fb1ba34e1af06001770e2ea,
  name='Knights',
  min=2,
  max=5,
  description='Men-at-arms, ministeriales and mercenaries',
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e2e9",
}
g_str_5fb1ba34e1af06001770e2ed='5fb1ba34e1af06001770e2ed'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ed]={
  id=g_str_5fb1ba34e1af06001770e2ed,
  name='Bad Horse',
  min=0,
  max=1,
  description='Armored crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba34e1af06001770e2ec",
}
g_str_5fb1ba34e1af06001770e2ef='5fb1ba34e1af06001770e2ef'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ef]={
  id=g_str_5fb1ba34e1af06001770e2ef,
  name='Horde',
  min=0,
  max=4,
  description='Feudal retainers or heerban',
  troop_type="Horde",
  troop_option_id="5fb1ba34e1af06001770e2ee",
}
g_str_5fb1ba34e1af06001770e2f1='5fb1ba34e1af06001770e2f1'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f1]={
  id=g_str_5fb1ba34e1af06001770e2f1,
  name='Bow Levy',
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e2f0",
}
g_str_5fb1ba34e1af06001770e2f3='5fb1ba34e1af06001770e2f3'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f3]={
  id=g_str_5fb1ba34e1af06001770e2f3,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e2f2",
}
g_str_5fb1ba34e1af06001770e2f6='5fb1ba34e1af06001770e2f6'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f6]={
  id=g_str_5fb1ba34e1af06001770e2f6,
  name='Archers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e2f5",
}
g_str_5fb1ba34e1af06001770e2f7='5fb1ba34e1af06001770e2f7'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f7]={
  id=g_str_5fb1ba34e1af06001770e2f7,
  name='Skirmishers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e2f5",
}
g_str_5fb1ba34e1af06001770e2fb='5fb1ba34e1af06001770e2fb'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fb]={
  id=g_str_5fb1ba34e1af06001770e2fb,
  name='Horse Bow',
  min=0,
  max=1,
  description='Hungarian horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba34e1af06001770e2f9",
}
g_str_5fb1ba34e1af06001770e2fd='5fb1ba34e1af06001770e2fd'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fd]={
  id=g_str_5fb1ba34e1af06001770e2fd,
  name='Bow Levy',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e2fc",
}
g_str_5fb1ba34e1af06001770e2fe='5fb1ba34e1af06001770e2fe'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fe]={
  id=g_str_5fb1ba34e1af06001770e2fe,
  name='Archers',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e2fc",
}
g_str_5fb1ba34e1af06001770e300='5fb1ba34e1af06001770e300'
g_base_definitions[g_str_5fb1ba34e1af06001770e300]={
  id=g_str_5fb1ba34e1af06001770e300,
  name='Heavy Foot',
  min=0,
  max=2,
  description='City militia spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e2ff",
}
g_str_5fb1ba34e1af06001770e303='5fb1ba34e1af06001770e303'
g_base_definitions[g_str_5fb1ba34e1af06001770e303]={
  id=g_str_5fb1ba34e1af06001770e303,
  name='Skirmishers',
  min=0,
  max=1,
  description='City militia skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e302",
}
g_str_5fb1ba34e1af06001770e307='5fb1ba34e1af06001770e307'
g_base_definitions[g_str_5fb1ba34e1af06001770e307]={
  id=g_str_5fb1ba34e1af06001770e307,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba34e1af06001770e305",
}
g_str_5fb1ba34e1af06001770e30a='5fb1ba34e1af06001770e30a'
g_base_definitions[g_str_5fb1ba34e1af06001770e30a]={
  id=g_str_5fb1ba34e1af06001770e30a,
  name='War Wagons',
  min=0,
  max=2,
  description='Hussite-style war wagons',
  troop_type="War Wagons",
  troop_option_id="5fb1ba34e1af06001770e308",
}
g_str_5fb1b9e9e1af060017709ce7_camp='5fb1b9e9e1af060017709ce7_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709ce7_camp]={
  id=g_str_5fb1b9e9e1af060017709ce7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709ce7_camp_fortified='5fb1b9e9e1af060017709ce7_camp_fortified'
g_base_definitions[g_str_5fb1b9e9e1af060017709ce7_camp_fortified]={
  id=g_str_5fb1b9e9e1af060017709ce7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba34e1af06001770e2ea_general='5fb1ba34e1af06001770e2ea_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ea_general]={
  id=g_str_5fb1ba34e1af06001770e2ea_general,
  name='Knights General',
  min=2,
  max=1,
  description='Men-at-arms, ministeriales and mercenaries',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e2e9",
}
g_str_5fb1ba34e1af06001770e2ea='5fb1ba34e1af06001770e2ea'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ea]={
  id=g_str_5fb1ba34e1af06001770e2ea,
  name='Knights',
  min=2,
  max=5,
  description='Men-at-arms, ministeriales and mercenaries',
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e2e9",
}
g_str_5fb1ba34e1af06001770e2ed='5fb1ba34e1af06001770e2ed'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ed]={
  id=g_str_5fb1ba34e1af06001770e2ed,
  name='Bad Horse',
  min=0,
  max=1,
  description='Armored crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba34e1af06001770e2ec",
}
g_str_5fb1ba34e1af06001770e2ef='5fb1ba34e1af06001770e2ef'
g_base_definitions[g_str_5fb1ba34e1af06001770e2ef]={
  id=g_str_5fb1ba34e1af06001770e2ef,
  name='Horde',
  min=0,
  max=4,
  description='Feudal retainers or heerban',
  troop_type="Horde",
  troop_option_id="5fb1ba34e1af06001770e2ee",
}
g_str_5fb1ba34e1af06001770e2f1='5fb1ba34e1af06001770e2f1'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f1]={
  id=g_str_5fb1ba34e1af06001770e2f1,
  name='Bow Levy',
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e2f0",
}
g_str_5fb1ba34e1af06001770e2f3='5fb1ba34e1af06001770e2f3'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f3]={
  id=g_str_5fb1ba34e1af06001770e2f3,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e2f2",
}
g_str_5fb1ba34e1af06001770e2f6='5fb1ba34e1af06001770e2f6'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f6]={
  id=g_str_5fb1ba34e1af06001770e2f6,
  name='Archers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e2f5",
}
g_str_5fb1ba34e1af06001770e2f7='5fb1ba34e1af06001770e2f7'
g_base_definitions[g_str_5fb1ba34e1af06001770e2f7]={
  id=g_str_5fb1ba34e1af06001770e2f7,
  name='Skirmishers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e2f5",
}
g_str_5fb1ba34e1af06001770e2fb='5fb1ba34e1af06001770e2fb'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fb]={
  id=g_str_5fb1ba34e1af06001770e2fb,
  name='Horse Bow',
  min=0,
  max=1,
  description='Hungarian horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba34e1af06001770e2f9",
}
g_str_5fb1ba34e1af06001770e2fd='5fb1ba34e1af06001770e2fd'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fd]={
  id=g_str_5fb1ba34e1af06001770e2fd,
  name='Bow Levy',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e2fc",
}
g_str_5fb1ba34e1af06001770e2fe='5fb1ba34e1af06001770e2fe'
g_base_definitions[g_str_5fb1ba34e1af06001770e2fe]={
  id=g_str_5fb1ba34e1af06001770e2fe,
  name='Archers',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e2fc",
}
g_str_5fb1ba34e1af06001770e300='5fb1ba34e1af06001770e300'
g_base_definitions[g_str_5fb1ba34e1af06001770e300]={
  id=g_str_5fb1ba34e1af06001770e300,
  name='Heavy Foot',
  min=0,
  max=2,
  description='City militia spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e2ff",
}
g_str_5fb1ba34e1af06001770e303='5fb1ba34e1af06001770e303'
g_base_definitions[g_str_5fb1ba34e1af06001770e303]={
  id=g_str_5fb1ba34e1af06001770e303,
  name='Skirmishers',
  min=0,
  max=1,
  description='City militia skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e302",
}
g_str_5fb1ba34e1af06001770e307='5fb1ba34e1af06001770e307'
g_base_definitions[g_str_5fb1ba34e1af06001770e307]={
  id=g_str_5fb1ba34e1af06001770e307,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba34e1af06001770e305",
}
g_str_5fb1ba34e1af06001770e30a='5fb1ba34e1af06001770e30a'
g_base_definitions[g_str_5fb1ba34e1af06001770e30a]={
  id=g_str_5fb1ba34e1af06001770e30a,
  name='War Wagons',
  min=0,
  max=2,
  description='Hussite-style war wagons',
  troop_type="War Wagons",
  troop_option_id="5fb1ba34e1af06001770e308",
}
g_str_5fb1b9e9e1af060017709ce7_camp='5fb1b9e9e1af060017709ce7_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709ce7_camp]={
  id=g_str_5fb1b9e9e1af060017709ce7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709ce7_camp_fortified='5fb1b9e9e1af060017709ce7_camp_fortified'
g_base_definitions[g_str_5fb1b9e9e1af060017709ce7_camp_fortified]={
  id=g_str_5fb1b9e9e1af060017709ce7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
