-- 5fb1b9f6e1af06001770a45e Other Melanesian  1100 to 1785 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba44e1af06001770fe56='5fb1ba44e1af06001770fe56'
g_base_definitions[g_str_5fb1ba44e1af06001770fe56]={
  id=g_str_5fb1ba44e1af06001770fe56,
  name='Light Foot',
  min=13,
  max=15,
  description='Tribesmen',
}
g_str_5fb1ba44e1af06001770fe58='5fb1ba44e1af06001770fe58'
g_base_definitions[g_str_5fb1ba44e1af06001770fe58]={
  id=g_str_5fb1ba44e1af06001770fe58,
  name='Skirmishers',
  min=1,
  max=3,
  description='Skirmishing bowmen and slingers',
}
g_str_5fb1ba44e1af06001770fe5a='5fb1ba44e1af06001770fe5a'
g_base_definitions[g_str_5fb1ba44e1af06001770fe5a]={
  name='Light Foot General',
  id=g_str_5fb1ba44e1af06001770fe5a,
  min=1,
  max=1,
}
g_str_5fb1b9f6e1af06001770a45e_camp='5fb1b9f6e1af06001770a45e_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a45e_camp]={
  name='Camp',
  id=g_str_5fb1b9f6e1af06001770a45e_camp,
  min=1,
  max=1,
}
army['5fb1b9f6e1af06001770a45e']={
  data={
    name='Other Melanesian  1100 to 1785 AD'
  },
  g_base_definitions[g_str_5fb1b9f6e1af06001770a45e_camp],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe5a],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe56],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe58],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a45e"] = army["5fb1b9f6e1af06001770a45e"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Other Melanesian  1100 to 1785 AD"] = army["5fb1b9f6e1af06001770a45e"]
