-- 5fb1b9f4e1af06001770a31f Later Kofun Japanese  501 to 645 AD

army['5fb1b9f4e1af06001770a31f']={
  data={
    name='Later Kofun Japanese  501 to 645 AD',
    id='5fb1b9f4e1af06001770a31f',
    dateRange={
      startDate=501,
      endDate=645,
    }
  },
  g_base_definitions[g_str_5fb1ba42e1af06001770fbae_general],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbae],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb0_general],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb0],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb2_general],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb2],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb4],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb5],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb7],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbb9],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbbb],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a31f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a31f"] = army["5fb1b9f4e1af06001770a31f"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Later Kofun Japanese  501 to 645 AD"] = army["5fb1b9f4e1af06001770a31f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Kofun Japanese  501 to 645 AD"] = army["5fb1b9f4e1af06001770a31f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a31f"] = {}
army_dates["5fb1b9f4e1af06001770a31f"]["501 AD to 645 AD"] = {
  startDate=501,
  endDate=645
}
