-- 5fb1b9e7e1af060017709c3a Feudal French  1086 to 1330 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba33e1af06001770e020_general='5fb1ba33e1af06001770e020_general'
g_base_definitions[g_str_5fb1ba33e1af06001770e020_general]={
  id=g_str_5fb1ba33e1af06001770e020_general,
  name='Knights General',
  min=2,
  max=1,
  description='Feudal or mercenary chevaliers',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e01f",
}
g_str_5fb1ba33e1af06001770e020='5fb1ba33e1af06001770e020'
g_base_definitions[g_str_5fb1ba33e1af06001770e020]={
  id=g_str_5fb1ba33e1af06001770e020,
  name='Knights',
  min=2,
  max=4,
  description='Feudal or mercenary chevaliers',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e01f",
}
g_str_5fb1ba33e1af06001770e022_general='5fb1ba33e1af06001770e022_general'
g_base_definitions[g_str_5fb1ba33e1af06001770e022_general]={
  id=g_str_5fb1ba33e1af06001770e022_general,
  name='Knights General',
  min=1,
  max=1,
  description='Sergeants mixed with chevaliers, or fighting separately',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e021",
}
g_str_5fb1ba33e1af06001770e022='5fb1ba33e1af06001770e022'
g_base_definitions[g_str_5fb1ba33e1af06001770e022]={
  id=g_str_5fb1ba33e1af06001770e022,
  name='Knights',
  min=1,
  max=1,
  description='Sergeants mixed with chevaliers, or fighting separately',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e021",
}
g_str_5fb1ba33e1af06001770e023='5fb1ba33e1af06001770e023'
g_base_definitions[g_str_5fb1ba33e1af06001770e023]={
  id=g_str_5fb1ba33e1af06001770e023,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='Sergeants mixed with chevaliers, or fighting separately',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba33e1af06001770e021",
}
g_str_5fb1ba33e1af06001770e025='5fb1ba33e1af06001770e025'
g_base_definitions[g_str_5fb1ba33e1af06001770e025]={
  id=g_str_5fb1ba33e1af06001770e025,
  name='Skirmishers',
  min=1,
  max=1,
  description='Skirmishing or armored crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba33e1af06001770e024",
}
g_str_5fb1ba33e1af06001770e026='5fb1ba33e1af06001770e026'
g_base_definitions[g_str_5fb1ba33e1af06001770e026]={
  id=g_str_5fb1ba33e1af06001770e026,
  name='Archers',
  min=1,
  max=1,
  description='Skirmishing or armored crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e024",
}
g_str_5fb1ba33e1af06001770e028='5fb1ba33e1af06001770e028'
g_base_definitions[g_str_5fb1ba33e1af06001770e028]={
  id=g_str_5fb1ba33e1af06001770e028,
  name='Bow Levy',
  min=0,
  max=3,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e027",
}
g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry='5fb1ba33e1af06001770e028_dismounted_mobile_infantry'
g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry='5fb1ba33e1af06001770e028_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry,
  name='Bow Levy',
  min=0,
  max=1,
  description='Bowmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e027",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry,
  name='Bow Levy',
  min=0,
  max=1,
  description='Bowmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e027",
}
g_str_5fb1ba33e1af06001770e02b='5fb1ba33e1af06001770e02b'
g_base_definitions[g_str_5fb1ba33e1af06001770e02b]={
  id=g_str_5fb1ba33e1af06001770e02b,
  name='Heavy Foot',
  min=2,
  max=6,
  description='Spearmen and communal French militia',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba33e1af06001770e02a",
}
g_str_5fb1ba33e1af06001770e02d='5fb1ba33e1af06001770e02d'
g_base_definitions[g_str_5fb1ba33e1af06001770e02d]={
  id=g_str_5fb1ba33e1af06001770e02d,
  name='Archers',
  min=0,
  max=1,
  description='Genoese mercenary crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e02c",
}
g_str_5fb1ba33e1af06001770e02f='5fb1ba33e1af06001770e02f'
g_base_definitions[g_str_5fb1ba33e1af06001770e02f]={
  id=g_str_5fb1ba33e1af06001770e02f,
  name='Light Foot',
  min=0,
  max=1,
  description='Bidets, bidowers or Bretons: light-armed infantry with spear and buckler',
  troop_type="Light Foot",
  troop_option_id="5fb1ba33e1af06001770e02e",
}
g_str_5fb1ba33e1af06001770e031='5fb1ba33e1af06001770e031'
g_base_definitions[g_str_5fb1ba33e1af06001770e031]={
  id=g_str_5fb1ba33e1af06001770e031,
  name='Rabble',
  min=0,
  max=2,
  description='Ribauds',
  troop_type="Rabble",
  troop_option_id="5fb1ba33e1af06001770e030",
}
g_str_5fb1ba33e1af06001770e033='5fb1ba33e1af06001770e033'
g_base_definitions[g_str_5fb1ba33e1af06001770e033]={
  id=g_str_5fb1ba33e1af06001770e033,
  name='Horde',
  min=0,
  max=2,
  description='Peasant levies',
  troop_type="Horde",
  troop_option_id="5fb1ba33e1af06001770e032",
}
g_str_5fb1ba33e1af06001770e036='5fb1ba33e1af06001770e036'
g_base_definitions[g_str_5fb1ba33e1af06001770e036]={
  id=g_str_5fb1ba33e1af06001770e036,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Aragonese horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba33e1af06001770e034",
}
g_str_5fb1ba33e1af06001770e039='5fb1ba33e1af06001770e039'
g_base_definitions[g_str_5fb1ba33e1af06001770e039]={
  id=g_str_5fb1ba33e1af06001770e039,
  name='Light Foot',
  min=0,
  max=1,
  description='Gascon, Navarrese, or Basque dardiers or Almughavars',
  troop_type="Light Foot",
  troop_option_id="5fb1ba33e1af06001770e037",
}
g_str_5fb1ba33e1af06001770e03c='5fb1ba33e1af06001770e03c'
g_base_definitions[g_str_5fb1ba33e1af06001770e03c]={
  id=g_str_5fb1ba33e1af06001770e03c,
  name='Pikes',
  min=0,
  max=2,
  description='Low Countries mercenary spearmen',
  troop_type="Pikes",
  troop_option_id="5fb1ba33e1af06001770e03a",
}
g_str_5fb1b9e7e1af060017709c3a_camp='5fb1b9e7e1af060017709c3a_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp]={
  id=g_str_5fb1b9e7e1af060017709c3a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e7e1af060017709c3a_camp_fortified='5fb1b9e7e1af060017709c3a_camp_fortified'
g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp_fortified]={
  id=g_str_5fb1b9e7e1af060017709c3a_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e7e1af060017709c3a']={
  data={
    name='Feudal French  1086 to 1330 AD'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e020_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e020],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022],
  g_base_definitions[g_str_5fb1ba33e1af06001770e023],
  g_base_definitions[g_str_5fb1ba33e1af06001770e025],
  g_base_definitions[g_str_5fb1ba33e1af06001770e026],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02b],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02f],
  g_base_definitions[g_str_5fb1ba33e1af06001770e031],
  g_base_definitions[g_str_5fb1ba33e1af06001770e033],
  g_base_definitions[g_str_5fb1ba33e1af06001770e036],
  g_base_definitions[g_str_5fb1ba33e1af06001770e039],
  g_base_definitions[g_str_5fb1ba33e1af06001770e03c],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c3a"] = army["5fb1b9e7e1af060017709c3a"]
army['5fb1b9e7e1af060017709c3a_1086_1149']={
  data={
    name='Feudal French 1086 AD to 1149 AD'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e020_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e020],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022],
  g_base_definitions[g_str_5fb1ba33e1af06001770e023],
  g_base_definitions[g_str_5fb1ba33e1af06001770e025],
  g_base_definitions[g_str_5fb1ba33e1af06001770e026],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02b],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02f],
  g_base_definitions[g_str_5fb1ba33e1af06001770e031],
  g_base_definitions[g_str_5fb1ba33e1af06001770e033],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp_fortified],
}
army['5fb1b9e7e1af060017709c3a_1150_1330']={
  data={
    name='Feudal French 1150 AD to 1330 AD'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e020_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e020],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022],
  g_base_definitions[g_str_5fb1ba33e1af06001770e023],
  g_base_definitions[g_str_5fb1ba33e1af06001770e025],
  g_base_definitions[g_str_5fb1ba33e1af06001770e026],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02b],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02f],
  g_base_definitions[g_str_5fb1ba33e1af06001770e031],
  g_base_definitions[g_str_5fb1ba33e1af06001770e033],
  g_base_definitions[g_str_5fb1ba33e1af06001770e036],
  g_base_definitions[g_str_5fb1ba33e1af06001770e039],
  g_base_definitions[g_str_5fb1ba33e1af06001770e03c],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp_fortified],
}
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c3a"] = {}
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1330 AD"] ="5fb1b9e7e1af060017709c3a"
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1149 AD"] ="5fb1b9e7e1af060017709c3a_1086_1149"
army_dates["5fb1b9e7e1af060017709c3a"]["1150 AD to 1330 AD"] ="5fb1b9e7e1af060017709c3a_1150_1330"
