troop_options['5fb1ba27e1af06001770c937'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-321,
    endDate=-301,
  }
}
troop_options['5fb1ba27e1af06001770c93a'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-300,
    endDate=-212,
  }
}
troop_options['5fb1ba27e1af06001770c93e'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-320,
    endDate=-145,
  }
}
troop_options['5fb1ba27e1af06001770c940'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-320,
    endDate=-145,
  }
}
troop_options['5fb1ba27e1af06001770c942'] = {
  min=4,
  max=12,
  dateRange={
    startDate=-320,
    endDate=-145,
  }
}
troop_options['5fb1ba27e1af06001770c944'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-320,
    endDate=-145,
  }
}
-- allies
