-- 5fb1b9e0e1af0600177097ff Roman Armenian  245 to 428 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2be1af06001770d19b_general='5fb1ba2be1af06001770d19b_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d19b_general]={
  id=g_str_5fb1ba2be1af06001770d19b_general,
  name='Cataphracts General',
  min=1,
  max=1,
  description='Cataphracts, or nobles armed in the "Sassanid" style',
  general=true,
}
g_str_5fb1ba2be1af06001770d19b='5fb1ba2be1af06001770d19b'
g_base_definitions[g_str_5fb1ba2be1af06001770d19b]={
  id=g_str_5fb1ba2be1af06001770d19b,
  name='Cataphracts',
  min=1,
  max=3,
  description='Cataphracts, or nobles armed in the "Sassanid" style',
}
g_str_5fb1ba2be1af06001770d19c_general='5fb1ba2be1af06001770d19c_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d19c_general]={
  id=g_str_5fb1ba2be1af06001770d19c_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Cataphracts, or nobles armed in the "Sassanid" style',
  general=true,
}
g_str_5fb1ba2be1af06001770d19c='5fb1ba2be1af06001770d19c'
g_base_definitions[g_str_5fb1ba2be1af06001770d19c]={
  id=g_str_5fb1ba2be1af06001770d19c,
  name='Elite Cavalary',
  min=1,
  max=3,
  description='Cataphracts, or nobles armed in the "Sassanid" style',
}
g_str_5fb1ba2be1af06001770d19e='5fb1ba2be1af06001770d19e'
g_base_definitions[g_str_5fb1ba2be1af06001770d19e]={
  id=g_str_5fb1ba2be1af06001770d19e,
  name='Horse Bow',
  min=3,
  max=5,
  description='Horse archers',
}
g_str_5fb1ba2be1af06001770d1a0='5fb1ba2be1af06001770d1a0'
g_base_definitions[g_str_5fb1ba2be1af06001770d1a0]={
  id=g_str_5fb1ba2be1af06001770d1a0,
  name='Bow Levy',
  min=2,
  max=5,
  description='Bowmen',
}
g_str_5fb1ba2be1af06001770d1a2='5fb1ba2be1af06001770d1a2'
g_base_definitions[g_str_5fb1ba2be1af06001770d1a2]={
  id=g_str_5fb1ba2be1af06001770d1a2,
  name='Light Foot',
  min=2,
  max=8,
  description='Javelinmen',
}
g_str_5fb1ba2be1af06001770d1a4='5fb1ba2be1af06001770d1a4'
g_base_definitions[g_str_5fb1ba2be1af06001770d1a4]={
  id=g_str_5fb1ba2be1af06001770d1a4,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
}
g_str_5fb1b9e0e1af0600177097ff_camp='5fb1b9e0e1af0600177097ff_camp'
g_base_definitions[g_str_5fb1b9e0e1af0600177097ff_camp]={
  name='Camp',
  id=g_str_5fb1b9e0e1af0600177097ff_camp,
  min=1,
  max=1,
}
army['5fb1b9e0e1af0600177097ff']={
  data={
    name='Roman Armenian  245 to 428 AD'
  },
  g_base_definitions[g_str_5fb1b9e0e1af0600177097ff_camp],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1a6],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1a7],
  g_base_definitions[g_str_5fb1ba2be1af06001770d19b_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d19b],
  g_base_definitions[g_str_5fb1ba2be1af06001770d19c_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d19c],
  g_base_definitions[g_str_5fb1ba2be1af06001770d19e],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1a0],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1a2],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1a4],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097ff"] = army["5fb1b9e0e1af0600177097ff"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Roman Armenian  245 to 428 AD"] = army["5fb1b9e0e1af0600177097ff"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Roman Armenian  245 to 428 AD"] = army["5fb1b9e0e1af0600177097ff"]
