-- 5fb1b9f3e1af06001770a28e Shatuo Chinese Dynasties  924 to 951 AD

army['5fb1b9f3e1af06001770a28e']={
  data={
    name='Shatuo Chinese Dynasties  924 to 951 AD',
    id='5fb1b9f3e1af06001770a28e',
    army_id='5fb1b9f3e1af06001770a28e'
  },
  g_base_definitions[g_str_5fb1ba40e1af06001770f94d_general],
  g_base_definitions[g_str_5fb1ba40e1af06001770f94d],
  g_base_definitions[g_str_5fb1ba40e1af06001770f94f],
  g_base_definitions[g_str_5fb1ba40e1af06001770f951],
  g_base_definitions[g_str_5fb1ba40e1af06001770f953_general],
  g_base_definitions[g_str_5fb1ba40e1af06001770f953],
  g_base_definitions[g_str_5fb1ba40e1af06001770f955],
  g_base_definitions[g_str_5fb1ba40e1af06001770f957],
  g_base_definitions[g_str_5fb1ba40e1af06001770f958],
  g_base_definitions[g_str_5fb1ba40e1af06001770f95a],
  g_base_definitions[g_str_5fb1ba40e1af06001770f95c],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a28e_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a28e_camp_pack_train],
  g_base_definitions[g_str_5fb1ba18e1af06001770baf1],
  g_base_definitions[g_str_5fb1ba18e1af06001770baf3],
  g_base_definitions[g_str_5fb1ba18e1af06001770baf5],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a28e"] = army["5fb1b9f3e1af06001770a28e"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Shatuo Chinese Dynasties  924 to 951 AD"] = army["5fb1b9f3e1af06001770a28e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Shatuo Chinese Dynasties  924 to 951 AD"] = army["5fb1b9f3e1af06001770a28e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a28e"] = {}
army_dates["5fb1b9f3e1af06001770a28e"]["924 AD to 951 AD"] ="5fb1b9f3e1af06001770a28e"
