troop_options['5fb1ba28e1af06001770cbff'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-300,
    endDate=-275,
  }
}
troop_options['5fb1ba28e1af06001770cc02'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-300,
    endDate=-275,
  }
}
troop_options['5fb1ba28e1af06001770cc06'] = {
  min=2,
  max=3,
  dateRange={
    startDate=-274,
    endDate=-272,
  }
}
troop_options['5fb1ba28e1af06001770cc09'] = {
  min=4,
  max=12,
  dateRange={
    startDate=-300,
    endDate=-272,
  }
}
troop_options['5fb1ba28e1af06001770cc0c'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-300,
    endDate=-272,
  }
}
troop_options['5fb1ba28e1af06001770cc0e'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-300,
    endDate=-272,
  }
}
troop_options['5fb1ba28e1af06001770cc10'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-287,
    endDate=-272,
  }
}
troop_options['5fb1ba28e1af06001770cc14'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-274,
    endDate=-272,
  }
}
-- allies
