-- 5fb1b9d9e1af060017709335 Early Egyptian  3000 to 1541 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba1fe1af06001770bf7c_general='5fb1ba1fe1af06001770bf7c_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf7c_general]={
  id=g_str_5fb1ba1fe1af06001770bf7c_general,
  name='Elite Foot General',
  min=1,
  max=1,
  description='Bodyguards armed with axe and large shield',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba1fe1af06001770bf7a",
}
g_str_5fb1ba1fe1af06001770bf7c='5fb1ba1fe1af06001770bf7c'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf7c]={
  id=g_str_5fb1ba1fe1af06001770bf7c,
  name='Elite Foot',
  min=1,
  max=1,
  description='Bodyguards armed with axe and large shield',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba1fe1af06001770bf7a",
}
g_str_5fb1ba1fe1af06001770bf7f_general='5fb1ba1fe1af06001770bf7f_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf7f_general]={
  id=g_str_5fb1ba1fe1af06001770bf7f_general,
  name='Chariots General',
  min=1,
  max=1,
  description='2-horse chariots or Bodyguards armed with axe and large shield',
  general=true,
  troop_type="Chariots",
  troop_option_id="5fb1ba1fe1af06001770bf7d",
}
g_str_5fb1ba1fe1af06001770bf7f='5fb1ba1fe1af06001770bf7f'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf7f]={
  id=g_str_5fb1ba1fe1af06001770bf7f,
  name='Chariots',
  min=1,
  max=1,
  description='2-horse chariots or Bodyguards armed with axe and large shield',
  troop_type="Chariots",
  troop_option_id="5fb1ba1fe1af06001770bf7d",
}
g_str_5fb1ba1fe1af06001770bf80_general='5fb1ba1fe1af06001770bf80_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf80_general]={
  id=g_str_5fb1ba1fe1af06001770bf80_general,
  name='Elite Foot General',
  min=1,
  max=1,
  description='2-horse chariots or Bodyguards armed with axe and large shield',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba1fe1af06001770bf7d",
}
g_str_5fb1ba1fe1af06001770bf80='5fb1ba1fe1af06001770bf80'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf80]={
  id=g_str_5fb1ba1fe1af06001770bf80,
  name='Elite Foot',
  min=1,
  max=1,
  description='2-horse chariots or Bodyguards armed with axe and large shield',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba1fe1af06001770bf7d",
}
g_str_5fb1ba1fe1af06001770bf82='5fb1ba1fe1af06001770bf82'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf82]={
  id=g_str_5fb1ba1fe1af06001770bf82,
  name='Bow Levy',
  min=4,
  max=8,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba1fe1af06001770bf81",
}
g_str_5fb1ba1fe1af06001770bf84='5fb1ba1fe1af06001770bf84'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf84]={
  id=g_str_5fb1ba1fe1af06001770bf84,
  name='Raiders',
  min=4,
  max=8,
  description='Menfat',
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770bf83",
}
g_str_5fb1ba1fe1af06001770bf85='5fb1ba1fe1af06001770bf85'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf85]={
  id=g_str_5fb1ba1fe1af06001770bf85,
  name='Heavy Foot',
  min=4,
  max=8,
  description='Menfat',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba1fe1af06001770bf83",
}
g_str_5fb1ba1fe1af06001770bf87='5fb1ba1fe1af06001770bf87'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf87]={
  id=g_str_5fb1ba1fe1af06001770bf87,
  name='Horde',
  min=2,
  max=6,
  description='Conscripts',
  troop_type="Horde",
  troop_option_id="5fb1ba1fe1af06001770bf86",
}
g_str_5fb1ba1fe1af06001770bf89='5fb1ba1fe1af06001770bf89'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf89]={
  id=g_str_5fb1ba1fe1af06001770bf89,
  name='Skirmishers',
  min=0,
  max=1,
  description='Javelinmen paired with quiver-carriers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba1fe1af06001770bf88",
}
g_str_5fb1ba1fe1af06001770bf8b='5fb1ba1fe1af06001770bf8b'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf8b]={
  id=g_str_5fb1ba1fe1af06001770bf8b,
  name='Archers',
  min=1,
  max=2,
  description='Medjay and other Nubian bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770bf8a",
}
g_str_5fb1ba1fe1af06001770bf8c='5fb1ba1fe1af06001770bf8c'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf8c]={
  id=g_str_5fb1ba1fe1af06001770bf8c,
  name='Skirmishers',
  min=1,
  max=2,
  description='Medjay and other Nubian bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba1fe1af06001770bf8a",
}
g_str_5fb1ba1fe1af06001770bf8e='5fb1ba1fe1af06001770bf8e'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf8e]={
  id=g_str_5fb1ba1fe1af06001770bf8e,
  name='Rabble',
  min=0,
  max=2,
  description='Libyan javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba1fe1af06001770bf8d",
}
g_str_5fb1ba1fe1af06001770bf90='5fb1ba1fe1af06001770bf90'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf90]={
  id=g_str_5fb1ba1fe1af06001770bf90,
  name='Skirmishers',
  min=0,
  max=1,
  description='Bedouin slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba1fe1af06001770bf8f",
}
g_str_5fb1b9d9e1af060017709335_camp='5fb1b9d9e1af060017709335_camp'
g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp]={
  id=g_str_5fb1b9d9e1af060017709335_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d9e1af060017709335_camp_pack_train='5fb1b9d9e1af060017709335_camp_pack_train'
g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp_pack_train]={
  id=g_str_5fb1b9d9e1af060017709335_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9d9e1af060017709335']={
  data={
    name='Early Egyptian  3000 to 1541 BC'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7c_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7f_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7f],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf80_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf80],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf82],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf84],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf85],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf87],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf89],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8b],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8e],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf90],
  g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709335"] = army["5fb1b9d9e1af060017709335"]
army['5fb1b9d9e1af060017709335_-3000_-1690']={
  data={
    name='Early Egyptian 3000 BC to 1690 BC'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7c_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf82],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf84],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf85],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf87],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf89],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8b],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8e],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf90],
  g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp_pack_train],
}
army['5fb1b9d9e1af060017709335_-1689_-1541']={
  data={
    name='Early Egyptian 1689 BC to 1541 BC'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7f_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf7f],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf80_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf80],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf82],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf84],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf85],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf87],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf89],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8b],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf8e],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf90],
  g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709335_camp_pack_train],
}
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Early Egyptian  3000 to 1541 BC"] = army["5fb1b9d9e1af060017709335"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Egyptian  3000 to 1541 BC"] = army["5fb1b9d9e1af060017709335"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709335"] = {}
army_dates["5fb1b9d9e1af060017709335"]["3000 BC to 1541 BC"] ="5fb1b9d9e1af060017709335"
army_dates["5fb1b9d9e1af060017709335"]["3000 BC to 1690 BC"] ="5fb1b9d9e1af060017709335_-3000_-1690"
army_dates["5fb1b9d9e1af060017709335"]["1689 BC to 1541 BC"] ="5fb1b9d9e1af060017709335_-1689_-1541"
