-- 5fb1b9e1e1af060017709849 Early German  115 BC to 250 AD

army['5fb1b9e1e1af060017709849']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Early German  115 BC to 250 AD',
    id='5fb1b9e1e1af060017709849',
    dateRange={
      startDate=-115,
      endDate=250,
    }
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_general_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ae_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b1_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b1],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b3],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b5],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2b7],
  g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af060017709849_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709849"] = army["5fb1b9e1e1af060017709849"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early German  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709849"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Early German  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709849"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early German  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709849"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709849"] = {}
army_dates["5fb1b9e1e1af060017709849"]["115 BC to 250 AD"] = {
  startDate=-115,
  endDate=250
}
army_dates["5fb1b9e1e1af060017709849"]["115 BC to 114 BC"] = {
  startDate=-115,
  endDate=-114
}
army_dates["5fb1b9e1e1af060017709849"]["113 BC to 102 BC"] = {
  startDate=-113,
  endDate=-102
}
army_dates["5fb1b9e1e1af060017709849"]["101 BC to 100 BC"] = {
  startDate=-101,
  endDate=-100
}
army_dates["5fb1b9e1e1af060017709849"]["99 BC to 50 BC"] = {
  startDate=-99,
  endDate=-50
}
army_dates["5fb1b9e1e1af060017709849"]["49 BC to 87 AD"] = {
  startDate=-49,
  endDate=87
}
army_dates["5fb1b9e1e1af060017709849"]["88 AD to 93 AD"] = {
  startDate=88,
  endDate=93
}
army_dates["5fb1b9e1e1af060017709849"]["94 AD to 250 AD"] = {
  startDate=94,
  endDate=250
}
