-- 5fb1b9f5e1af06001770a393 Minor Mexican City-States  600 BC to 950 AD

army['5fb1b9f5e1af06001770a393']={
  data={
    name='Minor Mexican City-States  600 BC to 950 AD',
    id='5fb1b9f5e1af06001770a393',
    army_id='5fb1b9f5e1af06001770a393'
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fd10_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd10],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd12],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd14],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a393_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a393"] = army["5fb1b9f5e1af06001770a393"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Minor Mexican City-States  600 BC to 950 AD"] = army["5fb1b9f5e1af06001770a393"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Minor Mexican City-States  600 BC to 950 AD"] = army["5fb1b9f5e1af06001770a393"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Minor Mexican City-States  600 BC to 950 AD"] = army["5fb1b9f5e1af06001770a393"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a393"] = {}
army_dates["5fb1b9f5e1af06001770a393"]["600 BC to 950 AD"] ="5fb1b9f5e1af06001770a393"
