g_str_5fb1ba2ce1af06001770d430_general='5fb1ba2ce1af06001770d430_general'
g_base_definitions[g_str_5fb1ba2ce1af06001770d430_general]={
  id=g_str_5fb1ba2ce1af06001770d430_general,
  name='Knights General',
  min=1,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba2ce1af06001770d42f",
}
g_str_5fb1ba2ce1af06001770d430='5fb1ba2ce1af06001770d430'
g_base_definitions[g_str_5fb1ba2ce1af06001770d430]={
  id=g_str_5fb1ba2ce1af06001770d430,
  name='Knights',
  min=1,
  max=1,
  description='Noble horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba2ce1af06001770d42f",
}
g_str_5fb1ba2ce1af06001770d432='5fb1ba2ce1af06001770d432'
g_base_definitions[g_str_5fb1ba2ce1af06001770d432]={
  id=g_str_5fb1ba2ce1af06001770d432,
  name='Warriors',
  min=8,
  max=14,
  description='Fierce fighting infantry',
  troop_type="Warriors",
  troop_option_id="5fb1ba2ce1af06001770d431",
}
g_str_5fb1ba2ce1af06001770d434='5fb1ba2ce1af06001770d434'
g_base_definitions[g_str_5fb1ba2ce1af06001770d434]={
  id=g_str_5fb1ba2ce1af06001770d434,
  name='Bow Levy',
  min=0,
  max=1,
  description='Close-order bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba2ce1af06001770d433",
}
g_str_5fb1ba2ce1af06001770d436='5fb1ba2ce1af06001770d436'
g_base_definitions[g_str_5fb1ba2ce1af06001770d436]={
  id=g_str_5fb1ba2ce1af06001770d436,
  name='Skirmishers',
  min=0,
  max=4,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2ce1af06001770d435",
}
g_str_5fb1ba2ce1af06001770d438='5fb1ba2ce1af06001770d438'
g_base_definitions[g_str_5fb1ba2ce1af06001770d438]={
  id=g_str_5fb1ba2ce1af06001770d438,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Roman heavy infantry',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2ce1af06001770d437",
}
g_str_5fb1ba2ce1af06001770d43a='5fb1ba2ce1af06001770d43a'
g_base_definitions[g_str_5fb1ba2ce1af06001770d43a]={
  id=g_str_5fb1ba2ce1af06001770d43a,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Roman horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2ce1af06001770d439",
}
g_str_5fb1b9e2e1af0600177098bb_camp='5fb1b9e2e1af0600177098bb_camp'
g_base_definitions[g_str_5fb1b9e2e1af0600177098bb_camp]={
  id=g_str_5fb1b9e2e1af0600177098bb_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af0600177098bb_camp_fortified='5fb1b9e2e1af0600177098bb_camp_fortified'
g_base_definitions[g_str_5fb1b9e2e1af0600177098bb_camp_fortified]={
  id=g_str_5fb1b9e2e1af0600177098bb_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
