troop_options['5fb1ba20e1af06001770bfdb'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-1213,
    endDate=-665,
  }
}
troop_options['5fb1ba20e1af06001770bfdd'] = {
  min=0,
  max=8,
  dateRange={
    startDate=-1213,
    endDate=-665,
  }
}
troop_options['5fb1ba20e1af06001770bfdf'] = {
  min=6,
  max=20,
  dateRange={
    startDate=-1213,
    endDate=-665,
  }
}
troop_options['5fb1ba20e1af06001770bfe1'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-1000,
    endDate=-665,
  }
}
troop_options['5fb1ba20e1af06001770bfe4'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-1213,
    endDate=-665,
  }
}
troop_options['5fb1ba20e1af06001770bfe7'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-1213,
    endDate=-665,
  }
}
-- allies
