g_str_5fb1ba1fe1af06001770bed5_general='5fb1ba1fe1af06001770bed5_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed5_general]={
  id=g_str_5fb1ba1fe1af06001770bed5_general,
  name='Archers General',
  min=1,
  max=1,
  description='Retainers',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed5='5fb1ba1fe1af06001770bed5'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed5]={
  id=g_str_5fb1ba1fe1af06001770bed5,
  name='Archers',
  min=1,
  max=3,
  description='Retainers',
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed6_general='5fb1ba1fe1af06001770bed6_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed6_general]={
  id=g_str_5fb1ba1fe1af06001770bed6_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Retainers',
  general=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed6='5fb1ba1fe1af06001770bed6'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed6]={
  id=g_str_5fb1ba1fe1af06001770bed6,
  name='Raiders',
  min=1,
  max=3,
  description='Retainers',
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed8_general='5fb1ba1fe1af06001770bed8_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed8_general]={
  id=g_str_5fb1ba1fe1af06001770bed8_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770bed7",
}
g_str_5fb1ba1fe1af06001770bed8='5fb1ba1fe1af06001770bed8'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed8]={
  id=g_str_5fb1ba1fe1af06001770bed8,
  name='Battle Taxi',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770bed7",
}
g_str_5fb1ba1fe1af06001770beda='5fb1ba1fe1af06001770beda'
g_base_definitions[g_str_5fb1ba1fe1af06001770beda]={
  id=g_str_5fb1ba1fe1af06001770beda,
  name='Bow Levy',
  min=9,
  max=22,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba1fe1af06001770bed9",
}
g_str_5fb1b9d8e1af060017709306_camp='5fb1b9d8e1af060017709306_camp'
g_base_definitions[g_str_5fb1b9d8e1af060017709306_camp]={
  id=g_str_5fb1b9d8e1af060017709306_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d8e1af060017709306_camp_pack_train='5fb1b9d8e1af060017709306_camp_pack_train'
g_base_definitions[g_str_5fb1b9d8e1af060017709306_camp_pack_train]={
  id=g_str_5fb1b9d8e1af060017709306_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba1fe1af06001770bed5_general='5fb1ba1fe1af06001770bed5_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed5_general]={
  id=g_str_5fb1ba1fe1af06001770bed5_general,
  name='Archers General',
  min=1,
  max=1,
  description='Retainers',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed5='5fb1ba1fe1af06001770bed5'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed5]={
  id=g_str_5fb1ba1fe1af06001770bed5,
  name='Archers',
  min=1,
  max=3,
  description='Retainers',
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed6_general='5fb1ba1fe1af06001770bed6_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed6_general]={
  id=g_str_5fb1ba1fe1af06001770bed6_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Retainers',
  general=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed6='5fb1ba1fe1af06001770bed6'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed6]={
  id=g_str_5fb1ba1fe1af06001770bed6,
  name='Raiders',
  min=1,
  max=3,
  description='Retainers',
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed8_general='5fb1ba1fe1af06001770bed8_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed8_general]={
  id=g_str_5fb1ba1fe1af06001770bed8_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770bed7",
}
g_str_5fb1ba1fe1af06001770bed8='5fb1ba1fe1af06001770bed8'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed8]={
  id=g_str_5fb1ba1fe1af06001770bed8,
  name='Battle Taxi',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770bed7",
}
g_str_5fb1ba1fe1af06001770beda='5fb1ba1fe1af06001770beda'
g_base_definitions[g_str_5fb1ba1fe1af06001770beda]={
  id=g_str_5fb1ba1fe1af06001770beda,
  name='Bow Levy',
  min=9,
  max=22,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba1fe1af06001770bed9",
}
g_str_5fb1b9d8e1af060017709306_camp='5fb1b9d8e1af060017709306_camp'
g_base_definitions[g_str_5fb1b9d8e1af060017709306_camp]={
  id=g_str_5fb1b9d8e1af060017709306_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d8e1af060017709306_camp_pack_train='5fb1b9d8e1af060017709306_camp_pack_train'
g_base_definitions[g_str_5fb1b9d8e1af060017709306_camp_pack_train]={
  id=g_str_5fb1b9d8e1af060017709306_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba1fe1af06001770bed5_general='5fb1ba1fe1af06001770bed5_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed5_general]={
  id=g_str_5fb1ba1fe1af06001770bed5_general,
  name='Archers General',
  min=1,
  max=1,
  description='Retainers',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed5='5fb1ba1fe1af06001770bed5'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed5]={
  id=g_str_5fb1ba1fe1af06001770bed5,
  name='Archers',
  min=1,
  max=3,
  description='Retainers',
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed6_general='5fb1ba1fe1af06001770bed6_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed6_general]={
  id=g_str_5fb1ba1fe1af06001770bed6_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Retainers',
  general=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed6='5fb1ba1fe1af06001770bed6'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed6]={
  id=g_str_5fb1ba1fe1af06001770bed6,
  name='Raiders',
  min=1,
  max=3,
  description='Retainers',
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770bed4",
}
g_str_5fb1ba1fe1af06001770bed8_general='5fb1ba1fe1af06001770bed8_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed8_general]={
  id=g_str_5fb1ba1fe1af06001770bed8_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770bed7",
}
g_str_5fb1ba1fe1af06001770bed8='5fb1ba1fe1af06001770bed8'
g_base_definitions[g_str_5fb1ba1fe1af06001770bed8]={
  id=g_str_5fb1ba1fe1af06001770bed8,
  name='Battle Taxi',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770bed7",
}
g_str_5fb1ba1fe1af06001770beda='5fb1ba1fe1af06001770beda'
g_base_definitions[g_str_5fb1ba1fe1af06001770beda]={
  id=g_str_5fb1ba1fe1af06001770beda,
  name='Bow Levy',
  min=9,
  max=22,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba1fe1af06001770bed9",
}
g_str_5fb1b9d8e1af060017709306_camp='5fb1b9d8e1af060017709306_camp'
g_base_definitions[g_str_5fb1b9d8e1af060017709306_camp]={
  id=g_str_5fb1b9d8e1af060017709306_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d8e1af060017709306_camp_pack_train='5fb1b9d8e1af060017709306_camp_pack_train'
g_base_definitions[g_str_5fb1b9d8e1af060017709306_camp_pack_train]={
  id=g_str_5fb1b9d8e1af060017709306_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
