troop_options['615351a203385c0016b857fb'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b857fd'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b857ff'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b85801'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b85803'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b85805'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b85807'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b85809'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b8580b'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b8580d'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b85811'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
troop_options['615351a203385c0016b85814'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-275,
    endDate=-203,
  }
}
-- allies
