-- 5fb1b9e5e1af060017709af5 Medieval Irish  1300 to 1515 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba31e1af06001770dbd0_general='5fb1ba31e1af06001770dbd0_general'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_general]={
  id=g_str_5fb1ba31e1af06001770dbd0_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Irish horsemen armed with javelins',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dbcf",
}
g_str_5fb1ba31e1af06001770dbd0_general_dismounted='5fb1ba31e1af06001770dbd0_general_dismounted'
g_str_5fb1ba31e1af06001770dbd0_general_mounted='5fb1ba31e1af06001770dbd0_general_mounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_general_dismounted]={
  id=g_str_5fb1ba31e1af06001770dbd0_general_dismounted,
  name='Light Foot General',
  min=1,
  max=1,
  description='Irish horsemen armed with javelins\nMid-battle dismounted from Javelin Cavalry General',
  dismounted_from=g_str_5fb1ba31e1af06001770dbd0_general_mounted,
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba31e1af06001770dbcf",
}
g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_general_mounted]={
  id=g_str_5fb1ba31e1af06001770dbd0_general_mounted,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Irish horsemen armed with javelins\nMid-battle dismounting as Light Foot',
  dismount_as=g_str_5fb1ba31e1af06001770dbd0_general_dismounted,
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dbcf",
}
g_str_5fb1ba31e1af06001770dbd0='5fb1ba31e1af06001770dbd0'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd0]={
  id=g_str_5fb1ba31e1af06001770dbd0,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Irish horsemen armed with javelins',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dbcf",
}
g_str_5fb1ba31e1af06001770dbd0_dismounted='5fb1ba31e1af06001770dbd0_dismounted'
g_str_5fb1ba31e1af06001770dbd0_mounted='5fb1ba31e1af06001770dbd0_mounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_dismounted]={
  id=g_str_5fb1ba31e1af06001770dbd0_dismounted,
  name='Light Foot',
  min=1,
  max=3,
  description='Irish horsemen armed with javelins\nMid-battle dismounted from Javelin Cavalry',
  dismounted_from=g_str_5fb1ba31e1af06001770dbd0_mounted,
  troop_type="Light Foot",
  troop_option_id="5fb1ba31e1af06001770dbcf",
}
g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_mounted]={
  id=g_str_5fb1ba31e1af06001770dbd0_mounted,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Irish horsemen armed with javelins\nMid-battle dismounting as Light Foot',
  dismount_as=g_str_5fb1ba31e1af06001770dbd0_dismounted,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dbcf",
}
g_str_5fb1ba31e1af06001770dbd3='5fb1ba31e1af06001770dbd3'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd3]={
  id=g_str_5fb1ba31e1af06001770dbd3,
  name='Elite Foot',
  min=0,
  max=4,
  description='Galloglaich',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba31e1af06001770dbd2",
}
g_str_5fb1ba31e1af06001770dbd5='5fb1ba31e1af06001770dbd5'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd5]={
  id=g_str_5fb1ba31e1af06001770dbd5,
  name='Light Foot',
  min=6,
  max=12,
  description='Kern javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba31e1af06001770dbd4",
}
g_str_5fb1ba31e1af06001770dbd7='5fb1ba31e1af06001770dbd7'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd7]={
  id=g_str_5fb1ba31e1af06001770dbd7,
  name='Skirmishers',
  min=1,
  max=3,
  description='Kern bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba31e1af06001770dbd6",
}
g_str_5fb1ba31e1af06001770dbd9='5fb1ba31e1af06001770dbd9'
g_base_definitions[g_str_5fb1ba31e1af06001770dbd9]={
  id=g_str_5fb1ba31e1af06001770dbd9,
  name='Rabble',
  min=0,
  max=12,
  description='\'Rising out\'',
  troop_type="Rabble",
  troop_option_id="5fb1ba31e1af06001770dbd8",
}
g_str_5fb1b9e5e1af060017709af5_camp='5fb1b9e5e1af060017709af5_camp'
g_base_definitions[g_str_5fb1b9e5e1af060017709af5_camp]={
  id=g_str_5fb1b9e5e1af060017709af5_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e5e1af060017709af5_camp_fortified='5fb1b9e5e1af060017709af5_camp_fortified'
g_base_definitions[g_str_5fb1b9e5e1af060017709af5_camp_fortified]={
  id=g_str_5fb1b9e5e1af060017709af5_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
g_str_5fb1b9e5e1af060017709af5_camp_pack_train='5fb1b9e5e1af060017709af5_camp_pack_train'
g_base_definitions[g_str_5fb1b9e5e1af060017709af5_camp_pack_train]={
  id=g_str_5fb1b9e5e1af060017709af5_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e5e1af060017709af5']={
  data={
    name='Medieval Irish  1300 to 1515 AD',
    id='5fb1b9e5e1af060017709af5',
    army_id='5fb1b9e5e1af060017709af5'
  },
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_general],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_general_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_general_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd0],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd0_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd3],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd5],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd7],
  g_base_definitions[g_str_5fb1ba31e1af06001770dbd9],
  g_base_definitions[g_str_5fb1b9e5e1af060017709af5_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709af5_camp_fortified],
  g_base_definitions[g_str_5fb1b9e5e1af060017709af5_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709af5"] = army["5fb1b9e5e1af060017709af5"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Medieval Irish  1300 to 1515 AD"] = army["5fb1b9e5e1af060017709af5"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Irish  1300 to 1515 AD"] = army["5fb1b9e5e1af060017709af5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Irish  1300 to 1515 AD"] = army["5fb1b9e5e1af060017709af5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e5e1af060017709af5"] = {}
army_dates["5fb1b9e5e1af060017709af5"]["1300 AD to 1515 AD"] ="5fb1b9e5e1af060017709af5"
