-- 5fb1b9ebe1af060017709e85 Nikaian Byzantine  1204 to 1261 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba38e1af06001770e9a1='5fb1ba38e1af06001770e9a1'
g_base_definitions[g_str_5fb1ba38e1af06001770e9a1]={
  id=g_str_5fb1ba38e1af06001770e9a1,
  name='Knights',
  min=1,
  max=2,
  description='Latinikon',
  troop_type="Knights",
}
g_str_5fb1ba38e1af06001770e9a3='5fb1ba38e1af06001770e9a3'
g_base_definitions[g_str_5fb1ba38e1af06001770e9a3]={
  id=g_str_5fb1ba38e1af06001770e9a3,
  name='Horse Bow',
  min=2,
  max=5,
  description='Skythikon, Vardariotai and Tourkopouloi',
  troop_type="Horse Bow",
}
g_str_5fb1ba38e1af06001770e9a5_general='5fb1ba38e1af06001770e9a5_general'
g_base_definitions[g_str_5fb1ba38e1af06001770e9a5_general]={
  id=g_str_5fb1ba38e1af06001770e9a5_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Skilled stratiotai',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba38e1af06001770e9a5='5fb1ba38e1af06001770e9a5'
g_base_definitions[g_str_5fb1ba38e1af06001770e9a5]={
  id=g_str_5fb1ba38e1af06001770e9a5,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Skilled stratiotai',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba38e1af06001770e9a7='5fb1ba38e1af06001770e9a7'
g_base_definitions[g_str_5fb1ba38e1af06001770e9a7]={
  id=g_str_5fb1ba38e1af06001770e9a7,
  name='Bad Horse',
  min=2,
  max=3,
  description='Stratiotai',
  troop_type="Bad Horse",
}
g_str_5fb1ba38e1af06001770e9aa='5fb1ba38e1af06001770e9aa'
g_base_definitions[g_str_5fb1ba38e1af06001770e9aa]={
  id=g_str_5fb1ba38e1af06001770e9aa,
  name='Horse Bow',
  min=2,
  max=6,
  description='Cuman horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba38e1af06001770e9ac='5fb1ba38e1af06001770e9ac'
g_base_definitions[g_str_5fb1ba38e1af06001770e9ac]={
  id=g_str_5fb1ba38e1af06001770e9ac,
  name='Bow Levy',
  min=2,
  max=4,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba38e1af06001770e9ae='5fb1ba38e1af06001770e9ae'
g_base_definitions[g_str_5fb1ba38e1af06001770e9ae]={
  id=g_str_5fb1ba38e1af06001770e9ae,
  name='Archers',
  min=0,
  max=1,
  description='Bowmen better equipped with spear and small shield',
  troop_type="Archers",
}
g_str_5fb1ba38e1af06001770e9b0='5fb1ba38e1af06001770e9b0'
g_base_definitions[g_str_5fb1ba38e1af06001770e9b0]={
  id=g_str_5fb1ba38e1af06001770e9b0,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Kontaratoi',
  troop_type="Heavy Foot",
}
g_str_5fb1ba38e1af06001770e9b2='5fb1ba38e1af06001770e9b2'
g_base_definitions[g_str_5fb1ba38e1af06001770e9b2]={
  id=g_str_5fb1ba38e1af06001770e9b2,
  name='Horde',
  min=0,
  max=1,
  description='Camp servants',
  troop_type="Horde",
}
g_str_5fb1b9ebe1af060017709e85_camp='5fb1b9ebe1af060017709e85_camp'
g_base_definitions[g_str_5fb1b9ebe1af060017709e85_camp]={
  name='Camp',
  id=g_str_5fb1b9ebe1af060017709e85_camp,
  min=1,
  max=1,
}
army['5fb1b9ebe1af060017709e85']={
  data={
    name='Nikaian Byzantine  1204 to 1261 AD'
  },
  g_base_definitions[g_str_5fb1b9ebe1af060017709e85_camp],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9a1],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9a3],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9a5_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9a5],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9a7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9aa],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9ac],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9ae],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9b0],
  g_base_definitions[g_str_5fb1ba38e1af06001770e9b2],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ebe1af060017709e85"] = army["5fb1b9ebe1af060017709e85"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Nikaian Byzantine  1204 to 1261 AD"] = army["5fb1b9ebe1af060017709e85"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Nikaian Byzantine  1204 to 1261 AD"] = army["5fb1b9ebe1af060017709e85"]
