-- 5fb1b9e2e1af06001770991b Early Frankish, etc.  250 to 584 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2de1af06001770d584='5fb1ba2de1af06001770d584'
g_base_definitions[g_str_5fb1ba2de1af06001770d584]={
  id=g_str_5fb1ba2de1af06001770d584,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Noble horsemen',
}
g_str_5fb1ba2de1af06001770d584_dismounted='5fb1ba2de1af06001770d584_dismounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d584_dismounted]={
  id=g_str_5fb1ba2de1af06001770d584_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Javelin Cavalry General',
  points=4,
}
g_5fb1ba2de1af06001770d584_dismounted=g_base_definitions[g_str_5fb1ba2de1af06001770d584_dismounted]
g_str_5fb1ba2de1af06001770d584_mounted='5fb1ba2de1af06001770d584_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d584_mounted]={
  id=g_str_5fb1ba2de1af06001770d584_mounted,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2de1af06001770d584_dismounted,
}
g_str_5fb1ba2de1af06001770d584='5fb1ba2de1af06001770d584'
g_base_definitions[g_str_5fb1ba2de1af06001770d584]={
  id=g_str_5fb1ba2de1af06001770d584,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen',
}
g_str_5fb1ba2de1af06001770d584_dismounted='5fb1ba2de1af06001770d584_dismounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d584_dismounted]={
  id=g_str_5fb1ba2de1af06001770d584_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
}
g_5fb1ba2de1af06001770d584_dismounted=g_base_definitions[g_str_5fb1ba2de1af06001770d584_dismounted]
g_str_5fb1ba2de1af06001770d584_mounted='5fb1ba2de1af06001770d584_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d584_mounted]={
  id=g_str_5fb1ba2de1af06001770d584_mounted,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2de1af06001770d584_dismounted,
}
g_str_5fb1ba2de1af06001770d587='5fb1ba2de1af06001770d587'
g_base_definitions[g_str_5fb1ba2de1af06001770d587]={
  id=g_str_5fb1ba2de1af06001770d587,
  name='Warriors General',
  min=12,
  max=1,
  description='Fierce fighters',
}
g_str_5fb1ba2de1af06001770d587='5fb1ba2de1af06001770d587'
g_base_definitions[g_str_5fb1ba2de1af06001770d587]={
  id=g_str_5fb1ba2de1af06001770d587,
  name='Warriors',
  min=12,
  max=16,
  description='Fierce fighters',
}
g_str_5fb1ba2de1af06001770d589='5fb1ba2de1af06001770d589'
g_base_definitions[g_str_5fb1ba2de1af06001770d589]={
  id=g_str_5fb1ba2de1af06001770d589,
  name='Light Foot',
  min=0,
  max=2,
  description='Javelinmen',
}
g_str_5fb1ba2de1af06001770d58b='5fb1ba2de1af06001770d58b'
g_base_definitions[g_str_5fb1ba2de1af06001770d58b]={
  id=g_str_5fb1ba2de1af06001770d58b,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
}
g_str_5fb1b9e2e1af06001770991b_camp='5fb1b9e2e1af06001770991b_camp'
g_base_definitions[g_str_5fb1b9e2e1af06001770991b_camp]={
  name='Camp',
  id=g_str_5fb1b9e2e1af06001770991b_camp,
  min=1,
  max=1,
}
army['5fb1b9e2e1af06001770991b']={
  data={
    name='Early Frankish, etc.  250 to 584 AD'
  },
  g_base_definitions[g_str_5fb1b9e2e1af06001770991b_camp],
  g_base_definitions[g_str_5fb1ba2de1af06001770d58d],
  g_base_definitions[g_str_5fb1ba2de1af06001770d58e],
  g_base_definitions[g_str_5fb1ba2de1af06001770d584],
  g_base_definitions[g_str_5fb1ba2de1af06001770d584_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d584_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d584],
  g_base_definitions[g_str_5fb1ba2de1af06001770d584_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d584_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d587],
  g_base_definitions[g_str_5fb1ba2de1af06001770d587],
  g_base_definitions[g_str_5fb1ba2de1af06001770d589],
  g_base_definitions[g_str_5fb1ba2de1af06001770d58b],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af06001770991b"] = army["5fb1b9e2e1af06001770991b"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Early Frankish, etc.  250 to 584 AD"] = army["5fb1b9e2e1af06001770991b"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Early Frankish, etc.  250 to 584 AD"] = army["5fb1b9e2e1af06001770991b"]
