-- 5fb1b9f2e1af06001770a20e Murong Xianbei  300 to 431 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3fe1af06001770f778='5fb1ba3fe1af06001770f778'
g_base_definitions[g_str_5fb1ba3fe1af06001770f778]={
  id=g_str_5fb1ba3fe1af06001770f778,
  name='Knights',
  min=1,
  max=3,
  description='Armored nobles on armored horses',
}
g_str_5fb1ba3fe1af06001770f779='5fb1ba3fe1af06001770f779'
g_base_definitions[g_str_5fb1ba3fe1af06001770f779]={
  id=g_str_5fb1ba3fe1af06001770f779,
  name='Cataphracts',
  min=1,
  max=3,
  description='Armored nobles on armored horses',
}
g_str_5fb1ba3fe1af06001770f77b='5fb1ba3fe1af06001770f77b'
g_base_definitions[g_str_5fb1ba3fe1af06001770f77b]={
  id=g_str_5fb1ba3fe1af06001770f77b,
  name='Horse Bow',
  min=5,
  max=11,
  description='Horse archers',
}
g_str_5fb1ba3fe1af06001770f77d='5fb1ba3fe1af06001770f77d'
g_base_definitions[g_str_5fb1ba3fe1af06001770f77d]={
  id=g_str_5fb1ba3fe1af06001770f77d,
  name='Elite Cavalary',
  min=0,
  max=2,
  description='"Chained together" closely formed horse archers',
}
g_str_5fb1ba3fe1af06001770f77e='5fb1ba3fe1af06001770f77e'
g_base_definitions[g_str_5fb1ba3fe1af06001770f77e]={
  id=g_str_5fb1ba3fe1af06001770f77e,
  name='Bad Horse',
  min=0,
  max=2,
  description='"Chained together" closely formed horse archers',
}
g_str_5fb1ba3fe1af06001770f781='5fb1ba3fe1af06001770f781'
g_base_definitions[g_str_5fb1ba3fe1af06001770f781]={
  id=g_str_5fb1ba3fe1af06001770f781,
  name='Skirmishers',
  min=0,
  max=3,
  description='Skirmishing bowmen',
}
g_str_5fb1ba3fe1af06001770f783='5fb1ba3fe1af06001770f783'
g_base_definitions[g_str_5fb1ba3fe1af06001770f783]={
  name='Knights General',
  id=g_str_5fb1ba3fe1af06001770f783,
  min=1,
  max=1,
}
g_str_5fb1ba3fe1af06001770f784='5fb1ba3fe1af06001770f784'
g_base_definitions[g_str_5fb1ba3fe1af06001770f784]={
  name='Cataphracts General',
  id=g_str_5fb1ba3fe1af06001770f784,
  min=1,
  max=1,
}
g_str_5fb1b9f2e1af06001770a20e_camp='5fb1b9f2e1af06001770a20e_camp'
g_base_definitions[g_str_5fb1b9f2e1af06001770a20e_camp]={
  name='Camp',
  id=g_str_5fb1b9f2e1af06001770a20e_camp,
  min=1,
  max=1,
}
army['5fb1b9f2e1af06001770a20e']={
  data={
    name='Murong Xianbei  300 to 431 AD'
  },
  g_base_definitions[g_str_5fb1b9f2e1af06001770a20e_camp],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f783],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f784],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f778],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f779],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f77b],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f77d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f77e],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f781],
}
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Murong Xianbei  300 to 431 AD"] = army["5fb1b9f2e1af06001770a20e"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Murong Xianbei  300 to 431 AD"] = army["5fb1b9f2e1af06001770a20e"]
