troop_options['5fb1ba20e1af06001770c045'] = {
  min=4,
  max=8,
  dateRange={
    startDate=-1595,
    endDate=-1274,
  }
}
troop_options['5fb1ba20e1af06001770c047'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-1595,
    endDate=-1274,
  }
}
troop_options['5fb1ba20e1af06001770c04a'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-1595,
    endDate=-1274,
  }
}
troop_options['5fb1ba20e1af06001770c04e'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-1595,
    endDate=-1274,
  }
}
troop_options['5fb1ba20e1af06001770c050'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-1595,
    endDate=-1274,
  }
}
-- allies
