troop_options['5fb1ba32e1af06001770dd73'] = {
  min=1,
  max=2,
  dateRange={
    startDate=900,
    endDate=1255,
  }
}
troop_options['5fb1ba32e1af06001770dd75'] = {
  min=1,
  max=2,
  dateRange={
    startDate=900,
    endDate=1255,
  }
}
troop_options['5fb1ba32e1af06001770dd77'] = {
  min=1,
  max=4,
  dateRange={
    startDate=900,
    endDate=1255,
  }
}
troop_options['5fb1ba32e1af06001770dd79'] = {
  min=10,
  max=18,
  dateRange={
    startDate=900,
    endDate=1255,
  }
}
-- allies
