-- 5fb1b9f0e1af06001770a10e Other Indonesian  1222 to 1511 AD

army['5fb1b9f0e1af06001770a10e']={
  data={
    name='Other Indonesian  1222 to 1511 AD',
    id='5fb1b9f0e1af06001770a10e',
    army_id='5fb1b9f0e1af06001770a10e'
  },
  g_base_definitions[g_str_5fb1ba3de1af06001770f46d],
  g_base_definitions[g_str_5fb1ba3de1af06001770f46f_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f46f],
  g_base_definitions[g_str_5fb1ba3de1af06001770f471],
  g_base_definitions[g_str_5fb1ba3de1af06001770f473],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a10e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a10e"] = army["5fb1b9f0e1af06001770a10e"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Other Indonesian  1222 to 1511 AD"] = army["5fb1b9f0e1af06001770a10e"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Other Indonesian  1222 to 1511 AD"] = army["5fb1b9f0e1af06001770a10e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Other Indonesian  1222 to 1511 AD"] = army["5fb1b9f0e1af06001770a10e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a10e"] = {}
army_dates["5fb1b9f0e1af06001770a10e"]["1222 AD to 1511 AD"] ="5fb1b9f0e1af06001770a10e"
