-- 5fb1b9dce1af060017709591 Numidian or Early Moorish  215 BC to 25 AD

army['5fb1b9dce1af060017709591']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Numidian or Early Moorish  215 BC to 25 AD',
    id='5fb1b9dce1af060017709591',
    dateRange={
      startDate=-215,
      endDate=25,
    },
  },
  g_base_definitions[g_str_615351a203385c0016b858bb_general],
  g_base_definitions[g_str_615351a203385c0016b858bb],
  g_base_definitions[g_str_615351a203385c0016b858bd],
  g_base_definitions[g_str_615351a203385c0016b858be],
  g_base_definitions[g_str_615351a203385c0016b858c0],
  g_base_definitions[g_str_615351a203385c0016b858c2],
  g_base_definitions[g_str_615351a203385c0016b858c5],
  g_base_definitions[g_str_615351a203385c0016b858c8],
  g_base_definitions[g_str_5fb1b9dce1af060017709591_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709591_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709591"] = army["5fb1b9dce1af060017709591"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Numidian or Early Moorish  215 BC to 25 AD"] = army["5fb1b9dce1af060017709591"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Numidian or Early Moorish  215 BC to 25 AD"] = army["5fb1b9dce1af060017709591"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709591"] = {}
army_dates["5fb1b9dce1af060017709591"]["215 BC to 25 AD"] = {
  startDate=-215,
  endDate=25
}
army_dates["5fb1b9dce1af060017709591"]["215 BC to 26 BC"] = {
  startDate=-215,
  endDate=-26
}
army_dates["5fb1b9dce1af060017709591"]["25 BC to 2 AD"] = {
  startDate=-25,
  endDate=2
}
army_dates["5fb1b9dce1af060017709591"]["3 AD to 6 AD"] = {
  startDate=3,
  endDate=6
}
army_dates["5fb1b9dce1af060017709591"]["7 AD to 25 AD"] = {
  startDate=7,
  endDate=25
}
