-- 5fb1b9eae1af060017709ddd Rus  860 to 1054 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba37e1af06001770e6f3_general='5fb1ba37e1af06001770e6f3_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general]={
  id=g_str_5fb1ba37e1af06001770e6f3_general,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Druzhina',
  general=true,
}
g_str_5fb1ba37e1af06001770e6f3='5fb1ba37e1af06001770e6f3'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f3]={
  id=g_str_5fb1ba37e1af06001770e6f3,
  name='Elite Foot',
  min=0,
  max=1,
  description='Druzhina',
}
g_str_5fb1ba37e1af06001770e6f4_general='5fb1ba37e1af06001770e6f4_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general]={
  id=g_str_5fb1ba37e1af06001770e6f4_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Druzhina',
  general=true,
}
g_str_5fb1ba37e1af06001770e6f4='5fb1ba37e1af06001770e6f4'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f4]={
  id=g_str_5fb1ba37e1af06001770e6f4,
  name='Bad Horse',
  min=0,
  max=1,
  description='Druzhina',
}
g_str_5fb1ba37e1af06001770e6f7_general='5fb1ba37e1af06001770e6f7_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general]={
  id=g_str_5fb1ba37e1af06001770e6f7_general,
  name='Spears General',
  min=7,
  max=1,
  description='Spearmen',
  general=true,
}
g_str_5fb1ba37e1af06001770e6f7='5fb1ba37e1af06001770e6f7'
g_base_definitions[g_str_5fb1ba37e1af06001770e6f7]={
  id=g_str_5fb1ba37e1af06001770e6f7,
  name='Spears',
  min=7,
  max=12,
  description='Spearmen',
}
g_str_5fb1ba37e1af06001770e6fb='5fb1ba37e1af06001770e6fb'
g_base_definitions[g_str_5fb1ba37e1af06001770e6fb]={
  id=g_str_5fb1ba37e1af06001770e6fb,
  name='Skirmishers',
  min=0,
  max=3,
  description='Bowmen',
}
g_str_5fb1ba37e1af06001770e6fe='5fb1ba37e1af06001770e6fe'
g_base_definitions[g_str_5fb1ba37e1af06001770e6fe]={
  id=g_str_5fb1ba37e1af06001770e6fe,
  name='Light Foot',
  min=0,
  max=1,
  description='Javelinmen',
}
g_str_5fb1ba37e1af06001770e701='5fb1ba37e1af06001770e701'
g_base_definitions[g_str_5fb1ba37e1af06001770e701]={
  id=g_str_5fb1ba37e1af06001770e701,
  name='Horse Bow',
  min=0,
  max=1,
  description='Alan, Turk, or Bulgar mercenary horse archers',
}
g_str_5fb1b9eae1af060017709ddd_camp='5fb1b9eae1af060017709ddd_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp]={
  name='Camp',
  id=g_str_5fb1b9eae1af060017709ddd_camp,
  min=1,
  max=1,
}
army['5fb1b9eae1af060017709ddd']={
  data={
    name='Rus  860 to 1054 AD'
  },
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp],
  g_base_definitions[g_str_5fb1ba37e1af06001770e703],
  g_base_definitions[g_str_5fb1ba37e1af06001770e704],
  g_base_definitions[g_str_5fb1ba37e1af06001770e706],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f3],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f4],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6f7],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fb],
  g_base_definitions[g_str_5fb1ba37e1af06001770e6fe],
  g_base_definitions[g_str_5fb1ba37e1af06001770e701],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709ddd"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
