-- 5fb1b9ede1af060017709f14 Early Abbasid  751 to 835 AD

army['5fb1b9ede1af060017709f14']={
  data={
    name='Early Abbasid  751 to 835 AD',
    id='5fb1b9ede1af060017709f14',
    dateRange={
      startDate=751,
      endDate=835,
    }
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0b_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0b_general_mounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0b_general_dismounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0b],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0b_mounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0b_dismounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0e],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0e_mounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec0e_dismounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec12],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec15],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec17],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec1b],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec1e],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec1f],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec22],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec24],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec26],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec28_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec28],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec2a],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec2b],
  g_base_definitions[g_str_5fb1ba39e1af06001770ec2d],
  g_base_definitions[g_str_5fb1b9ede1af060017709f14_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f14_camp_fortified],
  g_base_definitions[g_str_5fb1b9ede1af060017709f14_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f14"] = army["5fb1b9ede1af060017709f14"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Early Abbasid  751 to 835 AD"] = army["5fb1b9ede1af060017709f14"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Early Abbasid  751 to 835 AD"] = army["5fb1b9ede1af060017709f14"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Abbasid  751 to 835 AD"] = army["5fb1b9ede1af060017709f14"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f14"] = {}
army_dates["5fb1b9ede1af060017709f14"]["751 AD to 835 AD"] = {
  startDate=751,
  endDate=835
}
army_dates["5fb1b9ede1af060017709f14"]["751 AD to 763 AD"] = {
  startDate=751,
  endDate=763
}
army_dates["5fb1b9ede1af060017709f14"]["764 AD to 793 AD"] = {
  startDate=764,
  endDate=793
}
army_dates["5fb1b9ede1af060017709f14"]["794 AD to 813 AD"] = {
  startDate=794,
  endDate=813
}
army_dates["5fb1b9ede1af060017709f14"]["814 AD to 835 AD"] = {
  startDate=814,
  endDate=835
}
