troop_options['615351b203385c0016b88402'] = {
  min=0,
  max=1,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b88405'] = {
  min=2,
  max=3,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b88409'] = {
  min=0,
  max=1,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b8840b'] = {
  min=1,
  max=1,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b8840e'] = {
  min=4,
  max=8,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b88411'] = {
  min=0,
  max=1,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b88413'] = {
  min=4,
  max=8,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b88415'] = {
  min=3,
  max=6,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b88417'] = {
  min=0,
  max=2,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
troop_options['615351b203385c0016b8841a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=500,
    endDate=1526,
  }
}
-- allies
