troop_options['5fb1ba2ae1af06001770d090'] = {
  min=2,
  max=3,
  dateRange={
    startDate=321,
    endDate=545,
  }
}
troop_options['5fb1ba2ae1af06001770d093'] = {
  min=1,
  max=2,
  dateRange={
    startDate=321,
    endDate=545,
  }
}
troop_options['5fb1ba2ae1af06001770d095'] = {
  min=1,
  max=2,
  dateRange={
    startDate=321,
    endDate=545,
  }
}
troop_options['5fb1ba2ae1af06001770d097'] = {
  min=0,
  max=1,
  dateRange={
    startDate=321,
    endDate=545,
  }
}
troop_options['5fb1ba2ae1af06001770d099'] = {
  min=3,
  max=9,
  dateRange={
    startDate=321,
    endDate=545,
  }
}
troop_options['5fb1ba2ae1af06001770d09c'] = {
  min=2,
  max=4,
  dateRange={
    startDate=321,
    endDate=545,
  }
}
troop_options['5fb1ba2ae1af06001770d09f'] = {
  min=2,
  max=4,
  dateRange={
    startDate=321,
    endDate=545,
  }
}
-- allies
