troop_options['5fb1ba43e1af06001770fd2b'] = {
  min=2,
  max=6,
  dateRange={
    startDate=201,
    endDate=599,
  }
}
troop_options['5fb1ba43e1af06001770fd2d'] = {
  min=12,
  max=21,
  dateRange={
    startDate=201,
    endDate=599,
  }
}
troop_options['5fb1ba43e1af06001770fd30'] = {
  min=0,
  max=4,
  dateRange={
    startDate=201,
    endDate=599,
  }
}
-- allies
-- 5fb1b9f5e1af06001770a3aa Early Intermediate Period Maya  201 to 599 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba43e1af06001770fd2c_general='5fb1ba43e1af06001770fd2c_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c_general]={
  id=g_str_5fb1ba43e1af06001770fd2c_general,
  name='Light Foot General',
  min=2,
  max=1,
  description='Nobles and elite infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2c='5fb1ba43e1af06001770fd2c'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c]={
  id=g_str_5fb1ba43e1af06001770fd2c,
  name='Light Foot',
  min=2,
  max=6,
  description='Nobles and elite infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2e_general='5fb1ba43e1af06001770fd2e_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e_general]={
  id=g_str_5fb1ba43e1af06001770fd2e_general,
  name='Light Foot General',
  min=12,
  max=1,
  description='Commoners, some carrying roll-up shields',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2e='5fb1ba43e1af06001770fd2e'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e]={
  id=g_str_5fb1ba43e1af06001770fd2e,
  name='Light Foot',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2f='5fb1ba43e1af06001770fd2f'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2f]={
  id=g_str_5fb1ba43e1af06001770fd2f,
  name='Rabble',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd31='5fb1ba43e1af06001770fd31'
g_base_definitions[g_str_5fb1ba43e1af06001770fd31]={
  id=g_str_5fb1ba43e1af06001770fd31,
  name='Skirmishers',
  min=0,
  max=4,
  description='Peasant skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd30",
}
g_str_5fb1b9f5e1af06001770a3aa_camp='5fb1b9f5e1af06001770a3aa_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3aa_camp]={
  id=g_str_5fb1b9f5e1af06001770a3aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9f5e1af06001770a3aa']={
  data={
    name='Early Intermediate Period Maya  201 to 599 AD',
    id='5fb1b9f5e1af06001770a3aa',
    army_id='5fb1b9f5e1af06001770a3aa'
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fd2c_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd2c],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd2e_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd2e],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd2f],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd31],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3aa_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3aa"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Early Intermediate Period Maya  201 to 599 AD"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Early Intermediate Period Maya  201 to 599 AD"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Intermediate Period Maya  201 to 599 AD"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3aa"] = {}
army_dates["5fb1b9f5e1af06001770a3aa"]["201 AD to 599 AD"] ="5fb1b9f5e1af06001770a3aa"
