-- 5fb1b9e0e1af0600177097e0 Kushan Empire  99 BC to 477 AD

army['5fb1b9e0e1af0600177097e0']={
  data={
    invasionRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
      'Steppe',
    },
    name='Kushan Empire  99 BC to 477 AD',
    id='5fb1b9e0e1af0600177097e0',
    dateRange={
      startDate=-99,
      endDate=477,
    }
  },
  g_base_definitions[g_str_5fb1ba2ae1af06001770d135_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d135],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d137],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d139],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d13b_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d13b],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d13d],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d13f],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d140],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d142],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097e0_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097e0_camp_pack_train],
  g_base_definitions[g_str_5fb1ba0de1af06001770ac6e],
  g_base_definitions[g_str_5fb1ba0de1af06001770ac70],
  g_base_definitions[g_str_5fb1ba0de1af06001770ac72],
  g_base_definitions[g_str_5fb1ba0de1af06001770ac74],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097e0"] = army["5fb1b9e0e1af0600177097e0"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Kushan Empire  99 BC to 477 AD"] = army["5fb1b9e0e1af0600177097e0"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Kushan Empire  99 BC to 477 AD"] = army["5fb1b9e0e1af0600177097e0"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Kushan Empire  99 BC to 477 AD"] = army["5fb1b9e0e1af0600177097e0"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Kushan Empire  99 BC to 477 AD"] = army["5fb1b9e0e1af0600177097e0"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097e0"] = {}
army_dates["5fb1b9e0e1af0600177097e0"]["99 BC to 477 AD"] = {
  startDate=-99,
  endDate=477
}
army_dates["5fb1b9e0e1af0600177097e0"]["99 BC to 51 BC"] = {
  startDate=-99,
  endDate=-51
}
army_dates["5fb1b9e0e1af0600177097e0"]["50 BC to 39 AD"] = {
  startDate=-50,
  endDate=39
}
army_dates["5fb1b9e0e1af0600177097e0"]["40 AD to 50 AD"] = {
  startDate=40,
  endDate=50
}
army_dates["5fb1b9e0e1af0600177097e0"]["51 AD to 100 AD"] = {
  startDate=51,
  endDate=100
}
army_dates["5fb1b9e0e1af0600177097e0"]["101 AD to 225 AD"] = {
  startDate=101,
  endDate=225
}
army_dates["5fb1b9e0e1af0600177097e0"]["226 AD to 355 AD"] = {
  startDate=226,
  endDate=355
}
army_dates["5fb1b9e0e1af0600177097e0"]["356 AD to 390 AD"] = {
  startDate=356,
  endDate=390
}
army_dates["5fb1b9e0e1af0600177097e0"]["391 AD to 410 AD"] = {
  startDate=391,
  endDate=410
}
army_dates["5fb1b9e0e1af0600177097e0"]["411 AD to 477 AD"] = {
  startDate=411,
  endDate=477
}
