troop_options['5fb1ba39e1af06001770eae2'] = {
  min=1,
  max=2,
  dateRange={
    startDate=100,
    endDate=970,
  }
}
troop_options['5fb1ba39e1af06001770eae5'] = {
  min=2,
  max=4,
  dateRange={
    startDate=971,
    endDate=1284,
  }
}
troop_options['5fb1ba39e1af06001770eae8'] = {
  min=5,
  max=12,
  dateRange={
    startDate=100,
    endDate=1284,
  }
}
troop_options['5fb1ba39e1af06001770eaea'] = {
  min=1,
  max=5,
  dateRange={
    startDate=100,
    endDate=1284,
  }
}
troop_options['5fb1ba39e1af06001770eaec'] = {
  min=0,
  max=3,
  dateRange={
    startDate=971,
    endDate=1284,
  }
}
troop_options['5fb1ba39e1af06001770eaef'] = {
  min=0,
  max=1,
  dateRange={
    startDate=971,
    endDate=1284,
  }
}
troop_options['5fb1ba39e1af06001770eaf2'] = {
  min=1,
  max=2,
  dateRange={
    startDate=100,
    endDate=1284,
  }
}
troop_options['5fb1ba39e1af06001770eaf4'] = {
  min=0,
  max=1,
  dateRange={
    startDate=100,
    endDate=1284,
  }
}
troop_options['5fb1ba39e1af06001770eaf7'] = {
  min=1,
  max=2,
  dateRange={
    startDate=100,
    endDate=970,
  }
}
-- allies
