-- 5fb1b9ede1af060017709f4e Qaramita  897 to 1078 AD

army['5fb1b9ede1af060017709f4e']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Qaramita  897 to 1078 AD',
    id='5fb1b9ede1af060017709f4e',
    dateRange={
      startDate=897,
      endDate=1078,
    },
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed37_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed37],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed39],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed39_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed39_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed3c],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed3c_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed3c_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed3f_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed3f],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed41],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed43],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed43_light_camelry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ed46],
  g_base_definitions[g_str_5fb1b9ede1af060017709f4e_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f4e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f4e"] = army["5fb1b9ede1af060017709f4e"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Qaramita  897 to 1078 AD"] = army["5fb1b9ede1af060017709f4e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Qaramita  897 to 1078 AD"] = army["5fb1b9ede1af060017709f4e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f4e"] = {}
army_dates["5fb1b9ede1af060017709f4e"]["897 AD to 1078 AD"] = {
  startDate=897,
  endDate=1078
}
