-- 5fb1b9f6e1af06001770a470 Chanca and Caari  1200 to 1471 AD

army['5fb1b9f6e1af06001770a470']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Chanca and Caari  1200 to 1471 AD',
    id='5fb1b9f6e1af06001770a470',
    dateRange={
      startDate=1200,
      endDate=1471,
    },
  },
  g_base_definitions[g_str_615351b703385c0016b88ed6_general],
  g_base_definitions[g_str_615351b703385c0016b88ed6],
  g_base_definitions[g_str_615351b703385c0016b88ed8],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a470_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a470"] = army["5fb1b9f6e1af06001770a470"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Chanca and Caari  1200 to 1471 AD"] = army["5fb1b9f6e1af06001770a470"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Chanca and Caari  1200 to 1471 AD"] = army["5fb1b9f6e1af06001770a470"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a470"] = {}
army_dates["5fb1b9f6e1af06001770a470"]["1200 AD to 1471 AD"] = {
  startDate=1200,
  endDate=1471
}
army_dates["5fb1b9f6e1af06001770a470"]["1200 AD to 1440 AD"] = {
  startDate=1200,
  endDate=1440
}
army_dates["5fb1b9f6e1af06001770a470"]["1441 AD to 1471 AD"] = {
  startDate=1441,
  endDate=1471
}
