-- 5fb1b9ece1af060017709ec2 Nobatae or Ballana  30 BC to 550 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba39e1af06001770eacd_general='5fb1ba39e1af06001770eacd_general'
g_base_definitions[g_str_5fb1ba39e1af06001770eacd_general]={
  id=g_str_5fb1ba39e1af06001770eacd_general,
  name='Horse Bow General',
  min=2,
  max=1,
  description='Horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba39e1af06001770eacb",
}
g_str_5fb1ba39e1af06001770eacd='5fb1ba39e1af06001770eacd'
g_base_definitions[g_str_5fb1ba39e1af06001770eacd]={
  id=g_str_5fb1ba39e1af06001770eacd,
  name='Horse Bow',
  min=2,
  max=6,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba39e1af06001770eacb",
}
g_str_5fb1ba39e1af06001770ead0_general='5fb1ba39e1af06001770ead0_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ead0_general]={
  id=g_str_5fb1ba39e1af06001770ead0_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Horsemen with chamfrons or other horse armor',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba39e1af06001770eace",
}
g_str_5fb1ba39e1af06001770ead0='5fb1ba39e1af06001770ead0'
g_base_definitions[g_str_5fb1ba39e1af06001770ead0]={
  id=g_str_5fb1ba39e1af06001770ead0,
  name='Elite Cavalary',
  min=0,
  max=2,
  description='Horsemen with chamfrons or other horse armor',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba39e1af06001770eace",
}
g_str_5fb1ba39e1af06001770ead3_general='5fb1ba39e1af06001770ead3_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ead3_general]={
  id=g_str_5fb1ba39e1af06001770ead3_general,
  name='Horse Bow General',
  min=2,
  max=1,
  description='Horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba39e1af06001770ead1",
}
g_str_5fb1ba39e1af06001770ead3='5fb1ba39e1af06001770ead3'
g_base_definitions[g_str_5fb1ba39e1af06001770ead3]={
  id=g_str_5fb1ba39e1af06001770ead3,
  name='Horse Bow',
  min=2,
  max=4,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba39e1af06001770ead1",
}
g_str_5fb1ba39e1af06001770ead5='5fb1ba39e1af06001770ead5'
g_base_definitions[g_str_5fb1ba39e1af06001770ead5]={
  id=g_str_5fb1ba39e1af06001770ead5,
  name='Bow Levy',
  min=3,
  max=10,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba39e1af06001770ead4",
}
g_str_5fb1ba39e1af06001770ead7='5fb1ba39e1af06001770ead7'
g_base_definitions[g_str_5fb1ba39e1af06001770ead7]={
  id=g_str_5fb1ba39e1af06001770ead7,
  name='Light Foot',
  min=0,
  max=2,
  description='Blemmye/Beja spearmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba39e1af06001770ead6",
}
g_str_5fb1ba39e1af06001770ead9='5fb1ba39e1af06001770ead9'
g_base_definitions[g_str_5fb1ba39e1af06001770ead9]={
  id=g_str_5fb1ba39e1af06001770ead9,
  name='Heavy Foot',
  min=3,
  max=6,
  description='Nobades or subject Kushite spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba39e1af06001770ead8",
}
g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry='5fb1ba39e1af06001770ead9_dismounted_mobile_infantry'
g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry='5fb1ba39e1af06001770ead9_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Nobades or subject Kushite spearmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba39e1af06001770ead8",
}
g_base_definitions[g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Nobades or subject Kushite spearmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba39e1af06001770ead8",
}
g_str_5fb1ba39e1af06001770eadc='5fb1ba39e1af06001770eadc'
g_base_definitions[g_str_5fb1ba39e1af06001770eadc]={
  id=g_str_5fb1ba39e1af06001770eadc,
  name='Bad Horse',
  min=0,
  max=2,
  description='Camel-mounted spearmen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eadb",
}
g_str_5fb1ba39e1af06001770eadc_light_camelry='5fb1ba39e1af06001770eadc_light_camelry'
g_base_definitions[g_str_5fb1ba39e1af06001770eadc_light_camelry]={
  id=g_str_5fb1ba39e1af06001770eadc_light_camelry,
  name='Bad Horse',
  min=0,
  max=2,
  description='Camel-mounted spearmen\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eadb",
}
g_str_5fb1b9ece1af060017709ec2_camp='5fb1b9ece1af060017709ec2_camp'
g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp]={
  id=g_str_5fb1b9ece1af060017709ec2_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709ec2_camp_pack_train='5fb1b9ece1af060017709ec2_camp_pack_train'
g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp_pack_train]={
  id=g_str_5fb1b9ece1af060017709ec2_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9ece1af060017709ec2']={
  data={
    name='Nobatae or Ballana  30 BC to 550 AD'
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770eacd_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770eacd],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead0_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead0],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead3_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead3],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead5],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead7],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc_light_camelry],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709ec2"] = army["5fb1b9ece1af060017709ec2"]
army['5fb1b9ece1af060017709ec2_-30_500']={
  data={
    name='Nobatae or Ballana 30 BC to 500 AD'
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770eacd_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770eacd],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead5],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead7],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc_light_camelry],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp_pack_train],
}
army['5fb1b9ece1af060017709ec2_501_550']={
  data={
    name='Nobatae or Ballana 501 AD to 550 AD'
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770ead0_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead0],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead3_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead3],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead5],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead7],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc_light_camelry],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp_pack_train],
}
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Nobatae or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Nobatae or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709ec2"] = {}
army_dates["5fb1b9ece1af060017709ec2"]["30 BC to 550 AD"] ="5fb1b9ece1af060017709ec2"
army_dates["5fb1b9ece1af060017709ec2"]["30 BC to 500 AD"] ="5fb1b9ece1af060017709ec2_-30_500"
army_dates["5fb1b9ece1af060017709ec2"]["501 AD to 550 AD"] ="5fb1b9ece1af060017709ec2_501_550"
