troop_options['5fb1ba30e1af06001770dabe'] = {
  min=1,
  max=3,
  dateRange={
    startDate=842,
    endDate=1229,
  }
}
troop_options['5fb1ba30e1af06001770dac1'] = {
  min=5,
  max=10,
  dateRange={
    startDate=842,
    endDate=1229,
  }
}
troop_options['5fb1ba30e1af06001770dac4'] = {
  min=0,
  max=2,
  dateRange={
    startDate=842,
    endDate=1229,
  }
}
troop_options['5fb1ba30e1af06001770dac7'] = {
  min=0,
  max=1,
  dateRange={
    startDate=842,
    endDate=1229,
  }
}
troop_options['5fb1ba30e1af06001770dacb'] = {
  min=1,
  max=2,
  dateRange={
    startDate=842,
    endDate=1229,
  }
}
troop_options['5fb1ba30e1af06001770dace'] = {
  min=0,
  max=1,
  dateRange={
    startDate=842,
    endDate=1229,
  }
}
-- allies
