troop_options['5fb1ba2be1af06001770d207'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-103,
    endDate=-99,
  }
}
troop_options['5fb1ba2be1af06001770d209'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-103,
    endDate=-99,
  }
}
troop_options['5fb1ba2be1af06001770d20b'] = {
  min=3,
  max=6,
  dateRange={
    startDate=-103,
    endDate=-99,
  }
}
troop_options['5fb1ba2be1af06001770d20d'] = {
  min=6,
  max=17,
  dateRange={
    startDate=-103,
    endDate=-99,
  }
}
-- allies
