-- 5fb1b9dbe1af0600177094b7 Sikel  479 to 380 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba24e1af06001770c50f_general='5fb1ba24e1af06001770c50f_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c50f_general]={
  id=g_str_5fb1ba24e1af06001770c50f_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c50e",
}
g_str_5fb1ba24e1af06001770c50f_general_dismounted='5fb1ba24e1af06001770c50f_general_dismounted'
g_str_5fb1ba24e1af06001770c50f_general_mounted='5fb1ba24e1af06001770c50f_general_mounted'
g_base_definitions[g_str_5fb1ba24e1af06001770c50f_general_dismounted]={
  id=g_str_5fb1ba24e1af06001770c50f_general_dismounted,
  name='Warriors General',
  min=0,
  max=1,
  description='Horsemen\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  dismounted_from=g_str_5fb1ba24e1af06001770c50f_general_mounted,
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba24e1af06001770c50e",
}
g_base_definitions[g_str_5fb1ba24e1af06001770c50f_general_mounted]={
  id=g_str_5fb1ba24e1af06001770c50f_general_mounted,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_str_5fb1ba24e1af06001770c50f_general_dismounted,
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c50e",
}
g_str_5fb1ba24e1af06001770c50f='5fb1ba24e1af06001770c50f'
g_base_definitions[g_str_5fb1ba24e1af06001770c50f]={
  id=g_str_5fb1ba24e1af06001770c50f,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c50e",
}
g_str_5fb1ba24e1af06001770c50f_dismounted='5fb1ba24e1af06001770c50f_dismounted'
g_str_5fb1ba24e1af06001770c50f_mounted='5fb1ba24e1af06001770c50f_mounted'
g_base_definitions[g_str_5fb1ba24e1af06001770c50f_dismounted]={
  id=g_str_5fb1ba24e1af06001770c50f_dismounted,
  name='Warriors',
  min=0,
  max=1,
  description='Horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
  dismounted_from=g_str_5fb1ba24e1af06001770c50f_mounted,
  troop_type="Warriors",
  troop_option_id="5fb1ba24e1af06001770c50e",
}
g_base_definitions[g_str_5fb1ba24e1af06001770c50f_mounted]={
  id=g_str_5fb1ba24e1af06001770c50f_mounted,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_str_5fb1ba24e1af06001770c50f_dismounted,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c50e",
}
g_str_5fb1ba24e1af06001770c512_general='5fb1ba24e1af06001770c512_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c512_general]={
  id=g_str_5fb1ba24e1af06001770c512_general,
  name='Light Foot General',
  min=6,
  max=1,
  description='Light infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba24e1af06001770c511",
}
g_str_5fb1ba24e1af06001770c512='5fb1ba24e1af06001770c512'
g_base_definitions[g_str_5fb1ba24e1af06001770c512]={
  id=g_str_5fb1ba24e1af06001770c512,
  name='Light Foot',
  min=6,
  max=16,
  description='Light infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba24e1af06001770c511",
}
g_str_5fb1ba24e1af06001770c514='5fb1ba24e1af06001770c514'
g_base_definitions[g_str_5fb1ba24e1af06001770c514]={
  id=g_str_5fb1ba24e1af06001770c514,
  name='Heavy Foot',
  min=0,
  max=6,
  description='Spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba24e1af06001770c513",
}
g_str_5fb1ba24e1af06001770c516='5fb1ba24e1af06001770c516'
g_base_definitions[g_str_5fb1ba24e1af06001770c516]={
  id=g_str_5fb1ba24e1af06001770c516,
  name='Rabble',
  min=0,
  max=2,
  description='Javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba24e1af06001770c515",
}
g_str_5fb1b9dbe1af0600177094b7_camp='5fb1b9dbe1af0600177094b7_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094b7_camp]={
  id=g_str_5fb1b9dbe1af0600177094b7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dbe1af0600177094b7_camp_fortified='5fb1b9dbe1af0600177094b7_camp_fortified'
g_base_definitions[g_str_5fb1b9dbe1af0600177094b7_camp_fortified]={
  id=g_str_5fb1b9dbe1af0600177094b7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9dbe1af0600177094b7_camp_pack_train='5fb1b9dbe1af0600177094b7_camp_pack_train'
g_base_definitions[g_str_5fb1b9dbe1af0600177094b7_camp_pack_train]={
  id=g_str_5fb1b9dbe1af0600177094b7_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dbe1af0600177094b7']={
  data={
    name='Sikel  479 to 380 BC',
    id='5fb1b9dbe1af0600177094b7',
    army_id='5fb1b9dbe1af0600177094b7'
  },
  g_base_definitions[g_str_5fb1ba24e1af06001770c50f_general],
  g_base_definitions[g_str_5fb1ba24e1af06001770c50f_general_mounted],
  g_base_definitions[g_str_5fb1ba24e1af06001770c50f_general_dismounted],
  g_base_definitions[g_str_5fb1ba24e1af06001770c50f],
  g_base_definitions[g_str_5fb1ba24e1af06001770c50f_mounted],
  g_base_definitions[g_str_5fb1ba24e1af06001770c50f_dismounted],
  g_base_definitions[g_str_5fb1ba24e1af06001770c512_general],
  g_base_definitions[g_str_5fb1ba24e1af06001770c512],
  g_base_definitions[g_str_5fb1ba24e1af06001770c514],
  g_base_definitions[g_str_5fb1ba24e1af06001770c516],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094b7_camp],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094b7_camp_fortified],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094b7_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094b7"] = army["5fb1b9dbe1af0600177094b7"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Sikel  479 to 380 BC"] = army["5fb1b9dbe1af0600177094b7"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sikel  479 to 380 BC"] = army["5fb1b9dbe1af0600177094b7"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094b7"] = {}
army_dates["5fb1b9dbe1af0600177094b7"]["479 BC to 380 BC"] ="5fb1b9dbe1af0600177094b7"
