g_str_5fb1ba32e1af06001770df22_general='5fb1ba32e1af06001770df22_general'
g_base_definitions[g_str_5fb1ba32e1af06001770df22_general]={
  id=g_str_5fb1ba32e1af06001770df22_general,
  name='Knights General',
  min=2,
  max=1,
  description='Hidalgos, foreign crusaders, and mercenaries',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba32e1af06001770df21",
}
g_str_5fb1ba32e1af06001770df22='5fb1ba32e1af06001770df22'
g_base_definitions[g_str_5fb1ba32e1af06001770df22]={
  id=g_str_5fb1ba32e1af06001770df22,
  name='Knights',
  min=2,
  max=4,
  description='Hidalgos, foreign crusaders, and mercenaries',
  troop_type="Knights",
  troop_option_id="5fb1ba32e1af06001770df21",
}
g_str_5fb1ba32e1af06001770df24_general='5fb1ba32e1af06001770df24_general'
g_base_definitions[g_str_5fb1ba32e1af06001770df24_general]={
  id=g_str_5fb1ba32e1af06001770df24_general,
  name='Knights General',
  min=0,
  max=1,
  description='Military order knights, or French crusading nobles',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba32e1af06001770df23",
}
g_str_5fb1ba32e1af06001770df24='5fb1ba32e1af06001770df24'
g_base_definitions[g_str_5fb1ba32e1af06001770df24]={
  id=g_str_5fb1ba32e1af06001770df24,
  name='Knights',
  min=0,
  max=1,
  description='Military order knights, or French crusading nobles',
  troop_type="Knights",
  troop_option_id="5fb1ba32e1af06001770df23",
}
g_str_5fb1ba32e1af06001770df26='5fb1ba32e1af06001770df26'
g_base_definitions[g_str_5fb1ba32e1af06001770df26]={
  id=g_str_5fb1ba32e1af06001770df26,
  name='Javelin Cavalry',
  min=3,
  max=7,
  description='Jinetes',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770df25",
}
g_str_5fb1ba32e1af06001770df28='5fb1ba32e1af06001770df28'
g_base_definitions[g_str_5fb1ba32e1af06001770df28]={
  id=g_str_5fb1ba32e1af06001770df28,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Basque or mercenary Berber horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770df27",
}
g_str_5fb1ba32e1af06001770df2a='5fb1ba32e1af06001770df2a'
g_base_definitions[g_str_5fb1ba32e1af06001770df2a]={
  id=g_str_5fb1ba32e1af06001770df2a,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Basque or mercenary Berber horsemen, or Crossbowmen on horses',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770df29",
}
g_str_5fb1ba32e1af06001770df2b='5fb1ba32e1af06001770df2b'
g_base_definitions[g_str_5fb1ba32e1af06001770df2b]={
  id=g_str_5fb1ba32e1af06001770df2b,
  name='Bad Horse',
  min=0,
  max=1,
  description='Basque or mercenary Berber horsemen, or Crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba32e1af06001770df29",
}
g_str_5fb1ba32e1af06001770df2d='5fb1ba32e1af06001770df2d'
g_base_definitions[g_str_5fb1ba32e1af06001770df2d]={
  id=g_str_5fb1ba32e1af06001770df2d,
  name='Elite Foot',
  min=0,
  max=1,
  description='Armored axemen',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba32e1af06001770df2c",
}
g_str_5fb1ba32e1af06001770df2f='5fb1ba32e1af06001770df2f'
g_base_definitions[g_str_5fb1ba32e1af06001770df2f]={
  id=g_str_5fb1ba32e1af06001770df2f,
  name='Light Foot',
  min=0,
  max=2,
  description='Bidets or Almughavars',
  troop_type="Light Foot",
  troop_option_id="5fb1ba32e1af06001770df2e",
}
g_str_5fb1ba32e1af06001770df31='5fb1ba32e1af06001770df31'
g_base_definitions[g_str_5fb1ba32e1af06001770df31]={
  id=g_str_5fb1ba32e1af06001770df31,
  name='Heavy Foot',
  min=1,
  max=4,
  description='Spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba32e1af06001770df30",
}
g_str_5fb1ba32e1af06001770df34='5fb1ba32e1af06001770df34'
g_base_definitions[g_str_5fb1ba32e1af06001770df34]={
  id=g_str_5fb1ba32e1af06001770df34,
  name='Rabble',
  min=0,
  max=2,
  description='Javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba32e1af06001770df33",
}
g_str_5fb1ba32e1af06001770df36='5fb1ba32e1af06001770df36'
g_base_definitions[g_str_5fb1ba32e1af06001770df36]={
  id=g_str_5fb1ba32e1af06001770df36,
  name='Spears',
  min=0,
  max=1,
  description='Military order sergeants (if Aragon, Barcelona militia instead)',
  troop_type="Spears",
  troop_option_id="5fb1ba32e1af06001770df35",
}
g_str_5fb1ba32e1af06001770df39='5fb1ba32e1af06001770df39'
g_base_definitions[g_str_5fb1ba32e1af06001770df39]={
  id=g_str_5fb1ba32e1af06001770df39,
  name='Skirmishers',
  min=1,
  max=3,
  description='Skirmishing bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba32e1af06001770df38",
}
g_str_5fb1ba32e1af06001770df3c='5fb1ba32e1af06001770df3c'
g_base_definitions[g_str_5fb1ba32e1af06001770df3c]={
  id=g_str_5fb1ba32e1af06001770df3c,
  name='Bow Levy',
  min=0,
  max=1,
  description='Crossbowmen, possibly with armor and pavises, or from a military order',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba32e1af06001770df3b",
}
g_str_5fb1ba32e1af06001770df3d='5fb1ba32e1af06001770df3d'
g_base_definitions[g_str_5fb1ba32e1af06001770df3d]={
  id=g_str_5fb1ba32e1af06001770df3d,
  name='Archers',
  min=0,
  max=1,
  description='Crossbowmen, possibly with armor and pavises, or from a military order',
  troop_type="Archers",
  troop_option_id="5fb1ba32e1af06001770df3b",
}
g_str_5fb1b9e7e1af060017709bf6_camp='5fb1b9e7e1af060017709bf6_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709bf6_camp]={
  id=g_str_5fb1b9e7e1af060017709bf6_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e7e1af060017709bf6_camp_pack_train='5fb1b9e7e1af060017709bf6_camp_pack_train'
g_base_definitions[g_str_5fb1b9e7e1af060017709bf6_camp_pack_train]={
  id=g_str_5fb1b9e7e1af060017709bf6_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1b9e7e1af060017709bf6_camp_standard_wagon='5fb1b9e7e1af060017709bf6_camp_standard_wagon'
g_base_definitions[g_str_5fb1b9e7e1af060017709bf6_camp_standard_wagon]={
  id=g_str_5fb1b9e7e1af060017709bf6_camp_standard_wagon,
  name='Camp',
  min=0,
  max=1,
  description='Standard Wagon',
  standard_wagon=true,
  troop_type="Camp",
}
