troop_options['5fb1ba39e1af06001770ec5d'] = {
  min=2,
  max=4,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec61'] = {
  min=1,
  max=1,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec63'] = {
  min=0,
  max=1,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec65'] = {
  min=0,
  max=1,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec68'] = {
  min=0,
  max=3,
  dateRange={
    startDate=880,
    endDate=889,
  }
}
troop_options['5fb1ba39e1af06001770ec6c'] = {
  min=1,
  max=2,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec70'] = {
  min=1,
  max=2,
  dateRange={
    startDate=890,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec74'] = {
  min=0,
  max=1,
  dateRange={
    startDate=890,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec78'] = {
  min=2,
  max=6,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec7a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec7c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec7e'] = {
  min=0,
  max=2,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec80'] = {
  min=0,
  max=1,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec83'] = {
  min=0,
  max=1,
  dateRange={
    startDate=880,
    endDate=945,
  }
}
troop_options['5fb1ba39e1af06001770ec85'] = {
  min=0,
  max=1,
  dateRange={
    startDate=932,
    endDate=945,
  }
}
-- allies
