-- 5fb1b9f5e1af06001770a42a Aztec  1325 to 1521 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba44e1af06001770fe0d']= {
  min=2,
  max=6,
  description='Military order suit-wearers',
  core='all',
}
g_troop_entry['5fb1ba44e1af06001770fe0e']= {
  troop_option='5fb1ba44e1af06001770fe0d',
  troopTypeCode='RDR',
}
g_troop_option['5fb1ba44e1af06001770fe0f']= {
  min=0,
  max=1,
  description='Cuachichiqueh and Ontontin shock troops',
}
g_troop_entry['5fb1ba44e1af06001770fe10']= {
  troop_option='5fb1ba44e1af06001770fe0f',
  troopTypeCode='RDR',
}
g_troop_option['5fb1ba44e1af06001770fe11']= {
  min=4,
  max=11,
  description='Macehualtin tribesmen',
}
g_troop_entry['5fb1ba44e1af06001770fe12']= {
  troop_option='5fb1ba44e1af06001770fe11',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba44e1af06001770fe13']= {
  min=2,
  max=4,
  description='Skirmishing slingers or bowmen',
}
g_troop_entry['5fb1ba44e1af06001770fe14']= {
  troop_option='5fb1ba44e1af06001770fe13',
  troopTypeCode='SKM',
}
g_troop_option['5fb1ba44e1af06001770fe15']= {
  min=0,
  max=1,
  description='Mercenary bowmen',
}
g_troop_entry['5fb1ba44e1af06001770fe16']= {
  troop_option='5fb1ba44e1af06001770fe15',
  troopTypeCode='BLV',
}
g_str_5fb1ba44e1af06001770fe0e_general='5fb1ba44e1af06001770fe0e_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fe0e_general]={
  id=g_str_5fb1ba44e1af06001770fe0e_general,
  name='Raiders General',
  min=2,
  max=1,
  description='Military order suit-wearers',
  general=true,
  troop_type="Raiders",
}
g_str_5fb1ba44e1af06001770fe0e='5fb1ba44e1af06001770fe0e'
g_base_definitions[g_str_5fb1ba44e1af06001770fe0e]={
  id=g_str_5fb1ba44e1af06001770fe0e,
  name='Raiders',
  min=2,
  max=6,
  description='Military order suit-wearers',
  troop_type="Raiders",
}
g_str_5fb1ba44e1af06001770fe10_general='5fb1ba44e1af06001770fe10_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fe10_general]={
  id=g_str_5fb1ba44e1af06001770fe10_general,
  name='Raiders General',
  min=0,
  max=1,
  description='Cuachichiqueh and Ontontin shock troops',
  general=true,
  troop_type="Raiders",
}
g_str_5fb1ba44e1af06001770fe10='5fb1ba44e1af06001770fe10'
g_base_definitions[g_str_5fb1ba44e1af06001770fe10]={
  id=g_str_5fb1ba44e1af06001770fe10,
  name='Raiders',
  min=0,
  max=1,
  description='Cuachichiqueh and Ontontin shock troops',
  troop_type="Raiders",
}
g_str_5fb1ba44e1af06001770fe12='5fb1ba44e1af06001770fe12'
g_base_definitions[g_str_5fb1ba44e1af06001770fe12]={
  id=g_str_5fb1ba44e1af06001770fe12,
  name='Light Foot',
  min=4,
  max=11,
  description='Macehualtin tribesmen',
  troop_type="Light Foot",
}
g_str_5fb1ba44e1af06001770fe14='5fb1ba44e1af06001770fe14'
g_base_definitions[g_str_5fb1ba44e1af06001770fe14]={
  id=g_str_5fb1ba44e1af06001770fe14,
  name='Skirmishers',
  min=2,
  max=4,
  description='Skirmishing slingers or bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba44e1af06001770fe16='5fb1ba44e1af06001770fe16'
g_base_definitions[g_str_5fb1ba44e1af06001770fe16]={
  id=g_str_5fb1ba44e1af06001770fe16,
  name='Bow Levy',
  min=0,
  max=1,
  description='Mercenary bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1b9f5e1af06001770a42a_camp='5fb1b9f5e1af06001770a42a_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a42a_camp]={
  id=g_str_5fb1b9f5e1af06001770a42a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9f5e1af06001770a42a']={
  data={
    name='Aztec  1325 to 1521 AD',
    id='5fb1b9f5e1af06001770a42a',
    army_id='5fb1b9f5e1af06001770a42a'
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fe0e_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe0e],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe10_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe10],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe12],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe14],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe16],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a42a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a42a"] = army["5fb1b9f5e1af06001770a42a"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Aztec  1325 to 1521 AD"] = army["5fb1b9f5e1af06001770a42a"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Aztec  1325 to 1521 AD"] = army["5fb1b9f5e1af06001770a42a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Aztec  1325 to 1521 AD"] = army["5fb1b9f5e1af06001770a42a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a42a"] = {}
army_dates["5fb1b9f5e1af06001770a42a"]["1325 AD to 1521 AD"] ="5fb1b9f5e1af06001770a42a"
