troop_options['5fb1ba28e1af06001770cb06'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-512,
    endDate=-284,
  }
}
troop_options['5fb1ba28e1af06001770cb08'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-512,
    endDate=-284,
  }
}
troop_options['5fb1ba28e1af06001770cb0a'] = {
  min=7,
  max=12,
  dateRange={
    startDate=-512,
    endDate=-284,
  }
}
troop_options['5fb1ba28e1af06001770cb0c'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-512,
    endDate=-284,
  }
}
troop_options['5fb1ba28e1af06001770cb0e'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-512,
    endDate=-284,
  }
}
-- allies
