-- 5fb1b9e1e1af060017709838 Meroitic Kushite  592 BC to 350 AD

army['5fb1b9e1e1af060017709838']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Meroitic Kushite  592 BC to 350 AD',
    id='5fb1b9e1e1af060017709838',
    dateRange={
      startDate=-592,
      endDate=350,
    },
  },
  g_base_definitions[g_str_615351a603385c0016b862ff_general],
  g_base_definitions[g_str_615351a603385c0016b862ff],
  g_base_definitions[g_str_615351a603385c0016b86301_general],
  g_base_definitions[g_str_615351a603385c0016b86301],
  g_base_definitions[g_str_615351a603385c0016b86303_general],
  g_base_definitions[g_str_615351a603385c0016b86303],
  g_base_definitions[g_str_615351a603385c0016b86305],
  g_base_definitions[g_str_615351a603385c0016b86307],
  g_base_definitions[g_str_615351a603385c0016b86309],
  g_base_definitions[g_str_5fb1b9e1e1af060017709838_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709838"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709838"] = {}
army_dates["5fb1b9e1e1af060017709838"]["592 BC to 350 AD"] = {
  startDate=-592,
  endDate=350
}
army_dates["5fb1b9e1e1af060017709838"]["592 BC to 31 BC"] = {
  startDate=-592,
  endDate=-31
}
army_dates["5fb1b9e1e1af060017709838"]["30 BC to 350 AD"] = {
  startDate=-30,
  endDate=350
}
