-- 5fb1b9dfe1af060017709724 Maccabean Jewish Trained Army  152 to 104 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba29e1af06001770cec8']= {
  min=0,
  max=1,
  description='Horsemen of the army',
}
g_troop_entry['5fb1ba29e1af06001770cec9']= {
  troop_option='5fb1ba29e1af06001770cec8',
  troopTypeCode='KNT',
}
g_troop_option['5fb1ba29e1af06001770ceca']= {
  min=1,
  max=3,
  description='Horsemen of the phalanx',
}
g_troop_entry['5fb1ba29e1af06001770cecb']= {
  troop_option='5fb1ba29e1af06001770ceca',
  troopTypeCode='BAD',
}
g_troop_option['5fb1ba29e1af06001770cecc']= {
  min=2,
  max=8,
  description='Foot of the phalanx',
  core='all',
}
g_troop_entry['5fb1ba29e1af06001770cecd']= {
  troop_option='5fb1ba29e1af06001770cecc',
  troopTypeCode='RDR',
}
g_troop_option['5fb1ba29e1af06001770cece']= {
  min=0,
  max=5,
  description='Guerrilla dregs',
}
g_troop_entry['5fb1ba29e1af06001770cecf']= {
  troop_option='5fb1ba29e1af06001770cece',
  troopTypeCode='RBL',
}
g_troop_option['5fb1ba29e1af06001770ced0']= {
  min=1,
  max=3,
  description='Skirmishing slingers',
}
g_troop_entry['5fb1ba29e1af06001770ced1']= {
  troop_option='5fb1ba29e1af06001770ced0',
  troopTypeCode='SKM',
}
g_str_5fb1ba29e1af06001770cec9_general='5fb1ba29e1af06001770cec9_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cec9_general]={
  id=g_str_5fb1ba29e1af06001770cec9_general,
  name='Knights General',
  min=0,
  max=1,
  description='Horsemen of the army',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba29e1af06001770cec9='5fb1ba29e1af06001770cec9'
g_base_definitions[g_str_5fb1ba29e1af06001770cec9]={
  id=g_str_5fb1ba29e1af06001770cec9,
  name='Knights',
  min=0,
  max=1,
  description='Horsemen of the army',
  troop_type="Knights",
}
g_str_5fb1ba29e1af06001770cecb='5fb1ba29e1af06001770cecb'
g_base_definitions[g_str_5fb1ba29e1af06001770cecb]={
  id=g_str_5fb1ba29e1af06001770cecb,
  name='Bad Horse',
  min=1,
  max=3,
  description='Horsemen of the phalanx',
  troop_type="Bad Horse",
}
g_str_5fb1ba29e1af06001770cecd_general='5fb1ba29e1af06001770cecd_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cecd_general]={
  id=g_str_5fb1ba29e1af06001770cecd_general,
  name='Raiders General',
  min=2,
  max=1,
  description='Foot of the phalanx',
  general=true,
  troop_type="Raiders",
}
g_str_5fb1ba29e1af06001770cecd='5fb1ba29e1af06001770cecd'
g_base_definitions[g_str_5fb1ba29e1af06001770cecd]={
  id=g_str_5fb1ba29e1af06001770cecd,
  name='Raiders',
  min=2,
  max=8,
  description='Foot of the phalanx',
  troop_type="Raiders",
}
g_str_5fb1ba29e1af06001770cecf='5fb1ba29e1af06001770cecf'
g_base_definitions[g_str_5fb1ba29e1af06001770cecf]={
  id=g_str_5fb1ba29e1af06001770cecf,
  name='Rabble',
  min=0,
  max=5,
  description='Guerrilla dregs',
  troop_type="Rabble",
}
g_str_5fb1ba29e1af06001770ced1='5fb1ba29e1af06001770ced1'
g_base_definitions[g_str_5fb1ba29e1af06001770ced1]={
  id=g_str_5fb1ba29e1af06001770ced1,
  name='Skirmishers',
  min=1,
  max=3,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
}
g_str_5fb1b9dfe1af060017709724_camp='5fb1b9dfe1af060017709724_camp'
g_base_definitions[g_str_5fb1b9dfe1af060017709724_camp]={
  id=g_str_5fb1b9dfe1af060017709724_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af060017709724_camp_pack_train='5fb1b9dfe1af060017709724_camp_pack_train'
g_base_definitions[g_str_5fb1b9dfe1af060017709724_camp_pack_train]={
  id=g_str_5fb1b9dfe1af060017709724_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba0ce1af06001770ab65_general='5fb1ba0ce1af06001770ab65_general'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab65_general]={
  id=g_str_5fb1ba0ce1af06001770ab65_general,
  name='Light Foot General',
  min=4,
  max=1,
  description='Guerrillas',
  general=true,
  troop_type="Light Foot",
}
g_str_5fb1ba0ce1af06001770ab65='5fb1ba0ce1af06001770ab65'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab65]={
  id=g_str_5fb1ba0ce1af06001770ab65,
  name='Light Foot',
  min=4,
  max=11,
  description='Guerrillas',
  troop_type="Light Foot",
}
g_str_5fb1ba0ce1af06001770ab66='5fb1ba0ce1af06001770ab66'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab66]={
  id=g_str_5fb1ba0ce1af06001770ab66,
  name='Rabble',
  min=4,
  max=11,
  description='Guerrillas',
  troop_type="Rabble",
}
g_str_5fb1ba0ce1af06001770ab68='5fb1ba0ce1af06001770ab68'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab68]={
  id=g_str_5fb1ba0ce1af06001770ab68,
  name='Bow Levy',
  min=1,
  max=4,
  description='Guerrilla bowmen',
  troop_type="Bow Levy",
}
army['5fb1b9dfe1af060017709724']={
  data={
    name='Maccabean Jewish Trained Army  152 to 104 BC',
    id='5fb1b9dfe1af060017709724',
    army_id='5fb1b9dfe1af060017709724'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cec9_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cec9],
  g_base_definitions[g_str_5fb1ba29e1af06001770cecb],
  g_base_definitions[g_str_5fb1ba29e1af06001770cecd_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cecd],
  g_base_definitions[g_str_5fb1ba29e1af06001770cecf],
  g_base_definitions[g_str_5fb1ba29e1af06001770ced1],
  g_base_definitions[g_str_5fb1b9dfe1af060017709724_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709724_camp_pack_train],
  g_base_definitions[g_str_5fb1ba0ce1af06001770ab65_general],
  g_base_definitions[g_str_5fb1ba0ce1af06001770ab65],
  g_base_definitions[g_str_5fb1ba0ce1af06001770ab66],
  g_base_definitions[g_str_5fb1ba0ce1af06001770ab68],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709724"] = army["5fb1b9dfe1af060017709724"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Maccabean Jewish Trained Army  152 to 104 BC"] = army["5fb1b9dfe1af060017709724"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Maccabean Jewish Trained Army  152 to 104 BC"] = army["5fb1b9dfe1af060017709724"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709724"] = {}
army_dates["5fb1b9dfe1af060017709724"]["152 BC to 104 BC"] ="5fb1b9dfe1af060017709724"
