-- 5fb1b9dce1af060017709543 Camillan Roman  400 to 276 BC

army['5fb1b9dce1af060017709543']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Camillan Roman  400 to 276 BC',
    id='5fb1b9dce1af060017709543',
    dateRange={
      startDate=-400,
      endDate=-276,
    }
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720],
  g_base_definitions[g_str_5fb1ba26e1af06001770c723],
  g_base_definitions[g_str_5fb1ba26e1af06001770c725],
  g_base_definitions[g_str_5fb1ba26e1af06001770c727],
  g_base_definitions[g_str_5fb1ba26e1af06001770c729],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_fortified],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709543"] = army["5fb1b9dce1af060017709543"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709543"] = {}
army_dates["5fb1b9dce1af060017709543"]["400 BC to 276 BC"] = {
  startDate=-400,
  endDate=-276
}
army_dates["5fb1b9dce1af060017709543"]["400 BC to 356 BC"] = {
  startDate=-400,
  endDate=-356
}
army_dates["5fb1b9dce1af060017709543"]["355 BC to 341 BC"] = {
  startDate=-355,
  endDate=-341
}
army_dates["5fb1b9dce1af060017709543"]["340 BC"] = {
  startDate=-340,
  endDate=-340
}
army_dates["5fb1b9dce1af060017709543"]["339 BC to 276 BC"] = {
  startDate=-339,
  endDate=-276
}
-- 5fb1b9dce1af060017709543 Camillan Roman  400 to 276 BC

army['5fb1b9dce1af060017709543']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Camillan Roman  400 to 276 BC',
    id='5fb1b9dce1af060017709543',
    dateRange={
      startDate=-400,
      endDate=-276,
    }
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720],
  g_base_definitions[g_str_5fb1ba26e1af06001770c723],
  g_base_definitions[g_str_5fb1ba26e1af06001770c725],
  g_base_definitions[g_str_5fb1ba26e1af06001770c727],
  g_base_definitions[g_str_5fb1ba26e1af06001770c729],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_fortified],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709543"] = army["5fb1b9dce1af060017709543"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709543"] = {}
army_dates["5fb1b9dce1af060017709543"]["400 BC to 276 BC"] = {
  startDate=-400,
  endDate=-276
}
army_dates["5fb1b9dce1af060017709543"]["400 BC to 356 BC"] = {
  startDate=-400,
  endDate=-356
}
army_dates["5fb1b9dce1af060017709543"]["355 BC to 341 BC"] = {
  startDate=-355,
  endDate=-341
}
army_dates["5fb1b9dce1af060017709543"]["340 BC"] = {
  startDate=-340,
  endDate=-340
}
army_dates["5fb1b9dce1af060017709543"]["339 BC to 276 BC"] = {
  startDate=-339,
  endDate=-276
}
-- 5fb1b9dce1af060017709543 Camillan Roman  400 to 276 BC

army['5fb1b9dce1af060017709543']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Camillan Roman  400 to 276 BC',
    id='5fb1b9dce1af060017709543',
    dateRange={
      startDate=-400,
      endDate=-276,
    }
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720],
  g_base_definitions[g_str_5fb1ba26e1af06001770c723],
  g_base_definitions[g_str_5fb1ba26e1af06001770c725],
  g_base_definitions[g_str_5fb1ba26e1af06001770c727],
  g_base_definitions[g_str_5fb1ba26e1af06001770c729],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_fortified],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709543"] = army["5fb1b9dce1af060017709543"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709543"] = {}
army_dates["5fb1b9dce1af060017709543"]["400 BC to 276 BC"] = {
  startDate=-400,
  endDate=-276
}
army_dates["5fb1b9dce1af060017709543"]["400 BC to 356 BC"] = {
  startDate=-400,
  endDate=-356
}
army_dates["5fb1b9dce1af060017709543"]["355 BC to 341 BC"] = {
  startDate=-355,
  endDate=-341
}
army_dates["5fb1b9dce1af060017709543"]["340 BC"] = {
  startDate=-340,
  endDate=-340
}
army_dates["5fb1b9dce1af060017709543"]["339 BC to 276 BC"] = {
  startDate=-339,
  endDate=-276
}
