-- 5fb1b9f6e1af06001770a48a Mapuche  1461 to 1552 AD

army['5fb1b9f6e1af06001770a48a']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Mapuche  1461 to 1552 AD',
    id='5fb1b9f6e1af06001770a48a',
    dateRange={
      startDate=1461,
      endDate=1552,
    },
  },
  g_base_definitions[g_str_615351b703385c0016b88f08_general],
  g_base_definitions[g_str_615351b703385c0016b88f08],
  g_base_definitions[g_str_615351b703385c0016b88f0a],
  g_base_definitions[g_str_615351b703385c0016b88f0c],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a48a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a48a"] = army["5fb1b9f6e1af06001770a48a"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Mapuche  1461 to 1552 AD"] = army["5fb1b9f6e1af06001770a48a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mapuche  1461 to 1552 AD"] = army["5fb1b9f6e1af06001770a48a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a48a"] = {}
army_dates["5fb1b9f6e1af06001770a48a"]["1461 AD to 1552 AD"] = {
  startDate=1461,
  endDate=1552
}
