troop_options['5fb1ba3fe1af06001770f634'] = {
  min=2,
  max=5,
  dateRange={
    startDate=-315,
    endDate=302,
  }
}
troop_options['5fb1ba3fe1af06001770f637'] = {
  min=1,
  max=3,
  dateRange={
    startDate=303,
    endDate=550,
  }
}
troop_options['5fb1ba3fe1af06001770f63b'] = {
  min=1,
  max=2,
  dateRange={
    startDate=303,
    endDate=550,
  }
}
troop_options['5fb1ba3fe1af06001770f63e'] = {
  min=4,
  max=14,
  dateRange={
    startDate=-315,
    endDate=550,
  }
}
troop_options['5fb1ba3fe1af06001770f641'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-315,
    endDate=550,
  }
}
troop_options['5fb1ba3fe1af06001770f645'] = {
  min=1,
  max=5,
  dateRange={
    startDate=-315,
    endDate=550,
  }
}
troop_options['5fb1ba3fe1af06001770f648'] = {
  min=0,
  max=2,
  dateRange={
    startDate=110,
    endDate=214,
  }
}
-- allies
