troop_options['5fb1ba3de1af06001770f291'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f294'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1206,
    endDate=1219,
  }
}
troop_options['5fb1ba3de1af06001770f297'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1220,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f29a'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f29c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f29f'] = {
  min=0,
  max=5,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f2a2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f2a4'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f2a6'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
troop_options['5fb1ba3de1af06001770f2a8'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1206,
    endDate=1295,
  }
}
-- allies
