troop_options['615351ab03385c0016b870ed'] = {
  min=2,
  max=3,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b870f0'] = {
  min=2,
  max=3,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b870f3'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b870f5'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b870f8'] = {
  min=4,
  max=8,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b870fb'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b870fe'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b87100'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
troop_options['615351ab03385c0016b87102'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1445,
    endDate=1480,
  }
}
-- allies
