-- 5fb1b9e6e1af060017709b63 Hausa States  1391 to 1600 AD

army['5fb1b9e6e1af060017709b63']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Steppe',
    },
    name='Hausa States  1391 to 1600 AD',
    id='5fb1b9e6e1af060017709b63',
    dateRange={
      startDate=1391,
      endDate=1600,
    }
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6b],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6d],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b63"] = army["5fb1b9e6e1af060017709b63"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Hausa States  1391 to 1600 AD"] = army["5fb1b9e6e1af060017709b63"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hausa States  1391 to 1600 AD"] = army["5fb1b9e6e1af060017709b63"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b63"] = {}
army_dates["5fb1b9e6e1af060017709b63"]["1391 AD to 1600 AD"] = {
  startDate=1391,
  endDate=1600
}
-- 5fb1b9e6e1af060017709b63 Hausa States  1391 to 1600 AD

army['5fb1b9e6e1af060017709b63']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Steppe',
    },
    name='Hausa States  1391 to 1600 AD',
    id='5fb1b9e6e1af060017709b63',
    dateRange={
      startDate=1391,
      endDate=1600,
    }
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6b],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6d],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b63"] = army["5fb1b9e6e1af060017709b63"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Hausa States  1391 to 1600 AD"] = army["5fb1b9e6e1af060017709b63"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hausa States  1391 to 1600 AD"] = army["5fb1b9e6e1af060017709b63"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b63"] = {}
army_dates["5fb1b9e6e1af060017709b63"]["1391 AD to 1600 AD"] = {
  startDate=1391,
  endDate=1600
}
-- 5fb1b9e6e1af060017709b63 Hausa States  1391 to 1600 AD

army['5fb1b9e6e1af060017709b63']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Steppe',
    },
    name='Hausa States  1391 to 1600 AD',
    id='5fb1b9e6e1af060017709b63',
    dateRange={
      startDate=1391,
      endDate=1600,
    }
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6b],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6d],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b63"] = army["5fb1b9e6e1af060017709b63"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Hausa States  1391 to 1600 AD"] = army["5fb1b9e6e1af060017709b63"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hausa States  1391 to 1600 AD"] = army["5fb1b9e6e1af060017709b63"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b63"] = {}
army_dates["5fb1b9e6e1af060017709b63"]["1391 AD to 1600 AD"] = {
  startDate=1391,
  endDate=1600
}
