-- 5fb1b9e0e1af0600177097c0 Parthian  250 BC to 225 AD

army['5fb1b9e0e1af0600177097c0']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Parthian  250 BC to 225 AD',
    id='5fb1b9e0e1af0600177097c0',
    dateRange={
      startDate=-250,
      endDate=225,
    },
  },
  g_base_definitions[g_str_615351a503385c0016b86145_general],
  g_base_definitions[g_str_615351a503385c0016b86145_general_armored_camelry],
  g_base_definitions[g_str_615351a503385c0016b86145],
  g_base_definitions[g_str_615351a503385c0016b86145_armored_camelry],
  g_base_definitions[g_str_615351a503385c0016b86148],
  g_base_definitions[g_str_615351a503385c0016b8614a],
  g_base_definitions[g_str_615351a503385c0016b8614b],
  g_base_definitions[g_str_615351a503385c0016b8614d],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097c0_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097c0_camp_pack_train],
  g_base_definitions[g_str_6153519303385c0016b83c4d],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097c0"] = army["5fb1b9e0e1af0600177097c0"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Parthian  250 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c0"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Parthian  250 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c0"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Parthian  250 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c0"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Parthian  250 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c0"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097c0"] = {}
army_dates["5fb1b9e0e1af0600177097c0"]["250 BC to 225 AD"] = {
  startDate=-250,
  endDate=225
}
army_dates["5fb1b9e0e1af0600177097c0"]["250 BC to 167 BC"] = {
  startDate=-250,
  endDate=-167
}
army_dates["5fb1b9e0e1af0600177097c0"]["166 BC to 164 BC"] = {
  startDate=-166,
  endDate=-164
}
army_dates["5fb1b9e0e1af0600177097c0"]["163 BC to 148 BC"] = {
  startDate=-163,
  endDate=-148
}
army_dates["5fb1b9e0e1af0600177097c0"]["147 BC to 131 BC"] = {
  startDate=-147,
  endDate=-131
}
army_dates["5fb1b9e0e1af0600177097c0"]["130 BC"] = {
  startDate=-130,
  endDate=-130
}
army_dates["5fb1b9e0e1af0600177097c0"]["129 BC"] = {
  startDate=-129,
  endDate=-129
}
army_dates["5fb1b9e0e1af0600177097c0"]["128 BC to 127 BC"] = {
  startDate=-128,
  endDate=-127
}
army_dates["5fb1b9e0e1af0600177097c0"]["126 BC to 106 BC"] = {
  startDate=-126,
  endDate=-106
}
army_dates["5fb1b9e0e1af0600177097c0"]["105 BC to 84 BC"] = {
  startDate=-105,
  endDate=-84
}
army_dates["5fb1b9e0e1af0600177097c0"]["83 BC to 80 BC"] = {
  startDate=-83,
  endDate=-80
}
army_dates["5fb1b9e0e1af0600177097c0"]["79 BC to 70 BC"] = {
  startDate=-79,
  endDate=-70
}
army_dates["5fb1b9e0e1af0600177097c0"]["69 BC to 66 BC"] = {
  startDate=-69,
  endDate=-66
}
army_dates["5fb1b9e0e1af0600177097c0"]["65 BC to 63 BC"] = {
  startDate=-65,
  endDate=-63
}
army_dates["5fb1b9e0e1af0600177097c0"]["62 BC to 41 BC"] = {
  startDate=-62,
  endDate=-41
}
army_dates["5fb1b9e0e1af0600177097c0"]["40 BC to 39 BC"] = {
  startDate=-40,
  endDate=-39
}
army_dates["5fb1b9e0e1af0600177097c0"]["38 BC to 35 BC"] = {
  startDate=-38,
  endDate=-35
}
army_dates["5fb1b9e0e1af0600177097c0"]["34 BC to 25 BC"] = {
  startDate=-34,
  endDate=-25
}
army_dates["5fb1b9e0e1af0600177097c0"]["24 BC to 34 AD"] = {
  startDate=-24,
  endDate=34
}
army_dates["5fb1b9e0e1af0600177097c0"]["35 AD"] = {
  startDate=35,
  endDate=35
}
army_dates["5fb1b9e0e1af0600177097c0"]["36 AD to 41 AD"] = {
  startDate=36,
  endDate=41
}
army_dates["5fb1b9e0e1af0600177097c0"]["42 AD to 50 AD"] = {
  startDate=42,
  endDate=50
}
army_dates["5fb1b9e0e1af0600177097c0"]["51 AD to 72 AD"] = {
  startDate=51,
  endDate=72
}
army_dates["5fb1b9e0e1af0600177097c0"]["73 AD to 225 AD"] = {
  startDate=73,
  endDate=225
}
