-- 5fb1b9dde1af060017709617 Lykian  546 to 300 BC

army['5fb1b9dde1af060017709617']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Lykian  546 to 300 BC',
    id='5fb1b9dde1af060017709617',
    dateRange={
      startDate=-546,
      endDate=-300,
    },
  },
  g_base_definitions[g_str_615351a303385c0016b85ad7_general],
  g_base_definitions[g_str_615351a303385c0016b85ad7],
  g_base_definitions[g_str_615351a303385c0016b85ada_general],
  g_base_definitions[g_str_615351a303385c0016b85ada],
  g_base_definitions[g_str_615351a303385c0016b85adc],
  g_base_definitions[g_str_615351a303385c0016b85ade],
  g_base_definitions[g_str_615351a303385c0016b85ae1],
  g_base_definitions[g_str_615351a303385c0016b85ae3],
  g_base_definitions[g_str_615351a303385c0016b85ae5],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af060017709617"] = army["5fb1b9dde1af060017709617"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Lykian  546 to 300 BC"] = army["5fb1b9dde1af060017709617"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Lykian  546 to 300 BC"] = army["5fb1b9dde1af060017709617"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af060017709617"] = {}
army_dates["5fb1b9dde1af060017709617"]["546 BC to 300 BC"] = {
  startDate=-546,
  endDate=-300
}
