-- 5fb1b9e6e1af060017709b63 Hausa States  1391 to 1600 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba32e1af06001770dd66_general='5fb1ba32e1af06001770dd66_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dd66_general]={
  id=g_str_5fb1ba32e1af06001770dd66_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen, some with complete quilted armor for man and mount',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770dd66='5fb1ba32e1af06001770dd66'
g_base_definitions[g_str_5fb1ba32e1af06001770dd66]={
  id=g_str_5fb1ba32e1af06001770dd66,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen, some with complete quilted armor for man and mount',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770dd67_general='5fb1ba32e1af06001770dd67_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dd67_general]={
  id=g_str_5fb1ba32e1af06001770dd67_general,
  name='Cataphracts General',
  min=0,
  max=1,
  description='Horsemen, some with complete quilted armor for man and mount',
  general=true,
  troop_type="Cataphracts",
}
g_str_5fb1ba32e1af06001770dd67='5fb1ba32e1af06001770dd67'
g_base_definitions[g_str_5fb1ba32e1af06001770dd67]={
  id=g_str_5fb1ba32e1af06001770dd67,
  name='Cataphracts',
  min=0,
  max=1,
  description='Horsemen, some with complete quilted armor for man and mount',
  troop_type="Cataphracts",
}
g_str_5fb1ba32e1af06001770dd69_general='5fb1ba32e1af06001770dd69_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dd69_general]={
  id=g_str_5fb1ba32e1af06001770dd69_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770dd69='5fb1ba32e1af06001770dd69'
g_base_definitions[g_str_5fb1ba32e1af06001770dd69]={
  id=g_str_5fb1ba32e1af06001770dd69,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770dd6b='5fb1ba32e1af06001770dd6b'
g_base_definitions[g_str_5fb1ba32e1af06001770dd6b]={
  id=g_str_5fb1ba32e1af06001770dd6b,
  name='Light Spear',
  min=1,
  max=4,
  description='Spearmen',
  troop_type="Light Spear",
}
g_str_5fb1ba32e1af06001770dd6d='5fb1ba32e1af06001770dd6d'
g_base_definitions[g_str_5fb1ba32e1af06001770dd6d]={
  id=g_str_5fb1ba32e1af06001770dd6d,
  name='Bow Levy',
  min=14,
  max=20,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1b9e6e1af060017709b63_camp='5fb1b9e6e1af060017709b63_camp'
g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp]={
  name='Camp',
  id=g_str_5fb1b9e6e1af060017709b63_camp,
  min=1,
  max=1,
}
army['5fb1b9e6e1af060017709b63']={
  data={
    name='Hausa States  1391 to 1600 AD'
  },
  g_base_definitions[g_str_5fb1b9e6e1af060017709b63_camp],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6f],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd70],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd66],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd67],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd69],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6b],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd6d],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b63"] = army["5fb1b9e6e1af060017709b63"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Hausa States  1391 to 1600 AD"] = army["5fb1b9e6e1af060017709b63"]
