troop_options['615351b503385c0016b88c15'] = {
  min=1,
  max=1,
  dateRange={
    startDate=501,
    endDate=645,
  }
}
troop_options['615351b503385c0016b88c17'] = {
  min=1,
  max=3,
  dateRange={
    startDate=501,
    endDate=645,
  }
}
troop_options['615351b503385c0016b88c19'] = {
  min=3,
  max=6,
  dateRange={
    startDate=501,
    endDate=645,
  }
}
troop_options['615351b503385c0016b88c1b'] = {
  min=2,
  max=6,
  dateRange={
    startDate=501,
    endDate=645,
  }
}
troop_options['615351b503385c0016b88c1e'] = {
  min=0,
  max=3,
  dateRange={
    startDate=501,
    endDate=645,
  }
}
troop_options['615351b503385c0016b88c20'] = {
  min=0,
  max=1,
  dateRange={
    startDate=501,
    endDate=645,
  }
}
troop_options['615351b503385c0016b88c22'] = {
  min=0,
  max=1,
  dateRange={
    startDate=501,
    endDate=645,
  }
}
-- allies
