-- 5fb1b9dfe1af06001770971d Cleopatran Ptolemaic  53 to 30 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba29e1af06001770cea8_general='5fb1ba29e1af06001770cea8_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general]={
  id=g_str_5fb1ba29e1af06001770cea8_general,
  name='Knights General',
  min=0,
  max=1,
  description='Xystophoroi',
  general=true,
}
g_str_5fb1ba29e1af06001770cea8_general_dismounted='5fb1ba29e1af06001770cea8_general_dismounted'
g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general_dismounted]={
  id=g_str_5fb1ba29e1af06001770cea8_general_dismounted,
  name='Pikes',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounted from Knights General',
  points=4,
  general=true,
}
g_5fb1ba29e1af06001770cea8_general_dismounted=g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general_dismounted]
g_str_5fb1ba29e1af06001770cea8_general_mounted='5fb1ba29e1af06001770cea8_general_mounted'
g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general_mounted]={
  id=g_str_5fb1ba29e1af06001770cea8_general_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounting as Pikes',
  points=4,
  dismount_as=g_5fb1ba29e1af06001770cea8_general_dismounted,
  general=true,
}
g_str_5fb1ba29e1af06001770cea8='5fb1ba29e1af06001770cea8'
g_base_definitions[g_str_5fb1ba29e1af06001770cea8]={
  id=g_str_5fb1ba29e1af06001770cea8,
  name='Knights',
  min=0,
  max=1,
  description='Xystophoroi',
}
g_str_5fb1ba29e1af06001770cea8_dismounted='5fb1ba29e1af06001770cea8_dismounted'
g_base_definitions[g_str_5fb1ba29e1af06001770cea8_dismounted]={
  id=g_str_5fb1ba29e1af06001770cea8_dismounted,
  name='Pikes',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounted from Knights',
  points=4,
}
g_5fb1ba29e1af06001770cea8_dismounted=g_base_definitions[g_str_5fb1ba29e1af06001770cea8_dismounted]
g_str_5fb1ba29e1af06001770cea8_mounted='5fb1ba29e1af06001770cea8_mounted'
g_base_definitions[g_str_5fb1ba29e1af06001770cea8_mounted]={
  id=g_str_5fb1ba29e1af06001770cea8_mounted,
  name='Knights',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounting as Pikes',
  points=4,
  dismount_as=g_5fb1ba29e1af06001770cea8_dismounted,
}
g_str_5fb1ba29e1af06001770ceab_general='5fb1ba29e1af06001770ceab_general'
g_base_definitions[g_str_5fb1ba29e1af06001770ceab_general]={
  id=g_str_5fb1ba29e1af06001770ceab_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Mercenary Greek or Tarentine horsemen',
  general=true,
}
g_str_5fb1ba29e1af06001770ceab='5fb1ba29e1af06001770ceab'
g_base_definitions[g_str_5fb1ba29e1af06001770ceab]={
  id=g_str_5fb1ba29e1af06001770ceab,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Mercenary Greek or Tarentine horsemen',
}
g_str_5fb1ba29e1af06001770cead='5fb1ba29e1af06001770cead'
g_base_definitions[g_str_5fb1ba29e1af06001770cead]={
  id=g_str_5fb1ba29e1af06001770cead,
  name='Pikes',
  min=0,
  max=6,
  description='Phalanx',
}
g_str_5fb1ba29e1af06001770ceaf='5fb1ba29e1af06001770ceaf'
g_base_definitions[g_str_5fb1ba29e1af06001770ceaf]={
  id=g_str_5fb1ba29e1af06001770ceaf,
  name='Light Foot',
  min=4,
  max=8,
  description='Brigands from Kilikia, Syria, and other various light infantry',
}
g_str_5fb1ba29e1af06001770ceb1='5fb1ba29e1af06001770ceb1'
g_base_definitions[g_str_5fb1ba29e1af06001770ceb1]={
  id=g_str_5fb1ba29e1af06001770ceb1,
  name='Skirmishers',
  min=0,
  max=2,
  description='Cretan skirmishing bowmen',
}
g_str_5fb1ba29e1af06001770ceb3='5fb1ba29e1af06001770ceb3'
g_base_definitions[g_str_5fb1ba29e1af06001770ceb3]={
  id=g_str_5fb1ba29e1af06001770ceb3,
  name='Light Foot',
  min=0,
  max=1,
  description='Thracian light infantry',
}
g_str_5fb1ba29e1af06001770ceb5='5fb1ba29e1af06001770ceb5'
g_base_definitions[g_str_5fb1ba29e1af06001770ceb5]={
  id=g_str_5fb1ba29e1af06001770ceb5,
  name='Rabble',
  min=0,
  max=2,
  description='Garrisons and border guardsman',
}
g_str_5fb1ba29e1af06001770ceb7='5fb1ba29e1af06001770ceb7'
g_base_definitions[g_str_5fb1ba29e1af06001770ceb7]={
  id=g_str_5fb1ba29e1af06001770ceb7,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt-shooters',
}
g_str_5fb1ba29e1af06001770ceb9_general='5fb1ba29e1af06001770ceb9_general'
g_base_definitions[g_str_5fb1ba29e1af06001770ceb9_general]={
  id=g_str_5fb1ba29e1af06001770ceb9_general,
  name='Heavy Foot General',
  min=2,
  max=1,
  description='Imitation legionaries',
  general=true,
}
g_str_5fb1ba29e1af06001770ceb9='5fb1ba29e1af06001770ceb9'
g_base_definitions[g_str_5fb1ba29e1af06001770ceb9]={
  id=g_str_5fb1ba29e1af06001770ceb9,
  name='Heavy Foot',
  min=2,
  max=4,
  description='Imitation legionaries',
}
g_str_5fb1ba29e1af06001770cebb='5fb1ba29e1af06001770cebb'
g_base_definitions[g_str_5fb1ba29e1af06001770cebb]={
  id=g_str_5fb1ba29e1af06001770cebb,
  name='Elite Foot',
  min=0,
  max=2,
  description='Expatriate Roman legionaries',
}
g_str_5fb1ba29e1af06001770cebd='5fb1ba29e1af06001770cebd'
g_base_definitions[g_str_5fb1ba29e1af06001770cebd]={
  id=g_str_5fb1ba29e1af06001770cebd,
  name='Raiders',
  min=0,
  max=1,
  description='Nubian axemen',
}
g_str_5fb1ba29e1af06001770cebf='5fb1ba29e1af06001770cebf'
g_base_definitions[g_str_5fb1ba29e1af06001770cebf]={
  id=g_str_5fb1ba29e1af06001770cebf,
  name='Rabble',
  min=0,
  max=6,
  description='Rioting Alexandrian mob',
}
g_str_5fb1b9dfe1af06001770971d_camp='5fb1b9dfe1af06001770971d_camp'
g_base_definitions[g_str_5fb1b9dfe1af06001770971d_camp]={
  name='Camp',
  id=g_str_5fb1b9dfe1af06001770971d_camp,
  min=1,
  max=1,
}
army['5fb1b9dfe1af06001770971d']={
  data={
    name='Cleopatran Ptolemaic  53 to 30 BC'
  },
  g_base_definitions[g_str_5fb1b9dfe1af06001770971d_camp],
  g_base_definitions[g_str_5fb1ba29e1af06001770cec1],
  g_base_definitions[g_str_5fb1ba29e1af06001770cec3],
  g_base_definitions[g_str_5fb1ba29e1af06001770cec5],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceab_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceab],
  g_base_definitions[g_str_5fb1ba29e1af06001770cead],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceaf],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb1],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb3],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb5],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb7],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb9_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb9],
  g_base_definitions[g_str_5fb1ba29e1af06001770cebb],
  g_base_definitions[g_str_5fb1ba29e1af06001770cebd],
  g_base_definitions[g_str_5fb1ba29e1af06001770cebf],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770971d"] = army["5fb1b9dfe1af06001770971d"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Cleopatran Ptolemaic  53 to 30 BC"] = army["5fb1b9dfe1af06001770971d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Cleopatran Ptolemaic  53 to 30 BC"] = army["5fb1b9dfe1af06001770971d"]
