troop_options['5fb1ba38e1af06001770ea3c'] = {
  min=2,
  max=3,
  dateRange={
    startDate=1262,
    endDate=1460,
  }
}
troop_options['5fb1ba38e1af06001770ea3e'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1316,
    endDate=1460,
  }
}
troop_options['5fb1ba38e1af06001770ea41'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1262,
    endDate=1460,
  }
}
troop_options['5fb1ba38e1af06001770ea43'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1262,
    endDate=1460,
  }
}
troop_options['5fb1ba38e1af06001770ea45'] = {
  min=4,
  max=8,
  dateRange={
    startDate=1262,
    endDate=1460,
  }
}
troop_options['5fb1ba38e1af06001770ea47'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1262,
    endDate=1460,
  }
}
-- allies
