-- 5fb1b9dee1af0600177096c1 Later Galatian  64 to 25 BC

army['5fb1b9dee1af0600177096c1']={
  data={
    invasionRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Galatian  64 to 25 BC',
    id='5fb1b9dee1af0600177096c1',
    dateRange={
      startDate=-64,
      endDate=-25,
    }
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0c_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0c_general_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0c_general_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0c_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0c_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0f_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd0f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd11],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd13],
  g_base_definitions[g_str_5fb1b9dee1af0600177096c1_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096c1"] = army["5fb1b9dee1af0600177096c1"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Galatian  64 to 25 BC"] = army["5fb1b9dee1af0600177096c1"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Later Galatian  64 to 25 BC"] = army["5fb1b9dee1af0600177096c1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Galatian  64 to 25 BC"] = army["5fb1b9dee1af0600177096c1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096c1"] = {}
army_dates["5fb1b9dee1af0600177096c1"]["64 BC to 25 BC"] = {
  startDate=-64,
  endDate=-25
}
