-- 5fb1b9f5e1af06001770a3f0 Xicalanca City States and 8-Deer Era Mixtec  750 to 1000 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba44e1af06001770fdaf='5fb1ba44e1af06001770fdaf'
g_base_definitions[g_str_5fb1ba44e1af06001770fdaf]={
  id=g_str_5fb1ba44e1af06001770fdaf,
  name='Skirmishers',
  min=6,
  max=16,
  description='Skirmishing foot armed with atlatls',
}
g_str_5fb1ba44e1af06001770fdb1='5fb1ba44e1af06001770fdb1'
g_base_definitions[g_str_5fb1ba44e1af06001770fdb1]={
  id=g_str_5fb1ba44e1af06001770fdb1,
  name='Light Foot General',
  min=0,
  max=1,
  description='Formed infantry armed with spear and atlatl',
  general=true,
}
g_str_5fb1ba44e1af06001770fdb1='5fb1ba44e1af06001770fdb1'
g_base_definitions[g_str_5fb1ba44e1af06001770fdb1]={
  id=g_str_5fb1ba44e1af06001770fdb1,
  name='Light Foot',
  min=0,
  max=10,
  description='Formed infantry armed with spear and atlatl',
}
g_str_5fb1b9f5e1af06001770a3f0_camp='5fb1b9f5e1af06001770a3f0_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3f0_camp]={
  name='Camp',
  id=g_str_5fb1b9f5e1af06001770a3f0_camp,
  min=1,
  max=1,
}
army['5fb1b9f5e1af06001770a3f0']={
  data={
    name='Xicalanca City States and 8-Deer Era Mixtec  750 to 1000 AD'
  },
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3f0_camp],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdb3],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdaf],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdb1],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdb1],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3f0"] = army["5fb1b9f5e1af06001770a3f0"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Xicalanca City States and 8-Deer Era Mixtec  750 to 1000 AD"] = army["5fb1b9f5e1af06001770a3f0"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Xicalanca City States and 8-Deer Era Mixtec  750 to 1000 AD"] = army["5fb1b9f5e1af06001770a3f0"]
