-- 5fb1b9f4e1af06001770a37e Olmec  1150 to 400 BC

army['5fb1b9f4e1af06001770a37e']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Olmec  1150 to 400 BC',
    id='5fb1b9f4e1af06001770a37e',
    dateRange={
      startDate=-1150,
      endDate=-400,
    }
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf5_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf5],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf7_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf7],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcfa],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a37e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a37e"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a37e"] = {}
army_dates["5fb1b9f4e1af06001770a37e"]["1150 BC to 400 BC"] = {
  startDate=-1150,
  endDate=-400
}
army_dates["5fb1b9f4e1af06001770a37e"]["1150 BC to 900 BC"] = {
  startDate=-1150,
  endDate=-900
}
army_dates["5fb1b9f4e1af06001770a37e"]["899 BC to 400 BC"] = {
  startDate=-899,
  endDate=-400
}
-- 5fb1b9f4e1af06001770a37e Olmec  1150 to 400 BC

army['5fb1b9f4e1af06001770a37e']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Olmec  1150 to 400 BC',
    id='5fb1b9f4e1af06001770a37e',
    dateRange={
      startDate=-1150,
      endDate=-400,
    }
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf5_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf5],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf7_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf7],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcfa],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a37e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a37e"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a37e"] = {}
army_dates["5fb1b9f4e1af06001770a37e"]["1150 BC to 400 BC"] = {
  startDate=-1150,
  endDate=-400
}
army_dates["5fb1b9f4e1af06001770a37e"]["1150 BC to 900 BC"] = {
  startDate=-1150,
  endDate=-900
}
army_dates["5fb1b9f4e1af06001770a37e"]["899 BC to 400 BC"] = {
  startDate=-899,
  endDate=-400
}
-- 5fb1b9f4e1af06001770a37e Olmec  1150 to 400 BC

army['5fb1b9f4e1af06001770a37e']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Olmec  1150 to 400 BC',
    id='5fb1b9f4e1af06001770a37e',
    dateRange={
      startDate=-1150,
      endDate=-400,
    }
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf5_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf5],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf7_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcf7],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcfa],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a37e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a37e"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Olmec  1150 to 400 BC"] = army["5fb1b9f4e1af06001770a37e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a37e"] = {}
army_dates["5fb1b9f4e1af06001770a37e"]["1150 BC to 400 BC"] = {
  startDate=-1150,
  endDate=-400
}
army_dates["5fb1b9f4e1af06001770a37e"]["1150 BC to 900 BC"] = {
  startDate=-1150,
  endDate=-900
}
army_dates["5fb1b9f4e1af06001770a37e"]["899 BC to 400 BC"] = {
  startDate=-899,
  endDate=-400
}
