troop_options['615351a303385c0016b85c51'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c53'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c55'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c57'] = {
  min=2,
  max=8,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c5a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c5c'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c5f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c61'] = {
  min=2,
  max=8,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c63'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c65'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
troop_options['615351a303385c0016b85c68'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-320,
    endDate=-281,
  }
}
-- allies
