-- 5fb1b9e2e1af06001770992a Alamanni  250 to 584 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba2de1af06001770d5ae']= {
  min=0,
  max=1,
  description='Noble horsemen',
  core='all',
}
g_troop_entry['5fb1ba2de1af06001770d5af']= {
  troop_option='5fb1ba2de1af06001770d5ae',
  troopTypeCode='JCV',
}
g_troop_option['5fb1ba2de1af06001770d5b1']= {
  min=12,
  max=15,
  description='Fierce fighters',
  core='all',
}
g_troop_entry['5fb1ba2de1af06001770d5b2']= {
  troop_option='5fb1ba2de1af06001770d5b1',
  troopTypeCode='WRR',
}
g_troop_option['5fb1ba2de1af06001770d5b3']= {
  min=1,
  max=5,
  description='Formed bowmen',
  core='all',
}
g_troop_entry['5fb1ba2de1af06001770d5b4']= {
  troop_option='5fb1ba2de1af06001770d5b3',
  troopTypeCode='BLV',
}
g_troop_option['5fb1ba2de1af06001770d5b5']= {
  min=0,
  max=2,
  description='Javelinmen',
}
g_troop_entry['5fb1ba2de1af06001770d5b6']= {
  troop_option='5fb1ba2de1af06001770d5b5',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba2de1af06001770d5b7']= {
  min=0,
  max=2,
  description='Skirmishing bowmen',
}
g_troop_entry['5fb1ba2de1af06001770d5b8']= {
  troop_option='5fb1ba2de1af06001770d5b7',
  troopTypeCode='SKM',
}
g_str_5fb1ba2de1af06001770d5af_general='5fb1ba2de1af06001770d5af_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d5af_general]={
  id=g_str_5fb1ba2de1af06001770d5af_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2de1af06001770d5af_general_dismounted='5fb1ba2de1af06001770d5af_general_dismounted'
g_str_5fb1ba2de1af06001770d5af_general_mounted='5fb1ba2de1af06001770d5af_general_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d5af_general_dismounted]={
  id=g_str_5fb1ba2de1af06001770d5af_general_dismounted,
  name='Warriors General',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  dismounted_from=g_str_5fb1ba2de1af06001770d5af_general_mounted,
  general=true,
  troop_type="Warriors",
}
g_base_definitions[g_str_5fb1ba2de1af06001770d5af_general_mounted]={
  id=g_str_5fb1ba2de1af06001770d5af_general_mounted,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_str_5fb1ba2de1af06001770d5af_general_dismounted,
  general=true,
  deployment_dismounting=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2de1af06001770d5af='5fb1ba2de1af06001770d5af'
g_base_definitions[g_str_5fb1ba2de1af06001770d5af]={
  id=g_str_5fb1ba2de1af06001770d5af,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2de1af06001770d5af_dismounted='5fb1ba2de1af06001770d5af_dismounted'
g_str_5fb1ba2de1af06001770d5af_mounted='5fb1ba2de1af06001770d5af_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d5af_dismounted]={
  id=g_str_5fb1ba2de1af06001770d5af_dismounted,
  name='Warriors',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
  dismounted_from=g_str_5fb1ba2de1af06001770d5af_mounted,
  troop_type="Warriors",
}
g_base_definitions[g_str_5fb1ba2de1af06001770d5af_mounted]={
  id=g_str_5fb1ba2de1af06001770d5af_mounted,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_str_5fb1ba2de1af06001770d5af_dismounted,
  deployment_dismounting=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2de1af06001770d5b2_general='5fb1ba2de1af06001770d5b2_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d5b2_general]={
  id=g_str_5fb1ba2de1af06001770d5b2_general,
  name='Warriors General',
  min=12,
  max=1,
  description='Fierce fighters',
  general=true,
  troop_type="Warriors",
}
g_str_5fb1ba2de1af06001770d5b2='5fb1ba2de1af06001770d5b2'
g_base_definitions[g_str_5fb1ba2de1af06001770d5b2]={
  id=g_str_5fb1ba2de1af06001770d5b2,
  name='Warriors',
  min=12,
  max=15,
  description='Fierce fighters',
  troop_type="Warriors",
}
g_str_5fb1ba2de1af06001770d5b4='5fb1ba2de1af06001770d5b4'
g_base_definitions[g_str_5fb1ba2de1af06001770d5b4]={
  id=g_str_5fb1ba2de1af06001770d5b4,
  name='Bow Levy',
  min=1,
  max=5,
  description='Formed bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba2de1af06001770d5b6='5fb1ba2de1af06001770d5b6'
g_base_definitions[g_str_5fb1ba2de1af06001770d5b6]={
  id=g_str_5fb1ba2de1af06001770d5b6,
  name='Light Foot',
  min=0,
  max=2,
  description='Javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba2de1af06001770d5b8='5fb1ba2de1af06001770d5b8'
g_base_definitions[g_str_5fb1ba2de1af06001770d5b8]={
  id=g_str_5fb1ba2de1af06001770d5b8,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1b9e2e1af06001770992a_camp='5fb1b9e2e1af06001770992a_camp'
g_base_definitions[g_str_5fb1b9e2e1af06001770992a_camp]={
  id=g_str_5fb1b9e2e1af06001770992a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e2e1af06001770992a']={
  data={
    name='Alamanni  250 to 584 AD',
    id='5fb1b9e2e1af06001770992a',
    army_id='5fb1b9e2e1af06001770992a'
  },
  g_base_definitions[g_str_5fb1ba2de1af06001770d5af_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5af_general_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5af_general_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5af],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5af_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5af_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5b2_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5b2],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5b4],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5b6],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5b8],
  g_base_definitions[g_str_5fb1b9e2e1af06001770992a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af06001770992a"] = army["5fb1b9e2e1af06001770992a"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Alamanni  250 to 584 AD"] = army["5fb1b9e2e1af06001770992a"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Alamanni  250 to 584 AD"] = army["5fb1b9e2e1af06001770992a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Alamanni  250 to 584 AD"] = army["5fb1b9e2e1af06001770992a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af06001770992a"] = {}
army_dates["5fb1b9e2e1af06001770992a"]["250 AD to 584 AD"] ="5fb1b9e2e1af06001770992a"
