-- 5fb1b9e7e1af060017709c19 Transitional Renaissance Spanish  1495 to 1503 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba33e1af06001770dfb1_general='5fb1ba33e1af06001770dfb1_general'
g_base_definitions[g_str_5fb1ba33e1af06001770dfb1_general]={
  id=g_str_5fb1ba33e1af06001770dfb1_general,
  name='Knights General',
  min=2,
  max=1,
  description='Men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dfb0",
}
g_str_5fb1ba33e1af06001770dfb1='5fb1ba33e1af06001770dfb1'
g_base_definitions[g_str_5fb1ba33e1af06001770dfb1]={
  id=g_str_5fb1ba33e1af06001770dfb1,
  name='Knights',
  min=2,
  max=4,
  description='Men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dfb0",
}
g_str_5fb1ba33e1af06001770dfb3='5fb1ba33e1af06001770dfb3'
g_base_definitions[g_str_5fb1ba33e1af06001770dfb3]={
  id=g_str_5fb1ba33e1af06001770dfb3,
  name='Javelin Cavalry',
  min=2,
  max=4,
  description='Jinetes',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba33e1af06001770dfb2",
}
g_str_5fb1ba33e1af06001770dfb5='5fb1ba33e1af06001770dfb5'
g_base_definitions[g_str_5fb1ba33e1af06001770dfb5]={
  id=g_str_5fb1ba33e1af06001770dfb5,
  name='Light Spear',
  min=2,
  max=4,
  description='Pikemen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba33e1af06001770dfb4",
}
g_str_5fb1ba33e1af06001770dfb7='5fb1ba33e1af06001770dfb7'
g_base_definitions[g_str_5fb1ba33e1af06001770dfb7]={
  id=g_str_5fb1ba33e1af06001770dfb7,
  name='Raiders',
  min=1,
  max=3,
  description='Sword-and-buckler men',
  troop_type="Raiders",
  troop_option_id="5fb1ba33e1af06001770dfb6",
}
g_str_5fb1ba33e1af06001770dfb9='5fb1ba33e1af06001770dfb9'
g_base_definitions[g_str_5fb1ba33e1af06001770dfb9]={
  id=g_str_5fb1ba33e1af06001770dfb9,
  name='Skirmishers',
  min=1,
  max=3,
  description='Crossbowmen and handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba33e1af06001770dfb8",
}
g_str_5fb1ba33e1af06001770dfbb='5fb1ba33e1af06001770dfbb'
g_base_definitions[g_str_5fb1ba33e1af06001770dfbb]={
  id=g_str_5fb1ba33e1af06001770dfbb,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba33e1af06001770dfba",
}
g_str_5fb1b9e7e1af060017709c19_camp='5fb1b9e7e1af060017709c19_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709c19_camp]={
  id=g_str_5fb1b9e7e1af060017709c19_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e7e1af060017709c19_camp_pack_train='5fb1b9e7e1af060017709c19_camp_pack_train'
g_base_definitions[g_str_5fb1b9e7e1af060017709c19_camp_pack_train]={
  id=g_str_5fb1b9e7e1af060017709c19_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e7e1af060017709c19']={
  data={
    name='Transitional Renaissance Spanish  1495 to 1503 AD',
    id='5fb1b9e7e1af060017709c19',
    army_id='5fb1b9e7e1af060017709c19'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770dfb1_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfb1],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfb3],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfb5],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfb7],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfb9],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfbb],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c19_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c19_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c19"] = army["5fb1b9e7e1af060017709c19"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Transitional Renaissance Spanish  1495 to 1503 AD"] = army["5fb1b9e7e1af060017709c19"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Transitional Renaissance Spanish  1495 to 1503 AD"] = army["5fb1b9e7e1af060017709c19"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Transitional Renaissance Spanish  1495 to 1503 AD"] = army["5fb1b9e7e1af060017709c19"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c19"] = {}
army_dates["5fb1b9e7e1af060017709c19"]["1495 AD to 1503 AD"] ="5fb1b9e7e1af060017709c19"
