troop_options['5fb1ba2be1af06001770d2da'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-9,
    endDate=19,
  }
}
troop_options['5fb1ba2be1af06001770d2dd'] = {
  min=0,
  max=9,
  dateRange={
    startDate=-9,
    endDate=19,
  }
}
troop_options['5fb1ba2be1af06001770d2df'] = {
  min=4,
  max=8,
  dateRange={
    startDate=-9,
    endDate=19,
  }
}
troop_options['5fb1ba2be1af06001770d2e1'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-9,
    endDate=19,
  }
}
troop_options['5fb1ba2be1af06001770d2e3'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-9,
    endDate=19,
  }
}
-- allies
