-- 5fb1b9e0e1af0600177097b8 Mountain Indian  500 to 170 BC

army['5fb1b9e0e1af0600177097b8']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Mountain Indian  500 to 170 BC',
    id='5fb1b9e0e1af0600177097b8',
    dateRange={
      startDate=-500,
      endDate=-170,
    },
  },
  g_base_definitions[g_str_615351a503385c0016b86131_general],
  g_base_definitions[g_str_615351a503385c0016b86131],
  g_base_definitions[g_str_615351a503385c0016b86134_general],
  g_base_definitions[g_str_615351a503385c0016b86134],
  g_base_definitions[g_str_615351a503385c0016b86136_general],
  g_base_definitions[g_str_615351a503385c0016b86136],
  g_base_definitions[g_str_615351a503385c0016b86138],
  g_base_definitions[g_str_615351a503385c0016b8613a],
  g_base_definitions[g_str_615351a503385c0016b8613b],
  g_base_definitions[g_str_615351a503385c0016b8613c],
  g_base_definitions[g_str_615351a503385c0016b8613e],
  g_base_definitions[g_str_615351a503385c0016b8613e_elephant_screen],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097b8_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097b8"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097b8"] = {}
army_dates["5fb1b9e0e1af0600177097b8"]["500 BC to 170 BC"] = {
  startDate=-500,
  endDate=-170
}
