-- 5fb1b9e1e1af060017709806 Tigranes  83 to 69 BC

army['5fb1b9e1e1af060017709806']={
  data={
    invasionRatings={
      0,
    },
    homeTopographies={
      'Hilly',
    },
    name='Tigranes  83 to 69 BC',
    id='5fb1b9e1e1af060017709806',
    dateRange={
      startDate=-83,
      endDate=-69,
    }
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d1ad_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1ad],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1af],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1b1],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1b3],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1b5],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1b7],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1b9],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1bb],
  g_base_definitions[g_str_5fb1b9e1e1af060017709806_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709806_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709806"] = army["5fb1b9e1e1af060017709806"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Tigranes  83 to 69 BC"] = army["5fb1b9e1e1af060017709806"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Tigranes  83 to 69 BC"] = army["5fb1b9e1e1af060017709806"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tigranes  83 to 69 BC"] = army["5fb1b9e1e1af060017709806"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709806"] = {}
army_dates["5fb1b9e1e1af060017709806"]["83 BC to 69 BC"] = {
  startDate=-83,
  endDate=-69
}
