-- 5fb1b9f6e1af06001770a496 Shuar  1200 to 1850 AD

army['5fb1b9f6e1af06001770a496']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Hilly',
      'Forest',
    },
    name='Shuar  1200 to 1850 AD',
    id='5fb1b9f6e1af06001770a496',
    dateRange={
      startDate=1200,
      endDate=1850,
    },
  },
  g_base_definitions[g_str_615351b703385c0016b88f18_general],
  g_base_definitions[g_str_615351b703385c0016b88f18],
  g_base_definitions[g_str_615351b703385c0016b88f1a],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a496_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a496"] = army["5fb1b9f6e1af06001770a496"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Shuar  1200 to 1850 AD"] = army["5fb1b9f6e1af06001770a496"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Shuar  1200 to 1850 AD"] = army["5fb1b9f6e1af06001770a496"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a496"] = {}
army_dates["5fb1b9f6e1af06001770a496"]["1200 AD to 1850 AD"] = {
  startDate=1200,
  endDate=1850
}
