g_str_5fb1ba29e1af06001770cd7d_general='5fb1ba29e1af06001770cd7d_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd7d_general]={
  id=g_str_5fb1ba29e1af06001770cd7d_general,
  name='Knights General',
  min=1,
  max=1,
  description='Nobles',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd7c",
}
g_str_5fb1ba29e1af06001770cd7d='5fb1ba29e1af06001770cd7d'
g_base_definitions[g_str_5fb1ba29e1af06001770cd7d]={
  id=g_str_5fb1ba29e1af06001770cd7d,
  name='Knights',
  min=1,
  max=2,
  description='Nobles',
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd7c",
}
g_str_5fb1ba29e1af06001770cd7f='5fb1ba29e1af06001770cd7f'
g_base_definitions[g_str_5fb1ba29e1af06001770cd7f]={
  id=g_str_5fb1ba29e1af06001770cd7f,
  name='Horse Bow',
  min=3,
  max=8,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba29e1af06001770cd7e",
}
g_str_5fb1ba29e1af06001770cd82='5fb1ba29e1af06001770cd82'
g_base_definitions[g_str_5fb1ba29e1af06001770cd82]={
  id=g_str_5fb1ba29e1af06001770cd82,
  name='Light Foot',
  min=1,
  max=2,
  description='Bosporan Greek militia',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cd80",
}
g_str_5fb1ba29e1af06001770cd85='5fb1ba29e1af06001770cd85'
g_base_definitions[g_str_5fb1ba29e1af06001770cd85]={
  id=g_str_5fb1ba29e1af06001770cd85,
  name='Light Foot',
  min=1,
  max=2,
  description='Bosporan Greek militia, possibly trained as imitation legionaries',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cd83",
}
g_str_5fb1ba29e1af06001770cd86='5fb1ba29e1af06001770cd86'
g_base_definitions[g_str_5fb1ba29e1af06001770cd86]={
  id=g_str_5fb1ba29e1af06001770cd86,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Bosporan Greek militia, possibly trained as imitation legionaries',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba29e1af06001770cd83",
}
g_str_5fb1ba29e1af06001770cd88='5fb1ba29e1af06001770cd88'
g_base_definitions[g_str_5fb1ba29e1af06001770cd88]={
  id=g_str_5fb1ba29e1af06001770cd88,
  name='Light Foot',
  min=1,
  max=4,
  description='Subject tribes javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cd87",
}
g_str_5fb1ba29e1af06001770cd8a='5fb1ba29e1af06001770cd8a'
g_base_definitions[g_str_5fb1ba29e1af06001770cd8a]={
  id=g_str_5fb1ba29e1af06001770cd8a,
  name='Bow Levy',
  min=2,
  max=4,
  description='Subject tribes bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba29e1af06001770cd89",
}
g_str_5fb1ba29e1af06001770cd8c='5fb1ba29e1af06001770cd8c'
g_base_definitions[g_str_5fb1ba29e1af06001770cd8c]={
  id=g_str_5fb1ba29e1af06001770cd8c,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba29e1af06001770cd8b",
}
g_str_5fb1ba29e1af06001770cd8e='5fb1ba29e1af06001770cd8e'
g_base_definitions[g_str_5fb1ba29e1af06001770cd8e]={
  id=g_str_5fb1ba29e1af06001770cd8e,
  name='Light Foot',
  min=0,
  max=2,
  description='Thracian and similar mercenary javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cd8d",
}
g_str_5fb1b9dfe1af0600177096e6_camp='5fb1b9dfe1af0600177096e6_camp'
g_base_definitions[g_str_5fb1b9dfe1af0600177096e6_camp]={
  id=g_str_5fb1b9dfe1af0600177096e6_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af0600177096e6_camp_fortified='5fb1b9dfe1af0600177096e6_camp_fortified'
g_base_definitions[g_str_5fb1b9dfe1af0600177096e6_camp_fortified]={
  id=g_str_5fb1b9dfe1af0600177096e6_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
g_str_5fb1ba0ce1af06001770ab12='5fb1ba0ce1af06001770ab12'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab12]={
  id=g_str_5fb1ba0ce1af06001770ab12,
  name='Light Foot',
  min=1,
  max=3,
  description='Thracian mercenary javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0ce1af06001770ab11",
}
g_str_5fb1ba0ce1af06001770ab14='5fb1ba0ce1af06001770ab14'
g_base_definitions[g_str_5fb1ba0ce1af06001770ab14]={
  id=g_str_5fb1ba0ce1af06001770ab14,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Greek mercenary hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0ce1af06001770ab13",
}
