-- 5fb1b9dce1af060017709565 Later Carthaginian not in Spain or Italy  275 to 203 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba26e1af06001770c7bb']= {
  min=1,
  max=4,
  description='Numidian, Spanish, Poeni or Libyan horsemen',
}
g_troop_entry['5fb1ba26e1af06001770c7bc']= {
  troop_option='5fb1ba26e1af06001770c7bb',
  troopTypeCode='JCV',
}
g_troop_option['5fb1ba26e1af06001770c7bd']= {
  min=2,
  max=4,
  description='Libyan heavy infantry armed with spears',
  core='all',
}
g_troop_entry['5fb1ba26e1af06001770c7be']= {
  troop_option='5fb1ba26e1af06001770c7bd',
  troopTypeCode='HFT',
}
g_troop_option['5fb1ba26e1af06001770c7bf']= {
  min=1,
  max=3,
  description='Libyan, Moorish or Numidian javelinmen',
}
g_troop_entry['5fb1ba26e1af06001770c7c0']= {
  troop_option='5fb1ba26e1af06001770c7bf',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba26e1af06001770c7c1']= {
  min=0,
  max=1,
  description='Bolt-shooters',
}
g_troop_entry['5fb1ba26e1af06001770c7c2']= {
  troop_option='5fb1ba26e1af06001770c7c1',
  troopTypeCode='ART',
}
g_troop_option['5fb1ba26e1af06001770c7c3']= {
  min=0,
  max=2,
  description='Greek mercenary hoplites',
  core='all',
  startDate=-275,
  endDate=-236,
}
g_troop_entry['5fb1ba26e1af06001770c7c5']= {
  troop_option='5fb1ba26e1af06001770c7c3',
  troopTypeCode='HFT',
}
g_troop_option['5fb1ba26e1af06001770c7c7']= {
  min=0,
  max=1,
  description='Greek mercenary thureophoroi',
  core='all',
  startDate=-275,
  endDate=-236,
}
g_troop_entry['5fb1ba26e1af06001770c7c9']= {
  troop_option='5fb1ba26e1af06001770c7c7',
  troopTypeCode='RDR',
}
g_troop_option['5fb1ba26e1af06001770c7ca']= {
  min=0,
  max=2,
  description='Italian mercenary light infantry',
  startDate=-275,
  endDate=-236,
}
g_troop_entry['5fb1ba26e1af06001770c7cc']= {
  troop_option='5fb1ba26e1af06001770c7ca',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba26e1af06001770c7cd']= {
  min=0,
  max=1,
  description='Spanish mercenary light infantry',
}
g_troop_entry['5fb1ba26e1af06001770c7ce']= {
  troop_option='5fb1ba26e1af06001770c7cd',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba26e1af06001770c7cf']= {
  min=0,
  max=1,
  description='Balearic slingers',
}
g_troop_entry['5fb1ba26e1af06001770c7d0']= {
  troop_option='5fb1ba26e1af06001770c7cf',
  troopTypeCode='SKM',
}
g_troop_option['5fb1ba26e1af06001770c7d1']= {
  min=0,
  max=3,
  description='African elephants',
  core='all',
}
g_troop_entry['5fb1ba26e1af06001770c7d2']= {
  troop_option='5fb1ba26e1af06001770c7d1',
  troopTypeCode='ELE',
}
g_troop_option['5fb1ba26e1af06001770c7d3']= {
  min=0,
  max=3,
  description='Celtiberian mercenaries',
  note='only in Africa',
  core='all',
}
g_troop_entry['5fb1ba26e1af06001770c7d4']= {
  troop_option='5fb1ba26e1af06001770c7d3',
  troopTypeCode='RDR',
}
g_troop_option['5fb1ba26e1af06001770c7d5']= {
  min=0,
  max=1,
  description='Gallic noble horsemen',
}
g_troop_entry['5fb1ba26e1af06001770c7d6']= {
  troop_option='5fb1ba26e1af06001770c7d5',
  troopTypeCode='BAD',
}
g_troop_entry['5fb1ba26e1af06001770c7d7']= {
  troop_option='5fb1ba26e1af06001770c7d5',
  troopTypeCode='JCV',
}
g_troop_option['5fb1ba26e1af06001770c7d8']= {
  min=0,
  max=1,
  description='Gallic horsemen',
}
g_troop_entry['5fb1ba26e1af06001770c7d9']= {
  troop_option='5fb1ba26e1af06001770c7d8',
  troopTypeCode='BAD',
}
g_troop_option['5fb1ba26e1af06001770c7da']= {
  min=0,
  max=8,
  description='Gallic tribesmen mercenaries',
  core='all',
}
g_troop_entry['5fb1ba26e1af06001770c7db']= {
  troop_option='5fb1ba26e1af06001770c7da',
  troopTypeCode='WRR',
}
g_troop_option['5fb1ba26e1af06001770c7dc']= {
  min=0,
  max=2,
  description='Ligurian infantry',
  core='all',
}
g_troop_entry['5fb1ba26e1af06001770c7dd']= {
  troop_option='5fb1ba26e1af06001770c7dc',
  troopTypeCode='RDR',
}
g_str_5fb1ba26e1af06001770c7bc_general='5fb1ba26e1af06001770c7bc_general'
g_base_definitions[g_str_5fb1ba26e1af06001770c7bc_general]={
  id=g_str_5fb1ba26e1af06001770c7bc_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Numidian, Spanish, Poeni or Libyan horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba26e1af06001770c7bc='5fb1ba26e1af06001770c7bc'
g_base_definitions[g_str_5fb1ba26e1af06001770c7bc]={
  id=g_str_5fb1ba26e1af06001770c7bc,
  name='Javelin Cavalry',
  min=1,
  max=4,
  description='Numidian, Spanish, Poeni or Libyan horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba26e1af06001770c7be='5fb1ba26e1af06001770c7be'
g_base_definitions[g_str_5fb1ba26e1af06001770c7be]={
  id=g_str_5fb1ba26e1af06001770c7be,
  name='Heavy Foot',
  min=2,
  max=4,
  description='Libyan heavy infantry armed with spears',
  troop_type="Heavy Foot",
}
g_str_5fb1ba26e1af06001770c7c0='5fb1ba26e1af06001770c7c0'
g_base_definitions[g_str_5fb1ba26e1af06001770c7c0]={
  id=g_str_5fb1ba26e1af06001770c7c0,
  name='Light Foot',
  min=1,
  max=3,
  description='Libyan, Moorish or Numidian javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba26e1af06001770c7c2='5fb1ba26e1af06001770c7c2'
g_base_definitions[g_str_5fb1ba26e1af06001770c7c2]={
  id=g_str_5fb1ba26e1af06001770c7c2,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt-shooters',
  troop_type="Artillery",
}
g_str_5fb1ba26e1af06001770c7c5='5fb1ba26e1af06001770c7c5'
g_base_definitions[g_str_5fb1ba26e1af06001770c7c5]={
  id=g_str_5fb1ba26e1af06001770c7c5,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Greek mercenary hoplites',
  troop_type="Heavy Foot",
}
g_str_5fb1ba26e1af06001770c7c9='5fb1ba26e1af06001770c7c9'
g_base_definitions[g_str_5fb1ba26e1af06001770c7c9]={
  id=g_str_5fb1ba26e1af06001770c7c9,
  name='Raiders',
  min=0,
  max=1,
  description='Greek mercenary thureophoroi',
  troop_type="Raiders",
}
g_str_5fb1ba26e1af06001770c7cc='5fb1ba26e1af06001770c7cc'
g_base_definitions[g_str_5fb1ba26e1af06001770c7cc]={
  id=g_str_5fb1ba26e1af06001770c7cc,
  name='Light Foot',
  min=0,
  max=2,
  description='Italian mercenary light infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba26e1af06001770c7ce='5fb1ba26e1af06001770c7ce'
g_base_definitions[g_str_5fb1ba26e1af06001770c7ce]={
  id=g_str_5fb1ba26e1af06001770c7ce,
  name='Light Foot',
  min=0,
  max=1,
  description='Spanish mercenary light infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba26e1af06001770c7d0='5fb1ba26e1af06001770c7d0'
g_base_definitions[g_str_5fb1ba26e1af06001770c7d0]={
  id=g_str_5fb1ba26e1af06001770c7d0,
  name='Skirmishers',
  min=0,
  max=1,
  description='Balearic slingers',
  troop_type="Skirmishers",
}
g_str_5fb1ba26e1af06001770c7d2='5fb1ba26e1af06001770c7d2'
g_base_definitions[g_str_5fb1ba26e1af06001770c7d2]={
  id=g_str_5fb1ba26e1af06001770c7d2,
  name='Elephants',
  min=0,
  max=3,
  description='African elephants',
  troop_type="Elephants",
}
g_str_5fb1ba26e1af06001770c7d4='5fb1ba26e1af06001770c7d4'
g_base_definitions[g_str_5fb1ba26e1af06001770c7d4]={
  id=g_str_5fb1ba26e1af06001770c7d4,
  name='Raiders',
  min=0,
  max=3,
  description='Celtiberian mercenaries',
  troop_type="Raiders",
}
g_str_5fb1ba26e1af06001770c7d6='5fb1ba26e1af06001770c7d6'
g_base_definitions[g_str_5fb1ba26e1af06001770c7d6]={
  id=g_str_5fb1ba26e1af06001770c7d6,
  name='Bad Horse',
  min=0,
  max=1,
  description='Gallic noble horsemen',
  troop_type="Bad Horse",
}
g_str_5fb1ba26e1af06001770c7d7_general='5fb1ba26e1af06001770c7d7_general'
g_base_definitions[g_str_5fb1ba26e1af06001770c7d7_general]={
  id=g_str_5fb1ba26e1af06001770c7d7_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Gallic noble horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba26e1af06001770c7d7='5fb1ba26e1af06001770c7d7'
g_base_definitions[g_str_5fb1ba26e1af06001770c7d7]={
  id=g_str_5fb1ba26e1af06001770c7d7,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Gallic noble horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba26e1af06001770c7d9='5fb1ba26e1af06001770c7d9'
g_base_definitions[g_str_5fb1ba26e1af06001770c7d9]={
  id=g_str_5fb1ba26e1af06001770c7d9,
  name='Bad Horse',
  min=0,
  max=1,
  description='Gallic horsemen',
  troop_type="Bad Horse",
}
g_str_5fb1ba26e1af06001770c7db='5fb1ba26e1af06001770c7db'
g_base_definitions[g_str_5fb1ba26e1af06001770c7db]={
  id=g_str_5fb1ba26e1af06001770c7db,
  name='Warriors',
  min=0,
  max=8,
  description='Gallic tribesmen mercenaries',
  troop_type="Warriors",
}
g_str_5fb1ba26e1af06001770c7dd='5fb1ba26e1af06001770c7dd'
g_base_definitions[g_str_5fb1ba26e1af06001770c7dd]={
  id=g_str_5fb1ba26e1af06001770c7dd,
  name='Raiders',
  min=0,
  max=2,
  description='Ligurian infantry',
  troop_type="Raiders",
}
g_str_5fb1b9dce1af060017709565_camp='5fb1b9dce1af060017709565_camp'
g_base_definitions[g_str_5fb1b9dce1af060017709565_camp]={
  id=g_str_5fb1b9dce1af060017709565_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dce1af060017709565_camp_fortified='5fb1b9dce1af060017709565_camp_fortified'
g_base_definitions[g_str_5fb1b9dce1af060017709565_camp_fortified]={
  id=g_str_5fb1b9dce1af060017709565_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
army['5fb1b9dce1af060017709565']={
  data={
    name='Later Carthaginian not in Spain or Italy  275 to 203 BC',
    id='5fb1b9dce1af060017709565',
    army_id='5fb1b9dce1af060017709565'
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c7bc_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7bc],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7be],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c0],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c2],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c5],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c9],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7cc],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7ce],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d0],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d2],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d4],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d6],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d7_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d7],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d9],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7db],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7dd],
  g_base_definitions[g_str_5fb1b9dce1af060017709565_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709565_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709565"] = army["5fb1b9dce1af060017709565"]
army['5fb1b9dce1af060017709565_-275_-236']={
  data={
    name='Later Carthaginian not in Spain or Italy 275 BC to 236 BC',
    id='5fb1b9dce1af060017709565_-275_-236',
    army_id='5fb1b9dce1af060017709565'
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c7bc_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7bc],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7be],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c0],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c2],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c5],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c9],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7cc],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7ce],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d0],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d2],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d4],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d6],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d7_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d7],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d9],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7db],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7dd],
  g_base_definitions[g_str_5fb1b9dce1af060017709565_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709565_camp_fortified],
}
army['5fb1b9dce1af060017709565_-235_-203']={
  data={
    name='Later Carthaginian not in Spain or Italy 235 BC to 203 BC',
    id='5fb1b9dce1af060017709565_-235_-203',
    army_id='5fb1b9dce1af060017709565'
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c7bc_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7bc],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7be],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c0],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c2],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c5],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7c9],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7cc],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7ce],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d0],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d2],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d4],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d6],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d7_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d7],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7d9],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7db],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7dd],
  g_base_definitions[g_str_5fb1b9dce1af060017709565_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709565_camp_fortified],
}
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Later Carthaginian not in Spain or Italy  275 to 203 BC"] = army["5fb1b9dce1af060017709565"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Later Carthaginian not in Spain or Italy  275 to 203 BC"] = army["5fb1b9dce1af060017709565"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Carthaginian not in Spain or Italy  275 to 203 BC"] = army["5fb1b9dce1af060017709565"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709565"] = {}
army_dates["5fb1b9dce1af060017709565"]["275 BC to 203 BC"] ="5fb1b9dce1af060017709565"
army_dates["5fb1b9dce1af060017709565"]["275 BC to 236 BC"] ="5fb1b9dce1af060017709565_-275_-236"
army_dates["5fb1b9dce1af060017709565"]["235 BC to 203 BC"] ="5fb1b9dce1af060017709565_-235_-203"
