-- 5fb1b9dbe1af060017709478 Kushite Egyptian  745 to 593 BC

army['5fb1b9dbe1af060017709478']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Dry',
      'Delta',
      'Dry',
    },
    name='Kushite Egyptian  745 to 593 BC',
    id='5fb1b9dbe1af060017709478',
    dateRange={
      startDate=-745,
      endDate=-593,
    },
  },
  g_base_definitions[g_str_5fb1ba23e1af06001770c464_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c464],
  g_base_definitions[g_str_5fb1ba23e1af06001770c466],
  g_base_definitions[g_str_5fb1ba23e1af06001770c468],
  g_base_definitions[g_str_5fb1ba23e1af06001770c469],
  g_base_definitions[g_str_5fb1ba23e1af06001770c46b],
  g_base_definitions[g_str_5fb1ba23e1af06001770c46d],
  g_base_definitions[g_str_5fb1b9dbe1af060017709478_camp],
  g_base_definitions[g_str_5fb1b9dbe1af060017709478_camp_pack_train],
  g_base_definitions[g_str_5fb1ba09e1af06001770a76e_general],
  g_base_definitions[g_str_5fb1ba09e1af06001770a76e],
  g_base_definitions[g_str_5fb1ba09e1af06001770a770],
  g_base_definitions[g_str_5fb1ba09e1af06001770a772],
  g_base_definitions[g_str_5fb1ba09e1af06001770a774],
  g_base_definitions[g_str_5fb1ba09e1af06001770a776],
  g_base_definitions[g_str_5fb1ba09e1af06001770a778],
  g_base_definitions[g_str_5fb1ba09e1af06001770a779],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af060017709478"] = army["5fb1b9dbe1af060017709478"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Kushite Egyptian  745 to 593 BC"] = army["5fb1b9dbe1af060017709478"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Kushite Egyptian  745 to 593 BC"] = army["5fb1b9dbe1af060017709478"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af060017709478"] = {}
army_dates["5fb1b9dbe1af060017709478"]["745 BC to 593 BC"] = {
  startDate=-745,
  endDate=-593
}
army_dates["5fb1b9dbe1af060017709478"]["745 BC to 728 BC"] = {
  startDate=-745,
  endDate=-728
}
army_dates["5fb1b9dbe1af060017709478"]["727 BC to 663 BC"] = {
  startDate=-727,
  endDate=-663
}
army_dates["5fb1b9dbe1af060017709478"]["662 BC to 593 BC"] = {
  startDate=-662,
  endDate=-593
}
