troop_options['5fb1ba23e1af06001770c463'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-745,
    endDate=-593,
  }
}
troop_options['5fb1ba23e1af06001770c465'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-745,
    endDate=-593,
  }
}
troop_options['5fb1ba23e1af06001770c467'] = {
  min=3,
  max=8,
  dateRange={
    startDate=-745,
    endDate=-593,
  }
}
troop_options['5fb1ba23e1af06001770c46a'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-745,
    endDate=-593,
  }
}
troop_options['5fb1ba23e1af06001770c46c'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-745,
    endDate=-593,
  }
}
-- allies
