-- 5fb1b9e0e1af0600177097c8 Parthian Subject Provinces  147 BC to 225 AD

army['5fb1b9e0e1af0600177097c8']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Parthian Subject Provinces  147 BC to 225 AD',
    id='5fb1b9e0e1af0600177097c8',
    dateRange={
      startDate=-147,
      endDate=225,
    },
  },
  g_base_definitions[g_str_615351a503385c0016b86179_general],
  g_base_definitions[g_str_615351a503385c0016b86179_general_armored_camelry],
  g_base_definitions[g_str_615351a503385c0016b86179],
  g_base_definitions[g_str_615351a503385c0016b86179_armored_camelry],
  g_base_definitions[g_str_615351a503385c0016b8617c],
  g_base_definitions[g_str_615351a503385c0016b8617e],
  g_base_definitions[g_str_615351a503385c0016b86180],
  g_base_definitions[g_str_615351a503385c0016b86181],
  g_base_definitions[g_str_615351a503385c0016b86183],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097c8_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097c8_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097c8"] = army["5fb1b9e0e1af0600177097c8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Parthian Subject Provinces  147 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c8"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Parthian Subject Provinces  147 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Parthian Subject Provinces  147 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097c8"] = {}
army_dates["5fb1b9e0e1af0600177097c8"]["147 BC to 225 AD"] = {
  startDate=-147,
  endDate=225
}
