troop_options['5fb1ba41e1af06001770f9f3'] = {
  min=1,
  max=3,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770f9f5'] = {
  min=1,
  max=4,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770f9f7'] = {
  min=1,
  max=2,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770f9f9'] = {
  min=0,
  max=2,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770f9fb'] = {
  min=0,
  max=5,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770f9fd'] = {
  min=1,
  max=2,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770fa00'] = {
  min=1,
  max=2,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770fa02'] = {
  min=0,
  max=1,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
troop_options['5fb1ba41e1af06001770fa04'] = {
  min=0,
  max=1,
  dateRange={
    startDate=907,
    endDate=1125,
  }
}
-- allies
