troop_options['5fb1ba39e1af06001770ea73'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1419,
  }
}
troop_options['5fb1ba39e1af06001770ea76'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1320,
    endDate=1419,
  }
}
troop_options['5fb1ba39e1af06001770ea78'] = {
  min=6,
  max=24,
  dateRange={
    startDate=1320,
    endDate=1419,
  }
}
troop_options['5fb1ba39e1af06001770ea7a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1320,
    endDate=1419,
  }
}
troop_options['5fb1ba39e1af06001770ea7d'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1419,
  }
}
troop_options['5fb1ba39e1af06001770ea80'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1419,
  }
}
troop_options['5fb1ba39e1af06001770ea82'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1419,
  }
}
-- allies
