-- 5fb1b9d9e1af0600177093ad Hittite Empire  1380 to 1180 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba20e1af06001770c0f3_general='5fb1ba20e1af06001770c0f3_general'
g_base_definitions[g_str_5fb1ba20e1af06001770c0f3_general]={
  id=g_str_5fb1ba20e1af06001770c0f3_general,
  name='Chariots General',
  min=2,
  max=1,
  description='Chariots with 2 or (after 1340, up to half) 3 crewmen',
  general=true,
  troop_type="Chariots",
}
g_str_5fb1ba20e1af06001770c0f3='5fb1ba20e1af06001770c0f3'
g_base_definitions[g_str_5fb1ba20e1af06001770c0f3]={
  id=g_str_5fb1ba20e1af06001770c0f3,
  name='Chariots',
  min=2,
  max=5,
  description='Chariots with 2 or (after 1340, up to half) 3 crewmen',
  troop_type="Chariots",
}
g_str_5fb1ba20e1af06001770c0f5='5fb1ba20e1af06001770c0f5'
g_base_definitions[g_str_5fb1ba20e1af06001770c0f5]={
  id=g_str_5fb1ba20e1af06001770c0f5,
  name='Light Spear',
  min=4,
  max=8,
  description='Standing or seasonal army spearmen',
  troop_type="Light Spear",
}
g_str_5fb1ba20e1af06001770c0f7='5fb1ba20e1af06001770c0f7'
g_base_definitions[g_str_5fb1ba20e1af06001770c0f7]={
  id=g_str_5fb1ba20e1af06001770c0f7,
  name='Horde',
  min=0,
  max=6,
  description='Conscripts',
  troop_type="Horde",
}
g_str_5fb1ba20e1af06001770c0f9='5fb1ba20e1af06001770c0f9'
g_base_definitions[g_str_5fb1ba20e1af06001770c0f9]={
  id=g_str_5fb1ba20e1af06001770c0f9,
  name='Light Foot',
  min=1,
  max=2,
  description='Anatolian vassal javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba20e1af06001770c0fb='5fb1ba20e1af06001770c0fb'
g_base_definitions[g_str_5fb1ba20e1af06001770c0fb]={
  id=g_str_5fb1ba20e1af06001770c0fb,
  name='Skirmishers',
  min=0,
  max=3,
  description='Anatolian vassal slingers and skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba20e1af06001770c0fd='5fb1ba20e1af06001770c0fd'
g_base_definitions[g_str_5fb1ba20e1af06001770c0fd]={
  id=g_str_5fb1ba20e1af06001770c0fd,
  name='Warband',
  min=0,
  max=2,
  description='Gasgan swordsmen',
  troop_type="Warband",
}
g_str_5fb1ba20e1af06001770c0ff='5fb1ba20e1af06001770c0ff'
g_base_definitions[g_str_5fb1ba20e1af06001770c0ff]={
  id=g_str_5fb1ba20e1af06001770c0ff,
  name='Raiders',
  min=0,
  max=1,
  description='Lukka',
  troop_type="Raiders",
}
g_str_5fb1ba20e1af06001770c102='5fb1ba20e1af06001770c102'
g_base_definitions[g_str_5fb1ba20e1af06001770c102]={
  id=g_str_5fb1ba20e1af06001770c102,
  name='Light Foot',
  min=0,
  max=2,
  description='Shaasu or Sutu Bedouin',
  troop_type="Light Foot",
}
g_str_5fb1ba20e1af06001770c103='5fb1ba20e1af06001770c103'
g_base_definitions[g_str_5fb1ba20e1af06001770c103]={
  id=g_str_5fb1ba20e1af06001770c103,
  name='Rabble',
  min=0,
  max=2,
  description='Shaasu or Sutu Bedouin',
  troop_type="Rabble",
}
g_str_5fb1b9d9e1af0600177093ad_camp='5fb1b9d9e1af0600177093ad_camp'
g_base_definitions[g_str_5fb1b9d9e1af0600177093ad_camp]={
  id=g_str_5fb1b9d9e1af0600177093ad_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d9e1af0600177093ad_camp_pack_train='5fb1b9d9e1af0600177093ad_camp_pack_train'
g_base_definitions[g_str_5fb1b9d9e1af0600177093ad_camp_pack_train]={
  id=g_str_5fb1b9d9e1af0600177093ad_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9d9e1af0600177093ad']={
  data={
    name='Hittite Empire  1380 to 1180 BC'
  },
  g_base_definitions[g_str_5fb1ba20e1af06001770c0f3_general],
  g_base_definitions[g_str_5fb1ba20e1af06001770c0f3],
  g_base_definitions[g_str_5fb1ba20e1af06001770c0f5],
  g_base_definitions[g_str_5fb1ba20e1af06001770c0f7],
  g_base_definitions[g_str_5fb1ba20e1af06001770c0f9],
  g_base_definitions[g_str_5fb1ba20e1af06001770c0fb],
  g_base_definitions[g_str_5fb1ba20e1af06001770c0fd],
  g_base_definitions[g_str_5fb1ba20e1af06001770c0ff],
  g_base_definitions[g_str_5fb1ba20e1af06001770c102],
  g_base_definitions[g_str_5fb1ba20e1af06001770c103],
  g_base_definitions[g_str_5fb1b9d9e1af0600177093ad_camp],
  g_base_definitions[g_str_5fb1b9d9e1af0600177093ad_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af0600177093ad"] = army["5fb1b9d9e1af0600177093ad"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Hittite Empire  1380 to 1180 BC"] = army["5fb1b9d9e1af0600177093ad"]
