g_str_5fb1ba3ee1af06001770f4e2_general='5fb1ba3ee1af06001770f4e2_general'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4e2_general]={
  id=g_str_5fb1ba3ee1af06001770f4e2_general,
  name='Warriors General',
  min=5,
  max=1,
  description='Red Ti fierce fighters',
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba3ee1af06001770f4e1",
}
g_str_5fb1ba3ee1af06001770f4e2='5fb1ba3ee1af06001770f4e2'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4e2]={
  id=g_str_5fb1ba3ee1af06001770f4e2,
  name='Warriors',
  min=5,
  max=8,
  description='Red Ti fierce fighters',
  troop_type="Warriors",
  troop_option_id="5fb1ba3ee1af06001770f4e1",
}
g_str_5fb1ba3ee1af06001770f4e4='5fb1ba3ee1af06001770f4e4'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4e4]={
  id=g_str_5fb1ba3ee1af06001770f4e4,
  name='Horde',
  min=8,
  max=12,
  description='Subjugated clan fighters',
  troop_type="Horde",
  troop_option_id="5fb1ba3ee1af06001770f4e3",
}
g_str_5fb1ba3ee1af06001770f4e6='5fb1ba3ee1af06001770f4e6'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4e6]={
  id=g_str_5fb1ba3ee1af06001770f4e6,
  name='Skirmishers',
  min=2,
  max=4,
  description='Skirmishing bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3ee1af06001770f4e5",
}
g_str_5fb1ba3ee1af06001770f4e8='5fb1ba3ee1af06001770f4e8'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4e8]={
  id=g_str_5fb1ba3ee1af06001770f4e8,
  name='Horde',
  min=0,
  max=2,
  description='Levies, families, ill-equipped tribesmen and the like',
  troop_type="Horde",
  troop_option_id="5fb1ba3ee1af06001770f4e7",
}
g_str_5fb1b9f0e1af06001770a135_camp='5fb1b9f0e1af06001770a135_camp'
g_base_definitions[g_str_5fb1b9f0e1af06001770a135_camp]={
  id=g_str_5fb1b9f0e1af06001770a135_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
