-- 5fb1b9dfe1af06001770973d Mithradatic  110 to 47 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba29e1af06001770cf18='5fb1ba29e1af06001770cf18'
g_base_definitions[g_str_5fb1ba29e1af06001770cf18]={
  id=g_str_5fb1ba29e1af06001770cf18,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Heavy horsemen with armored horses',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba29e1af06001770cf17",
}
g_str_5fb1ba29e1af06001770cf1a_general='5fb1ba29e1af06001770cf1a_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cf1a_general]={
  id=g_str_5fb1ba29e1af06001770cf1a_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen and light horsemen armed with javelins',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cf19",
}
g_str_5fb1ba29e1af06001770cf1a='5fb1ba29e1af06001770cf1a'
g_base_definitions[g_str_5fb1ba29e1af06001770cf1a]={
  id=g_str_5fb1ba29e1af06001770cf1a,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Horsemen and light horsemen armed with javelins',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cf19",
}
g_str_5fb1ba29e1af06001770cf1c='5fb1ba29e1af06001770cf1c'
g_base_definitions[g_str_5fb1ba29e1af06001770cf1c]={
  id=g_str_5fb1ba29e1af06001770cf1c,
  name='Horse Bow',
  min=0,
  max=1,
  description='Skythian horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba29e1af06001770cf1b",
}
g_str_5fb1ba29e1af06001770cf1e='5fb1ba29e1af06001770cf1e'
g_base_definitions[g_str_5fb1ba29e1af06001770cf1e]={
  id=g_str_5fb1ba29e1af06001770cf1e,
  name='Knights',
  min=0,
  max=1,
  description='Iazygian or Bosporan nobles',
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cf1d",
}
g_str_5fb1ba29e1af06001770cf20='5fb1ba29e1af06001770cf20'
g_base_definitions[g_str_5fb1ba29e1af06001770cf20]={
  id=g_str_5fb1ba29e1af06001770cf20,
  name='Raiders',
  min=1,
  max=2,
  description='Thureophoroi',
  troop_type="Raiders",
  troop_option_id="5fb1ba29e1af06001770cf1f",
}
g_str_5fb1ba29e1af06001770cf22='5fb1ba29e1af06001770cf22'
g_base_definitions[g_str_5fb1ba29e1af06001770cf22]={
  id=g_str_5fb1ba29e1af06001770cf22,
  name='Light Foot',
  min=1,
  max=5,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cf21",
}
g_str_5fb1ba29e1af06001770cf25='5fb1ba29e1af06001770cf25'
g_base_definitions[g_str_5fb1ba29e1af06001770cf25]={
  id=g_str_5fb1ba29e1af06001770cf25,
  name='Pikes',
  min=4,
  max=6,
  description='Phalanx',
  troop_type="Pikes",
  troop_option_id="5fb1ba29e1af06001770cf23",
}
g_str_5fb1ba29e1af06001770cf28='5fb1ba29e1af06001770cf28'
g_base_definitions[g_str_5fb1ba29e1af06001770cf28]={
  id=g_str_5fb1ba29e1af06001770cf28,
  name='Light Spear',
  min=0,
  max=1,
  description='Chalybes',
  troop_type="Light Spear",
  troop_option_id="5fb1ba29e1af06001770cf26",
}
g_str_5fb1ba29e1af06001770cf2b='5fb1ba29e1af06001770cf2b'
g_base_definitions[g_str_5fb1ba29e1af06001770cf2b]={
  id=g_str_5fb1ba29e1af06001770cf2b,
  name='Elite Foot',
  min=2,
  max=4,
  description='Imitation legionaries',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba29e1af06001770cf29",
}
g_str_5fb1ba29e1af06001770cf2d='5fb1ba29e1af06001770cf2d'
g_base_definitions[g_str_5fb1ba29e1af06001770cf2d]={
  id=g_str_5fb1ba29e1af06001770cf2d,
  name='Bow Levy',
  min=1,
  max=2,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba29e1af06001770cf2c",
}
g_str_5fb1ba29e1af06001770cf2f='5fb1ba29e1af06001770cf2f'
g_base_definitions[g_str_5fb1ba29e1af06001770cf2f]={
  id=g_str_5fb1ba29e1af06001770cf2f,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba29e1af06001770cf2e",
}
g_str_5fb1ba29e1af06001770cf31='5fb1ba29e1af06001770cf31'
g_base_definitions[g_str_5fb1ba29e1af06001770cf31]={
  id=g_str_5fb1ba29e1af06001770cf31,
  name='Light Foot',
  min=0,
  max=1,
  description='Thracian light infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cf30",
}
g_str_5fb1ba29e1af06001770cf33='5fb1ba29e1af06001770cf33'
g_base_definitions[g_str_5fb1ba29e1af06001770cf33]={
  id=g_str_5fb1ba29e1af06001770cf33,
  name='Warriors',
  min=0,
  max=2,
  description='Galatian mercenary foot',
  troop_type="Warriors",
  troop_option_id="5fb1ba29e1af06001770cf32",
}
g_str_5fb1ba29e1af06001770cf35='5fb1ba29e1af06001770cf35'
g_base_definitions[g_str_5fb1ba29e1af06001770cf35]={
  id=g_str_5fb1ba29e1af06001770cf35,
  name='Raiders',
  min=0,
  max=1,
  description='Bastarnae infantry',
  troop_type="Raiders",
  troop_option_id="5fb1ba29e1af06001770cf34",
}
g_str_5fb1b9dfe1af06001770973d_camp='5fb1b9dfe1af06001770973d_camp'
g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp]={
  id=g_str_5fb1b9dfe1af06001770973d_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af06001770973d_camp_fortified='5fb1b9dfe1af06001770973d_camp_fortified'
g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp_fortified]={
  id=g_str_5fb1b9dfe1af06001770973d_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9dfe1af06001770973d']={
  data={
    name='Mithradatic  110 to 47 BC',
    id='5fb1b9dfe1af06001770973d'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cf18],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1a_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1e],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf20],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf22],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf25],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf28],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2b],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2d],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf31],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf33],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf35],
  g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770973d"] = army["5fb1b9dfe1af06001770973d"]
army['5fb1b9dfe1af06001770973d_-110_-85']={
  data={
    name='Mithradatic 110 BC to 85 BC',
    id='5fb1b9dfe1af06001770973d_-110_-85'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cf18],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1a_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1e],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf20],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf22],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf25],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2d],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf31],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf33],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf35],
  g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp_fortified],
}
army['5fb1b9dfe1af06001770973d_-84_-47']={
  data={
    name='Mithradatic 84 BC to 47 BC',
    id='5fb1b9dfe1af06001770973d_-84_-47'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cf18],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1a_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf1e],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf20],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf22],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf28],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2b],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2d],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf2f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf31],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf33],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf35],
  g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770973d_camp_fortified],
}
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Mithradatic  110 to 47 BC"] = army["5fb1b9dfe1af06001770973d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Mithradatic  110 to 47 BC"] = army["5fb1b9dfe1af06001770973d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mithradatic  110 to 47 BC"] = army["5fb1b9dfe1af06001770973d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af06001770973d"] = {}
army_dates["5fb1b9dfe1af06001770973d"]["110 BC to 47 BC"] ="5fb1b9dfe1af06001770973d"
army_dates["5fb1b9dfe1af06001770973d"]["110 BC to 85 BC"] ="5fb1b9dfe1af06001770973d_-110_-85"
army_dates["5fb1b9dfe1af06001770973d"]["84 BC to 47 BC"] ="5fb1b9dfe1af06001770973d_-84_-47"
