-- 5fb1b9e7e1af060017709c2d Navarrese Company in Greece  1377 to 1430 AD

army['5fb1b9e7e1af060017709c2d']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Navarrese Company in Greece  1377 to 1430 AD',
    id='5fb1b9e7e1af060017709c2d',
    dateRange={
      startDate=1377,
      endDate=1430,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770dff0_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff0],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff5],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff7_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff7],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff9],
  g_base_definitions[g_str_5fb1ba33e1af06001770dffb],
  g_base_definitions[g_str_5fb1ba33e1af06001770dffd],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfff],
  g_base_definitions[g_str_5fb1ba33e1af06001770e001],
  g_base_definitions[g_str_5fb1ba33e1af06001770e003],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c2d_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c2d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c2d"] = army["5fb1b9e7e1af060017709c2d"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Navarrese Company in Greece  1377 to 1430 AD"] = army["5fb1b9e7e1af060017709c2d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Navarrese Company in Greece  1377 to 1430 AD"] = army["5fb1b9e7e1af060017709c2d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c2d"] = {}
army_dates["5fb1b9e7e1af060017709c2d"]["1377 AD to 1430 AD"] = {
  startDate=1377,
  endDate=1430
}
army_dates["5fb1b9e7e1af060017709c2d"]["1377 AD to 1389 AD"] = {
  startDate=1377,
  endDate=1389
}
army_dates["5fb1b9e7e1af060017709c2d"]["1390 AD to 1393 AD"] = {
  startDate=1390,
  endDate=1393
}
army_dates["5fb1b9e7e1af060017709c2d"]["1394 AD to 1395 AD"] = {
  startDate=1394,
  endDate=1395
}
army_dates["5fb1b9e7e1af060017709c2d"]["1396 AD to 1430 AD"] = {
  startDate=1396,
  endDate=1430
}
