troop_options['5fb1ba33e1af06001770dfd2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1234,
    endDate=1378,
  }
}
troop_options['5fb1ba33e1af06001770dfd4'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1328,
    endDate=1378,
  }
}
troop_options['5fb1ba33e1af06001770dfd7'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1350,
    endDate=1378,
  }
}
troop_options['5fb1ba33e1af06001770dfdb'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1350,
    endDate=1378,
  }
}
troop_options['5fb1ba33e1af06001770dfde'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1350,
    endDate=1378,
  }
}
troop_options['5fb1ba33e1af06001770dfe2'] = {
  min=4,
  max=12,
  dateRange={
    startDate=1234,
    endDate=1378,
  }
}
troop_options['5fb1ba33e1af06001770dfe4'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1234,
    endDate=1378,
  }
}
troop_options['5fb1ba33e1af06001770dfe6'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1234,
    endDate=1378,
  }
}
-- allies
