-- 5fb1b9ede1af060017709f4e Qaramita  897 to 1078 AD

army['5fb1b9ede1af060017709f4e']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Qaramita  897 to 1078 AD',
    id='5fb1b9ede1af060017709f4e',
    dateRange={
      startDate=897,
      endDate=1078,
    },
  },
  g_base_definitions[g_str_615351b003385c0016b87dba_general],
  g_base_definitions[g_str_615351b003385c0016b87dba],
  g_base_definitions[g_str_615351b003385c0016b87dbc],
  g_base_definitions[g_str_615351b003385c0016b87dbc_mounted_mobile_infantry],
  g_base_definitions[g_str_615351b003385c0016b87dbc_dismounted_mobile_infantry],
  g_base_definitions[g_str_615351b003385c0016b87dbf],
  g_base_definitions[g_str_615351b003385c0016b87dbf_mounted_mobile_infantry],
  g_base_definitions[g_str_615351b003385c0016b87dbf_dismounted_mobile_infantry],
  g_base_definitions[g_str_615351b003385c0016b87dc2_general],
  g_base_definitions[g_str_615351b003385c0016b87dc2],
  g_base_definitions[g_str_615351b003385c0016b87dc4],
  g_base_definitions[g_str_615351b003385c0016b87dc6],
  g_base_definitions[g_str_615351b003385c0016b87dc6_light_camelry],
  g_base_definitions[g_str_615351b003385c0016b87dc9],
  g_base_definitions[g_str_5fb1b9ede1af060017709f4e_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f4e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f4e"] = army["5fb1b9ede1af060017709f4e"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Qaramita  897 to 1078 AD"] = army["5fb1b9ede1af060017709f4e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Qaramita  897 to 1078 AD"] = army["5fb1b9ede1af060017709f4e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f4e"] = {}
army_dates["5fb1b9ede1af060017709f4e"]["897 AD to 1078 AD"] = {
  startDate=897,
  endDate=1078
}
