-- 5fb1b9e4e1af060017709a59 Duke William's Norman Invasion  1066 to 1066 AD

army['5fb1b9e4e1af060017709a59']={
  data={
    invasionRatings={
      {
        value=3,
        note='',
      },
    },
    name='Duke William\'s Norman Invasion  1066 to 1066 AD',
    id='5fb1b9e4e1af060017709a59',
    dateRange={
      startDate=1066,
      endDate=1066,
    }
  },
  g_base_definitions[g_str_5fb1ba2fe1af06001770d99d_general],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d99d_general_mounted],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d99d_general_dismounted],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d99d],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d99d_mounted],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d99d_dismounted],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9a0],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9a2_general],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9a2],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9a3],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9a5],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9a7],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9a9],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9ab],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9ad],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d9af],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a59_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a59"] = army["5fb1b9e4e1af060017709a59"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Duke William\'s Norman Invasion  1066 to 1066 AD"] = army["5fb1b9e4e1af060017709a59"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Duke William\'s Norman Invasion  1066 to 1066 AD"] = army["5fb1b9e4e1af060017709a59"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a59"] = {}
army_dates["5fb1b9e4e1af060017709a59"]["1066 AD"] = {
  startDate=1066,
  endDate=1066
}
