-- 5fb1b9ece1af060017709efc Khawarij Rebellions  658 to 873 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba39e1af06001770ebbf='5fb1ba39e1af06001770ebbf'
g_base_definitions[g_str_5fb1ba39e1af06001770ebbf]={
  id=g_str_5fb1ba39e1af06001770ebbf,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770ebbe",
}
g_str_5fb1ba39e1af06001770ebbf_light_camelry='5fb1ba39e1af06001770ebbf_light_camelry'
g_base_definitions[g_str_5fb1ba39e1af06001770ebbf_light_camelry]={
  id=g_str_5fb1ba39e1af06001770ebbf_light_camelry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770ebbe",
}
g_str_5fb1ba39e1af06001770ebc2_general='5fb1ba39e1af06001770ebc2_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_general]={
  id=g_str_5fb1ba39e1af06001770ebc2_general,
  name='Knights General',
  min=3,
  max=1,
  description='Khwarij Jund horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba39e1af06001770ebc1",
}
g_str_5fb1ba39e1af06001770ebc2_general_dismounted='5fb1ba39e1af06001770ebc2_general_dismounted'
g_str_5fb1ba39e1af06001770ebc2_general_mounted='5fb1ba39e1af06001770ebc2_general_mounted'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_general_dismounted]={
  id=g_str_5fb1ba39e1af06001770ebc2_general_dismounted,
  name='Spears General',
  min=3,
  max=1,
  description='Khwarij Jund horsemen\nDeployment dismounted from Knights General',
  points=4,
  dismounted_from=g_str_5fb1ba39e1af06001770ebc2_general_mounted,
  general=true,
  troop_type="Spears",
  troop_option_id="5fb1ba39e1af06001770ebc1",
}
g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_general_mounted]={
  id=g_str_5fb1ba39e1af06001770ebc2_general_mounted,
  name='Knights General',
  min=3,
  max=1,
  description='Khwarij Jund horsemen\nDeployment dismounting as Spears',
  points=4,
  dismount_as=g_str_5fb1ba39e1af06001770ebc2_general_dismounted,
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba39e1af06001770ebc1",
}
g_str_5fb1ba39e1af06001770ebc2='5fb1ba39e1af06001770ebc2'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc2]={
  id=g_str_5fb1ba39e1af06001770ebc2,
  name='Knights',
  min=3,
  max=6,
  description='Khwarij Jund horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba39e1af06001770ebc1",
}
g_str_5fb1ba39e1af06001770ebc2_dismounted='5fb1ba39e1af06001770ebc2_dismounted'
g_str_5fb1ba39e1af06001770ebc2_mounted='5fb1ba39e1af06001770ebc2_mounted'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_dismounted]={
  id=g_str_5fb1ba39e1af06001770ebc2_dismounted,
  name='Spears',
  min=3,
  max=6,
  description='Khwarij Jund horsemen\nDeployment dismounted from Knights',
  points=4,
  dismounted_from=g_str_5fb1ba39e1af06001770ebc2_mounted,
  troop_type="Spears",
  troop_option_id="5fb1ba39e1af06001770ebc1",
}
g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_mounted]={
  id=g_str_5fb1ba39e1af06001770ebc2_mounted,
  name='Knights',
  min=3,
  max=6,
  description='Khwarij Jund horsemen\nDeployment dismounting as Spears',
  points=4,
  dismount_as=g_str_5fb1ba39e1af06001770ebc2_dismounted,
  troop_type="Knights",
  troop_option_id="5fb1ba39e1af06001770ebc1",
}
g_str_5fb1ba39e1af06001770ebc5='5fb1ba39e1af06001770ebc5'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc5]={
  id=g_str_5fb1ba39e1af06001770ebc5,
  name='Warband',
  min=5,
  max=10,
  description='Khawarij swordsmen',
  troop_type="Warband",
  troop_option_id="5fb1ba39e1af06001770ebc4",
}
g_str_5fb1ba39e1af06001770ebc5_dismounted_mobile_infantry='5fb1ba39e1af06001770ebc5_dismounted_mobile_infantry'
g_str_5fb1ba39e1af06001770ebc5_mounted_mobile_infantry='5fb1ba39e1af06001770ebc5_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc5_dismounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebc5_dismounted_mobile_infantry,
  name='Warband',
  min=5,
  max=10,
  description='Khawarij swordsmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba39e1af06001770ebc5_mounted_mobile_infantry,
  troop_type="Warband",
  troop_option_id="5fb1ba39e1af06001770ebc4",
}
g_base_definitions[g_str_5fb1ba39e1af06001770ebc5_mounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebc5_mounted_mobile_infantry,
  name='Warband',
  min=5,
  max=10,
  description='Khawarij swordsmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba39e1af06001770ebc5_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Warband",
  troop_option_id="5fb1ba39e1af06001770ebc4",
}
g_str_5fb1ba39e1af06001770ebc8='5fb1ba39e1af06001770ebc8'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc8]={
  id=g_str_5fb1ba39e1af06001770ebc8,
  name='Archers',
  min=1,
  max=2,
  description='Muslim bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba39e1af06001770ebc7",
}
g_str_5fb1ba39e1af06001770ebc8_dismounted_mobile_infantry='5fb1ba39e1af06001770ebc8_dismounted_mobile_infantry'
g_str_5fb1ba39e1af06001770ebc8_mounted_mobile_infantry='5fb1ba39e1af06001770ebc8_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba39e1af06001770ebc8_dismounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebc8_dismounted_mobile_infantry,
  name='Archers',
  min=1,
  max=2,
  description='Muslim bowmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba39e1af06001770ebc8_mounted_mobile_infantry,
  troop_type="Archers",
  troop_option_id="5fb1ba39e1af06001770ebc7",
}
g_base_definitions[g_str_5fb1ba39e1af06001770ebc8_mounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebc8_mounted_mobile_infantry,
  name='Archers',
  min=1,
  max=2,
  description='Muslim bowmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba39e1af06001770ebc8_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Archers",
  troop_option_id="5fb1ba39e1af06001770ebc7",
}
g_str_5fb1ba39e1af06001770ebcb='5fb1ba39e1af06001770ebcb'
g_base_definitions[g_str_5fb1ba39e1af06001770ebcb]={
  id=g_str_5fb1ba39e1af06001770ebcb,
  name='Light Foot',
  min=0,
  max=2,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba39e1af06001770ebca",
}
g_str_5fb1ba39e1af06001770ebcb_dismounted_mobile_infantry='5fb1ba39e1af06001770ebcb_dismounted_mobile_infantry'
g_str_5fb1ba39e1af06001770ebcb_mounted_mobile_infantry='5fb1ba39e1af06001770ebcb_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba39e1af06001770ebcb_dismounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebcb_dismounted_mobile_infantry,
  name='Light Foot',
  min=0,
  max=2,
  description='Javelinmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba39e1af06001770ebcb_mounted_mobile_infantry,
  troop_type="Light Foot",
  troop_option_id="5fb1ba39e1af06001770ebca",
}
g_base_definitions[g_str_5fb1ba39e1af06001770ebcb_mounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebcb_mounted_mobile_infantry,
  name='Light Foot',
  min=0,
  max=2,
  description='Javelinmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba39e1af06001770ebcb_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba39e1af06001770ebca",
}
g_str_5fb1ba39e1af06001770ebce='5fb1ba39e1af06001770ebce'
g_base_definitions[g_str_5fb1ba39e1af06001770ebce]={
  id=g_str_5fb1ba39e1af06001770ebce,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba39e1af06001770ebcd",
}
g_str_5fb1ba39e1af06001770ebce_dismounted_mobile_infantry='5fb1ba39e1af06001770ebce_dismounted_mobile_infantry'
g_str_5fb1ba39e1af06001770ebce_mounted_mobile_infantry='5fb1ba39e1af06001770ebce_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba39e1af06001770ebce_dismounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebce_dismounted_mobile_infantry,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba39e1af06001770ebce_mounted_mobile_infantry,
  troop_type="Skirmishers",
  troop_option_id="5fb1ba39e1af06001770ebcd",
}
g_base_definitions[g_str_5fb1ba39e1af06001770ebce_mounted_mobile_infantry]={
  id=g_str_5fb1ba39e1af06001770ebce_mounted_mobile_infantry,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba39e1af06001770ebce_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Skirmishers",
  troop_option_id="5fb1ba39e1af06001770ebcd",
}
g_str_5fb1b9ece1af060017709efc_camp='5fb1b9ece1af060017709efc_camp'
g_base_definitions[g_str_5fb1b9ece1af060017709efc_camp]={
  id=g_str_5fb1b9ece1af060017709efc_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709efc_camp_pack_train='5fb1b9ece1af060017709efc_camp_pack_train'
g_base_definitions[g_str_5fb1b9ece1af060017709efc_camp_pack_train]={
  id=g_str_5fb1b9ece1af060017709efc_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9ece1af060017709efc']={
  data={
    name='Khawarij Rebellions  658 to 873 AD'
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770ebbf],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebbf_light_camelry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_general_mounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_general_dismounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc2],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_mounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc2_dismounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc5],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc5_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc5_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc8],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc8_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebc8_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebcb],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebcb_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebcb_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebce],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebce_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebce_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ece1af060017709efc_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709efc_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709efc"] = army["5fb1b9ece1af060017709efc"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Khawarij Rebellions  658 to 873 AD"] = army["5fb1b9ece1af060017709efc"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Khawarij Rebellions  658 to 873 AD"] = army["5fb1b9ece1af060017709efc"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Khawarij Rebellions  658 to 873 AD"] = army["5fb1b9ece1af060017709efc"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709efc"] = {}
army_dates["5fb1b9ece1af060017709efc"]["658 AD to 873 AD"] ="5fb1b9ece1af060017709efc"
