-- 5fb1b9ebe1af060017709ead Early Venetians in Cyprus  1320 to 1419 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba39e1af06001770ea74_general='5fb1ba39e1af06001770ea74_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ea74_general]={
  id=g_str_5fb1ba39e1af06001770ea74_general,
  name='Knights General',
  min=0,
  max=1,
  description='Venetian elmeti',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba39e1af06001770ea74_general_dismounted='5fb1ba39e1af06001770ea74_general_dismounted'
g_base_definitions[g_str_5fb1ba39e1af06001770ea74_general_dismounted]={
  id=g_str_5fb1ba39e1af06001770ea74_general_dismounted,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Venetian elmeti\nDeployment dismounted from Knights General',
  points=4,
  general=true,
  troop_type="Elite Foot",
}
g_5fb1ba39e1af06001770ea74_general_dismounted=g_base_definitions[g_str_5fb1ba39e1af06001770ea74_general_dismounted]
g_str_5fb1ba39e1af06001770ea74_general_mounted='5fb1ba39e1af06001770ea74_general_mounted'
g_base_definitions[g_str_5fb1ba39e1af06001770ea74_general_mounted]={
  id=g_str_5fb1ba39e1af06001770ea74_general_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='Venetian elmeti\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba39e1af06001770ea74_general_dismounted,
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba39e1af06001770ea74='5fb1ba39e1af06001770ea74'
g_base_definitions[g_str_5fb1ba39e1af06001770ea74]={
  id=g_str_5fb1ba39e1af06001770ea74,
  name='Knights',
  min=0,
  max=1,
  description='Venetian elmeti',
  troop_type="Knights",
}
g_str_5fb1ba39e1af06001770ea74_dismounted='5fb1ba39e1af06001770ea74_dismounted'
g_base_definitions[g_str_5fb1ba39e1af06001770ea74_dismounted]={
  id=g_str_5fb1ba39e1af06001770ea74_dismounted,
  name='Elite Foot',
  min=0,
  max=1,
  description='Venetian elmeti\nDeployment dismounted from Knights',
  points=4,
  troop_type="Elite Foot",
}
g_5fb1ba39e1af06001770ea74_dismounted=g_base_definitions[g_str_5fb1ba39e1af06001770ea74_dismounted]
g_str_5fb1ba39e1af06001770ea74_mounted='5fb1ba39e1af06001770ea74_mounted'
g_base_definitions[g_str_5fb1ba39e1af06001770ea74_mounted]={
  id=g_str_5fb1ba39e1af06001770ea74_mounted,
  name='Knights',
  min=0,
  max=1,
  description='Venetian elmeti\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba39e1af06001770ea74_dismounted,
  troop_type="Knights",
}
g_str_5fb1ba39e1af06001770ea77_general='5fb1ba39e1af06001770ea77_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ea77_general]={
  id=g_str_5fb1ba39e1af06001770ea77_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Mounted crossbowmen',
  general=true,
  troop_type="Bad Horse",
}
g_str_5fb1ba39e1af06001770ea77='5fb1ba39e1af06001770ea77'
g_base_definitions[g_str_5fb1ba39e1af06001770ea77]={
  id=g_str_5fb1ba39e1af06001770ea77,
  name='Bad Horse',
  min=0,
  max=2,
  description='Mounted crossbowmen',
  troop_type="Bad Horse",
}
g_str_5fb1ba39e1af06001770ea79_general='5fb1ba39e1af06001770ea79_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ea79_general]={
  id=g_str_5fb1ba39e1af06001770ea79_general,
  name='Bow Levy General',
  min=6,
  max=1,
  description='Militia crossbowmen',
  general=true,
  troop_type="Bow Levy",
}
g_str_5fb1ba39e1af06001770ea79='5fb1ba39e1af06001770ea79'
g_base_definitions[g_str_5fb1ba39e1af06001770ea79]={
  id=g_str_5fb1ba39e1af06001770ea79,
  name='Bow Levy',
  min=6,
  max=24,
  description='Militia crossbowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba39e1af06001770ea7b_general='5fb1ba39e1af06001770ea7b_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7b_general]={
  id=g_str_5fb1ba39e1af06001770ea7b_general,
  name='Archers General',
  min=0,
  max=1,
  description='Mercenary crossbowmen',
  general=true,
  troop_type="Archers",
}
g_str_5fb1ba39e1af06001770ea7b='5fb1ba39e1af06001770ea7b'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7b]={
  id=g_str_5fb1ba39e1af06001770ea7b,
  name='Archers',
  min=0,
  max=2,
  description='Mercenary crossbowmen',
  troop_type="Archers",
}
g_str_5fb1ba39e1af06001770ea7c_general='5fb1ba39e1af06001770ea7c_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7c_general]={
  id=g_str_5fb1ba39e1af06001770ea7c_general,
  name='Pavisiers General',
  min=0,
  max=1,
  description='Mercenary crossbowmen',
  general=true,
  troop_type="Pavisiers",
}
g_str_5fb1ba39e1af06001770ea7c='5fb1ba39e1af06001770ea7c'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7c]={
  id=g_str_5fb1ba39e1af06001770ea7c,
  name='Pavisiers',
  min=0,
  max=2,
  description='Mercenary crossbowmen',
  troop_type="Pavisiers",
}
g_str_5fb1ba39e1af06001770ea7e_general='5fb1ba39e1af06001770ea7e_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7e_general]={
  id=g_str_5fb1ba39e1af06001770ea7e_general,
  name='Light Foot General',
  min=0,
  max=1,
  description='Javelinmen or swordsmen',
  general=true,
  troop_type="Light Foot",
}
g_str_5fb1ba39e1af06001770ea7e='5fb1ba39e1af06001770ea7e'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7e]={
  id=g_str_5fb1ba39e1af06001770ea7e,
  name='Light Foot',
  min=0,
  max=1,
  description='Javelinmen or swordsmen',
  troop_type="Light Foot",
}
g_str_5fb1ba39e1af06001770ea7f_general='5fb1ba39e1af06001770ea7f_general'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7f_general]={
  id=g_str_5fb1ba39e1af06001770ea7f_general,
  name='Heavy Foot General',
  min=0,
  max=1,
  description='Javelinmen or swordsmen',
  general=true,
  troop_type="Heavy Foot",
}
g_str_5fb1ba39e1af06001770ea7f='5fb1ba39e1af06001770ea7f'
g_base_definitions[g_str_5fb1ba39e1af06001770ea7f]={
  id=g_str_5fb1ba39e1af06001770ea7f,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Javelinmen or swordsmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba39e1af06001770ea81='5fb1ba39e1af06001770ea81'
g_base_definitions[g_str_5fb1ba39e1af06001770ea81]={
  id=g_str_5fb1ba39e1af06001770ea81,
  name='Horde',
  min=0,
  max=1,
  description='Pioneers or armed peasants',
  troop_type="Horde",
}
g_str_5fb1ba39e1af06001770ea83='5fb1ba39e1af06001770ea83'
g_base_definitions[g_str_5fb1ba39e1af06001770ea83]={
  id=g_str_5fb1ba39e1af06001770ea83,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards and other guns',
  troop_type="Artillery",
}
g_str_5fb1b9ebe1af060017709ead_camp='5fb1b9ebe1af060017709ead_camp'
g_base_definitions[g_str_5fb1b9ebe1af060017709ead_camp]={
  id=g_str_5fb1b9ebe1af060017709ead_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ebe1af060017709ead_camp_fortified='5fb1b9ebe1af060017709ead_camp_fortified'
g_base_definitions[g_str_5fb1b9ebe1af060017709ead_camp_fortified]={
  id=g_str_5fb1b9ebe1af060017709ead_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9ebe1af060017709ead']={
  data={
    name='Early Venetians in Cyprus  1320 to 1419 AD'
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770ea74_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea74_general_mounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea74_general_dismounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea74],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea74_mounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea74_dismounted],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea77_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea77],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea79_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea79],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7b_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7b],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7c_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7c],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7e_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7e],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7f_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea7f],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea81],
  g_base_definitions[g_str_5fb1ba39e1af06001770ea83],
  g_base_definitions[g_str_5fb1b9ebe1af060017709ead_camp],
  g_base_definitions[g_str_5fb1b9ebe1af060017709ead_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ebe1af060017709ead"] = army["5fb1b9ebe1af060017709ead"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Early Venetians in Cyprus  1320 to 1419 AD"] = army["5fb1b9ebe1af060017709ead"]
