-- 5fb1b9e7e1af060017709bee Early Feudal Spanish  718 to 1200 AD

army['5fb1b9e7e1af060017709bee']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Early Feudal Spanish  718 to 1200 AD',
    id='5fb1b9e7e1af060017709bee',
    dateRange={
      startDate=718,
      endDate=1200,
    }
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770df00_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770df00],
  g_base_definitions[g_str_5fb1ba32e1af06001770df03],
  g_base_definitions[g_str_5fb1ba32e1af06001770df05],
  g_base_definitions[g_str_5fb1ba32e1af06001770df08],
  g_base_definitions[g_str_5fb1ba32e1af06001770df0a_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770df0a],
  g_base_definitions[g_str_5fb1ba32e1af06001770df0c],
  g_base_definitions[g_str_5fb1ba32e1af06001770df0f],
  g_base_definitions[g_str_5fb1ba32e1af06001770df11],
  g_base_definitions[g_str_5fb1ba32e1af06001770df15],
  g_base_definitions[g_str_5fb1ba32e1af06001770df18],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bee_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bee_camp_pack_train],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bee_camp_standard_wagon],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709bee"] = army["5fb1b9e7e1af060017709bee"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Feudal Spanish  718 to 1200 AD"] = army["5fb1b9e7e1af060017709bee"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Early Feudal Spanish  718 to 1200 AD"] = army["5fb1b9e7e1af060017709bee"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Feudal Spanish  718 to 1200 AD"] = army["5fb1b9e7e1af060017709bee"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709bee"] = {}
army_dates["5fb1b9e7e1af060017709bee"]["718 AD to 1200 AD"] = {
  startDate=718,
  endDate=1200
}
army_dates["5fb1b9e7e1af060017709bee"]["718 AD to 764 AD"] = {
  startDate=718,
  endDate=764
}
army_dates["5fb1b9e7e1af060017709bee"]["765 AD to 950 AD"] = {
  startDate=765,
  endDate=950
}
army_dates["5fb1b9e7e1af060017709bee"]["951 AD to 1000 AD"] = {
  startDate=951,
  endDate=1000
}
army_dates["5fb1b9e7e1af060017709bee"]["1001 AD to 1030 AD"] = {
  startDate=1001,
  endDate=1030
}
army_dates["5fb1b9e7e1af060017709bee"]["1031 AD to 1110 AD"] = {
  startDate=1031,
  endDate=1110
}
army_dates["5fb1b9e7e1af060017709bee"]["1111 AD to 1150 AD"] = {
  startDate=1111,
  endDate=1150
}
army_dates["5fb1b9e7e1af060017709bee"]["1151 AD to 1172 AD"] = {
  startDate=1151,
  endDate=1172
}
army_dates["5fb1b9e7e1af060017709bee"]["1173 AD to 1200 AD"] = {
  startDate=1173,
  endDate=1200
}
