-- 5fb1b9e7e1af060017709c2d Navarrese Company in Greece  1377 to 1430 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba33e1af06001770dff0_general='5fb1ba33e1af06001770dff0_general'
g_base_definitions[g_str_5fb1ba33e1af06001770dff0_general]={
  id=g_str_5fb1ba33e1af06001770dff0_general,
  name='Knights General',
  min=0,
  max=1,
  description='Mesnaderos',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dfef",
}
g_str_5fb1ba33e1af06001770dff0='5fb1ba33e1af06001770dff0'
g_base_definitions[g_str_5fb1ba33e1af06001770dff0]={
  id=g_str_5fb1ba33e1af06001770dff0,
  name='Knights',
  min=0,
  max=1,
  description='Mesnaderos',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dfef",
}
g_str_5fb1ba33e1af06001770dff2_general='5fb1ba33e1af06001770dff2_general'
g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general]={
  id=g_str_5fb1ba33e1af06001770dff2_general,
  name='Knights General',
  min=1,
  max=1,
  description='Free company Gascon men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dff1",
}
g_str_5fb1ba33e1af06001770dff2_general_dismounted='5fb1ba33e1af06001770dff2_general_dismounted'
g_str_5fb1ba33e1af06001770dff2_general_mounted='5fb1ba33e1af06001770dff2_general_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general_dismounted]={
  id=g_str_5fb1ba33e1af06001770dff2_general_dismounted,
  name='Elite Foot General',
  min=1,
  max=1,
  description='Free company Gascon men-at-arms\nDeployment dismounted from Knights General',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770dff2_general_mounted,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770dff1",
}
g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general_mounted]={
  id=g_str_5fb1ba33e1af06001770dff2_general_mounted,
  name='Knights General',
  min=1,
  max=1,
  description='Free company Gascon men-at-arms\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770dff2_general_dismounted,
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dff1",
}
g_str_5fb1ba33e1af06001770dff2='5fb1ba33e1af06001770dff2'
g_base_definitions[g_str_5fb1ba33e1af06001770dff2]={
  id=g_str_5fb1ba33e1af06001770dff2,
  name='Knights',
  min=1,
  max=2,
  description='Free company Gascon men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dff1",
}
g_str_5fb1ba33e1af06001770dff2_dismounted='5fb1ba33e1af06001770dff2_dismounted'
g_str_5fb1ba33e1af06001770dff2_mounted='5fb1ba33e1af06001770dff2_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770dff2_dismounted]={
  id=g_str_5fb1ba33e1af06001770dff2_dismounted,
  name='Elite Foot',
  min=1,
  max=2,
  description='Free company Gascon men-at-arms\nDeployment dismounted from Knights',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770dff2_mounted,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770dff1",
}
g_base_definitions[g_str_5fb1ba33e1af06001770dff2_mounted]={
  id=g_str_5fb1ba33e1af06001770dff2_mounted,
  name='Knights',
  min=1,
  max=2,
  description='Free company Gascon men-at-arms\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770dff2_dismounted,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dff1",
}
g_str_5fb1ba33e1af06001770dff5='5fb1ba33e1af06001770dff5'
g_base_definitions[g_str_5fb1ba33e1af06001770dff5]={
  id=g_str_5fb1ba33e1af06001770dff5,
  name='Spears',
  min=0,
  max=2,
  description='Gascon brigans armed with spear and pavise',
  troop_type="Spears",
  troop_option_id="5fb1ba33e1af06001770dff4",
}
g_str_5fb1ba33e1af06001770dff7_general='5fb1ba33e1af06001770dff7_general'
g_base_definitions[g_str_5fb1ba33e1af06001770dff7_general]={
  id=g_str_5fb1ba33e1af06001770dff7_general,
  name='Knights General',
  min=1,
  max=1,
  description='Italian elmeti',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dff6",
}
g_str_5fb1ba33e1af06001770dff7='5fb1ba33e1af06001770dff7'
g_base_definitions[g_str_5fb1ba33e1af06001770dff7]={
  id=g_str_5fb1ba33e1af06001770dff7,
  name='Knights',
  min=1,
  max=2,
  description='Italian elmeti',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dff6",
}
g_str_5fb1ba33e1af06001770dff9='5fb1ba33e1af06001770dff9'
g_base_definitions[g_str_5fb1ba33e1af06001770dff9]={
  id=g_str_5fb1ba33e1af06001770dff9,
  name='Archers',
  min=1,
  max=2,
  description='Italian crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770dff8",
}
g_str_5fb1ba33e1af06001770dffb='5fb1ba33e1af06001770dffb'
g_base_definitions[g_str_5fb1ba33e1af06001770dffb]={
  id=g_str_5fb1ba33e1af06001770dffb,
  name='Light Foot',
  min=4,
  max=8,
  description='Navarrese javelinmen or Gascon bidets',
  troop_type="Light Foot",
  troop_option_id="5fb1ba33e1af06001770dffa",
}
g_str_5fb1ba33e1af06001770dffd='5fb1ba33e1af06001770dffd'
g_base_definitions[g_str_5fb1ba33e1af06001770dffd]={
  id=g_str_5fb1ba33e1af06001770dffd,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba33e1af06001770dffc",
}
g_str_5fb1ba33e1af06001770dfff='5fb1ba33e1af06001770dfff'
g_base_definitions[g_str_5fb1ba33e1af06001770dfff]={
  id=g_str_5fb1ba33e1af06001770dfff,
  name='Archers',
  min=0,
  max=2,
  description='Gascon crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770dffe",
}
g_str_5fb1ba33e1af06001770e001='5fb1ba33e1af06001770e001'
g_base_definitions[g_str_5fb1ba33e1af06001770e001]={
  id=g_str_5fb1ba33e1af06001770e001,
  name='Bow Levy',
  min=0,
  max=1,
  description='Greek bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e000",
}
g_str_5fb1ba33e1af06001770e003='5fb1ba33e1af06001770e003'
g_base_definitions[g_str_5fb1ba33e1af06001770e003]={
  id=g_str_5fb1ba33e1af06001770e003,
  name='Horse Bow',
  min=0,
  max=1,
  description='Turkish horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba33e1af06001770e002",
}
g_str_5fb1b9e7e1af060017709c2d_camp='5fb1b9e7e1af060017709c2d_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709c2d_camp]={
  id=g_str_5fb1b9e7e1af060017709c2d_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e7e1af060017709c2d_camp_pack_train='5fb1b9e7e1af060017709c2d_camp_pack_train'
g_base_definitions[g_str_5fb1b9e7e1af060017709c2d_camp_pack_train]={
  id=g_str_5fb1b9e7e1af060017709c2d_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e7e1af060017709c2d']={
  data={
    name='Navarrese Company in Greece  1377 to 1430 AD'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770dff0_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff0],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff2_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff5],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff7_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff7],
  g_base_definitions[g_str_5fb1ba33e1af06001770dff9],
  g_base_definitions[g_str_5fb1ba33e1af06001770dffb],
  g_base_definitions[g_str_5fb1ba33e1af06001770dffd],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfff],
  g_base_definitions[g_str_5fb1ba33e1af06001770e001],
  g_base_definitions[g_str_5fb1ba33e1af06001770e003],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c2d_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c2d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c2d"] = army["5fb1b9e7e1af060017709c2d"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Navarrese Company in Greece  1377 to 1430 AD"] = army["5fb1b9e7e1af060017709c2d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c2d"] = {}
army_dates["5fb1b9e7e1af060017709c2d"]["1377 AD to 1430 AD"] ="5fb1b9e7e1af060017709c2d"
