troop_options['5fb1ba44e1af06001770fdef'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1168,
    endDate=1521,
  }
}
troop_options['5fb1ba44e1af06001770fdf1'] = {
  min=8,
  max=14,
  dateRange={
    startDate=1168,
    endDate=1521,
  }
}
troop_options['5fb1ba44e1af06001770fdf4'] = {
  min=2,
  max=5,
  dateRange={
    startDate=1168,
    endDate=1521,
  }
}
troop_options['5fb1ba44e1af06001770fdf7'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1168,
    endDate=1521,
  }
}
-- allies
