-- 5fb1b9f6e1af06001770a476 Quechua or Aymari  1438 to 1534 AD

army['5fb1b9f6e1af06001770a476']={
  data={
    name='Quechua or Aymari  1438 to 1534 AD',
    id='5fb1b9f6e1af06001770a476',
    army_id='5fb1b9f6e1af06001770a476'
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fe7c],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe7e],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a476_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a476"] = army["5fb1b9f6e1af06001770a476"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Quechua or Aymari  1438 to 1534 AD"] = army["5fb1b9f6e1af06001770a476"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Quechua or Aymari  1438 to 1534 AD"] = army["5fb1b9f6e1af06001770a476"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a476"] = {}
army_dates["5fb1b9f6e1af06001770a476"]["1438 AD to 1534 AD"] ="5fb1b9f6e1af06001770a476"
