-- 5fb1b9ebe1af060017709e2c Thematic Byzantine (in Italy)  650 to 799 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba37e1af06001770e82a']= {
  min=2,
  max=4,
  description='Kavallarioi lancers',
  core='all',
}
g_troop_entry['5fb1ba37e1af06001770e82b']= {
  troop_option='5fb1ba37e1af06001770e82a',
  troopTypeCode='JCV',
}
g_troop_option['5fb1ba37e1af06001770e82d']= {
  min=2,
  max=6,
  description='Kavallarioi horse archers',
}
g_troop_entry['5fb1ba37e1af06001770e82e']= {
  troop_option='5fb1ba37e1af06001770e82d',
  troopTypeCode='HBW',
}
g_troop_option['5fb1ba37e1af06001770e82f']= {
  min=0,
  max=2,
  description='Skoutatoi',
  core='all',
}
g_troop_entry['5fb1ba37e1af06001770e830']= {
  troop_option='5fb1ba37e1af06001770e82f',
  troopTypeCode='SPR',
}
g_troop_option['5fb1ba37e1af06001770e833']= {
  min=0,
  max=1,
  description='Bowmen',
}
g_troop_entry['5fb1ba37e1af06001770e834']= {
  troop_option='5fb1ba37e1af06001770e833',
  troopTypeCode='SKM',
}
g_troop_entry['5fb1ba37e1af06001770e835']= {
  troop_option='5fb1ba37e1af06001770e833',
  troopTypeCode='ARC',
}
g_troop_option['5fb1ba37e1af06001770e837']= {
  min=1,
  max=4,
  description='Italian town militia',
  core='all',
}
g_troop_entry['5fb1ba37e1af06001770e838']= {
  troop_option='5fb1ba37e1af06001770e837',
  troopTypeCode='HFT',
}
g_troop_option['5fb1ba37e1af06001770e839']= {
  min=0,
  max=2,
  description='Poorly armed militia "populus"',
  core='all',
}
g_troop_entry['5fb1ba37e1af06001770e83a']= {
  troop_option='5fb1ba37e1af06001770e839',
  troopTypeCode='HRD',
}
g_str_5fb1ba37e1af06001770e82b_general='5fb1ba37e1af06001770e82b_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e82b_general]={
  id=g_str_5fb1ba37e1af06001770e82b_general,
  name='Javelin Cavalry General',
  min=2,
  max=1,
  description='Kavallarioi lancers',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba37e1af06001770e82b='5fb1ba37e1af06001770e82b'
g_base_definitions[g_str_5fb1ba37e1af06001770e82b]={
  id=g_str_5fb1ba37e1af06001770e82b,
  name='Javelin Cavalry',
  min=2,
  max=4,
  description='Kavallarioi lancers',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba37e1af06001770e82e='5fb1ba37e1af06001770e82e'
g_base_definitions[g_str_5fb1ba37e1af06001770e82e]={
  id=g_str_5fb1ba37e1af06001770e82e,
  name='Horse Bow',
  min=2,
  max=6,
  description='Kavallarioi horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba37e1af06001770e830='5fb1ba37e1af06001770e830'
g_base_definitions[g_str_5fb1ba37e1af06001770e830]={
  id=g_str_5fb1ba37e1af06001770e830,
  name='Spears',
  min=0,
  max=2,
  description='Skoutatoi',
  troop_type="Spears",
}
g_str_5fb1ba37e1af06001770e834='5fb1ba37e1af06001770e834'
g_base_definitions[g_str_5fb1ba37e1af06001770e834]={
  id=g_str_5fb1ba37e1af06001770e834,
  name='Skirmishers',
  min=0,
  max=1,
  description='Bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba37e1af06001770e835='5fb1ba37e1af06001770e835'
g_base_definitions[g_str_5fb1ba37e1af06001770e835]={
  id=g_str_5fb1ba37e1af06001770e835,
  name='Archers',
  min=0,
  max=1,
  description='Bowmen',
  troop_type="Archers",
}
g_str_5fb1ba37e1af06001770e838='5fb1ba37e1af06001770e838'
g_base_definitions[g_str_5fb1ba37e1af06001770e838]={
  id=g_str_5fb1ba37e1af06001770e838,
  name='Heavy Foot',
  min=1,
  max=4,
  description='Italian town militia',
  troop_type="Heavy Foot",
}
g_str_5fb1ba37e1af06001770e83a='5fb1ba37e1af06001770e83a'
g_base_definitions[g_str_5fb1ba37e1af06001770e83a]={
  id=g_str_5fb1ba37e1af06001770e83a,
  name='Horde',
  min=0,
  max=2,
  description='Poorly armed militia "populus"',
  troop_type="Horde",
}
g_str_5fb1b9ebe1af060017709e2c_camp='5fb1b9ebe1af060017709e2c_camp'
g_base_definitions[g_str_5fb1b9ebe1af060017709e2c_camp]={
  id=g_str_5fb1b9ebe1af060017709e2c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ebe1af060017709e2c_camp_fortified='5fb1b9ebe1af060017709e2c_camp_fortified'
g_base_definitions[g_str_5fb1b9ebe1af060017709e2c_camp_fortified]={
  id=g_str_5fb1b9ebe1af060017709e2c_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9ebe1af060017709e2c_camp_pack_train='5fb1b9ebe1af060017709e2c_camp_pack_train'
g_base_definitions[g_str_5fb1b9ebe1af060017709e2c_camp_pack_train]={
  id=g_str_5fb1b9ebe1af060017709e2c_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9ebe1af060017709e2c']={
  data={
    name='Thematic Byzantine (in Italy)  650 to 799 AD',
    id='5fb1b9ebe1af060017709e2c',
    army_id='5fb1b9ebe1af060017709e2c'
  },
  g_base_definitions[g_str_5fb1ba37e1af06001770e82b_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e82b],
  g_base_definitions[g_str_5fb1ba37e1af06001770e82e],
  g_base_definitions[g_str_5fb1ba37e1af06001770e830],
  g_base_definitions[g_str_5fb1ba37e1af06001770e834],
  g_base_definitions[g_str_5fb1ba37e1af06001770e835],
  g_base_definitions[g_str_5fb1ba37e1af06001770e838],
  g_base_definitions[g_str_5fb1ba37e1af06001770e83a],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e2c_camp],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e2c_camp_fortified],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e2c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ebe1af060017709e2c"] = army["5fb1b9ebe1af060017709e2c"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Thematic Byzantine (in Italy)  650 to 799 AD"] = army["5fb1b9ebe1af060017709e2c"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Thematic Byzantine (in Italy)  650 to 799 AD"] = army["5fb1b9ebe1af060017709e2c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Thematic Byzantine (in Italy)  650 to 799 AD"] = army["5fb1b9ebe1af060017709e2c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ebe1af060017709e2c"] = {}
army_dates["5fb1b9ebe1af060017709e2c"]["650 AD to 799 AD"] ="5fb1b9ebe1af060017709e2c"
