-- 5fb1b9dce1af06001770959d Warlike Gallic  400 to 100 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba27e1af06001770c87f_general='5fb1ba27e1af06001770c87f_general'
g_base_definitions[g_str_5fb1ba27e1af06001770c87f_general]={
  id=g_str_5fb1ba27e1af06001770c87f_general,
  name='Battle Taxi General',
  min=1,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c87d",
}
g_str_5fb1ba27e1af06001770c87f_general_dismounted='5fb1ba27e1af06001770c87f_general_dismounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c87f_general_dismounted]={
  id=g_str_5fb1ba27e1af06001770c87f_general_dismounted,
  name='Warriors General',
  min=1,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounted from Battle Taxi General',
  points=3,
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba27e1af06001770c87d",
}
g_5fb1ba27e1af06001770c87f_general_dismounted=g_base_definitions[g_str_5fb1ba27e1af06001770c87f_general_dismounted]
g_str_5fb1ba27e1af06001770c87f_general_mounted='5fb1ba27e1af06001770c87f_general_mounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c87f_general_mounted]={
  id=g_str_5fb1ba27e1af06001770c87f_general_mounted,
  name='Battle Taxi General',
  min=1,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounting as Warrior',
  points=3,
  dismount_as=g_5fb1ba27e1af06001770c87f_general_dismounted,
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c87d",
}
g_str_5fb1ba27e1af06001770c87f='5fb1ba27e1af06001770c87f'
g_base_definitions[g_str_5fb1ba27e1af06001770c87f]={
  id=g_str_5fb1ba27e1af06001770c87f,
  name='Battle Taxi',
  min=1,
  max=3,
  description='2-horse battle platforms with champions who dismount to fight on foot',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c87d",
}
g_str_5fb1ba27e1af06001770c87f_dismounted='5fb1ba27e1af06001770c87f_dismounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c87f_dismounted]={
  id=g_str_5fb1ba27e1af06001770c87f_dismounted,
  name='Warriors',
  min=1,
  max=3,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounted from Battle Taxi',
  points=3,
  troop_type="Warriors",
  troop_option_id="5fb1ba27e1af06001770c87d",
}
g_5fb1ba27e1af06001770c87f_dismounted=g_base_definitions[g_str_5fb1ba27e1af06001770c87f_dismounted]
g_str_5fb1ba27e1af06001770c87f_mounted='5fb1ba27e1af06001770c87f_mounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c87f_mounted]={
  id=g_str_5fb1ba27e1af06001770c87f_mounted,
  name='Battle Taxi',
  min=1,
  max=3,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounting as Warrior',
  points=3,
  dismount_as=g_5fb1ba27e1af06001770c87f_dismounted,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c87d",
}
g_str_5fb1ba27e1af06001770c883_general='5fb1ba27e1af06001770c883_general'
g_base_definitions[g_str_5fb1ba27e1af06001770c883_general]={
  id=g_str_5fb1ba27e1af06001770c883_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c881",
}
g_str_5fb1ba27e1af06001770c883_general_dismounted='5fb1ba27e1af06001770c883_general_dismounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c883_general_dismounted]={
  id=g_str_5fb1ba27e1af06001770c883_general_dismounted,
  name='Warriors General',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounted from Battle Taxi General',
  points=3,
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba27e1af06001770c881",
}
g_5fb1ba27e1af06001770c883_general_dismounted=g_base_definitions[g_str_5fb1ba27e1af06001770c883_general_dismounted]
g_str_5fb1ba27e1af06001770c883_general_mounted='5fb1ba27e1af06001770c883_general_mounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c883_general_mounted]={
  id=g_str_5fb1ba27e1af06001770c883_general_mounted,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounting as Warrior',
  points=3,
  dismount_as=g_5fb1ba27e1af06001770c883_general_dismounted,
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c881",
}
g_str_5fb1ba27e1af06001770c883='5fb1ba27e1af06001770c883'
g_base_definitions[g_str_5fb1ba27e1af06001770c883]={
  id=g_str_5fb1ba27e1af06001770c883,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c881",
}
g_str_5fb1ba27e1af06001770c883_dismounted='5fb1ba27e1af06001770c883_dismounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c883_dismounted]={
  id=g_str_5fb1ba27e1af06001770c883_dismounted,
  name='Warriors',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounted from Battle Taxi',
  points=3,
  troop_type="Warriors",
  troop_option_id="5fb1ba27e1af06001770c881",
}
g_5fb1ba27e1af06001770c883_dismounted=g_base_definitions[g_str_5fb1ba27e1af06001770c883_dismounted]
g_str_5fb1ba27e1af06001770c883_mounted='5fb1ba27e1af06001770c883_mounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c883_mounted]={
  id=g_str_5fb1ba27e1af06001770c883_mounted,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who dismount to fight on foot\nDeployment dismounting as Warrior',
  points=3,
  dismount_as=g_5fb1ba27e1af06001770c883_dismounted,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770c881",
}
g_str_5fb1ba27e1af06001770c887_general='5fb1ba27e1af06001770c887_general'
g_base_definitions[g_str_5fb1ba27e1af06001770c887_general]={
  id=g_str_5fb1ba27e1af06001770c887_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba27e1af06001770c885",
}
g_str_5fb1ba27e1af06001770c887='5fb1ba27e1af06001770c887'
g_base_definitions[g_str_5fb1ba27e1af06001770c887]={
  id=g_str_5fb1ba27e1af06001770c887,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Noble horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba27e1af06001770c885",
}
g_str_5fb1ba27e1af06001770c889='5fb1ba27e1af06001770c889'
g_base_definitions[g_str_5fb1ba27e1af06001770c889]={
  id=g_str_5fb1ba27e1af06001770c889,
  name='Bad Horse',
  min=0,
  max=3,
  description='Horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba27e1af06001770c888",
}
g_str_5fb1ba27e1af06001770c88b_general='5fb1ba27e1af06001770c88b_general'
g_base_definitions[g_str_5fb1ba27e1af06001770c88b_general]={
  id=g_str_5fb1ba27e1af06001770c88b_general,
  name='Warriors General',
  min=8,
  max=1,
  description='Fierce fighters',
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba27e1af06001770c88a",
}
g_str_5fb1ba27e1af06001770c88b='5fb1ba27e1af06001770c88b'
g_base_definitions[g_str_5fb1ba27e1af06001770c88b]={
  id=g_str_5fb1ba27e1af06001770c88b,
  name='Warriors',
  min=8,
  max=14,
  description='Fierce fighters',
  troop_type="Warriors",
  troop_option_id="5fb1ba27e1af06001770c88a",
}
g_str_5fb1ba27e1af06001770c88d='5fb1ba27e1af06001770c88d'
g_base_definitions[g_str_5fb1ba27e1af06001770c88d]={
  id=g_str_5fb1ba27e1af06001770c88d,
  name='Rabble',
  min=1,
  max=2,
  description='Poorly equipped and trained bowmen, slingers, and unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba27e1af06001770c88c",
}
g_str_5fb1ba27e1af06001770c88f='5fb1ba27e1af06001770c88f'
g_base_definitions[g_str_5fb1ba27e1af06001770c88f]={
  id=g_str_5fb1ba27e1af06001770c88f,
  name='Warband',
  min=0,
  max=3,
  description='Gaesati naked fighters',
  troop_type="Warband",
  troop_option_id="5fb1ba27e1af06001770c88e",
}
g_str_5fb1b9dce1af06001770959d_camp='5fb1b9dce1af06001770959d_camp'
g_base_definitions[g_str_5fb1b9dce1af06001770959d_camp]={
  id=g_str_5fb1b9dce1af06001770959d_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dce1af06001770959d_camp_fortified='5fb1b9dce1af06001770959d_camp_fortified'
g_base_definitions[g_str_5fb1b9dce1af06001770959d_camp_fortified]={
  id=g_str_5fb1b9dce1af06001770959d_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9dce1af06001770959d']={
  data={
    name='Warlike Gallic  400 to 100 BC'
  },
  g_base_definitions[g_str_5fb1ba27e1af06001770c87f_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770c87f_general_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c87f_general_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c87f],
  g_base_definitions[g_str_5fb1ba27e1af06001770c87f_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c87f_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c883_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770c883_general_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c883_general_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c883],
  g_base_definitions[g_str_5fb1ba27e1af06001770c883_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c883_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c887_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770c887],
  g_base_definitions[g_str_5fb1ba27e1af06001770c889],
  g_base_definitions[g_str_5fb1ba27e1af06001770c88b_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770c88b],
  g_base_definitions[g_str_5fb1ba27e1af06001770c88d],
  g_base_definitions[g_str_5fb1ba27e1af06001770c88f],
  g_base_definitions[g_str_5fb1b9dce1af06001770959d_camp],
  g_base_definitions[g_str_5fb1b9dce1af06001770959d_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af06001770959d"] = army["5fb1b9dce1af06001770959d"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Warlike Gallic  400 to 100 BC"] = army["5fb1b9dce1af06001770959d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Warlike Gallic  400 to 100 BC"] = army["5fb1b9dce1af06001770959d"]
