-- 5fb1b9dee1af0600177096ce Ariariathid Kappadokian  330 BC to 17 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba29e1af06001770cd46='5fb1ba29e1af06001770cd46'
g_base_definitions[g_str_5fb1ba29e1af06001770cd46]={
  id=g_str_5fb1ba29e1af06001770cd46,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Horsemen with armored horses',
}
g_str_5fb1ba29e1af06001770cd46='5fb1ba29e1af06001770cd46'
g_base_definitions[g_str_5fb1ba29e1af06001770cd46]={
  id=g_str_5fb1ba29e1af06001770cd46,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Horsemen with armored horses',
}
g_str_5fb1ba29e1af06001770cd48='5fb1ba29e1af06001770cd48'
g_base_definitions[g_str_5fb1ba29e1af06001770cd48]={
  id=g_str_5fb1ba29e1af06001770cd48,
  name='Javelin Cavalry General',
  min=3,
  max=1,
  description='Horsemen and light Horsemen, all with javelins',
}
g_str_5fb1ba29e1af06001770cd48='5fb1ba29e1af06001770cd48'
g_base_definitions[g_str_5fb1ba29e1af06001770cd48]={
  id=g_str_5fb1ba29e1af06001770cd48,
  name='Javelin Cavalry',
  min=3,
  max=6,
  description='Horsemen and light Horsemen, all with javelins',
}
g_str_5fb1ba29e1af06001770cd4a='5fb1ba29e1af06001770cd4a'
g_base_definitions[g_str_5fb1ba29e1af06001770cd4a]={
  id=g_str_5fb1ba29e1af06001770cd4a,
  name='Light Foot',
  min=3,
  max=11,
  description='Infantry',
}
g_str_5fb1ba29e1af06001770cd4c='5fb1ba29e1af06001770cd4c'
g_base_definitions[g_str_5fb1ba29e1af06001770cd4c]={
  id=g_str_5fb1ba29e1af06001770cd4c,
  name='Bow Levy',
  min=1,
  max=4,
  description='Bowmen',
}
g_str_5fb1ba29e1af06001770cd4f='5fb1ba29e1af06001770cd4f'
g_base_definitions[g_str_5fb1ba29e1af06001770cd4f]={
  id=g_str_5fb1ba29e1af06001770cd4f,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Mercenary hoplites',
}
g_str_5fb1ba29e1af06001770cd52='5fb1ba29e1af06001770cd52'
g_base_definitions[g_str_5fb1ba29e1af06001770cd52]={
  id=g_str_5fb1ba29e1af06001770cd52,
  name='Light Foot',
  min=0,
  max=1,
  description='Thracian mercenary infantry',
}
g_str_5fb1ba29e1af06001770cd55='5fb1ba29e1af06001770cd55'
g_base_definitions[g_str_5fb1ba29e1af06001770cd55]={
  id=g_str_5fb1ba29e1af06001770cd55,
  name='Raiders',
  min=0,
  max=1,
  description='Mercenary thureophoroi',
}
g_str_5fb1b9dee1af0600177096ce_camp='5fb1b9dee1af0600177096ce_camp'
g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp]={
  name='Camp',
  id=g_str_5fb1b9dee1af0600177096ce_camp,
  min=1,
  max=1,
}
army['5fb1b9dee1af0600177096ce']={
  data={
    name='Ariariathid Kappadokian  330 BC to 17 AD'
  },
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd57],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd58],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd52],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd55],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096ce"] = army["5fb1b9dee1af0600177096ce"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Ariariathid Kappadokian  330 BC to 17 AD"] = army["5fb1b9dee1af0600177096ce"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Ariariathid Kappadokian  330 BC to 17 AD"] = army["5fb1b9dee1af0600177096ce"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Ariariathid Kappadokian  330 BC to 17 AD"] = army["5fb1b9dee1af0600177096ce"]
