-- 5fb1b9dee1af06001770968b Hellenistic Aitolian  278 to 146 BC

army['5fb1b9dee1af06001770968b']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Hellenistic Aitolian  278 to 146 BC',
    id='5fb1b9dee1af06001770968b',
    dateRange={
      startDate=-278,
      endDate=-146,
    },
  },
  g_base_definitions[g_str_615351a303385c0016b85cc5_general],
  g_base_definitions[g_str_615351a303385c0016b85cc5],
  g_base_definitions[g_str_615351a303385c0016b85cc7],
  g_base_definitions[g_str_615351a303385c0016b85cc9],
  g_base_definitions[g_str_615351a303385c0016b85ccb],
  g_base_definitions[g_str_615351a303385c0016b85cce],
  g_base_definitions[g_str_615351a303385c0016b85cd0],
  g_base_definitions[g_str_615351a303385c0016b85cd1],
  g_base_definitions[g_str_5fb1b9dee1af06001770968b_camp],
  g_base_definitions[g_str_5fb1b9dee1af06001770968b_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af06001770968b"] = army["5fb1b9dee1af06001770968b"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Hellenistic Aitolian  278 to 146 BC"] = army["5fb1b9dee1af06001770968b"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Hellenistic Aitolian  278 to 146 BC"] = army["5fb1b9dee1af06001770968b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hellenistic Aitolian  278 to 146 BC"] = army["5fb1b9dee1af06001770968b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af06001770968b"] = {}
army_dates["5fb1b9dee1af06001770968b"]["278 BC to 146 BC"] = {
  startDate=-278,
  endDate=-146
}
