-- 5fb1b9dfe1af06001770977d Early Graeco-Bactrian  260 to 151 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ae1af06001770d00f_general='5fb1ba2ae1af06001770d00f_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770d00f_general]={
  id=g_str_5fb1ba2ae1af06001770d00f_general,
  name='Knights General',
  min=2,
  max=1,
  description='Iranian lancers',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba2ae1af06001770d00f='5fb1ba2ae1af06001770d00f'
g_base_definitions[g_str_5fb1ba2ae1af06001770d00f]={
  id=g_str_5fb1ba2ae1af06001770d00f,
  name='Knights',
  min=2,
  max=4,
  description='Iranian lancers',
  troop_type="Knights",
}
g_str_5fb1ba2ae1af06001770d011='5fb1ba2ae1af06001770d011'
g_base_definitions[g_str_5fb1ba2ae1af06001770d011]={
  id=g_str_5fb1ba2ae1af06001770d011,
  name='Javelin Cavalry',
  min=2,
  max=5,
  description='Bactrian, Arachosian, or similar light horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ae1af06001770d013='5fb1ba2ae1af06001770d013'
g_base_definitions[g_str_5fb1ba2ae1af06001770d013]={
  id=g_str_5fb1ba2ae1af06001770d013,
  name='Horse Bow',
  min=0,
  max=1,
  description='Saka horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1b9dfe1af06001770977d_camp='5fb1b9dfe1af06001770977d_camp'
g_base_definitions[g_str_5fb1b9dfe1af06001770977d_camp]={
  id=g_str_5fb1b9dfe1af06001770977d_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af06001770977d_camp_pack_train='5fb1b9dfe1af06001770977d_camp_pack_train'
g_base_definitions[g_str_5fb1b9dfe1af06001770977d_camp_pack_train]={
  id=g_str_5fb1b9dfe1af06001770977d_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dfe1af06001770977d']={
  data={
    name='Early Graeco-Bactrian  260 to 151 BC'
  },
  g_base_definitions[g_str_5fb1ba2ae1af06001770d00f_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d00f],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d011],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d013],
  g_base_definitions[g_str_5fb1b9dfe1af06001770977d_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770977d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770977d"] = army["5fb1b9dfe1af06001770977d"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Graeco-Bactrian  260 to 151 BC"] = army["5fb1b9dfe1af06001770977d"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Early Graeco-Bactrian  260 to 151 BC"] = army["5fb1b9dfe1af06001770977d"]
