-- 5fb1b9e1e1af06001770980d Marian Roman  105 to 25 BC

army['5fb1b9e1e1af06001770980d']={
  data={
    name='Marian Roman  105 to 25 BC',
    id='5fb1b9e1e1af06001770980d',
    army_id='5fb1b9e1e1af06001770980d'
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d1c9_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1c9],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1cb_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1cb],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1ce],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d0],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d2],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d4],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d6],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d8],
  g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp],
  g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp_pack_train],
  g_base_definitions[g_str_5fb1ba0de1af06001770acb3],
  g_base_definitions[g_str_5fb1ba0de1af06001770acb5],
  g_base_definitions[g_str_5fb1ba0de1af06001770acb6],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af06001770980d"] = army["5fb1b9e1e1af06001770980d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Marian Roman  105 to 25 BC"] = army["5fb1b9e1e1af06001770980d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Marian Roman  105 to 25 BC"] = army["5fb1b9e1e1af06001770980d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af06001770980d"] = {}
army_dates["5fb1b9e1e1af06001770980d"]["105 BC to 25 BC"] ="5fb1b9e1e1af06001770980d"
