troop_options['615351a803385c0016b86873'] = {
  min=0,
  max=2,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b86876'] = {
  min=3,
  max=6,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b86878'] = {
  min=1,
  max=4,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b8687b'] = {
  min=1,
  max=2,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b8687f'] = {
  min=0,
  max=2,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b86881'] = {
  min=0,
  max=1,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b86883'] = {
  min=0,
  max=1,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b86886'] = {
  min=0,
  max=2,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
troop_options['615351a803385c0016b86889'] = {
  min=0,
  max=1,
  dateRange={
    startDate=493,
    endDate=559,
  }
}
-- allies
