-- 5fb1b9e8e1af060017709cca Medieval German Citystates  1321 to 1439 AD

army['5fb1b9e8e1af060017709cca']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
      'Arable',
    },
    name='Medieval German Citystates  1321 to 1439 AD',
    id='5fb1b9e8e1af060017709cca',
    dateRange={
      startDate=1321,
      endDate=1439,
    },
  },
  g_base_definitions[g_str_615351ac03385c0016b872d3_general],
  g_base_definitions[g_str_615351ac03385c0016b872d3_general_mounted],
  g_base_definitions[g_str_615351ac03385c0016b872d3_general_dismounted],
  g_base_definitions[g_str_615351ac03385c0016b872d3],
  g_base_definitions[g_str_615351ac03385c0016b872d3_mounted],
  g_base_definitions[g_str_615351ac03385c0016b872d3_dismounted],
  g_base_definitions[g_str_615351ac03385c0016b872d6_general],
  g_base_definitions[g_str_615351ac03385c0016b872d6],
  g_base_definitions[g_str_615351ac03385c0016b872d8],
  g_base_definitions[g_str_615351ac03385c0016b872da],
  g_base_definitions[g_str_615351ac03385c0016b872db_general],
  g_base_definitions[g_str_615351ac03385c0016b872db],
  g_base_definitions[g_str_615351ac03385c0016b872dd_general],
  g_base_definitions[g_str_615351ac03385c0016b872dd],
  g_base_definitions[g_str_615351ac03385c0016b872e0],
  g_base_definitions[g_str_615351ac03385c0016b872e3],
  g_base_definitions[g_str_615351ac03385c0016b872e5],
  g_base_definitions[g_str_615351ac03385c0016b872e7_general],
  g_base_definitions[g_str_615351ac03385c0016b872e7],
  g_base_definitions[g_str_615351ac03385c0016b872ea_general],
  g_base_definitions[g_str_615351ac03385c0016b872ea],
  g_base_definitions[g_str_615351ac03385c0016b872eb],
  g_base_definitions[g_str_615351ac03385c0016b872ef],
  g_base_definitions[g_str_615351ac03385c0016b872f2],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cca_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cca_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cca_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709cca"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709cca"] = {}
army_dates["5fb1b9e8e1af060017709cca"]["1321 AD to 1439 AD"] = {
  startDate=1321,
  endDate=1439
}
army_dates["5fb1b9e8e1af060017709cca"]["1321 AD to 1384 AD"] = {
  startDate=1321,
  endDate=1384
}
army_dates["5fb1b9e8e1af060017709cca"]["1385 AD to 1388 AD"] = {
  startDate=1385,
  endDate=1388
}
army_dates["5fb1b9e8e1af060017709cca"]["1389 AD to 1424 AD"] = {
  startDate=1389,
  endDate=1424
}
army_dates["5fb1b9e8e1af060017709cca"]["1425 AD to 1439 AD"] = {
  startDate=1425,
  endDate=1439
}
