-- 5fb1b9e8e1af060017709ca5 Feudal German Kings or Emperors  1106 to 1320 AD

army['5fb1b9e8e1af060017709ca5']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Feudal German Kings or Emperors  1106 to 1320 AD',
    id='5fb1b9e8e1af060017709ca5',
    dateRange={
      startDate=1106,
      endDate=1320,
    }
  },
  g_base_definitions[g_str_5fb1ba34e1af06001770e1b5_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e1b5],
  g_base_definitions[g_str_5fb1ba34e1af06001770e1b8],
  g_base_definitions[g_str_5fb1ba34e1af06001770e1ba],
  g_base_definitions[g_str_5fb1ba34e1af06001770e1bc],
  g_base_definitions[g_str_5fb1ba34e1af06001770e1bf],
  g_base_definitions[g_str_5fb1ba34e1af06001770e1c0],
  g_base_definitions[g_str_5fb1b9e8e1af060017709ca5_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709ca5_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709ca5_camp_standard_wagon],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709ca5"] = army["5fb1b9e8e1af060017709ca5"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Feudal German Kings or Emperors  1106 to 1320 AD"] = army["5fb1b9e8e1af060017709ca5"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Feudal German Kings or Emperors  1106 to 1320 AD"] = army["5fb1b9e8e1af060017709ca5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Feudal German Kings or Emperors  1106 to 1320 AD"] = army["5fb1b9e8e1af060017709ca5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709ca5"] = {}
army_dates["5fb1b9e8e1af060017709ca5"]["1106 AD to 1320 AD"] = {
  startDate=1106,
  endDate=1320
}
army_dates["5fb1b9e8e1af060017709ca5"]["1106 AD to 1150 AD"] = {
  startDate=1106,
  endDate=1150
}
army_dates["5fb1b9e8e1af060017709ca5"]["1151 AD to 1244 AD"] = {
  startDate=1151,
  endDate=1244
}
army_dates["5fb1b9e8e1af060017709ca5"]["1245 AD to 1277 AD"] = {
  startDate=1245,
  endDate=1277
}
army_dates["5fb1b9e8e1af060017709ca5"]["1278 AD"] = {
  startDate=1278,
  endDate=1278
}
army_dates["5fb1b9e8e1af060017709ca5"]["1279 AD to 1320 AD"] = {
  startDate=1279,
  endDate=1320
}
