-- 5fb1b9dde1af060017709606 Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba27e1af06001770ca33='5fb1ba27e1af06001770ca33'
g_base_definitions[g_str_5fb1ba27e1af06001770ca33]={
  id=g_str_5fb1ba27e1af06001770ca33,
  name='Heavy Foot',
  min=2,
  max=9,
  description='Hoplites',
}
g_str_5fb1ba27e1af06001770ca36='5fb1ba27e1af06001770ca36'
g_base_definitions[g_str_5fb1ba27e1af06001770ca36]={
  id=g_str_5fb1ba27e1af06001770ca36,
  name='Rabble',
  min=1,
  max=3,
  description='Psiloi armed with javelins',
}
g_str_5fb1ba27e1af06001770ca38='5fb1ba27e1af06001770ca38'
g_base_definitions[g_str_5fb1ba27e1af06001770ca38]={
  id=g_str_5fb1ba27e1af06001770ca38,
  name='Javelin Cavalry',
  min=1,
  max=5,
  description='Horsemen',
}
g_str_5fb1ba27e1af06001770ca3a='5fb1ba27e1af06001770ca3a'
g_base_definitions[g_str_5fb1ba27e1af06001770ca3a]={
  id=g_str_5fb1ba27e1af06001770ca3a,
  name='Skirmishers',
  min=0,
  max=1,
  description='Cretan or other skirmishing mercenary bowmen',
}
g_str_5fb1ba27e1af06001770ca3c='5fb1ba27e1af06001770ca3c'
g_base_definitions[g_str_5fb1ba27e1af06001770ca3c]={
  id=g_str_5fb1ba27e1af06001770ca3c,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
}
g_str_5fb1ba27e1af06001770ca3e='5fb1ba27e1af06001770ca3e'
g_base_definitions[g_str_5fb1ba27e1af06001770ca3e]={
  id=g_str_5fb1ba27e1af06001770ca3e,
  name='Heavy Foot',
  min=0,
  max=12,
  description='Mercenary hoplites',
}
g_str_5fb1ba27e1af06001770ca40='5fb1ba27e1af06001770ca40'
g_base_definitions[g_str_5fb1ba27e1af06001770ca40]={
  id=g_str_5fb1ba27e1af06001770ca40,
  name='Light Foot',
  min=0,
  max=3,
  description='Mercenary peltasts',
}
g_str_5fb1ba27e1af06001770ca42='5fb1ba27e1af06001770ca42'
g_base_definitions[g_str_5fb1ba27e1af06001770ca42]={
  id=g_str_5fb1ba27e1af06001770ca42,
  name='Light Foot',
  min=0,
  max=2,
  description='Sikels',
}
g_str_5fb1ba27e1af06001770ca44='5fb1ba27e1af06001770ca44'
g_base_definitions[g_str_5fb1ba27e1af06001770ca44]={
  name='Javelin Cavalry General',
  id=g_str_5fb1ba27e1af06001770ca44,
  min=1,
  max=1,
}
g_str_5fb1ba27e1af06001770ca45='5fb1ba27e1af06001770ca45'
g_base_definitions[g_str_5fb1ba27e1af06001770ca45]={
  name='Heavy Foot General',
  id=g_str_5fb1ba27e1af06001770ca45,
  min=1,
  max=1,
}
g_str_5fb1b9dde1af060017709606_camp='5fb1b9dde1af060017709606_camp'
g_base_definitions[g_str_5fb1b9dde1af060017709606_camp]={
  name='Camp',
  id=g_str_5fb1b9dde1af060017709606_camp,
  min=1,
  max=1,
}
army['5fb1b9dde1af060017709606']={
  data={
    name='Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC'
  },
  g_base_definitions[g_str_5fb1b9dde1af060017709606_camp],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca44],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca45],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca33],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca36],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca38],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca3a],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca3c],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca3e],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca40],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca42],
}
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC"] = army["5fb1b9dde1af060017709606"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC"] = army["5fb1b9dde1af060017709606"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC"] = army["5fb1b9dde1af060017709606"]
