troop_options['5fb1ba37e1af06001770e842'] = {
  min=1,
  max=2,
  dateRange={
    startDate=639,
    endDate=717,
  }
}
troop_options['5fb1ba37e1af06001770e844'] = {
  min=2,
  max=4,
  dateRange={
    startDate=639,
    endDate=717,
  }
}
troop_options['5fb1ba37e1af06001770e846'] = {
  min=4,
  max=11,
  dateRange={
    startDate=639,
    endDate=717,
  }
}
troop_options['5fb1ba37e1af06001770e849'] = {
  min=1,
  max=4,
  dateRange={
    startDate=639,
    endDate=717,
  }
}
troop_options['5fb1ba37e1af06001770e84c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=639,
    endDate=717,
  }
}
-- allies
