-- 5fb1b9f3e1af06001770a302 Early Ming Chinese  1350 to 1419 AD

army['5fb1b9f3e1af06001770a302']={
  data={
    invasionRatings={
      {
        value=3,
        note='',
      },
    },
    name='Early Ming Chinese  1350 to 1419 AD',
    id='5fb1b9f3e1af06001770a302',
    dateRange={
      startDate=1350,
      endDate=1419,
    }
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770fb55_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb55],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb58_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb58],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5a_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5a],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5d_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5d],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5f],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb62],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb63],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb65],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb66],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb68],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb69],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb6b],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a302_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a302"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a302"] = {}
army_dates["5fb1b9f3e1af06001770a302"]["1350 AD to 1419 AD"] = {
  startDate=1350,
  endDate=1419
}
army_dates["5fb1b9f3e1af06001770a302"]["1350 AD to 1359 AD"] = {
  startDate=1350,
  endDate=1359
}
army_dates["5fb1b9f3e1af06001770a302"]["1360 AD to 1362 AD"] = {
  startDate=1360,
  endDate=1362
}
army_dates["5fb1b9f3e1af06001770a302"]["1363 AD to 1419 AD"] = {
  startDate=1363,
  endDate=1419
}
