-- 5fb1b9efe1af06001770a07a Ghaznavid  962 to 1186 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3ce1af06001770f228_general='5fb1ba3ce1af06001770f228_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f228_general]={
  id=g_str_5fb1ba3ce1af06001770f228_general,
  name='Elite Cavalary General',
  min=2,
  max=1,
  description='Ghulams',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f227",
}
g_str_5fb1ba3ce1af06001770f228='5fb1ba3ce1af06001770f228'
g_base_definitions[g_str_5fb1ba3ce1af06001770f228]={
  id=g_str_5fb1ba3ce1af06001770f228,
  name='Elite Cavalary',
  min=2,
  max=4,
  description='Ghulams',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f227",
}
g_str_5fb1ba3ce1af06001770f22c_general='5fb1ba3ce1af06001770f22c_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f22c_general]={
  id=g_str_5fb1ba3ce1af06001770f22c_general,
  name='Elephants General',
  min=1,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
  troop_option_id="5fb1ba3ce1af06001770f22a",
}
g_str_5fb1ba3ce1af06001770f22c='5fb1ba3ce1af06001770f22c'
g_base_definitions[g_str_5fb1ba3ce1af06001770f22c]={
  id=g_str_5fb1ba3ce1af06001770f22c,
  name='Elephants',
  min=1,
  max=2,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba3ce1af06001770f22a",
}
g_str_5fb1ba3ce1af06001770f22e='5fb1ba3ce1af06001770f22e'
g_base_definitions[g_str_5fb1ba3ce1af06001770f22e]={
  id=g_str_5fb1ba3ce1af06001770f22e,
  name='Spears',
  min=0,
  max=1,
  description='Armored infantry',
  troop_type="Spears",
  troop_option_id="5fb1ba3ce1af06001770f22d",
}
g_str_5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry='5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry'
g_str_5fb1ba3ce1af06001770f22e_mounted_mobile_infantry='5fb1ba3ce1af06001770f22e_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry,
  name='Spears',
  min=0,
  max=1,
  description='Armored infantry\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba3ce1af06001770f22e_mounted_mobile_infantry,
  troop_type="Spears",
  troop_option_id="5fb1ba3ce1af06001770f22d",
}
g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_mounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f22e_mounted_mobile_infantry,
  name='Spears',
  min=0,
  max=1,
  description='Armored infantry\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Spears",
  troop_option_id="5fb1ba3ce1af06001770f22d",
}
g_str_5fb1ba3ce1af06001770f22f='5fb1ba3ce1af06001770f22f'
g_base_definitions[g_str_5fb1ba3ce1af06001770f22f]={
  id=g_str_5fb1ba3ce1af06001770f22f,
  name='Archers',
  min=0,
  max=1,
  description='Armored infantry',
  troop_type="Archers",
  troop_option_id="5fb1ba3ce1af06001770f22d",
}
g_str_5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry='5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry'
g_str_5fb1ba3ce1af06001770f22f_mounted_mobile_infantry='5fb1ba3ce1af06001770f22f_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry,
  name='Archers',
  min=0,
  max=1,
  description='Armored infantry\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba3ce1af06001770f22f_mounted_mobile_infantry,
  troop_type="Archers",
  troop_option_id="5fb1ba3ce1af06001770f22d",
}
g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_mounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f22f_mounted_mobile_infantry,
  name='Archers',
  min=0,
  max=1,
  description='Armored infantry\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Archers",
  troop_option_id="5fb1ba3ce1af06001770f22d",
}
g_str_5fb1ba3ce1af06001770f232='5fb1ba3ce1af06001770f232'
g_base_definitions[g_str_5fb1ba3ce1af06001770f232]={
  id=g_str_5fb1ba3ce1af06001770f232,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami zupin-men',
  troop_type="Raiders",
  troop_option_id="5fb1ba3ce1af06001770f231",
}
g_str_5fb1ba3ce1af06001770f232_dismounted_mobile_infantry='5fb1ba3ce1af06001770f232_dismounted_mobile_infantry'
g_str_5fb1ba3ce1af06001770f232_mounted_mobile_infantry='5fb1ba3ce1af06001770f232_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba3ce1af06001770f232_dismounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f232_dismounted_mobile_infantry,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami zupin-men\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba3ce1af06001770f232_mounted_mobile_infantry,
  troop_type="Raiders",
  troop_option_id="5fb1ba3ce1af06001770f231",
}
g_base_definitions[g_str_5fb1ba3ce1af06001770f232_mounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f232_mounted_mobile_infantry,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami zupin-men\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba3ce1af06001770f232_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba3ce1af06001770f231",
}
g_str_5fb1ba3ce1af06001770f235='5fb1ba3ce1af06001770f235'
g_base_definitions[g_str_5fb1ba3ce1af06001770f235]={
  id=g_str_5fb1ba3ce1af06001770f235,
  name='Horse Bow',
  min=1,
  max=2,
  description='Turkish, Tajik or similar nomadic auxiliaries or ghazis',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3ce1af06001770f234",
}
g_str_5fb1ba3ce1af06001770f237_general='5fb1ba3ce1af06001770f237_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f237_general]={
  id=g_str_5fb1ba3ce1af06001770f237_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Kurdish auxiliary horsemen',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f236",
}
g_str_5fb1ba3ce1af06001770f237='5fb1ba3ce1af06001770f237'
g_base_definitions[g_str_5fb1ba3ce1af06001770f237]={
  id=g_str_5fb1ba3ce1af06001770f237,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Kurdish auxiliary horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f236",
}
g_str_5fb1ba3ce1af06001770f23a='5fb1ba3ce1af06001770f23a'
g_base_definitions[g_str_5fb1ba3ce1af06001770f23a]={
  id=g_str_5fb1ba3ce1af06001770f23a,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Arab or Kurdish ghazis',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3ce1af06001770f239",
}
g_str_5fb1ba3ce1af06001770f23c='5fb1ba3ce1af06001770f23c'
g_base_definitions[g_str_5fb1ba3ce1af06001770f23c]={
  id=g_str_5fb1ba3ce1af06001770f23c,
  name='Warband',
  min=0,
  max=1,
  description='Ghazis on foot',
  troop_type="Warband",
  troop_option_id="5fb1ba3ce1af06001770f23b",
}
g_str_5fb1ba3ce1af06001770f23e='5fb1ba3ce1af06001770f23e'
g_base_definitions[g_str_5fb1ba3ce1af06001770f23e]={
  id=g_str_5fb1ba3ce1af06001770f23e,
  name='Light Spear',
  min=0,
  max=1,
  description='Afghan light infantry',
  troop_type="Light Spear",
  troop_option_id="5fb1ba3ce1af06001770f23d",
}
g_str_5fb1ba3ce1af06001770f241='5fb1ba3ce1af06001770f241'
g_base_definitions[g_str_5fb1ba3ce1af06001770f241]={
  id=g_str_5fb1ba3ce1af06001770f241,
  name='Bow Levy',
  min=0,
  max=2,
  description='Hindu Indian bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3ce1af06001770f23f",
}
g_str_5fb1b9efe1af06001770a07a_camp='5fb1b9efe1af06001770a07a_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp]={
  id=g_str_5fb1b9efe1af06001770a07a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9efe1af06001770a07a_camp_fortified='5fb1b9efe1af06001770a07a_camp_fortified'
g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_fortified]={
  id=g_str_5fb1b9efe1af06001770a07a_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9efe1af06001770a07a_camp_pack_train='5fb1b9efe1af06001770a07a_camp_pack_train'
g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_pack_train]={
  id=g_str_5fb1b9efe1af06001770a07a_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9efe1af06001770a07a']={
  data={
    name='Ghaznavid  962 to 1186 AD'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f228_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f228],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22c_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f235],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f237_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f237],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23a],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f241],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_fortified],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a07a"] = army["5fb1b9efe1af06001770a07a"]
army['5fb1b9efe1af06001770a07a_962_1001']={
  data={
    name='Ghaznavid 962 AD to 1001 AD'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f228_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f228],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f235],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f237_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f237],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23a],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23e],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_fortified],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_pack_train],
}
army['5fb1b9efe1af06001770a07a_1002_1186']={
  data={
    name='Ghaznavid 1002 AD to 1186 AD'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f228_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f228],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22c_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22e_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f22f_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f232_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f235],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f237_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f237],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23a],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f23e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f241],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_fortified],
  g_base_definitions[g_str_5fb1b9efe1af06001770a07a_camp_pack_train],
}
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Ghaznavid  962 to 1186 AD"] = army["5fb1b9efe1af06001770a07a"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Ghaznavid  962 to 1186 AD"] = army["5fb1b9efe1af06001770a07a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Ghaznavid  962 to 1186 AD"] = army["5fb1b9efe1af06001770a07a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a07a"] = {}
army_dates["5fb1b9efe1af06001770a07a"]["962 AD to 1186 AD"] ="5fb1b9efe1af06001770a07a"
army_dates["5fb1b9efe1af06001770a07a"]["962 AD to 1001 AD"] ="5fb1b9efe1af06001770a07a_962_1001"
army_dates["5fb1b9efe1af06001770a07a"]["1002 AD to 1186 AD"] ="5fb1b9efe1af06001770a07a_1002_1186"
