-- 5fb1b9e2e1af0600177098f4 Later Patrician Roman West  468 to 486 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2de1af06001770d511='5fb1ba2de1af06001770d511'
g_base_definitions[g_str_5fb1ba2de1af06001770d511]={
  id=g_str_5fb1ba2de1af06001770d511,
  name='Knights',
  min=0,
  max=2,
  description='Germanic or Alan lancers',
  troop_type="Knights",
  troop_option_id="5fb1ba2de1af06001770d510",
}
g_str_5fb1ba2de1af06001770d513='5fb1ba2de1af06001770d513'
g_base_definitions[g_str_5fb1ba2de1af06001770d513]={
  id=g_str_5fb1ba2de1af06001770d513,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Equites, possibly equipped in Hunnish style',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2de1af06001770d512",
}
g_str_5fb1ba2de1af06001770d514_general='5fb1ba2de1af06001770d514_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d514_general]={
  id=g_str_5fb1ba2de1af06001770d514_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Equites, possibly equipped in Hunnish style',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2de1af06001770d512",
}
g_str_5fb1ba2de1af06001770d514='5fb1ba2de1af06001770d514'
g_base_definitions[g_str_5fb1ba2de1af06001770d514]={
  id=g_str_5fb1ba2de1af06001770d514,
  name='Horse Bow',
  min=1,
  max=2,
  description='Equites, possibly equipped in Hunnish style',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2de1af06001770d512",
}
g_str_5fb1ba2de1af06001770d516_general='5fb1ba2de1af06001770d516_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d516_general]={
  id=g_str_5fb1ba2de1af06001770d516_general,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Legionarii',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba2de1af06001770d515",
}
g_str_5fb1ba2de1af06001770d516='5fb1ba2de1af06001770d516'
g_base_definitions[g_str_5fb1ba2de1af06001770d516]={
  id=g_str_5fb1ba2de1af06001770d516,
  name='Elite Foot',
  min=0,
  max=2,
  description='Legionarii',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba2de1af06001770d515",
}
g_str_5fb1ba2de1af06001770d51a='5fb1ba2de1af06001770d51a'
g_base_definitions[g_str_5fb1ba2de1af06001770d51a]={
  id=g_str_5fb1ba2de1af06001770d51a,
  name='Raiders',
  min=0,
  max=2,
  description='Auxilia Palatina',
  troop_type="Raiders",
  troop_option_id="5fb1ba2de1af06001770d519",
}
g_str_5fb1ba2de1af06001770d51d_general='5fb1ba2de1af06001770d51d_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d51d_general]={
  id=g_str_5fb1ba2de1af06001770d51d_general,
  name='Heavy Foot General',
  min=4,
  max=1,
  description='Various garrison, Foederati, and downgraded Legio and Auxilia Palatina',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2de1af06001770d51c",
}
g_str_5fb1ba2de1af06001770d51d='5fb1ba2de1af06001770d51d'
g_base_definitions[g_str_5fb1ba2de1af06001770d51d]={
  id=g_str_5fb1ba2de1af06001770d51d,
  name='Heavy Foot',
  min=4,
  max=14,
  description='Various garrison, Foederati, and downgraded Legio and Auxilia Palatina',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2de1af06001770d51c",
}
g_str_5fb1ba2de1af06001770d51f='5fb1ba2de1af06001770d51f'
g_base_definitions[g_str_5fb1ba2de1af06001770d51f]={
  id=g_str_5fb1ba2de1af06001770d51f,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen and other light infantry',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2de1af06001770d51e",
}
g_str_5fb1ba2de1af06001770d520='5fb1ba2de1af06001770d520'
g_base_definitions[g_str_5fb1ba2de1af06001770d520]={
  id=g_str_5fb1ba2de1af06001770d520,
  name='Rabble',
  min=0,
  max=2,
  description='Skirmishing bowmen and other light infantry',
  troop_type="Rabble",
  troop_option_id="5fb1ba2de1af06001770d51e",
}
g_str_5fb1ba2de1af06001770d523_general='5fb1ba2de1af06001770d523_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d523_general]={
  id=g_str_5fb1ba2de1af06001770d523_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Alan or Hun horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2de1af06001770d522",
}
g_str_5fb1ba2de1af06001770d523='5fb1ba2de1af06001770d523'
g_base_definitions[g_str_5fb1ba2de1af06001770d523]={
  id=g_str_5fb1ba2de1af06001770d523,
  name='Horse Bow',
  min=0,
  max=1,
  description='Alan or Hun horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2de1af06001770d522",
}
g_str_5fb1ba2de1af06001770d525='5fb1ba2de1af06001770d525'
g_base_definitions[g_str_5fb1ba2de1af06001770d525]={
  id=g_str_5fb1ba2de1af06001770d525,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt-shooters',
  troop_type="Artillery",
  troop_option_id="5fb1ba2de1af06001770d524",
}
g_str_5fb1b9e2e1af0600177098f4_camp='5fb1b9e2e1af0600177098f4_camp'
g_base_definitions[g_str_5fb1b9e2e1af0600177098f4_camp]={
  id=g_str_5fb1b9e2e1af0600177098f4_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af0600177098f4_camp_fortified='5fb1b9e2e1af0600177098f4_camp_fortified'
g_base_definitions[g_str_5fb1b9e2e1af0600177098f4_camp_fortified]={
  id=g_str_5fb1b9e2e1af0600177098f4_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af0600177098f4_camp_pack_train='5fb1b9e2e1af0600177098f4_camp_pack_train'
g_base_definitions[g_str_5fb1b9e2e1af0600177098f4_camp_pack_train]={
  id=g_str_5fb1b9e2e1af0600177098f4_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e2e1af0600177098f4']={
  data={
    name='Later Patrician Roman West  468 to 486 AD'
  },
  g_base_definitions[g_str_5fb1ba2de1af06001770d511],
  g_base_definitions[g_str_5fb1ba2de1af06001770d513],
  g_base_definitions[g_str_5fb1ba2de1af06001770d514_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d514],
  g_base_definitions[g_str_5fb1ba2de1af06001770d516_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d516],
  g_base_definitions[g_str_5fb1ba2de1af06001770d51a],
  g_base_definitions[g_str_5fb1ba2de1af06001770d51d_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d51d],
  g_base_definitions[g_str_5fb1ba2de1af06001770d51f],
  g_base_definitions[g_str_5fb1ba2de1af06001770d520],
  g_base_definitions[g_str_5fb1ba2de1af06001770d523_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d523],
  g_base_definitions[g_str_5fb1ba2de1af06001770d525],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098f4_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098f4_camp_fortified],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098f4_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098f4"] = army["5fb1b9e2e1af0600177098f4"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Later Patrician Roman West  468 to 486 AD"] = army["5fb1b9e2e1af0600177098f4"]
