troop_options['615351ab03385c0016b86ec9'] = {
  min=3,
  max=9,
  dateRange={
    startDate=696,
    endDate=800,
  }
}
troop_options['615351ab03385c0016b86ecb'] = {
  min=4,
  max=8,
  dateRange={
    startDate=696,
    endDate=800,
  }
}
troop_options['615351ab03385c0016b86ecd'] = {
  min=0,
  max=1,
  dateRange={
    startDate=696,
    endDate=800,
  }
}
troop_options['615351ab03385c0016b86ecf'] = {
  min=0,
  max=2,
  dateRange={
    startDate=696,
    endDate=800,
  }
}
troop_options['615351ab03385c0016b86ed2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=696,
    endDate=800,
  }
}
troop_options['615351ab03385c0016b86ed4'] = {
  min=0,
  max=1,
  dateRange={
    startDate=696,
    endDate=800,
  }
}
troop_options['615351ab03385c0016b86ed6'] = {
  min=0,
  max=1,
  dateRange={
    startDate=696,
    endDate=800,
  }
}
-- allies
