troop_options['5fb1ba2fe1af06001770da11'] = {
  min=1,
  max=2,
  dateRange={
    startDate=840,
    endDate=885,
  }
}
troop_options['5fb1ba2fe1af06001770da13'] = {
  min=7,
  max=14,
  dateRange={
    startDate=840,
    endDate=885,
  }
}
troop_options['5fb1ba2fe1af06001770da15'] = {
  min=0,
  max=1,
  dateRange={
    startDate=840,
    endDate=885,
  }
}
troop_options['5fb1ba2fe1af06001770da18'] = {
  min=0,
  max=6,
  dateRange={
    startDate=840,
    endDate=885,
  }
}
troop_options['5fb1ba2fe1af06001770da1a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=840,
    endDate=885,
  }
}
-- allies
