g_str_5fb1ba2be1af06001770d25e_general='5fb1ba2be1af06001770d25e_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d25e_general]={
  id=g_str_5fb1ba2be1af06001770d25e_general,
  name='Elite Foot General',
  min=2,
  max=1,
  description='Legionaries',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba2be1af06001770d25d",
}
g_str_5fb1ba2be1af06001770d25e='5fb1ba2be1af06001770d25e'
g_base_definitions[g_str_5fb1ba2be1af06001770d25e]={
  id=g_str_5fb1ba2be1af06001770d25e,
  name='Elite Foot',
  min=2,
  max=6,
  description='Legionaries',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba2be1af06001770d25d",
}
g_str_5fb1ba2be1af06001770d262_general='5fb1ba2be1af06001770d262_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d262_general]={
  id=g_str_5fb1ba2be1af06001770d262_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Equites alares',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d261",
}
g_str_5fb1ba2be1af06001770d262='5fb1ba2be1af06001770d262'
g_base_definitions[g_str_5fb1ba2be1af06001770d262]={
  id=g_str_5fb1ba2be1af06001770d262,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='Equites alares',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d261",
}
g_str_5fb1ba2be1af06001770d264='5fb1ba2be1af06001770d264'
g_base_definitions[g_str_5fb1ba2be1af06001770d264]={
  id=g_str_5fb1ba2be1af06001770d264,
  name='Bad Horse',
  min=0,
  max=1,
  description='Equites cohortales',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba2be1af06001770d263",
}
g_str_5fb1ba2be1af06001770d266='5fb1ba2be1af06001770d266'
g_base_definitions[g_str_5fb1ba2be1af06001770d266]={
  id=g_str_5fb1ba2be1af06001770d266,
  name='Raiders',
  min=2,
  max=6,
  description='Auxiliary infantry',
  troop_type="Raiders",
  troop_option_id="5fb1ba2be1af06001770d265",
}
g_str_5fb1ba2be1af06001770d269='5fb1ba2be1af06001770d269'
g_base_definitions[g_str_5fb1ba2be1af06001770d269]={
  id=g_str_5fb1ba2be1af06001770d269,
  name='Skirmishers',
  min=0,
  max=1,
  description='Auxiliary bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2be1af06001770d268",
}
g_str_5fb1ba2be1af06001770d26a='5fb1ba2be1af06001770d26a'
g_base_definitions[g_str_5fb1ba2be1af06001770d26a]={
  id=g_str_5fb1ba2be1af06001770d26a,
  name='Archers',
  min=0,
  max=1,
  description='Auxiliary bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba2be1af06001770d268",
}
g_str_5fb1ba2be1af06001770d26d_general='5fb1ba2be1af06001770d26d_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d26d_general]={
  id=g_str_5fb1ba2be1af06001770d26d_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Numidian, Moorish, or other horsemen depending upon where based',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d26c",
}
g_str_5fb1ba2be1af06001770d26d='5fb1ba2be1af06001770d26d'
g_base_definitions[g_str_5fb1ba2be1af06001770d26d]={
  id=g_str_5fb1ba2be1af06001770d26d,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Numidian, Moorish, or other horsemen depending upon where based',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d26c",
}
g_str_5fb1ba2be1af06001770d26f='5fb1ba2be1af06001770d26f'
g_base_definitions[g_str_5fb1ba2be1af06001770d26f]={
  id=g_str_5fb1ba2be1af06001770d26f,
  name='Artillery',
  min=0,
  max=1,
  description='Stone-throwers and bolt-shooters',
  troop_type="Artillery",
  troop_option_id="5fb1ba2be1af06001770d26e",
}
g_str_5fb1ba2be1af06001770d271='5fb1ba2be1af06001770d271'
g_base_definitions[g_str_5fb1ba2be1af06001770d271]={
  id=g_str_5fb1ba2be1af06001770d271,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Raw legionaries',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2be1af06001770d270",
}
g_str_5fb1ba2be1af06001770d273='5fb1ba2be1af06001770d273'
g_base_definitions[g_str_5fb1ba2be1af06001770d273]={
  id=g_str_5fb1ba2be1af06001770d273,
  name='Light Foot',
  min=0,
  max=2,
  description='Numeri or Symmachiarii light infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2be1af06001770d272",
}
g_str_5fb1b9e1e1af060017709831_camp='5fb1b9e1e1af060017709831_camp'
g_base_definitions[g_str_5fb1b9e1e1af060017709831_camp]={
  id=g_str_5fb1b9e1e1af060017709831_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af060017709831_camp_fortified='5fb1b9e1e1af060017709831_camp_fortified'
g_base_definitions[g_str_5fb1b9e1e1af060017709831_camp_fortified]={
  id=g_str_5fb1b9e1e1af060017709831_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af060017709831_camp_pack_train='5fb1b9e1e1af060017709831_camp_pack_train'
g_base_definitions[g_str_5fb1b9e1e1af060017709831_camp_pack_train]={
  id=g_str_5fb1b9e1e1af060017709831_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
