g_str_5fb1ba24e1af06001770c4f0_general='5fb1ba24e1af06001770c4f0_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f0_general]={
  id=g_str_5fb1ba24e1af06001770c4f0_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='2-horse battle-platform',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c4ef",
}
g_str_5fb1ba24e1af06001770c4f0='5fb1ba24e1af06001770c4f0'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f0]={
  id=g_str_5fb1ba24e1af06001770c4f0,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle-platform',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c4ef",
}
g_str_5fb1ba24e1af06001770c4f2_general='5fb1ba24e1af06001770c4f2_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f2_general]={
  id=g_str_5fb1ba24e1af06001770c4f2_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c4f1",
}
g_str_5fb1ba24e1af06001770c4f2='5fb1ba24e1af06001770c4f2'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f2]={
  id=g_str_5fb1ba24e1af06001770c4f2,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c4f1",
}
g_str_5fb1ba24e1af06001770c4f4='5fb1ba24e1af06001770c4f4'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f4]={
  id=g_str_5fb1ba24e1af06001770c4f4,
  name='Warriors',
  min=5,
  max=10,
  description='Spearmen',
  troop_type="Warriors",
  troop_option_id="5fb1ba24e1af06001770c4f3",
}
g_str_5fb1ba24e1af06001770c4f6='5fb1ba24e1af06001770c4f6'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f6]={
  id=g_str_5fb1ba24e1af06001770c4f6,
  name='Light Foot',
  min=3,
  max=10,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba24e1af06001770c4f5",
}
g_str_5fb1ba24e1af06001770c4f8='5fb1ba24e1af06001770c4f8'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f8]={
  id=g_str_5fb1ba24e1af06001770c4f8,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing mixed bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba24e1af06001770c4f7",
}
g_str_5fb1b9dbe1af0600177094aa_camp='5fb1b9dbe1af0600177094aa_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094aa_camp]={
  id=g_str_5fb1b9dbe1af0600177094aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba24e1af06001770c4f0_general='5fb1ba24e1af06001770c4f0_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f0_general]={
  id=g_str_5fb1ba24e1af06001770c4f0_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='2-horse battle-platform',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c4ef",
}
g_str_5fb1ba24e1af06001770c4f0='5fb1ba24e1af06001770c4f0'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f0]={
  id=g_str_5fb1ba24e1af06001770c4f0,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle-platform',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c4ef",
}
g_str_5fb1ba24e1af06001770c4f2_general='5fb1ba24e1af06001770c4f2_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f2_general]={
  id=g_str_5fb1ba24e1af06001770c4f2_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c4f1",
}
g_str_5fb1ba24e1af06001770c4f2='5fb1ba24e1af06001770c4f2'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f2]={
  id=g_str_5fb1ba24e1af06001770c4f2,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c4f1",
}
g_str_5fb1ba24e1af06001770c4f4='5fb1ba24e1af06001770c4f4'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f4]={
  id=g_str_5fb1ba24e1af06001770c4f4,
  name='Warriors',
  min=5,
  max=10,
  description='Spearmen',
  troop_type="Warriors",
  troop_option_id="5fb1ba24e1af06001770c4f3",
}
g_str_5fb1ba24e1af06001770c4f6='5fb1ba24e1af06001770c4f6'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f6]={
  id=g_str_5fb1ba24e1af06001770c4f6,
  name='Light Foot',
  min=3,
  max=10,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba24e1af06001770c4f5",
}
g_str_5fb1ba24e1af06001770c4f8='5fb1ba24e1af06001770c4f8'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f8]={
  id=g_str_5fb1ba24e1af06001770c4f8,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing mixed bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba24e1af06001770c4f7",
}
g_str_5fb1b9dbe1af0600177094aa_camp='5fb1b9dbe1af0600177094aa_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094aa_camp]={
  id=g_str_5fb1b9dbe1af0600177094aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba24e1af06001770c4f0_general='5fb1ba24e1af06001770c4f0_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f0_general]={
  id=g_str_5fb1ba24e1af06001770c4f0_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='2-horse battle-platform',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c4ef",
}
g_str_5fb1ba24e1af06001770c4f0='5fb1ba24e1af06001770c4f0'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f0]={
  id=g_str_5fb1ba24e1af06001770c4f0,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle-platform',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c4ef",
}
g_str_5fb1ba24e1af06001770c4f2_general='5fb1ba24e1af06001770c4f2_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f2_general]={
  id=g_str_5fb1ba24e1af06001770c4f2_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c4f1",
}
g_str_5fb1ba24e1af06001770c4f2='5fb1ba24e1af06001770c4f2'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f2]={
  id=g_str_5fb1ba24e1af06001770c4f2,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c4f1",
}
g_str_5fb1ba24e1af06001770c4f4='5fb1ba24e1af06001770c4f4'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f4]={
  id=g_str_5fb1ba24e1af06001770c4f4,
  name='Warriors',
  min=5,
  max=10,
  description='Spearmen',
  troop_type="Warriors",
  troop_option_id="5fb1ba24e1af06001770c4f3",
}
g_str_5fb1ba24e1af06001770c4f6='5fb1ba24e1af06001770c4f6'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f6]={
  id=g_str_5fb1ba24e1af06001770c4f6,
  name='Light Foot',
  min=3,
  max=10,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba24e1af06001770c4f5",
}
g_str_5fb1ba24e1af06001770c4f8='5fb1ba24e1af06001770c4f8'
g_base_definitions[g_str_5fb1ba24e1af06001770c4f8]={
  id=g_str_5fb1ba24e1af06001770c4f8,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing mixed bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba24e1af06001770c4f7",
}
g_str_5fb1b9dbe1af0600177094aa_camp='5fb1b9dbe1af0600177094aa_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094aa_camp]={
  id=g_str_5fb1b9dbe1af0600177094aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
