-- 5fb1b9f5e1af06001770a38c Nomadic Raider MFP Meso-American  899 to 400 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba43e1af06001770fd06_general='5fb1ba43e1af06001770fd06_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd06_general]={
  id=g_str_5fb1ba43e1af06001770fd06_general,
  name='Light Foot General',
  min=0,
  max=1,
  description='Well equipped or trained infantry',
  general=true,
  troop_type="Light Foot",
}
g_str_5fb1ba43e1af06001770fd06='5fb1ba43e1af06001770fd06'
g_base_definitions[g_str_5fb1ba43e1af06001770fd06]={
  id=g_str_5fb1ba43e1af06001770fd06,
  name='Light Foot',
  min=0,
  max=2,
  description='Well equipped or trained infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba43e1af06001770fd08='5fb1ba43e1af06001770fd08'
g_base_definitions[g_str_5fb1ba43e1af06001770fd08]={
  id=g_str_5fb1ba43e1af06001770fd08,
  name='Skirmishers',
  min=11,
  max=16,
  description='Hit-and-run unshielded fighters armed with substantial melee weapons',
  troop_type="Skirmishers",
}
g_str_5fb1ba43e1af06001770fd0a_general='5fb1ba43e1af06001770fd0a_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd0a_general]={
  id=g_str_5fb1ba43e1af06001770fd0a_general,
  name='Rabble General',
  min=0,
  max=1,
  description='Poorly-armed skirmishing foot',
  general=true,
  troop_type="Rabble",
}
g_str_5fb1ba43e1af06001770fd0a='5fb1ba43e1af06001770fd0a'
g_base_definitions[g_str_5fb1ba43e1af06001770fd0a]={
  id=g_str_5fb1ba43e1af06001770fd0a,
  name='Rabble',
  min=0,
  max=4,
  description='Poorly-armed skirmishing foot',
  troop_type="Rabble",
}
g_str_5fb1b9f5e1af06001770a38c_camp='5fb1b9f5e1af06001770a38c_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a38c_camp]={
  id=g_str_5fb1b9f5e1af06001770a38c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9f5e1af06001770a38c']={
  data={
    name='Nomadic Raider MFP Meso-American  899 to 400 BC'
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fd06_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd06],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd08],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd0a_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd0a],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a38c_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a38c"] = army["5fb1b9f5e1af06001770a38c"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Nomadic Raider MFP Meso-American  899 to 400 BC"] = army["5fb1b9f5e1af06001770a38c"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Nomadic Raider MFP Meso-American  899 to 400 BC"] = army["5fb1b9f5e1af06001770a38c"]
