-- 5fb1b9dfe1af06001770972a Maccabean Revolt and Maccabean Irregulars  168 to 104 BC

army['5fb1b9dfe1af06001770972a']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Maccabean Revolt and Maccabean Irregulars  168 to 104 BC',
    id='5fb1b9dfe1af06001770972a',
    dateRange={
      startDate=-168,
      endDate=-104,
    },
    ambush=true,  },
  g_base_definitions[g_str_615351a403385c0016b85f52_general],
  g_base_definitions[g_str_615351a403385c0016b85f52],
  g_base_definitions[g_str_615351a403385c0016b85f53_general],
  g_base_definitions[g_str_615351a403385c0016b85f53],
  g_base_definitions[g_str_615351a403385c0016b85f55],
  g_base_definitions[g_str_615351a403385c0016b85f57_general],
  g_base_definitions[g_str_615351a403385c0016b85f57],
  g_base_definitions[g_str_615351a403385c0016b85f59],
  g_base_definitions[g_str_5fb1b9dfe1af06001770972a_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770972a_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770972a"] = army["5fb1b9dfe1af06001770972a"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Maccabean Revolt and Maccabean Irregulars  168 to 104 BC"] = army["5fb1b9dfe1af06001770972a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Maccabean Revolt and Maccabean Irregulars  168 to 104 BC"] = army["5fb1b9dfe1af06001770972a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af06001770972a"] = {}
army_dates["5fb1b9dfe1af06001770972a"]["168 BC to 104 BC"] = {
  startDate=-168,
  endDate=-104
}
