g_str_5fb1ba2de1af06001770d571_general='5fb1ba2de1af06001770d571_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d571_general]={
  id=g_str_5fb1ba2de1af06001770d571_general,
  name='Warriors General',
  min=11,
  max=1,
  description='Fierce fighters armed with spears',
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba2de1af06001770d570",
}
g_str_5fb1ba2de1af06001770d571_general_dismounted_mobile_infantry='5fb1ba2de1af06001770d571_general_dismounted_mobile_infantry'
g_str_5fb1ba2de1af06001770d571_general_mounted_mobile_infantry='5fb1ba2de1af06001770d571_general_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba2de1af06001770d571_general_dismounted_mobile_infantry]={
  id=g_str_5fb1ba2de1af06001770d571_general_dismounted_mobile_infantry,
  name='Warriors General',
  min=0,
  max=1,
  description='Fierce fighters armed with spears\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba2de1af06001770d571_general_mounted_mobile_infantry,
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba2de1af06001770d570",
}
g_base_definitions[g_str_5fb1ba2de1af06001770d571_general_mounted_mobile_infantry]={
  id=g_str_5fb1ba2de1af06001770d571_general_mounted_mobile_infantry,
  name='Warriors General',
  min=0,
  max=1,
  description='Fierce fighters armed with spears\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba2de1af06001770d571_general_dismounted_mobile_infantry,
  general=true,
  mobile_infantry=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba2de1af06001770d570",
}
g_str_5fb1ba2de1af06001770d571='5fb1ba2de1af06001770d571'
g_base_definitions[g_str_5fb1ba2de1af06001770d571]={
  id=g_str_5fb1ba2de1af06001770d571,
  name='Warriors',
  min=11,
  max=16,
  description='Fierce fighters armed with spears',
  troop_type="Warriors",
  troop_option_id="5fb1ba2de1af06001770d570",
}
g_str_5fb1ba2de1af06001770d571_dismounted_mobile_infantry='5fb1ba2de1af06001770d571_dismounted_mobile_infantry'
g_str_5fb1ba2de1af06001770d571_mounted_mobile_infantry='5fb1ba2de1af06001770d571_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba2de1af06001770d571_dismounted_mobile_infantry]={
  id=g_str_5fb1ba2de1af06001770d571_dismounted_mobile_infantry,
  name='Warriors',
  min=0,
  max=3,
  description='Fierce fighters armed with spears\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba2de1af06001770d571_mounted_mobile_infantry,
  troop_type="Warriors",
  troop_option_id="5fb1ba2de1af06001770d570",
}
g_base_definitions[g_str_5fb1ba2de1af06001770d571_mounted_mobile_infantry]={
  id=g_str_5fb1ba2de1af06001770d571_mounted_mobile_infantry,
  name='Warriors',
  min=0,
  max=3,
  description='Fierce fighters armed with spears\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba2de1af06001770d571_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba2de1af06001770d570",
}
g_str_5fb1ba2de1af06001770d574='5fb1ba2de1af06001770d574'
g_base_definitions[g_str_5fb1ba2de1af06001770d574]={
  id=g_str_5fb1ba2de1af06001770d574,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2de1af06001770d573",
}
g_str_5fb1ba2de1af06001770d576='5fb1ba2de1af06001770d576'
g_base_definitions[g_str_5fb1ba2de1af06001770d576]={
  id=g_str_5fb1ba2de1af06001770d576,
  name='Light Foot',
  min=0,
  max=1,
  description='Javelinmen with shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2de1af06001770d575",
}
g_str_5fb1ba2de1af06001770d578='5fb1ba2de1af06001770d578'
g_base_definitions[g_str_5fb1ba2de1af06001770d578]={
  id=g_str_5fb1ba2de1af06001770d578,
  name='Horde',
  min=0,
  max=2,
  description='Throng',
  troop_type="Horde",
  troop_option_id="5fb1ba2de1af06001770d577",
}
g_str_5fb1ba2de1af06001770d57a='5fb1ba2de1af06001770d57a'
g_base_definitions[g_str_5fb1ba2de1af06001770d57a]={
  id=g_str_5fb1ba2de1af06001770d57a,
  name='Rabble',
  min=0,
  max=2,
  description='Unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba2de1af06001770d579",
}
g_str_5fb1b9e2e1af060017709910_camp='5fb1b9e2e1af060017709910_camp'
g_base_definitions[g_str_5fb1b9e2e1af060017709910_camp]={
  id=g_str_5fb1b9e2e1af060017709910_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
