troop_options['5fb1ba44e1af06001770feca'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
troop_options['5fb1ba44e1af06001770fecd'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
troop_options['5fb1ba44e1af06001770fecf'] = {
  min=4,
  max=6,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
troop_options['5fb1ba44e1af06001770fed1'] = {
  min=9,
  max=14,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
-- allies
