-- 5fb1b9dfe1af0600177096f4 Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba29e1af06001770cdc2_general='5fb1ba29e1af06001770cdc2_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cdc2_general]={
  id=g_str_5fb1ba29e1af06001770cdc2_general,
  name='Knights General',
  min=6,
  max=1,
  description='Lancers',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba29e1af06001770cdc2='5fb1ba29e1af06001770cdc2'
g_base_definitions[g_str_5fb1ba29e1af06001770cdc2]={
  id=g_str_5fb1ba29e1af06001770cdc2,
  name='Knights',
  min=6,
  max=12,
  description='Lancers',
  troop_type="Knights",
}
g_str_5fb1ba29e1af06001770cdc4='5fb1ba29e1af06001770cdc4'
g_base_definitions[g_str_5fb1ba29e1af06001770cdc4]={
  id=g_str_5fb1ba29e1af06001770cdc4,
  name='Horse Bow',
  min=0,
  max=1,
  description='Mounted scouts and skirmishing horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba29e1af06001770cdc6='5fb1ba29e1af06001770cdc6'
g_base_definitions[g_str_5fb1ba29e1af06001770cdc6]={
  id=g_str_5fb1ba29e1af06001770cdc6,
  name='Skirmishers',
  min=0,
  max=2,
  description='Peasant skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba29e1af06001770cdc8='5fb1ba29e1af06001770cdc8'
g_base_definitions[g_str_5fb1ba29e1af06001770cdc8]={
  id=g_str_5fb1ba29e1af06001770cdc8,
  name='Horde',
  min=0,
  max=2,
  description='Massed levy',
  troop_type="Horde",
}
g_str_5fb1b9dfe1af0600177096f4_camp='5fb1b9dfe1af0600177096f4_camp'
g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp]={
  id=g_str_5fb1b9dfe1af0600177096f4_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af0600177096f4_camp_fortified='5fb1b9dfe1af0600177096f4_camp_fortified'
g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp_fortified]={
  id=g_str_5fb1b9dfe1af0600177096f4_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9dfe1af0600177096f4']={
  data={
    name='Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc2_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc2],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc4],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc6],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc8],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af0600177096f4"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
