-- 5fb1b9dfe1af06001770970f Early Ptolemaic  320 to 275 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba29e1af06001770ce5b_general='5fb1ba29e1af06001770ce5b_general'
g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general]={
  id=g_str_5fb1ba29e1af06001770ce5b_general,
  name='Knights General',
  min=0,
  max=1,
  description='Xystophoroi',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770ce5a",
}
g_str_5fb1ba29e1af06001770ce5b_general_dismounted='5fb1ba29e1af06001770ce5b_general_dismounted'
g_str_5fb1ba29e1af06001770ce5b_general_mounted='5fb1ba29e1af06001770ce5b_general_mounted'
g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_dismounted]={
  id=g_str_5fb1ba29e1af06001770ce5b_general_dismounted,
  name='Pikes General',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounted from Knights General',
  points=4,
  dismounted_from=g_str_5fb1ba29e1af06001770ce5b_general_mounted,
  general=true,
  troop_type="Pikes",
  troop_option_id="5fb1ba29e1af06001770ce5a",
}
g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_mounted]={
  id=g_str_5fb1ba29e1af06001770ce5b_general_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounting as Pikes',
  points=4,
  dismount_as=g_str_5fb1ba29e1af06001770ce5b_general_dismounted,
  general=true,
  deployment_dismounting=true,
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770ce5a",
}
g_str_5fb1ba29e1af06001770ce5b='5fb1ba29e1af06001770ce5b'
g_base_definitions[g_str_5fb1ba29e1af06001770ce5b]={
  id=g_str_5fb1ba29e1af06001770ce5b,
  name='Knights',
  min=0,
  max=1,
  description='Xystophoroi',
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770ce5a",
}
g_str_5fb1ba29e1af06001770ce5b_dismounted='5fb1ba29e1af06001770ce5b_dismounted'
g_str_5fb1ba29e1af06001770ce5b_mounted='5fb1ba29e1af06001770ce5b_mounted'
g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_dismounted]={
  id=g_str_5fb1ba29e1af06001770ce5b_dismounted,
  name='Pikes',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounted from Knights',
  points=4,
  dismounted_from=g_str_5fb1ba29e1af06001770ce5b_mounted,
  troop_type="Pikes",
  troop_option_id="5fb1ba29e1af06001770ce5a",
}
g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_mounted]={
  id=g_str_5fb1ba29e1af06001770ce5b_mounted,
  name='Knights',
  min=0,
  max=1,
  description='Xystophoroi\nDeployment dismounting as Pikes',
  points=4,
  dismount_as=g_str_5fb1ba29e1af06001770ce5b_dismounted,
  deployment_dismounting=true,
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770ce5a",
}
g_str_5fb1ba29e1af06001770ce5e_general='5fb1ba29e1af06001770ce5e_general'
g_base_definitions[g_str_5fb1ba29e1af06001770ce5e_general]={
  id=g_str_5fb1ba29e1af06001770ce5e_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Greek mercenaries, Tarentines, or similar horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770ce5d",
}
g_str_5fb1ba29e1af06001770ce5e='5fb1ba29e1af06001770ce5e'
g_base_definitions[g_str_5fb1ba29e1af06001770ce5e]={
  id=g_str_5fb1ba29e1af06001770ce5e,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Greek mercenaries, Tarentines, or similar horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770ce5d",
}
g_str_5fb1ba29e1af06001770ce60_general='5fb1ba29e1af06001770ce60_general'
g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general]={
  id=g_str_5fb1ba29e1af06001770ce60_general,
  name='Pikes General',
  min=2,
  max=1,
  description='Phalanx',
  general=true,
  troop_type="Pikes",
  troop_option_id="5fb1ba29e1af06001770ce5f",
}
g_str_5fb1ba29e1af06001770ce60_general_elephant_screen='5fb1ba29e1af06001770ce60_general_elephant_screen'
g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general_elephant_screen]={
  id=g_str_5fb1ba29e1af06001770ce60_general_elephant_screen,
  name='Pikes General',
  min=2,
  max=1,
  description='Phalanx\nElephant Screen',
  general=true,
  elephant_screen=true,
  troop_type="Pikes",
  troop_option_id="5fb1ba29e1af06001770ce5f",
}
g_str_5fb1ba29e1af06001770ce60_general_elephant_screen_elephant_screen_counter='5fb1ba29e1af06001770ce60_general_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba29e1af06001770ce60_general_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=2,
  max=1,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba29e1af06001770ce60='5fb1ba29e1af06001770ce60'
g_base_definitions[g_str_5fb1ba29e1af06001770ce60]={
  id=g_str_5fb1ba29e1af06001770ce60,
  name='Pikes',
  min=2,
  max=8,
  description='Phalanx',
  troop_type="Pikes",
  troop_option_id="5fb1ba29e1af06001770ce5f",
}
g_str_5fb1ba29e1af06001770ce60_elephant_screen='5fb1ba29e1af06001770ce60_elephant_screen'
g_base_definitions[g_str_5fb1ba29e1af06001770ce60_elephant_screen]={
  id=g_str_5fb1ba29e1af06001770ce60_elephant_screen,
  name='Pikes',
  min=2,
  max=8,
  description='Phalanx\nElephant Screen',
  elephant_screen=true,
  troop_type="Pikes",
  troop_option_id="5fb1ba29e1af06001770ce5f",
}
g_str_5fb1ba29e1af06001770ce60_elephant_screen_elephant_screen_counter='5fb1ba29e1af06001770ce60_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba29e1af06001770ce60_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba29e1af06001770ce60_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=2,
  max=8,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba29e1af06001770ce63_general='5fb1ba29e1af06001770ce63_general'
g_base_definitions[g_str_5fb1ba29e1af06001770ce63_general]={
  id=g_str_5fb1ba29e1af06001770ce63_general,
  name='Light Foot General',
  min=3,
  max=1,
  description='Mercenary peltasts',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770ce62",
}
g_str_5fb1ba29e1af06001770ce63='5fb1ba29e1af06001770ce63'
g_base_definitions[g_str_5fb1ba29e1af06001770ce63]={
  id=g_str_5fb1ba29e1af06001770ce63,
  name='Light Foot',
  min=3,
  max=8,
  description='Mercenary peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770ce62",
}
g_str_5fb1ba29e1af06001770ce65_general='5fb1ba29e1af06001770ce65_general'
g_base_definitions[g_str_5fb1ba29e1af06001770ce65_general]={
  id=g_str_5fb1ba29e1af06001770ce65_general,
  name='Light Foot General',
  min=0,
  max=1,
  description='Thracian light infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770ce64",
}
g_str_5fb1ba29e1af06001770ce65='5fb1ba29e1af06001770ce65'
g_base_definitions[g_str_5fb1ba29e1af06001770ce65]={
  id=g_str_5fb1ba29e1af06001770ce65,
  name='Light Foot',
  min=0,
  max=1,
  description='Thracian light infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770ce64",
}
g_str_5fb1ba29e1af06001770ce68='5fb1ba29e1af06001770ce68'
g_base_definitions[g_str_5fb1ba29e1af06001770ce68]={
  id=g_str_5fb1ba29e1af06001770ce68,
  name='Elephants',
  min=0,
  max=1,
  description='Indian war elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba29e1af06001770ce66",
}
g_str_5fb1ba29e1af06001770ce6b='5fb1ba29e1af06001770ce6b'
g_base_definitions[g_str_5fb1ba29e1af06001770ce6b]={
  id=g_str_5fb1ba29e1af06001770ce6b,
  name='Skirmishers',
  min=0,
  max=2,
  description='Cretan skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba29e1af06001770ce6a",
}
g_str_5fb1ba29e1af06001770ce6d='5fb1ba29e1af06001770ce6d'
g_base_definitions[g_str_5fb1ba29e1af06001770ce6d]={
  id=g_str_5fb1ba29e1af06001770ce6d,
  name='Rabble',
  min=0,
  max=1,
  description='Garrisons and border guardsman',
  troop_type="Rabble",
  troop_option_id="5fb1ba29e1af06001770ce6c",
}
g_str_5fb1ba29e1af06001770ce6f='5fb1ba29e1af06001770ce6f'
g_base_definitions[g_str_5fb1ba29e1af06001770ce6f]={
  id=g_str_5fb1ba29e1af06001770ce6f,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt-shooters',
  troop_type="Artillery",
  troop_option_id="5fb1ba29e1af06001770ce6e",
}
g_str_5fb1b9dfe1af06001770970f_camp='5fb1b9dfe1af06001770970f_camp'
g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp]={
  id=g_str_5fb1b9dfe1af06001770970f_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af06001770970f_camp_fortified='5fb1b9dfe1af06001770970f_camp_fortified'
g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_fortified]={
  id=g_str_5fb1b9dfe1af06001770970f_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9dfe1af06001770970f_camp_pack_train='5fb1b9dfe1af06001770970f_camp_pack_train'
g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_pack_train]={
  id=g_str_5fb1b9dfe1af06001770970f_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dfe1af06001770970f']={
  data={
    name='Early Ptolemaic  320 to 275 BC',
    id='5fb1b9dfe1af06001770970f',
    army_id='5fb1b9dfe1af06001770970f'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5e_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5e],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general_elephant_screen],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_elephant_screen],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce63_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce63],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce65_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce65],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce68],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6b],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6d],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6f],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_fortified],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770970f"] = army["5fb1b9dfe1af06001770970f"]
army['5fb1b9dfe1af06001770970f_-320_-313']={
  data={
    name='Early Ptolemaic 320 BC to 313 BC',
    id='5fb1b9dfe1af06001770970f_-320_-313',
    army_id='5fb1b9dfe1af06001770970f'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5e_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5e],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general_elephant_screen],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_elephant_screen],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce63_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce63],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce65_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce65],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6b],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6d],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6f],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_fortified],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_pack_train],
}
army['5fb1b9dfe1af06001770970f_-312_-275']={
  data={
    name='Early Ptolemaic 312 BC to 275 BC',
    id='5fb1b9dfe1af06001770970f_-312_-275',
    army_id='5fb1b9dfe1af06001770970f'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_general_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5b_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5e_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce5e],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_general_elephant_screen],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce60_elephant_screen],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce63_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce63],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce65_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce65],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce68],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6b],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6d],
  g_base_definitions[g_str_5fb1ba29e1af06001770ce6f],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_fortified],
  g_base_definitions[g_str_5fb1b9dfe1af06001770970f_camp_pack_train],
}
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Ptolemaic  320 to 275 BC"] = army["5fb1b9dfe1af06001770970f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Ptolemaic  320 to 275 BC"] = army["5fb1b9dfe1af06001770970f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af06001770970f"] = {}
army_dates["5fb1b9dfe1af06001770970f"]["320 BC to 275 BC"] ="5fb1b9dfe1af06001770970f"
army_dates["5fb1b9dfe1af06001770970f"]["320 BC to 313 BC"] ="5fb1b9dfe1af06001770970f_-320_-313"
army_dates["5fb1b9dfe1af06001770970f"]["312 BC to 275 BC"] ="5fb1b9dfe1af06001770970f_-312_-275"
