-- 5fb1b9dce1af060017709557 Massilian  400 to 49 BC

army['5fb1b9dce1af060017709557']={
  data={
    name='Massilian  400 to 49 BC',
    id='5fb1b9dce1af060017709557',
    dateRange={
      startDate=-400,
      endDate=-49,
    }
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c779_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c779],
  g_base_definitions[g_str_5fb1ba26e1af06001770c77b],
  g_base_definitions[g_str_5fb1ba26e1af06001770c77d_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c77d],
  g_base_definitions[g_str_5fb1ba26e1af06001770c780],
  g_base_definitions[g_str_5fb1ba26e1af06001770c782],
  g_base_definitions[g_str_5fb1ba26e1af06001770c784],
  g_base_definitions[g_str_5fb1ba26e1af06001770c786],
  g_base_definitions[g_str_5fb1b9dce1af060017709557_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709557"] = army["5fb1b9dce1af060017709557"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Massilian  400 to 49 BC"] = army["5fb1b9dce1af060017709557"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Massilian  400 to 49 BC"] = army["5fb1b9dce1af060017709557"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Massilian  400 to 49 BC"] = army["5fb1b9dce1af060017709557"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709557"] = {}
army_dates["5fb1b9dce1af060017709557"]["400 BC to 49 BC"] = {
  startDate=-400,
  endDate=-49
}
