troop_options['5fb1ba3ae1af06001770ed24'] = {
  min=6,
  max=12,
  dateRange={
    startDate=890,
    endDate=1150,
  }
}
troop_options['5fb1ba3ae1af06001770ed26'] = {
  min=0,
  max=2,
  dateRange={
    startDate=890,
    endDate=1150,
  }
}
troop_options['5fb1ba3ae1af06001770ed28'] = {
  min=0,
  max=1,
  dateRange={
    startDate=890,
    endDate=1150,
  }
}
troop_options['5fb1ba3ae1af06001770ed2b'] = {
  min=0,
  max=2,
  dateRange={
    startDate=890,
    endDate=1150,
  }
}
troop_options['5fb1ba3ae1af06001770ed2d'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1008,
    endDate=1079,
  }
}
-- allies
