-- 5fb1b9eae1af060017709d8c Wallachian or Moldavian  1330 to 1517 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba36e1af06001770e5b6_general='5fb1ba36e1af06001770e5b6_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e5b6_general]={
  id=g_str_5fb1ba36e1af06001770e5b6_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Veteran horsemen',
  general=true,
  troop_type="Elite Cavalary",
}
g_str_5fb1ba36e1af06001770e5b6='5fb1ba36e1af06001770e5b6'
g_base_definitions[g_str_5fb1ba36e1af06001770e5b6]={
  id=g_str_5fb1ba36e1af06001770e5b6,
  name='Elite Cavalary',
  min=1,
  max=1,
  description='Veteran horsemen',
  troop_type="Elite Cavalary",
}
g_str_5fb1ba36e1af06001770e5b9='5fb1ba36e1af06001770e5b9'
g_base_definitions[g_str_5fb1ba36e1af06001770e5b9]={
  id=g_str_5fb1ba36e1af06001770e5b9,
  name='Knights',
  min=1,
  max=1,
  description='Boyars armed with lances and bows, some with partial plate armor',
  troop_type="Knights",
}
g_str_5fb1ba36e1af06001770e5bc='5fb1ba36e1af06001770e5bc'
g_base_definitions[g_str_5fb1ba36e1af06001770e5bc]={
  id=g_str_5fb1ba36e1af06001770e5bc,
  name='Knights',
  min=0,
  max=1,
  description='Italian men-at-arms and other mercenary "crusaders"',
  troop_type="Knights",
}
g_str_5fb1ba36e1af06001770e5be='5fb1ba36e1af06001770e5be'
g_base_definitions[g_str_5fb1ba36e1af06001770e5be]={
  id=g_str_5fb1ba36e1af06001770e5be,
  name='Horse Bow',
  min=2,
  max=4,
  description='Lesser boyars or viteji fighting as horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba36e1af06001770e5c0='5fb1ba36e1af06001770e5c0'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c0]={
  id=g_str_5fb1ba36e1af06001770e5c0,
  name='Elite Foot',
  min=0,
  max=1,
  description='Armored voynuks armed with polearms',
  troop_type="Elite Foot",
}
g_str_5fb1ba36e1af06001770e5c2='5fb1ba36e1af06001770e5c2'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c2]={
  id=g_str_5fb1ba36e1af06001770e5c2,
  name='Bow Levy',
  min=6,
  max=12,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba36e1af06001770e5c4='5fb1ba36e1af06001770e5c4'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c4]={
  id=g_str_5fb1ba36e1af06001770e5c4,
  name='Archers',
  min=0,
  max=3,
  description='Curteni bowmen',
  troop_type="Archers",
}
g_str_5fb1ba36e1af06001770e5c6='5fb1ba36e1af06001770e5c6'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c6]={
  id=g_str_5fb1ba36e1af06001770e5c6,
  name='Rabble',
  min=1,
  max=4,
  description='Rustici armed with spears, javelins, axes, halberds, flails, maces, and scythes',
  troop_type="Rabble",
}
g_str_5fb1ba36e1af06001770e5c7='5fb1ba36e1af06001770e5c7'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c7]={
  id=g_str_5fb1ba36e1af06001770e5c7,
  name='Light Foot',
  min=1,
  max=4,
  description='Rustici armed with spears, javelins, axes, halberds, flails, maces, and scythes',
  troop_type="Light Foot",
}
g_str_5fb1ba36e1af06001770e5c9='5fb1ba36e1af06001770e5c9'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c9]={
  id=g_str_5fb1ba36e1af06001770e5c9,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing crossbowmen or handgunners',
  troop_type="Skirmishers",
}
g_str_5fb1ba36e1af06001770e5cc='5fb1ba36e1af06001770e5cc'
g_base_definitions[g_str_5fb1ba36e1af06001770e5cc]={
  id=g_str_5fb1ba36e1af06001770e5cc,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
}
g_str_5fb1b9eae1af060017709d8c_camp='5fb1b9eae1af060017709d8c_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709d8c_camp]={
  name='Camp',
  id=g_str_5fb1b9eae1af060017709d8c_camp,
  min=1,
  max=1,
}
army['5fb1b9eae1af060017709d8c']={
  data={
    name='Wallachian or Moldavian  1330 to 1517 AD'
  },
  g_base_definitions[g_str_5fb1b9eae1af060017709d8c_camp],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5ce],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5b6_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5b6],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5bc],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5be],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5c0],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5c4],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5c6],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5c7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5c9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e5cc],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709d8c"] = army["5fb1b9eae1af060017709d8c"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Wallachian or Moldavian  1330 to 1517 AD"] = army["5fb1b9eae1af060017709d8c"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Wallachian or Moldavian  1330 to 1517 AD"] = army["5fb1b9eae1af060017709d8c"]
