-- 5fb1b9dfe1af0600177096f4 Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD

army['5fb1b9dfe1af0600177096f4']={
  data={
    name='Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD',
    id='5fb1b9dfe1af0600177096f4',
    army_id='5fb1b9dfe1af0600177096f4'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc2_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc2],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc4],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc6],
  g_base_definitions[g_str_5fb1ba29e1af06001770cdc8],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af0600177096f4"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Siracae, Iazyges, Later Rhoxolani Sarmatian  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af0600177096f4"] = {}
army_dates["5fb1b9dfe1af0600177096f4"]["310 BC to 375 AD"] ="5fb1b9dfe1af0600177096f4"
