-- 5fb1b9f5e1af06001770a405 Toltec Empire  930 to 1168 AD

army['5fb1b9f5e1af06001770a405']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Dry',
    },
    name='Toltec Empire  930 to 1168 AD',
    id='5fb1b9f5e1af06001770a405',
    dateRange={
      startDate=930,
      endDate=1168,
    },
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fdc9_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdc9],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdcb_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdcb],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdcd],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a405_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a405"] = army["5fb1b9f5e1af06001770a405"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Toltec Empire  930 to 1168 AD"] = army["5fb1b9f5e1af06001770a405"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Toltec Empire  930 to 1168 AD"] = army["5fb1b9f5e1af06001770a405"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Toltec Empire  930 to 1168 AD"] = army["5fb1b9f5e1af06001770a405"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a405"] = {}
army_dates["5fb1b9f5e1af06001770a405"]["930 AD to 1168 AD"] = {
  startDate=930,
  endDate=1168
}
