troop_options['5fb1ba38e1af06001770ea11'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1261,
    endDate=1384,
  }
}
troop_options['5fb1ba38e1af06001770ea13'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1261,
    endDate=1384,
  }
}
troop_options['5fb1ba38e1af06001770ea15'] = {
  min=2,
  max=3,
  dateRange={
    startDate=1261,
    endDate=1384,
  }
}
troop_options['5fb1ba38e1af06001770ea17'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1261,
    endDate=1384,
  }
}
troop_options['5fb1ba38e1af06001770ea19'] = {
  min=3,
  max=6,
  dateRange={
    startDate=1261,
    endDate=1384,
  }
}
troop_options['5fb1ba38e1af06001770ea1b'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1261,
    endDate=1384,
  }
}
troop_options['5fb1ba38e1af06001770ea1d'] = {
  min=0,
  max=10,
  dateRange={
    startDate=1261,
    endDate=1384,
  }
}
troop_options['5fb1ba38e1af06001770ea1f'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1261,
    endDate=1291,
  }
}
troop_options['5fb1ba38e1af06001770ea22'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1261,
    endDate=1320,
  }
}
troop_options['5fb1ba38e1af06001770ea25'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1321,
    endDate=1384,
  }
}
-- allies
