-- 5fb1b9f5e1af06001770a3e9 Later West Mexican  1401 to 1500 AD

army['5fb1b9f5e1af06001770a3e9']={
  data={
    name='Later West Mexican  1401 to 1500 AD',
    id='5fb1b9f5e1af06001770a3e9',
    dateRange={
      startDate=1401,
      endDate=1500,
    }
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fda3],
  g_base_definitions[g_str_5fb1ba44e1af06001770fda5_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fda5],
  g_base_definitions[g_str_5fb1ba44e1af06001770fda7],
  g_base_definitions[g_str_5fb1ba44e1af06001770fda9],
  g_base_definitions[g_str_5fb1ba44e1af06001770fdab],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3e9_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3e9"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Later West Mexican  1401 to 1500 AD"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Later West Mexican  1401 to 1500 AD"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later West Mexican  1401 to 1500 AD"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3e9"] = {}
army_dates["5fb1b9f5e1af06001770a3e9"]["1401 AD to 1500 AD"] = {
  startDate=1401,
  endDate=1500
}
