-- 5fb1b9e9e1af060017709d6f Hussite  1421 to 1471 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba35e1af06001770e534_general='5fb1ba35e1af06001770e534_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e534_general]={
  id=g_str_5fb1ba35e1af06001770e534_general,
  name='War Wagons General',
  min=3,
  max=1,
  description='War wagons manned by crossbowmen, handgunners, and light guns',
  general=true,
  troop_type="War Wagons",
}
g_str_5fb1ba35e1af06001770e534='5fb1ba35e1af06001770e534'
g_base_definitions[g_str_5fb1ba35e1af06001770e534]={
  id=g_str_5fb1ba35e1af06001770e534,
  name='War Wagons',
  min=3,
  max=6,
  description='War wagons manned by crossbowmen, handgunners, and light guns',
  troop_type="War Wagons",
}
g_str_5fb1ba35e1af06001770e536='5fb1ba35e1af06001770e536'
g_base_definitions[g_str_5fb1ba35e1af06001770e536]={
  id=g_str_5fb1ba35e1af06001770e536,
  name='Bad Horse',
  min=0,
  max=1,
  description='Crossbowmen on horses',
  troop_type="Bad Horse",
}
g_str_5fb1ba35e1af06001770e539='5fb1ba35e1af06001770e539'
g_base_definitions[g_str_5fb1ba35e1af06001770e539]={
  id=g_str_5fb1ba35e1af06001770e539,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Lithuanian horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba35e1af06001770e539_dismounted='5fb1ba35e1af06001770e539_dismounted'
g_base_definitions[g_str_5fb1ba35e1af06001770e539_dismounted]={
  id=g_str_5fb1ba35e1af06001770e539_dismounted,
  name='Archers',
  min=0,
  max=1,
  description='Lithuanian horsemen\nMid-battle dismounted from Javelin Cavalry',
  troop_type="Archers",
}
g_5fb1ba35e1af06001770e539_dismounted=g_base_definitions[g_str_5fb1ba35e1af06001770e539_dismounted]
g_str_5fb1ba35e1af06001770e539_mounted='5fb1ba35e1af06001770e539_mounted'
g_base_definitions[g_str_5fb1ba35e1af06001770e539_mounted]={
  id=g_str_5fb1ba35e1af06001770e539_mounted,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Lithuanian horsemen\nMid-battle dismounting as Archers',
  dismount_as=g_5fb1ba35e1af06001770e539_dismounted,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba35e1af06001770e53c_general='5fb1ba35e1af06001770e53c_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e53c_general]={
  id=g_str_5fb1ba35e1af06001770e53c_general,
  name='Heavy Foot General',
  min=4,
  max=1,
  description='Mixed flailmen and halberdiers',
  general=true,
  troop_type="Heavy Foot",
}
g_str_5fb1ba35e1af06001770e53c='5fb1ba35e1af06001770e53c'
g_base_definitions[g_str_5fb1ba35e1af06001770e53c]={
  id=g_str_5fb1ba35e1af06001770e53c,
  name='Heavy Foot',
  min=4,
  max=12,
  description='Mixed flailmen and halberdiers',
  troop_type="Heavy Foot",
}
g_str_5fb1ba35e1af06001770e53d_general='5fb1ba35e1af06001770e53d_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e53d_general]={
  id=g_str_5fb1ba35e1af06001770e53d_general,
  name='Elite Foot General',
  min=4,
  max=1,
  description='Mixed flailmen and halberdiers',
  general=true,
  troop_type="Elite Foot",
}
g_str_5fb1ba35e1af06001770e53d='5fb1ba35e1af06001770e53d'
g_base_definitions[g_str_5fb1ba35e1af06001770e53d]={
  id=g_str_5fb1ba35e1af06001770e53d,
  name='Elite Foot',
  min=4,
  max=12,
  description='Mixed flailmen and halberdiers',
  troop_type="Elite Foot",
}
g_str_5fb1ba35e1af06001770e53f_general='5fb1ba35e1af06001770e53f_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e53f_general]={
  id=g_str_5fb1ba35e1af06001770e53f_general,
  name='Knights General',
  min=0,
  max=1,
  description='Hussite men-at-arms',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba35e1af06001770e53f='5fb1ba35e1af06001770e53f'
g_base_definitions[g_str_5fb1ba35e1af06001770e53f]={
  id=g_str_5fb1ba35e1af06001770e53f,
  name='Knights',
  min=0,
  max=1,
  description='Hussite men-at-arms',
  troop_type="Knights",
}
g_str_5fb1ba35e1af06001770e541='5fb1ba35e1af06001770e541'
g_base_definitions[g_str_5fb1ba35e1af06001770e541]={
  id=g_str_5fb1ba35e1af06001770e541,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards and houfnice and trebuchet',
  troop_type="Artillery",
}
g_str_5fb1b9e9e1af060017709d6f_camp='5fb1b9e9e1af060017709d6f_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d6f_camp]={
  id=g_str_5fb1b9e9e1af060017709d6f_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e9e1af060017709d6f']={
  data={
    name='Hussite  1421 to 1471 AD'
  },
  g_base_definitions[g_str_5fb1ba35e1af06001770e534_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e534],
  g_base_definitions[g_str_5fb1ba35e1af06001770e536],
  g_base_definitions[g_str_5fb1ba35e1af06001770e539],
  g_base_definitions[g_str_5fb1ba35e1af06001770e539_mounted],
  g_base_definitions[g_str_5fb1ba35e1af06001770e539_dismounted],
  g_base_definitions[g_str_5fb1ba35e1af06001770e53c_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e53c],
  g_base_definitions[g_str_5fb1ba35e1af06001770e53d_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e53d],
  g_base_definitions[g_str_5fb1ba35e1af06001770e53f_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e53f],
  g_base_definitions[g_str_5fb1ba35e1af06001770e541],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d6f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d6f"] = army["5fb1b9e9e1af060017709d6f"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Hussite  1421 to 1471 AD"] = army["5fb1b9e9e1af060017709d6f"]
