troop_options['5fb1ba3ee1af06001770f535'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-770,
    endDate=-550,
  }
}
troop_options['5fb1ba3ee1af06001770f537'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-770,
    endDate=-550,
  }
}
troop_options['5fb1ba3ee1af06001770f53b'] = {
  min=6,
  max=14,
  dateRange={
    startDate=-770,
    endDate=-550,
  }
}
troop_options['5fb1ba3ee1af06001770f53d'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-770,
    endDate=-550,
  }
}
-- allies
