-- 5fb1b9eee1af060017709fd2 Lusignan Cypriot  1192 to 1489 AD

army['5fb1b9eee1af060017709fd2']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Lusignan Cypriot  1192 to 1489 AD',
    id='5fb1b9eee1af060017709fd2',
    dateRange={
      startDate=1192,
      endDate=1489,
    },
  },
  g_base_definitions[g_str_615351b103385c0016b87fcf_general],
  g_base_definitions[g_str_615351b103385c0016b87fcf],
  g_base_definitions[g_str_615351b103385c0016b87fd2_general],
  g_base_definitions[g_str_615351b103385c0016b87fd2],
  g_base_definitions[g_str_615351b103385c0016b87fd4],
  g_base_definitions[g_str_615351b103385c0016b87fd7_general],
  g_base_definitions[g_str_615351b103385c0016b87fd7],
  g_base_definitions[g_str_615351b103385c0016b87fda_general],
  g_base_definitions[g_str_615351b103385c0016b87fda],
  g_base_definitions[g_str_615351b103385c0016b87fdc],
  g_base_definitions[g_str_615351b103385c0016b87fde_general],
  g_base_definitions[g_str_615351b103385c0016b87fde],
  g_base_definitions[g_str_615351b103385c0016b87fe0],
  g_base_definitions[g_str_615351b103385c0016b87fe2],
  g_base_definitions[g_str_615351b103385c0016b87fe4],
  g_base_definitions[g_str_615351b103385c0016b87fe7],
  g_base_definitions[g_str_615351b103385c0016b87fea],
  g_base_definitions[g_str_615351b103385c0016b87fed],
  g_base_definitions[g_str_615351b103385c0016b87ff0],
  g_base_definitions[g_str_615351b103385c0016b87ff3],
  g_base_definitions[g_str_615351b103385c0016b87ff4],
  g_base_definitions[g_str_5fb1b9eee1af060017709fd2_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af060017709fd2"] = army["5fb1b9eee1af060017709fd2"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Lusignan Cypriot  1192 to 1489 AD"] = army["5fb1b9eee1af060017709fd2"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Lusignan Cypriot  1192 to 1489 AD"] = army["5fb1b9eee1af060017709fd2"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Lusignan Cypriot  1192 to 1489 AD"] = army["5fb1b9eee1af060017709fd2"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Lusignan Cypriot  1192 to 1489 AD"] = army["5fb1b9eee1af060017709fd2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Lusignan Cypriot  1192 to 1489 AD"] = army["5fb1b9eee1af060017709fd2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af060017709fd2"] = {}
army_dates["5fb1b9eee1af060017709fd2"]["1192 AD to 1489 AD"] = {
  startDate=1192,
  endDate=1489
}
army_dates["5fb1b9eee1af060017709fd2"]["1192 AD to 1249 AD"] = {
  startDate=1192,
  endDate=1249
}
army_dates["5fb1b9eee1af060017709fd2"]["1250 AD to 1356 AD"] = {
  startDate=1250,
  endDate=1356
}
army_dates["5fb1b9eee1af060017709fd2"]["1357 AD to 1364 AD"] = {
  startDate=1357,
  endDate=1364
}
army_dates["5fb1b9eee1af060017709fd2"]["1365 AD"] = {
  startDate=1365,
  endDate=1365
}
army_dates["5fb1b9eee1af060017709fd2"]["1366 AD to 1410 AD"] = {
  startDate=1366,
  endDate=1410
}
army_dates["5fb1b9eee1af060017709fd2"]["1411 AD to 1459 AD"] = {
  startDate=1411,
  endDate=1459
}
army_dates["5fb1b9eee1af060017709fd2"]["1460 AD to 1464 AD"] = {
  startDate=1460,
  endDate=1464
}
army_dates["5fb1b9eee1af060017709fd2"]["1465 AD to 1489 AD"] = {
  startDate=1465,
  endDate=1489
}
