-- 5fb1b9d9e1af06001770930d Middle Elam  1400 to 800 BC

army['5fb1b9d9e1af06001770930d']={
  data={
    invasionRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Middle Elam  1400 to 800 BC',
    id='5fb1b9d9e1af06001770930d',
    dateRange={
      startDate=-1400,
      endDate=-800,
    }
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bef9_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bef9],
  g_base_definitions[g_str_5fb1ba1fe1af06001770befb],
  g_base_definitions[g_str_5fb1b9d9e1af06001770930d_camp],
  g_base_definitions[g_str_5fb1b9d9e1af06001770930d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af06001770930d"] = army["5fb1b9d9e1af06001770930d"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Middle Elam  1400 to 800 BC"] = army["5fb1b9d9e1af06001770930d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Middle Elam  1400 to 800 BC"] = army["5fb1b9d9e1af06001770930d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af06001770930d"] = {}
army_dates["5fb1b9d9e1af06001770930d"]["1400 BC to 800 BC"] = {
  startDate=-1400,
  endDate=-800
}
army_dates["5fb1b9d9e1af06001770930d"]["1400 BC to 950 BC"] = {
  startDate=-1400,
  endDate=-950
}
army_dates["5fb1b9d9e1af06001770930d"]["949 BC to 800 BC"] = {
  startDate=-949,
  endDate=-800
}
