troop_options['615351ae03385c0016b8769f'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1200,
    endDate=1227,
  }
}
troop_options['615351ae03385c0016b876a2'] = {
  min=8,
  max=14,
  dateRange={
    startDate=1200,
    endDate=1227,
  }
}
troop_options['615351ae03385c0016b876a4'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1200,
    endDate=1227,
  }
}
troop_options['615351ae03385c0016b876a7'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1200,
    endDate=1227,
  }
}
-- allies
