-- 5fb1b9dee1af0600177096b3 Early Galatian  280 to 228 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba29e1af06001770cce3']= {
  min=1,
  max=2,
  description='Noble horsemen',
}
g_troop_entry['5fb1ba29e1af06001770cce4']= {
  troop_option='5fb1ba29e1af06001770cce3',
  troopTypeCode='JCV',
}
g_troop_option['5fb1ba29e1af06001770cce5']= {
  min=1,
  max=3,
  description='Mounted attendants',
}
g_troop_entry['5fb1ba29e1af06001770cce6']= {
  troop_option='5fb1ba29e1af06001770cce5',
  troopTypeCode='BAD',
}
g_troop_option['5fb1ba29e1af06001770cce7']= {
  min=0,
  max=1,
  description='Mobile battle platforms',
}
g_troop_entry['5fb1ba29e1af06001770cce8']= {
  troop_option='5fb1ba29e1af06001770cce7',
  troopTypeCode='BTX',
}
g_troop_option['5fb1ba29e1af06001770cce9']= {
  min=6,
  max=13,
  description='Fierce fighters',
  core='all',
}
g_troop_entry['5fb1ba29e1af06001770ccea']= {
  troop_option='5fb1ba29e1af06001770cce9',
  troopTypeCode='WRR',
}
g_troop_option['5fb1ba29e1af06001770cceb']= {
  min=0,
  max=2,
  description='Javelinmen',
}
g_troop_entry['5fb1ba29e1af06001770ccec']= {
  troop_option='5fb1ba29e1af06001770cceb',
  troopTypeCode='RBL',
}
g_str_5fb1ba29e1af06001770cce4_general='5fb1ba29e1af06001770cce4_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cce4_general]={
  id=g_str_5fb1ba29e1af06001770cce4_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba29e1af06001770cce4='5fb1ba29e1af06001770cce4'
g_base_definitions[g_str_5fb1ba29e1af06001770cce4]={
  id=g_str_5fb1ba29e1af06001770cce4,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Noble horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba29e1af06001770cce6='5fb1ba29e1af06001770cce6'
g_base_definitions[g_str_5fb1ba29e1af06001770cce6]={
  id=g_str_5fb1ba29e1af06001770cce6,
  name='Bad Horse',
  min=1,
  max=3,
  description='Mounted attendants',
  troop_type="Bad Horse",
}
g_str_5fb1ba29e1af06001770cce8_general='5fb1ba29e1af06001770cce8_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cce8_general]={
  id=g_str_5fb1ba29e1af06001770cce8_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='Mobile battle platforms',
  general=true,
  troop_type="Battle Taxi",
}
g_str_5fb1ba29e1af06001770cce8='5fb1ba29e1af06001770cce8'
g_base_definitions[g_str_5fb1ba29e1af06001770cce8]={
  id=g_str_5fb1ba29e1af06001770cce8,
  name='Battle Taxi',
  min=0,
  max=1,
  description='Mobile battle platforms',
  troop_type="Battle Taxi",
}
g_str_5fb1ba29e1af06001770ccea='5fb1ba29e1af06001770ccea'
g_base_definitions[g_str_5fb1ba29e1af06001770ccea]={
  id=g_str_5fb1ba29e1af06001770ccea,
  name='Warriors',
  min=6,
  max=13,
  description='Fierce fighters',
  troop_type="Warriors",
}
g_str_5fb1ba29e1af06001770ccec='5fb1ba29e1af06001770ccec'
g_base_definitions[g_str_5fb1ba29e1af06001770ccec]={
  id=g_str_5fb1ba29e1af06001770ccec,
  name='Rabble',
  min=0,
  max=2,
  description='Javelinmen',
  troop_type="Rabble",
}
g_str_5fb1b9dee1af0600177096b3_camp='5fb1b9dee1af0600177096b3_camp'
g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp]={
  id=g_str_5fb1b9dee1af0600177096b3_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dee1af0600177096b3_camp_pack_train='5fb1b9dee1af0600177096b3_camp_pack_train'
g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp_pack_train]={
  id=g_str_5fb1b9dee1af0600177096b3_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dee1af0600177096b3']={
  data={
    name='Early Galatian  280 to 228 BC',
    id='5fb1b9dee1af0600177096b3',
    army_id='5fb1b9dee1af0600177096b3'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce6],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccea],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccec],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096b3"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096b3"] = {}
army_dates["5fb1b9dee1af0600177096b3"]["280 BC to 228 BC"] ="5fb1b9dee1af0600177096b3"
