troop_options['5fb1ba25e1af06001770c5cd'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5cf'] = {
  min=6,
  max=16,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5d1'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5d3'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5d5'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5d7'] = {
  min=0,
  max=6,
  dateRange={
    startDate=-461,
    endDate=-461,
  }
}
troop_options['5fb1ba25e1af06001770c5da'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
-- allies
