troop_options['5fb1ba1ee1af06001770be47'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-2028,
    endDate=-1460,
  }
}
troop_options['5fb1ba1ee1af06001770be4a'] = {
  min=3,
  max=10,
  dateRange={
    startDate=-2028,
    endDate=-1460,
  }
}
troop_options['5fb1ba1ee1af06001770be4e'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-2028,
    endDate=-1460,
  }
}
troop_options['5fb1ba1ee1af06001770be50'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-2028,
    endDate=-1460,
  }
}
troop_options['5fb1ba1ee1af06001770be52'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-2028,
    endDate=-1460,
  }
}
troop_options['5fb1ba1ee1af06001770be54'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-2028,
    endDate=-1460,
  }
}
troop_options['5fb1ba1ee1af06001770be56'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-2017,
    endDate=-1794,
  }
}
-- allies
