-- 5fb1b9dbe1af0600177094b0 Sardinian  1000 to 50 BC

army['5fb1b9dbe1af0600177094b0']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Sardinian  1000 to 50 BC',
    id='5fb1b9dbe1af0600177094b0',
    dateRange={
      startDate=-1000,
      endDate=-50,
    },
  },
  g_base_definitions[g_str_615351a103385c0016b85506_general],
  g_base_definitions[g_str_615351a103385c0016b85506],
  g_base_definitions[g_str_615351a103385c0016b85508_general],
  g_base_definitions[g_str_615351a103385c0016b85508],
  g_base_definitions[g_str_615351a103385c0016b8550a],
  g_base_definitions[g_str_615351a103385c0016b8550c],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094b0_camp],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094b0_camp_fortified],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094b0_camp_pack_train],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094b0_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094b0"] = army["5fb1b9dbe1af0600177094b0"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Sardinian  1000 to 50 BC"] = army["5fb1b9dbe1af0600177094b0"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Sardinian  1000 to 50 BC"] = army["5fb1b9dbe1af0600177094b0"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sardinian  1000 to 50 BC"] = army["5fb1b9dbe1af0600177094b0"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094b0"] = {}
army_dates["5fb1b9dbe1af0600177094b0"]["1000 BC to 50 BC"] = {
  startDate=-1000,
  endDate=-50
}
army_dates["5fb1b9dbe1af0600177094b0"]["1000 BC to 665 BC"] = {
  startDate=-1000,
  endDate=-665
}
army_dates["5fb1b9dbe1af0600177094b0"]["664 BC to 525 BC"] = {
  startDate=-664,
  endDate=-525
}
army_dates["5fb1b9dbe1af0600177094b0"]["524 BC to 351 BC"] = {
  startDate=-524,
  endDate=-351
}
army_dates["5fb1b9dbe1af0600177094b0"]["350 BC to 50 BC"] = {
  startDate=-350,
  endDate=-50
}
