troop_options['615351a903385c0016b86ad0'] = {
  min=1,
  max=2,
  dateRange={
    startDate=896,
    endDate=1003,
  }
}
troop_options['615351a903385c0016b86ad3'] = {
  min=1,
  max=2,
  dateRange={
    startDate=896,
    endDate=1003,
  }
}
troop_options['615351a903385c0016b86ad5'] = {
  min=1,
  max=2,
  dateRange={
    startDate=896,
    endDate=1003,
  }
}
troop_options['615351a903385c0016b86ad7'] = {
  min=5,
  max=9,
  dateRange={
    startDate=896,
    endDate=1003,
  }
}
troop_options['615351a903385c0016b86ad9'] = {
  min=0,
  max=2,
  dateRange={
    startDate=896,
    endDate=1003,
  }
}
-- allies
