-- 5fb1b9efe1af06001770a05c Qara-Khitan  1124 to 1211 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba3ce1af06001770f1a4']= {
  min=0,
  max=1,
  description='Bodyguard',
  core='all',
}
g_str_5fb1ba3ce1af06001770f1a5_general='5fb1ba3ce1af06001770f1a5_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5_general]={
  id=g_str_5fb1ba3ce1af06001770f1a5_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Bodyguard',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f1a4",
}
g_str_5fb1ba3ce1af06001770f1a5='5fb1ba3ce1af06001770f1a5'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5]={
  id=g_str_5fb1ba3ce1af06001770f1a5,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Bodyguard',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f1a4",
}
g_troop_option['5fb1ba3ce1af06001770f1a6']= {
  min=0,
  max=1,
  description='Tribal horsemen with armored horses',
  core='all',
}
g_str_5fb1ba3ce1af06001770f1a7_general='5fb1ba3ce1af06001770f1a7_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7_general]={
  id=g_str_5fb1ba3ce1af06001770f1a7_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Tribal horsemen with armored horses',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f1a6",
}
g_str_5fb1ba3ce1af06001770f1a7='5fb1ba3ce1af06001770f1a7'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7]={
  id=g_str_5fb1ba3ce1af06001770f1a7,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Tribal horsemen with armored horses',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f1a6",
}
g_troop_option['5fb1ba3ce1af06001770f1a8']= {
  min=6,
  max=11,
  description='Tribal standing-army horse archers',
}
g_str_5fb1ba3ce1af06001770f1a9_general='5fb1ba3ce1af06001770f1a9_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9_general]={
  id=g_str_5fb1ba3ce1af06001770f1a9_general,
  name='Horse Bow General',
  min=6,
  max=1,
  description='Tribal standing-army horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3ce1af06001770f1a8",
}
g_str_5fb1ba3ce1af06001770f1a9='5fb1ba3ce1af06001770f1a9'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9]={
  id=g_str_5fb1ba3ce1af06001770f1a9,
  name='Horse Bow',
  min=6,
  max=11,
  description='Tribal standing-army horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3ce1af06001770f1a8",
}
g_troop_option['5fb1ba3ce1af06001770f1aa']= {
  min=1,
  max=4,
  description='Qarluq nobles and horse archers',
  startDate=1132,
  endDate=1210,
}
g_str_5fb1ba3ce1af06001770f1ac_general='5fb1ba3ce1af06001770f1ac_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac_general]={
  id=g_str_5fb1ba3ce1af06001770f1ac_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Qarluq nobles and horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3ce1af06001770f1aa",
}
g_str_5fb1ba3ce1af06001770f1ac='5fb1ba3ce1af06001770f1ac'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac]={
  id=g_str_5fb1ba3ce1af06001770f1ac,
  name='Horse Bow',
  min=1,
  max=4,
  description='Qarluq nobles and horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3ce1af06001770f1aa",
}
g_troop_option['5fb1ba3ce1af06001770f1ad']= {
  min=0,
  max=1,
  description='City militia',
  core='all',
}
g_str_5fb1ba3ce1af06001770f1ae='5fb1ba3ce1af06001770f1ae'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1ae]={
  id=g_str_5fb1ba3ce1af06001770f1ae,
  name='Bow Levy',
  min=0,
  max=1,
  description='City militia',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3ce1af06001770f1ad",
}
g_troop_option['5fb1ba3ce1af06001770f1af']= {
  min=0,
  max=1,
  description='Subject levy',
  core='all',
}
g_str_5fb1ba3ce1af06001770f1b0='5fb1ba3ce1af06001770f1b0'
g_base_definitions[g_str_5fb1ba3ce1af06001770f1b0]={
  id=g_str_5fb1ba3ce1af06001770f1b0,
  name='Horde',
  min=0,
  max=1,
  description='Subject levy',
  troop_type="Horde",
  troop_option_id="5fb1ba3ce1af06001770f1af",
}
g_str_5fb1b9efe1af06001770a05c_camp='5fb1b9efe1af06001770a05c_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp]={
  id=g_str_5fb1b9efe1af06001770a05c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9efe1af06001770a05c_camp_pack_train='5fb1b9efe1af06001770a05c_camp_pack_train'
g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp_pack_train]={
  id=g_str_5fb1b9efe1af06001770a05c_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9efe1af06001770a05c']={
  data={
    name='Qara-Khitan  1124 to 1211 AD',
    id='5fb1b9efe1af06001770a05c',
    army_id='5fb1b9efe1af06001770a05c'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ae],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1b0],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a05c"] = army["5fb1b9efe1af06001770a05c"]
army['5fb1b9efe1af06001770a05c_1124_1131']={
  data={
    name='Qara-Khitan 1124 AD to 1131 AD',
    id='5fb1b9efe1af06001770a05c_1124_1131',
    army_id='5fb1b9efe1af06001770a05c'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ae],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1b0],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp_pack_train],
}
army['5fb1b9efe1af06001770a05c_1132_1210']={
  data={
    name='Qara-Khitan 1132 AD to 1210 AD',
    id='5fb1b9efe1af06001770a05c_1132_1210',
    army_id='5fb1b9efe1af06001770a05c'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ae],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1b0],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp_pack_train],
}
army['5fb1b9efe1af06001770a05c_1211_1211']={
  data={
    name='Qara-Khitan 1211 AD',
    id='5fb1b9efe1af06001770a05c_1211_1211',
    army_id='5fb1b9efe1af06001770a05c'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ae],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1b0],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp_pack_train],
}
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Qara-Khitan  1124 to 1211 AD"] = army["5fb1b9efe1af06001770a05c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Qara-Khitan  1124 to 1211 AD"] = army["5fb1b9efe1af06001770a05c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a05c"] = {}
army_dates["5fb1b9efe1af06001770a05c"]["1124 AD to 1211 AD"] ="5fb1b9efe1af06001770a05c"
army_dates["5fb1b9efe1af06001770a05c"]["1124 AD to 1131 AD"] ="5fb1b9efe1af06001770a05c_1124_1131"
army_dates["5fb1b9efe1af06001770a05c"]["1132 AD to 1210 AD"] ="5fb1b9efe1af06001770a05c_1132_1210"
army_dates["5fb1b9efe1af06001770a05c"]["1211 AD"] ="5fb1b9efe1af06001770a05c_1211_1211"
