-- 5fb1b9dbe1af0600177094e9 Early Hoplite Greek: Thessalian  669 to 449 BC

army['5fb1b9dbe1af0600177094e9']={
  data={
    name='Early Hoplite Greek: Thessalian  669 to 449 BC',
    id='5fb1b9dbe1af0600177094e9',
    army_id='5fb1b9dbe1af0600177094e9'
  },
  g_base_definitions[g_str_5fb1ba25e1af06001770c5ad_general],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5ad],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5af],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5b1],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5b3],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094e9_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094e9"] = army["5fb1b9dbe1af0600177094e9"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Hoplite Greek: Thessalian  669 to 449 BC"] = army["5fb1b9dbe1af0600177094e9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hoplite Greek: Thessalian  669 to 449 BC"] = army["5fb1b9dbe1af0600177094e9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094e9"] = {}
army_dates["5fb1b9dbe1af0600177094e9"]["669 BC to 449 BC"] ="5fb1b9dbe1af0600177094e9"
