-- 5fb1b9f3e1af06001770a2a9 Xixia (all mounted)  982 to 1227 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba40e1af06001770f9ce='5fb1ba40e1af06001770f9ce'
g_base_definitions[g_str_5fb1ba40e1af06001770f9ce]={
  id=g_str_5fb1ba40e1af06001770f9ce,
  name='Cataphracts',
  min=0,
  max=2,
  description='Tangut Iron Sparrowhawk  horsemen',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba40e1af06001770f9cd",
}
g_str_5fb1ba40e1af06001770f9ce_dismounted='5fb1ba40e1af06001770f9ce_dismounted'
g_base_definitions[g_str_5fb1ba40e1af06001770f9ce_dismounted]={
  id=g_str_5fb1ba40e1af06001770f9ce_dismounted,
  name='Elite Foot',
  min=0,
  max=2,
  description='Tangut Iron Sparrowhawk  horsemen\nDeployment dismounted from Cataphracts',
  points=4,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba40e1af06001770f9cd",
}
g_5fb1ba40e1af06001770f9ce_dismounted=g_base_definitions[g_str_5fb1ba40e1af06001770f9ce_dismounted]
g_str_5fb1ba40e1af06001770f9ce_mounted='5fb1ba40e1af06001770f9ce_mounted'
g_base_definitions[g_str_5fb1ba40e1af06001770f9ce_mounted]={
  id=g_str_5fb1ba40e1af06001770f9ce_mounted,
  name='Cataphracts',
  min=0,
  max=2,
  description='Tangut Iron Sparrowhawk  horsemen\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba40e1af06001770f9ce_dismounted,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba40e1af06001770f9cd",
}
g_str_5fb1ba40e1af06001770f9d1_general='5fb1ba40e1af06001770f9d1_general'
g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general]={
  id=g_str_5fb1ba40e1af06001770f9d1_general,
  name='Elite Cavalary General',
  min=4,
  max=1,
  description='Tangut nomad horsemen',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba40e1af06001770f9d0",
}
g_str_5fb1ba40e1af06001770f9d1_general_dismounted='5fb1ba40e1af06001770f9d1_general_dismounted'
g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general_dismounted]={
  id=g_str_5fb1ba40e1af06001770f9d1_general_dismounted,
  name='Archers General',
  min=4,
  max=1,
  description='Tangut nomad horsemen\nDeployment dismounted from Elite Cavalary General',
  points=4,
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba40e1af06001770f9d0",
}
g_5fb1ba40e1af06001770f9d1_general_dismounted=g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general_dismounted]
g_str_5fb1ba40e1af06001770f9d1_general_mounted='5fb1ba40e1af06001770f9d1_general_mounted'
g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general_mounted]={
  id=g_str_5fb1ba40e1af06001770f9d1_general_mounted,
  name='Elite Cavalary General',
  min=4,
  max=1,
  description='Tangut nomad horsemen\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_5fb1ba40e1af06001770f9d1_general_dismounted,
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba40e1af06001770f9d0",
}
g_str_5fb1ba40e1af06001770f9d1='5fb1ba40e1af06001770f9d1'
g_base_definitions[g_str_5fb1ba40e1af06001770f9d1]={
  id=g_str_5fb1ba40e1af06001770f9d1,
  name='Elite Cavalary',
  min=4,
  max=8,
  description='Tangut nomad horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba40e1af06001770f9d0",
}
g_str_5fb1ba40e1af06001770f9d1_dismounted='5fb1ba40e1af06001770f9d1_dismounted'
g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_dismounted]={
  id=g_str_5fb1ba40e1af06001770f9d1_dismounted,
  name='Archers',
  min=4,
  max=8,
  description='Tangut nomad horsemen\nDeployment dismounted from Elite Cavalary',
  points=4,
  troop_type="Archers",
  troop_option_id="5fb1ba40e1af06001770f9d0",
}
g_5fb1ba40e1af06001770f9d1_dismounted=g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_dismounted]
g_str_5fb1ba40e1af06001770f9d1_mounted='5fb1ba40e1af06001770f9d1_mounted'
g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_mounted]={
  id=g_str_5fb1ba40e1af06001770f9d1_mounted,
  name='Elite Cavalary',
  min=4,
  max=8,
  description='Tangut nomad horsemen\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_5fb1ba40e1af06001770f9d1_dismounted,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba40e1af06001770f9d0",
}
g_str_5fb1ba40e1af06001770f9d4='5fb1ba40e1af06001770f9d4'
g_base_definitions[g_str_5fb1ba40e1af06001770f9d4]={
  id=g_str_5fb1ba40e1af06001770f9d4,
  name='Horse Bow',
  min=3,
  max=6,
  description='Tangut settled horse archers and nomad scouts',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba40e1af06001770f9d3",
}
g_str_5fb1b9f3e1af06001770a2a9_camp='5fb1b9f3e1af06001770a2a9_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp]={
  id=g_str_5fb1b9f3e1af06001770a2a9_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2a9_camp_fortified='5fb1b9f3e1af06001770a2a9_camp_fortified'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp_fortified]={
  id=g_str_5fb1b9f3e1af06001770a2a9_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9f3e1af06001770a2a9']={
  data={
    name='Xixia (all mounted)  982 to 1227 AD'
  },
  g_base_definitions[g_str_5fb1ba40e1af06001770f9ce],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9ce_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9ce_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d4],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2a9"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Xixia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Xixia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
