troop_options['5fb1ba2ce1af06001770d40b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=200,
    endDate=407,
  }
}
troop_options['5fb1ba2ce1af06001770d40e'] = {
  min=8,
  max=16,
  dateRange={
    startDate=200,
    endDate=407,
  }
}
troop_options['5fb1ba2ce1af06001770d410'] = {
  min=0,
  max=1,
  dateRange={
    startDate=200,
    endDate=407,
  }
}
troop_options['5fb1ba2ce1af06001770d412'] = {
  min=0,
  max=4,
  dateRange={
    startDate=200,
    endDate=407,
  }
}
-- allies
