-- 5fb1b9f5e1af06001770a3a3 Preclassic Maya  400 BC to 200 AD

army['5fb1b9f5e1af06001770a3a3']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Preclassic Maya  400 BC to 200 AD',
    id='5fb1b9f5e1af06001770a3a3',
    dateRange={
      startDate=-400,
      endDate=200,
    },
  },
  g_base_definitions[g_str_615351b603385c0016b88d8c_general],
  g_base_definitions[g_str_615351b603385c0016b88d8c],
  g_base_definitions[g_str_615351b603385c0016b88d8e],
  g_base_definitions[g_str_615351b603385c0016b88d90],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3a3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3a3"] = army["5fb1b9f5e1af06001770a3a3"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Preclassic Maya  400 BC to 200 AD"] = army["5fb1b9f5e1af06001770a3a3"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Preclassic Maya  400 BC to 200 AD"] = army["5fb1b9f5e1af06001770a3a3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Preclassic Maya  400 BC to 200 AD"] = army["5fb1b9f5e1af06001770a3a3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3a3"] = {}
army_dates["5fb1b9f5e1af06001770a3a3"]["400 BC to 200 AD"] = {
  startDate=-400,
  endDate=200
}
