troop_options['615351a603385c0016b864ee'] = {
  min=4,
  max=8,
  dateRange={
    startDate=401,
    endDate=406,
  }
}
troop_options['615351a603385c0016b864f0'] = {
  min=0,
  max=10,
  dateRange={
    startDate=401,
    endDate=406,
  }
}
troop_options['615351a603385c0016b864f2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=401,
    endDate=406,
  }
}
troop_options['615351a603385c0016b864f4'] = {
  min=0,
  max=1,
  dateRange={
    startDate=401,
    endDate=406,
  }
}
troop_options['615351a603385c0016b864f6'] = {
  min=3,
  max=8,
  dateRange={
    startDate=401,
    endDate=406,
  }
}
troop_options['615351a603385c0016b864f8'] = {
  min=0,
  max=1,
  dateRange={
    startDate=401,
    endDate=406,
  }
}
-- allies
