-- 5fb1b9ece1af060017709ef4 Arab Conquest Expansion  639 to 660 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba39e1af06001770eba1='5fb1ba39e1af06001770eba1'
g_base_definitions[g_str_5fb1ba39e1af06001770eba1]={
  id=g_str_5fb1ba39e1af06001770eba1,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels',
}
g_str_5fb1ba39e1af06001770eba4='5fb1ba39e1af06001770eba4'
g_base_definitions[g_str_5fb1ba39e1af06001770eba4]={
  id=g_str_5fb1ba39e1af06001770eba4,
  name='Javelin Cavalry',
  min=3,
  max=5,
  description='Jund horsemen',
}
g_str_5fb1ba39e1af06001770eba7='5fb1ba39e1af06001770eba7'
g_base_definitions[g_str_5fb1ba39e1af06001770eba7]={
  id=g_str_5fb1ba39e1af06001770eba7,
  name='Elite Foot',
  min=3,
  max=5,
  description='Muslim swordsmen',
}
g_str_5fb1ba39e1af06001770ebaa='5fb1ba39e1af06001770ebaa'
g_base_definitions[g_str_5fb1ba39e1af06001770ebaa]={
  id=g_str_5fb1ba39e1af06001770ebaa,
  name='Archers',
  min=0,
  max=1,
  description='Muslim bowmen',
}
g_str_5fb1ba39e1af06001770ebad='5fb1ba39e1af06001770ebad'
g_base_definitions[g_str_5fb1ba39e1af06001770ebad]={
  id=g_str_5fb1ba39e1af06001770ebad,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami ex-guardsmen',
}
g_str_5fb1ba39e1af06001770ebb0='5fb1ba39e1af06001770ebb0'
g_base_definitions[g_str_5fb1ba39e1af06001770ebb0]={
  id=g_str_5fb1ba39e1af06001770ebb0,
  name='Heavy Foot',
  min=3,
  max=8,
  description='Ex-Apostate swordsmen',
}
g_str_5fb1ba39e1af06001770ebb3='5fb1ba39e1af06001770ebb3'
g_base_definitions[g_str_5fb1ba39e1af06001770ebb3]={
  id=g_str_5fb1ba39e1af06001770ebb3,
  name='Archers',
  min=1,
  max=2,
  description='Ex-Apostate bowmen',
}
g_str_5fb1ba39e1af06001770ebb6='5fb1ba39e1af06001770ebb6'
g_base_definitions[g_str_5fb1ba39e1af06001770ebb6]={
  id=g_str_5fb1ba39e1af06001770ebb6,
  name='Light Foot',
  min=0,
  max=2,
  description='Javelinmen',
}
g_str_5fb1ba39e1af06001770ebb9='5fb1ba39e1af06001770ebb9'
g_base_definitions[g_str_5fb1ba39e1af06001770ebb9]={
  id=g_str_5fb1ba39e1af06001770ebb9,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
}
g_str_5fb1ba39e1af06001770ebbc='5fb1ba39e1af06001770ebbc'
g_base_definitions[g_str_5fb1ba39e1af06001770ebbc]={
  name='Javelin Cavalry General',
  min=1,
  max=1,
}
g_str_5fb1b9ece1af060017709ef4_camp='5fb1b9ece1af060017709ef4_camp'
g_base_definitions[g_str_5fb1b9ece1af060017709ef4_camp]={
  name='Camp',
  min=1,
  max=1,
}
army['5fb1b9ece1af060017709ef4']={
  data={
    name='Arab Conquest Expansion  639 to 660 AD'
  },
  g_base_definitions[g_str_5fb1b9ece1af060017709ef4_camp],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebbc],
  g_base_definitions[g_str_5fb1ba39e1af06001770eba1],
  g_base_definitions[g_str_5fb1ba39e1af06001770eba4],
  g_base_definitions[g_str_5fb1ba39e1af06001770eba7],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebaa],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebad],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebb0],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebb3],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebb6],
  g_base_definitions[g_str_5fb1ba39e1af06001770ebb9],
}
