troop_options['5fb1ba2ee1af06001770d6ce'] = {
  min=4,
  max=7,
  dateRange={
    startDate=433,
    endDate=453,
  }
}
troop_options['5fb1ba2ee1af06001770d6d0'] = {
  min=0,
  max=1,
  dateRange={
    startDate=433,
    endDate=453,
  }
}
troop_options['5fb1ba2ee1af06001770d6d2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=433,
    endDate=453,
  }
}
troop_options['5fb1ba2ee1af06001770d6d4'] = {
  min=2,
  max=4,
  dateRange={
    startDate=433,
    endDate=453,
  }
}
troop_options['5fb1ba2ee1af06001770d6d6'] = {
  min=2,
  max=6,
  dateRange={
    startDate=433,
    endDate=453,
  }
}
troop_options['5fb1ba2ee1af06001770d6d8'] = {
  min=1,
  max=2,
  dateRange={
    startDate=433,
    endDate=453,
  }
}
-- allies
