troop_options['5fb1ba1fe1af06001770bf01'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-1749,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf03'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-1749,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf06'] = {
  min=6,
  max=18,
  dateRange={
    startDate=-1749,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf08'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-1500,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf0b'] = {
  min=4,
  max=12,
  dateRange={
    startDate=-1749,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf0d'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-1749,
    endDate=-950,
  }
}
-- allies
