-- 5fb1b9e1e1af06001770985d Batavian Revolt  69 to 70 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2be1af06001770d2ea_general='5fb1ba2be1af06001770d2ea_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_general]={
  id=g_str_5fb1ba2be1af06001770d2ea_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
}
g_str_5fb1ba2be1af06001770d2ea_general_dismounted='5fb1ba2be1af06001770d2ea_general_dismounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_general_dismounted]={
  id=g_str_5fb1ba2be1af06001770d2ea_general_dismounted,
  name='Warrior',
  min=1,
  max=1,
  description='Horsemen\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  general=true,
}
g_5fb1ba2be1af06001770d2ea_general_dismounted=g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_general_dismounted]
g_str_5fb1ba2be1af06001770d2ea_general_mounted='5fb1ba2be1af06001770d2ea_general_mounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_general_mounted]={
  id=g_str_5fb1ba2be1af06001770d2ea_general_mounted,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2be1af06001770d2ea_general_dismounted,
  general=true,
}
g_str_5fb1ba2be1af06001770d2ea='5fb1ba2be1af06001770d2ea'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ea]={
  id=g_str_5fb1ba2be1af06001770d2ea,
  name='Javelin Cavalry',
  min=1,
  max=4,
  description='Horsemen',
}
g_str_5fb1ba2be1af06001770d2ea_dismounted='5fb1ba2be1af06001770d2ea_dismounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_dismounted]={
  id=g_str_5fb1ba2be1af06001770d2ea_dismounted,
  name='Warrior',
  min=1,
  max=4,
  description='Horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
}
g_5fb1ba2be1af06001770d2ea_dismounted=g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_dismounted]
g_str_5fb1ba2be1af06001770d2ea_mounted='5fb1ba2be1af06001770d2ea_mounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_mounted]={
  id=g_str_5fb1ba2be1af06001770d2ea_mounted,
  name='Javelin Cavalry',
  min=1,
  max=4,
  description='Horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2be1af06001770d2ea_dismounted,
}
g_str_5fb1ba2be1af06001770d2ed='5fb1ba2be1af06001770d2ed'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ed]={
  id=g_str_5fb1ba2be1af06001770d2ed,
  name='Warband',
  min=5,
  max=9,
  description='Fierce fighters',
}
g_str_5fb1ba2be1af06001770d2ef='5fb1ba2be1af06001770d2ef'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ef]={
  id=g_str_5fb1ba2be1af06001770d2ef,
  name='Warriors',
  min=0,
  max=2,
  description='Heroes with long spears',
}
g_str_5fb1ba2be1af06001770d2f1_general='5fb1ba2be1af06001770d2f1_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d2f1_general]={
  id=g_str_5fb1ba2be1af06001770d2f1_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Roman deserter horsemen',
  general=true,
}
g_str_5fb1ba2be1af06001770d2f1='5fb1ba2be1af06001770d2f1'
g_base_definitions[g_str_5fb1ba2be1af06001770d2f1]={
  id=g_str_5fb1ba2be1af06001770d2f1,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Roman deserter horsemen',
}
g_str_5fb1ba2be1af06001770d2f3='5fb1ba2be1af06001770d2f3'
g_base_definitions[g_str_5fb1ba2be1af06001770d2f3]={
  id=g_str_5fb1ba2be1af06001770d2f3,
  name='Raiders',
  min=1,
  max=3,
  description='Roman deserter auxilia',
}
g_str_5fb1ba2be1af06001770d2f5='5fb1ba2be1af06001770d2f5'
g_base_definitions[g_str_5fb1ba2be1af06001770d2f5]={
  id=g_str_5fb1ba2be1af06001770d2f5,
  name='Rabble',
  min=2,
  max=4,
  description='Foot skirmishers armed with many fire-hardened untipped throwing spears',
}
g_str_5fb1ba2be1af06001770d2f7='5fb1ba2be1af06001770d2f7'
g_base_definitions[g_str_5fb1ba2be1af06001770d2f7]={
  id=g_str_5fb1ba2be1af06001770d2f7,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
}
g_str_5fb1b9e1e1af06001770985d_camp='5fb1b9e1e1af06001770985d_camp'
g_base_definitions[g_str_5fb1b9e1e1af06001770985d_camp]={
  name='Camp',
  id=g_str_5fb1b9e1e1af06001770985d_camp,
  min=1,
  max=1,
}
army['5fb1b9e1e1af06001770985d']={
  data={
    name='Batavian Revolt  69 to 70 AD'
  },
  g_base_definitions[g_str_5fb1b9e1e1af06001770985d_camp],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2f9],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_general_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_general_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ea],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ea_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ed],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ef],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2f1_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2f1],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2f3],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2f5],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2f7],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af06001770985d"] = army["5fb1b9e1e1af06001770985d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Batavian Revolt  69 to 70 AD"] = army["5fb1b9e1e1af06001770985d"]
