g_str_5fb1ba3ae1af06001770ed25_general='5fb1ba3ae1af06001770ed25_general'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed25_general]={
  id=g_str_5fb1ba3ae1af06001770ed25_general,
  name='Javelin Cavalry General',
  min=6,
  max=1,
  description='Bedouin "Arabitai"',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3ae1af06001770ed24",
}
g_str_5fb1ba3ae1af06001770ed25='5fb1ba3ae1af06001770ed25'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed25]={
  id=g_str_5fb1ba3ae1af06001770ed25,
  name='Javelin Cavalry',
  min=6,
  max=12,
  description='Bedouin "Arabitai"',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3ae1af06001770ed24",
}
g_str_5fb1ba3ae1af06001770ed27='5fb1ba3ae1af06001770ed27'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed27]={
  id=g_str_5fb1ba3ae1af06001770ed27,
  name='Skirmishers',
  min=0,
  max=2,
  description='Bedouin skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3ae1af06001770ed26",
}
g_str_5fb1ba3ae1af06001770ed29='5fb1ba3ae1af06001770ed29'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed29]={
  id=g_str_5fb1ba3ae1af06001770ed29,
  name='Bad Horse',
  min=0,
  max=1,
  description='Bedouin camel-mounted scouts',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba3ae1af06001770ed28",
}
g_str_5fb1ba3ae1af06001770ed29_light_camelry='5fb1ba3ae1af06001770ed29_light_camelry'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed29_light_camelry]={
  id=g_str_5fb1ba3ae1af06001770ed29_light_camelry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Bedouin camel-mounted scouts\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba3ae1af06001770ed28",
}
g_str_5fb1ba3ae1af06001770ed2c='5fb1ba3ae1af06001770ed2c'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed2c]={
  id=g_str_5fb1ba3ae1af06001770ed2c,
  name='Horde',
  min=0,
  max=2,
  description='Ahdath militia',
  troop_type="Horde",
  troop_option_id="5fb1ba3ae1af06001770ed2b",
}
g_str_5fb1ba3ae1af06001770ed2f='5fb1ba3ae1af06001770ed2f'
g_base_definitions[g_str_5fb1ba3ae1af06001770ed2f]={
  id=g_str_5fb1ba3ae1af06001770ed2f,
  name='Horde',
  min=0,
  max=2,
  description='Syrian peasants',
  troop_type="Horde",
  troop_option_id="5fb1ba3ae1af06001770ed2d",
}
g_str_5fb1b9ede1af060017709f47_camp='5fb1b9ede1af060017709f47_camp'
g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp]={
  id=g_str_5fb1b9ede1af060017709f47_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ede1af060017709f47_camp_pack_train='5fb1b9ede1af060017709f47_camp_pack_train'
g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp_pack_train]={
  id=g_str_5fb1b9ede1af060017709f47_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba15e1af06001770b68e='5fb1ba15e1af06001770b68e'
g_base_definitions[g_str_5fb1ba15e1af06001770b68e]={
  id=g_str_5fb1ba15e1af06001770b68e,
  name='Elite Cavalary',
  min=2,
  max=4,
  description='Kurdish horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba15e1af06001770b68d",
}
