-- 5fb1b9dce1af0600177095a5 Sedentary Gallic  99 to 50 BC

army['5fb1b9dce1af0600177095a5']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Sedentary Gallic  99 to 50 BC',
    id='5fb1b9dce1af0600177095a5',
    dateRange={
      startDate=-99,
      endDate=-50,
    },
  },
  g_base_definitions[g_str_5fb1ba27e1af06001770c89b_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770c89b],
  g_base_definitions[g_str_5fb1ba27e1af06001770c89d],
  g_base_definitions[g_str_5fb1ba27e1af06001770c89f_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770c89f],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8a1],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8a3],
  g_base_definitions[g_str_5fb1b9dce1af0600177095a5_camp],
  g_base_definitions[g_str_5fb1b9dce1af0600177095a5_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af0600177095a5"] = army["5fb1b9dce1af0600177095a5"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Sedentary Gallic  99 to 50 BC"] = army["5fb1b9dce1af0600177095a5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sedentary Gallic  99 to 50 BC"] = army["5fb1b9dce1af0600177095a5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af0600177095a5"] = {}
army_dates["5fb1b9dce1af0600177095a5"]["99 BC to 50 BC"] = {
  startDate=-99,
  endDate=-50
}
army_dates["5fb1b9dce1af0600177095a5"]["99 BC to 72 BC"] = {
  startDate=-99,
  endDate=-72
}
army_dates["5fb1b9dce1af0600177095a5"]["71 BC to 61 BC"] = {
  startDate=-71,
  endDate=-61
}
army_dates["5fb1b9dce1af0600177095a5"]["60 BC to 50 BC"] = {
  startDate=-60,
  endDate=-50
}
