-- 5fb1b9efe1af06001770a0ab Rajput Indian  747 to 1303 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3de1af06001770f2eb_general='5fb1ba3de1af06001770f2eb_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f2eb_general]={
  id=g_str_5fb1ba3de1af06001770f2eb_general,
  name='Elephants General',
  min=2,
  max=1,
  description='War elephants',
  general=true,
}
g_str_5fb1ba3de1af06001770f2eb='5fb1ba3de1af06001770f2eb'
g_base_definitions[g_str_5fb1ba3de1af06001770f2eb]={
  id=g_str_5fb1ba3de1af06001770f2eb,
  name='Elephants',
  min=2,
  max=3,
  description='War elephants',
}
g_str_5fb1ba3de1af06001770f2ee_general='5fb1ba3de1af06001770f2ee_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f2ee_general]={
  id=g_str_5fb1ba3de1af06001770f2ee_general,
  name='Knights General',
  min=2,
  max=1,
  description='Rajput horsemen',
  general=true,
}
g_str_5fb1ba3de1af06001770f2ee='5fb1ba3de1af06001770f2ee'
g_base_definitions[g_str_5fb1ba3de1af06001770f2ee]={
  id=g_str_5fb1ba3de1af06001770f2ee,
  name='Knights',
  min=2,
  max=4,
  description='Rajput horsemen',
}
g_str_5fb1ba3de1af06001770f2f0='5fb1ba3de1af06001770f2f0'
g_base_definitions[g_str_5fb1ba3de1af06001770f2f0]={
  id=g_str_5fb1ba3de1af06001770f2f0,
  name='Bad Horse',
  min=0,
  max=3,
  description='Camel riders',
}
g_str_5fb1ba3de1af06001770f2f3='5fb1ba3de1af06001770f2f3'
g_base_definitions[g_str_5fb1ba3de1af06001770f2f3]={
  id=g_str_5fb1ba3de1af06001770f2f3,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Skirmishing light horsemen',
}
g_str_5fb1ba3de1af06001770f2f5='5fb1ba3de1af06001770f2f5'
g_base_definitions[g_str_5fb1ba3de1af06001770f2f5]={
  id=g_str_5fb1ba3de1af06001770f2f5,
  name='Skirmishers',
  min=0,
  max=1,
  description='Forest and hill tribe skirmishing bowmen or Kashmiri slingers',
}
g_str_5fb1ba3de1af06001770f2f7='5fb1ba3de1af06001770f2f7'
g_base_definitions[g_str_5fb1ba3de1af06001770f2f7]={
  id=g_str_5fb1ba3de1af06001770f2f7,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Guard spearmen',
}
g_str_5fb1ba3de1af06001770f2fa='5fb1ba3de1af06001770f2fa'
g_base_definitions[g_str_5fb1ba3de1af06001770f2fa]={
  id=g_str_5fb1ba3de1af06001770f2fa,
  name='Raiders',
  min=1,
  max=2,
  description='Swordsmen',
}
g_str_5fb1ba3de1af06001770f2fd='5fb1ba3de1af06001770f2fd'
g_base_definitions[g_str_5fb1ba3de1af06001770f2fd]={
  id=g_str_5fb1ba3de1af06001770f2fd,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Spearmen',
}
g_str_5fb1ba3de1af06001770f300='5fb1ba3de1af06001770f300'
g_base_definitions[g_str_5fb1ba3de1af06001770f300]={
  id=g_str_5fb1ba3de1af06001770f300,
  name='Bow Levy',
  min=4,
  max=8,
  description='Bowmen',
}
g_str_5fb1ba3de1af06001770f303='5fb1ba3de1af06001770f303'
g_base_definitions[g_str_5fb1ba3de1af06001770f303]={
  id=g_str_5fb1ba3de1af06001770f303,
  name='Horde',
  min=0,
  max=2,
  description='Camp followers',
}
g_str_5fb1b9efe1af06001770a0ab_camp='5fb1b9efe1af06001770a0ab_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a0ab_camp]={
  name='Camp',
  id=g_str_5fb1b9efe1af06001770a0ab_camp,
  min=1,
  max=1,
}
army['5fb1b9efe1af06001770a0ab']={
  data={
    name='Rajput Indian  747 to 1303 AD'
  },
  g_base_definitions[g_str_5fb1b9efe1af06001770a0ab_camp],
  g_base_definitions[g_str_5fb1ba3de1af06001770f305],
  g_base_definitions[g_str_5fb1ba3de1af06001770f306],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2eb_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2eb],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2ee_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2ee],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2f0],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2f3],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2f5],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2f7],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2fa],
  g_base_definitions[g_str_5fb1ba3de1af06001770f2fd],
  g_base_definitions[g_str_5fb1ba3de1af06001770f300],
  g_base_definitions[g_str_5fb1ba3de1af06001770f303],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a0ab"] = army["5fb1b9efe1af06001770a0ab"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Rajput Indian  747 to 1303 AD"] = army["5fb1b9efe1af06001770a0ab"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Rajput Indian  747 to 1303 AD"] = army["5fb1b9efe1af06001770a0ab"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Rajput Indian  747 to 1303 AD"] = army["5fb1b9efe1af06001770a0ab"]
