-- 5fb1b9eae1af060017709dab St. George's Night Uprising  1343 to 1345 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba36e1af06001770e641_general='5fb1ba36e1af06001770e641_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e641_general]={
  id=g_str_5fb1ba36e1af06001770e641_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Livonian horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba36e1af06001770e640",
}
g_str_5fb1ba36e1af06001770e641='5fb1ba36e1af06001770e641'
g_base_definitions[g_str_5fb1ba36e1af06001770e641]={
  id=g_str_5fb1ba36e1af06001770e641,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Livonian horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba36e1af06001770e640",
}
g_str_5fb1ba36e1af06001770e643_general='5fb1ba36e1af06001770e643_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e643_general]={
  id=g_str_5fb1ba36e1af06001770e643_general,
  name='Warriors General',
  min=0,
  max=1,
  description='Nobles and their retinue',
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba36e1af06001770e642",
}
g_str_5fb1ba36e1af06001770e643_general_dismounted_mobile_infantry='5fb1ba36e1af06001770e643_general_dismounted_mobile_infantry'
g_str_5fb1ba36e1af06001770e643_general_mounted_mobile_infantry='5fb1ba36e1af06001770e643_general_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba36e1af06001770e643_general_dismounted_mobile_infantry]={
  id=g_str_5fb1ba36e1af06001770e643_general_dismounted_mobile_infantry,
  name='Warriors General',
  min=0,
  max=1,
  description='Nobles and their retinue\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba36e1af06001770e643_general_mounted_mobile_infantry,
  general=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba36e1af06001770e642",
}
g_base_definitions[g_str_5fb1ba36e1af06001770e643_general_mounted_mobile_infantry]={
  id=g_str_5fb1ba36e1af06001770e643_general_mounted_mobile_infantry,
  name='Warriors General',
  min=0,
  max=1,
  description='Nobles and their retinue\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba36e1af06001770e643_general_dismounted_mobile_infantry,
  general=true,
  mobile_infantry=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba36e1af06001770e642",
}
g_str_5fb1ba36e1af06001770e643='5fb1ba36e1af06001770e643'
g_base_definitions[g_str_5fb1ba36e1af06001770e643]={
  id=g_str_5fb1ba36e1af06001770e643,
  name='Warriors',
  min=0,
  max=2,
  description='Nobles and their retinue',
  troop_type="Warriors",
  troop_option_id="5fb1ba36e1af06001770e642",
}
g_str_5fb1ba36e1af06001770e643_dismounted_mobile_infantry='5fb1ba36e1af06001770e643_dismounted_mobile_infantry'
g_str_5fb1ba36e1af06001770e643_mounted_mobile_infantry='5fb1ba36e1af06001770e643_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba36e1af06001770e643_dismounted_mobile_infantry]={
  id=g_str_5fb1ba36e1af06001770e643_dismounted_mobile_infantry,
  name='Warriors',
  min=0,
  max=2,
  description='Nobles and their retinue\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba36e1af06001770e643_mounted_mobile_infantry,
  troop_type="Warriors",
  troop_option_id="5fb1ba36e1af06001770e642",
}
g_base_definitions[g_str_5fb1ba36e1af06001770e643_mounted_mobile_infantry]={
  id=g_str_5fb1ba36e1af06001770e643_mounted_mobile_infantry,
  name='Warriors',
  min=0,
  max=2,
  description='Nobles and their retinue\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba36e1af06001770e643_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba36e1af06001770e642",
}
g_str_5fb1ba36e1af06001770e646_general='5fb1ba36e1af06001770e646_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e646_general]={
  id=g_str_5fb1ba36e1af06001770e646_general,
  name='Warband General',
  min=8,
  max=1,
  description='Fierce fighters',
  general=true,
  troop_type="Warband",
  troop_option_id="5fb1ba36e1af06001770e645",
}
g_str_5fb1ba36e1af06001770e646='5fb1ba36e1af06001770e646'
g_base_definitions[g_str_5fb1ba36e1af06001770e646]={
  id=g_str_5fb1ba36e1af06001770e646,
  name='Warband',
  min=8,
  max=14,
  description='Fierce fighters',
  troop_type="Warband",
  troop_option_id="5fb1ba36e1af06001770e645",
}
g_str_5fb1ba36e1af06001770e648='5fb1ba36e1af06001770e648'
g_base_definitions[g_str_5fb1ba36e1af06001770e648]={
  id=g_str_5fb1ba36e1af06001770e648,
  name='Skirmishers',
  min=2,
  max=4,
  description='Bowmen and crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba36e1af06001770e647",
}
g_str_5fb1ba36e1af06001770e649='5fb1ba36e1af06001770e649'
g_base_definitions[g_str_5fb1ba36e1af06001770e649]={
  id=g_str_5fb1ba36e1af06001770e649,
  name='Bow Levy',
  min=2,
  max=4,
  description='Bowmen and crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba36e1af06001770e647",
}
g_str_5fb1b9eae1af060017709dab_camp='5fb1b9eae1af060017709dab_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709dab_camp]={
  id=g_str_5fb1b9eae1af060017709dab_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9eae1af060017709dab']={
  data={
    name='St. George\'s Night Uprising  1343 to 1345 AD',
    id='5fb1b9eae1af060017709dab'
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e641_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e641],
  g_base_definitions[g_str_5fb1ba36e1af06001770e643_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e643_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba36e1af06001770e643_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba36e1af06001770e643],
  g_base_definitions[g_str_5fb1ba36e1af06001770e643_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba36e1af06001770e643_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba36e1af06001770e646_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e646],
  g_base_definitions[g_str_5fb1ba36e1af06001770e648],
  g_base_definitions[g_str_5fb1ba36e1af06001770e649],
  g_base_definitions[g_str_5fb1b9eae1af060017709dab_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dab"] = army["5fb1b9eae1af060017709dab"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["St. George\'s Night Uprising  1343 to 1345 AD"] = army["5fb1b9eae1af060017709dab"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["St. George\'s Night Uprising  1343 to 1345 AD"] = army["5fb1b9eae1af060017709dab"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["St. George\'s Night Uprising  1343 to 1345 AD"] = army["5fb1b9eae1af060017709dab"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dab"] = {}
army_dates["5fb1b9eae1af060017709dab"]["1343 AD to 1345 AD"] ="5fb1b9eae1af060017709dab"
