troop_options['5fb1ba3ae1af06001770ee90'] = {
  min=4,
  max=8,
  dateRange={
    startDate=1092,
    endDate=1172,
  }
}
troop_options['5fb1ba3ae1af06001770ee92'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1092,
    endDate=1172,
  }
}
troop_options['5fb1ba3ae1af06001770ee94'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1092,
    endDate=1172,
  }
}
troop_options['5fb1ba3ae1af06001770ee96'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1092,
    endDate=1172,
  }
}
troop_options['5fb1ba3ae1af06001770ee98'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1092,
    endDate=1172,
  }
}
troop_options['5fb1ba3ae1af06001770ee9a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1092,
    endDate=1172,
  }
}
troop_options['5fb1ba3ae1af06001770ee9c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1092,
    endDate=1172,
  }
}
-- allies
