-- 5fb1b9f0e1af06001770a149 Other Early Chinese Border Tribes  2000 to 315 BC

army['5fb1b9f0e1af06001770a149']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
      'Steppe',
      'Hilly',
    },
    name='Other Early Chinese Border Tribes  2000 to 315 BC',
    id='5fb1b9f0e1af06001770a149',
    dateRange={
      startDate=-2000,
      endDate=-315,
    },
  },
  g_base_definitions[g_str_5fb1ba3ee1af06001770f511_general],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f511],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f513],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f515],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a149_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a149"] = army["5fb1b9f0e1af06001770a149"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Other Early Chinese Border Tribes  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a149"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Other Early Chinese Border Tribes  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a149"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Other Early Chinese Border Tribes  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a149"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a149"] = {}
army_dates["5fb1b9f0e1af06001770a149"]["2000 BC to 315 BC"] = {
  startDate=-2000,
  endDate=-315
}
army_dates["5fb1b9f0e1af06001770a149"]["2000 BC to 1101 BC"] = {
  startDate=-2000,
  endDate=-1101
}
army_dates["5fb1b9f0e1af06001770a149"]["1100 BC to 771 BC"] = {
  startDate=-1100,
  endDate=-771
}
army_dates["5fb1b9f0e1af06001770a149"]["770 BC to 550 BC"] = {
  startDate=-770,
  endDate=-550
}
army_dates["5fb1b9f0e1af06001770a149"]["549 BC to 315 BC"] = {
  startDate=-549,
  endDate=-315
}
