troop_options['6153519f03385c0016b850e9'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-1500,
    endDate=-312,
  }
}
troop_options['6153519f03385c0016b850ec'] = {
  min=0,
  max=6,
  dateRange={
    startDate=-1500,
    endDate=-312,
  }
}
troop_options['6153519f03385c0016b850ee'] = {
  min=6,
  max=12,
  dateRange={
    startDate=-1500,
    endDate=-312,
  }
}
troop_options['6153519f03385c0016b850f0'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-1500,
    endDate=-312,
  }
}
troop_options['6153519f03385c0016b850f2'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-1500,
    endDate=-312,
  }
}
-- allies
