troop_options['5fb1ba20e1af06001770c004'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
troop_options['5fb1ba20e1af06001770c006'] = {
  min=3,
  max=7,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
troop_options['5fb1ba20e1af06001770c008'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
troop_options['5fb1ba20e1af06001770c00a'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
troop_options['5fb1ba20e1af06001770c00c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
troop_options['5fb1ba20e1af06001770c00e'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
troop_options['5fb1ba20e1af06001770c010'] = {
  min=0,
  max=10,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
troop_options['5fb1ba20e1af06001770c012'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-1645,
    endDate=-1537,
  }
}
-- allies
