troop_options['615351a803385c0016b86989'] = {
  min=3,
  max=5,
  dateRange={
    startDate=584,
    endDate=774,
  }
}
troop_options['615351a803385c0016b8698b'] = {
  min=3,
  max=5,
  dateRange={
    startDate=584,
    endDate=774,
  }
}
troop_options['615351a803385c0016b8698d'] = {
  min=2,
  max=4,
  dateRange={
    startDate=584,
    endDate=774,
  }
}
troop_options['615351a803385c0016b86990'] = {
  min=0,
  max=4,
  dateRange={
    startDate=584,
    endDate=774,
  }
}
-- allies
