-- 5fb1b9ede1af060017709f14 Early Abbasid  751 to 835 AD

army['5fb1b9ede1af060017709f14']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Delta',
      'Dry',
      'Hilly',
    },
    name='Early Abbasid  751 to 835 AD',
    id='5fb1b9ede1af060017709f14',
    dateRange={
      startDate=751,
      endDate=835,
    },
  },
  g_base_definitions[g_str_615351af03385c0016b87c8e_general],
  g_base_definitions[g_str_615351af03385c0016b87c8e_general_mounted],
  g_base_definitions[g_str_615351af03385c0016b87c8e_general_dismounted],
  g_base_definitions[g_str_615351af03385c0016b87c8e],
  g_base_definitions[g_str_615351af03385c0016b87c8e_mounted],
  g_base_definitions[g_str_615351af03385c0016b87c8e_dismounted],
  g_base_definitions[g_str_615351af03385c0016b87c91],
  g_base_definitions[g_str_615351af03385c0016b87c91_mounted],
  g_base_definitions[g_str_615351af03385c0016b87c91_dismounted],
  g_base_definitions[g_str_615351af03385c0016b87c95],
  g_base_definitions[g_str_615351af03385c0016b87c98],
  g_base_definitions[g_str_615351af03385c0016b87c9a],
  g_base_definitions[g_str_615351af03385c0016b87c9e],
  g_base_definitions[g_str_615351af03385c0016b87ca1],
  g_base_definitions[g_str_615351af03385c0016b87ca2],
  g_base_definitions[g_str_615351af03385c0016b87ca5],
  g_base_definitions[g_str_615351af03385c0016b87ca7],
  g_base_definitions[g_str_615351af03385c0016b87ca9],
  g_base_definitions[g_str_615351af03385c0016b87cab_general],
  g_base_definitions[g_str_615351af03385c0016b87cab],
  g_base_definitions[g_str_615351af03385c0016b87cad],
  g_base_definitions[g_str_615351af03385c0016b87cae],
  g_base_definitions[g_str_615351af03385c0016b87cb0],
  g_base_definitions[g_str_5fb1b9ede1af060017709f14_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f14_camp_fortified],
  g_base_definitions[g_str_5fb1b9ede1af060017709f14_camp_pack_train],
  g_base_definitions[g_str_5fb1b9ede1af060017709f14_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f14"] = army["5fb1b9ede1af060017709f14"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Early Abbasid  751 to 835 AD"] = army["5fb1b9ede1af060017709f14"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Early Abbasid  751 to 835 AD"] = army["5fb1b9ede1af060017709f14"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Abbasid  751 to 835 AD"] = army["5fb1b9ede1af060017709f14"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f14"] = {}
army_dates["5fb1b9ede1af060017709f14"]["751 AD to 835 AD"] = {
  startDate=751,
  endDate=835
}
