-- 5fb1b9dce1af060017709589 Garamantes  500 BC to 670 AD

army['5fb1b9dce1af060017709589']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Garamantes  500 BC to 670 AD',
    id='5fb1b9dce1af060017709589',
    dateRange={
      startDate=-500,
      endDate=670,
    },
  },
  g_base_definitions[g_str_615351a203385c0016b858ab_general],
  g_base_definitions[g_str_615351a203385c0016b858ab],
  g_base_definitions[g_str_615351a203385c0016b858ac_general],
  g_base_definitions[g_str_615351a203385c0016b858ac],
  g_base_definitions[g_str_615351a203385c0016b858af_general],
  g_base_definitions[g_str_615351a203385c0016b858af],
  g_base_definitions[g_str_615351a203385c0016b858b1],
  g_base_definitions[g_str_615351a203385c0016b858b3],
  g_base_definitions[g_str_615351a203385c0016b858b5],
  g_base_definitions[g_str_5fb1b9dce1af060017709589_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709589_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709589"] = army["5fb1b9dce1af060017709589"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Garamantes  500 BC to 670 AD"] = army["5fb1b9dce1af060017709589"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Garamantes  500 BC to 670 AD"] = army["5fb1b9dce1af060017709589"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Garamantes  500 BC to 670 AD"] = army["5fb1b9dce1af060017709589"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Garamantes  500 BC to 670 AD"] = army["5fb1b9dce1af060017709589"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709589"] = {}
army_dates["5fb1b9dce1af060017709589"]["500 BC to 670 AD"] = {
  startDate=-500,
  endDate=670
}
