troop_options['5fb1ba1ee1af06001770bdd6'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-2334,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bdd8'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-2334,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bdda'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-2334,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bddd'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-2334,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bde0'] = {
  min=4,
  max=12,
  dateRange={
    startDate=-2334,
    endDate=-2279,
  }
}
troop_options['5fb1ba1ee1af06001770bde3'] = {
  min=4,
  max=12,
  dateRange={
    startDate=-2278,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bde7'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-2278,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bdea'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-2278,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bded'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-2334,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bdef'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-2334,
    endDate=-2193,
  }
}
troop_options['5fb1ba1ee1af06001770bdf1'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-2334,
    endDate=-2193,
  }
}
-- allies
