troop_options['615351a303385c0016b85a2a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['615351a303385c0016b85a2e'] = {
  min=7,
  max=14,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['615351a303385c0016b85a31'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['615351a303385c0016b85a33'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['615351a303385c0016b85a35'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['615351a303385c0016b85a37'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['615351a303385c0016b85a39'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['615351a303385c0016b85a3b'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
-- allies
