-- 5fb1b9e6e1af060017709b7d Fante and Gold Coast Peoples  800 to 1600 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba32e1af06001770dd9e='5fb1ba32e1af06001770dd9e'
g_base_definitions[g_str_5fb1ba32e1af06001770dd9e]={
  id=g_str_5fb1ba32e1af06001770dd9e,
  name='Raiders',
  min=1,
  max=1,
  description='Braffos and retainers with sword, club, or battle axe',
}
g_str_5fb1ba32e1af06001770dda0='5fb1ba32e1af06001770dda0'
g_base_definitions[g_str_5fb1ba32e1af06001770dda0]={
  id=g_str_5fb1ba32e1af06001770dda0,
  name='Light Foot',
  min=3,
  max=8,
  description='Spearmen',
}
g_str_5fb1ba32e1af06001770dda2='5fb1ba32e1af06001770dda2'
g_base_definitions[g_str_5fb1ba32e1af06001770dda2]={
  id=g_str_5fb1ba32e1af06001770dda2,
  name='Skirmishers',
  min=1,
  max=3,
  description='Skirmishing bowmen',
}
g_str_5fb1ba32e1af06001770dda4='5fb1ba32e1af06001770dda4'
g_base_definitions[g_str_5fb1ba32e1af06001770dda4]={
  id=g_str_5fb1ba32e1af06001770dda4,
  name='Warband',
  min=3,
  max=8,
  description='Fierce infantry',
}
g_str_5fb1ba32e1af06001770dda6='5fb1ba32e1af06001770dda6'
g_base_definitions[g_str_5fb1ba32e1af06001770dda6]={
  name='Raiders General',
  id=g_str_5fb1ba32e1af06001770dda6,
  min=1,
  max=1,
}
g_str_5fb1b9e6e1af060017709b7d_camp='5fb1b9e6e1af060017709b7d_camp'
g_base_definitions[g_str_5fb1b9e6e1af060017709b7d_camp]={
  name='Camp',
  id=g_str_5fb1b9e6e1af060017709b7d_camp,
  min=1,
  max=1,
}
army['5fb1b9e6e1af060017709b7d']={
  data={
    name='Fante and Gold Coast Peoples  800 to 1600 AD'
  },
  g_base_definitions[g_str_5fb1b9e6e1af060017709b7d_camp],
  g_base_definitions[g_str_5fb1ba32e1af06001770dda6],
  g_base_definitions[g_str_5fb1ba32e1af06001770dd9e],
  g_base_definitions[g_str_5fb1ba32e1af06001770dda0],
  g_base_definitions[g_str_5fb1ba32e1af06001770dda2],
  g_base_definitions[g_str_5fb1ba32e1af06001770dda4],
}
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Fante and Gold Coast Peoples  800 to 1600 AD"] = army["5fb1b9e6e1af060017709b7d"]
