-- 5fb1b9f0e1af06001770a0d5 Burmese  500 to 1526 AD

army['5fb1b9f0e1af06001770a0d5']={
  data={
    name='Burmese  500 to 1526 AD',
    id='5fb1b9f0e1af06001770a0d5',
    dateRange={
      startDate=500,
      endDate=1526,
    }
  },
  g_base_definitions[g_str_5fb1ba3de1af06001770f380_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f380],
  g_base_definitions[g_str_5fb1ba3de1af06001770f383_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f383],
  g_base_definitions[g_str_5fb1ba3de1af06001770f386_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f386],
  g_base_definitions[g_str_5fb1ba3de1af06001770f389],
  g_base_definitions[g_str_5fb1ba3de1af06001770f38b_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f38b_general_elephant_screen],
  g_base_definitions[g_str_5fb1ba3de1af06001770f38b],
  g_base_definitions[g_str_5fb1ba3de1af06001770f38b_elephant_screen],
  g_base_definitions[g_str_5fb1ba3de1af06001770f38e_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f38e],
  g_base_definitions[g_str_5fb1ba3de1af06001770f390],
  g_base_definitions[g_str_5fb1ba3de1af06001770f392],
  g_base_definitions[g_str_5fb1ba3de1af06001770f394],
  g_base_definitions[g_str_5fb1ba3de1af06001770f395],
  g_base_definitions[g_str_5fb1ba3de1af06001770f397],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a0d5_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a0d5"] = army["5fb1b9f0e1af06001770a0d5"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Burmese  500 to 1526 AD"] = army["5fb1b9f0e1af06001770a0d5"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Burmese  500 to 1526 AD"] = army["5fb1b9f0e1af06001770a0d5"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Burmese  500 to 1526 AD"] = army["5fb1b9f0e1af06001770a0d5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Burmese  500 to 1526 AD"] = army["5fb1b9f0e1af06001770a0d5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a0d5"] = {}
army_dates["5fb1b9f0e1af06001770a0d5"]["500 AD to 1526 AD"] = {
  startDate=500,
  endDate=1526
}
army_dates["5fb1b9f0e1af06001770a0d5"]["500 AD to 1043 AD"] = {
  startDate=500,
  endDate=1043
}
army_dates["5fb1b9f0e1af06001770a0d5"]["1044 AD to 1173 AD"] = {
  startDate=1044,
  endDate=1173
}
army_dates["5fb1b9f0e1af06001770a0d5"]["1174 AD to 1526 AD"] = {
  startDate=1174,
  endDate=1526
}
