g_str_5fb1ba43e1af06001770fd35_general='5fb1ba43e1af06001770fd35_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd35_general]={
  id=g_str_5fb1ba43e1af06001770fd35_general,
  name='Light Foot General',
  min=12,
  max=1,
  description='Formed infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd34",
}
g_str_5fb1ba43e1af06001770fd35='5fb1ba43e1af06001770fd35'
g_base_definitions[g_str_5fb1ba43e1af06001770fd35]={
  id=g_str_5fb1ba43e1af06001770fd35,
  name='Light Foot',
  min=12,
  max=16,
  description='Formed infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd34",
}
g_str_5fb1ba43e1af06001770fd37='5fb1ba43e1af06001770fd37'
g_base_definitions[g_str_5fb1ba43e1af06001770fd37]={
  id=g_str_5fb1ba43e1af06001770fd37,
  name='Skirmishers',
  min=0,
  max=3,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd36",
}
g_str_5fb1ba43e1af06001770fd39='5fb1ba43e1af06001770fd39'
g_base_definitions[g_str_5fb1ba43e1af06001770fd39]={
  id=g_str_5fb1ba43e1af06001770fd39,
  name='Skirmishers',
  min=0,
  max=1,
  description='Road weasel scouts',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd38",
}
g_str_5fb1b9f5e1af06001770a3b1_camp='5fb1b9f5e1af06001770a3b1_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3b1_camp]={
  id=g_str_5fb1b9f5e1af06001770a3b1_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
