troop_options['5fb1ba35e1af06001770e464'] = {
  min=3,
  max=6,
  dateRange={
    startDate=1282,
    endDate=1442,
  }
}
troop_options['5fb1ba35e1af06001770e466'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1282,
    endDate=1442,
  }
}
troop_options['5fb1ba35e1af06001770e468'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1282,
    endDate=1442,
  }
}
troop_options['5fb1ba35e1af06001770e46a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1282,
    endDate=1442,
  }
}
troop_options['5fb1ba35e1af06001770e46e'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1282,
    endDate=1442,
  }
}
troop_options['5fb1ba35e1af06001770e470'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1282,
    endDate=1442,
  }
}
troop_options['5fb1ba35e1af06001770e472'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1282,
    endDate=1442,
  }
}
-- allies
-- 5fb1b9e9e1af060017709d43 Medieval Sicilian  1282 to 1442 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba35e1af06001770e465_general='5fb1ba35e1af06001770e465_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e465_general]={
  id=g_str_5fb1ba35e1af06001770e465_general,
  name='Knights General',
  min=3,
  max=1,
  description='Feudal men-at-arms and sergeants, or Italian communal cavalieri',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba35e1af06001770e464",
}
g_str_5fb1ba35e1af06001770e465='5fb1ba35e1af06001770e465'
g_base_definitions[g_str_5fb1ba35e1af06001770e465]={
  id=g_str_5fb1ba35e1af06001770e465,
  name='Knights',
  min=3,
  max=6,
  description='Feudal men-at-arms and sergeants, or Italian communal cavalieri',
  troop_type="Knights",
  troop_option_id="5fb1ba35e1af06001770e464",
}
g_str_5fb1ba35e1af06001770e467='5fb1ba35e1af06001770e467'
g_base_definitions[g_str_5fb1ba35e1af06001770e467]={
  id=g_str_5fb1ba35e1af06001770e467,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Aragonese cavalls alforrats',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba35e1af06001770e466",
}
g_str_5fb1ba35e1af06001770e469='5fb1ba35e1af06001770e469'
g_base_definitions[g_str_5fb1ba35e1af06001770e469]={
  id=g_str_5fb1ba35e1af06001770e469,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Italian communal spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba35e1af06001770e468",
}
g_str_5fb1ba35e1af06001770e46b='5fb1ba35e1af06001770e46b'
g_base_definitions[g_str_5fb1ba35e1af06001770e46b]={
  id=g_str_5fb1ba35e1af06001770e46b,
  name='Bow Levy',
  min=0,
  max=2,
  description='Italian communal crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba35e1af06001770e46a",
}
g_str_5fb1ba35e1af06001770e46c='5fb1ba35e1af06001770e46c'
g_base_definitions[g_str_5fb1ba35e1af06001770e46c]={
  id=g_str_5fb1ba35e1af06001770e46c,
  name='Pavisiers',
  min=0,
  max=2,
  description='Italian communal crossbowmen',
  troop_type="Pavisiers",
  troop_option_id="5fb1ba35e1af06001770e46a",
}
g_str_5fb1ba35e1af06001770e46f='5fb1ba35e1af06001770e46f'
g_base_definitions[g_str_5fb1ba35e1af06001770e46f]={
  id=g_str_5fb1ba35e1af06001770e46f,
  name='Pavisiers',
  min=0,
  max=2,
  description='Aragonese escudats i ballesters',
  troop_type="Pavisiers",
  troop_option_id="5fb1ba35e1af06001770e46e",
}
g_str_5fb1ba35e1af06001770e471='5fb1ba35e1af06001770e471'
g_base_definitions[g_str_5fb1ba35e1af06001770e471]={
  id=g_str_5fb1ba35e1af06001770e471,
  name='Archers',
  min=0,
  max=2,
  description='Mercenary crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba35e1af06001770e470",
}
g_str_5fb1ba35e1af06001770e473='5fb1ba35e1af06001770e473'
g_base_definitions[g_str_5fb1ba35e1af06001770e473]={
  id=g_str_5fb1ba35e1af06001770e473,
  name='Horde',
  min=0,
  max=4,
  description='Arriere-ban',
  troop_type="Horde",
  troop_option_id="5fb1ba35e1af06001770e472",
}
g_str_5fb1b9e9e1af060017709d43_camp='5fb1b9e9e1af060017709d43_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d43_camp]={
  id=g_str_5fb1b9e9e1af060017709d43_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e9e1af060017709d43']={
  data={
    name='Medieval Sicilian  1282 to 1442 AD',
    id='5fb1b9e9e1af060017709d43',
    army_id='5fb1b9e9e1af060017709d43'
  },
  g_base_definitions[g_str_5fb1ba35e1af06001770e465_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e465],
  g_base_definitions[g_str_5fb1ba35e1af06001770e467],
  g_base_definitions[g_str_5fb1ba35e1af06001770e469],
  g_base_definitions[g_str_5fb1ba35e1af06001770e46b],
  g_base_definitions[g_str_5fb1ba35e1af06001770e46c],
  g_base_definitions[g_str_5fb1ba35e1af06001770e46f],
  g_base_definitions[g_str_5fb1ba35e1af06001770e471],
  g_base_definitions[g_str_5fb1ba35e1af06001770e473],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d43_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d43"] = army["5fb1b9e9e1af060017709d43"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Medieval Sicilian  1282 to 1442 AD"] = army["5fb1b9e9e1af060017709d43"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Sicilian  1282 to 1442 AD"] = army["5fb1b9e9e1af060017709d43"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d43"] = {}
army_dates["5fb1b9e9e1af060017709d43"]["1282 AD to 1442 AD"] ="5fb1b9e9e1af060017709d43"
