troop_options['5fb1ba3be1af06001770efb4'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1281,
    endDate=1361,
  }
}
troop_options['5fb1ba3be1af06001770efb6'] = {
  min=7,
  max=11,
  dateRange={
    startDate=1281,
    endDate=1361,
  }
}
troop_options['5fb1ba3be1af06001770efb8'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1281,
    endDate=1361,
  }
}
troop_options['5fb1ba3be1af06001770efbb'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1281,
    endDate=1361,
  }
}
troop_options['5fb1ba3be1af06001770efbe'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1281,
    endDate=1361,
  }
}
troop_options['5fb1ba3be1af06001770efc0'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1281,
    endDate=1361,
  }
}
-- allies
-- 5fb1b9eee1af060017709feb Early Ottoman  1281 to 1361 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3be1af06001770efb5_general='5fb1ba3be1af06001770efb5_general'
g_base_definitions[g_str_5fb1ba3be1af06001770efb5_general]={
  id=g_str_5fb1ba3be1af06001770efb5_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Feudal sipahis',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770efb4",
}
g_str_5fb1ba3be1af06001770efb5='5fb1ba3be1af06001770efb5'
g_base_definitions[g_str_5fb1ba3be1af06001770efb5]={
  id=g_str_5fb1ba3be1af06001770efb5,
  name='Horse Bow',
  min=0,
  max=2,
  description='Feudal sipahis',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770efb4",
}
g_str_5fb1ba3be1af06001770efb7_general='5fb1ba3be1af06001770efb7_general'
g_base_definitions[g_str_5fb1ba3be1af06001770efb7_general]={
  id=g_str_5fb1ba3be1af06001770efb7_general,
  name='Horse Bow General',
  min=7,
  max=1,
  description='Ghazis',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770efb6",
}
g_str_5fb1ba3be1af06001770efb7='5fb1ba3be1af06001770efb7'
g_base_definitions[g_str_5fb1ba3be1af06001770efb7]={
  id=g_str_5fb1ba3be1af06001770efb7,
  name='Horse Bow',
  min=7,
  max=11,
  description='Ghazis',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770efb6",
}
g_str_5fb1ba3be1af06001770efb9='5fb1ba3be1af06001770efb9'
g_base_definitions[g_str_5fb1ba3be1af06001770efb9]={
  id=g_str_5fb1ba3be1af06001770efb9,
  name='Light Foot',
  min=0,
  max=2,
  description='Spearmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3be1af06001770efb8",
}
g_str_5fb1ba3be1af06001770efba='5fb1ba3be1af06001770efba'
g_base_definitions[g_str_5fb1ba3be1af06001770efba]={
  id=g_str_5fb1ba3be1af06001770efba,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3be1af06001770efb8",
}
g_str_5fb1ba3be1af06001770efbc='5fb1ba3be1af06001770efbc'
g_base_definitions[g_str_5fb1ba3be1af06001770efbc]={
  id=g_str_5fb1ba3be1af06001770efbc,
  name='Skirmishers',
  min=1,
  max=2,
  description='Azab bowmen or slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3be1af06001770efbb",
}
g_str_5fb1ba3be1af06001770efbd='5fb1ba3be1af06001770efbd'
g_base_definitions[g_str_5fb1ba3be1af06001770efbd]={
  id=g_str_5fb1ba3be1af06001770efbd,
  name='Bow Levy',
  min=1,
  max=2,
  description='Azab bowmen or slingers',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3be1af06001770efbb",
}
g_str_5fb1ba3be1af06001770efbf='5fb1ba3be1af06001770efbf'
g_base_definitions[g_str_5fb1ba3be1af06001770efbf]={
  id=g_str_5fb1ba3be1af06001770efbf,
  name='Rabble',
  min=0,
  max=2,
  description='Azab javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba3be1af06001770efbe",
}
g_str_5fb1ba3be1af06001770efc1='5fb1ba3be1af06001770efc1'
g_base_definitions[g_str_5fb1ba3be1af06001770efc1]={
  id=g_str_5fb1ba3be1af06001770efc1,
  name='Horde',
  min=0,
  max=2,
  description='Poorly equipped azabs (Levendat) or European levy infantry',
  troop_type="Horde",
  troop_option_id="5fb1ba3be1af06001770efc0",
}
g_str_5fb1b9eee1af060017709feb_camp='5fb1b9eee1af060017709feb_camp'
g_base_definitions[g_str_5fb1b9eee1af060017709feb_camp]={
  id=g_str_5fb1b9eee1af060017709feb_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9eee1af060017709feb_camp_pack_train='5fb1b9eee1af060017709feb_camp_pack_train'
g_base_definitions[g_str_5fb1b9eee1af060017709feb_camp_pack_train]={
  id=g_str_5fb1b9eee1af060017709feb_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9eee1af060017709feb']={
  data={
    name='Early Ottoman  1281 to 1361 AD',
    id='5fb1b9eee1af060017709feb',
    army_id='5fb1b9eee1af060017709feb'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770efb5_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770efb5],
  g_base_definitions[g_str_5fb1ba3be1af06001770efb7_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770efb7],
  g_base_definitions[g_str_5fb1ba3be1af06001770efb9],
  g_base_definitions[g_str_5fb1ba3be1af06001770efba],
  g_base_definitions[g_str_5fb1ba3be1af06001770efbc],
  g_base_definitions[g_str_5fb1ba3be1af06001770efbd],
  g_base_definitions[g_str_5fb1ba3be1af06001770efbf],
  g_base_definitions[g_str_5fb1ba3be1af06001770efc1],
  g_base_definitions[g_str_5fb1b9eee1af060017709feb_camp],
  g_base_definitions[g_str_5fb1b9eee1af060017709feb_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af060017709feb"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af060017709feb"] = {}
army_dates["5fb1b9eee1af060017709feb"]["1281 AD to 1361 AD"] ="5fb1b9eee1af060017709feb"
