-- 5fb1b9dce1af0600177095ab Iberians  240 to 20 BC

army['5fb1b9dce1af0600177095ab']={
  data={
    invasionRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Iberians  240 to 20 BC',
    id='5fb1b9dce1af0600177095ab',
    dateRange={
      startDate=-240,
      endDate=-20,
    }
  },
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_general_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_general_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b1],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b3],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b5],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b7],
  g_base_definitions[g_str_5fb1b9dce1af0600177095ab_camp],
  g_base_definitions[g_str_5fb1b9dce1af0600177095ab_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af0600177095ab"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af0600177095ab"] = {}
army_dates["5fb1b9dce1af0600177095ab"]["240 BC to 20 BC"] = {
  startDate=-240,
  endDate=-20
}
