-- 5fb1b9e7e1af060017709be7 Murcian and Granadine  1228 to 1492 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba32e1af06001770dee0']= {
  min=0,
  max=1,
  description='Lancers',
  startDate=1228,
  endDate=1339,
}
g_str_5fb1ba32e1af06001770dee2_general='5fb1ba32e1af06001770dee2_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dee2_general]={
  id=g_str_5fb1ba32e1af06001770dee2_general,
  name='Knights General',
  min=0,
  max=1,
  description='Lancers',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba32e1af06001770dee0",
}
g_str_5fb1ba32e1af06001770dee2='5fb1ba32e1af06001770dee2'
g_base_definitions[g_str_5fb1ba32e1af06001770dee2]={
  id=g_str_5fb1ba32e1af06001770dee2,
  name='Knights',
  min=0,
  max=1,
  description='Lancers',
  troop_type="Knights",
  troop_option_id="5fb1ba32e1af06001770dee0",
}
g_troop_option['5fb1ba32e1af06001770dee3']= {
  min=0,
  max=1,
  description='Lancers',
  startDate=1340,
  endDate=1492,
}
g_str_5fb1ba32e1af06001770dee5_general='5fb1ba32e1af06001770dee5_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dee5_general]={
  id=g_str_5fb1ba32e1af06001770dee5_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Lancers',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770dee3",
}
g_str_5fb1ba32e1af06001770dee5='5fb1ba32e1af06001770dee5'
g_base_definitions[g_str_5fb1ba32e1af06001770dee5]={
  id=g_str_5fb1ba32e1af06001770dee5,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Lancers',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770dee3",
}
g_troop_option['5fb1ba32e1af06001770dee6']= {
  min=2,
  max=4,
  description='Jinetes',
}
g_str_5fb1ba32e1af06001770dee7_general='5fb1ba32e1af06001770dee7_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dee7_general]={
  id=g_str_5fb1ba32e1af06001770dee7_general,
  name='Javelin Cavalry General',
  min=2,
  max=1,
  description='Jinetes',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770dee6",
}
g_str_5fb1ba32e1af06001770dee7='5fb1ba32e1af06001770dee7'
g_base_definitions[g_str_5fb1ba32e1af06001770dee7]={
  id=g_str_5fb1ba32e1af06001770dee7,
  name='Javelin Cavalry',
  min=2,
  max=4,
  description='Jinetes',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770dee6",
}
g_troop_option['5fb1ba32e1af06001770dee8']= {
  min=1,
  max=1,
  description='Crossbowmen on horses',
}
g_str_5fb1ba32e1af06001770dee9='5fb1ba32e1af06001770dee9'
g_base_definitions[g_str_5fb1ba32e1af06001770dee9]={
  id=g_str_5fb1ba32e1af06001770dee9,
  name='Bad Horse',
  min=1,
  max=1,
  description='Crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba32e1af06001770dee8",
}
g_troop_option['5fb1ba32e1af06001770deea']= {
  min=0,
  max=1,
  description='Mercenary spearmen',
  core='all',
}
g_str_5fb1ba32e1af06001770deeb='5fb1ba32e1af06001770deeb'
g_base_definitions[g_str_5fb1ba32e1af06001770deeb]={
  id=g_str_5fb1ba32e1af06001770deeb,
  name='Spears',
  min=0,
  max=1,
  description='Mercenary spearmen',
  troop_type="Spears",
  troop_option_id="5fb1ba32e1af06001770deea",
}
g_troop_option['5fb1ba32e1af06001770deec']= {
  min=0,
  max=2,
  description='Mercenary crossbowmen or bowmen',
  core='all',
}
g_str_5fb1ba32e1af06001770deed='5fb1ba32e1af06001770deed'
g_base_definitions[g_str_5fb1ba32e1af06001770deed]={
  id=g_str_5fb1ba32e1af06001770deed,
  name='Archers',
  min=0,
  max=2,
  description='Mercenary crossbowmen or bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba32e1af06001770deec",
}
g_troop_option['5fb1ba32e1af06001770deee']= {
  min=0,
  max=2,
  description='Town militia',
  core='all',
}
g_str_5fb1ba32e1af06001770deef='5fb1ba32e1af06001770deef'
g_base_definitions[g_str_5fb1ba32e1af06001770deef]={
  id=g_str_5fb1ba32e1af06001770deef,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Town militia',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba32e1af06001770deee",
}
g_troop_option['5fb1ba32e1af06001770def0']= {
  min=6,
  max=18,
  description='Peasant crossbowmen',
}
g_str_5fb1ba32e1af06001770def1='5fb1ba32e1af06001770def1'
g_base_definitions[g_str_5fb1ba32e1af06001770def1]={
  id=g_str_5fb1ba32e1af06001770def1,
  name='Bow Levy',
  min=6,
  max=18,
  description='Peasant crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba32e1af06001770def0",
}
g_troop_option['5fb1ba32e1af06001770def2']= {
  min=0,
  max=1,
  description='Staff-slingers',
}
g_str_5fb1ba32e1af06001770def3='5fb1ba32e1af06001770def3'
g_base_definitions[g_str_5fb1ba32e1af06001770def3]={
  id=g_str_5fb1ba32e1af06001770def3,
  name='Skirmishers',
  min=0,
  max=1,
  description='Staff-slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba32e1af06001770def2",
}
g_troop_option['5fb1ba32e1af06001770def4']= {
  min=0,
  max=1,
  description='Handgunners',
  startDate=1340,
  endDate=1492,
}
g_str_5fb1ba32e1af06001770def6='5fb1ba32e1af06001770def6'
g_base_definitions[g_str_5fb1ba32e1af06001770def6]={
  id=g_str_5fb1ba32e1af06001770def6,
  name='Skirmishers',
  min=0,
  max=1,
  description='Handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba32e1af06001770def4",
}
g_str_5fb1b9e7e1af060017709be7_camp='5fb1b9e7e1af060017709be7_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp]={
  id=g_str_5fb1b9e7e1af060017709be7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e7e1af060017709be7_camp_pack_train='5fb1b9e7e1af060017709be7_camp_pack_train'
g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp_pack_train]={
  id=g_str_5fb1b9e7e1af060017709be7_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e7e1af060017709be7']={
  data={
    name='Murcian and Granadine  1228 to 1492 AD',
    id='5fb1b9e7e1af060017709be7',
    army_id='5fb1b9e7e1af060017709be7'
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770dee2_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee2],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee5_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee5],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee7_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee7],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee9],
  g_base_definitions[g_str_5fb1ba32e1af06001770deeb],
  g_base_definitions[g_str_5fb1ba32e1af06001770deed],
  g_base_definitions[g_str_5fb1ba32e1af06001770deef],
  g_base_definitions[g_str_5fb1ba32e1af06001770def1],
  g_base_definitions[g_str_5fb1ba32e1af06001770def3],
  g_base_definitions[g_str_5fb1ba32e1af06001770def6],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709be7"] = army["5fb1b9e7e1af060017709be7"]
army['5fb1b9e7e1af060017709be7_1228_1339']={
  data={
    name='Murcian and Granadine 1228 AD to 1339 AD',
    id='5fb1b9e7e1af060017709be7_1228_1339',
    army_id='5fb1b9e7e1af060017709be7'
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770dee2_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee2],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee7_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee7],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee9],
  g_base_definitions[g_str_5fb1ba32e1af06001770deeb],
  g_base_definitions[g_str_5fb1ba32e1af06001770deed],
  g_base_definitions[g_str_5fb1ba32e1af06001770deef],
  g_base_definitions[g_str_5fb1ba32e1af06001770def1],
  g_base_definitions[g_str_5fb1ba32e1af06001770def3],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp_pack_train],
}
army['5fb1b9e7e1af060017709be7_1340_1492']={
  data={
    name='Murcian and Granadine 1340 AD to 1492 AD',
    id='5fb1b9e7e1af060017709be7_1340_1492',
    army_id='5fb1b9e7e1af060017709be7'
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770dee5_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee5],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee7_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee7],
  g_base_definitions[g_str_5fb1ba32e1af06001770dee9],
  g_base_definitions[g_str_5fb1ba32e1af06001770deeb],
  g_base_definitions[g_str_5fb1ba32e1af06001770deed],
  g_base_definitions[g_str_5fb1ba32e1af06001770deef],
  g_base_definitions[g_str_5fb1ba32e1af06001770def1],
  g_base_definitions[g_str_5fb1ba32e1af06001770def3],
  g_base_definitions[g_str_5fb1ba32e1af06001770def6],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp_pack_train],
}
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Murcian and Granadine  1228 to 1492 AD"] = army["5fb1b9e7e1af060017709be7"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Murcian and Granadine  1228 to 1492 AD"] = army["5fb1b9e7e1af060017709be7"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Murcian and Granadine  1228 to 1492 AD"] = army["5fb1b9e7e1af060017709be7"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709be7"] = {}
army_dates["5fb1b9e7e1af060017709be7"]["1228 AD to 1492 AD"] ="5fb1b9e7e1af060017709be7"
army_dates["5fb1b9e7e1af060017709be7"]["1228 AD to 1339 AD"] ="5fb1b9e7e1af060017709be7_1228_1339"
army_dates["5fb1b9e7e1af060017709be7"]["1340 AD to 1492 AD"] ="5fb1b9e7e1af060017709be7_1340_1492"
