troop_options['5fb1ba26e1af06001770c839'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-664,
    endDate=70,
  }
}
troop_options['5fb1ba26e1af06001770c83b'] = {
  min=0,
  max=10,
  dateRange={
    startDate=-664,
    endDate=70,
  }
}
troop_options['5fb1ba26e1af06001770c83d'] = {
  min=7,
  max=15,
  dateRange={
    startDate=-664,
    endDate=70,
  }
}
troop_options['5fb1ba26e1af06001770c83f'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-664,
    endDate=70,
  }
}
-- allies
