-- 5fb1b9dee1af06001770967e Hellenistic Boiotian  278 to 146 BC

army['5fb1b9dee1af06001770967e']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Hellenistic Boiotian  278 to 146 BC',
    id='5fb1b9dee1af06001770967e',
    dateRange={
      startDate=-278,
      endDate=-146,
    },
  },
  g_base_definitions[g_str_615351a303385c0016b85c99_general],
  g_base_definitions[g_str_615351a303385c0016b85c99],
  g_base_definitions[g_str_615351a303385c0016b85c9b],
  g_base_definitions[g_str_615351a303385c0016b85c9e],
  g_base_definitions[g_str_615351a303385c0016b85ca1],
  g_base_definitions[g_str_615351a303385c0016b85ca3],
  g_base_definitions[g_str_615351a303385c0016b85ca5],
  g_base_definitions[g_str_615351a303385c0016b85ca6],
  g_base_definitions[g_str_5fb1b9dee1af06001770967e_camp],
  g_base_definitions[g_str_5fb1b9dee1af06001770967e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af06001770967e"] = army["5fb1b9dee1af06001770967e"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Hellenistic Boiotian  278 to 146 BC"] = army["5fb1b9dee1af06001770967e"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Hellenistic Boiotian  278 to 146 BC"] = army["5fb1b9dee1af06001770967e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hellenistic Boiotian  278 to 146 BC"] = army["5fb1b9dee1af06001770967e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af06001770967e"] = {}
army_dates["5fb1b9dee1af06001770967e"]["278 BC to 146 BC"] = {
  startDate=-278,
  endDate=-146
}
