troop_options['5fb1ba1fe1af06001770bf14'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-1650,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf16'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-1650,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf1a'] = {
  min=5,
  max=12,
  dateRange={
    startDate=-1650,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf1c'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-1650,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf1e'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-1650,
    endDate=-950,
  }
}
troop_options['5fb1ba1fe1af06001770bf20'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-1650,
    endDate=-950,
  }
}
-- allies
