-- 5fb1b9f3e1af06001770a302 Early Ming Chinese  1350 to 1419 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba41e1af06001770fb55_general='5fb1ba41e1af06001770fb55_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fb55_general]={
  id=g_str_5fb1ba41e1af06001770fb55_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Jingwei guard horsemen',
  general=true,
  troop_type="Elite Cavalary",
}
g_str_5fb1ba41e1af06001770fb55='5fb1ba41e1af06001770fb55'
g_base_definitions[g_str_5fb1ba41e1af06001770fb55]={
  id=g_str_5fb1ba41e1af06001770fb55,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Jingwei guard horsemen',
  troop_type="Elite Cavalary",
}
g_str_5fb1ba41e1af06001770fb58_general='5fb1ba41e1af06001770fb58_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fb58_general]={
  id=g_str_5fb1ba41e1af06001770fb58_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Mongol or Jurchen guard horsemen',
  general=true,
  troop_type="Elite Cavalary",
}
g_str_5fb1ba41e1af06001770fb58='5fb1ba41e1af06001770fb58'
g_base_definitions[g_str_5fb1ba41e1af06001770fb58]={
  id=g_str_5fb1ba41e1af06001770fb58,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Mongol or Jurchen guard horsemen',
  troop_type="Elite Cavalary",
}
g_str_5fb1ba41e1af06001770fb5a_general='5fb1ba41e1af06001770fb5a_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fb5a_general]={
  id=g_str_5fb1ba41e1af06001770fb5a_general,
  name='Horse Bow General',
  min=2,
  max=1,
  description='Chinese horse archers',
  general=true,
  troop_type="Horse Bow",
}
g_str_5fb1ba41e1af06001770fb5a='5fb1ba41e1af06001770fb5a'
g_base_definitions[g_str_5fb1ba41e1af06001770fb5a]={
  id=g_str_5fb1ba41e1af06001770fb5a,
  name='Horse Bow',
  min=2,
  max=3,
  description='Chinese horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba41e1af06001770fb5d_general='5fb1ba41e1af06001770fb5d_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fb5d_general]={
  id=g_str_5fb1ba41e1af06001770fb5d_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Mongol or Jurchen horse archers',
  general=true,
  troop_type="Horse Bow",
}
g_str_5fb1ba41e1af06001770fb5d='5fb1ba41e1af06001770fb5d'
g_base_definitions[g_str_5fb1ba41e1af06001770fb5d]={
  id=g_str_5fb1ba41e1af06001770fb5d,
  name='Horse Bow',
  min=0,
  max=2,
  description='Mongol or Jurchen horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba41e1af06001770fb5f='5fb1ba41e1af06001770fb5f'
g_base_definitions[g_str_5fb1ba41e1af06001770fb5f]={
  id=g_str_5fb1ba41e1af06001770fb5f,
  name='Elite Foot',
  min=2,
  max=3,
  description='Veteran Chinese close-fighting infantry armed with mixed halberd-type weapons',
  troop_type="Elite Foot",
}
g_str_5fb1ba41e1af06001770fb62='5fb1ba41e1af06001770fb62'
g_base_definitions[g_str_5fb1ba41e1af06001770fb62]={
  id=g_str_5fb1ba41e1af06001770fb62,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Chinese close-fighting infantry armed with mixed halberd-type weapons',
  troop_type="Heavy Foot",
}
g_str_5fb1ba41e1af06001770fb63='5fb1ba41e1af06001770fb63'
g_base_definitions[g_str_5fb1ba41e1af06001770fb63]={
  id=g_str_5fb1ba41e1af06001770fb63,
  name='Elite Foot',
  min=1,
  max=2,
  description='Chinese close-fighting infantry armed with mixed halberd-type weapons',
  troop_type="Elite Foot",
}
g_str_5fb1ba41e1af06001770fb65='5fb1ba41e1af06001770fb65'
g_base_definitions[g_str_5fb1ba41e1af06001770fb65]={
  id=g_str_5fb1ba41e1af06001770fb65,
  name='Archers',
  min=2,
  max=3,
  description='Veteran Chinese bowmen or crossbowmen, separate or protected behind men armed with shield and spear',
  troop_type="Archers",
}
g_str_5fb1ba41e1af06001770fb66='5fb1ba41e1af06001770fb66'
g_base_definitions[g_str_5fb1ba41e1af06001770fb66]={
  id=g_str_5fb1ba41e1af06001770fb66,
  name='Pavisiers',
  min=2,
  max=3,
  description='Veteran Chinese bowmen or crossbowmen, separate or protected behind men armed with shield and spear',
  troop_type="Pavisiers",
}
g_str_5fb1ba41e1af06001770fb68='5fb1ba41e1af06001770fb68'
g_base_definitions[g_str_5fb1ba41e1af06001770fb68]={
  id=g_str_5fb1ba41e1af06001770fb68,
  name='Raiders',
  min=0,
  max=1,
  description='"Dare to die" troops with halberds, swords, handguns, or fire-lances',
  troop_type="Raiders",
}
g_str_5fb1ba41e1af06001770fb69='5fb1ba41e1af06001770fb69'
g_base_definitions[g_str_5fb1ba41e1af06001770fb69]={
  id=g_str_5fb1ba41e1af06001770fb69,
  name='Skirmishers',
  min=0,
  max=1,
  description='"Dare to die" troops with halberds, swords, handguns, or fire-lances',
  troop_type="Skirmishers",
}
g_str_5fb1ba41e1af06001770fb6b='5fb1ba41e1af06001770fb6b'
g_base_definitions[g_str_5fb1ba41e1af06001770fb6b]={
  id=g_str_5fb1ba41e1af06001770fb6b,
  name='Artillery',
  min=0,
  max=2,
  description='Various guns, rockets, frame-mounted crossbows, and counter-weight stone-throwers',
  troop_type="Artillery",
}
g_str_5fb1b9f3e1af06001770a302_camp='5fb1b9f3e1af06001770a302_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a302_camp]={
  name='Camp',
  id=g_str_5fb1b9f3e1af06001770a302_camp,
  min=1,
  max=1,
}
army['5fb1b9f3e1af06001770a302']={
  data={
    name='Early Ming Chinese  1350 to 1419 AD'
  },
  g_base_definitions[g_str_5fb1b9f3e1af06001770a302_camp],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb6d],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb6e],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb55_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb55],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb58_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb58],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5a_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5a],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5d_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5d],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb5f],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb62],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb63],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb65],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb66],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb68],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb69],
  g_base_definitions[g_str_5fb1ba41e1af06001770fb6b],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a302"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
