-- 5fb1b9e2e1af060017709910 Old Saxon and related tribes  250 to 804 AD

army['5fb1b9e2e1af060017709910']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Marsh',
      'Arable',
      'Forest',
    },
    name='Old Saxon and related tribes  250 to 804 AD',
    id='5fb1b9e2e1af060017709910',
    dateRange={
      startDate=250,
      endDate=804,
    },
  },
  g_base_definitions[g_str_615351a703385c0016b865ed_general],
  g_base_definitions[g_str_615351a703385c0016b865ed_general_mounted_mobile_infantry],
  g_base_definitions[g_str_615351a703385c0016b865ed_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_615351a703385c0016b865ed],
  g_base_definitions[g_str_615351a703385c0016b865ed_mounted_mobile_infantry],
  g_base_definitions[g_str_615351a703385c0016b865ed_dismounted_mobile_infantry],
  g_base_definitions[g_str_615351a703385c0016b865f0],
  g_base_definitions[g_str_615351a703385c0016b865f2],
  g_base_definitions[g_str_615351a703385c0016b865f4],
  g_base_definitions[g_str_615351a703385c0016b865f6],
  g_base_definitions[g_str_5fb1b9e2e1af060017709910_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af060017709910"] = army["5fb1b9e2e1af060017709910"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Old Saxon and related tribes  250 to 804 AD"] = army["5fb1b9e2e1af060017709910"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Old Saxon and related tribes  250 to 804 AD"] = army["5fb1b9e2e1af060017709910"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Old Saxon and related tribes  250 to 804 AD"] = army["5fb1b9e2e1af060017709910"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Old Saxon and related tribes  250 to 804 AD"] = army["5fb1b9e2e1af060017709910"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Old Saxon and related tribes  250 to 804 AD"] = army["5fb1b9e2e1af060017709910"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af060017709910"] = {}
army_dates["5fb1b9e2e1af060017709910"]["250 AD to 804 AD"] = {
  startDate=250,
  endDate=804
}
army_dates["5fb1b9e2e1af060017709910"]["250 AD to 552 AD"] = {
  startDate=250,
  endDate=552
}
army_dates["5fb1b9e2e1af060017709910"]["553 AD to 579 AD"] = {
  startDate=553,
  endDate=579
}
army_dates["5fb1b9e2e1af060017709910"]["580 AD to 768 AD"] = {
  startDate=580,
  endDate=768
}
army_dates["5fb1b9e2e1af060017709910"]["769 AD to 788 AD"] = {
  startDate=769,
  endDate=788
}
army_dates["5fb1b9e2e1af060017709910"]["789 AD to 804 AD"] = {
  startDate=789,
  endDate=804
}
