-- 5fb1b9e2e1af0600177098cf Ostrogoths 376 AD  376 to 376 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ce1af06001770d469_general='5fb1ba2ce1af06001770d469_general'
g_base_definitions[g_str_5fb1ba2ce1af06001770d469_general]={
  id=g_str_5fb1ba2ce1af06001770d469_general,
  name='Knights General',
  min=6,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba2ce1af06001770d469='5fb1ba2ce1af06001770d469'
g_base_definitions[g_str_5fb1ba2ce1af06001770d469]={
  id=g_str_5fb1ba2ce1af06001770d469,
  name='Knights',
  min=6,
  max=12,
  description='Noble horsemen',
  troop_type="Knights",
}
g_str_5fb1ba2ce1af06001770d46b='5fb1ba2ce1af06001770d46b'
g_base_definitions[g_str_5fb1ba2ce1af06001770d46b]={
  id=g_str_5fb1ba2ce1af06001770d46b,
  name='Bow Levy',
  min=0,
  max=10,
  description='Close-order bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba2ce1af06001770d46d='5fb1ba2ce1af06001770d46d'
g_base_definitions[g_str_5fb1ba2ce1af06001770d46d]={
  id=g_str_5fb1ba2ce1af06001770d46d,
  name='Horse Bow',
  min=0,
  max=1,
  description='Mercenary Hun horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1b9e2e1af0600177098cf_camp='5fb1b9e2e1af0600177098cf_camp'
g_base_definitions[g_str_5fb1b9e2e1af0600177098cf_camp]={
  name='Camp',
  id=g_str_5fb1b9e2e1af0600177098cf_camp,
  min=1,
  max=1,
}
army['5fb1b9e2e1af0600177098cf']={
  data={
    name='Ostrogoths 376 AD  376 to 376 AD'
  },
  g_base_definitions[g_str_5fb1b9e2e1af0600177098cf_camp],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d469_general],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d469],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d46b],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d46d],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098cf"] = army["5fb1b9e2e1af0600177098cf"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Ostrogoths 376 AD  376 to 376 AD"] = army["5fb1b9e2e1af0600177098cf"]
