-- 5fb1b9ede1af060017709f35 Iqshidid Egyptian  935 to 970 AD

army['5fb1b9ede1af060017709f35']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Delta',
      'Dry',
    },
    name='Iqshidid Egyptian  935 to 970 AD',
    id='5fb1b9ede1af060017709f35',
    dateRange={
      startDate=935,
      endDate=970,
    },
  },
  g_base_definitions[g_str_615351b003385c0016b87d5f_general],
  g_base_definitions[g_str_615351b003385c0016b87d5f_general_mounted],
  g_base_definitions[g_str_615351b003385c0016b87d5f_general_dismounted],
  g_base_definitions[g_str_615351b003385c0016b87d5f_general_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87d5f],
  g_base_definitions[g_str_615351b003385c0016b87d5f_mounted],
  g_base_definitions[g_str_615351b003385c0016b87d5f_dismounted],
  g_base_definitions[g_str_615351b003385c0016b87d5f_shower_shooting],
  g_base_definitions[g_str_615351b003385c0016b87d63],
  g_base_definitions[g_str_615351b003385c0016b87d65],
  g_base_definitions[g_str_615351b003385c0016b87d67],
  g_base_definitions[g_str_615351b003385c0016b87d68],
  g_base_definitions[g_str_615351b003385c0016b87d6a],
  g_base_definitions[g_str_615351b003385c0016b87d6c],
  g_base_definitions[g_str_615351b003385c0016b87d6e],
  g_base_definitions[g_str_615351b003385c0016b87d70_general],
  g_base_definitions[g_str_615351b003385c0016b87d70],
  g_base_definitions[g_str_615351b003385c0016b87d73],
  g_base_definitions[g_str_615351b003385c0016b87d73_mounted_mobile_infantry],
  g_base_definitions[g_str_615351b003385c0016b87d73_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp_fortified],
  g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f35"] = army["5fb1b9ede1af060017709f35"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Iqshidid Egyptian  935 to 970 AD"] = army["5fb1b9ede1af060017709f35"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Iqshidid Egyptian  935 to 970 AD"] = army["5fb1b9ede1af060017709f35"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f35"] = {}
army_dates["5fb1b9ede1af060017709f35"]["935 AD to 970 AD"] = {
  startDate=935,
  endDate=970
}
army_dates["5fb1b9ede1af060017709f35"]["935 AD to 969 AD"] = {
  startDate=935,
  endDate=969
}
army_dates["5fb1b9ede1af060017709f35"]["970 AD"] = {
  startDate=970,
  endDate=970
}
