-- 5fb1b9dae1af060017709444 Neo-Babylonian Empire  604 to 539 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba22e1af06001770c365_general='5fb1ba22e1af06001770c365_general'
g_base_definitions[g_str_5fb1ba22e1af06001770c365_general]={
  id=g_str_5fb1ba22e1af06001770c365_general,
  name='Chariots General',
  min=1,
  max=1,
  description='4-horse chariots with three crewmen',
  general=true,
  troop_type="Chariots",
}
g_str_5fb1ba22e1af06001770c365='5fb1ba22e1af06001770c365'
g_base_definitions[g_str_5fb1ba22e1af06001770c365]={
  id=g_str_5fb1ba22e1af06001770c365,
  name='Chariots',
  min=1,
  max=2,
  description='4-horse chariots with three crewmen',
  troop_type="Chariots",
}
g_str_5fb1ba22e1af06001770c367='5fb1ba22e1af06001770c367'
g_base_definitions[g_str_5fb1ba22e1af06001770c367]={
  id=g_str_5fb1ba22e1af06001770c367,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='Qurbuti horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba22e1af06001770c369='5fb1ba22e1af06001770c369'
g_base_definitions[g_str_5fb1ba22e1af06001770c369]={
  id=g_str_5fb1ba22e1af06001770c369,
  name='Bad Horse',
  min=0,
  max=1,
  description='Qurbuti, Chaldean, Aramaean, or militia horsemen',
  troop_type="Bad Horse",
}
g_str_5fb1ba22e1af06001770c36b='5fb1ba22e1af06001770c36b'
g_base_definitions[g_str_5fb1ba22e1af06001770c36b]={
  id=g_str_5fb1ba22e1af06001770c36b,
  name='Spears',
  min=0,
  max=1,
  description='Qurbuti infantry',
  troop_type="Spears",
}
g_str_5fb1ba22e1af06001770c36c='5fb1ba22e1af06001770c36c'
g_base_definitions[g_str_5fb1ba22e1af06001770c36c]={
  id=g_str_5fb1ba22e1af06001770c36c,
  name='Light Foot',
  min=0,
  max=1,
  description='Qurbuti infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba22e1af06001770c36e='5fb1ba22e1af06001770c36e'
g_base_definitions[g_str_5fb1ba22e1af06001770c36e]={
  id=g_str_5fb1ba22e1af06001770c36e,
  name='Bow Levy',
  min=3,
  max=8,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba22e1af06001770c370='5fb1ba22e1af06001770c370'
g_base_definitions[g_str_5fb1ba22e1af06001770c370]={
  id=g_str_5fb1ba22e1af06001770c370,
  name='Pavisiers',
  min=0,
  max=5,
  description='Bowmen behind long-shield spearmen',
  troop_type="Pavisiers",
}
g_str_5fb1ba22e1af06001770c373='5fb1ba22e1af06001770c373'
g_base_definitions[g_str_5fb1ba22e1af06001770c373]={
  id=g_str_5fb1ba22e1af06001770c373,
  name='Rabble',
  min=0,
  max=1,
  description='Levy infantry',
  troop_type="Rabble",
}
g_str_5fb1ba22e1af06001770c375='5fb1ba22e1af06001770c375'
g_base_definitions[g_str_5fb1ba22e1af06001770c375]={
  id=g_str_5fb1ba22e1af06001770c375,
  name='Horde',
  min=0,
  max=8,
  description='Reserves and emergency levies',
  troop_type="Horde",
}
g_str_5fb1b9dae1af060017709444_camp='5fb1b9dae1af060017709444_camp'
g_base_definitions[g_str_5fb1b9dae1af060017709444_camp]={
  id=g_str_5fb1b9dae1af060017709444_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dae1af060017709444_camp_pack_train='5fb1b9dae1af060017709444_camp_pack_train'
g_base_definitions[g_str_5fb1b9dae1af060017709444_camp_pack_train]={
  id=g_str_5fb1b9dae1af060017709444_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dae1af060017709444']={
  data={
    name='Neo-Babylonian Empire  604 to 539 BC'
  },
  g_base_definitions[g_str_5fb1ba22e1af06001770c365_general],
  g_base_definitions[g_str_5fb1ba22e1af06001770c365],
  g_base_definitions[g_str_5fb1ba22e1af06001770c367],
  g_base_definitions[g_str_5fb1ba22e1af06001770c369],
  g_base_definitions[g_str_5fb1ba22e1af06001770c36b],
  g_base_definitions[g_str_5fb1ba22e1af06001770c36c],
  g_base_definitions[g_str_5fb1ba22e1af06001770c36e],
  g_base_definitions[g_str_5fb1ba22e1af06001770c370],
  g_base_definitions[g_str_5fb1ba22e1af06001770c373],
  g_base_definitions[g_str_5fb1ba22e1af06001770c375],
  g_base_definitions[g_str_5fb1b9dae1af060017709444_camp],
  g_base_definitions[g_str_5fb1b9dae1af060017709444_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af060017709444"] = army["5fb1b9dae1af060017709444"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Neo-Babylonian Empire  604 to 539 BC"] = army["5fb1b9dae1af060017709444"]
