-- 5fb1b9f1e1af06001770a17c Early Warring States Chinese  480 to 356 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3ee1af06001770f58f_general='5fb1ba3ee1af06001770f58f_general'
g_base_definitions[g_str_5fb1ba3ee1af06001770f58f_general]={
  id=g_str_5fb1ba3ee1af06001770f58f_general,
  name='Chariots General',
  min=1,
  max=1,
  description='4-horse chariots',
  general=true,
  troop_type="Chariots",
  troop_option_id="5fb1ba3ee1af06001770f58e",
}
g_str_5fb1ba3ee1af06001770f58f='5fb1ba3ee1af06001770f58f'
g_base_definitions[g_str_5fb1ba3ee1af06001770f58f]={
  id=g_str_5fb1ba3ee1af06001770f58f,
  name='Chariots',
  min=1,
  max=2,
  description='4-horse chariots',
  troop_type="Chariots",
  troop_option_id="5fb1ba3ee1af06001770f58e",
}
g_str_5fb1ba3ee1af06001770f591='5fb1ba3ee1af06001770f591'
g_base_definitions[g_str_5fb1ba3ee1af06001770f591]={
  id=g_str_5fb1ba3ee1af06001770f591,
  name='Light Spear',
  min=6,
  max=13,
  description='Infantry armed with halberds or spears',
  troop_type="Light Spear",
  troop_option_id="5fb1ba3ee1af06001770f590",
}
g_str_5fb1ba3ee1af06001770f594='5fb1ba3ee1af06001770f594'
g_base_definitions[g_str_5fb1ba3ee1af06001770f594]={
  id=g_str_5fb1ba3ee1af06001770f594,
  name='Skirmishers',
  min=1,
  max=4,
  description='Supporting bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3ee1af06001770f593",
}
g_str_5fb1ba3ee1af06001770f597='5fb1ba3ee1af06001770f597'
g_base_definitions[g_str_5fb1ba3ee1af06001770f597]={
  id=g_str_5fb1ba3ee1af06001770f597,
  name='Archers',
  min=0,
  max=1,
  description='Formed crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba3ee1af06001770f596",
}
g_str_5fb1ba3ee1af06001770f599='5fb1ba3ee1af06001770f599'
g_base_definitions[g_str_5fb1ba3ee1af06001770f599]={
  id=g_str_5fb1ba3ee1af06001770f599,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen or crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3ee1af06001770f598",
}
g_str_5fb1ba3ee1af06001770f59b='5fb1ba3ee1af06001770f59b'
g_base_definitions[g_str_5fb1ba3ee1af06001770f59b]={
  id=g_str_5fb1ba3ee1af06001770f59b,
  name='Warband',
  min=0,
  max=2,
  description='Southern fierce tribesmen',
  troop_type="Warband",
  troop_option_id="5fb1ba3ee1af06001770f59a",
}
g_str_5fb1b9f1e1af06001770a17c_camp='5fb1b9f1e1af06001770a17c_camp'
g_base_definitions[g_str_5fb1b9f1e1af06001770a17c_camp]={
  id=g_str_5fb1b9f1e1af06001770a17c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f1e1af06001770a17c_camp_fortified='5fb1b9f1e1af06001770a17c_camp_fortified'
g_base_definitions[g_str_5fb1b9f1e1af06001770a17c_camp_fortified]={
  id=g_str_5fb1b9f1e1af06001770a17c_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
army['5fb1b9f1e1af06001770a17c']={
  data={
    name='Early Warring States Chinese  480 to 356 BC',
    id='5fb1b9f1e1af06001770a17c',
    army_id='5fb1b9f1e1af06001770a17c'
  },
  g_base_definitions[g_str_5fb1ba3ee1af06001770f58f_general],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f58f],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f591],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f594],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f597],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f599],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f59b],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a17c_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a17c_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a17c"] = army["5fb1b9f1e1af06001770a17c"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Early Warring States Chinese  480 to 356 BC"] = army["5fb1b9f1e1af06001770a17c"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Early Warring States Chinese  480 to 356 BC"] = army["5fb1b9f1e1af06001770a17c"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Early Warring States Chinese  480 to 356 BC"] = army["5fb1b9f1e1af06001770a17c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Warring States Chinese  480 to 356 BC"] = army["5fb1b9f1e1af06001770a17c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a17c"] = {}
army_dates["5fb1b9f1e1af06001770a17c"]["480 BC to 356 BC"] ="5fb1b9f1e1af06001770a17c"
