troop_options['5fb1ba44e1af06001770fe99'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1535,
    endDate=1572,
  }
}
troop_options['5fb1ba44e1af06001770fe9b'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1535,
    endDate=1572,
  }
}
troop_options['5fb1ba44e1af06001770fe9d'] = {
  min=4,
  max=12,
  dateRange={
    startDate=1535,
    endDate=1572,
  }
}
troop_options['5fb1ba44e1af06001770fe9f'] = {
  min=0,
  max=8,
  dateRange={
    startDate=1535,
    endDate=1572,
  }
}
-- allies
