-- 5fb1b9dee1af0600177096c8 Attalid Pergamene  263 to 129 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba29e1af06001770cd1a_general='5fb1ba29e1af06001770cd1a_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd1a_general]={
  id=g_str_5fb1ba29e1af06001770cd1a_general,
  name='Knights General',
  min=1,
  max=1,
  description='Lancers',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba29e1af06001770cd1a='5fb1ba29e1af06001770cd1a'
g_base_definitions[g_str_5fb1ba29e1af06001770cd1a]={
  id=g_str_5fb1ba29e1af06001770cd1a,
  name='Knights',
  min=1,
  max=1,
  description='Lancers',
  troop_type="Knights",
}
g_str_5fb1ba29e1af06001770cd1b_general='5fb1ba29e1af06001770cd1b_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd1b_general]={
  id=g_str_5fb1ba29e1af06001770cd1b_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Lancers',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba29e1af06001770cd1b='5fb1ba29e1af06001770cd1b'
g_base_definitions[g_str_5fb1ba29e1af06001770cd1b]={
  id=g_str_5fb1ba29e1af06001770cd1b,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='Lancers',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba29e1af06001770cd1d_general='5fb1ba29e1af06001770cd1d_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd1d_general]={
  id=g_str_5fb1ba29e1af06001770cd1d_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Pergamene light horsemen or Galatian horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba29e1af06001770cd1d='5fb1ba29e1af06001770cd1d'
g_base_definitions[g_str_5fb1ba29e1af06001770cd1d]={
  id=g_str_5fb1ba29e1af06001770cd1d,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Pergamene light horsemen or Galatian horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba29e1af06001770cd1f='5fb1ba29e1af06001770cd1f'
g_base_definitions[g_str_5fb1ba29e1af06001770cd1f]={
  id=g_str_5fb1ba29e1af06001770cd1f,
  name='Light Foot',
  min=2,
  max=4,
  description='Mercenary peltasts',
  troop_type="Light Foot",
}
g_str_5fb1ba29e1af06001770cd21='5fb1ba29e1af06001770cd21'
g_base_definitions[g_str_5fb1ba29e1af06001770cd21]={
  id=g_str_5fb1ba29e1af06001770cd21,
  name='Skirmishers',
  min=1,
  max=2,
  description='Cretan bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba29e1af06001770cd23='5fb1ba29e1af06001770cd23'
g_base_definitions[g_str_5fb1ba29e1af06001770cd23]={
  id=g_str_5fb1ba29e1af06001770cd23,
  name='Skirmishers',
  min=1,
  max=1,
  description='Trallian slingers',
  troop_type="Skirmishers",
}
g_str_5fb1ba29e1af06001770cd25='5fb1ba29e1af06001770cd25'
g_base_definitions[g_str_5fb1ba29e1af06001770cd25]={
  id=g_str_5fb1ba29e1af06001770cd25,
  name='Warriors',
  min=0,
  max=1,
  description='Galatian fierce fighters',
  troop_type="Warriors",
}
g_str_5fb1ba29e1af06001770cd27='5fb1ba29e1af06001770cd27'
g_base_definitions[g_str_5fb1ba29e1af06001770cd27]={
  id=g_str_5fb1ba29e1af06001770cd27,
  name='Light Foot',
  min=0,
  max=3,
  description='Pergamene citizen infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba29e1af06001770cd29='5fb1ba29e1af06001770cd29'
g_base_definitions[g_str_5fb1ba29e1af06001770cd29]={
  id=g_str_5fb1ba29e1af06001770cd29,
  name='Light Foot',
  min=0,
  max=3,
  description='Mysian or Masdyene infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba29e1af06001770cd2b='5fb1ba29e1af06001770cd2b'
g_base_definitions[g_str_5fb1ba29e1af06001770cd2b]={
  id=g_str_5fb1ba29e1af06001770cd2b,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt-shooters and stone-throwers',
  troop_type="Artillery",
}
g_str_5fb1ba29e1af06001770cd2e='5fb1ba29e1af06001770cd2e'
g_base_definitions[g_str_5fb1ba29e1af06001770cd2e]={
  id=g_str_5fb1ba29e1af06001770cd2e,
  name='Cataphracts',
  min=0,
  max=1,
  description='Formerly Seleucid horsemen',
  troop_type="Cataphracts",
}
g_str_5fb1ba29e1af06001770cd31='5fb1ba29e1af06001770cd31'
g_base_definitions[g_str_5fb1ba29e1af06001770cd31]={
  id=g_str_5fb1ba29e1af06001770cd31,
  name='Pikes',
  min=1,
  max=2,
  description='Formerly Seleucid phalanx',
  troop_type="Pikes",
}
g_str_5fb1ba29e1af06001770cd31_elephant_screen='5fb1ba29e1af06001770cd31_elephant_screen'
g_base_definitions[g_str_5fb1ba29e1af06001770cd31_elephant_screen]={
  id=g_str_5fb1ba29e1af06001770cd31_elephant_screen,
  name='Pikes Elephant Screen',
  min=1,
  max=2,
  description='Formerly Seleucid phalanx\nElephant Screen',
  elephant_screen=true,
  troop_type="Pikes",
}
g_str_5fb1ba29e1af06001770cd35='5fb1ba29e1af06001770cd35'
g_base_definitions[g_str_5fb1ba29e1af06001770cd35]={
  id=g_str_5fb1ba29e1af06001770cd35,
  name='Elephants',
  min=0,
  max=1,
  description='Formerly Seleucid War elephants',
  troop_type="Elephants",
}
g_str_5fb1b9dee1af0600177096c8_camp='5fb1b9dee1af0600177096c8_camp'
g_base_definitions[g_str_5fb1b9dee1af0600177096c8_camp]={
  id=g_str_5fb1b9dee1af0600177096c8_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dee1af0600177096c8_camp_pack_train='5fb1b9dee1af0600177096c8_camp_pack_train'
g_base_definitions[g_str_5fb1b9dee1af0600177096c8_camp_pack_train]={
  id=g_str_5fb1b9dee1af0600177096c8_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dee1af0600177096c8']={
  data={
    name='Attalid Pergamene  263 to 129 BC'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cd1a_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd1a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd1b_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd1b],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd1d_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd1d],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd1f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd21],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd23],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd25],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd27],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd29],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd2b],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd2e],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd31],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd31_elephant_screen],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd35],
  g_base_definitions[g_str_5fb1b9dee1af0600177096c8_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096c8_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096c8"] = army["5fb1b9dee1af0600177096c8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Attalid Pergamene  263 to 129 BC"] = army["5fb1b9dee1af0600177096c8"]
