g_str_5fb1ba29e1af06001770cd6f_general='5fb1ba29e1af06001770cd6f_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd6f_general]={
  id=g_str_5fb1ba29e1af06001770cd6f_general,
  name='Knights General',
  min=0,
  max=1,
  description='Charging noble horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd6e",
}
g_str_5fb1ba29e1af06001770cd6f='5fb1ba29e1af06001770cd6f'
g_base_definitions[g_str_5fb1ba29e1af06001770cd6f]={
  id=g_str_5fb1ba29e1af06001770cd6f,
  name='Knights',
  min=0,
  max=2,
  description='Charging noble horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd6e",
}
g_str_5fb1ba29e1af06001770cd71_general='5fb1ba29e1af06001770cd71_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd71_general]={
  id=g_str_5fb1ba29e1af06001770cd71_general,
  name='Javelin Cavalry General',
  min=4,
  max=1,
  description='Horsemen with light spears',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd70",
}
g_str_5fb1ba29e1af06001770cd71='5fb1ba29e1af06001770cd71'
g_base_definitions[g_str_5fb1ba29e1af06001770cd71]={
  id=g_str_5fb1ba29e1af06001770cd71,
  name='Javelin Cavalry',
  min=4,
  max=12,
  description='Horsemen with light spears',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd70",
}
g_str_5fb1ba29e1af06001770cd73='5fb1ba29e1af06001770cd73'
g_base_definitions[g_str_5fb1ba29e1af06001770cd73]={
  id=g_str_5fb1ba29e1af06001770cd73,
  name='Horse Bow',
  min=0,
  max=1,
  description='Mounted scouts and skirmishing horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba29e1af06001770cd72",
}
g_str_5fb1ba29e1af06001770cd75='5fb1ba29e1af06001770cd75'
g_base_definitions[g_str_5fb1ba29e1af06001770cd75]={
  id=g_str_5fb1ba29e1af06001770cd75,
  name='Bow Levy',
  min=0,
  max=4,
  description='Peasant bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba29e1af06001770cd74",
}
g_str_5fb1b9dfe1af0600177096de_camp='5fb1b9dfe1af0600177096de_camp'
g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp]={
  id=g_str_5fb1b9dfe1af0600177096de_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af0600177096de_camp_fortified='5fb1b9dfe1af0600177096de_camp_fortified'
g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp_fortified]={
  id=g_str_5fb1b9dfe1af0600177096de_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba29e1af06001770cd6f_general='5fb1ba29e1af06001770cd6f_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd6f_general]={
  id=g_str_5fb1ba29e1af06001770cd6f_general,
  name='Knights General',
  min=0,
  max=1,
  description='Charging noble horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd6e",
}
g_str_5fb1ba29e1af06001770cd6f='5fb1ba29e1af06001770cd6f'
g_base_definitions[g_str_5fb1ba29e1af06001770cd6f]={
  id=g_str_5fb1ba29e1af06001770cd6f,
  name='Knights',
  min=0,
  max=2,
  description='Charging noble horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd6e",
}
g_str_5fb1ba29e1af06001770cd71_general='5fb1ba29e1af06001770cd71_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd71_general]={
  id=g_str_5fb1ba29e1af06001770cd71_general,
  name='Javelin Cavalry General',
  min=4,
  max=1,
  description='Horsemen with light spears',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd70",
}
g_str_5fb1ba29e1af06001770cd71='5fb1ba29e1af06001770cd71'
g_base_definitions[g_str_5fb1ba29e1af06001770cd71]={
  id=g_str_5fb1ba29e1af06001770cd71,
  name='Javelin Cavalry',
  min=4,
  max=12,
  description='Horsemen with light spears',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd70",
}
g_str_5fb1ba29e1af06001770cd73='5fb1ba29e1af06001770cd73'
g_base_definitions[g_str_5fb1ba29e1af06001770cd73]={
  id=g_str_5fb1ba29e1af06001770cd73,
  name='Horse Bow',
  min=0,
  max=1,
  description='Mounted scouts and skirmishing horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba29e1af06001770cd72",
}
g_str_5fb1ba29e1af06001770cd75='5fb1ba29e1af06001770cd75'
g_base_definitions[g_str_5fb1ba29e1af06001770cd75]={
  id=g_str_5fb1ba29e1af06001770cd75,
  name='Bow Levy',
  min=0,
  max=4,
  description='Peasant bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba29e1af06001770cd74",
}
g_str_5fb1b9dfe1af0600177096de_camp='5fb1b9dfe1af0600177096de_camp'
g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp]={
  id=g_str_5fb1b9dfe1af0600177096de_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af0600177096de_camp_fortified='5fb1b9dfe1af0600177096de_camp_fortified'
g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp_fortified]={
  id=g_str_5fb1b9dfe1af0600177096de_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba29e1af06001770cd6f_general='5fb1ba29e1af06001770cd6f_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd6f_general]={
  id=g_str_5fb1ba29e1af06001770cd6f_general,
  name='Knights General',
  min=0,
  max=1,
  description='Charging noble horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd6e",
}
g_str_5fb1ba29e1af06001770cd6f='5fb1ba29e1af06001770cd6f'
g_base_definitions[g_str_5fb1ba29e1af06001770cd6f]={
  id=g_str_5fb1ba29e1af06001770cd6f,
  name='Knights',
  min=0,
  max=2,
  description='Charging noble horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba29e1af06001770cd6e",
}
g_str_5fb1ba29e1af06001770cd71_general='5fb1ba29e1af06001770cd71_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd71_general]={
  id=g_str_5fb1ba29e1af06001770cd71_general,
  name='Javelin Cavalry General',
  min=4,
  max=1,
  description='Horsemen with light spears',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd70",
}
g_str_5fb1ba29e1af06001770cd71='5fb1ba29e1af06001770cd71'
g_base_definitions[g_str_5fb1ba29e1af06001770cd71]={
  id=g_str_5fb1ba29e1af06001770cd71,
  name='Javelin Cavalry',
  min=4,
  max=12,
  description='Horsemen with light spears',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd70",
}
g_str_5fb1ba29e1af06001770cd73='5fb1ba29e1af06001770cd73'
g_base_definitions[g_str_5fb1ba29e1af06001770cd73]={
  id=g_str_5fb1ba29e1af06001770cd73,
  name='Horse Bow',
  min=0,
  max=1,
  description='Mounted scouts and skirmishing horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba29e1af06001770cd72",
}
g_str_5fb1ba29e1af06001770cd75='5fb1ba29e1af06001770cd75'
g_base_definitions[g_str_5fb1ba29e1af06001770cd75]={
  id=g_str_5fb1ba29e1af06001770cd75,
  name='Bow Levy',
  min=0,
  max=4,
  description='Peasant bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba29e1af06001770cd74",
}
g_str_5fb1b9dfe1af0600177096de_camp='5fb1b9dfe1af0600177096de_camp'
g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp]={
  id=g_str_5fb1b9dfe1af0600177096de_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af0600177096de_camp_fortified='5fb1b9dfe1af0600177096de_camp_fortified'
g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp_fortified]={
  id=g_str_5fb1b9dfe1af0600177096de_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
