troop_options['5fb1ba35e1af06001770e479'] = {
  min=3,
  max=6,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e47b'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e47d'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e47f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e481'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e483'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e486'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e488'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e48b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e48e'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
troop_options['5fb1ba35e1af06001770e490'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1320,
    endDate=1362,
  }
}
-- allies
