troop_options['5fb1ba34e1af06001770e293'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e295'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e297'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e299'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e29c'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2a0'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2a3'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2a5'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2a7'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2a9'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2ac'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2ae'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1450,
    endDate=1462,
  }
}
troop_options['5fb1ba34e1af06001770e2b1'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
troop_options['5fb1ba34e1af06001770e2b5'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1440,
    endDate=1493,
  }
}
-- allies
