-- 5fb1b9dce1af060017709581 Later Libyan  664 BC to 70 AD

army['5fb1b9dce1af060017709581']={
  data={
    invasionRatings={
      {
        value=1,
        note='',
      },
    },
    name='Later Libyan  664 BC to 70 AD',
    id='5fb1b9dce1af060017709581',
    dateRange={
      startDate=-664,
      endDate=70,
    }
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c83a_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c83a],
  g_base_definitions[g_str_5fb1ba26e1af06001770c83c],
  g_base_definitions[g_str_5fb1ba26e1af06001770c83e],
  g_base_definitions[g_str_5fb1ba26e1af06001770c840],
  g_base_definitions[g_str_5fb1b9dce1af060017709581_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709581_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709581"] = army["5fb1b9dce1af060017709581"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Later Libyan  664 BC to 70 AD"] = army["5fb1b9dce1af060017709581"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Later Libyan  664 BC to 70 AD"] = army["5fb1b9dce1af060017709581"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Later Libyan  664 BC to 70 AD"] = army["5fb1b9dce1af060017709581"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Libyan  664 BC to 70 AD"] = army["5fb1b9dce1af060017709581"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709581"] = {}
army_dates["5fb1b9dce1af060017709581"]["664 BC to 70 AD"] = {
  startDate=-664,
  endDate=70
}
