troop_options['5fb1ba3de1af06001770f2ea'] = {
  min=2,
  max=3,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2ed'] = {
  min=2,
  max=4,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2ef'] = {
  min=0,
  max=3,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2f2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2f4'] = {
  min=0,
  max=1,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2f6'] = {
  min=0,
  max=1,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2f9'] = {
  min=1,
  max=2,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2fc'] = {
  min=0,
  max=3,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f2ff'] = {
  min=4,
  max=8,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
troop_options['5fb1ba3de1af06001770f302'] = {
  min=0,
  max=2,
  dateRange={
    startDate=747,
    endDate=1303,
  }
}
-- allies
