-- 5fb1b9e2e1af0600177098ee Early Patrician Roman West: Africa  408 to 441 AD

army['5fb1b9e2e1af0600177098ee']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Early Patrician Roman West: Africa  408 to 441 AD',
    id='5fb1b9e2e1af0600177098ee',
    dateRange={
      startDate=408,
      endDate=441,
    },
  },
  g_base_definitions[g_str_615351a703385c0016b8656b_general],
  g_base_definitions[g_str_615351a703385c0016b8656b],
  g_base_definitions[g_str_615351a703385c0016b8656d_general],
  g_base_definitions[g_str_615351a703385c0016b8656d],
  g_base_definitions[g_str_615351a703385c0016b8656f],
  g_base_definitions[g_str_615351a703385c0016b86573],
  g_base_definitions[g_str_615351a703385c0016b86576],
  g_base_definitions[g_str_615351a703385c0016b86578],
  g_base_definitions[g_str_615351a703385c0016b8657b],
  g_base_definitions[g_str_615351a703385c0016b8657e],
  g_base_definitions[g_str_615351a703385c0016b86580_general],
  g_base_definitions[g_str_615351a703385c0016b86580],
  g_base_definitions[g_str_615351a703385c0016b86582],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098ee_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098ee_camp_fortified],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098ee_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098ee"] = army["5fb1b9e2e1af0600177098ee"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Early Patrician Roman West: Africa  408 to 441 AD"] = army["5fb1b9e2e1af0600177098ee"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Patrician Roman West: Africa  408 to 441 AD"] = army["5fb1b9e2e1af0600177098ee"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098ee"] = {}
army_dates["5fb1b9e2e1af0600177098ee"]["408 AD to 441 AD"] = {
  startDate=408,
  endDate=441
}
