-- 5fb1b9e2e1af06001770994f Middle Sassanid Persian  350 to 576 AD

army['5fb1b9e2e1af06001770994f']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
      3,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Middle Sassanid Persian  350 to 576 AD',
    id='5fb1b9e2e1af06001770994f',
    dateRange={
      startDate=350,
      endDate=576,
    }
  },
  g_base_definitions[g_str_5fb1ba2de1af06001770d646_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d646],
  g_base_definitions[g_str_5fb1ba2de1af06001770d648_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d648_general_shower_shooting],
  g_base_definitions[g_str_5fb1ba2de1af06001770d648],
  g_base_definitions[g_str_5fb1ba2de1af06001770d648_shower_shooting],
  g_base_definitions[g_str_5fb1ba2de1af06001770d64b],
  g_base_definitions[g_str_5fb1ba2de1af06001770d64d],
  g_base_definitions[g_str_5fb1ba2de1af06001770d64d_elephant_screen],
  g_base_definitions[g_str_5fb1ba2de1af06001770d650],
  g_base_definitions[g_str_5fb1ba2de1af06001770d650_elephant_screen],
  g_base_definitions[g_str_5fb1ba2de1af06001770d653],
  g_base_definitions[g_str_5fb1ba2de1af06001770d655],
  g_base_definitions[g_str_5fb1ba2de1af06001770d655_elephant_screen],
  g_base_definitions[g_str_5fb1ba2de1af06001770d656],
  g_base_definitions[g_str_5fb1ba2de1af06001770d656_elephant_screen],
  g_base_definitions[g_str_5fb1ba2de1af06001770d659],
  g_base_definitions[g_str_5fb1ba2de1af06001770d65c],
  g_base_definitions[g_str_5fb1ba2de1af06001770d65d],
  g_base_definitions[g_str_5fb1ba2de1af06001770d65f],
  g_base_definitions[g_str_5fb1ba2de1af06001770d660],
  g_base_definitions[g_str_5fb1ba2de1af06001770d663],
  g_base_definitions[g_str_5fb1b9e2e1af06001770994f_camp],
  g_base_definitions[g_str_5fb1b9e2e1af06001770994f_camp_fortified],
  g_base_definitions[g_str_5fb1b9e2e1af06001770994f_camp_pack_train],
  g_base_definitions[g_str_5fb1b9e2e1af06001770994f_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af06001770994f"] = army["5fb1b9e2e1af06001770994f"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Middle Sassanid Persian  350 to 576 AD"] = army["5fb1b9e2e1af06001770994f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Middle Sassanid Persian  350 to 576 AD"] = army["5fb1b9e2e1af06001770994f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af06001770994f"] = {}
army_dates["5fb1b9e2e1af06001770994f"]["350 AD to 576 AD"] = {
  startDate=350,
  endDate=576
}
army_dates["5fb1b9e2e1af06001770994f"]["350 AD to 355 AD"] = {
  startDate=350,
  endDate=355
}
army_dates["5fb1b9e2e1af06001770994f"]["356 AD to 379 AD"] = {
  startDate=356,
  endDate=379
}
army_dates["5fb1b9e2e1af06001770994f"]["380 AD to 427 AD"] = {
  startDate=380,
  endDate=427
}
army_dates["5fb1b9e2e1af06001770994f"]["428 AD"] = {
  startDate=428,
  endDate=428
}
army_dates["5fb1b9e2e1af06001770994f"]["429 AD to 477 AD"] = {
  startDate=429,
  endDate=477
}
army_dates["5fb1b9e2e1af06001770994f"]["478 AD to 514 AD"] = {
  startDate=478,
  endDate=514
}
army_dates["5fb1b9e2e1af06001770994f"]["515 AD to 530 AD"] = {
  startDate=515,
  endDate=530
}
army_dates["5fb1b9e2e1af06001770994f"]["531 AD to 549 AD"] = {
  startDate=531,
  endDate=549
}
army_dates["5fb1b9e2e1af06001770994f"]["550 AD to 556 AD"] = {
  startDate=550,
  endDate=556
}
army_dates["5fb1b9e2e1af06001770994f"]["557 AD to 558 AD"] = {
  startDate=557,
  endDate=558
}
army_dates["5fb1b9e2e1af06001770994f"]["559 AD to 568 AD"] = {
  startDate=559,
  endDate=568
}
army_dates["5fb1b9e2e1af06001770994f"]["569 AD to 571 AD"] = {
  startDate=569,
  endDate=571
}
army_dates["5fb1b9e2e1af06001770994f"]["572 AD to 576 AD"] = {
  startDate=572,
  endDate=576
}
