-- 5fb1b9dae1af0600177093bb Later Mycenaean and Trojan War  1250 to 1190 BC

army['5fb1b9dae1af0600177093bb']={
  data={
    name='Later Mycenaean and Trojan War  1250 to 1190 BC',
    id='5fb1b9dae1af0600177093bb',
    army_id='5fb1b9dae1af0600177093bb'
  },
  g_base_definitions[g_str_5fb1ba21e1af06001770c120_general],
  g_base_definitions[g_str_5fb1ba21e1af06001770c120],
  g_base_definitions[g_str_5fb1ba21e1af06001770c122],
  g_base_definitions[g_str_5fb1ba21e1af06001770c124],
  g_base_definitions[g_str_5fb1ba21e1af06001770c126],
  g_base_definitions[g_str_5fb1ba21e1af06001770c127],
  g_base_definitions[g_str_5fb1ba21e1af06001770c129],
  g_base_definitions[g_str_5fb1ba21e1af06001770c12b],
  g_base_definitions[g_str_5fb1ba21e1af06001770c12d],
  g_base_definitions[g_str_5fb1ba21e1af06001770c12e],
  g_base_definitions[g_str_5fb1ba21e1af06001770c130],
  g_base_definitions[g_str_5fb1b9dae1af0600177093bb_camp],
  g_base_definitions[g_str_5fb1b9dae1af0600177093bb_camp_fortified],
  g_base_definitions[g_str_5fb1ba07e1af06001770a629_general],
  g_base_definitions[g_str_5fb1ba07e1af06001770a629],
  g_base_definitions[g_str_5fb1ba07e1af06001770a62b],
  g_base_definitions[g_str_5fb1ba07e1af06001770a62d],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093bb"] = army["5fb1b9dae1af0600177093bb"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Later Mycenaean and Trojan War  1250 to 1190 BC"] = army["5fb1b9dae1af0600177093bb"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Later Mycenaean and Trojan War  1250 to 1190 BC"] = army["5fb1b9dae1af0600177093bb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Mycenaean and Trojan War  1250 to 1190 BC"] = army["5fb1b9dae1af0600177093bb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af0600177093bb"] = {}
army_dates["5fb1b9dae1af0600177093bb"]["1250 BC to 1190 BC"] ="5fb1b9dae1af0600177093bb"
