-- 5fb1b9f0e1af06001770a0e9 Khmer  605 to 1431 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3de1af06001770f3c7_general='5fb1ba3de1af06001770f3c7_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f3c7_general]={
  id=g_str_5fb1ba3de1af06001770f3c7_general,
  name='Elephants General',
  min=2,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
}
g_str_5fb1ba3de1af06001770f3c7='5fb1ba3de1af06001770f3c7'
g_base_definitions[g_str_5fb1ba3de1af06001770f3c7]={
  id=g_str_5fb1ba3de1af06001770f3c7,
  name='Elephants',
  min=2,
  max=3,
  description='War elephants',
  troop_type="Elephants",
}
g_str_5fb1ba3de1af06001770f3ca_general='5fb1ba3de1af06001770f3ca_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f3ca_general]={
  id=g_str_5fb1ba3de1af06001770f3ca_general,
  name='Chariots General',
  min=0,
  max=1,
  description='2-horse chariots with bow-armed crew',
  general=true,
  troop_type="Chariots",
}
g_str_5fb1ba3de1af06001770f3ca='5fb1ba3de1af06001770f3ca'
g_base_definitions[g_str_5fb1ba3de1af06001770f3ca]={
  id=g_str_5fb1ba3de1af06001770f3ca,
  name='Chariots',
  min=0,
  max=1,
  description='2-horse chariots with bow-armed crew',
  troop_type="Chariots",
}
g_str_5fb1ba3de1af06001770f3cc='5fb1ba3de1af06001770f3cc'
g_base_definitions[g_str_5fb1ba3de1af06001770f3cc]={
  id=g_str_5fb1ba3de1af06001770f3cc,
  name='Bad Horse',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Bad Horse",
}
g_str_5fb1ba3de1af06001770f3ce='5fb1ba3de1af06001770f3ce'
g_base_definitions[g_str_5fb1ba3de1af06001770f3ce]={
  id=g_str_5fb1ba3de1af06001770f3ce,
  name='Raiders',
  min=2,
  max=4,
  description='Jacketed spearmen with long shield',
  troop_type="Raiders",
}
g_str_5fb1ba3de1af06001770f3d1='5fb1ba3de1af06001770f3d1'
g_base_definitions[g_str_5fb1ba3de1af06001770f3d1]={
  id=g_str_5fb1ba3de1af06001770f3d1,
  name='Light Foot',
  min=1,
  max=2,
  description='Jacketed spearmen with small round shield',
  troop_type="Light Foot",
}
g_str_5fb1ba3de1af06001770f3d3='5fb1ba3de1af06001770f3d3'
g_base_definitions[g_str_5fb1ba3de1af06001770f3d3]={
  id=g_str_5fb1ba3de1af06001770f3d3,
  name='Raiders',
  min=0,
  max=1,
  description='Ph\'kak-men',
  troop_type="Raiders",
}
g_str_5fb1ba3de1af06001770f3d5='5fb1ba3de1af06001770f3d5'
g_base_definitions[g_str_5fb1ba3de1af06001770f3d5]={
  id=g_str_5fb1ba3de1af06001770f3d5,
  name='Light Foot',
  min=0,
  max=1,
  description='Maiden guard infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba3de1af06001770f3d7='5fb1ba3de1af06001770f3d7'
g_base_definitions[g_str_5fb1ba3de1af06001770f3d7]={
  id=g_str_5fb1ba3de1af06001770f3d7,
  name='Light Foot',
  min=3,
  max=6,
  description='Unarmored spearmen',
  troop_type="Light Foot",
}
g_str_5fb1ba3de1af06001770f3d7_elephant_screen='5fb1ba3de1af06001770f3d7_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f3d7_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f3d7_elephant_screen,
  name='Light Foot Elephant Screen',
  min=3,
  max=6,
  description='Unarmored spearmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Light Foot",
}
g_str_5fb1ba3de1af06001770f3da='5fb1ba3de1af06001770f3da'
g_base_definitions[g_str_5fb1ba3de1af06001770f3da]={
  id=g_str_5fb1ba3de1af06001770f3da,
  name='Rabble',
  min=0,
  max=1,
  description='Javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba3de1af06001770f3dc='5fb1ba3de1af06001770f3dc'
g_base_definitions[g_str_5fb1ba3de1af06001770f3dc]={
  id=g_str_5fb1ba3de1af06001770f3dc,
  name='Warband',
  min=0,
  max=1,
  description='Thai fighter allies',
  troop_type="Warband",
}
g_str_5fb1ba3de1af06001770f3de='5fb1ba3de1af06001770f3de'
g_base_definitions[g_str_5fb1ba3de1af06001770f3de]={
  id=g_str_5fb1ba3de1af06001770f3de,
  name='Skirmishers',
  min=2,
  max=4,
  description='Bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba3de1af06001770f3e1='5fb1ba3de1af06001770f3e1'
g_base_definitions[g_str_5fb1ba3de1af06001770f3e1]={
  id=g_str_5fb1ba3de1af06001770f3e1,
  name='Archers',
  min=0,
  max=1,
  description='Bowmen protected by pavises',
  troop_type="Archers",
}
g_str_5fb1ba3de1af06001770f3e3='5fb1ba3de1af06001770f3e3'
g_base_definitions[g_str_5fb1ba3de1af06001770f3e3]={
  id=g_str_5fb1ba3de1af06001770f3e3,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing crossbowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba3de1af06001770f3e6='5fb1ba3de1af06001770f3e6'
g_base_definitions[g_str_5fb1ba3de1af06001770f3e6]={
  id=g_str_5fb1ba3de1af06001770f3e6,
  name='Artillery',
  min=0,
  max=1,
  description='Wheeled or elephant-mounted Song-style ballista',
  troop_type="Artillery",
}
g_str_5fb1b9f0e1af06001770a0e9_camp='5fb1b9f0e1af06001770a0e9_camp'
g_base_definitions[g_str_5fb1b9f0e1af06001770a0e9_camp]={
  name='Camp',
  id=g_str_5fb1b9f0e1af06001770a0e9_camp,
  min=1,
  max=1,
}
army['5fb1b9f0e1af06001770a0e9']={
  data={
    name='Khmer  605 to 1431 AD'
  },
  g_base_definitions[g_str_5fb1b9f0e1af06001770a0e9_camp],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3c7_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3c7],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3ca_general],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3ca],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3cc],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3ce],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3d1],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3d3],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3d5],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3d7],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3d7_elephant_screen],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3da],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3dc],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3de],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3e1],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3e3],
  g_base_definitions[g_str_5fb1ba3de1af06001770f3e6],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a0e9"] = army["5fb1b9f0e1af06001770a0e9"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Khmer  605 to 1431 AD"] = army["5fb1b9f0e1af06001770a0e9"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Khmer  605 to 1431 AD"] = army["5fb1b9f0e1af06001770a0e9"]
