-- 5fb1b9e4e1af060017709a11 First Bulgar Empire  853 to 1018 AD

army['5fb1b9e4e1af060017709a11']={
  data={
    name='First Bulgar Empire  853 to 1018 AD',
    id='5fb1b9e4e1af060017709a11',
    dateRange={
      startDate=853,
      endDate=1018,
    }
  },
  g_base_definitions[g_str_5fb1ba2fe1af06001770d8b5_general],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d8b5],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d8b7],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d8b9],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d8bb],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a11_camp],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a11_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a11"] = army["5fb1b9e4e1af060017709a11"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["First Bulgar Empire  853 to 1018 AD"] = army["5fb1b9e4e1af060017709a11"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["First Bulgar Empire  853 to 1018 AD"] = army["5fb1b9e4e1af060017709a11"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["First Bulgar Empire  853 to 1018 AD"] = army["5fb1b9e4e1af060017709a11"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a11"] = {}
army_dates["5fb1b9e4e1af060017709a11"]["853 AD to 1018 AD"] = {
  startDate=853,
  endDate=1018
}
