-- 5fb1b9dfe1af060017709784 Later Graeco-Bactrian  150 to 130 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba2ae1af06001770d01b']= {
  min=1,
  max=2,
  description='Greek or bodyguard horsemen',
  core='all',
}
g_str_5fb1ba2ae1af06001770d01c='5fb1ba2ae1af06001770d01c'
g_base_definitions[g_str_5fb1ba2ae1af06001770d01c]={
  id=g_str_5fb1ba2ae1af06001770d01c,
  name='Knights',
  min=1,
  max=2,
  description='Greek or bodyguard horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba2ae1af06001770d01b",
}
g_troop_option['5fb1ba2ae1af06001770d01d']= {
  min=1,
  max=2,
  description='Iranian lancers on armored horses',
  core='all',
}
g_str_5fb1ba2ae1af06001770d01e='5fb1ba2ae1af06001770d01e'
g_base_definitions[g_str_5fb1ba2ae1af06001770d01e]={
  id=g_str_5fb1ba2ae1af06001770d01e,
  name='Cataphracts',
  min=1,
  max=2,
  description='Iranian lancers on armored horses',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2ae1af06001770d01d",
}
g_troop_option['5fb1ba2ae1af06001770d01f']= {
  min=2,
  max=5,
  description='Bactrian, Arachosian, or similar light horsemen',
}
g_str_5fb1ba2ae1af06001770d020_general='5fb1ba2ae1af06001770d020_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770d020_general]={
  id=g_str_5fb1ba2ae1af06001770d020_general,
  name='Javelin Cavalry General',
  min=2,
  max=1,
  description='Bactrian, Arachosian, or similar light horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2ae1af06001770d01f",
}
g_str_5fb1ba2ae1af06001770d020='5fb1ba2ae1af06001770d020'
g_base_definitions[g_str_5fb1ba2ae1af06001770d020]={
  id=g_str_5fb1ba2ae1af06001770d020,
  name='Javelin Cavalry',
  min=2,
  max=5,
  description='Bactrian, Arachosian, or similar light horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2ae1af06001770d01f",
}
g_troop_option['5fb1ba2ae1af06001770d021']= {
  min=0,
  max=1,
  description='Saka horse archers',
}
g_str_5fb1ba2ae1af06001770d022='5fb1ba2ae1af06001770d022'
g_base_definitions[g_str_5fb1ba2ae1af06001770d022]={
  id=g_str_5fb1ba2ae1af06001770d022,
  name='Horse Bow',
  min=0,
  max=1,
  description='Saka horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2ae1af06001770d021",
}
g_str_5fb1b9dfe1af060017709784_camp='5fb1b9dfe1af060017709784_camp'
g_base_definitions[g_str_5fb1b9dfe1af060017709784_camp]={
  id=g_str_5fb1b9dfe1af060017709784_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af060017709784_camp_pack_train='5fb1b9dfe1af060017709784_camp_pack_train'
g_base_definitions[g_str_5fb1b9dfe1af060017709784_camp_pack_train]={
  id=g_str_5fb1b9dfe1af060017709784_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba0de1af06001770abe0='5fb1ba0de1af06001770abe0'
g_base_definitions[g_str_5fb1ba0de1af06001770abe0]={
  id=g_str_5fb1ba0de1af06001770abe0,
  name='Pikes',
  min=2,
  max=4,
  description='Phalanx',
  troop_type="Pikes",
  troop_option_id="5fb1ba0de1af06001770abdf",
}
g_str_5fb1ba0de1af06001770abe2='5fb1ba0de1af06001770abe2'
g_base_definitions[g_str_5fb1ba0de1af06001770abe2]={
  id=g_str_5fb1ba0de1af06001770abe2,
  name='Raiders',
  min=0,
  max=2,
  description='Pisidian settler thureophoroi',
  troop_type="Raiders",
  troop_option_id="5fb1ba0de1af06001770abe1",
}
g_str_5fb1ba0de1af06001770abe4='5fb1ba0de1af06001770abe4'
g_base_definitions[g_str_5fb1ba0de1af06001770abe4]={
  id=g_str_5fb1ba0de1af06001770abe4,
  name='Skirmishers',
  min=0,
  max=1,
  description='Cretans',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0de1af06001770abe3",
}
g_str_5fb1ba0de1af06001770abe6='5fb1ba0de1af06001770abe6'
g_base_definitions[g_str_5fb1ba0de1af06001770abe6]={
  id=g_str_5fb1ba0de1af06001770abe6,
  name='Light Spear',
  min=1,
  max=3,
  description='Mountain Indian spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba0de1af06001770abe5",
}
g_str_5fb1ba0de1af06001770abe8='5fb1ba0de1af06001770abe8'
g_base_definitions[g_str_5fb1ba0de1af06001770abe8]={
  id=g_str_5fb1ba0de1af06001770abe8,
  name='Skirmishers',
  min=1,
  max=3,
  description='Mountain Indian bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0de1af06001770abe7",
}
g_str_5fb1ba0de1af06001770abe9='5fb1ba0de1af06001770abe9'
g_base_definitions[g_str_5fb1ba0de1af06001770abe9]={
  id=g_str_5fb1ba0de1af06001770abe9,
  name='Archers',
  min=1,
  max=3,
  description='Mountain Indian bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba0de1af06001770abe7",
}
g_str_5fb1ba0de1af06001770abea='5fb1ba0de1af06001770abea'
g_base_definitions[g_str_5fb1ba0de1af06001770abea]={
  id=g_str_5fb1ba0de1af06001770abea,
  name='Bow Levy',
  min=1,
  max=3,
  description='Mountain Indian bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba0de1af06001770abe7",
}
g_str_5fb1ba0de1af06001770abec='5fb1ba0de1af06001770abec'
g_base_definitions[g_str_5fb1ba0de1af06001770abec]={
  id=g_str_5fb1ba0de1af06001770abec,
  name='Elephants',
  min=0,
  max=1,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba0de1af06001770abeb",
}
army['5fb1b9dfe1af060017709784']={
  data={
    name='Later Graeco-Bactrian  150 to 130 BC',
    id='5fb1b9dfe1af060017709784',
    army_id='5fb1b9dfe1af060017709784'
  },
  g_base_definitions[g_str_5fb1ba2ae1af06001770d01c],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d01e],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d020_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d020],
  g_base_definitions[g_str_5fb1ba2ae1af06001770d022],
  g_base_definitions[g_str_5fb1b9dfe1af060017709784_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709784_camp_pack_train],
  g_base_definitions[g_str_5fb1ba0de1af06001770abe0],
  g_base_definitions[g_str_5fb1ba0de1af06001770abe2],
  g_base_definitions[g_str_5fb1ba0de1af06001770abe4],
  g_base_definitions[g_str_5fb1ba0de1af06001770abe6],
  g_base_definitions[g_str_5fb1ba0de1af06001770abe8],
  g_base_definitions[g_str_5fb1ba0de1af06001770abe9],
  g_base_definitions[g_str_5fb1ba0de1af06001770abea],
  g_base_definitions[g_str_5fb1ba0de1af06001770abec],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709784"] = army["5fb1b9dfe1af060017709784"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Graeco-Bactrian  150 to 130 BC"] = army["5fb1b9dfe1af060017709784"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Later Graeco-Bactrian  150 to 130 BC"] = army["5fb1b9dfe1af060017709784"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Graeco-Bactrian  150 to 130 BC"] = army["5fb1b9dfe1af060017709784"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709784"] = {}
army_dates["5fb1b9dfe1af060017709784"]["150 BC to 130 BC"] ="5fb1b9dfe1af060017709784"
