-- 5fb1b9e7e1af060017709be0 Andalusian  765 to 1172 AD

army['5fb1b9e7e1af060017709be0']={
  data={
    name='Andalusian  765 to 1172 AD',
    id='5fb1b9e7e1af060017709be0',
    army_id='5fb1b9e7e1af060017709be0'
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770dec3_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec3],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec5_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec5],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec6_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec6],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec8],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec9],
  g_base_definitions[g_str_5fb1ba32e1af06001770decb],
  g_base_definitions[g_str_5fb1ba32e1af06001770decb_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba32e1af06001770decb_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba32e1af06001770decc],
  g_base_definitions[g_str_5fb1ba32e1af06001770decc_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba32e1af06001770decc_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba32e1af06001770decf],
  g_base_definitions[g_str_5fb1ba32e1af06001770ded1],
  g_base_definitions[g_str_5fb1ba32e1af06001770ded4],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be0_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be0_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709be0"] = army["5fb1b9e7e1af060017709be0"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Andalusian  765 to 1172 AD"] = army["5fb1b9e7e1af060017709be0"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Andalusian  765 to 1172 AD"] = army["5fb1b9e7e1af060017709be0"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Andalusian  765 to 1172 AD"] = army["5fb1b9e7e1af060017709be0"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709be0"] = {}
army_dates["5fb1b9e7e1af060017709be0"]["765 AD to 1172 AD"] ="5fb1b9e7e1af060017709be0"
