troop_options['5fb1ba25e1af06001770c6ea'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-420,
    endDate=-341,
  }
}
troop_options['5fb1ba25e1af06001770c6ec'] = {
  min=4,
  max=12,
  dateRange={
    startDate=-420,
    endDate=-341,
  }
}
troop_options['5fb1ba25e1af06001770c6ee'] = {
  min=0,
  max=12,
  dateRange={
    startDate=-420,
    endDate=-341,
  }
}
troop_options['5fb1ba25e1af06001770c6f0'] = {
  min=3,
  max=8,
  dateRange={
    startDate=-420,
    endDate=-341,
  }
}
-- allies
