-- 5fb1b9f5e1af06001770a38c Nomadic Raider MFP Meso-American  899 to 400 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba43e1af06001770fd06='5fb1ba43e1af06001770fd06'
g_base_definitions[g_str_5fb1ba43e1af06001770fd06]={
  id=g_str_5fb1ba43e1af06001770fd06,
  name='Light Foot',
  min=0,
  max=2,
  description='Well equipped or trained infantry',
}
g_str_5fb1ba43e1af06001770fd08='5fb1ba43e1af06001770fd08'
g_base_definitions[g_str_5fb1ba43e1af06001770fd08]={
  id=g_str_5fb1ba43e1af06001770fd08,
  name='Skirmishers',
  min=11,
  max=16,
  description='Hit-and-run unshielded fighters armed with substantial melee weapons',
}
g_str_5fb1ba43e1af06001770fd0a='5fb1ba43e1af06001770fd0a'
g_base_definitions[g_str_5fb1ba43e1af06001770fd0a]={
  id=g_str_5fb1ba43e1af06001770fd0a,
  name='Rabble',
  min=0,
  max=4,
  description='Poorly-armed skirmishing foot',
}
g_str_5fb1ba43e1af06001770fd0c='5fb1ba43e1af06001770fd0c'
g_base_definitions[g_str_5fb1ba43e1af06001770fd0c]={
  name='Light Foot General',
  min=1,
  max=1,
}
g_str_5fb1ba43e1af06001770fd0e='5fb1ba43e1af06001770fd0e'
g_base_definitions[g_str_5fb1ba43e1af06001770fd0e]={
  name='Rabble General',
  min=1,
  max=1,
}
g_str_5fb1b9f5e1af06001770a38c_camp='5fb1b9f5e1af06001770a38c_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a38c_camp]={
  name='Camp',
  min=1,
  max=1,
}
army['5fb1b9f5e1af06001770a38c']={
  data={
    name='Nomadic Raider MFP Meso-American  899 to 400 BC'
  },
  g_base_definitions[g_str_5fb1b9f5e1af06001770a38c_camp],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd0c],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd0e],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd06],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd08],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd0a],
}
