-- 5fb1b9e1e1af060017709825 Late Judaean  63 BC to 6 AD

army['5fb1b9e1e1af060017709825']={
  data={
    name='Late Judaean  63 BC to 6 AD',
    id='5fb1b9e1e1af060017709825',
    dateRange={
      startDate=-63,
      endDate=6,
    }
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d221],
  g_base_definitions[g_str_5fb1ba2be1af06001770d223_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d223],
  g_base_definitions[g_str_5fb1ba2be1af06001770d226],
  g_base_definitions[g_str_5fb1ba2be1af06001770d229_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d229],
  g_base_definitions[g_str_5fb1ba2be1af06001770d22b],
  g_base_definitions[g_str_5fb1ba2be1af06001770d22d_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d22d],
  g_base_definitions[g_str_5fb1ba2be1af06001770d22e_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d22e],
  g_base_definitions[g_str_5fb1ba2be1af06001770d230],
  g_base_definitions[g_str_5fb1ba2be1af06001770d232],
  g_base_definitions[g_str_5fb1ba2be1af06001770d234],
  g_base_definitions[g_str_5fb1ba2be1af06001770d236],
  g_base_definitions[g_str_5fb1ba2be1af06001770d238],
  g_base_definitions[g_str_5fb1ba2be1af06001770d23a_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d23a],
  g_base_definitions[g_str_5fb1ba2be1af06001770d23c],
  g_base_definitions[g_str_5fb1ba2be1af06001770d23e],
  g_base_definitions[g_str_5fb1b9e1e1af060017709825_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709825_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709825"] = army["5fb1b9e1e1af060017709825"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Late Judaean  63 BC to 6 AD"] = army["5fb1b9e1e1af060017709825"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Late Judaean  63 BC to 6 AD"] = army["5fb1b9e1e1af060017709825"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709825"] = {}
army_dates["5fb1b9e1e1af060017709825"]["63 BC to 6 AD"] = {
  startDate=-63,
  endDate=6
}
army_dates["5fb1b9e1e1af060017709825"]["63 BC to 49 BC"] = {
  startDate=-63,
  endDate=-49
}
army_dates["5fb1b9e1e1af060017709825"]["48 BC to 47 BC"] = {
  startDate=-48,
  endDate=-47
}
army_dates["5fb1b9e1e1af060017709825"]["46 BC to 6 AD"] = {
  startDate=-46,
  endDate=6
}
