troop_options['5fb1ba44e1af06001770feef'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
troop_options['5fb1ba44e1af06001770fef2'] = {
  min=8,
  max=14,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
troop_options['5fb1ba44e1af06001770fef4'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
troop_options['5fb1ba44e1af06001770fef6'] = {
  min=4,
  max=8,
  dateRange={
    startDate=1200,
    endDate=1520,
  }
}
-- allies
