-- 5fb1b9f6e1af06001770a43f North-Western American  1100 to 1770 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1b9f6e1af06001770a43f_camp='5fb1b9f6e1af06001770a43f_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a43f_camp]={
  name='Camp',
  min=1,
  max=1,
}
army['5fb1b9f6e1af06001770a43f']={
  data={
    name='North-Western American  1100 to 1770 AD'
  },
  g_base_definitions[g_str_5fb1b9f6e1af06001770a43f_camp],
}
