troop_options['5fb1ba44e1af06001770fe0d'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1325,
    endDate=1521,
  }
}
troop_options['5fb1ba44e1af06001770fe0f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1325,
    endDate=1521,
  }
}
troop_options['5fb1ba44e1af06001770fe11'] = {
  min=4,
  max=11,
  dateRange={
    startDate=1325,
    endDate=1521,
  }
}
troop_options['5fb1ba44e1af06001770fe13'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1325,
    endDate=1521,
  }
}
troop_options['5fb1ba44e1af06001770fe15'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1325,
    endDate=1521,
  }
}
-- allies
