troop_options['5fb1ba43e1af06001770fc82'] = {
  min=3,
  max=9,
  dateRange={
    startDate=1020,
    endDate=1300,
  }
}
troop_options['5fb1ba43e1af06001770fc84'] = {
  min=0,
  max=9,
  dateRange={
    startDate=1020,
    endDate=1300,
  }
}
troop_options['5fb1ba43e1af06001770fc86'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1020,
    endDate=1300,
  }
}
troop_options['5fb1ba43e1af06001770fc88'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1020,
    endDate=1300,
  }
}
troop_options['5fb1ba43e1af06001770fc8a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1020,
    endDate=1300,
  }
}
-- allies
