g_str_5fb1ba3fe1af06001770f5e6_general='5fb1ba3fe1af06001770f5e6_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5e6_general]={
  id=g_str_5fb1ba3fe1af06001770f5e6_general,
  name='Chariots General',
  min=1,
  max=1,
  description='4-horse chariots',
  general=true,
  troop_type="Chariots",
  troop_option_id="5fb1ba3fe1af06001770f5e5",
}
g_str_5fb1ba3fe1af06001770f5e6='5fb1ba3fe1af06001770f5e6'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5e6]={
  id=g_str_5fb1ba3fe1af06001770f5e6,
  name='Chariots',
  min=1,
  max=2,
  description='4-horse chariots',
  troop_type="Chariots",
  troop_option_id="5fb1ba3fe1af06001770f5e5",
}
g_str_5fb1ba3fe1af06001770f5e9='5fb1ba3fe1af06001770f5e9'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5e9]={
  id=g_str_5fb1ba3fe1af06001770f5e9,
  name='Raiders',
  min=1,
  max=1,
  description='Armored men armed with iron clubs',
  troop_type="Raiders",
  troop_option_id="5fb1ba3fe1af06001770f5e7",
}
g_str_5fb1ba3fe1af06001770f5eb='5fb1ba3fe1af06001770f5eb'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5eb]={
  id=g_str_5fb1ba3fe1af06001770f5eb,
  name='Archers',
  min=1,
  max=4,
  description='Elite crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba3fe1af06001770f5ea",
}
g_str_5fb1ba3fe1af06001770f5ed='5fb1ba3fe1af06001770f5ed'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5ed]={
  id=g_str_5fb1ba3fe1af06001770f5ed,
  name='Elite Foot',
  min=1,
  max=4,
  description='Elite dagger-axe or halberdmen',
  hold_the_line=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba3fe1af06001770f5ec",
}
g_str_5fb1ba3fe1af06001770f5f0='5fb1ba3fe1af06001770f5f0'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5f0]={
  id=g_str_5fb1ba3fe1af06001770f5f0,
  name='Bow Levy',
  min=2,
  max=4,
  description='Conscript crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3fe1af06001770f5ef",
}
g_str_5fb1ba3fe1af06001770f5f2='5fb1ba3fe1af06001770f5f2'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5f2]={
  id=g_str_5fb1ba3fe1af06001770f5f2,
  name='Heavy Foot',
  min=2,
  max=4,
  description='Conscript dagger-axe or halberdmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3fe1af06001770f5f1",
}
g_str_5fb1ba3fe1af06001770f5f4='5fb1ba3fe1af06001770f5f4'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5f4]={
  id=g_str_5fb1ba3fe1af06001770f5f4,
  name='Pavisiers',
  min=0,
  max=6,
  description='Mixed formations of crossbowmen behind lines of dagger-axe men',
  hold_the_line=true,
  troop_type="Pavisiers",
  troop_option_id="5fb1ba3fe1af06001770f5f3",
}
g_str_5fb1ba3fe1af06001770f5f7='5fb1ba3fe1af06001770f5f7'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5f7]={
  id=g_str_5fb1ba3fe1af06001770f5f7,
  name='Light Foot',
  min=0,
  max=4,
  description='Dagger-axe men rearmed with spear and shield',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3fe1af06001770f5f6",
}
g_str_5fb1ba3fe1af06001770f5f9='5fb1ba3fe1af06001770f5f9'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5f9]={
  id=g_str_5fb1ba3fe1af06001770f5f9,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen or crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3fe1af06001770f5f8",
}
g_str_5fb1ba3fe1af06001770f5fb='5fb1ba3fe1af06001770f5fb'
g_base_definitions[g_str_5fb1ba3fe1af06001770f5fb]={
  id=g_str_5fb1ba3fe1af06001770f5fb,
  name='Warband',
  min=0,
  max=2,
  description='Southern fierce tribesmen',
  troop_type="Warband",
  troop_option_id="5fb1ba3fe1af06001770f5fa",
}
g_str_5fb1b9f1e1af06001770a195_camp='5fb1b9f1e1af06001770a195_camp'
g_base_definitions[g_str_5fb1b9f1e1af06001770a195_camp]={
  id=g_str_5fb1b9f1e1af06001770a195_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f1e1af06001770a195_camp_fortified='5fb1b9f1e1af06001770a195_camp_fortified'
g_base_definitions[g_str_5fb1b9f1e1af06001770a195_camp_fortified]={
  id=g_str_5fb1b9f1e1af06001770a195_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
