-- 5fb1b9ede1af060017709f72 Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3ae1af06001770ede9='5fb1ba3ae1af06001770ede9'
g_base_definitions[g_str_5fb1ba3ae1af06001770ede9]={
  id=g_str_5fb1ba3ae1af06001770ede9,
  name='Elite Cavalary',
  min=1,
  max=1,
  description='Seljuq nobles and retainers',
}
g_str_5fb1ba3ae1af06001770edec='5fb1ba3ae1af06001770edec'
g_base_definitions[g_str_5fb1ba3ae1af06001770edec]={
  id=g_str_5fb1ba3ae1af06001770edec,
  name='Horse Bow',
  min=1,
  max=4,
  description='Seljuq tribesmen before 1063 (Askar after 1063)',
}
g_str_5fb1ba3ae1af06001770edee='5fb1ba3ae1af06001770edee'
g_base_definitions[g_str_5fb1ba3ae1af06001770edee]={
  id=g_str_5fb1ba3ae1af06001770edee,
  name='Horse Bow',
  min=4,
  max=7,
  description='Turkoman horse archers',
}
g_str_5fb1ba3ae1af06001770edf0='5fb1ba3ae1af06001770edf0'
g_base_definitions[g_str_5fb1ba3ae1af06001770edf0]={
  id=g_str_5fb1ba3ae1af06001770edf0,
  name='Light Foot',
  min=0,
  max=2,
  description='Turkish, Armenian, or Kurdish light infantry',
}
g_str_5fb1ba3ae1af06001770edf2='5fb1ba3ae1af06001770edf2'
g_base_definitions[g_str_5fb1ba3ae1af06001770edf2]={
  id=g_str_5fb1ba3ae1af06001770edf2,
  name='Bow Levy',
  min=0,
  max=4,
  description='Turkish, Armenian, or Kurdish bowmen',
}
g_str_5fb1ba3ae1af06001770edf4='5fb1ba3ae1af06001770edf4'
g_base_definitions[g_str_5fb1ba3ae1af06001770edf4]={
  id=g_str_5fb1ba3ae1af06001770edf4,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami zupin-men',
}
g_str_5fb1ba3ae1af06001770edf8='5fb1ba3ae1af06001770edf8'
g_base_definitions[g_str_5fb1ba3ae1af06001770edf8]={
  id=g_str_5fb1ba3ae1af06001770edf8,
  name='Cataphracts',
  min=0,
  max=1,
  description='Agulani',
}
g_str_5fb1ba3ae1af06001770edfb='5fb1ba3ae1af06001770edfb'
g_base_definitions[g_str_5fb1ba3ae1af06001770edfb]={
  id=g_str_5fb1ba3ae1af06001770edfb,
  name='Knights',
  min=0,
  max=1,
  description='Armenians, Georgians, and "Franks" men-at-arms',
}
g_str_5fb1ba3ae1af06001770edfe='5fb1ba3ae1af06001770edfe'
g_base_definitions[g_str_5fb1ba3ae1af06001770edfe]={
  id=g_str_5fb1ba3ae1af06001770edfe,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Seljuq spearmen',
}
g_str_5fb1ba3ae1af06001770ee00='5fb1ba3ae1af06001770ee00'
g_base_definitions[g_str_5fb1ba3ae1af06001770ee00]={
  name='Elite Cavalary General',
  id=g_str_5fb1ba3ae1af06001770ee00,
  min=1,
  max=1,
}
g_str_5fb1ba3ae1af06001770ee01='5fb1ba3ae1af06001770ee01'
g_base_definitions[g_str_5fb1ba3ae1af06001770ee01]={
  name='Horse Bow General',
  id=g_str_5fb1ba3ae1af06001770ee01,
  min=1,
  max=1,
}
g_str_5fb1b9ede1af060017709f72_camp='5fb1b9ede1af060017709f72_camp'
g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp]={
  name='Camp',
  id=g_str_5fb1b9ede1af060017709f72_camp,
  min=1,
  max=1,
}
army['5fb1b9ede1af060017709f72']={
  data={
    name='Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD'
  },
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ee00],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ee01],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf8],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edfb],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edfe],
}
