troop_options['5fb1ba2ae1af06001770cf97'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-312,
    endDate=-127,
  }
}
troop_options['5fb1ba2ae1af06001770cf9a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-126,
    endDate=240,
  }
}
troop_options['5fb1ba2ae1af06001770cf9e'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-312,
    endDate=240,
  }
}
troop_options['5fb1ba2ae1af06001770cfa0'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-51,
    endDate=72,
  }
}
troop_options['5fb1ba2ae1af06001770cfa3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-312,
    endDate=240,
  }
}
troop_options['5fb1ba2ae1af06001770cfa6'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-312,
    endDate=240,
  }
}
troop_options['5fb1ba2ae1af06001770cfa8'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-312,
    endDate=240,
  }
}
troop_options['5fb1ba2ae1af06001770cfaa'] = {
  min=5,
  max=16,
  dateRange={
    startDate=-312,
    endDate=240,
  }
}
troop_options['5fb1ba2ae1af06001770cfad'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-312,
    endDate=240,
  }
}
-- allies
