-- 5fb1b9dfe1af060017709758 Arabo-Aramaean Other  312 BC to 240 AD

army['5fb1b9dfe1af060017709758']={
  data={
    name='Arabo-Aramaean Other  312 BC to 240 AD',
    id='5fb1b9dfe1af060017709758',
    dateRange={
      startDate=-312,
      endDate=240,
    }
  },
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf99_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf99],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9c_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9c],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9d],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9f_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9f],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa2],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa4],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa4_light_camelry],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa7],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa9],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfab],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfac],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfae],
  g_base_definitions[g_str_5fb1b9dfe1af060017709758_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709758_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709758"] = army["5fb1b9dfe1af060017709758"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Arabo-Aramaean Other  312 BC to 240 AD"] = army["5fb1b9dfe1af060017709758"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Arabo-Aramaean Other  312 BC to 240 AD"] = army["5fb1b9dfe1af060017709758"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Arabo-Aramaean Other  312 BC to 240 AD"] = army["5fb1b9dfe1af060017709758"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709758"] = {}
army_dates["5fb1b9dfe1af060017709758"]["312 BC to 240 AD"] = {
  startDate=-312,
  endDate=240
}
army_dates["5fb1b9dfe1af060017709758"]["312 BC to 127 BC"] = {
  startDate=-312,
  endDate=240
}
army_dates["5fb1b9dfe1af060017709758"]["126 BC to 52 BC"] = {
  startDate=-312,
  endDate=240
}
army_dates["5fb1b9dfe1af060017709758"]["51 BC to 72 AD"] = {
  startDate=-312,
  endDate=240
}
army_dates["5fb1b9dfe1af060017709758"]["73 AD to 240 AD"] = {
  startDate=-312,
  endDate=240
}
