-- 5fb1b9dbe1af06001770949e Dark Age and Geometric Greek  1160 to 665 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba23e1af06001770c4d4='5fb1ba23e1af06001770c4d4'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d4]={
  id=g_str_5fb1ba23e1af06001770c4d4,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who usually fight on foot',
}
g_str_5fb1ba23e1af06001770c4d6='5fb1ba23e1af06001770c4d6'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d6]={
  id=g_str_5fb1ba23e1af06001770c4d6,
  name='Bad Horse',
  min=1,
  max=2,
  description='Greek horsemen',
}
g_str_5fb1ba23e1af06001770c4d8='5fb1ba23e1af06001770c4d8'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d8]={
  id=g_str_5fb1ba23e1af06001770c4d8,
  name='Light Foot',
  min=8,
  max=14,
  description='Light infantry armed with sword or spear and dipylon shield',
}
g_str_5fb1ba23e1af06001770c4dc='5fb1ba23e1af06001770c4dc'
g_base_definitions[g_str_5fb1ba23e1af06001770c4dc]={
  id=g_str_5fb1ba23e1af06001770c4dc,
  name='Heavy Foot',
  min=0,
  max=14,
  description='Heavy infantry armed with a mix of dipylon and hoplon shields',
}
g_str_5fb1ba23e1af06001770c4df='5fb1ba23e1af06001770c4df'
g_base_definitions[g_str_5fb1ba23e1af06001770c4df]={
  id=g_str_5fb1ba23e1af06001770c4df,
  name='Skirmishers',
  min=0,
  max=4,
  description='Skirmishing bowmen',
}
g_str_5fb1ba23e1af06001770c4e2='5fb1ba23e1af06001770c4e2'
g_base_definitions[g_str_5fb1ba23e1af06001770c4e2]={
  id=g_str_5fb1ba23e1af06001770c4e2,
  name='Rabble',
  min=1,
  max=4,
  description='Javelinmen',
}
g_str_5fb1ba23e1af06001770c4e4='5fb1ba23e1af06001770c4e4'
g_base_definitions[g_str_5fb1ba23e1af06001770c4e4]={
  name='Battle Taxi General',
  id=g_str_5fb1ba23e1af06001770c4e4,
  min=1,
  max=1,
}
g_str_5fb1ba23e1af06001770c4e5='5fb1ba23e1af06001770c4e5'
g_base_definitions[g_str_5fb1ba23e1af06001770c4e5]={
  name='Bad Horse General',
  id=g_str_5fb1ba23e1af06001770c4e5,
  min=1,
  max=1,
}
g_str_5fb1b9dbe1af06001770949e_camp='5fb1b9dbe1af06001770949e_camp'
g_base_definitions[g_str_5fb1b9dbe1af06001770949e_camp]={
  name='Camp',
  id=g_str_5fb1b9dbe1af06001770949e_camp,
  min=1,
  max=1,
}
army['5fb1b9dbe1af06001770949e']={
  data={
    name='Dark Age and Geometric Greek  1160 to 665 BC'
  },
  g_base_definitions[g_str_5fb1b9dbe1af06001770949e_camp],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4e4],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4e5],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d4],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d6],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d8],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4dc],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4df],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4e2],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af06001770949e"] = army["5fb1b9dbe1af06001770949e"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Dark Age and Geometric Greek  1160 to 665 BC"] = army["5fb1b9dbe1af06001770949e"]
