troop_options['5fb1ba2fe1af06001770d91f'] = {
  min=4,
  max=6,
  dateRange={
    startDate=775,
    endDate=1076,
  }
}
troop_options['5fb1ba2fe1af06001770d921'] = {
  min=2,
  max=6,
  dateRange={
    startDate=775,
    endDate=1076,
  }
}
troop_options['5fb1ba2fe1af06001770d923'] = {
  min=0,
  max=4,
  dateRange={
    startDate=775,
    endDate=1076,
  }
}
troop_options['5fb1ba2fe1af06001770d925'] = {
  min=2,
  max=4,
  dateRange={
    startDate=775,
    endDate=1076,
  }
}
-- allies
