troop_options['5fb1ba37e1af06001770e717'] = {
  min=1,
  max=3,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e719'] = {
  min=3,
  max=5,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e71b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e71d'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e720'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e723'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e726'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e728'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e72a'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e72c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
troop_options['5fb1ba37e1af06001770e730'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1054,
    endDate=1246,
  }
}
-- allies
