-- 5fb1b9dce1af06001770954f Syracusan  410 to 210 BC

army['5fb1b9dce1af06001770954f']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
      3,
    },
    homeTopographies={
      'Arable',
    },
    name='Syracusan  410 to 210 BC',
    id='5fb1b9dce1af06001770954f',
    dateRange={
      startDate=-410,
      endDate=-210,
    },
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c750_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c750],
  g_base_definitions[g_str_5fb1ba26e1af06001770c752_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c752],
  g_base_definitions[g_str_5fb1ba26e1af06001770c754],
  g_base_definitions[g_str_5fb1ba26e1af06001770c757],
  g_base_definitions[g_str_5fb1ba26e1af06001770c759],
  g_base_definitions[g_str_5fb1ba26e1af06001770c75b],
  g_base_definitions[g_str_5fb1ba26e1af06001770c75d],
  g_base_definitions[g_str_5fb1ba26e1af06001770c75f],
  g_base_definitions[g_str_5fb1b9dce1af06001770954f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af06001770954f"] = army["5fb1b9dce1af06001770954f"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Syracusan  410 to 210 BC"] = army["5fb1b9dce1af06001770954f"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Syracusan  410 to 210 BC"] = army["5fb1b9dce1af06001770954f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Syracusan  410 to 210 BC"] = army["5fb1b9dce1af06001770954f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af06001770954f"] = {}
army_dates["5fb1b9dce1af06001770954f"]["410 BC to 210 BC"] = {
  startDate=-410,
  endDate=-210
}
army_dates["5fb1b9dce1af06001770954f"]["410 BC to 314 BC"] = {
  startDate=-410,
  endDate=-314
}
army_dates["5fb1b9dce1af06001770954f"]["313 BC to 311 BC"] = {
  startDate=-313,
  endDate=-311
}
army_dates["5fb1b9dce1af06001770954f"]["310 BC to 308 BC"] = {
  startDate=-310,
  endDate=-308
}
army_dates["5fb1b9dce1af06001770954f"]["307 BC"] = {
  startDate=-307,
  endDate=-307
}
army_dates["5fb1b9dce1af06001770954f"]["306 BC to 301 BC"] = {
  startDate=-306,
  endDate=-301
}
army_dates["5fb1b9dce1af06001770954f"]["300 BC to 288 BC"] = {
  startDate=-300,
  endDate=-288
}
army_dates["5fb1b9dce1af06001770954f"]["287 BC to 279 BC"] = {
  startDate=-287,
  endDate=-279
}
army_dates["5fb1b9dce1af06001770954f"]["278 BC to 276 BC"] = {
  startDate=-278,
  endDate=-276
}
army_dates["5fb1b9dce1af06001770954f"]["275 BC"] = {
  startDate=-275,
  endDate=-275
}
army_dates["5fb1b9dce1af06001770954f"]["274 BC to 272 BC"] = {
  startDate=-274,
  endDate=-272
}
army_dates["5fb1b9dce1af06001770954f"]["271 BC to 266 BC"] = {
  startDate=-271,
  endDate=-266
}
army_dates["5fb1b9dce1af06001770954f"]["265 BC to 236 BC"] = {
  startDate=-265,
  endDate=-236
}
army_dates["5fb1b9dce1af06001770954f"]["235 BC to 216 BC"] = {
  startDate=-235,
  endDate=-216
}
army_dates["5fb1b9dce1af06001770954f"]["215 BC to 214 BC"] = {
  startDate=-215,
  endDate=-214
}
army_dates["5fb1b9dce1af06001770954f"]["213 BC to 210 BC"] = {
  startDate=-213,
  endDate=-210
}
