-- 5fb1b9dbe1af06001770947f Saitic Egyptian  664 to 525 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba23e1af06001770c475_general='5fb1ba23e1af06001770c475_general'
g_base_definitions[g_str_5fb1ba23e1af06001770c475_general]={
  id=g_str_5fb1ba23e1af06001770c475_general,
  name='Chariots General',
  min=1,
  max=1,
  description='4-horse chariots with three crewmen',
  general=true,
  troop_type="Chariots",
}
g_str_5fb1ba23e1af06001770c475='5fb1ba23e1af06001770c475'
g_base_definitions[g_str_5fb1ba23e1af06001770c475]={
  id=g_str_5fb1ba23e1af06001770c475,
  name='Chariots',
  min=1,
  max=2,
  description='4-horse chariots with three crewmen',
  troop_type="Chariots",
}
g_str_5fb1ba23e1af06001770c477_general='5fb1ba23e1af06001770c477_general'
g_base_definitions[g_str_5fb1ba23e1af06001770c477_general]={
  id=g_str_5fb1ba23e1af06001770c477_general,
  name='Bad Horse General',
  min=1,
  max=1,
  description='Egyptian horsemen',
  general=true,
  troop_type="Bad Horse",
}
g_str_5fb1ba23e1af06001770c477='5fb1ba23e1af06001770c477'
g_base_definitions[g_str_5fb1ba23e1af06001770c477]={
  id=g_str_5fb1ba23e1af06001770c477,
  name='Bad Horse',
  min=1,
  max=2,
  description='Egyptian horsemen',
  troop_type="Bad Horse",
}
g_str_5fb1ba23e1af06001770c47a='5fb1ba23e1af06001770c47a'
g_base_definitions[g_str_5fb1ba23e1af06001770c47a]={
  id=g_str_5fb1ba23e1af06001770c47a,
  name='Horse Bow',
  min=0,
  max=1,
  description='Skythian mercenary horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba23e1af06001770c47c='5fb1ba23e1af06001770c47c'
g_base_definitions[g_str_5fb1ba23e1af06001770c47c]={
  id=g_str_5fb1ba23e1af06001770c47c,
  name='Spears',
  min=0,
  max=1,
  description='Guard spearmen',
  troop_type="Spears",
}
g_str_5fb1ba23e1af06001770c47e='5fb1ba23e1af06001770c47e'
g_base_definitions[g_str_5fb1ba23e1af06001770c47e]={
  id=g_str_5fb1ba23e1af06001770c47e,
  name='Archers',
  min=0,
  max=1,
  description='Guard bowmen',
  troop_type="Archers",
}
g_str_5fb1ba23e1af06001770c480='5fb1ba23e1af06001770c480'
g_base_definitions[g_str_5fb1ba23e1af06001770c480]={
  id=g_str_5fb1ba23e1af06001770c480,
  name='Heavy Foot',
  min=3,
  max=6,
  description='Levy spearmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba23e1af06001770c482='5fb1ba23e1af06001770c482'
g_base_definitions[g_str_5fb1ba23e1af06001770c482]={
  id=g_str_5fb1ba23e1af06001770c482,
  name='Bow Levy',
  min=2,
  max=4,
  description='Levy bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba23e1af06001770c484='5fb1ba23e1af06001770c484'
g_base_definitions[g_str_5fb1ba23e1af06001770c484]={
  id=g_str_5fb1ba23e1af06001770c484,
  name='Skirmishers',
  min=0,
  max=2,
  description='Nubian skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba23e1af06001770c486='5fb1ba23e1af06001770c486'
g_base_definitions[g_str_5fb1ba23e1af06001770c486]={
  id=g_str_5fb1ba23e1af06001770c486,
  name='Rabble',
  min=0,
  max=2,
  description='Levy or Libyan javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba23e1af06001770c488='5fb1ba23e1af06001770c488'
g_base_definitions[g_str_5fb1ba23e1af06001770c488]={
  id=g_str_5fb1ba23e1af06001770c488,
  name='Spears',
  min=0,
  max=3,
  description='Greek mercenary hoplites',
  troop_type="Spears",
}
g_str_5fb1ba23e1af06001770c489='5fb1ba23e1af06001770c489'
g_base_definitions[g_str_5fb1ba23e1af06001770c489]={
  id=g_str_5fb1ba23e1af06001770c489,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Greek mercenary hoplites',
  troop_type="Heavy Foot",
}
g_str_5fb1b9dbe1af06001770947f_camp='5fb1b9dbe1af06001770947f_camp'
g_base_definitions[g_str_5fb1b9dbe1af06001770947f_camp]={
  id=g_str_5fb1b9dbe1af06001770947f_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dbe1af06001770947f_camp_pack_train='5fb1b9dbe1af06001770947f_camp_pack_train'
g_base_definitions[g_str_5fb1b9dbe1af06001770947f_camp_pack_train]={
  id=g_str_5fb1b9dbe1af06001770947f_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dbe1af06001770947f']={
  data={
    name='Saitic Egyptian  664 to 525 BC'
  },
  g_base_definitions[g_str_5fb1ba23e1af06001770c475_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c475],
  g_base_definitions[g_str_5fb1ba23e1af06001770c477_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c477],
  g_base_definitions[g_str_5fb1ba23e1af06001770c47a],
  g_base_definitions[g_str_5fb1ba23e1af06001770c47c],
  g_base_definitions[g_str_5fb1ba23e1af06001770c47e],
  g_base_definitions[g_str_5fb1ba23e1af06001770c480],
  g_base_definitions[g_str_5fb1ba23e1af06001770c482],
  g_base_definitions[g_str_5fb1ba23e1af06001770c484],
  g_base_definitions[g_str_5fb1ba23e1af06001770c486],
  g_base_definitions[g_str_5fb1ba23e1af06001770c488],
  g_base_definitions[g_str_5fb1ba23e1af06001770c489],
  g_base_definitions[g_str_5fb1b9dbe1af06001770947f_camp],
  g_base_definitions[g_str_5fb1b9dbe1af06001770947f_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af06001770947f"] = army["5fb1b9dbe1af06001770947f"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Saitic Egyptian  664 to 525 BC"] = army["5fb1b9dbe1af06001770947f"]
