-- 5fb1b9eee1af060017709ff3 Ottoman Empire  1362 to 1520 AD

army['5fb1b9eee1af060017709ff3']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      3,
      4,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Ottoman Empire  1362 to 1520 AD',
    id='5fb1b9eee1af060017709ff3',
    dateRange={
      startDate=1362,
      endDate=1520,
    }
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770efc6_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770efc6_general_shower_shooting],
  g_base_definitions[g_str_5fb1ba3be1af06001770efc6],
  g_base_definitions[g_str_5fb1ba3be1af06001770efc6_shower_shooting],
  g_base_definitions[g_str_5fb1ba3be1af06001770efc9_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770efc9],
  g_base_definitions[g_str_5fb1ba3be1af06001770efcc],
  g_base_definitions[g_str_5fb1ba3be1af06001770efce_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770efce],
  g_base_definitions[g_str_5fb1ba3be1af06001770efd0],
  g_base_definitions[g_str_5fb1ba3be1af06001770efd2],
  g_base_definitions[g_str_5fb1ba3be1af06001770efd4],
  g_base_definitions[g_str_5fb1ba3be1af06001770efd6],
  g_base_definitions[g_str_5fb1ba3be1af06001770efd8],
  g_base_definitions[g_str_5fb1ba3be1af06001770efd9],
  g_base_definitions[g_str_5fb1ba3be1af06001770efdb],
  g_base_definitions[g_str_5fb1ba3be1af06001770efdd],
  g_base_definitions[g_str_5fb1ba3be1af06001770efdf],
  g_base_definitions[g_str_5fb1ba3be1af06001770efe1],
  g_base_definitions[g_str_5fb1ba3be1af06001770efe3],
  g_base_definitions[g_str_5fb1b9eee1af060017709ff3_camp],
  g_base_definitions[g_str_5fb1b9eee1af060017709ff3_camp_fortified],
  g_base_definitions[g_str_5fb1b9eee1af060017709ff3_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af060017709ff3"] = army["5fb1b9eee1af060017709ff3"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Ottoman Empire  1362 to 1520 AD"] = army["5fb1b9eee1af060017709ff3"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Ottoman Empire  1362 to 1520 AD"] = army["5fb1b9eee1af060017709ff3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Ottoman Empire  1362 to 1520 AD"] = army["5fb1b9eee1af060017709ff3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af060017709ff3"] = {}
army_dates["5fb1b9eee1af060017709ff3"]["1362 AD to 1520 AD"] = {
  startDate=1362,
  endDate=1520
}
army_dates["5fb1b9eee1af060017709ff3"]["1362 AD to 1379 AD"] = {
  startDate=1362,
  endDate=1379
}
army_dates["5fb1b9eee1af060017709ff3"]["1380 AD"] = {
  startDate=1380,
  endDate=1380
}
army_dates["5fb1b9eee1af060017709ff3"]["1381 AD to 1389 AD"] = {
  startDate=1381,
  endDate=1389
}
army_dates["5fb1b9eee1af060017709ff3"]["1390 AD to 1400 AD"] = {
  startDate=1390,
  endDate=1400
}
army_dates["5fb1b9eee1af060017709ff3"]["1401 AD to 1449 AD"] = {
  startDate=1401,
  endDate=1449
}
army_dates["5fb1b9eee1af060017709ff3"]["1450 AD to 1455 AD"] = {
  startDate=1450,
  endDate=1455
}
army_dates["5fb1b9eee1af060017709ff3"]["1456 AD to 1476 AD"] = {
  startDate=1456,
  endDate=1476
}
army_dates["5fb1b9eee1af060017709ff3"]["1477 AD to 1479 AD"] = {
  startDate=1477,
  endDate=1479
}
army_dates["5fb1b9eee1af060017709ff3"]["1480 AD to 1509 AD"] = {
  startDate=1480,
  endDate=1509
}
army_dates["5fb1b9eee1af060017709ff3"]["1510 AD to 1515 AD"] = {
  startDate=1510,
  endDate=1515
}
army_dates["5fb1b9eee1af060017709ff3"]["1516 AD to 1517 AD"] = {
  startDate=1516,
  endDate=1517
}
army_dates["5fb1b9eee1af060017709ff3"]["1518 AD to 1520 AD"] = {
  startDate=1518,
  endDate=1520
}
