-- 5fb1b9e3e1af06001770997a Army of Attila  433 to 453 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ee1af06001770d6cf='5fb1ba2ee1af06001770d6cf'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6cf]={
  id=g_str_5fb1ba2ee1af06001770d6cf,
  name='Horse Bow General',
  min=4,
  max=1,
  description='Hun horse archers',
}
g_str_5fb1ba2ee1af06001770d6cf='5fb1ba2ee1af06001770d6cf'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6cf]={
  id=g_str_5fb1ba2ee1af06001770d6cf,
  name='Horse Bow',
  min=4,
  max=7,
  description='Hun horse archers',
}
g_str_5fb1ba2ee1af06001770d6d1='5fb1ba2ee1af06001770d6d1'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6d1]={
  id=g_str_5fb1ba2ee1af06001770d6d1,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Alan subject horse archers',
}
g_str_5fb1ba2ee1af06001770d6d1='5fb1ba2ee1af06001770d6d1'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6d1]={
  id=g_str_5fb1ba2ee1af06001770d6d1,
  name='Horse Bow',
  min=0,
  max=1,
  description='Alan subject horse archers',
}
g_str_5fb1ba2ee1af06001770d6d3='5fb1ba2ee1af06001770d6d3'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6d3]={
  id=g_str_5fb1ba2ee1af06001770d6d3,
  name='Light Foot',
  min=0,
  max=1,
  description='Herul light infantry',
}
g_str_5fb1ba2ee1af06001770d6d5='5fb1ba2ee1af06001770d6d5'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6d5]={
  id=g_str_5fb1ba2ee1af06001770d6d5,
  name='Knights',
  min=2,
  max=4,
  description='Ostrogoth and Gepid horsemen, plus Sciri or Herul subject horsemen',
}
g_str_5fb1ba2ee1af06001770d6d7='5fb1ba2ee1af06001770d6d7'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6d7]={
  id=g_str_5fb1ba2ee1af06001770d6d7,
  name='Warriors',
  min=2,
  max=6,
  description='Gepid, Burgundian, Frankish, Rugian, and Thuringian subject infantry',
}
g_str_5fb1ba2ee1af06001770d6d9='5fb1ba2ee1af06001770d6d9'
g_base_definitions[g_str_5fb1ba2ee1af06001770d6d9]={
  id=g_str_5fb1ba2ee1af06001770d6d9,
  name='Bow Levy',
  min=1,
  max=2,
  description='Gepid bowmen',
}
g_str_5fb1b9e3e1af06001770997a_camp='5fb1b9e3e1af06001770997a_camp'
g_base_definitions[g_str_5fb1b9e3e1af06001770997a_camp]={
  name='Camp',
  id=g_str_5fb1b9e3e1af06001770997a_camp,
  min=1,
  max=1,
}
army['5fb1b9e3e1af06001770997a']={
  data={
    name='Army of Attila  433 to 453 AD'
  },
  g_base_definitions[g_str_5fb1b9e3e1af06001770997a_camp],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6db],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6cf],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6cf],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6d1],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6d1],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6d3],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6d5],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6d7],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6d9],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af06001770997a"] = army["5fb1b9e3e1af06001770997a"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Army of Attila  433 to 453 AD"] = army["5fb1b9e3e1af06001770997a"]
