-- 5fb1b9e3e1af06001770995d Hepthalites in India  356 to 570 AD

army['5fb1b9e3e1af06001770995d']={
  data={
    invasionRatings={
      {
        value=3,
        note='',
      },
    },
    name='Hepthalites in India  356 to 570 AD',
    id='5fb1b9e3e1af06001770995d',
    dateRange={
      startDate=356,
      endDate=570,
    }
  },
  g_base_definitions[g_str_5fb1ba2de1af06001770d6a9_general],
  g_base_definitions[g_str_5fb1ba2de1af06001770d6a9],
  g_base_definitions[g_str_5fb1ba2de1af06001770d6ab],
  g_base_definitions[g_str_5fb1ba2de1af06001770d6ae],
  g_base_definitions[g_str_5fb1ba2de1af06001770d6ae_elephant_screen],
  g_base_definitions[g_str_5fb1ba2de1af06001770d6b1],
  g_base_definitions[g_str_5fb1b9e3e1af06001770995d_camp],
  g_base_definitions[g_str_5fb1b9e3e1af06001770995d_camp_fortified],
  g_base_definitions[g_str_5fb1b9e3e1af06001770995d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af06001770995d"] = army["5fb1b9e3e1af06001770995d"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Hepthalites in India  356 to 570 AD"] = army["5fb1b9e3e1af06001770995d"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Hepthalites in India  356 to 570 AD"] = army["5fb1b9e3e1af06001770995d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hepthalites in India  356 to 570 AD"] = army["5fb1b9e3e1af06001770995d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af06001770995d"] = {}
army_dates["5fb1b9e3e1af06001770995d"]["356 AD to 570 AD"] = {
  startDate=356,
  endDate=570
}
