troop_options['615351b303385c0016b885dc'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-549,
    endDate=-480,
  }
}
troop_options['615351b303385c0016b885de'] = {
  min=6,
  max=13,
  dateRange={
    startDate=-549,
    endDate=-480,
  }
}
troop_options['615351b303385c0016b885e2'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-549,
    endDate=-480,
  }
}
troop_options['615351b303385c0016b885e6'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-549,
    endDate=-480,
  }
}
-- allies
