troop_options['615351a803385c0016b8696d'] = {
  min=1,
  max=3,
  dateRange={
    startDate=799,
    endDate=1089,
  }
}
troop_options['615351a803385c0016b86970'] = {
  min=1,
  max=4,
  dateRange={
    startDate=799,
    endDate=1089,
  }
}
troop_options['615351a803385c0016b86972'] = {
  min=4,
  max=7,
  dateRange={
    startDate=799,
    endDate=1089,
  }
}
troop_options['615351a803385c0016b86974'] = {
  min=0,
  max=1,
  dateRange={
    startDate=799,
    endDate=1089,
  }
}
troop_options['615351a803385c0016b86976'] = {
  min=0,
  max=8,
  dateRange={
    startDate=799,
    endDate=1089,
  }
}
-- allies
