troop_options['5fb1ba2fe1af06001770d93b'] = {
  min=3,
  max=7,
  dateRange={
    startDate=639,
    endDate=888,
  }
}
troop_options['5fb1ba2fe1af06001770d93e'] = {
  min=0,
  max=3,
  dateRange={
    startDate=639,
    endDate=888,
  }
}
troop_options['5fb1ba2fe1af06001770d943'] = {
  min=0,
  max=1,
  dateRange={
    startDate=639,
    endDate=888,
  }
}
troop_options['5fb1ba2fe1af06001770d945'] = {
  min=1,
  max=5,
  dateRange={
    startDate=639,
    endDate=888,
  }
}
troop_options['5fb1ba2fe1af06001770d947'] = {
  min=0,
  max=3,
  dateRange={
    startDate=639,
    endDate=888,
  }
}
troop_options['5fb1ba2fe1af06001770d949'] = {
  min=0,
  max=1,
  dateRange={
    startDate=639,
    endDate=888,
  }
}
troop_options['5fb1ba2fe1af06001770d94b'] = {
  min=0,
  max=2,
  dateRange={
    startDate=639,
    endDate=888,
  }
}
troop_options['5fb1ba2fe1af06001770d94d'] = {
  min=0,
  max=2,
  dateRange={
    startDate=836,
    endDate=838,
  }
}
-- allies
