troop_options['5fb1ba27e1af06001770c98b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['5fb1ba27e1af06001770c98f'] = {
  min=8,
  max=15,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['5fb1ba27e1af06001770c992'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['5fb1ba27e1af06001770c994'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['5fb1ba27e1af06001770c997'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['5fb1ba27e1af06001770c999'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['5fb1ba27e1af06001770c99b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-448,
    endDate=-225,
  }
}
troop_options['5fb1ba27e1af06001770c99d'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-448,
    endDate=-397,
  }
}
troop_options['5fb1ba27e1af06001770c9a0'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-415,
    endDate=-413,
  }
}
troop_options['5fb1ba27e1af06001770c9a3'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-374,
    endDate=-353,
  }
}
-- allies
