troop_options['5fb1ba27e1af06001770ca67'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-546,
    endDate=-300,
  }
}
troop_options['5fb1ba27e1af06001770ca69'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-546,
    endDate=-500,
  }
}
troop_options['5fb1ba27e1af06001770ca6c'] = {
  min=7,
  max=14,
  dateRange={
    startDate=-546,
    endDate=-300,
  }
}
troop_options['5fb1ba27e1af06001770ca6e'] = {
  min=0,
  max=8,
  dateRange={
    startDate=-546,
    endDate=-300,
  }
}
troop_options['5fb1ba27e1af06001770ca71'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-546,
    endDate=-300,
  }
}
troop_options['5fb1ba27e1af06001770ca73'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-546,
    endDate=-300,
  }
}
troop_options['5fb1ba27e1af06001770ca75'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-546,
    endDate=-300,
  }
}
-- allies
-- 5fb1b9dde1af060017709617 Lykian  546 to 300 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba27e1af06001770ca68_general='5fb1ba27e1af06001770ca68_general'
g_base_definitions[g_str_5fb1ba27e1af06001770ca68_general]={
  id=g_str_5fb1ba27e1af06001770ca68_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba27e1af06001770ca67",
}
g_str_5fb1ba27e1af06001770ca68='5fb1ba27e1af06001770ca68'
g_base_definitions[g_str_5fb1ba27e1af06001770ca68]={
  id=g_str_5fb1ba27e1af06001770ca68,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba27e1af06001770ca67",
}
g_str_5fb1ba27e1af06001770ca6b_general='5fb1ba27e1af06001770ca6b_general'
g_base_definitions[g_str_5fb1ba27e1af06001770ca6b_general]={
  id=g_str_5fb1ba27e1af06001770ca6b_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='Battle platforms with javelin-armed crew',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770ca69",
}
g_str_5fb1ba27e1af06001770ca6b='5fb1ba27e1af06001770ca6b'
g_base_definitions[g_str_5fb1ba27e1af06001770ca6b]={
  id=g_str_5fb1ba27e1af06001770ca6b,
  name='Battle Taxi',
  min=0,
  max=1,
  description='Battle platforms with javelin-armed crew',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba27e1af06001770ca69",
}
g_str_5fb1ba27e1af06001770ca6d='5fb1ba27e1af06001770ca6d'
g_base_definitions[g_str_5fb1ba27e1af06001770ca6d]={
  id=g_str_5fb1ba27e1af06001770ca6d,
  name='Light Foot',
  min=7,
  max=14,
  description='Light infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba27e1af06001770ca6c",
}
g_str_5fb1ba27e1af06001770ca6f='5fb1ba27e1af06001770ca6f'
g_base_definitions[g_str_5fb1ba27e1af06001770ca6f]={
  id=g_str_5fb1ba27e1af06001770ca6f,
  name='Heavy Foot',
  min=0,
  max=8,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba27e1af06001770ca6e",
}
g_str_5fb1ba27e1af06001770ca72='5fb1ba27e1af06001770ca72'
g_base_definitions[g_str_5fb1ba27e1af06001770ca72]={
  id=g_str_5fb1ba27e1af06001770ca72,
  name='Raiders',
  min=0,
  max=2,
  description='Fighters with drepanon scythe-sword',
  troop_type="Raiders",
  troop_option_id="5fb1ba27e1af06001770ca71",
}
g_str_5fb1ba27e1af06001770ca74='5fb1ba27e1af06001770ca74'
g_base_definitions[g_str_5fb1ba27e1af06001770ca74]={
  id=g_str_5fb1ba27e1af06001770ca74,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba27e1af06001770ca73",
}
g_str_5fb1ba27e1af06001770ca76='5fb1ba27e1af06001770ca76'
g_base_definitions[g_str_5fb1ba27e1af06001770ca76]={
  id=g_str_5fb1ba27e1af06001770ca76,
  name='Rabble',
  min=0,
  max=2,
  description='Peasants',
  troop_type="Rabble",
  troop_option_id="5fb1ba27e1af06001770ca75",
}
g_str_5fb1b9dde1af060017709617_camp='5fb1b9dde1af060017709617_camp'
g_base_definitions[g_str_5fb1b9dde1af060017709617_camp]={
  id=g_str_5fb1b9dde1af060017709617_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dde1af060017709617_camp_pack_train='5fb1b9dde1af060017709617_camp_pack_train'
g_base_definitions[g_str_5fb1b9dde1af060017709617_camp_pack_train]={
  id=g_str_5fb1b9dde1af060017709617_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dde1af060017709617']={
  data={
    name='Lykian  546 to 300 BC',
    id='5fb1b9dde1af060017709617',
    army_id='5fb1b9dde1af060017709617'
  },
  g_base_definitions[g_str_5fb1ba27e1af06001770ca68_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca68],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6b_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6b],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6d],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6f],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca72],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca74],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca76],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af060017709617"] = army["5fb1b9dde1af060017709617"]
army['5fb1b9dde1af060017709617_-546_-500']={
  data={
    name='Lykian 546 BC to 500 BC',
    id='5fb1b9dde1af060017709617_-546_-500',
    army_id='5fb1b9dde1af060017709617'
  },
  g_base_definitions[g_str_5fb1ba27e1af06001770ca68_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca68],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6b_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6b],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6d],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6f],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca72],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca74],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca76],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp_pack_train],
}
army['5fb1b9dde1af060017709617_-499_-300']={
  data={
    name='Lykian 499 BC to 300 BC',
    id='5fb1b9dde1af060017709617_-499_-300',
    army_id='5fb1b9dde1af060017709617'
  },
  g_base_definitions[g_str_5fb1ba27e1af06001770ca68_general],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca68],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6d],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca6f],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca72],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca74],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca76],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709617_camp_pack_train],
}
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Lykian  546 to 300 BC"] = army["5fb1b9dde1af060017709617"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Lykian  546 to 300 BC"] = army["5fb1b9dde1af060017709617"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af060017709617"] = {}
army_dates["5fb1b9dde1af060017709617"]["546 BC to 300 BC"] ="5fb1b9dde1af060017709617"
army_dates["5fb1b9dde1af060017709617"]["546 BC to 500 BC"] ="5fb1b9dde1af060017709617_-546_-500"
army_dates["5fb1b9dde1af060017709617"]["499 BC to 300 BC"] ="5fb1b9dde1af060017709617_-499_-300"
