-- 5fb1b9f1e1af06001770a1df Nanyue  206 to 111 BC

army['5fb1b9f1e1af06001770a1df']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Nanyue  206 to 111 BC',
    id='5fb1b9f1e1af06001770a1df',
    dateRange={
      startDate=-206,
      endDate=-111,
    },
  },
  g_base_definitions[g_str_615351b303385c0016b88732_general],
  g_base_definitions[g_str_615351b303385c0016b88732],
  g_base_definitions[g_str_615351b303385c0016b88734],
  g_base_definitions[g_str_615351b303385c0016b88736_general],
  g_base_definitions[g_str_615351b303385c0016b88736],
  g_base_definitions[g_str_615351b303385c0016b88738],
  g_base_definitions[g_str_615351b303385c0016b8873a],
  g_base_definitions[g_str_615351b303385c0016b8873c],
  g_base_definitions[g_str_615351b303385c0016b8873e],
  g_base_definitions[g_str_615351b303385c0016b88740],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1df_camp],
  g_base_definitions[g_str_6153519b03385c0016b849f5],
  g_base_definitions[g_str_6153519b03385c0016b849f7],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1df"] = army["5fb1b9f1e1af06001770a1df"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Nanyue  206 to 111 BC"] = army["5fb1b9f1e1af06001770a1df"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Nanyue  206 to 111 BC"] = army["5fb1b9f1e1af06001770a1df"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Nanyue  206 to 111 BC"] = army["5fb1b9f1e1af06001770a1df"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1df"] = {}
army_dates["5fb1b9f1e1af06001770a1df"]["206 BC to 111 BC"] = {
  startDate=-206,
  endDate=-111
}
