-- 5fb1b9e1e1af060017709851 Early German Suevi  19 to 49 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba2be1af06001770d2ca_general='5fb1ba2be1af06001770d2ca_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ca_general]={
  id=g_str_5fb1ba2be1af06001770d2ca_general,
  name='Knights General',
  min=1,
  max=1,
  description='Sarmatians',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba2be1af06001770d2c9",
}
g_str_5fb1ba2be1af06001770d2ca='5fb1ba2be1af06001770d2ca'
g_base_definitions[g_str_5fb1ba2be1af06001770d2ca]={
  id=g_str_5fb1ba2be1af06001770d2ca,
  name='Knights',
  min=1,
  max=1,
  description='Sarmatians',
  troop_type="Knights",
  troop_option_id="5fb1ba2be1af06001770d2c9",
}
g_str_5fb1ba2be1af06001770d2cc='5fb1ba2be1af06001770d2cc'
g_base_definitions[g_str_5fb1ba2be1af06001770d2cc]={
  id=g_str_5fb1ba2be1af06001770d2cc,
  name='Javelin Cavalry',
  min=0,
  max=3,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d2cb",
}
g_str_5fb1ba2be1af06001770d2cc_dismounted='5fb1ba2be1af06001770d2cc_dismounted'
g_str_5fb1ba2be1af06001770d2cc_mounted='5fb1ba2be1af06001770d2cc_mounted'
g_base_definitions[g_str_5fb1ba2be1af06001770d2cc_dismounted]={
  id=g_str_5fb1ba2be1af06001770d2cc_dismounted,
  name='Warriors',
  min=0,
  max=3,
  description='Horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
  dismounted_from=g_str_5fb1ba2be1af06001770d2cc_mounted,
  troop_type="Warriors",
  troop_option_id="5fb1ba2be1af06001770d2cb",
}
g_base_definitions[g_str_5fb1ba2be1af06001770d2cc_mounted]={
  id=g_str_5fb1ba2be1af06001770d2cc_mounted,
  name='Javelin Cavalry',
  min=0,
  max=3,
  description='Horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_str_5fb1ba2be1af06001770d2cc_dismounted,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d2cb",
}
g_str_5fb1ba2be1af06001770d2cf='5fb1ba2be1af06001770d2cf'
g_base_definitions[g_str_5fb1ba2be1af06001770d2cf]={
  id=g_str_5fb1ba2be1af06001770d2cf,
  name='Warriors',
  min=6,
  max=13,
  description='Fierce fighters',
  troop_type="Warriors",
  troop_option_id="5fb1ba2be1af06001770d2ce",
}
g_str_5fb1ba2be1af06001770d2d1='5fb1ba2be1af06001770d2d1'
g_base_definitions[g_str_5fb1ba2be1af06001770d2d1]={
  id=g_str_5fb1ba2be1af06001770d2d1,
  name='Raiders',
  min=0,
  max=1,
  description='Fighters armed with sword, shield, and wooden club',
  troop_type="Raiders",
  troop_option_id="5fb1ba2be1af06001770d2d0",
}
g_str_5fb1ba2be1af06001770d2d3='5fb1ba2be1af06001770d2d3'
g_base_definitions[g_str_5fb1ba2be1af06001770d2d3]={
  id=g_str_5fb1ba2be1af06001770d2d3,
  name='Rabble',
  min=2,
  max=4,
  description='Foot skirmishers armed with many fire-hardened untipped throwing spears',
  troop_type="Rabble",
  troop_option_id="5fb1ba2be1af06001770d2d2",
}
g_str_5fb1ba2be1af06001770d2d5='5fb1ba2be1af06001770d2d5'
g_base_definitions[g_str_5fb1ba2be1af06001770d2d5]={
  id=g_str_5fb1ba2be1af06001770d2d5,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2be1af06001770d2d4",
}
g_str_5fb1b9e1e1af060017709851_camp='5fb1b9e1e1af060017709851_camp'
g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp]={
  id=g_str_5fb1b9e1e1af060017709851_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af060017709851_camp_fortified='5fb1b9e1e1af060017709851_camp_fortified'
g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp_fortified]={
  id=g_str_5fb1b9e1e1af060017709851_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af060017709851_camp_pack_train='5fb1b9e1e1af060017709851_camp_pack_train'
g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp_pack_train]={
  id=g_str_5fb1b9e1e1af060017709851_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e1e1af060017709851']={
  data={
    name='Early German Suevi  19 to 49 AD'
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ca_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ca],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2cc],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2cc_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2cc_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2cf],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2d1],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2d3],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2d5],
  g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709851"] = army["5fb1b9e1e1af060017709851"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early German Suevi  19 to 49 AD"] = army["5fb1b9e1e1af060017709851"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709851"] = {}
army_dates["5fb1b9e1e1af060017709851"]["19 AD to 49 AD"] ="5fb1b9e1e1af060017709851"
