-- 5fb1b9f6e1af06001770a46a Chimu Empire  1100 to 1480 AD

army['5fb1b9f6e1af06001770a46a']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Chimu Empire  1100 to 1480 AD',
    id='5fb1b9f6e1af06001770a46a',
    dateRange={
      startDate=1100,
      endDate=1480,
    },
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fe65_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe65],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe67],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe69],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe6c],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe6f],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a46a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a46a"] = army["5fb1b9f6e1af06001770a46a"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Chimu Empire  1100 to 1480 AD"] = army["5fb1b9f6e1af06001770a46a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Chimu Empire  1100 to 1480 AD"] = army["5fb1b9f6e1af06001770a46a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a46a"] = {}
army_dates["5fb1b9f6e1af06001770a46a"]["1100 AD to 1480 AD"] = {
  startDate=1100,
  endDate=1480
}
army_dates["5fb1b9f6e1af06001770a46a"]["1100 AD to 1464 AD"] = {
  startDate=1100,
  endDate=1464
}
army_dates["5fb1b9f6e1af06001770a46a"]["1465 AD to 1467 AD"] = {
  startDate=1465,
  endDate=1467
}
army_dates["5fb1b9f6e1af06001770a46a"]["1468 AD to 1480 AD"] = {
  startDate=1468,
  endDate=1480
}
