troop_options['5fb1ba35e1af06001770e437'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e439'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e43b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e43d'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e43f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e441'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e444'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e446'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e448'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e44b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e44d'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e44f'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e453'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
troop_options['5fb1ba35e1af06001770e455'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1151,
    endDate=1320,
  }
}
-- allies
-- 5fb1b9e9e1af060017709d3d Later Papal Italian  1151 to 1320 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba35e1af06001770e438_general='5fb1ba35e1af06001770e438_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e438_general]={
  id=g_str_5fb1ba35e1af06001770e438_general,
  name='Spears General',
  min=0,
  max=1,
  description='Papal guard spearmen',
  general=true,
  troop_type="Spears",
  troop_option_id="5fb1ba35e1af06001770e437",
}
g_str_5fb1ba35e1af06001770e438='5fb1ba35e1af06001770e438'
g_base_definitions[g_str_5fb1ba35e1af06001770e438]={
  id=g_str_5fb1ba35e1af06001770e438,
  name='Spears',
  min=0,
  max=1,
  description='Papal guard spearmen',
  troop_type="Spears",
  troop_option_id="5fb1ba35e1af06001770e437",
}
g_str_5fb1ba35e1af06001770e43a_general='5fb1ba35e1af06001770e43a_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e43a_general]={
  id=g_str_5fb1ba35e1af06001770e43a_general,
  name='Knights General',
  min=1,
  max=1,
  description='Papal feudal and Lombard mercenary men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba35e1af06001770e439",
}
g_str_5fb1ba35e1af06001770e43a='5fb1ba35e1af06001770e43a'
g_base_definitions[g_str_5fb1ba35e1af06001770e43a]={
  id=g_str_5fb1ba35e1af06001770e43a,
  name='Knights',
  min=1,
  max=2,
  description='Papal feudal and Lombard mercenary men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba35e1af06001770e439",
}
g_str_5fb1ba35e1af06001770e43c='5fb1ba35e1af06001770e43c'
g_base_definitions[g_str_5fb1ba35e1af06001770e43c]={
  id=g_str_5fb1ba35e1af06001770e43c,
  name='Skirmishers',
  min=0,
  max=1,
  description='Mercenary bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba35e1af06001770e43b",
}
g_str_5fb1ba35e1af06001770e43e_general='5fb1ba35e1af06001770e43e_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e43e_general]={
  id=g_str_5fb1ba35e1af06001770e43e_general,
  name='Spears General',
  min=0,
  max=1,
  description='Mercenary spearmen',
  general=true,
  troop_type="Spears",
  troop_option_id="5fb1ba35e1af06001770e43d",
}
g_str_5fb1ba35e1af06001770e43e='5fb1ba35e1af06001770e43e'
g_base_definitions[g_str_5fb1ba35e1af06001770e43e]={
  id=g_str_5fb1ba35e1af06001770e43e,
  name='Spears',
  min=0,
  max=1,
  description='Mercenary spearmen',
  troop_type="Spears",
  troop_option_id="5fb1ba35e1af06001770e43d",
}
g_str_5fb1ba35e1af06001770e440='5fb1ba35e1af06001770e440'
g_base_definitions[g_str_5fb1ba35e1af06001770e440]={
  id=g_str_5fb1ba35e1af06001770e440,
  name='Archers',
  min=0,
  max=1,
  description='Mercenary crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba35e1af06001770e43f",
}
g_str_5fb1ba35e1af06001770e442_general='5fb1ba35e1af06001770e442_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e442_general]={
  id=g_str_5fb1ba35e1af06001770e442_general,
  name='Knights General',
  min=1,
  max=1,
  description='Contadini and communal cavalieri and some German mercenary men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba35e1af06001770e441",
}
g_str_5fb1ba35e1af06001770e442='5fb1ba35e1af06001770e442'
g_base_definitions[g_str_5fb1ba35e1af06001770e442]={
  id=g_str_5fb1ba35e1af06001770e442,
  name='Knights',
  min=1,
  max=2,
  description='Contadini and communal cavalieri and some German mercenary men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba35e1af06001770e441",
}
g_str_5fb1ba35e1af06001770e443='5fb1ba35e1af06001770e443'
g_base_definitions[g_str_5fb1ba35e1af06001770e443]={
  id=g_str_5fb1ba35e1af06001770e443,
  name='Bad Horse',
  min=1,
  max=2,
  description='Contadini and communal cavalieri and some German mercenary men-at-arms',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba35e1af06001770e441",
}
g_str_5fb1ba35e1af06001770e445='5fb1ba35e1af06001770e445'
g_base_definitions[g_str_5fb1ba35e1af06001770e445]={
  id=g_str_5fb1ba35e1af06001770e445,
  name='Bad Horse',
  min=0,
  max=1,
  description='Crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba35e1af06001770e444",
}
g_str_5fb1ba35e1af06001770e447_general='5fb1ba35e1af06001770e447_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e447_general]={
  id=g_str_5fb1ba35e1af06001770e447_general,
  name='Spears General',
  min=0,
  max=1,
  description='Popolo spearmen',
  general=true,
  troop_type="Spears",
  troop_option_id="5fb1ba35e1af06001770e446",
}
g_str_5fb1ba35e1af06001770e447='5fb1ba35e1af06001770e447'
g_base_definitions[g_str_5fb1ba35e1af06001770e447]={
  id=g_str_5fb1ba35e1af06001770e447,
  name='Spears',
  min=0,
  max=1,
  description='Popolo spearmen',
  troop_type="Spears",
  troop_option_id="5fb1ba35e1af06001770e446",
}
g_str_5fb1ba35e1af06001770e449='5fb1ba35e1af06001770e449'
g_base_definitions[g_str_5fb1ba35e1af06001770e449]={
  id=g_str_5fb1ba35e1af06001770e449,
  name='Heavy Foot',
  min=2,
  max=6,
  description='Italian communal spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba35e1af06001770e448",
}
g_str_5fb1ba35e1af06001770e449_plaustrella='5fb1ba35e1af06001770e449_plaustrella'
g_base_definitions[g_str_5fb1ba35e1af06001770e449_plaustrella]={
  id=g_str_5fb1ba35e1af06001770e449_plaustrella,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Italian communal spearmen\nPlaustrella',
  plaustrella=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba35e1af06001770e448",
}
g_str_5fb1ba35e1af06001770e44c='5fb1ba35e1af06001770e44c'
g_base_definitions[g_str_5fb1ba35e1af06001770e44c]={
  id=g_str_5fb1ba35e1af06001770e44c,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Italian communal axemen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba35e1af06001770e44b",
}
g_str_5fb1ba35e1af06001770e44e='5fb1ba35e1af06001770e44e'
g_base_definitions[g_str_5fb1ba35e1af06001770e44e]={
  id=g_str_5fb1ba35e1af06001770e44e,
  name='Light Foot',
  min=0,
  max=2,
  description='Italian communal javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba35e1af06001770e44d",
}
g_str_5fb1ba35e1af06001770e450='5fb1ba35e1af06001770e450'
g_base_definitions[g_str_5fb1ba35e1af06001770e450]={
  id=g_str_5fb1ba35e1af06001770e450,
  name='Bow Levy',
  min=1,
  max=2,
  description='Italian communal crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba35e1af06001770e44f",
}
g_str_5fb1ba35e1af06001770e451='5fb1ba35e1af06001770e451'
g_base_definitions[g_str_5fb1ba35e1af06001770e451]={
  id=g_str_5fb1ba35e1af06001770e451,
  name='Pavisiers',
  min=1,
  max=2,
  description='Italian communal crossbowmen',
  troop_type="Pavisiers",
  troop_option_id="5fb1ba35e1af06001770e44f",
}
g_str_5fb1ba35e1af06001770e454='5fb1ba35e1af06001770e454'
g_base_definitions[g_str_5fb1ba35e1af06001770e454]={
  id=g_str_5fb1ba35e1af06001770e454,
  name='Skirmishers',
  min=0,
  max=1,
  description='Italian communal skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba35e1af06001770e453",
}
g_str_5fb1ba35e1af06001770e456='5fb1ba35e1af06001770e456'
g_base_definitions[g_str_5fb1ba35e1af06001770e456]={
  id=g_str_5fb1ba35e1af06001770e456,
  name='Horde',
  min=0,
  max=2,
  description='Contadini infantry',
  troop_type="Horde",
  troop_option_id="5fb1ba35e1af06001770e455",
}
g_str_5fb1b9e9e1af060017709d3d_camp='5fb1b9e9e1af060017709d3d_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d3d_camp]={
  id=g_str_5fb1b9e9e1af060017709d3d_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709d3d_camp_standard_wagon='5fb1b9e9e1af060017709d3d_camp_standard_wagon'
g_base_definitions[g_str_5fb1b9e9e1af060017709d3d_camp_standard_wagon]={
  id=g_str_5fb1b9e9e1af060017709d3d_camp_standard_wagon,
  name='Camp',
  min=0,
  max=1,
  description='Standard Wagon',
  standard_wagon=true,
  troop_type="Camp",
}
army['5fb1b9e9e1af060017709d3d']={
  data={
    name='Later Papal Italian  1151 to 1320 AD',
    id='5fb1b9e9e1af060017709d3d',
    army_id='5fb1b9e9e1af060017709d3d'
  },
  g_base_definitions[g_str_5fb1ba35e1af06001770e438_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e438],
  g_base_definitions[g_str_5fb1ba35e1af06001770e43a_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e43a],
  g_base_definitions[g_str_5fb1ba35e1af06001770e43c],
  g_base_definitions[g_str_5fb1ba35e1af06001770e43e_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e43e],
  g_base_definitions[g_str_5fb1ba35e1af06001770e440],
  g_base_definitions[g_str_5fb1ba35e1af06001770e442_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e442],
  g_base_definitions[g_str_5fb1ba35e1af06001770e443],
  g_base_definitions[g_str_5fb1ba35e1af06001770e445],
  g_base_definitions[g_str_5fb1ba35e1af06001770e447_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e447],
  g_base_definitions[g_str_5fb1ba35e1af06001770e449],
  g_base_definitions[g_str_5fb1ba35e1af06001770e449_plaustrella],
  g_base_definitions[g_str_5fb1ba35e1af06001770e44c],
  g_base_definitions[g_str_5fb1ba35e1af06001770e44e],
  g_base_definitions[g_str_5fb1ba35e1af06001770e450],
  g_base_definitions[g_str_5fb1ba35e1af06001770e451],
  g_base_definitions[g_str_5fb1ba35e1af06001770e454],
  g_base_definitions[g_str_5fb1ba35e1af06001770e456],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d3d_camp],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d3d_camp_standard_wagon],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d3d"] = army["5fb1b9e9e1af060017709d3d"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Later Papal Italian  1151 to 1320 AD"] = army["5fb1b9e9e1af060017709d3d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Papal Italian  1151 to 1320 AD"] = army["5fb1b9e9e1af060017709d3d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d3d"] = {}
army_dates["5fb1b9e9e1af060017709d3d"]["1151 AD to 1320 AD"] ="5fb1b9e9e1af060017709d3d"
