troop_options['5fb1ba39e1af06001770ebf7'] = {
  min=3,
  max=6,
  dateRange={
    startDate=747,
    endDate=750,
  }
}
troop_options['5fb1ba39e1af06001770ebfa'] = {
  min=2,
  max=4,
  dateRange={
    startDate=747,
    endDate=750,
  }
}
troop_options['5fb1ba39e1af06001770ebfd'] = {
  min=2,
  max=3,
  dateRange={
    startDate=747,
    endDate=750,
  }
}
troop_options['5fb1ba39e1af06001770ec01'] = {
  min=0,
  max=2,
  dateRange={
    startDate=747,
    endDate=750,
  }
}
troop_options['5fb1ba39e1af06001770ec03'] = {
  min=0,
  max=4,
  dateRange={
    startDate=747,
    endDate=750,
  }
}
-- allies
