-- 5fb1b9dbe1af0600177094e3 Early Hoplite Greek: Theban  669 to 449 BC

army['5fb1b9dbe1af0600177094e3']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Early Hoplite Greek: Theban  669 to 449 BC',
    id='5fb1b9dbe1af0600177094e3',
    dateRange={
      startDate=-669,
      endDate=-449,
    }
  },
  g_base_definitions[g_str_5fb1ba24e1af06001770c5a3_general],
  g_base_definitions[g_str_5fb1ba24e1af06001770c5a3],
  g_base_definitions[g_str_5fb1ba24e1af06001770c5a5],
  g_base_definitions[g_str_5fb1ba24e1af06001770c5a7],
  g_base_definitions[g_str_5fb1ba24e1af06001770c5a9],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094e3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094e3"] = army["5fb1b9dbe1af0600177094e3"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Hoplite Greek: Theban  669 to 449 BC"] = army["5fb1b9dbe1af0600177094e3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hoplite Greek: Theban  669 to 449 BC"] = army["5fb1b9dbe1af0600177094e3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094e3"] = {}
army_dates["5fb1b9dbe1af0600177094e3"]["669 BC to 449 BC"] = {
  startDate=-669,
  endDate=-449
}
