g_str_5fb1ba42e1af06001770fbc3_general='5fb1ba42e1af06001770fbc3_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fbc3_general]={
  id=g_str_5fb1ba42e1af06001770fbc3_general,
  name='Horse Bow General',
  min=2,
  max=1,
  description='Horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba42e1af06001770fbc1",
}
g_str_5fb1ba42e1af06001770fbc3='5fb1ba42e1af06001770fbc3'
g_base_definitions[g_str_5fb1ba42e1af06001770fbc3]={
  id=g_str_5fb1ba42e1af06001770fbc3,
  name='Horse Bow',
  min=2,
  max=4,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba42e1af06001770fbc1",
}
g_str_5fb1ba42e1af06001770fbc6='5fb1ba42e1af06001770fbc6'
g_base_definitions[g_str_5fb1ba42e1af06001770fbc6]={
  id=g_str_5fb1ba42e1af06001770fbc6,
  name='Cataphracts',
  min=1,
  max=2,
  description='Guard heavy horsemen',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba42e1af06001770fbc4",
}
g_str_5fb1ba42e1af06001770fbc9_general='5fb1ba42e1af06001770fbc9_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fbc9_general]={
  id=g_str_5fb1ba42e1af06001770fbc9_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba42e1af06001770fbc7",
}
g_str_5fb1ba42e1af06001770fbc9='5fb1ba42e1af06001770fbc9'
g_base_definitions[g_str_5fb1ba42e1af06001770fbc9]={
  id=g_str_5fb1ba42e1af06001770fbc9,
  name='Horse Bow',
  min=1,
  max=2,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba42e1af06001770fbc7",
}
g_str_5fb1ba42e1af06001770fbcb='5fb1ba42e1af06001770fbcb'
g_base_definitions[g_str_5fb1ba42e1af06001770fbcb]={
  id=g_str_5fb1ba42e1af06001770fbcb,
  name='Light Spear',
  min=1,
  max=2,
  description='Provincial spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fbca",
}
g_str_5fb1ba42e1af06001770fbcd='5fb1ba42e1af06001770fbcd'
g_base_definitions[g_str_5fb1ba42e1af06001770fbcd]={
  id=g_str_5fb1ba42e1af06001770fbcd,
  name='Archers',
  min=1,
  max=1,
  description='Provincial bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba42e1af06001770fbcc",
}
g_str_5fb1ba42e1af06001770fbcf='5fb1ba42e1af06001770fbcf'
g_base_definitions[g_str_5fb1ba42e1af06001770fbcf]={
  id=g_str_5fb1ba42e1af06001770fbcf,
  name='Light Spear',
  min=2,
  max=8,
  description='Militia spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fbce",
}
g_str_5fb1ba42e1af06001770fbd1='5fb1ba42e1af06001770fbd1'
g_base_definitions[g_str_5fb1ba42e1af06001770fbd1]={
  id=g_str_5fb1ba42e1af06001770fbd1,
  name='Bow Levy',
  min=2,
  max=8,
  description='Militia bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba42e1af06001770fbd0",
}
g_str_5fb1ba42e1af06001770fbd3='5fb1ba42e1af06001770fbd3'
g_base_definitions[g_str_5fb1ba42e1af06001770fbd3]={
  id=g_str_5fb1ba42e1af06001770fbd3,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba42e1af06001770fbd2",
}
g_str_5fb1b9f4e1af06001770a325_camp='5fb1b9f4e1af06001770a325_camp'
g_base_definitions[g_str_5fb1b9f4e1af06001770a325_camp]={
  id=g_str_5fb1b9f4e1af06001770a325_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f4e1af06001770a325_camp_fortified='5fb1b9f4e1af06001770a325_camp_fortified'
g_base_definitions[g_str_5fb1b9f4e1af06001770a325_camp_fortified]={
  id=g_str_5fb1b9f4e1af06001770a325_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba19e1af06001770bbd4='5fb1ba19e1af06001770bbd4'
g_base_definitions[g_str_5fb1ba19e1af06001770bbd4]={
  id=g_str_5fb1ba19e1af06001770bbd4,
  name='Archers',
  min=1,
  max=3,
  description='Bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba19e1af06001770bbd3",
}
g_str_5fb1ba19e1af06001770bbd6='5fb1ba19e1af06001770bbd6'
g_base_definitions[g_str_5fb1ba19e1af06001770bbd6]={
  id=g_str_5fb1ba19e1af06001770bbd6,
  name='Spears',
  min=1,
  max=2,
  description='Spearmen with large shields; spears could be very long',
  troop_type="Spears",
  troop_option_id="5fb1ba19e1af06001770bbd5",
}
g_str_5fb1ba19e1af06001770bbd7='5fb1ba19e1af06001770bbd7'
g_base_definitions[g_str_5fb1ba19e1af06001770bbd7]={
  id=g_str_5fb1ba19e1af06001770bbd7,
  name='Pikes',
  min=1,
  max=2,
  description='Spearmen with large shields; spears could be very long',
  troop_type="Pikes",
  troop_option_id="5fb1ba19e1af06001770bbd5",
}
g_str_5fb1ba19e1af06001770bbdb='5fb1ba19e1af06001770bbdb'
g_base_definitions[g_str_5fb1ba19e1af06001770bbdb]={
  id=g_str_5fb1ba19e1af06001770bbdb,
  name='Archers',
  min=0,
  max=1,
  description='Fully armored noble bowmen with pavise',
  troop_type="Archers",
  troop_option_id="5fb1ba19e1af06001770bbda",
}
g_str_5fb1ba19e1af06001770bbdd='5fb1ba19e1af06001770bbdd'
g_base_definitions[g_str_5fb1ba19e1af06001770bbdd]={
  id=g_str_5fb1ba19e1af06001770bbdd,
  name='Archers',
  min=1,
  max=2,
  description='Yatsuko retainer bowmen with less armor',
  troop_type="Archers",
  troop_option_id="5fb1ba19e1af06001770bbdc",
}
g_str_5fb1ba19e1af06001770bbdf='5fb1ba19e1af06001770bbdf'
g_base_definitions[g_str_5fb1ba19e1af06001770bbdf]={
  id=g_str_5fb1ba19e1af06001770bbdf,
  name='Spears',
  min=1,
  max=2,
  description='Spearmen with large shields; spears could be very long',
  troop_type="Spears",
  troop_option_id="5fb1ba19e1af06001770bbde",
}
g_str_5fb1ba19e1af06001770bbe0='5fb1ba19e1af06001770bbe0'
g_base_definitions[g_str_5fb1ba19e1af06001770bbe0]={
  id=g_str_5fb1ba19e1af06001770bbe0,
  name='Pikes',
  min=1,
  max=2,
  description='Spearmen with large shields; spears could be very long',
  troop_type="Pikes",
  troop_option_id="5fb1ba19e1af06001770bbde",
}
g_str_5fb1ba19e1af06001770bc1c='5fb1ba19e1af06001770bc1c'
g_base_definitions[g_str_5fb1ba19e1af06001770bc1c]={
  id=g_str_5fb1ba19e1af06001770bc1c,
  name='Pavisiers',
  min=2,
  max=3,
  description='Heishi militia bowmen protected by spearmen',
  troop_type="Pavisiers",
  troop_option_id="5fb1ba19e1af06001770bc1b",
}
g_str_5fb1ba19e1af06001770bc1f='5fb1ba19e1af06001770bc1f'
g_base_definitions[g_str_5fb1ba19e1af06001770bc1f]={
  id=g_str_5fb1ba19e1af06001770bc1f,
  name='Horse Bow',
  min=0,
  max=1,
  description='Kondei, fushu resettled Emishi, and similar additional horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba19e1af06001770bc1d",
}
g_str_5fb1ba19e1af06001770bbf5='5fb1ba19e1af06001770bbf5'
g_base_definitions[g_str_5fb1ba19e1af06001770bbf5]={
  id=g_str_5fb1ba19e1af06001770bbf5,
  name='Cataphracts',
  min=0,
  max=1,
  description='Noble heavy horsemen',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba19e1af06001770bbf4",
}
g_str_5fb1ba19e1af06001770bbf7='5fb1ba19e1af06001770bbf7'
g_base_definitions[g_str_5fb1ba19e1af06001770bbf7]={
  id=g_str_5fb1ba19e1af06001770bbf7,
  name='Elite Foot',
  min=0,
  max=1,
  description='Armored halberdiers',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba19e1af06001770bbf6",
}
g_str_5fb1ba19e1af06001770bbf9='5fb1ba19e1af06001770bbf9'
g_base_definitions[g_str_5fb1ba19e1af06001770bbf9]={
  id=g_str_5fb1ba19e1af06001770bbf9,
  name='Pikes',
  min=0,
  max=1,
  description='Infantry armed with long spears',
  troop_type="Pikes",
  troop_option_id="5fb1ba19e1af06001770bbf8",
}
g_str_5fb1ba19e1af06001770bbfb='5fb1ba19e1af06001770bbfb'
g_base_definitions[g_str_5fb1ba19e1af06001770bbfb]={
  id=g_str_5fb1ba19e1af06001770bbfb,
  name='Light Spear',
  min=1,
  max=2,
  description='Militia spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba19e1af06001770bbfa",
}
g_str_5fb1ba19e1af06001770bbfd='5fb1ba19e1af06001770bbfd'
g_base_definitions[g_str_5fb1ba19e1af06001770bbfd]={
  id=g_str_5fb1ba19e1af06001770bbfd,
  name='Bow Levy',
  min=0,
  max=1,
  description='Militia bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba19e1af06001770bbfc",
}
