g_str_5fb1ba34e1af06001770e39d_general='5fb1ba34e1af06001770e39d_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e39d_general]={
  id=g_str_5fb1ba34e1af06001770e39d_general,
  name='Knights General',
  min=2,
  max=1,
  description='Feudal men-at-arms and sergeants, or cavalieri',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e39c",
}
g_str_5fb1ba34e1af06001770e39d='5fb1ba34e1af06001770e39d'
g_base_definitions[g_str_5fb1ba34e1af06001770e39d]={
  id=g_str_5fb1ba34e1af06001770e39d,
  name='Knights',
  min=2,
  max=4,
  description='Feudal men-at-arms and sergeants, or cavalieri',
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e39c",
}
g_str_5fb1ba34e1af06001770e39f='5fb1ba34e1af06001770e39f'
g_base_definitions[g_str_5fb1ba34e1af06001770e39f]={
  id=g_str_5fb1ba34e1af06001770e39f,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Italian communal spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e39e",
}
g_str_5fb1ba34e1af06001770e3a1='5fb1ba34e1af06001770e3a1'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a1]={
  id=g_str_5fb1ba34e1af06001770e3a1,
  name='Bow Levy',
  min=0,
  max=2,
  description='Italian communal crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e3a0",
}
g_str_5fb1ba34e1af06001770e3a3='5fb1ba34e1af06001770e3a3'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a3]={
  id=g_str_5fb1ba34e1af06001770e3a3,
  name='Archers',
  min=0,
  max=2,
  description='Mercenary crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e3a2",
}
g_str_5fb1ba34e1af06001770e3a5='5fb1ba34e1af06001770e3a5'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a5]={
  id=g_str_5fb1ba34e1af06001770e3a5,
  name='Light Foot',
  min=0,
  max=3,
  description='Griffons: Sicilian Greek infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba34e1af06001770e3a4",
}
g_str_5fb1ba34e1af06001770e3a7='5fb1ba34e1af06001770e3a7'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a7]={
  id=g_str_5fb1ba34e1af06001770e3a7,
  name='Bow Levy',
  min=4,
  max=6,
  description='Saracen foot bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e3a6",
}
g_str_5fb1ba35e1af06001770e3a9='5fb1ba35e1af06001770e3a9'
g_base_definitions[g_str_5fb1ba35e1af06001770e3a9]={
  id=g_str_5fb1ba35e1af06001770e3a9,
  name='Light Foot',
  min=0,
  max=2,
  description='Saracen javelinmen or axemen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba34e1af06001770e3a8",
}
g_str_5fb1b9e9e1af060017709d1e_camp='5fb1b9e9e1af060017709d1e_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d1e_camp]={
  id=g_str_5fb1b9e9e1af060017709d1e_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba34e1af06001770e39d_general='5fb1ba34e1af06001770e39d_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e39d_general]={
  id=g_str_5fb1ba34e1af06001770e39d_general,
  name='Knights General',
  min=2,
  max=1,
  description='Feudal men-at-arms and sergeants, or cavalieri',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e39c",
}
g_str_5fb1ba34e1af06001770e39d='5fb1ba34e1af06001770e39d'
g_base_definitions[g_str_5fb1ba34e1af06001770e39d]={
  id=g_str_5fb1ba34e1af06001770e39d,
  name='Knights',
  min=2,
  max=4,
  description='Feudal men-at-arms and sergeants, or cavalieri',
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e39c",
}
g_str_5fb1ba34e1af06001770e39f='5fb1ba34e1af06001770e39f'
g_base_definitions[g_str_5fb1ba34e1af06001770e39f]={
  id=g_str_5fb1ba34e1af06001770e39f,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Italian communal spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e39e",
}
g_str_5fb1ba34e1af06001770e3a1='5fb1ba34e1af06001770e3a1'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a1]={
  id=g_str_5fb1ba34e1af06001770e3a1,
  name='Bow Levy',
  min=0,
  max=2,
  description='Italian communal crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e3a0",
}
g_str_5fb1ba34e1af06001770e3a3='5fb1ba34e1af06001770e3a3'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a3]={
  id=g_str_5fb1ba34e1af06001770e3a3,
  name='Archers',
  min=0,
  max=2,
  description='Mercenary crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e3a2",
}
g_str_5fb1ba34e1af06001770e3a5='5fb1ba34e1af06001770e3a5'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a5]={
  id=g_str_5fb1ba34e1af06001770e3a5,
  name='Light Foot',
  min=0,
  max=3,
  description='Griffons: Sicilian Greek infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba34e1af06001770e3a4",
}
g_str_5fb1ba34e1af06001770e3a7='5fb1ba34e1af06001770e3a7'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a7]={
  id=g_str_5fb1ba34e1af06001770e3a7,
  name='Bow Levy',
  min=4,
  max=6,
  description='Saracen foot bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e3a6",
}
g_str_5fb1ba35e1af06001770e3a9='5fb1ba35e1af06001770e3a9'
g_base_definitions[g_str_5fb1ba35e1af06001770e3a9]={
  id=g_str_5fb1ba35e1af06001770e3a9,
  name='Light Foot',
  min=0,
  max=2,
  description='Saracen javelinmen or axemen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba34e1af06001770e3a8",
}
g_str_5fb1b9e9e1af060017709d1e_camp='5fb1b9e9e1af060017709d1e_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d1e_camp]={
  id=g_str_5fb1b9e9e1af060017709d1e_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba34e1af06001770e39d_general='5fb1ba34e1af06001770e39d_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e39d_general]={
  id=g_str_5fb1ba34e1af06001770e39d_general,
  name='Knights General',
  min=2,
  max=1,
  description='Feudal men-at-arms and sergeants, or cavalieri',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e39c",
}
g_str_5fb1ba34e1af06001770e39d='5fb1ba34e1af06001770e39d'
g_base_definitions[g_str_5fb1ba34e1af06001770e39d]={
  id=g_str_5fb1ba34e1af06001770e39d,
  name='Knights',
  min=2,
  max=4,
  description='Feudal men-at-arms and sergeants, or cavalieri',
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e39c",
}
g_str_5fb1ba34e1af06001770e39f='5fb1ba34e1af06001770e39f'
g_base_definitions[g_str_5fb1ba34e1af06001770e39f]={
  id=g_str_5fb1ba34e1af06001770e39f,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Italian communal spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e39e",
}
g_str_5fb1ba34e1af06001770e3a1='5fb1ba34e1af06001770e3a1'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a1]={
  id=g_str_5fb1ba34e1af06001770e3a1,
  name='Bow Levy',
  min=0,
  max=2,
  description='Italian communal crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e3a0",
}
g_str_5fb1ba34e1af06001770e3a3='5fb1ba34e1af06001770e3a3'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a3]={
  id=g_str_5fb1ba34e1af06001770e3a3,
  name='Archers',
  min=0,
  max=2,
  description='Mercenary crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e3a2",
}
g_str_5fb1ba34e1af06001770e3a5='5fb1ba34e1af06001770e3a5'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a5]={
  id=g_str_5fb1ba34e1af06001770e3a5,
  name='Light Foot',
  min=0,
  max=3,
  description='Griffons: Sicilian Greek infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba34e1af06001770e3a4",
}
g_str_5fb1ba34e1af06001770e3a7='5fb1ba34e1af06001770e3a7'
g_base_definitions[g_str_5fb1ba34e1af06001770e3a7]={
  id=g_str_5fb1ba34e1af06001770e3a7,
  name='Bow Levy',
  min=4,
  max=6,
  description='Saracen foot bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e3a6",
}
g_str_5fb1ba35e1af06001770e3a9='5fb1ba35e1af06001770e3a9'
g_base_definitions[g_str_5fb1ba35e1af06001770e3a9]={
  id=g_str_5fb1ba35e1af06001770e3a9,
  name='Light Foot',
  min=0,
  max=2,
  description='Saracen javelinmen or axemen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba34e1af06001770e3a8",
}
g_str_5fb1b9e9e1af060017709d1e_camp='5fb1b9e9e1af060017709d1e_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d1e_camp]={
  id=g_str_5fb1b9e9e1af060017709d1e_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
