-- 5fb1b9d9e1af06001770933c Nubian  3000 to 1480 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba1fe1af06001770bf96='5fb1ba1fe1af06001770bf96'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf96]={
  id=g_str_5fb1ba1fe1af06001770bf96,
  name='Warband General',
  min=0,
  max=1,
  description='Nubian fierce close-combat fighters',
  general=true,
}
g_str_5fb1ba1fe1af06001770bf96='5fb1ba1fe1af06001770bf96'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf96]={
  id=g_str_5fb1ba1fe1af06001770bf96,
  name='Warband',
  min=0,
  max=5,
  description='Nubian fierce close-combat fighters',
}
g_str_5fb1ba1fe1af06001770bf98='5fb1ba1fe1af06001770bf98'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf98]={
  id=g_str_5fb1ba1fe1af06001770bf98,
  name='Archers General',
  min=6,
  max=1,
  description='Bowmen',
  general=true,
}
g_str_5fb1ba1fe1af06001770bf98='5fb1ba1fe1af06001770bf98'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf98]={
  id=g_str_5fb1ba1fe1af06001770bf98,
  name='Archers',
  min=6,
  max=16,
  description='Bowmen',
}
g_str_5fb1ba1fe1af06001770bf99='5fb1ba1fe1af06001770bf99'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf99]={
  id=g_str_5fb1ba1fe1af06001770bf99,
  name='Skirmishers General',
  min=6,
  max=1,
  description='Bowmen',
  general=true,
}
g_str_5fb1ba1fe1af06001770bf99='5fb1ba1fe1af06001770bf99'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf99]={
  id=g_str_5fb1ba1fe1af06001770bf99,
  name='Skirmishers',
  min=6,
  max=16,
  description='Bowmen',
}
g_str_5fb1ba1fe1af06001770bf9b='5fb1ba1fe1af06001770bf9b'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf9b]={
  id=g_str_5fb1ba1fe1af06001770bf9b,
  name='Rabble',
  min=0,
  max=4,
  description='Javelinmen',
}
g_str_5fb1b9d9e1af06001770933c_camp='5fb1b9d9e1af06001770933c_camp'
g_base_definitions[g_str_5fb1b9d9e1af06001770933c_camp]={
  name='Camp',
  id=g_str_5fb1b9d9e1af06001770933c_camp,
  min=1,
  max=1,
}
army['5fb1b9d9e1af06001770933c']={
  data={
    name='Nubian  3000 to 1480 BC'
  },
  g_base_definitions[g_str_5fb1b9d9e1af06001770933c_camp],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf9d],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf9f],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bfa1],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf96],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf96],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf98],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf98],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf99],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf99],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf9b],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af06001770933c"] = army["5fb1b9d9e1af06001770933c"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Nubian  3000 to 1480 BC"] = army["5fb1b9d9e1af06001770933c"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Nubian  3000 to 1480 BC"] = army["5fb1b9d9e1af06001770933c"]
