-- 5fb1b9e7e1af060017709c4b Medieval French  1347 to 1445 AD

army['5fb1b9e7e1af060017709c4b']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Medieval French  1347 to 1445 AD',
    id='5fb1b9e7e1af060017709c4b',
    dateRange={
      startDate=1347,
      endDate=1445,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e066],
  g_base_definitions[g_str_5fb1ba33e1af06001770e068],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06a],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06c],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06e],
  g_base_definitions[g_str_5fb1ba33e1af06001770e071],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e078],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c4b_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c4b"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c4b"] = {}
army_dates["5fb1b9e7e1af060017709c4b"]["1347 AD to 1445 AD"] = {
  startDate=1347,
  endDate=1445
}
army_dates["5fb1b9e7e1af060017709c4b"]["1347 AD to 1349 AD"] = {
  startDate=1347,
  endDate=1349
}
army_dates["5fb1b9e7e1af060017709c4b"]["1350 AD to 1361 AD"] = {
  startDate=1350,
  endDate=1361
}
army_dates["5fb1b9e7e1af060017709c4b"]["1362 AD to 1400 AD"] = {
  startDate=1362,
  endDate=1400
}
army_dates["5fb1b9e7e1af060017709c4b"]["1401 AD to 1429 AD"] = {
  startDate=1401,
  endDate=1429
}
army_dates["5fb1b9e7e1af060017709c4b"]["1430 AD to 1445 AD"] = {
  startDate=1430,
  endDate=1445
}
-- 5fb1b9e7e1af060017709c4b Medieval French  1347 to 1445 AD

army['5fb1b9e7e1af060017709c4b']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Medieval French  1347 to 1445 AD',
    id='5fb1b9e7e1af060017709c4b',
    dateRange={
      startDate=1347,
      endDate=1445,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e066],
  g_base_definitions[g_str_5fb1ba33e1af06001770e068],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06a],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06c],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06e],
  g_base_definitions[g_str_5fb1ba33e1af06001770e071],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e078],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c4b_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c4b"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c4b"] = {}
army_dates["5fb1b9e7e1af060017709c4b"]["1347 AD to 1445 AD"] = {
  startDate=1347,
  endDate=1445
}
army_dates["5fb1b9e7e1af060017709c4b"]["1347 AD to 1349 AD"] = {
  startDate=1347,
  endDate=1349
}
army_dates["5fb1b9e7e1af060017709c4b"]["1350 AD to 1361 AD"] = {
  startDate=1350,
  endDate=1361
}
army_dates["5fb1b9e7e1af060017709c4b"]["1362 AD to 1400 AD"] = {
  startDate=1362,
  endDate=1400
}
army_dates["5fb1b9e7e1af060017709c4b"]["1401 AD to 1429 AD"] = {
  startDate=1401,
  endDate=1429
}
army_dates["5fb1b9e7e1af060017709c4b"]["1430 AD to 1445 AD"] = {
  startDate=1430,
  endDate=1445
}
-- 5fb1b9e7e1af060017709c4b Medieval French  1347 to 1445 AD

army['5fb1b9e7e1af060017709c4b']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Medieval French  1347 to 1445 AD',
    id='5fb1b9e7e1af060017709c4b',
    dateRange={
      startDate=1347,
      endDate=1445,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e060_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e063_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e066],
  g_base_definitions[g_str_5fb1ba33e1af06001770e068],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06a],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06c],
  g_base_definitions[g_str_5fb1ba33e1af06001770e06e],
  g_base_definitions[g_str_5fb1ba33e1af06001770e071],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e074_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e078],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c4b_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c4b"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval French  1347 to 1445 AD"] = army["5fb1b9e7e1af060017709c4b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c4b"] = {}
army_dates["5fb1b9e7e1af060017709c4b"]["1347 AD to 1445 AD"] = {
  startDate=1347,
  endDate=1445
}
army_dates["5fb1b9e7e1af060017709c4b"]["1347 AD to 1349 AD"] = {
  startDate=1347,
  endDate=1349
}
army_dates["5fb1b9e7e1af060017709c4b"]["1350 AD to 1361 AD"] = {
  startDate=1350,
  endDate=1361
}
army_dates["5fb1b9e7e1af060017709c4b"]["1362 AD to 1400 AD"] = {
  startDate=1362,
  endDate=1400
}
army_dates["5fb1b9e7e1af060017709c4b"]["1401 AD to 1429 AD"] = {
  startDate=1401,
  endDate=1429
}
army_dates["5fb1b9e7e1af060017709c4b"]["1430 AD to 1445 AD"] = {
  startDate=1430,
  endDate=1445
}
