-- 5fb1b9dde1af0600177095ff Sacred War Phokian  357 to 347 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba27e1af06001770ca15='5fb1ba27e1af06001770ca15'
g_base_definitions[g_str_5fb1ba27e1af06001770ca15]={
  id=g_str_5fb1ba27e1af06001770ca15,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Phokian hoplites',
}
g_str_5fb1ba27e1af06001770ca18='5fb1ba27e1af06001770ca18'
g_base_definitions[g_str_5fb1ba27e1af06001770ca18]={
  id=g_str_5fb1ba27e1af06001770ca18,
  name='Light Foot',
  min=1,
  max=2,
  description='Psiloi armed with javelins',
}
g_str_5fb1ba27e1af06001770ca1a='5fb1ba27e1af06001770ca1a'
g_base_definitions[g_str_5fb1ba27e1af06001770ca1a]={
  id=g_str_5fb1ba27e1af06001770ca1a,
  name='Bad Horse',
  min=0,
  max=2,
  description='Horsemen',
}
g_str_5fb1ba27e1af06001770ca1c='5fb1ba27e1af06001770ca1c'
g_base_definitions[g_str_5fb1ba27e1af06001770ca1c]={
  id=g_str_5fb1ba27e1af06001770ca1c,
  name='Skirmishers',
  min=0,
  max=1,
  description='Cretan or other skirmishing mercenary bowmen',
}
g_str_5fb1ba27e1af06001770ca1e='5fb1ba27e1af06001770ca1e'
g_base_definitions[g_str_5fb1ba27e1af06001770ca1e]={
  id=g_str_5fb1ba27e1af06001770ca1e,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
}
g_str_5fb1ba27e1af06001770ca20='5fb1ba27e1af06001770ca20'
g_base_definitions[g_str_5fb1ba27e1af06001770ca20]={
  id=g_str_5fb1ba27e1af06001770ca20,
  name='Light Foot',
  min=0,
  max=1,
  description='Thracian infantry',
}
g_str_5fb1ba27e1af06001770ca22='5fb1ba27e1af06001770ca22'
g_base_definitions[g_str_5fb1ba27e1af06001770ca22]={
  id=g_str_5fb1ba27e1af06001770ca22,
  name='Heavy Foot',
  min=6,
  max=14,
  description='Mercenary hoplites',
}
g_str_5fb1ba27e1af06001770ca24='5fb1ba27e1af06001770ca24'
g_base_definitions[g_str_5fb1ba27e1af06001770ca24]={
  id=g_str_5fb1ba27e1af06001770ca24,
  name='Light Foot',
  min=0,
  max=4,
  description='Mercenary peltasts',
}
g_str_5fb1ba27e1af06001770ca26='5fb1ba27e1af06001770ca26'
g_base_definitions[g_str_5fb1ba27e1af06001770ca26]={
  id=g_str_5fb1ba27e1af06001770ca26,
  name='Artillery',
  min=0,
  max=3,
  description='Stone-throwers',
}
g_str_5fb1ba27e1af06001770ca28='5fb1ba27e1af06001770ca28'
g_base_definitions[g_str_5fb1ba27e1af06001770ca28]={
  name='Bad Horse General',
  id=g_str_5fb1ba27e1af06001770ca28,
  min=1,
  max=1,
}
g_str_5fb1ba27e1af06001770ca29='5fb1ba27e1af06001770ca29'
g_base_definitions[g_str_5fb1ba27e1af06001770ca29]={
  name='Heavy Foot General',
  id=g_str_5fb1ba27e1af06001770ca29,
  min=1,
  max=1,
}
g_str_5fb1b9dde1af0600177095ff_camp='5fb1b9dde1af0600177095ff_camp'
g_base_definitions[g_str_5fb1b9dde1af0600177095ff_camp]={
  name='Camp',
  id=g_str_5fb1b9dde1af0600177095ff_camp,
  min=1,
  max=1,
}
army['5fb1b9dde1af0600177095ff']={
  data={
    name='Sacred War Phokian  357 to 347 BC'
  },
  g_base_definitions[g_str_5fb1b9dde1af0600177095ff_camp],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca28],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca29],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca15],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca18],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca1a],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca1c],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca1e],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca20],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca22],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca24],
  g_base_definitions[g_str_5fb1ba27e1af06001770ca26],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af0600177095ff"] = army["5fb1b9dde1af0600177095ff"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Sacred War Phokian  357 to 347 BC"] = army["5fb1b9dde1af0600177095ff"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Sacred War Phokian  357 to 347 BC"] = army["5fb1b9dde1af0600177095ff"]
