-- 5fb1b9e9e1af060017709d49 Early Italian Condotta  1320 to 1362 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba35e1af06001770e479']= {
  min=3,
  max=6,
  description='Condottieri elmeti',
}
g_troop_entry['5fb1ba35e1af06001770e47a']= {
  troop_option='5fb1ba35e1af06001770e479',
  troopTypeCode='KNT',
}
g_troop_option['5fb1ba35e1af06001770e47b']= {
  min=0,
  max=2,
  description='Feudal elmeti',
  note='only Naples or Papal',
}
g_troop_entry['5fb1ba35e1af06001770e47c']= {
  troop_option='5fb1ba35e1af06001770e47b',
  troopTypeCode='KNT',
}
g_troop_option['5fb1ba35e1af06001770e47d']= {
  min=0,
  max=1,
  description='Crossbowmen on horses',
}
g_troop_entry['5fb1ba35e1af06001770e47e']= {
  troop_option='5fb1ba35e1af06001770e47d',
  troopTypeCode='BAD',
}
g_troop_option['5fb1ba35e1af06001770e47f']= {
  min=0,
  max=1,
  description='Hungarian horse archers',
  note='only Florence, Naples or Papal',
}
g_troop_entry['5fb1ba35e1af06001770e480']= {
  troop_option='5fb1ba35e1af06001770e47f',
  troopTypeCode='HBW',
}
g_troop_option['5fb1ba35e1af06001770e481']= {
  min=0,
  max=1,
  description='Militia spearmen or pikemen',
  core='all',
}
g_troop_entry['5fb1ba35e1af06001770e482']= {
  troop_option='5fb1ba35e1af06001770e481',
  troopTypeCode='HFT',
}
g_troop_option['5fb1ba35e1af06001770e483']= {
  min=1,
  max=2,
  description='Militia pavisiers and crossbowmen',
  core='all',
}
g_troop_entry['5fb1ba35e1af06001770e484']= {
  troop_option='5fb1ba35e1af06001770e483',
  troopTypeCode='PAV',
}
g_troop_option['5fb1ba35e1af06001770e486']= {
  min=0,
  max=1,
  description='Militia crossbowmen',
  core='all',
}
g_troop_entry['5fb1ba35e1af06001770e487']= {
  troop_option='5fb1ba35e1af06001770e486',
  troopTypeCode='BLV',
}
g_troop_option['5fb1ba35e1af06001770e488']= {
  min=0,
  max=1,
  description='Mercenary crossbowmen',
  core='all',
}
g_troop_entry['5fb1ba35e1af06001770e489']= {
  troop_option='5fb1ba35e1af06001770e488',
  troopTypeCode='ARC',
}
g_troop_entry['5fb1ba35e1af06001770e48a']= {
  troop_option='5fb1ba35e1af06001770e488',
  troopTypeCode='PAV',
}
g_troop_option['5fb1ba35e1af06001770e48b']= {
  min=0,
  max=1,
  description='Javelinmen or swordsmen',
}
g_troop_entry['5fb1ba35e1af06001770e48c']= {
  troop_option='5fb1ba35e1af06001770e48b',
  troopTypeCode='LFT',
}
g_troop_entry['5fb1ba35e1af06001770e48d']= {
  troop_option='5fb1ba35e1af06001770e48b',
  troopTypeCode='HFT',
}
g_troop_option['5fb1ba35e1af06001770e48e']= {
  min=0,
  max=1,
  description='Pioneers or armed peasants',
  core='all',
}
g_troop_entry['5fb1ba35e1af06001770e48f']= {
  troop_option='5fb1ba35e1af06001770e48e',
  troopTypeCode='HRD',
}
g_troop_option['5fb1ba35e1af06001770e490']= {
  min=0,
  max=1,
  description='Bombards and other big guns',
  core='all',
}
g_troop_entry['5fb1ba35e1af06001770e491']= {
  troop_option='5fb1ba35e1af06001770e490',
  troopTypeCode='ART',
}
g_str_5fb1ba35e1af06001770e47a_general='5fb1ba35e1af06001770e47a_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e47a_general]={
  id=g_str_5fb1ba35e1af06001770e47a_general,
  name='Knights General',
  min=3,
  max=1,
  description='Condottieri elmeti',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba35e1af06001770e47a='5fb1ba35e1af06001770e47a'
g_base_definitions[g_str_5fb1ba35e1af06001770e47a]={
  id=g_str_5fb1ba35e1af06001770e47a,
  name='Knights',
  min=3,
  max=6,
  description='Condottieri elmeti',
  troop_type="Knights",
}
g_str_5fb1ba35e1af06001770e47c_general='5fb1ba35e1af06001770e47c_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e47c_general]={
  id=g_str_5fb1ba35e1af06001770e47c_general,
  name='Knights General',
  min=0,
  max=1,
  description='Feudal elmeti',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba35e1af06001770e47c='5fb1ba35e1af06001770e47c'
g_base_definitions[g_str_5fb1ba35e1af06001770e47c]={
  id=g_str_5fb1ba35e1af06001770e47c,
  name='Knights',
  min=0,
  max=2,
  description='Feudal elmeti',
  troop_type="Knights",
}
g_str_5fb1ba35e1af06001770e47e='5fb1ba35e1af06001770e47e'
g_base_definitions[g_str_5fb1ba35e1af06001770e47e]={
  id=g_str_5fb1ba35e1af06001770e47e,
  name='Bad Horse',
  min=0,
  max=1,
  description='Crossbowmen on horses',
  troop_type="Bad Horse",
}
g_str_5fb1ba35e1af06001770e480='5fb1ba35e1af06001770e480'
g_base_definitions[g_str_5fb1ba35e1af06001770e480]={
  id=g_str_5fb1ba35e1af06001770e480,
  name='Horse Bow',
  min=0,
  max=1,
  description='Hungarian horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba35e1af06001770e482='5fb1ba35e1af06001770e482'
g_base_definitions[g_str_5fb1ba35e1af06001770e482]={
  id=g_str_5fb1ba35e1af06001770e482,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Militia spearmen or pikemen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba35e1af06001770e484='5fb1ba35e1af06001770e484'
g_base_definitions[g_str_5fb1ba35e1af06001770e484]={
  id=g_str_5fb1ba35e1af06001770e484,
  name='Pavisiers',
  min=1,
  max=2,
  description='Militia pavisiers and crossbowmen',
  troop_type="Pavisiers",
}
g_str_5fb1ba35e1af06001770e487='5fb1ba35e1af06001770e487'
g_base_definitions[g_str_5fb1ba35e1af06001770e487]={
  id=g_str_5fb1ba35e1af06001770e487,
  name='Bow Levy',
  min=0,
  max=1,
  description='Militia crossbowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba35e1af06001770e489='5fb1ba35e1af06001770e489'
g_base_definitions[g_str_5fb1ba35e1af06001770e489]={
  id=g_str_5fb1ba35e1af06001770e489,
  name='Archers',
  min=0,
  max=1,
  description='Mercenary crossbowmen',
  troop_type="Archers",
}
g_str_5fb1ba35e1af06001770e48a='5fb1ba35e1af06001770e48a'
g_base_definitions[g_str_5fb1ba35e1af06001770e48a]={
  id=g_str_5fb1ba35e1af06001770e48a,
  name='Pavisiers',
  min=0,
  max=1,
  description='Mercenary crossbowmen',
  troop_type="Pavisiers",
}
g_str_5fb1ba35e1af06001770e48c='5fb1ba35e1af06001770e48c'
g_base_definitions[g_str_5fb1ba35e1af06001770e48c]={
  id=g_str_5fb1ba35e1af06001770e48c,
  name='Light Foot',
  min=0,
  max=1,
  description='Javelinmen or swordsmen',
  troop_type="Light Foot",
}
g_str_5fb1ba35e1af06001770e48d='5fb1ba35e1af06001770e48d'
g_base_definitions[g_str_5fb1ba35e1af06001770e48d]={
  id=g_str_5fb1ba35e1af06001770e48d,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Javelinmen or swordsmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba35e1af06001770e48f='5fb1ba35e1af06001770e48f'
g_base_definitions[g_str_5fb1ba35e1af06001770e48f]={
  id=g_str_5fb1ba35e1af06001770e48f,
  name='Horde',
  min=0,
  max=1,
  description='Pioneers or armed peasants',
  troop_type="Horde",
}
g_str_5fb1ba35e1af06001770e491='5fb1ba35e1af06001770e491'
g_base_definitions[g_str_5fb1ba35e1af06001770e491]={
  id=g_str_5fb1ba35e1af06001770e491,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards and other big guns',
  troop_type="Artillery",
}
g_str_5fb1b9e9e1af060017709d49_camp='5fb1b9e9e1af060017709d49_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d49_camp]={
  id=g_str_5fb1b9e9e1af060017709d49_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709d49_camp_fortified='5fb1b9e9e1af060017709d49_camp_fortified'
g_base_definitions[g_str_5fb1b9e9e1af060017709d49_camp_fortified]={
  id=g_str_5fb1b9e9e1af060017709d49_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709d49_camp_standard_wagon='5fb1b9e9e1af060017709d49_camp_standard_wagon'
g_base_definitions[g_str_5fb1b9e9e1af060017709d49_camp_standard_wagon]={
  id=g_str_5fb1b9e9e1af060017709d49_camp_standard_wagon,
  name='Camp',
  min=0,
  max=1,
  description='Standard Wagon',
  standard_wagon=true,
  troop_type="Camp",
}
army['5fb1b9e9e1af060017709d49']={
  data={
    name='Early Italian Condotta  1320 to 1362 AD',
    id='5fb1b9e9e1af060017709d49',
    army_id='5fb1b9e9e1af060017709d49'
  },
  g_base_definitions[g_str_5fb1ba35e1af06001770e47a_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e47a],
  g_base_definitions[g_str_5fb1ba35e1af06001770e47c_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e47c],
  g_base_definitions[g_str_5fb1ba35e1af06001770e47e],
  g_base_definitions[g_str_5fb1ba35e1af06001770e480],
  g_base_definitions[g_str_5fb1ba35e1af06001770e482],
  g_base_definitions[g_str_5fb1ba35e1af06001770e484],
  g_base_definitions[g_str_5fb1ba35e1af06001770e487],
  g_base_definitions[g_str_5fb1ba35e1af06001770e489],
  g_base_definitions[g_str_5fb1ba35e1af06001770e48a],
  g_base_definitions[g_str_5fb1ba35e1af06001770e48c],
  g_base_definitions[g_str_5fb1ba35e1af06001770e48d],
  g_base_definitions[g_str_5fb1ba35e1af06001770e48f],
  g_base_definitions[g_str_5fb1ba35e1af06001770e491],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d49_camp],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d49_camp_fortified],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d49_camp_standard_wagon],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d49"] = army["5fb1b9e9e1af060017709d49"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Early Italian Condotta  1320 to 1362 AD"] = army["5fb1b9e9e1af060017709d49"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Italian Condotta  1320 to 1362 AD"] = army["5fb1b9e9e1af060017709d49"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d49"] = {}
army_dates["5fb1b9e9e1af060017709d49"]["1320 AD to 1362 AD"] ="5fb1b9e9e1af060017709d49"
