-- 5fb1b9f5e1af06001770a3e9 West Mexican  1101 to 1526 AD

army['5fb1b9f5e1af06001770a3e9']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='West Mexican  1101 to 1526 AD',
    id='5fb1b9f5e1af06001770a3e9',
    dateRange={
      startDate=1101,
      endDate=1526,
    },
  },
  g_base_definitions[g_str_615351b603385c0016b88e04],
  g_base_definitions[g_str_615351b603385c0016b88e06_general],
  g_base_definitions[g_str_615351b603385c0016b88e06],
  g_base_definitions[g_str_615351b603385c0016b88e08],
  g_base_definitions[g_str_615351b603385c0016b88e0b],
  g_base_definitions[g_str_615351b603385c0016b88e0d],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3e9_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3e9"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["West Mexican  1101 to 1526 AD"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["West Mexican  1101 to 1526 AD"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["West Mexican  1101 to 1526 AD"] = army["5fb1b9f5e1af06001770a3e9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3e9"] = {}
army_dates["5fb1b9f5e1af06001770a3e9"]["1101 AD to 1526 AD"] = {
  startDate=1101,
  endDate=1526
}
