-- 5fb1b9dce1af060017709543 Camillan Roman  400 to 276 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba26e1af06001770c71c_general='5fb1ba26e1af06001770c71c_general'
g_base_definitions[g_str_5fb1ba26e1af06001770c71c_general]={
  id=g_str_5fb1ba26e1af06001770c71c_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Roman and better ally horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba26e1af06001770c71b",
}
g_str_5fb1ba26e1af06001770c71c='5fb1ba26e1af06001770c71c'
g_base_definitions[g_str_5fb1ba26e1af06001770c71c]={
  id=g_str_5fb1ba26e1af06001770c71c,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Roman and better ally horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba26e1af06001770c71b",
}
g_str_5fb1ba26e1af06001770c71e_general='5fb1ba26e1af06001770c71e_general'
g_base_definitions[g_str_5fb1ba26e1af06001770c71e_general]={
  id=g_str_5fb1ba26e1af06001770c71e_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Italian ally horsemen',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba26e1af06001770c71d",
}
g_str_5fb1ba26e1af06001770c71e='5fb1ba26e1af06001770c71e'
g_base_definitions[g_str_5fb1ba26e1af06001770c71e]={
  id=g_str_5fb1ba26e1af06001770c71e,
  name='Bad Horse',
  min=0,
  max=2,
  description='Italian ally horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba26e1af06001770c71d",
}
g_str_5fb1ba26e1af06001770c720_general='5fb1ba26e1af06001770c720_general'
g_base_definitions[g_str_5fb1ba26e1af06001770c720_general]={
  id=g_str_5fb1ba26e1af06001770c720_general,
  name='Elite Foot General',
  min=3,
  max=1,
  description='Triarii, principes, and better-equipped hastati',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba26e1af06001770c71f",
}
g_str_5fb1ba26e1af06001770c720='5fb1ba26e1af06001770c720'
g_base_definitions[g_str_5fb1ba26e1af06001770c720]={
  id=g_str_5fb1ba26e1af06001770c720,
  name='Elite Foot',
  min=3,
  max=8,
  description='Triarii, principes, and better-equipped hastati',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba26e1af06001770c71f",
}
g_str_5fb1ba26e1af06001770c723='5fb1ba26e1af06001770c723'
g_base_definitions[g_str_5fb1ba26e1af06001770c723]={
  id=g_str_5fb1ba26e1af06001770c723,
  name='Heavy Foot',
  min=3,
  max=8,
  description='Hastati, or Latin ally heavy infantry',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba26e1af06001770c722",
}
g_str_5fb1ba26e1af06001770c725='5fb1ba26e1af06001770c725'
g_base_definitions[g_str_5fb1ba26e1af06001770c725]={
  id=g_str_5fb1ba26e1af06001770c725,
  name='Rabble',
  min=2,
  max=8,
  description='Leves and rorarii',
  troop_type="Rabble",
  troop_option_id="5fb1ba26e1af06001770c724",
}
g_str_5fb1ba26e1af06001770c727='5fb1ba26e1af06001770c727'
g_base_definitions[g_str_5fb1ba26e1af06001770c727]={
  id=g_str_5fb1ba26e1af06001770c727,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Accensi',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba26e1af06001770c726",
}
g_str_5fb1ba26e1af06001770c729='5fb1ba26e1af06001770c729'
g_base_definitions[g_str_5fb1ba26e1af06001770c729]={
  id=g_str_5fb1ba26e1af06001770c729,
  name='Light Foot',
  min=1,
  max=8,
  description='Italian allied infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba26e1af06001770c728",
}
g_str_5fb1b9dce1af060017709543_camp='5fb1b9dce1af060017709543_camp'
g_base_definitions[g_str_5fb1b9dce1af060017709543_camp]={
  id=g_str_5fb1b9dce1af060017709543_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dce1af060017709543_camp_fortified='5fb1b9dce1af060017709543_camp_fortified'
g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_fortified]={
  id=g_str_5fb1b9dce1af060017709543_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dce1af060017709543_camp_pack_train='5fb1b9dce1af060017709543_camp_pack_train'
g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_pack_train]={
  id=g_str_5fb1b9dce1af060017709543_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dce1af060017709543']={
  data={
    name='Camillan Roman  400 to 276 BC'
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71c],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c71e],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c720],
  g_base_definitions[g_str_5fb1ba26e1af06001770c723],
  g_base_definitions[g_str_5fb1ba26e1af06001770c725],
  g_base_definitions[g_str_5fb1ba26e1af06001770c727],
  g_base_definitions[g_str_5fb1ba26e1af06001770c729],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_fortified],
  g_base_definitions[g_str_5fb1b9dce1af060017709543_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709543"] = army["5fb1b9dce1af060017709543"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Camillan Roman  400 to 276 BC"] = army["5fb1b9dce1af060017709543"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709543"] = {}
army_dates["5fb1b9dce1af060017709543"]["400 BC to 276 BC"] ="5fb1b9dce1af060017709543"
