-- 5fb1b9f5e1af06001770a3a3 Early Horizon Period Maya  400 BC to 200 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba43e1af06001770fd24='5fb1ba43e1af06001770fd24'
g_base_definitions[g_str_5fb1ba43e1af06001770fd24]={
  id=g_str_5fb1ba43e1af06001770fd24,
  name='Light Foot',
  min=2,
  max=6,
  description='Nobles and elite infantry',
}
g_str_5fb1ba43e1af06001770fd26='5fb1ba43e1af06001770fd26'
g_base_definitions[g_str_5fb1ba43e1af06001770fd26]={
  id=g_str_5fb1ba43e1af06001770fd26,
  name='Rabble',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
}
g_str_5fb1ba43e1af06001770fd28='5fb1ba43e1af06001770fd28'
g_base_definitions[g_str_5fb1ba43e1af06001770fd28]={
  id=g_str_5fb1ba43e1af06001770fd28,
  name='Skirmishers',
  min=0,
  max=4,
  description='Peasant skirmishing slingers',
}
g_str_5fb1ba43e1af06001770fd2a='5fb1ba43e1af06001770fd2a'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2a]={
  name='Light Foot General',
  id=g_str_5fb1ba43e1af06001770fd2a,
  min=1,
  max=1,
}
g_str_5fb1b9f5e1af06001770a3a3_camp='5fb1b9f5e1af06001770a3a3_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3a3_camp]={
  name='Camp',
  id=g_str_5fb1b9f5e1af06001770a3a3_camp,
  min=1,
  max=1,
}
army['5fb1b9f5e1af06001770a3a3']={
  data={
    name='Early Horizon Period Maya  400 BC to 200 AD'
  },
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3a3_camp],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd2a],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd24],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd26],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd28],
}
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Early Horizon Period Maya  400 BC to 200 AD"] = army["5fb1b9f5e1af06001770a3a3"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Early Horizon Period Maya  400 BC to 200 AD"] = army["5fb1b9f5e1af06001770a3a3"]
