-- 5fb1b9e8e1af060017709c5b Later French Ordonnance  1481 to 1494 AD

army['5fb1b9e8e1af060017709c5b']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Later French Ordonnance  1481 to 1494 AD',
    id='5fb1b9e8e1af060017709c5b',
    dateRange={
      startDate=1481,
      endDate=1494,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e09d_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e09d_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e09d_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e09d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e09d_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e09d_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a0],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a0_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a0_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a3_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a3],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a5],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a5_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a5_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0a8],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0aa],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0ab],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0ad],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0af],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0af_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0af_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0b2],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0b4],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0b6],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c5b_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c5b"] = army["5fb1b9e8e1af060017709c5b"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Later French Ordonnance  1481 to 1494 AD"] = army["5fb1b9e8e1af060017709c5b"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Later French Ordonnance  1481 to 1494 AD"] = army["5fb1b9e8e1af060017709c5b"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Later French Ordonnance  1481 to 1494 AD"] = army["5fb1b9e8e1af060017709c5b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later French Ordonnance  1481 to 1494 AD"] = army["5fb1b9e8e1af060017709c5b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c5b"] = {}
army_dates["5fb1b9e8e1af060017709c5b"]["1481 AD to 1494 AD"] = {
  startDate=1481,
  endDate=1494
}
army_dates["5fb1b9e8e1af060017709c5b"]["1481 AD to 1487 AD"] = {
  startDate=1481,
  endDate=1487
}
army_dates["5fb1b9e8e1af060017709c5b"]["1488 AD"] = {
  startDate=1488,
  endDate=1488
}
army_dates["5fb1b9e8e1af060017709c5b"]["1489 AD to 1491 AD"] = {
  startDate=1489,
  endDate=1491
}
army_dates["5fb1b9e8e1af060017709c5b"]["1492 AD to 1494 AD"] = {
  startDate=1492,
  endDate=1494
}
