troop_options['615351b403385c0016b88956'] = {
  min=1,
  max=2,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b88958'] = {
  min=0,
  max=1,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b8895a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b8895c'] = {
  min=1,
  max=3,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b8895e'] = {
  min=1,
  max=3,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b88960'] = {
  min=2,
  max=4,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b88963'] = {
  min=2,
  max=3,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b88965'] = {
  min=0,
  max=2,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
troop_options['615351b403385c0016b88968'] = {
  min=0,
  max=4,
  dateRange={
    startDate=907,
    endDate=960,
  }
}
-- allies
