-- 5fb1b9e9e1af060017709d1e Sicilio-Norman  1072 to 1193 AD

army['5fb1b9e9e1af060017709d1e']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Sicilio-Norman  1072 to 1193 AD',
    id='5fb1b9e9e1af060017709d1e',
    dateRange={
      startDate=1072,
      endDate=1193,
    },
  },
  g_base_definitions[g_str_615351ac03385c0016b8740f_general],
  g_base_definitions[g_str_615351ac03385c0016b8740f],
  g_base_definitions[g_str_615351ac03385c0016b87411],
  g_base_definitions[g_str_615351ac03385c0016b87413],
  g_base_definitions[g_str_615351ac03385c0016b87415],
  g_base_definitions[g_str_615351ac03385c0016b87417],
  g_base_definitions[g_str_615351ac03385c0016b87419],
  g_base_definitions[g_str_615351ac03385c0016b8741b],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d1e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d1e"] = army["5fb1b9e9e1af060017709d1e"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Sicilio-Norman  1072 to 1193 AD"] = army["5fb1b9e9e1af060017709d1e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sicilio-Norman  1072 to 1193 AD"] = army["5fb1b9e9e1af060017709d1e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d1e"] = {}
army_dates["5fb1b9e9e1af060017709d1e"]["1072 AD to 1193 AD"] = {
  startDate=1072,
  endDate=1193
}
