-- 5fb1b9e9e1af060017709d15 Early Renaissance Swiss  1478 to 1522 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba34e1af06001770e392_general='5fb1ba34e1af06001770e392_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e392_general]={
  id=g_str_5fb1ba34e1af06001770e392_general,
  name='Pikes General',
  min=11,
  max=1,
  description='Pikemen mixed with some halberdiers',
  general=true,
  troop_type="Pikes",
}
g_str_5fb1ba34e1af06001770e392='5fb1ba34e1af06001770e392'
g_base_definitions[g_str_5fb1ba34e1af06001770e392]={
  id=g_str_5fb1ba34e1af06001770e392,
  name='Pikes',
  min=11,
  max=15,
  description='Pikemen mixed with some halberdiers',
  troop_type="Pikes",
}
g_str_5fb1ba34e1af06001770e394='5fb1ba34e1af06001770e394'
g_base_definitions[g_str_5fb1ba34e1af06001770e394]={
  id=g_str_5fb1ba34e1af06001770e394,
  name='Raiders',
  min=0,
  max=1,
  description='Separately deployed halberdiers, some with armor',
  troop_type="Raiders",
}
g_str_5fb1ba34e1af06001770e395='5fb1ba34e1af06001770e395'
g_base_definitions[g_str_5fb1ba34e1af06001770e395]={
  id=g_str_5fb1ba34e1af06001770e395,
  name='Elite Foot',
  min=0,
  max=1,
  description='Separately deployed halberdiers, some with armor',
  troop_type="Elite Foot",
}
g_str_5fb1ba34e1af06001770e397='5fb1ba34e1af06001770e397'
g_base_definitions[g_str_5fb1ba34e1af06001770e397]={
  id=g_str_5fb1ba34e1af06001770e397,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing handgunners',
  troop_type="Skirmishers",
}
g_str_5fb1ba34e1af06001770e399='5fb1ba34e1af06001770e399'
g_base_definitions[g_str_5fb1ba34e1af06001770e399]={
  id=g_str_5fb1ba34e1af06001770e399,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing crossbowmen or handgunners',
  troop_type="Skirmishers",
}
g_str_5fb1b9e9e1af060017709d15_camp='5fb1b9e9e1af060017709d15_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d15_camp]={
  name='Camp',
  id=g_str_5fb1b9e9e1af060017709d15_camp,
  min=1,
  max=1,
}
army['5fb1b9e9e1af060017709d15']={
  data={
    name='Early Renaissance Swiss  1478 to 1522 AD'
  },
  g_base_definitions[g_str_5fb1b9e9e1af060017709d15_camp],
  g_base_definitions[g_str_5fb1ba34e1af06001770e392_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e392],
  g_base_definitions[g_str_5fb1ba34e1af06001770e394],
  g_base_definitions[g_str_5fb1ba34e1af06001770e395],
  g_base_definitions[g_str_5fb1ba34e1af06001770e397],
  g_base_definitions[g_str_5fb1ba34e1af06001770e399],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d15"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
