troop_options['615351b603385c0016b88e40'] = {
  min=1,
  max=3,
  dateRange={
    startDate=1401,
    endDate=1521,
  }
}
troop_options['615351b603385c0016b88e43'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1401,
    endDate=1521,
  }
}
troop_options['615351b603385c0016b88e46'] = {
  min=6,
  max=20,
  dateRange={
    startDate=1401,
    endDate=1521,
  }
}
troop_options['615351b603385c0016b88e49'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1401,
    endDate=1521,
  }
}
-- allies
