-- 5fb1b9f3e1af06001770a2e1 Yuan in the Steppe or Korea  1260 to 1368 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba41e1af06001770faa5']= {
  min=1,
  max=2,
  description='Guard horsemen',
  core='all',
}
g_str_5fb1ba41e1af06001770faa6_general='5fb1ba41e1af06001770faa6_general'
g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general]={
  id=g_str_5fb1ba41e1af06001770faa6_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Guard horsemen',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770faa5",
}
g_str_5fb1ba41e1af06001770faa6_general_dismounted='5fb1ba41e1af06001770faa6_general_dismounted'
g_str_5fb1ba41e1af06001770faa6_general_mounted='5fb1ba41e1af06001770faa6_general_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted]={
  id=g_str_5fb1ba41e1af06001770faa6_general_dismounted,
  name='Archers General',
  min=1,
  max=1,
  description='Guard horsemen\nDeployment dismounted from Elite Cavalary General',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770faa6_general_mounted,
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770faa5",
}
g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted]={
  id=g_str_5fb1ba41e1af06001770faa6_general_mounted,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Guard horsemen\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770faa6_general_dismounted,
  general=true,
  deployment_dismounting=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770faa5",
}
g_str_5fb1ba41e1af06001770faa6='5fb1ba41e1af06001770faa6'
g_base_definitions[g_str_5fb1ba41e1af06001770faa6]={
  id=g_str_5fb1ba41e1af06001770faa6,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Guard horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770faa5",
}
g_str_5fb1ba41e1af06001770faa6_dismounted='5fb1ba41e1af06001770faa6_dismounted'
g_str_5fb1ba41e1af06001770faa6_mounted='5fb1ba41e1af06001770faa6_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted]={
  id=g_str_5fb1ba41e1af06001770faa6_dismounted,
  name='Archers',
  min=1,
  max=2,
  description='Guard horsemen\nDeployment dismounted from Elite Cavalary',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770faa6_mounted,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770faa5",
}
g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted]={
  id=g_str_5fb1ba41e1af06001770faa6_mounted,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Guard horsemen\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770faa6_dismounted,
  deployment_dismounting=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770faa5",
}
g_troop_option['5fb1ba41e1af06001770faa8']= {
  min=0,
  max=1,
  description='Chinese guards',
  core='all',
}
g_str_5fb1ba41e1af06001770faa9='5fb1ba41e1af06001770faa9'
g_base_definitions[g_str_5fb1ba41e1af06001770faa9]={
  id=g_str_5fb1ba41e1af06001770faa9,
  name='Elite Foot',
  min=0,
  max=1,
  description='Chinese guards',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba41e1af06001770faa8",
}
g_troop_option['5fb1ba41e1af06001770faab']= {
  min=0,
  max=1,
  description='North Chinese subject horsemen',
  core='all',
  startDate=1260,
  endDate=1274,
}
g_str_5fb1ba41e1af06001770faad_general='5fb1ba41e1af06001770faad_general'
g_base_definitions[g_str_5fb1ba41e1af06001770faad_general]={
  id=g_str_5fb1ba41e1af06001770faad_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='North Chinese subject horsemen',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770faab",
}
g_str_5fb1ba41e1af06001770faad='5fb1ba41e1af06001770faad'
g_base_definitions[g_str_5fb1ba41e1af06001770faad]={
  id=g_str_5fb1ba41e1af06001770faad,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='North Chinese subject horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770faab",
}
g_troop_option['5fb1ba41e1af06001770faae']= {
  min=2,
  max=7,
  description='Mongol horse archers',
  startDate=1260,
  endDate=1300,
}
g_str_5fb1ba41e1af06001770fab0_general='5fb1ba41e1af06001770fab0_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general]={
  id=g_str_5fb1ba41e1af06001770fab0_general,
  name='Horse Bow General',
  min=2,
  max=1,
  description='Mongol horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770faae",
}
g_str_5fb1ba41e1af06001770fab0_general_dismounted='5fb1ba41e1af06001770fab0_general_dismounted'
g_str_5fb1ba41e1af06001770fab0_general_mounted='5fb1ba41e1af06001770fab0_general_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_dismounted]={
  id=g_str_5fb1ba41e1af06001770fab0_general_dismounted,
  name='Archers General',
  min=2,
  max=1,
  description='Mongol horse archers\nDeployment dismounted from Horse Bow General',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770fab0_general_mounted,
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770faae",
}
g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_mounted]={
  id=g_str_5fb1ba41e1af06001770fab0_general_mounted,
  name='Horse Bow General',
  min=2,
  max=1,
  description='Mongol horse archers\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770fab0_general_dismounted,
  general=true,
  deployment_dismounting=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770faae",
}
g_str_5fb1ba41e1af06001770fab0='5fb1ba41e1af06001770fab0'
g_base_definitions[g_str_5fb1ba41e1af06001770fab0]={
  id=g_str_5fb1ba41e1af06001770fab0,
  name='Horse Bow',
  min=2,
  max=7,
  description='Mongol horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770faae",
}
g_str_5fb1ba41e1af06001770fab0_dismounted='5fb1ba41e1af06001770fab0_dismounted'
g_str_5fb1ba41e1af06001770fab0_mounted='5fb1ba41e1af06001770fab0_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770fab0_dismounted]={
  id=g_str_5fb1ba41e1af06001770fab0_dismounted,
  name='Archers',
  min=2,
  max=7,
  description='Mongol horse archers\nDeployment dismounted from Horse Bow',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770fab0_mounted,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770faae",
}
g_base_definitions[g_str_5fb1ba41e1af06001770fab0_mounted]={
  id=g_str_5fb1ba41e1af06001770fab0_mounted,
  name='Horse Bow',
  min=2,
  max=7,
  description='Mongol horse archers\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770fab0_dismounted,
  deployment_dismounting=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770faae",
}
g_troop_option['5fb1ba41e1af06001770fab2']= {
  min=2,
  max=3,
  description='Menggu jun settled Mongol horse archers with inferior mounts and training',
  startDate=1301,
  endDate=1368,
}
g_str_5fb1ba41e1af06001770fab4='5fb1ba41e1af06001770fab4'
g_base_definitions[g_str_5fb1ba41e1af06001770fab4]={
  id=g_str_5fb1ba41e1af06001770fab4,
  name='Bad Horse',
  min=2,
  max=3,
  description='Menggu jun settled Mongol horse archers with inferior mounts and training',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fab2",
}
g_str_5fb1ba41e1af06001770fab4_dismounted='5fb1ba41e1af06001770fab4_dismounted'
g_str_5fb1ba41e1af06001770fab4_mounted='5fb1ba41e1af06001770fab4_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770fab4_dismounted]={
  id=g_str_5fb1ba41e1af06001770fab4_dismounted,
  name='Archers',
  min=2,
  max=3,
  description='Menggu jun settled Mongol horse archers with inferior mounts and training\nDeployment dismounted from Bad Horse',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770fab4_mounted,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770fab2",
}
g_base_definitions[g_str_5fb1ba41e1af06001770fab4_mounted]={
  id=g_str_5fb1ba41e1af06001770fab4_mounted,
  name='Bad Horse',
  min=2,
  max=3,
  description='Menggu jun settled Mongol horse archers with inferior mounts and training\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770fab4_dismounted,
  deployment_dismounting=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fab2",
}
g_troop_option['5fb1ba41e1af06001770fab6']= {
  min=0,
  max=4,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training',
  startDate=1301,
  endDate=1368,
}
g_str_5fb1ba41e1af06001770fab8_general='5fb1ba41e1af06001770fab8_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general]={
  id=g_str_5fb1ba41e1af06001770fab8_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_str_5fb1ba41e1af06001770fab8_general_dismounted='5fb1ba41e1af06001770fab8_general_dismounted'
g_str_5fb1ba41e1af06001770fab8_general_mounted='5fb1ba41e1af06001770fab8_general_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_dismounted]={
  id=g_str_5fb1ba41e1af06001770fab8_general_dismounted,
  name='Archers General',
  min=0,
  max=1,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training\nDeployment dismounted from Horse Bow General',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770fab8_general_mounted,
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_mounted]={
  id=g_str_5fb1ba41e1af06001770fab8_general_mounted,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770fab8_general_dismounted,
  general=true,
  deployment_dismounting=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_str_5fb1ba41e1af06001770fab8='5fb1ba41e1af06001770fab8'
g_base_definitions[g_str_5fb1ba41e1af06001770fab8]={
  id=g_str_5fb1ba41e1af06001770fab8,
  name='Horse Bow',
  min=0,
  max=4,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_str_5fb1ba41e1af06001770fab8_dismounted='5fb1ba41e1af06001770fab8_dismounted'
g_str_5fb1ba41e1af06001770fab8_mounted='5fb1ba41e1af06001770fab8_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770fab8_dismounted]={
  id=g_str_5fb1ba41e1af06001770fab8_dismounted,
  name='Archers',
  min=0,
  max=4,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training\nDeployment dismounted from Horse Bow',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770fab8_mounted,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_base_definitions[g_str_5fb1ba41e1af06001770fab8_mounted]={
  id=g_str_5fb1ba41e1af06001770fab8_mounted,
  name='Horse Bow',
  min=0,
  max=4,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770fab8_dismounted,
  deployment_dismounting=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_str_5fb1ba41e1af06001770fab9='5fb1ba41e1af06001770fab9'
g_base_definitions[g_str_5fb1ba41e1af06001770fab9]={
  id=g_str_5fb1ba41e1af06001770fab9,
  name='Bad Horse',
  min=0,
  max=4,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_str_5fb1ba41e1af06001770fab9_dismounted='5fb1ba41e1af06001770fab9_dismounted'
g_str_5fb1ba41e1af06001770fab9_mounted='5fb1ba41e1af06001770fab9_mounted'
g_base_definitions[g_str_5fb1ba41e1af06001770fab9_dismounted]={
  id=g_str_5fb1ba41e1af06001770fab9_dismounted,
  name='Archers',
  min=0,
  max=4,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training\nDeployment dismounted from Bad Horse',
  points=4,
  dismounted_from=g_str_5fb1ba41e1af06001770fab9_mounted,
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_base_definitions[g_str_5fb1ba41e1af06001770fab9_mounted]={
  id=g_str_5fb1ba41e1af06001770fab9_mounted,
  name='Bad Horse',
  min=0,
  max=4,
  description='Mongol horse archers who retained their steppe skills; or Mengkuchun settled Mongol horse archers with inferior mounts and training\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_str_5fb1ba41e1af06001770fab9_dismounted,
  deployment_dismounting=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fab6",
}
g_troop_option['5fb1ba41e1af06001770fabb']= {
  min=1,
  max=3,
  description='Tammachi horse archers',
}
g_str_5fb1ba41e1af06001770fabc_general='5fb1ba41e1af06001770fabc_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general]={
  id=g_str_5fb1ba41e1af06001770fabc_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Tammachi horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fabb",
}
g_str_5fb1ba41e1af06001770fabc='5fb1ba41e1af06001770fabc'
g_base_definitions[g_str_5fb1ba41e1af06001770fabc]={
  id=g_str_5fb1ba41e1af06001770fabc,
  name='Horse Bow',
  min=1,
  max=3,
  description='Tammachi horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fabb",
}
g_troop_option['5fb1ba41e1af06001770fabd']= {
  min=0,
  max=1,
  description='Bolt shooters and counterweight stone-throwers',
  core='all',
}
g_str_5fb1ba41e1af06001770fabe='5fb1ba41e1af06001770fabe'
g_base_definitions[g_str_5fb1ba41e1af06001770fabe]={
  id=g_str_5fb1ba41e1af06001770fabe,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt shooters and counterweight stone-throwers',
  troop_type="Artillery",
  troop_option_id="5fb1ba41e1af06001770fabd",
}
g_str_5fb1b9f3e1af06001770a2e1_camp='5fb1b9f3e1af06001770a2e1_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp]={
  id=g_str_5fb1b9f3e1af06001770a2e1_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train='5fb1b9f3e1af06001770a2e1_camp_pack_train'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train]={
  id=g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba19e1af06001770bba6='5fb1ba19e1af06001770bba6'
g_base_definitions[g_str_5fb1ba19e1af06001770bba6]={
  id=g_str_5fb1ba19e1af06001770bba6,
  name='Raiders',
  min=0,
  max=1,
  description='Swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba19e1af06001770bba5",
}
g_str_5fb1ba19e1af06001770bba8='5fb1ba19e1af06001770bba8'
g_base_definitions[g_str_5fb1ba19e1af06001770bba8]={
  id=g_str_5fb1ba19e1af06001770bba8,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Spearmen and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba19e1af06001770bba7",
}
g_str_5fb1ba19e1af06001770bbaa='5fb1ba19e1af06001770bbaa'
g_base_definitions[g_str_5fb1ba19e1af06001770bbaa]={
  id=g_str_5fb1ba19e1af06001770bbaa,
  name='Archers',
  min=1,
  max=3,
  description='Crossbowmen or bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba19e1af06001770bba9",
}
g_str_5fb1ba19e1af06001770bbac='5fb1ba19e1af06001770bbac'
g_base_definitions[g_str_5fb1ba19e1af06001770bbac]={
  id=g_str_5fb1ba19e1af06001770bbac,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba19e1af06001770bbab",
}
g_str_5fb1ba19e1af06001770bba6='5fb1ba19e1af06001770bba6'
g_base_definitions[g_str_5fb1ba19e1af06001770bba6]={
  id=g_str_5fb1ba19e1af06001770bba6,
  name='Raiders',
  min=0,
  max=1,
  description='Swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba19e1af06001770bba5",
}
g_str_5fb1ba19e1af06001770bba8='5fb1ba19e1af06001770bba8'
g_base_definitions[g_str_5fb1ba19e1af06001770bba8]={
  id=g_str_5fb1ba19e1af06001770bba8,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Spearmen and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba19e1af06001770bba7",
}
g_str_5fb1ba19e1af06001770bbaa='5fb1ba19e1af06001770bbaa'
g_base_definitions[g_str_5fb1ba19e1af06001770bbaa]={
  id=g_str_5fb1ba19e1af06001770bbaa,
  name='Archers',
  min=1,
  max=3,
  description='Crossbowmen or bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba19e1af06001770bba9",
}
g_str_5fb1ba19e1af06001770bbac='5fb1ba19e1af06001770bbac'
g_base_definitions[g_str_5fb1ba19e1af06001770bbac]={
  id=g_str_5fb1ba19e1af06001770bbac,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba19e1af06001770bbab",
}
g_str_5fb1ba19e1af06001770bba6='5fb1ba19e1af06001770bba6'
g_base_definitions[g_str_5fb1ba19e1af06001770bba6]={
  id=g_str_5fb1ba19e1af06001770bba6,
  name='Raiders',
  min=0,
  max=1,
  description='Swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba19e1af06001770bba5",
}
g_str_5fb1ba19e1af06001770bba8='5fb1ba19e1af06001770bba8'
g_base_definitions[g_str_5fb1ba19e1af06001770bba8]={
  id=g_str_5fb1ba19e1af06001770bba8,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Spearmen and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba19e1af06001770bba7",
}
g_str_5fb1ba19e1af06001770bbaa='5fb1ba19e1af06001770bbaa'
g_base_definitions[g_str_5fb1ba19e1af06001770bbaa]={
  id=g_str_5fb1ba19e1af06001770bbaa,
  name='Archers',
  min=1,
  max=3,
  description='Crossbowmen or bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba19e1af06001770bba9",
}
g_str_5fb1ba19e1af06001770bbac='5fb1ba19e1af06001770bbac'
g_base_definitions[g_str_5fb1ba19e1af06001770bbac]={
  id=g_str_5fb1ba19e1af06001770bbac,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba19e1af06001770bbab",
}
g_str_5fb1ba19e1af06001770bba6='5fb1ba19e1af06001770bba6'
g_base_definitions[g_str_5fb1ba19e1af06001770bba6]={
  id=g_str_5fb1ba19e1af06001770bba6,
  name='Raiders',
  min=0,
  max=1,
  description='Swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba19e1af06001770bba5",
}
g_str_5fb1ba19e1af06001770bba8='5fb1ba19e1af06001770bba8'
g_base_definitions[g_str_5fb1ba19e1af06001770bba8]={
  id=g_str_5fb1ba19e1af06001770bba8,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Spearmen and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba19e1af06001770bba7",
}
g_str_5fb1ba19e1af06001770bbaa='5fb1ba19e1af06001770bbaa'
g_base_definitions[g_str_5fb1ba19e1af06001770bbaa]={
  id=g_str_5fb1ba19e1af06001770bbaa,
  name='Archers',
  min=1,
  max=3,
  description='Crossbowmen or bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba19e1af06001770bba9",
}
g_str_5fb1ba19e1af06001770bbac='5fb1ba19e1af06001770bbac'
g_base_definitions[g_str_5fb1ba19e1af06001770bbac]={
  id=g_str_5fb1ba19e1af06001770bbac,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba19e1af06001770bbab",
}
army['5fb1b9f3e1af06001770a2e1']={
  data={
    name='Yuan in the Steppe or Korea  1260 to 1368 AD',
    id='5fb1b9f3e1af06001770a2e1',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2e1"] = army["5fb1b9f3e1af06001770a2e1"]
army['5fb1b9f3e1af06001770a2e1_1260_1274']={
  data={
    name='Yuan in the Steppe or Korea 1260 AD to 1274 AD',
    id='5fb1b9f3e1af06001770a2e1_1260_1274',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
army['5fb1b9f3e1af06001770a2e1_1275_1300']={
  data={
    name='Yuan in the Steppe or Korea 1275 AD to 1300 AD',
    id='5fb1b9f3e1af06001770a2e1_1275_1300',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
army['5fb1b9f3e1af06001770a2e1_1301_1368']={
  data={
    name='Yuan in the Steppe or Korea 1301 AD to 1368 AD',
    id='5fb1b9f3e1af06001770a2e1_1301_1368',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Yuan in the Steppe or Korea  1260 to 1368 AD"] = army["5fb1b9f3e1af06001770a2e1"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Yuan in the Steppe or Korea  1260 to 1368 AD"] = army["5fb1b9f3e1af06001770a2e1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Yuan in the Steppe or Korea  1260 to 1368 AD"] = army["5fb1b9f3e1af06001770a2e1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2e1"] = {}
army_dates["5fb1b9f3e1af06001770a2e1"]["1260 AD to 1368 AD"] ="5fb1b9f3e1af06001770a2e1"
army_dates["5fb1b9f3e1af06001770a2e1"]["1260 AD to 1274 AD"] ="5fb1b9f3e1af06001770a2e1_1260_1274"
army_dates["5fb1b9f3e1af06001770a2e1"]["1275 AD to 1300 AD"] ="5fb1b9f3e1af06001770a2e1_1275_1300"
army_dates["5fb1b9f3e1af06001770a2e1"]["1301 AD to 1368 AD"] ="5fb1b9f3e1af06001770a2e1_1301_1368"
