-- 5fb1b9f5e1af06001770a3cd Teotihuacan Empire  451 to 650 AD

army['5fb1b9f5e1af06001770a3cd']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Teotihuacan Empire  451 to 650 AD',
    id='5fb1b9f5e1af06001770a3cd',
    dateRange={
      startDate=451,
      endDate=650,
    },
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fd6c_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd6c],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd6d_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd6d],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd6f_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd6f],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd71],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd73],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3cd_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3cd"] = army["5fb1b9f5e1af06001770a3cd"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Teotihuacan Empire  451 to 650 AD"] = army["5fb1b9f5e1af06001770a3cd"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Teotihuacan Empire  451 to 650 AD"] = army["5fb1b9f5e1af06001770a3cd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Teotihuacan Empire  451 to 650 AD"] = army["5fb1b9f5e1af06001770a3cd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3cd"] = {}
army_dates["5fb1b9f5e1af06001770a3cd"]["451 AD to 650 AD"] = {
  startDate=451,
  endDate=650
}
army_dates["5fb1b9f5e1af06001770a3cd"]["451 AD to 599 AD"] = {
  startDate=451,
  endDate=599
}
army_dates["5fb1b9f5e1af06001770a3cd"]["600 AD"] = {
  startDate=600,
  endDate=600
}
army_dates["5fb1b9f5e1af06001770a3cd"]["601 AD to 650 AD"] = {
  startDate=601,
  endDate=650
}
