-- 5fb1b9dae1af060017709418 Phrygian  850 to 676 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba22e1af06001770c2c6_general='5fb1ba22e1af06001770c2c6_general'
g_base_definitions[g_str_5fb1ba22e1af06001770c2c6_general]={
  id=g_str_5fb1ba22e1af06001770c2c6_general,
  name='Battle Taxi General',
  min=1,
  max=1,
  description='2- or 4-horse battle platforms with javelin-armed crewmen',
  general=true,
  troop_type="Battle Taxi",
}
g_str_5fb1ba22e1af06001770c2c6='5fb1ba22e1af06001770c2c6'
g_base_definitions[g_str_5fb1ba22e1af06001770c2c6]={
  id=g_str_5fb1ba22e1af06001770c2c6,
  name='Battle Taxi',
  min=1,
  max=2,
  description='2- or 4-horse battle platforms with javelin-armed crewmen',
  troop_type="Battle Taxi",
}
g_str_5fb1ba22e1af06001770c2c8='5fb1ba22e1af06001770c2c8'
g_base_definitions[g_str_5fb1ba22e1af06001770c2c8]={
  id=g_str_5fb1ba22e1af06001770c2c8,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba22e1af06001770c2ca='5fb1ba22e1af06001770c2ca'
g_base_definitions[g_str_5fb1ba22e1af06001770c2ca]={
  id=g_str_5fb1ba22e1af06001770c2ca,
  name='Light Foot',
  min=7,
  max=14,
  description='Spearmen',
  troop_type="Light Foot",
}
g_str_5fb1ba22e1af06001770c2cc='5fb1ba22e1af06001770c2cc'
g_base_definitions[g_str_5fb1ba22e1af06001770c2cc]={
  id=g_str_5fb1ba22e1af06001770c2cc,
  name='Skirmishers',
  min=1,
  max=5,
  description='Skirmishing bowmen and slingers',
  troop_type="Skirmishers",
}
g_str_5fb1ba22e1af06001770c2ce='5fb1ba22e1af06001770c2ce'
g_base_definitions[g_str_5fb1ba22e1af06001770c2ce]={
  id=g_str_5fb1ba22e1af06001770c2ce,
  name='Light Foot',
  min=0,
  max=3,
  description='Javelinmen, some with shields',
  troop_type="Light Foot",
}
g_str_5fb1ba22e1af06001770c2cf='5fb1ba22e1af06001770c2cf'
g_base_definitions[g_str_5fb1ba22e1af06001770c2cf]={
  id=g_str_5fb1ba22e1af06001770c2cf,
  name='Rabble',
  min=0,
  max=3,
  description='Javelinmen, some with shields',
  troop_type="Rabble",
}
g_str_5fb1b9dae1af060017709418_camp='5fb1b9dae1af060017709418_camp'
g_base_definitions[g_str_5fb1b9dae1af060017709418_camp]={
  id=g_str_5fb1b9dae1af060017709418_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dae1af060017709418_camp_pack_train='5fb1b9dae1af060017709418_camp_pack_train'
g_base_definitions[g_str_5fb1b9dae1af060017709418_camp_pack_train]={
  id=g_str_5fb1b9dae1af060017709418_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dae1af060017709418']={
  data={
    name='Phrygian  850 to 676 BC'
  },
  g_base_definitions[g_str_5fb1ba22e1af06001770c2c6_general],
  g_base_definitions[g_str_5fb1ba22e1af06001770c2c6],
  g_base_definitions[g_str_5fb1ba22e1af06001770c2c8],
  g_base_definitions[g_str_5fb1ba22e1af06001770c2ca],
  g_base_definitions[g_str_5fb1ba22e1af06001770c2cc],
  g_base_definitions[g_str_5fb1ba22e1af06001770c2ce],
  g_base_definitions[g_str_5fb1ba22e1af06001770c2cf],
  g_base_definitions[g_str_5fb1b9dae1af060017709418_camp],
  g_base_definitions[g_str_5fb1b9dae1af060017709418_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af060017709418"] = army["5fb1b9dae1af060017709418"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Phrygian  850 to 676 BC"] = army["5fb1b9dae1af060017709418"]
