-- 5fb1b9d9e1af060017709327 Bronze Age Zagros and Anatolian Highlanders  3000 to 950 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba1fe1af06001770bf51_general='5fb1ba1fe1af06001770bf51_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf51_general]={
  id=g_str_5fb1ba1fe1af06001770bf51_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Bodyguards',
  general=true,
  troop_type="Raiders",
}
g_str_5fb1ba1fe1af06001770bf51='5fb1ba1fe1af06001770bf51'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf51]={
  id=g_str_5fb1ba1fe1af06001770bf51,
  name='Raiders',
  min=1,
  max=2,
  description='Bodyguards',
  troop_type="Raiders",
}
g_str_5fb1ba1fe1af06001770bf52_general='5fb1ba1fe1af06001770bf52_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf52_general]={
  id=g_str_5fb1ba1fe1af06001770bf52_general,
  name='Archers General',
  min=1,
  max=1,
  description='Bodyguards',
  general=true,
  troop_type="Archers",
}
g_str_5fb1ba1fe1af06001770bf52='5fb1ba1fe1af06001770bf52'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf52]={
  id=g_str_5fb1ba1fe1af06001770bf52,
  name='Archers',
  min=1,
  max=2,
  description='Bodyguards',
  troop_type="Archers",
}
g_str_5fb1ba1fe1af06001770bf54='5fb1ba1fe1af06001770bf54'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf54]={
  id=g_str_5fb1ba1fe1af06001770bf54,
  name='Rabble',
  min=8,
  max=20,
  description='Unshielded javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba1fe1af06001770bf57='5fb1ba1fe1af06001770bf57'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf57]={
  id=g_str_5fb1ba1fe1af06001770bf57,
  name='Light Foot',
  min=0,
  max=3,
  description='Javelinmen with shields',
  troop_type="Light Foot",
}
g_str_5fb1ba1fe1af06001770bf59='5fb1ba1fe1af06001770bf59'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf59]={
  id=g_str_5fb1ba1fe1af06001770bf59,
  name='Bow Levy',
  min=4,
  max=12,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba1fe1af06001770bf5b='5fb1ba1fe1af06001770bf5b'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf5b]={
  id=g_str_5fb1ba1fe1af06001770bf5b,
  name='Skirmishers',
  min=0,
  max=2,
  description='Slingers',
  troop_type="Skirmishers",
}
g_str_5fb1b9d9e1af060017709327_camp='5fb1b9d9e1af060017709327_camp'
g_base_definitions[g_str_5fb1b9d9e1af060017709327_camp]={
  id=g_str_5fb1b9d9e1af060017709327_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d9e1af060017709327_camp_pack_train='5fb1b9d9e1af060017709327_camp_pack_train'
g_base_definitions[g_str_5fb1b9d9e1af060017709327_camp_pack_train]={
  id=g_str_5fb1b9d9e1af060017709327_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9d9e1af060017709327']={
  data={
    name='Bronze Age Zagros and Anatolian Highlanders  3000 to 950 BC'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf51_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf51],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf52_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf52],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf54],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf57],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf59],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf5b],
  g_base_definitions[g_str_5fb1b9d9e1af060017709327_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709327_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709327"] = army["5fb1b9d9e1af060017709327"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Bronze Age Zagros and Anatolian Highlanders  3000 to 950 BC"] = army["5fb1b9d9e1af060017709327"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Bronze Age Zagros and Anatolian Highlanders  3000 to 950 BC"] = army["5fb1b9d9e1af060017709327"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Bronze Age Zagros and Anatolian Highlanders  3000 to 950 BC"] = army["5fb1b9d9e1af060017709327"]
