-- 5fb1b9d9e1af06001770935f Later Amorite  1894 to 1595 BC

army['5fb1b9d9e1af06001770935f']={
  data={
    invasionRatings={
      3,
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Amorite  1894 to 1595 BC',
    id='5fb1b9d9e1af06001770935f',
    dateRange={
      startDate=-1894,
      endDate=-1595,
    }
  },
  g_base_definitions[g_str_5fb1ba20e1af06001770bff0_general],
  g_base_definitions[g_str_5fb1ba20e1af06001770bff0],
  g_base_definitions[g_str_5fb1ba20e1af06001770bff1_general],
  g_base_definitions[g_str_5fb1ba20e1af06001770bff1],
  g_base_definitions[g_str_5fb1ba20e1af06001770bff3],
  g_base_definitions[g_str_5fb1ba20e1af06001770bff5],
  g_base_definitions[g_str_5fb1ba20e1af06001770bff6],
  g_base_definitions[g_str_5fb1ba20e1af06001770bff8],
  g_base_definitions[g_str_5fb1ba20e1af06001770bffa],
  g_base_definitions[g_str_5fb1ba20e1af06001770bffc],
  g_base_definitions[g_str_5fb1ba20e1af06001770bffe],
  g_base_definitions[g_str_5fb1b9d9e1af06001770935f_camp],
  g_base_definitions[g_str_5fb1b9d9e1af06001770935f_camp_fortified],
  g_base_definitions[g_str_5fb1b9d9e1af06001770935f_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af06001770935f"] = army["5fb1b9d9e1af06001770935f"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Later Amorite  1894 to 1595 BC"] = army["5fb1b9d9e1af06001770935f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Amorite  1894 to 1595 BC"] = army["5fb1b9d9e1af06001770935f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af06001770935f"] = {}
army_dates["5fb1b9d9e1af06001770935f"]["1894 BC to 1595 BC"] = {
  startDate=-1894,
  endDate=-1595
}
