-- 5fb1b9eee1af060017709fe4 Genoese Condotta in Cyprus  1373 to 1464 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3be1af06001770ef97_general='5fb1ba3be1af06001770ef97_general'
g_base_definitions[g_str_5fb1ba3be1af06001770ef97_general]={
  id=g_str_5fb1ba3be1af06001770ef97_general,
  name='Knights General',
  min=0,
  max=1,
  description='Condottieri',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba3be1af06001770ef97_general_dismounted='5fb1ba3be1af06001770ef97_general_dismounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef97_general_dismounted]={
  id=g_str_5fb1ba3be1af06001770ef97_general_dismounted,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Condottieri\nDeployment dismounted from Knights General',
  points=4,
  general=true,
  troop_type="Elite Foot",
}
g_5fb1ba3be1af06001770ef97_general_dismounted=g_base_definitions[g_str_5fb1ba3be1af06001770ef97_general_dismounted]
g_str_5fb1ba3be1af06001770ef97_general_mounted='5fb1ba3be1af06001770ef97_general_mounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef97_general_mounted]={
  id=g_str_5fb1ba3be1af06001770ef97_general_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='Condottieri\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba3be1af06001770ef97_general_dismounted,
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba3be1af06001770ef97='5fb1ba3be1af06001770ef97'
g_base_definitions[g_str_5fb1ba3be1af06001770ef97]={
  id=g_str_5fb1ba3be1af06001770ef97,
  name='Knights',
  min=0,
  max=1,
  description='Condottieri',
  troop_type="Knights",
}
g_str_5fb1ba3be1af06001770ef97_dismounted='5fb1ba3be1af06001770ef97_dismounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef97_dismounted]={
  id=g_str_5fb1ba3be1af06001770ef97_dismounted,
  name='Elite Foot',
  min=0,
  max=1,
  description='Condottieri\nDeployment dismounted from Knights',
  points=4,
  troop_type="Elite Foot",
}
g_5fb1ba3be1af06001770ef97_dismounted=g_base_definitions[g_str_5fb1ba3be1af06001770ef97_dismounted]
g_str_5fb1ba3be1af06001770ef97_mounted='5fb1ba3be1af06001770ef97_mounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef97_mounted]={
  id=g_str_5fb1ba3be1af06001770ef97_mounted,
  name='Knights',
  min=0,
  max=1,
  description='Condottieri\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba3be1af06001770ef97_dismounted,
  troop_type="Knights",
}
g_str_5fb1ba3be1af06001770ef9a='5fb1ba3be1af06001770ef9a'
g_base_definitions[g_str_5fb1ba3be1af06001770ef9a]={
  id=g_str_5fb1ba3be1af06001770ef9a,
  name='Bad Horse',
  min=0,
  max=1,
  description='Crossbowmen on horses',
  troop_type="Bad Horse",
}
g_str_5fb1ba3be1af06001770ef9c='5fb1ba3be1af06001770ef9c'
g_base_definitions[g_str_5fb1ba3be1af06001770ef9c]={
  id=g_str_5fb1ba3be1af06001770ef9c,
  name='Bow Levy',
  min=0,
  max=2,
  description='Militia or native crossbowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba3be1af06001770ef9e='5fb1ba3be1af06001770ef9e'
g_base_definitions[g_str_5fb1ba3be1af06001770ef9e]={
  id=g_str_5fb1ba3be1af06001770ef9e,
  name='Archers',
  min=2,
  max=4,
  description='Mercenary crossbowmen',
  troop_type="Archers",
}
g_str_5fb1ba3be1af06001770ef9f='5fb1ba3be1af06001770ef9f'
g_base_definitions[g_str_5fb1ba3be1af06001770ef9f]={
  id=g_str_5fb1ba3be1af06001770ef9f,
  name='Pavisiers',
  min=2,
  max=4,
  description='Mercenary crossbowmen',
  troop_type="Pavisiers",
}
g_str_5fb1ba3be1af06001770efa1='5fb1ba3be1af06001770efa1'
g_base_definitions[g_str_5fb1ba3be1af06001770efa1]={
  id=g_str_5fb1ba3be1af06001770efa1,
  name='Light Foot',
  min=0,
  max=1,
  description='Mercenary javelinmen or swordsmen',
  troop_type="Light Foot",
}
g_str_5fb1ba3be1af06001770efa2='5fb1ba3be1af06001770efa2'
g_base_definitions[g_str_5fb1ba3be1af06001770efa2]={
  id=g_str_5fb1ba3be1af06001770efa2,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Mercenary javelinmen or swordsmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba3be1af06001770efa4='5fb1ba3be1af06001770efa4'
g_base_definitions[g_str_5fb1ba3be1af06001770efa4]={
  id=g_str_5fb1ba3be1af06001770efa4,
  name='Horde',
  min=0,
  max=2,
  description='Unenthusiastic Cypriot peasants',
  troop_type="Horde",
}
g_str_5fb1ba3be1af06001770efa6='5fb1ba3be1af06001770efa6'
g_base_definitions[g_str_5fb1ba3be1af06001770efa6]={
  id=g_str_5fb1ba3be1af06001770efa6,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards and other guns',
  troop_type="Artillery",
}
g_str_5fb1ba3be1af06001770efa9='5fb1ba3be1af06001770efa9'
g_base_definitions[g_str_5fb1ba3be1af06001770efa9]={
  id=g_str_5fb1ba3be1af06001770efa9,
  name='Horse Bow',
  min=0,
  max=3,
  description='Bulgarian horsemen',
  troop_type="Horse Bow",
}
g_str_5fb1ba3be1af06001770efab='5fb1ba3be1af06001770efab'
g_base_definitions[g_str_5fb1ba3be1af06001770efab]={
  id=g_str_5fb1ba3be1af06001770efab,
  name='Light Foot',
  min=1,
  max=2,
  description='Galley crewmen',
  troop_type="Light Foot",
}
g_str_5fb1ba3be1af06001770efae='5fb1ba3be1af06001770efae'
g_base_definitions[g_str_5fb1ba3be1af06001770efae]={
  id=g_str_5fb1ba3be1af06001770efae,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing handgunners',
  troop_type="Skirmishers",
}
g_str_5fb1ba3be1af06001770efb1='5fb1ba3be1af06001770efb1'
g_base_definitions[g_str_5fb1ba3be1af06001770efb1]={
  id=g_str_5fb1ba3be1af06001770efb1,
  name='Raiders',
  min=0,
  max=1,
  description='Sword-and-buckler men',
  troop_type="Raiders",
}
g_str_5fb1b9eee1af060017709fe4_camp='5fb1b9eee1af060017709fe4_camp'
g_base_definitions[g_str_5fb1b9eee1af060017709fe4_camp]={
  name='Camp',
  id=g_str_5fb1b9eee1af060017709fe4_camp,
  min=1,
  max=1,
}
army['5fb1b9eee1af060017709fe4']={
  data={
    name='Genoese Condotta in Cyprus  1373 to 1464 AD'
  },
  g_base_definitions[g_str_5fb1b9eee1af060017709fe4_camp],
  g_base_definitions[g_str_5fb1ba3be1af06001770efb3],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef97_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef97_general_mounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef97_general_dismounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef97],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef97_mounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef97_dismounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef9a],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef9c],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef9e],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef9f],
  g_base_definitions[g_str_5fb1ba3be1af06001770efa1],
  g_base_definitions[g_str_5fb1ba3be1af06001770efa2],
  g_base_definitions[g_str_5fb1ba3be1af06001770efa4],
  g_base_definitions[g_str_5fb1ba3be1af06001770efa6],
  g_base_definitions[g_str_5fb1ba3be1af06001770efa9],
  g_base_definitions[g_str_5fb1ba3be1af06001770efab],
  g_base_definitions[g_str_5fb1ba3be1af06001770efae],
  g_base_definitions[g_str_5fb1ba3be1af06001770efb1],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af060017709fe4"] = army["5fb1b9eee1af060017709fe4"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Genoese Condotta in Cyprus  1373 to 1464 AD"] = army["5fb1b9eee1af060017709fe4"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Genoese Condotta in Cyprus  1373 to 1464 AD"] = army["5fb1b9eee1af060017709fe4"]
