-- 5fb1b9f3e1af06001770a2da Later Jurchen Jin  1200 to 1234 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba41e1af06001770fa88_general='5fb1ba41e1af06001770fa88_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fa88_general]={
  id=g_str_5fb1ba41e1af06001770fa88_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Jurchen horsemen (possibly still effective)',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770fa87",
}
g_str_5fb1ba41e1af06001770fa88='5fb1ba41e1af06001770fa88'
g_base_definitions[g_str_5fb1ba41e1af06001770fa88]={
  id=g_str_5fb1ba41e1af06001770fa88,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Jurchen horsemen (possibly still effective)',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770fa87",
}
g_str_5fb1ba41e1af06001770fa89_general='5fb1ba41e1af06001770fa89_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fa89_general]={
  id=g_str_5fb1ba41e1af06001770fa89_general,
  name='Bad Horse General',
  min=1,
  max=1,
  description='Jurchen horsemen (possibly still effective)',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa87",
}
g_str_5fb1ba41e1af06001770fa89='5fb1ba41e1af06001770fa89'
g_base_definitions[g_str_5fb1ba41e1af06001770fa89]={
  id=g_str_5fb1ba41e1af06001770fa89,
  name='Bad Horse',
  min=1,
  max=2,
  description='Jurchen horsemen (possibly still effective)',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa87",
}
g_str_5fb1ba41e1af06001770fa8b_general='5fb1ba41e1af06001770fa8b_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fa8b_general]={
  id=g_str_5fb1ba41e1af06001770fa8b_general,
  name='Bad Horse General',
  min=1,
  max=1,
  description='Jurchen horsemen with poor training and support',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa8a",
}
g_str_5fb1ba41e1af06001770fa8b='5fb1ba41e1af06001770fa8b'
g_base_definitions[g_str_5fb1ba41e1af06001770fa8b]={
  id=g_str_5fb1ba41e1af06001770fa8b,
  name='Bad Horse',
  min=1,
  max=4,
  description='Jurchen horsemen with poor training and support',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa8a",
}
g_str_5fb1ba41e1af06001770fa8d='5fb1ba41e1af06001770fa8d'
g_base_definitions[g_str_5fb1ba41e1af06001770fa8d]={
  id=g_str_5fb1ba41e1af06001770fa8d,
  name='Horse Bow',
  min=0,
  max=1,
  description='Jurchen scout horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fa8c",
}
g_str_5fb1ba41e1af06001770fa8f_general='5fb1ba41e1af06001770fa8f_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fa8f_general]={
  id=g_str_5fb1ba41e1af06001770fa8f_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Khitan heavy horsemen',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa8e",
}
g_str_5fb1ba41e1af06001770fa8f='5fb1ba41e1af06001770fa8f'
g_base_definitions[g_str_5fb1ba41e1af06001770fa8f]={
  id=g_str_5fb1ba41e1af06001770fa8f,
  name='Bad Horse',
  min=0,
  max=3,
  description='Khitan heavy horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fa8e",
}
g_str_5fb1ba41e1af06001770fa91='5fb1ba41e1af06001770fa91'
g_base_definitions[g_str_5fb1ba41e1af06001770fa91]={
  id=g_str_5fb1ba41e1af06001770fa91,
  name='War Wagons',
  min=0,
  max=1,
  description='War wagons',
  troop_type="War Wagons",
  troop_option_id="5fb1ba41e1af06001770fa90",
}
g_str_5fb1ba41e1af06001770fa94='5fb1ba41e1af06001770fa94'
g_base_definitions[g_str_5fb1ba41e1af06001770fa94]={
  id=g_str_5fb1ba41e1af06001770fa94,
  name='Horse Bow',
  min=0,
  max=1,
  description='Uighur, Tangut, and other mercenary horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fa92",
}
g_str_5fb1ba41e1af06001770fa97='5fb1ba41e1af06001770fa97'
g_base_definitions[g_str_5fb1ba41e1af06001770fa97]={
  id=g_str_5fb1ba41e1af06001770fa97,
  name='Archers',
  min=0,
  max=1,
  description='Volunteer crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770fa95",
}
g_str_5fb1ba41e1af06001770fa9a='5fb1ba41e1af06001770fa9a'
g_base_definitions[g_str_5fb1ba41e1af06001770fa9a]={
  id=g_str_5fb1ba41e1af06001770fa9a,
  name='Raiders',
  min=0,
  max=1,
  description='Volunteer spearmen or swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba41e1af06001770fa98",
}
g_str_5fb1b9f3e1af06001770a2da_camp='5fb1b9f3e1af06001770a2da_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp]={
  id=g_str_5fb1b9f3e1af06001770a2da_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f3e1af06001770a2da_camp_pack_train='5fb1b9f3e1af06001770a2da_camp_pack_train'
g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp_pack_train]={
  id=g_str_5fb1b9f3e1af06001770a2da_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9f3e1af06001770a2da']={
  data={
    name='Later Jurchen Jin  1200 to 1234 AD',
    id='5fb1b9f3e1af06001770a2da'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770fa88_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa88],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa89_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa89],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8b_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8b],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8d],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8f_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8f],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa91],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa94],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa97],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa9a],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2da"] = army["5fb1b9f3e1af06001770a2da"]
army['5fb1b9f3e1af06001770a2da_1200_1220']={
  data={
    name='Later Jurchen Jin 1200 AD to 1220 AD',
    id='5fb1b9f3e1af06001770a2da_1200_1220'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770fa88_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa88],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa89_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa89],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8b_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8b],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8d],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8f_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8f],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa91],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp_pack_train],
}
army['5fb1b9f3e1af06001770a2da_1221_1234']={
  data={
    name='Later Jurchen Jin 1221 AD to 1234 AD',
    id='5fb1b9f3e1af06001770a2da_1221_1234'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770fa88_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa88],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa89_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa89],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8b_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8b],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8d],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8f_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa8f],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa91],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa94],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa97],
  g_base_definitions[g_str_5fb1ba41e1af06001770fa9a],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2da_camp_pack_train],
}
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Later Jurchen Jin  1200 to 1234 AD"] = army["5fb1b9f3e1af06001770a2da"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Jurchen Jin  1200 to 1234 AD"] = army["5fb1b9f3e1af06001770a2da"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2da"] = {}
army_dates["5fb1b9f3e1af06001770a2da"]["1200 AD to 1234 AD"] ="5fb1b9f3e1af06001770a2da"
army_dates["5fb1b9f3e1af06001770a2da"]["1200 AD to 1220 AD"] ="5fb1b9f3e1af06001770a2da_1200_1220"
army_dates["5fb1b9f3e1af06001770a2da"]["1221 AD to 1234 AD"] ="5fb1b9f3e1af06001770a2da_1221_1234"
