troop_options['5fb1ba37e1af06001770e798'] = {
  min=0,
  max=2,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e79a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e79d'] = {
  min=1,
  max=2,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e79f'] = {
  min=2,
  max=3,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e7a1'] = {
  min=1,
  max=5,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e7a3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e7a6'] = {
  min=0,
  max=2,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e7a8'] = {
  min=0,
  max=1,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
troop_options['5fb1ba37e1af06001770e7aa'] = {
  min=0,
  max=4,
  dateRange={
    startDate=896,
    endDate=965,
  }
}
-- allies
