-- 5fb1b9f4e1af06001770a371 Sengoku Samurai  1465 to 1542 AD

army['5fb1b9f4e1af06001770a371']={
  data={
    name='Sengoku Samurai  1465 to 1542 AD',
    id='5fb1b9f4e1af06001770a371',
    army_id='5fb1b9f4e1af06001770a371'
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fcca_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcca],
  g_base_definitions[g_str_5fb1ba43e1af06001770fccc_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fccc],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcce],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcd0],
  g_base_definitions[g_str_5fb1ba43e1af06001770fcd2],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a371_camp],
  g_base_definitions[g_str_5fb1ba19e1af06001770bc6a],
  g_base_definitions[g_str_5fb1ba19e1af06001770bc6d],
  g_base_definitions[g_str_5fb1ba19e1af06001770bc70],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a371"] = army["5fb1b9f4e1af06001770a371"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Sengoku Samurai  1465 to 1542 AD"] = army["5fb1b9f4e1af06001770a371"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sengoku Samurai  1465 to 1542 AD"] = army["5fb1b9f4e1af06001770a371"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a371"] = {}
army_dates["5fb1b9f4e1af06001770a371"]["1465 AD to 1542 AD"] ="5fb1b9f4e1af06001770a371"
