-- 5fb1b9dfe1af06001770976e Later Pre-Islamic Arab Yemen  312 BC to 633 AD

army['5fb1b9dfe1af06001770976e']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Dry',
    },
    name='Later Pre-Islamic Arab Yemen  312 BC to 633 AD',
    id='5fb1b9dfe1af06001770976e',
    dateRange={
      startDate=-312,
      endDate=633,
    },
  },
  g_base_definitions[g_str_615351a503385c0016b86066_general],
  g_base_definitions[g_str_615351a503385c0016b86066],
  g_base_definitions[g_str_615351a503385c0016b86068],
  g_base_definitions[g_str_615351a503385c0016b86068_light_camelry],
  g_base_definitions[g_str_615351a503385c0016b8606b],
  g_base_definitions[g_str_615351a503385c0016b8606d],
  g_base_definitions[g_str_615351a503385c0016b8606e],
  g_base_definitions[g_str_615351a503385c0016b86070],
  g_base_definitions[g_str_615351a503385c0016b86072],
  g_base_definitions[g_str_5fb1b9dfe1af06001770976e_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770976e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770976e"] = army["5fb1b9dfe1af06001770976e"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Pre-Islamic Arab Yemen  312 BC to 633 AD"] = army["5fb1b9dfe1af06001770976e"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Later Pre-Islamic Arab Yemen  312 BC to 633 AD"] = army["5fb1b9dfe1af06001770976e"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Pre-Islamic Arab Yemen  312 BC to 633 AD"] = army["5fb1b9dfe1af06001770976e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Pre-Islamic Arab Yemen  312 BC to 633 AD"] = army["5fb1b9dfe1af06001770976e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af06001770976e"] = {}
army_dates["5fb1b9dfe1af06001770976e"]["312 BC to 633 AD"] = {
  startDate=-312,
  endDate=633
}
