g_str_5fb1ba37e1af06001770e766_general='5fb1ba37e1af06001770e766_general'
g_base_definitions[g_str_5fb1ba37e1af06001770e766_general]={
  id=g_str_5fb1ba37e1af06001770e766_general,
  name='Elite Cavalry General',
  min=1,
  max=1,
  description='Dvor',
  general=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba37e1af06001770e765",
}
g_str_5fb1ba37e1af06001770e766='5fb1ba37e1af06001770e766'
g_base_definitions[g_str_5fb1ba37e1af06001770e766]={
  id=g_str_5fb1ba37e1af06001770e766,
  name='Elite Cavalry',
  min=1,
  max=2,
  description='Dvor',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba37e1af06001770e765",
}
g_str_5fb1ba37e1af06001770e768='5fb1ba37e1af06001770e768'
g_base_definitions[g_str_5fb1ba37e1af06001770e768]={
  id=g_str_5fb1ba37e1af06001770e768,
  name='Horse Bow',
  min=4,
  max=8,
  description='Lesser boyars and their retainers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba37e1af06001770e767",
}
g_str_5fb1ba37e1af06001770e76a='5fb1ba37e1af06001770e76a'
g_base_definitions[g_str_5fb1ba37e1af06001770e76a]={
  id=g_str_5fb1ba37e1af06001770e76a,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Militia spearmen armed with boar spears and axes',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba37e1af06001770e769",
}
g_str_5fb1ba37e1af06001770e76c='5fb1ba37e1af06001770e76c'
g_base_definitions[g_str_5fb1ba37e1af06001770e76c]={
  id=g_str_5fb1ba37e1af06001770e76c,
  name='Bow Levy',
  min=0,
  max=1,
  description='Militia bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba37e1af06001770e76b",
}
g_str_5fb1ba37e1af06001770e76e='5fb1ba37e1af06001770e76e'
g_base_definitions[g_str_5fb1ba37e1af06001770e76e]={
  id=g_str_5fb1ba37e1af06001770e76e,
  name='War Wagons',
  min=0,
  max=2,
  description='Gulay gorod',
  troop_type="War Wagons",
  troop_option_id="5fb1ba37e1af06001770e76d",
}
g_str_5fb1ba37e1af06001770e771='5fb1ba37e1af06001770e771'
g_base_definitions[g_str_5fb1ba37e1af06001770e771]={
  id=g_str_5fb1ba37e1af06001770e771,
  name='Horse Bow',
  min=0,
  max=2,
  description='Tartar horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba37e1af06001770e76f",
}
g_str_5fb1ba37e1af06001770e774='5fb1ba37e1af06001770e774'
g_base_definitions[g_str_5fb1ba37e1af06001770e774]={
  id=g_str_5fb1ba37e1af06001770e774,
  name='Skirmishers',
  min=0,
  max=1,
  description='Cossack skirmishing foot',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba37e1af06001770e772",
}
g_str_5fb1b9eae1af060017709df3_camp='5fb1b9eae1af060017709df3_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709df3_camp]={
  id=g_str_5fb1b9eae1af060017709df3_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9eae1af060017709df3_prepared_defenses='5fb1b9eae1af060017709df3_prepared_defenses'
g_base_definitions[g_str_5fb1b9eae1af060017709df3_prepared_defenses]={
  id=g_str_5fb1b9eae1af060017709df3_prepared_defenses,
  name='Prepared Defenses',
  min=0,
  max=16,
  description='Gulay gorod -- wagons and fixed wall sections between them',
  prepared_defenses=true,
  troop_type="Prepared Defenses",
}
