troop_options['615351aa03385c0016b86bfe'] = {
  min=1,
  max=3,
  dateRange={
    startDate=842,
    endDate=1300,
  }
}
troop_options['615351aa03385c0016b86c01'] = {
  min=0,
  max=3,
  dateRange={
    startDate=842,
    endDate=1300,
  }
}
troop_options['615351aa03385c0016b86c04'] = {
  min=8,
  max=16,
  dateRange={
    startDate=842,
    endDate=1300,
  }
}
troop_options['615351aa03385c0016b86c06'] = {
  min=0,
  max=1,
  dateRange={
    startDate=842,
    endDate=1300,
  }
}
troop_options['615351aa03385c0016b86c08'] = {
  min=0,
  max=7,
  dateRange={
    startDate=842,
    endDate=1300,
  }
}
troop_options['615351aa03385c0016b86c0a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=842,
    endDate=1300,
  }
}
troop_options['615351aa03385c0016b86c0c'] = {
  min=0,
  max=3,
  dateRange={
    startDate=842,
    endDate=1300,
  }
}
-- allies
