-- 5fb1b9f1e1af06001770a19f Later Warring States Chinese: Zhao or Chu  307 to 202 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3fe1af06001770f601='5fb1ba3fe1af06001770f601'
g_base_definitions[g_str_5fb1ba3fe1af06001770f601]={
  id=g_str_5fb1ba3fe1af06001770f601,
  name='Chariots',
  min=1,
  max=2,
  description='4-horse chariots',
}
g_str_5fb1ba3fe1af06001770f603='5fb1ba3fe1af06001770f603'
g_base_definitions[g_str_5fb1ba3fe1af06001770f603]={
  id=g_str_5fb1ba3fe1af06001770f603,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Heavy horsemen armed with spears and crossbows',
}
g_str_5fb1ba3fe1af06001770f607='5fb1ba3fe1af06001770f607'
g_base_definitions[g_str_5fb1ba3fe1af06001770f607]={
  id=g_str_5fb1ba3fe1af06001770f607,
  name='Horse Bow',
  min=1,
  max=4,
  description='Light horse archers',
}
g_str_5fb1ba3fe1af06001770f60a='5fb1ba3fe1af06001770f60a'
g_base_definitions[g_str_5fb1ba3fe1af06001770f60a]={
  id=g_str_5fb1ba3fe1af06001770f60a,
  name='Horse Bow',
  min=0,
  max=1,
  description='Light horse archers',
}
g_str_5fb1ba3fe1af06001770f60c='5fb1ba3fe1af06001770f60c'
g_base_definitions[g_str_5fb1ba3fe1af06001770f60c]={
  id=g_str_5fb1ba3fe1af06001770f60c,
  name='Archers',
  min=1,
  max=4,
  description='Elite crossbowmen',
}
g_str_5fb1ba3fe1af06001770f60e='5fb1ba3fe1af06001770f60e'
g_base_definitions[g_str_5fb1ba3fe1af06001770f60e]={
  id=g_str_5fb1ba3fe1af06001770f60e,
  name='Elite Foot',
  min=1,
  max=4,
  description='Elite dagger-axe or halberdmen',
}
g_str_5fb1ba3fe1af06001770f611='5fb1ba3fe1af06001770f611'
g_base_definitions[g_str_5fb1ba3fe1af06001770f611]={
  id=g_str_5fb1ba3fe1af06001770f611,
  name='Bow Levy',
  min=2,
  max=4,
  description='Conscript crossbowmen',
}
g_str_5fb1ba3fe1af06001770f613='5fb1ba3fe1af06001770f613'
g_base_definitions[g_str_5fb1ba3fe1af06001770f613]={
  id=g_str_5fb1ba3fe1af06001770f613,
  name='Heavy Foot',
  min=2,
  max=4,
  description='Conscript dagger-axe or halberdmen',
}
g_str_5fb1ba3fe1af06001770f615='5fb1ba3fe1af06001770f615'
g_base_definitions[g_str_5fb1ba3fe1af06001770f615]={
  id=g_str_5fb1ba3fe1af06001770f615,
  name='Pavisiers',
  min=0,
  max=6,
  description='Mixed formations of crossbowmen behind lines of dagger-axe men',
}
g_str_5fb1ba3fe1af06001770f618='5fb1ba3fe1af06001770f618'
g_base_definitions[g_str_5fb1ba3fe1af06001770f618]={
  id=g_str_5fb1ba3fe1af06001770f618,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen or crossbowmen',
}
g_str_5fb1ba3fe1af06001770f61a='5fb1ba3fe1af06001770f61a'
g_base_definitions[g_str_5fb1ba3fe1af06001770f61a]={
  id=g_str_5fb1ba3fe1af06001770f61a,
  name='Warband',
  min=0,
  max=2,
  description='Southern fierce tribesmen',
}
g_str_5fb1ba3fe1af06001770f61c='5fb1ba3fe1af06001770f61c'
g_base_definitions[g_str_5fb1ba3fe1af06001770f61c]={
  name='Chariots General',
  id=g_str_5fb1ba3fe1af06001770f61c,
  min=1,
  max=1,
}
g_str_5fb1ba3fe1af06001770f61d='5fb1ba3fe1af06001770f61d'
g_base_definitions[g_str_5fb1ba3fe1af06001770f61d]={
  name='Javelin Cavalry General',
  id=g_str_5fb1ba3fe1af06001770f61d,
  min=1,
  max=1,
}
g_str_5fb1b9f1e1af06001770a19f_camp='5fb1b9f1e1af06001770a19f_camp'
g_base_definitions[g_str_5fb1b9f1e1af06001770a19f_camp]={
  name='Camp',
  id=g_str_5fb1b9f1e1af06001770a19f_camp,
  min=1,
  max=1,
}
army['5fb1b9f1e1af06001770a19f']={
  data={
    name='Later Warring States Chinese: Zhao or Chu  307 to 202 BC'
  },
  g_base_definitions[g_str_5fb1b9f1e1af06001770a19f_camp],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f61c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f61d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f601],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f603],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f607],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f60a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f60c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f60e],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f611],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f613],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f615],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f618],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f61a],
}
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Later Warring States Chinese: Zhao or Chu  307 to 202 BC"] = army["5fb1b9f1e1af06001770a19f"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Later Warring States Chinese: Zhao or Chu  307 to 202 BC"] = army["5fb1b9f1e1af06001770a19f"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Later Warring States Chinese: Zhao or Chu  307 to 202 BC"] = army["5fb1b9f1e1af06001770a19f"]
