troop_options['5fb1ba25e1af06001770c5e2'] = {
  min=6,
  max=16,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5e4'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5e6'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5e8'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-541,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5eb'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-510,
    endDate=-449,
  }
}
troop_options['5fb1ba25e1af06001770c5ee'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-489,
    endDate=-449,
  }
}
-- allies
