-- 5fb1b9e6e1af060017709b83 Mali  900 to 1600 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba32e1af06001770dda9']= {
  min=0,
  max=1,
  description='Horsemen',
}
g_troop_entry['5fb1ba32e1af06001770ddaa']= {
  troop_option='5fb1ba32e1af06001770dda9',
  troopTypeCode='JCV',
}
g_troop_option['5fb1ba32e1af06001770ddab']= {
  min=1,
  max=4,
  description='Javelinmen',
  core='all',
}
g_troop_entry['5fb1ba32e1af06001770ddac']= {
  troop_option='5fb1ba32e1af06001770ddab',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba32e1af06001770ddad']= {
  min=6,
  max=22,
  description='Bowmen',
  core='all',
}
g_troop_entry['5fb1ba32e1af06001770ddae']= {
  troop_option='5fb1ba32e1af06001770ddad',
  troopTypeCode='BLV',
}
g_troop_option['5fb1ba32e1af06001770ddaf']= {
  min=0,
  max=2,
  description='Skirmishing bowmen',
}
g_troop_entry['5fb1ba32e1af06001770ddb0']= {
  troop_option='5fb1ba32e1af06001770ddaf',
  troopTypeCode='SKM',
}
g_str_5fb1ba32e1af06001770ddaa_general='5fb1ba32e1af06001770ddaa_general'
g_base_definitions[g_str_5fb1ba32e1af06001770ddaa_general]={
  id=g_str_5fb1ba32e1af06001770ddaa_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770ddaa='5fb1ba32e1af06001770ddaa'
g_base_definitions[g_str_5fb1ba32e1af06001770ddaa]={
  id=g_str_5fb1ba32e1af06001770ddaa,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770ddac_general='5fb1ba32e1af06001770ddac_general'
g_base_definitions[g_str_5fb1ba32e1af06001770ddac_general]={
  id=g_str_5fb1ba32e1af06001770ddac_general,
  name='Light Foot General',
  min=1,
  max=1,
  description='Javelinmen',
  general=true,
  troop_type="Light Foot",
}
g_str_5fb1ba32e1af06001770ddac='5fb1ba32e1af06001770ddac'
g_base_definitions[g_str_5fb1ba32e1af06001770ddac]={
  id=g_str_5fb1ba32e1af06001770ddac,
  name='Light Foot',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba32e1af06001770ddae='5fb1ba32e1af06001770ddae'
g_base_definitions[g_str_5fb1ba32e1af06001770ddae]={
  id=g_str_5fb1ba32e1af06001770ddae,
  name='Bow Levy',
  min=6,
  max=22,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba32e1af06001770ddb0='5fb1ba32e1af06001770ddb0'
g_base_definitions[g_str_5fb1ba32e1af06001770ddb0]={
  id=g_str_5fb1ba32e1af06001770ddb0,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1b9e6e1af060017709b83_camp='5fb1b9e6e1af060017709b83_camp'
g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp]={
  id=g_str_5fb1b9e6e1af060017709b83_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e6e1af060017709b83_camp_fortified='5fb1b9e6e1af060017709b83_camp_fortified'
g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp_fortified]={
  id=g_str_5fb1b9e6e1af060017709b83_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9e6e1af060017709b83_camp_pack_train='5fb1b9e6e1af060017709b83_camp_pack_train'
g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp_pack_train]={
  id=g_str_5fb1b9e6e1af060017709b83_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e6e1af060017709b83']={
  data={
    name='Mali  900 to 1600 AD',
    id='5fb1b9e6e1af060017709b83',
    army_id='5fb1b9e6e1af060017709b83'
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770ddaa_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770ddaa],
  g_base_definitions[g_str_5fb1ba32e1af06001770ddac_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770ddac],
  g_base_definitions[g_str_5fb1ba32e1af06001770ddae],
  g_base_definitions[g_str_5fb1ba32e1af06001770ddb0],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b83"] = army["5fb1b9e6e1af060017709b83"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Mali  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b83"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mali  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b83"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b83"] = {}
army_dates["5fb1b9e6e1af060017709b83"]["900 AD to 1600 AD"] ="5fb1b9e6e1af060017709b83"
