-- 5fb1b9dbe1af0600177094dd Tullian Roman  578 to 400 BC

army['5fb1b9dbe1af0600177094dd']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Tullian Roman  578 to 400 BC',
    id='5fb1b9dbe1af0600177094dd',
    dateRange={
      startDate=-578,
      endDate=-400,
    }
  },
  g_base_definitions[g_str_5fb1ba24e1af06001770c58a_general],
  g_base_definitions[g_str_5fb1ba24e1af06001770c58a],
  g_base_definitions[g_str_5fb1ba24e1af06001770c58c_general],
  g_base_definitions[g_str_5fb1ba24e1af06001770c58c],
  g_base_definitions[g_str_5fb1ba24e1af06001770c58f],
  g_base_definitions[g_str_5fb1ba24e1af06001770c591],
  g_base_definitions[g_str_5fb1ba24e1af06001770c592],
  g_base_definitions[g_str_5fb1ba24e1af06001770c594],
  g_base_definitions[g_str_5fb1ba24e1af06001770c596],
  g_base_definitions[g_str_5fb1ba24e1af06001770c597],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094dd_camp],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094dd_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094dd"] = army["5fb1b9dbe1af0600177094dd"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Tullian Roman  578 to 400 BC"] = army["5fb1b9dbe1af0600177094dd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tullian Roman  578 to 400 BC"] = army["5fb1b9dbe1af0600177094dd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094dd"] = {}
army_dates["5fb1b9dbe1af0600177094dd"]["578 BC to 400 BC"] = {
  startDate=-578,
  endDate=-400
}
army_dates["5fb1b9dbe1af0600177094dd"]["578 BC to 509 BC"] = {
  startDate=-578,
  endDate=-509
}
army_dates["5fb1b9dbe1af0600177094dd"]["508 BC to 400 BC"] = {
  startDate=-508,
  endDate=-400
}
