-- 5fb1b9dee1af06001770965f Alketas  320 to 320 BC

army['5fb1b9dee1af06001770965f']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
    },
    name='Alketas  320 to 320 BC',
    id='5fb1b9dee1af06001770965f',
    dateRange={
      startDate=-320,
      endDate=-320,
    },
  },
  g_base_definitions[g_str_5fb1ba28e1af06001770cb86_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb86],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb88_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb88],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb8a],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb8c],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb8e],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb91],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb93],
  g_base_definitions[g_str_5fb1ba28e1af06001770cb95],
  g_base_definitions[g_str_5fb1b9dee1af06001770965f_camp],
  g_base_definitions[g_str_5fb1b9dee1af06001770965f_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af06001770965f"] = army["5fb1b9dee1af06001770965f"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Alketas  320 to 320 BC"] = army["5fb1b9dee1af06001770965f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Alketas  320 to 320 BC"] = army["5fb1b9dee1af06001770965f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af06001770965f"] = {}
army_dates["5fb1b9dee1af06001770965f"]["320 BC"] = {
  startDate=-320,
  endDate=-320
}
