g_str_5fb1ba33e1af06001770df9f_general='5fb1ba33e1af06001770df9f_general'
g_base_definitions[g_str_5fb1ba33e1af06001770df9f_general]={
  id=g_str_5fb1ba33e1af06001770df9f_general,
  name='Knights General',
  min=2,
  max=1,
  description='Men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770df9e",
}
g_str_5fb1ba33e1af06001770df9f='5fb1ba33e1af06001770df9f'
g_base_definitions[g_str_5fb1ba33e1af06001770df9f]={
  id=g_str_5fb1ba33e1af06001770df9f,
  name='Knights',
  min=2,
  max=4,
  description='Men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770df9e",
}
g_str_5fb1ba33e1af06001770dfa1_general='5fb1ba33e1af06001770dfa1_general'
g_base_definitions[g_str_5fb1ba33e1af06001770dfa1_general]={
  id=g_str_5fb1ba33e1af06001770dfa1_general,
  name='Knights General',
  min=0,
  max=1,
  description='Military order men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dfa0",
}
g_str_5fb1ba33e1af06001770dfa1='5fb1ba33e1af06001770dfa1'
g_base_definitions[g_str_5fb1ba33e1af06001770dfa1]={
  id=g_str_5fb1ba33e1af06001770dfa1,
  name='Knights',
  min=0,
  max=1,
  description='Military order men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770dfa0",
}
g_str_5fb1ba33e1af06001770dfa3='5fb1ba33e1af06001770dfa3'
g_base_definitions[g_str_5fb1ba33e1af06001770dfa3]={
  id=g_str_5fb1ba33e1af06001770dfa3,
  name='Javelin Cavalry',
  min=2,
  max=4,
  description='Jinetes',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba33e1af06001770dfa2",
}
g_str_5fb1ba33e1af06001770dfa5='5fb1ba33e1af06001770dfa5'
g_base_definitions[g_str_5fb1ba33e1af06001770dfa5]={
  id=g_str_5fb1ba33e1af06001770dfa5,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba33e1af06001770dfa4",
}
g_str_5fb1ba33e1af06001770dfa7='5fb1ba33e1af06001770dfa7'
g_base_definitions[g_str_5fb1ba33e1af06001770dfa7]={
  id=g_str_5fb1ba33e1af06001770dfa7,
  name='Bow Levy',
  min=1,
  max=4,
  description='Crossbowmen and bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770dfa6",
}
g_str_5fb1ba33e1af06001770dfa8='5fb1ba33e1af06001770dfa8'
g_base_definitions[g_str_5fb1ba33e1af06001770dfa8]={
  id=g_str_5fb1ba33e1af06001770dfa8,
  name='Archers',
  min=1,
  max=4,
  description='Crossbowmen and bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770dfa6",
}
g_str_5fb1ba33e1af06001770dfaa='5fb1ba33e1af06001770dfaa'
g_base_definitions[g_str_5fb1ba33e1af06001770dfaa]={
  id=g_str_5fb1ba33e1af06001770dfaa,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba33e1af06001770dfa9",
}
g_str_5fb1ba33e1af06001770dfac='5fb1ba33e1af06001770dfac'
g_base_definitions[g_str_5fb1ba33e1af06001770dfac]={
  id=g_str_5fb1ba33e1af06001770dfac,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba33e1af06001770dfab",
}
g_str_5fb1b9e7e1af060017709c12_camp='5fb1b9e7e1af060017709c12_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709c12_camp]={
  id=g_str_5fb1b9e7e1af060017709c12_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e7e1af060017709c12_camp_pack_train='5fb1b9e7e1af060017709c12_camp_pack_train'
g_base_definitions[g_str_5fb1b9e7e1af060017709c12_camp_pack_train]={
  id=g_str_5fb1b9e7e1af060017709c12_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
