-- 5fb1b9f0e1af06001770a142 Dongyi  2000 to 315 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3ee1af06001770f503='5fb1ba3ee1af06001770f503'
g_base_definitions[g_str_5fb1ba3ee1af06001770f503]={
  id=g_str_5fb1ba3ee1af06001770f503,
  name='Warband',
  min=5,
  max=12,
  description='Fierce tribal foot',
}
g_str_5fb1ba3ee1af06001770f505='5fb1ba3ee1af06001770f505'
g_base_definitions[g_str_5fb1ba3ee1af06001770f505]={
  id=g_str_5fb1ba3ee1af06001770f505,
  name='Bow Levy',
  min=2,
  max=8,
  description='Bowmen',
}
g_str_5fb1ba3ee1af06001770f507='5fb1ba3ee1af06001770f507'
g_base_definitions[g_str_5fb1ba3ee1af06001770f507]={
  id=g_str_5fb1ba3ee1af06001770f507,
  name='Skirmishers',
  min=2,
  max=4,
  description='Skirmishing bowmen and slingers',
}
g_str_5fb1ba3ee1af06001770f509='5fb1ba3ee1af06001770f509'
g_base_definitions[g_str_5fb1ba3ee1af06001770f509]={
  id=g_str_5fb1ba3ee1af06001770f509,
  name='Horde',
  min=0,
  max=2,
  description='Levies, families, ill-equipped tribesmen and the like',
}
g_str_5fb1ba3ee1af06001770f50b='5fb1ba3ee1af06001770f50b'
g_base_definitions[g_str_5fb1ba3ee1af06001770f50b]={
  name='Warband General',
  id=g_str_5fb1ba3ee1af06001770f50b,
  min=1,
  max=1,
}
g_str_5fb1b9f0e1af06001770a142_camp='5fb1b9f0e1af06001770a142_camp'
g_base_definitions[g_str_5fb1b9f0e1af06001770a142_camp]={
  name='Camp',
  id=g_str_5fb1b9f0e1af06001770a142_camp,
  min=1,
  max=1,
}
army['5fb1b9f0e1af06001770a142']={
  data={
    name='Dongyi  2000 to 315 BC'
  },
  g_base_definitions[g_str_5fb1b9f0e1af06001770a142_camp],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f50b],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f503],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f505],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f507],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f509],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a142"] = army["5fb1b9f0e1af06001770a142"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Dongyi  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a142"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Dongyi  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a142"]
