g_str_5fb1ba3ee1af06001770f491_general='5fb1ba3ee1af06001770f491_general'
g_base_definitions[g_str_5fb1ba3ee1af06001770f491_general]={
  id=g_str_5fb1ba3ee1af06001770f491_general,
  name='Elephants General',
  min=2,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
  troop_option_id="5fb1ba3ee1af06001770f490",
}
g_str_5fb1ba3ee1af06001770f491='5fb1ba3ee1af06001770f491'
g_base_definitions[g_str_5fb1ba3ee1af06001770f491]={
  id=g_str_5fb1ba3ee1af06001770f491,
  name='Elephants',
  min=2,
  max=3,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba3ee1af06001770f490",
}
g_str_5fb1ba3ee1af06001770f494='5fb1ba3ee1af06001770f494'
g_base_definitions[g_str_5fb1ba3ee1af06001770f494]={
  id=g_str_5fb1ba3ee1af06001770f494,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3ee1af06001770f493",
}
g_str_5fb1ba3ee1af06001770f496='5fb1ba3ee1af06001770f496'
g_base_definitions[g_str_5fb1ba3ee1af06001770f496]={
  id=g_str_5fb1ba3ee1af06001770f496,
  name='Raiders',
  min=0,
  max=2,
  description='Retinue and veteran soldiers',
  troop_type="Raiders",
  troop_option_id="5fb1ba3ee1af06001770f495",
}
g_str_5fb1ba3ee1af06001770f496_elephant_screen='5fb1ba3ee1af06001770f496_elephant_screen'
g_base_definitions[g_str_5fb1ba3ee1af06001770f496_elephant_screen]={
  id=g_str_5fb1ba3ee1af06001770f496_elephant_screen,
  name='Raiders',
  min=0,
  max=2,
  description='Retinue and veteran soldiers\nElephant Screen',
  elephant_screen=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba3ee1af06001770f495",
}
g_str_5fb1ba3ee1af06001770f496_elephant_screen_elephant_screen_counter='5fb1ba3ee1af06001770f496_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3ee1af06001770f496_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3ee1af06001770f496_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=2,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3ee1af06001770f49a='5fb1ba3ee1af06001770f49a'
g_base_definitions[g_str_5fb1ba3ee1af06001770f49a]={
  id=g_str_5fb1ba3ee1af06001770f49a,
  name='Light Foot',
  min=4,
  max=12,
  description='Levies or fierce infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3ee1af06001770f499",
}
g_str_5fb1ba3ee1af06001770f49b='5fb1ba3ee1af06001770f49b'
g_base_definitions[g_str_5fb1ba3ee1af06001770f49b]={
  id=g_str_5fb1ba3ee1af06001770f49b,
  name='Warband',
  min=4,
  max=12,
  description='Levies or fierce infantry',
  troop_type="Warband",
  troop_option_id="5fb1ba3ee1af06001770f499",
}
g_str_5fb1ba3ee1af06001770f49e='5fb1ba3ee1af06001770f49e'
g_base_definitions[g_str_5fb1ba3ee1af06001770f49e]={
  id=g_str_5fb1ba3ee1af06001770f49e,
  name='Skirmishers',
  min=1,
  max=3,
  description='Skirmishing bowmen and crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3ee1af06001770f49d",
}
g_str_5fb1ba3ee1af06001770f4a1='5fb1ba3ee1af06001770f4a1'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4a1]={
  id=g_str_5fb1ba3ee1af06001770f4a1,
  name='Bow Levy',
  min=0,
  max=2,
  description='Bowmen and crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3ee1af06001770f4a0",
}
g_str_5fb1b9f0e1af06001770a11c_camp='5fb1b9f0e1af06001770a11c_camp'
g_base_definitions[g_str_5fb1b9f0e1af06001770a11c_camp]={
  id=g_str_5fb1b9f0e1af06001770a11c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f0e1af06001770a11c_camp_fortified='5fb1b9f0e1af06001770a11c_camp_fortified'
g_base_definitions[g_str_5fb1b9f0e1af06001770a11c_camp_fortified]={
  id=g_str_5fb1b9f0e1af06001770a11c_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
g_str_5fb1ba17e1af06001770b8ad='5fb1ba17e1af06001770b8ad'
g_base_definitions[g_str_5fb1ba17e1af06001770b8ad]={
  id=g_str_5fb1ba17e1af06001770b8ad,
  name='Elephants',
  min=1,
  max=1,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba17e1af06001770b8ac",
}
g_str_5fb1ba17e1af06001770b8af='5fb1ba17e1af06001770b8af'
g_base_definitions[g_str_5fb1ba17e1af06001770b8af]={
  id=g_str_5fb1ba17e1af06001770b8af,
  name='Raiders',
  min=1,
  max=1,
  description='Jacketed spearmen with long shield',
  troop_type="Raiders",
  troop_option_id="5fb1ba17e1af06001770b8ae",
}
g_str_5fb1ba17e1af06001770b8b1='5fb1ba17e1af06001770b8b1'
g_base_definitions[g_str_5fb1ba17e1af06001770b8b1]={
  id=g_str_5fb1ba17e1af06001770b8b1,
  name='Light Foot',
  min=0,
  max=1,
  description='Jacketed spearmen with small round shield',
  troop_type="Light Foot",
  troop_option_id="5fb1ba17e1af06001770b8b0",
}
g_str_5fb1ba17e1af06001770b8b3='5fb1ba17e1af06001770b8b3'
g_base_definitions[g_str_5fb1ba17e1af06001770b8b3]={
  id=g_str_5fb1ba17e1af06001770b8b3,
  name='Light Foot',
  min=1,
  max=2,
  description='Unarmored spearmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba17e1af06001770b8b2",
}
g_str_5fb1ba17e1af06001770b8b5='5fb1ba17e1af06001770b8b5'
g_base_definitions[g_str_5fb1ba17e1af06001770b8b5]={
  id=g_str_5fb1ba17e1af06001770b8b5,
  name='Skirmishers',
  min=1,
  max=1,
  description='Bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba17e1af06001770b8b4",
}
