-- 5fb1b9dfe1af060017709758 Arabo-Aramaean Other  312 BC to 240 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ae1af06001770cf99_general='5fb1ba2ae1af06001770cf99_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf99_general]={
  id=g_str_5fb1ba2ae1af06001770cf99_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ae1af06001770cf99='5fb1ba2ae1af06001770cf99'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf99]={
  id=g_str_5fb1ba2ae1af06001770cf99,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ae1af06001770cf9c_general='5fb1ba2ae1af06001770cf9c_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf9c_general]={
  id=g_str_5fb1ba2ae1af06001770cf9c_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ae1af06001770cf9c='5fb1ba2ae1af06001770cf9c'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf9c]={
  id=g_str_5fb1ba2ae1af06001770cf9c,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ae1af06001770cf9d='5fb1ba2ae1af06001770cf9d'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf9d]={
  id=g_str_5fb1ba2ae1af06001770cf9d,
  name='Cataphracts',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Cataphracts",
}
g_str_5fb1ba2ae1af06001770cf9f_general='5fb1ba2ae1af06001770cf9f_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf9f_general]={
  id=g_str_5fb1ba2ae1af06001770cf9f_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Horse archers',
  general=true,
  troop_type="Horse Bow",
}
g_str_5fb1ba2ae1af06001770cf9f='5fb1ba2ae1af06001770cf9f'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf9f]={
  id=g_str_5fb1ba2ae1af06001770cf9f,
  name='Horse Bow',
  min=1,
  max=4,
  description='Horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba2ae1af06001770cfa2='5fb1ba2ae1af06001770cfa2'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfa2]={
  id=g_str_5fb1ba2ae1af06001770cfa2,
  name='Raiders',
  min=0,
  max=1,
  description='Guard infantry',
  troop_type="Raiders",
}
g_str_5fb1ba2ae1af06001770cfa4='5fb1ba2ae1af06001770cfa4'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfa4]={
  id=g_str_5fb1ba2ae1af06001770cfa4,
  name='Bad Horse',
  min=0,
  max=1,
  description='Scouts on camels',
  troop_type="Bad Horse",
}
g_str_5fb1ba2ae1af06001770cfa7='5fb1ba2ae1af06001770cfa7'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfa7]={
  id=g_str_5fb1ba2ae1af06001770cfa7,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Swordsmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba2ae1af06001770cfa9='5fb1ba2ae1af06001770cfa9'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfa9]={
  id=g_str_5fb1ba2ae1af06001770cfa9,
  name='Light Foot',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba2ae1af06001770cfab='5fb1ba2ae1af06001770cfab'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfab]={
  id=g_str_5fb1ba2ae1af06001770cfab,
  name='Archers',
  min=5,
  max=16,
  description='Bowmen',
  troop_type="Archers",
}
g_str_5fb1ba2ae1af06001770cfac='5fb1ba2ae1af06001770cfac'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfac]={
  id=g_str_5fb1ba2ae1af06001770cfac,
  name='Bow Levy',
  min=5,
  max=16,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba2ae1af06001770cfae='5fb1ba2ae1af06001770cfae'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfae]={
  id=g_str_5fb1ba2ae1af06001770cfae,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
}
g_str_5fb1b9dfe1af060017709758_camp='5fb1b9dfe1af060017709758_camp'
g_base_definitions[g_str_5fb1b9dfe1af060017709758_camp]={
  name='Camp',
  id=g_str_5fb1b9dfe1af060017709758_camp,
  min=1,
  max=1,
}
army['5fb1b9dfe1af060017709758']={
  data={
    name='Arabo-Aramaean Other  312 BC to 240 AD'
  },
  g_base_definitions[g_str_5fb1b9dfe1af060017709758_camp],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfb0],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfb1],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf99_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf99],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9c_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9c],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9d],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9f_general],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cf9f],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa2],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa4],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa7],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfa9],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfab],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfac],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfae],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709758"] = army["5fb1b9dfe1af060017709758"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Arabo-Aramaean Other  312 BC to 240 AD"] = army["5fb1b9dfe1af060017709758"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Arabo-Aramaean Other  312 BC to 240 AD"] = army["5fb1b9dfe1af060017709758"]
