-- 5fb1b9e8e1af060017709cbb Feudal German Citystates  1106 to 1320 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba34e1af06001770e20e']= {
  min=0,
  max=1,
  description='City men-at-arms and mounted rich burghers',
  core='all',
}
g_str_5fb1ba34e1af06001770e20f_general='5fb1ba34e1af06001770e20f_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e20f_general]={
  id=g_str_5fb1ba34e1af06001770e20f_general,
  name='Knights General',
  min=0,
  max=1,
  description='City men-at-arms and mounted rich burghers',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e20e",
}
g_str_5fb1ba34e1af06001770e20f='5fb1ba34e1af06001770e20f'
g_base_definitions[g_str_5fb1ba34e1af06001770e20f]={
  id=g_str_5fb1ba34e1af06001770e20f,
  name='Knights',
  min=0,
  max=1,
  description='City men-at-arms and mounted rich burghers',
  troop_type="Knights",
  troop_option_id="5fb1ba34e1af06001770e20e",
}
g_troop_option['5fb1ba34e1af06001770e211']= {
  min=0,
  max=1,
  description='Hungarian horse archers',
  startDate=1150,
  endDate=1320,
}
g_str_5fb1ba34e1af06001770e213='5fb1ba34e1af06001770e213'
g_base_definitions[g_str_5fb1ba34e1af06001770e213]={
  id=g_str_5fb1ba34e1af06001770e213,
  name='Horse Bow',
  min=0,
  max=1,
  description='Hungarian horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba34e1af06001770e211",
}
g_troop_option['5fb1ba34e1af06001770e214']= {
  min=2,
  max=4,
  description='City militia crossbow',
  core='all',
}
g_str_5fb1ba34e1af06001770e215='5fb1ba34e1af06001770e215'
g_base_definitions[g_str_5fb1ba34e1af06001770e215]={
  id=g_str_5fb1ba34e1af06001770e215,
  name='Bow Levy',
  min=2,
  max=4,
  description='City militia crossbow',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e214",
}
g_troop_option['5fb1ba34e1af06001770e216']= {
  min=2,
  max=4,
  description='City militia spearmen',
  core='all',
}
g_str_5fb1ba34e1af06001770e217_general='5fb1ba34e1af06001770e217_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e217_general]={
  id=g_str_5fb1ba34e1af06001770e217_general,
  name='Heavy Foot General',
  min=2,
  max=1,
  description='City militia spearmen',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e216",
}
g_str_5fb1ba34e1af06001770e217='5fb1ba34e1af06001770e217'
g_base_definitions[g_str_5fb1ba34e1af06001770e217]={
  id=g_str_5fb1ba34e1af06001770e217,
  name='Heavy Foot',
  min=2,
  max=4,
  description='City militia spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e216",
}
g_troop_option['5fb1ba34e1af06001770e219']= {
  min=0,
  max=3,
  description='City militia skirmishing bowmen',
}
g_str_5fb1ba34e1af06001770e21a='5fb1ba34e1af06001770e21a'
g_base_definitions[g_str_5fb1ba34e1af06001770e21a]={
  id=g_str_5fb1ba34e1af06001770e21a,
  name='Skirmishers',
  min=0,
  max=3,
  description='City militia skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e219",
}
g_troop_option['5fb1ba34e1af06001770e21c']= {
  min=0,
  max=2,
  description='Brabanter mercenary pikemen',
  core='all',
  startDate=1150,
  endDate=1320,
}
g_str_5fb1ba34e1af06001770e21e='5fb1ba34e1af06001770e21e'
g_base_definitions[g_str_5fb1ba34e1af06001770e21e]={
  id=g_str_5fb1ba34e1af06001770e21e,
  name='Pikes',
  min=0,
  max=2,
  description='Brabanter mercenary pikemen',
  troop_type="Pikes",
  troop_option_id="5fb1ba34e1af06001770e21c",
}
g_troop_option['5fb1ba34e1af06001770e21f']= {
  min=0,
  max=3,
  description='Poorly equipped heerban',
  core='all',
}
g_str_5fb1ba34e1af06001770e220='5fb1ba34e1af06001770e220'
g_base_definitions[g_str_5fb1ba34e1af06001770e220]={
  id=g_str_5fb1ba34e1af06001770e220,
  name='Horde',
  min=0,
  max=3,
  description='Poorly equipped heerban',
  troop_type="Horde",
  troop_option_id="5fb1ba34e1af06001770e21f",
}
g_troop_option['5fb1ba34e1af06001770e221']= {
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  core='all',
}
g_str_5fb1ba34e1af06001770e222='5fb1ba34e1af06001770e222'
g_base_definitions[g_str_5fb1ba34e1af06001770e222]={
  id=g_str_5fb1ba34e1af06001770e222,
  name='Bow Levy',
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e221",
}
g_troop_option['5fb1ba34e1af06001770e223']= {
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, or halberdiers',
  core='all',
}
g_str_5fb1ba34e1af06001770e224_general='5fb1ba34e1af06001770e224_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e224_general]={
  id=g_str_5fb1ba34e1af06001770e224_general,
  name='Heavy Foot General',
  min=0,
  max=1,
  description='Mercenary axemen, swordsmen, or halberdiers',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e223",
}
g_str_5fb1ba34e1af06001770e224='5fb1ba34e1af06001770e224'
g_base_definitions[g_str_5fb1ba34e1af06001770e224]={
  id=g_str_5fb1ba34e1af06001770e224,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, or halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e223",
}
g_troop_option['5fb1ba34e1af06001770e226']= {
  min=1,
  max=2,
  description='Mercenary bowmen or crossbowmen',
}
g_str_5fb1ba34e1af06001770e227='5fb1ba34e1af06001770e227'
g_base_definitions[g_str_5fb1ba34e1af06001770e227]={
  id=g_str_5fb1ba34e1af06001770e227,
  name='Archers',
  min=1,
  max=2,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e226",
}
g_str_5fb1ba34e1af06001770e228='5fb1ba34e1af06001770e228'
g_base_definitions[g_str_5fb1ba34e1af06001770e228]={
  id=g_str_5fb1ba34e1af06001770e228,
  name='Skirmishers',
  min=1,
  max=2,
  description='Mercenary bowmen or crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e226",
}
g_str_5fb1b9e8e1af060017709cbb_camp='5fb1b9e8e1af060017709cbb_camp'
g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp]={
  id=g_str_5fb1b9e8e1af060017709cbb_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e8e1af060017709cbb_camp_fortified='5fb1b9e8e1af060017709cbb_camp_fortified'
g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_fortified]={
  id=g_str_5fb1b9e8e1af060017709cbb_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9e8e1af060017709cbb_camp_standard_wagon='5fb1b9e8e1af060017709cbb_camp_standard_wagon'
g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_standard_wagon]={
  id=g_str_5fb1b9e8e1af060017709cbb_camp_standard_wagon,
  name='Camp',
  min=0,
  max=1,
  description='Standard Wagon',
  standard_wagon=true,
  troop_type="Camp",
}
army['5fb1b9e8e1af060017709cbb']={
  data={
    name='Feudal German Citystates  1106 to 1320 AD',
    id='5fb1b9e8e1af060017709cbb',
    army_id='5fb1b9e8e1af060017709cbb'
  },
  g_base_definitions[g_str_5fb1ba34e1af06001770e20f_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e20f],
  g_base_definitions[g_str_5fb1ba34e1af06001770e213],
  g_base_definitions[g_str_5fb1ba34e1af06001770e215],
  g_base_definitions[g_str_5fb1ba34e1af06001770e217_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e217],
  g_base_definitions[g_str_5fb1ba34e1af06001770e21a],
  g_base_definitions[g_str_5fb1ba34e1af06001770e21e],
  g_base_definitions[g_str_5fb1ba34e1af06001770e220],
  g_base_definitions[g_str_5fb1ba34e1af06001770e222],
  g_base_definitions[g_str_5fb1ba34e1af06001770e224_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e224],
  g_base_definitions[g_str_5fb1ba34e1af06001770e227],
  g_base_definitions[g_str_5fb1ba34e1af06001770e228],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_standard_wagon],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709cbb"] = army["5fb1b9e8e1af060017709cbb"]
army['5fb1b9e8e1af060017709cbb_1106_1149']={
  data={
    name='Feudal German Citystates 1106 AD to 1149 AD',
    id='5fb1b9e8e1af060017709cbb_1106_1149',
    army_id='5fb1b9e8e1af060017709cbb'
  },
  g_base_definitions[g_str_5fb1ba34e1af06001770e20f_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e20f],
  g_base_definitions[g_str_5fb1ba34e1af06001770e215],
  g_base_definitions[g_str_5fb1ba34e1af06001770e217_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e217],
  g_base_definitions[g_str_5fb1ba34e1af06001770e21a],
  g_base_definitions[g_str_5fb1ba34e1af06001770e220],
  g_base_definitions[g_str_5fb1ba34e1af06001770e222],
  g_base_definitions[g_str_5fb1ba34e1af06001770e224_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e224],
  g_base_definitions[g_str_5fb1ba34e1af06001770e227],
  g_base_definitions[g_str_5fb1ba34e1af06001770e228],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_standard_wagon],
}
army['5fb1b9e8e1af060017709cbb_1150_1320']={
  data={
    name='Feudal German Citystates 1150 AD to 1320 AD',
    id='5fb1b9e8e1af060017709cbb_1150_1320',
    army_id='5fb1b9e8e1af060017709cbb'
  },
  g_base_definitions[g_str_5fb1ba34e1af06001770e20f_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e20f],
  g_base_definitions[g_str_5fb1ba34e1af06001770e213],
  g_base_definitions[g_str_5fb1ba34e1af06001770e215],
  g_base_definitions[g_str_5fb1ba34e1af06001770e217_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e217],
  g_base_definitions[g_str_5fb1ba34e1af06001770e21a],
  g_base_definitions[g_str_5fb1ba34e1af06001770e21e],
  g_base_definitions[g_str_5fb1ba34e1af06001770e220],
  g_base_definitions[g_str_5fb1ba34e1af06001770e222],
  g_base_definitions[g_str_5fb1ba34e1af06001770e224_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e224],
  g_base_definitions[g_str_5fb1ba34e1af06001770e227],
  g_base_definitions[g_str_5fb1ba34e1af06001770e228],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cbb_camp_standard_wagon],
}
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Feudal German Citystates  1106 to 1320 AD"] = army["5fb1b9e8e1af060017709cbb"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Feudal German Citystates  1106 to 1320 AD"] = army["5fb1b9e8e1af060017709cbb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Feudal German Citystates  1106 to 1320 AD"] = army["5fb1b9e8e1af060017709cbb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709cbb"] = {}
army_dates["5fb1b9e8e1af060017709cbb"]["1106 AD to 1320 AD"] ="5fb1b9e8e1af060017709cbb"
army_dates["5fb1b9e8e1af060017709cbb"]["1106 AD to 1149 AD"] ="5fb1b9e8e1af060017709cbb_1106_1149"
army_dates["5fb1b9e8e1af060017709cbb"]["1150 AD to 1320 AD"] ="5fb1b9e8e1af060017709cbb_1150_1320"
