troop_options['615351b103385c0016b8801a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b8801d'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b8801f'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b88021'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b88024'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b88027'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b88029'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b8802b'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b8802e'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b88030'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
troop_options['615351b103385c0016b88033'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1373,
    endDate=1464,
  }
}
-- allies
