-- 5fb1b9ede1af060017709f29 Zanj Revolt  869 to 883 AD

army['5fb1b9ede1af060017709f29']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Delta',
      'Dry',
    },
    name='Zanj Revolt  869 to 883 AD',
    id='5fb1b9ede1af060017709f29',
    dateRange={
      startDate=869,
      endDate=883,
    }
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ec98_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ec98],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ec9a_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ec9a],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ec9c],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ec9e],
  g_base_definitions[g_str_5fb1ba3ae1af06001770eca0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770eca2],
  g_base_definitions[g_str_5fb1b9ede1af060017709f29_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f29_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f29"] = army["5fb1b9ede1af060017709f29"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Zanj Revolt  869 to 883 AD"] = army["5fb1b9ede1af060017709f29"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Zanj Revolt  869 to 883 AD"] = army["5fb1b9ede1af060017709f29"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f29"] = {}
army_dates["5fb1b9ede1af060017709f29"]["869 AD to 883 AD"] = {
  startDate=869,
  endDate=883
}
