troop_options['5fb1ba40e1af06001770f8b6'] = {
  min=0,
  max=1,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8b8'] = {
  min=0,
  max=1,
  dateRange={
    startDate=755,
    endDate=906,
  }
}
troop_options['5fb1ba40e1af06001770f8bb'] = {
  min=1,
  max=3,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8be'] = {
  min=1,
  max=3,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8c1'] = {
  min=2,
  max=4,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8c5'] = {
  min=2,
  max=3,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8c8'] = {
  min=0,
  max=2,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8cb'] = {
  min=0,
  max=4,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8cd'] = {
  min=0,
  max=3,
  dateRange={
    startDate=755,
    endDate=979,
  }
}
troop_options['5fb1ba40e1af06001770f8d0'] = {
  min=0,
  max=1,
  dateRange={
    startDate=907,
    endDate=971,
  }
}
-- allies
