-- 5fb1b9dfe1af060017709736 Early Pontic  302 to 111 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba29e1af06001770cf05='5fb1ba29e1af06001770cf05'
g_base_definitions[g_str_5fb1ba29e1af06001770cf05]={
  id=g_str_5fb1ba29e1af06001770cf05,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Heavy horsemen with armored horses',
  general=true,
}
g_str_5fb1ba29e1af06001770cf05='5fb1ba29e1af06001770cf05'
g_base_definitions[g_str_5fb1ba29e1af06001770cf05]={
  id=g_str_5fb1ba29e1af06001770cf05,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Heavy horsemen with armored horses',
}
g_str_5fb1ba29e1af06001770cf07='5fb1ba29e1af06001770cf07'
g_base_definitions[g_str_5fb1ba29e1af06001770cf07]={
  id=g_str_5fb1ba29e1af06001770cf07,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Horsemen and light horsemen armed with javelins',
}
g_str_5fb1ba29e1af06001770cf09='5fb1ba29e1af06001770cf09'
g_base_definitions[g_str_5fb1ba29e1af06001770cf09]={
  id=g_str_5fb1ba29e1af06001770cf09,
  name='Pikes',
  min=0,
  max=2,
  description='Phalanx',
}
g_str_5fb1ba29e1af06001770cf0b='5fb1ba29e1af06001770cf0b'
g_base_definitions[g_str_5fb1ba29e1af06001770cf0b]={
  id=g_str_5fb1ba29e1af06001770cf0b,
  name='Light Foot',
  min=4,
  max=8,
  description='Javelinmen',
}
g_str_5fb1ba29e1af06001770cf0d='5fb1ba29e1af06001770cf0d'
g_base_definitions[g_str_5fb1ba29e1af06001770cf0d]={
  id=g_str_5fb1ba29e1af06001770cf0d,
  name='Bow Levy',
  min=1,
  max=2,
  description='Bowmen',
}
g_str_5fb1ba29e1af06001770cf0f='5fb1ba29e1af06001770cf0f'
g_base_definitions[g_str_5fb1ba29e1af06001770cf0f]={
  id=g_str_5fb1ba29e1af06001770cf0f,
  name='Raiders',
  min=1,
  max=2,
  description='Mercenary Greek thureophoroi',
}
g_str_5fb1ba29e1af06001770cf11='5fb1ba29e1af06001770cf11'
g_base_definitions[g_str_5fb1ba29e1af06001770cf11]={
  id=g_str_5fb1ba29e1af06001770cf11,
  name='Light Foot',
  min=0,
  max=2,
  description='Thracian light infantry',
}
g_str_5fb1ba29e1af06001770cf13='5fb1ba29e1af06001770cf13'
g_base_definitions[g_str_5fb1ba29e1af06001770cf13]={
  id=g_str_5fb1ba29e1af06001770cf13,
  name='Warriors',
  min=0,
  max=2,
  description='Galatian mercenary foot',
}
g_str_5fb1b9dfe1af060017709736_camp='5fb1b9dfe1af060017709736_camp'
g_base_definitions[g_str_5fb1b9dfe1af060017709736_camp]={
  name='Camp',
  id=g_str_5fb1b9dfe1af060017709736_camp,
  min=1,
  max=1,
}
army['5fb1b9dfe1af060017709736']={
  data={
    name='Early Pontic  302 to 111 BC'
  },
  g_base_definitions[g_str_5fb1b9dfe1af060017709736_camp],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf15],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf05],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf05],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf07],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf09],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf0b],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf0d],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf0f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf11],
  g_base_definitions[g_str_5fb1ba29e1af06001770cf13],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709736"] = army["5fb1b9dfe1af060017709736"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Pontic  302 to 111 BC"] = army["5fb1b9dfe1af060017709736"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early Pontic  302 to 111 BC"] = army["5fb1b9dfe1af060017709736"]
