-- 5fb1b9eee1af060017709fc9 Ayyubid Egyptian  1171 to 1250 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3be1af06001770ef28_general='5fb1ba3be1af06001770ef28_general'
g_base_definitions[g_str_5fb1ba3be1af06001770ef28_general]={
  id=g_str_5fb1ba3be1af06001770ef28_general,
  name='Elite Cavalary General',
  min=2,
  max=1,
  description='Toassin, halqa or Kipchak mamluks armed with bow and lance, possibly with horse armor',
  general=true,
}
g_str_5fb1ba3be1af06001770ef28_general_dismounted='5fb1ba3be1af06001770ef28_general_dismounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef28_general_dismounted]={
  id=g_str_5fb1ba3be1af06001770ef28_general_dismounted,
  name='Archer',
  min=2,
  max=1,
  description='Toassin, halqa or Kipchak mamluks armed with bow and lance, possibly with horse armor\nDeployment dismounted from Elite Cavalary General',
  points=4,
  general=true,
}
g_5fb1ba3be1af06001770ef28_general_dismounted=g_base_definitions[g_str_5fb1ba3be1af06001770ef28_general_dismounted]
g_str_5fb1ba3be1af06001770ef28_general_mounted='5fb1ba3be1af06001770ef28_general_mounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef28_general_mounted]={
  id=g_str_5fb1ba3be1af06001770ef28_general_mounted,
  name='Elite Cavalary General',
  min=2,
  max=1,
  description='Toassin, halqa or Kipchak mamluks armed with bow and lance, possibly with horse armor\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_5fb1ba3be1af06001770ef28_general_dismounted,
  general=true,
}
g_str_5fb1ba3be1af06001770ef28='5fb1ba3be1af06001770ef28'
g_base_definitions[g_str_5fb1ba3be1af06001770ef28]={
  id=g_str_5fb1ba3be1af06001770ef28,
  name='Elite Cavalary',
  min=2,
  max=4,
  description='Toassin, halqa or Kipchak mamluks armed with bow and lance, possibly with horse armor',
}
g_str_5fb1ba3be1af06001770ef28_dismounted='5fb1ba3be1af06001770ef28_dismounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef28_dismounted]={
  id=g_str_5fb1ba3be1af06001770ef28_dismounted,
  name='Archer',
  min=2,
  max=4,
  description='Toassin, halqa or Kipchak mamluks armed with bow and lance, possibly with horse armor\nDeployment dismounted from Elite Cavalary',
  points=4,
}
g_5fb1ba3be1af06001770ef28_dismounted=g_base_definitions[g_str_5fb1ba3be1af06001770ef28_dismounted]
g_str_5fb1ba3be1af06001770ef28_mounted='5fb1ba3be1af06001770ef28_mounted'
g_base_definitions[g_str_5fb1ba3be1af06001770ef28_mounted]={
  id=g_str_5fb1ba3be1af06001770ef28_mounted,
  name='Elite Cavalary',
  min=2,
  max=4,
  description='Toassin, halqa or Kipchak mamluks armed with bow and lance, possibly with horse armor\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_5fb1ba3be1af06001770ef28_dismounted,
}
g_str_5fb1ba3be1af06001770ef2d='5fb1ba3be1af06001770ef2d'
g_base_definitions[g_str_5fb1ba3be1af06001770ef2d]={
  id=g_str_5fb1ba3be1af06001770ef2d,
  name='Horse Bow',
  min=2,
  max=6,
  description='Turkoman horse archers, or mamluks armed with bow but no lance or horse armor',
}
g_str_5fb1ba3be1af06001770ef30='5fb1ba3be1af06001770ef30'
g_base_definitions[g_str_5fb1ba3be1af06001770ef30]={
  id=g_str_5fb1ba3be1af06001770ef30,
  name='Horse Bow',
  min=0,
  max=2,
  description='Mamluks armed with bow but no lance or horse armor',
}
g_str_5fb1ba3be1af06001770ef32='5fb1ba3be1af06001770ef32'
g_base_definitions[g_str_5fb1ba3be1af06001770ef32]={
  id=g_str_5fb1ba3be1af06001770ef32,
  name='Javelin Cavalry',
  min=2,
  max=4,
  description='Qaraghulams, Kurds or Syrian askaris',
}
g_str_5fb1ba3be1af06001770ef34='5fb1ba3be1af06001770ef34'
g_base_definitions[g_str_5fb1ba3be1af06001770ef34]={
  id=g_str_5fb1ba3be1af06001770ef34,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Bedouin Arab horsemen',
}
g_str_5fb1ba3be1af06001770ef36='5fb1ba3be1af06001770ef36'
g_base_definitions[g_str_5fb1ba3be1af06001770ef36]={
  id=g_str_5fb1ba3be1af06001770ef36,
  name='Light Foot',
  min=0,
  max=2,
  description='Jabaliyya or Kurdish javelinmen',
}
g_str_5fb1ba3be1af06001770ef38='5fb1ba3be1af06001770ef38'
g_base_definitions[g_str_5fb1ba3be1af06001770ef38]={
  id=g_str_5fb1ba3be1af06001770ef38,
  name='Warband',
  min=0,
  max=2,
  description='Ghazis',
}
g_str_5fb1ba3be1af06001770ef3a='5fb1ba3be1af06001770ef3a'
g_base_definitions[g_str_5fb1ba3be1af06001770ef3a]={
  id=g_str_5fb1ba3be1af06001770ef3a,
  name='Horde',
  min=0,
  max=2,
  description='Syrian ahdath or Egyptian city mob',
}
g_str_5fb1ba3be1af06001770ef3b='5fb1ba3be1af06001770ef3b'
g_base_definitions[g_str_5fb1ba3be1af06001770ef3b]={
  id=g_str_5fb1ba3be1af06001770ef3b,
  name='Rabble',
  min=0,
  max=2,
  description='Syrian ahdath or Egyptian city mob',
}
g_str_5fb1ba3be1af06001770ef3d='5fb1ba3be1af06001770ef3d'
g_base_definitions[g_str_5fb1ba3be1af06001770ef3d]={
  id=g_str_5fb1ba3be1af06001770ef3d,
  name='Skirmishers',
  min=0,
  max=3,
  description='Al-ashair armed with mixed sling, bow, and crossbow',
}
g_str_5fb1ba3be1af06001770ef40='5fb1ba3be1af06001770ef40'
g_base_definitions[g_str_5fb1ba3be1af06001770ef40]={
  id=g_str_5fb1ba3be1af06001770ef40,
  name='Archers',
  min=0,
  max=3,
  description='Sudanese bowmen',
}
g_str_5fb1b9eee1af060017709fc9_camp='5fb1b9eee1af060017709fc9_camp'
g_base_definitions[g_str_5fb1b9eee1af060017709fc9_camp]={
  name='Camp',
  id=g_str_5fb1b9eee1af060017709fc9_camp,
  min=1,
  max=1,
}
army['5fb1b9eee1af060017709fc9']={
  data={
    name='Ayyubid Egyptian  1171 to 1250 AD'
  },
  g_base_definitions[g_str_5fb1b9eee1af060017709fc9_camp],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef42],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef28_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef28_general_mounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef28_general_dismounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef28],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef28_mounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef28_dismounted],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef2d],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef30],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef32],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef34],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef36],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef38],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef3a],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef3b],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef3d],
  g_base_definitions[g_str_5fb1ba3be1af06001770ef40],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af060017709fc9"] = army["5fb1b9eee1af060017709fc9"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Ayyubid Egyptian  1171 to 1250 AD"] = army["5fb1b9eee1af060017709fc9"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Ayyubid Egyptian  1171 to 1250 AD"] = army["5fb1b9eee1af060017709fc9"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Ayyubid Egyptian  1171 to 1250 AD"] = army["5fb1b9eee1af060017709fc9"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Ayyubid Egyptian  1171 to 1250 AD"] = army["5fb1b9eee1af060017709fc9"]
