-- 5fb1b9ece1af060017709ed7 Solomonic Ethiopia  1314 to 1529 AD

army['5fb1b9ece1af060017709ed7']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Solomonic Ethiopia  1314 to 1529 AD',
    id='5fb1b9ece1af060017709ed7',
    dateRange={
      startDate=1314,
      endDate=1529,
    }
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770eb27_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb27],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb29],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb2c],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb2e],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb30],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb32],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb34],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb34_light_camelry],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb37],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb39],
  g_base_definitions[g_str_5fb1ba39e1af06001770eb3c],
  g_base_definitions[g_str_5fb1b9ece1af060017709ed7_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ed7_camp_fortified],
  g_base_definitions[g_str_5fb1b9ece1af060017709ed7_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709ed7"] = army["5fb1b9ece1af060017709ed7"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Solomonic Ethiopia  1314 to 1529 AD"] = army["5fb1b9ece1af060017709ed7"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Solomonic Ethiopia  1314 to 1529 AD"] = army["5fb1b9ece1af060017709ed7"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709ed7"] = {}
army_dates["5fb1b9ece1af060017709ed7"]["1314 AD to 1529 AD"] = {
  startDate=1314,
  endDate=1529
}
army_dates["5fb1b9ece1af060017709ed7"]["1314 AD to 1447 AD"] = {
  startDate=1314,
  endDate=1447
}
army_dates["5fb1b9ece1af060017709ed7"]["1448 AD to 1529 AD"] = {
  startDate=1448,
  endDate=1529
}
