troop_options['5fb1ba29e1af06001770ced9'] = {
  min=9,
  max=14,
  dateRange={
    startDate=-168,
    endDate=-104,
  }
}
troop_options['5fb1ba29e1af06001770cedc'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-168,
    endDate=-104,
  }
}
troop_options['5fb1ba29e1af06001770cede'] = {
  min=0,
  max=5,
  dateRange={
    startDate=-168,
    endDate=-104,
  }
}
troop_options['5fb1ba29e1af06001770cee0'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-168,
    endDate=-104,
  }
}
-- allies
