-- 5fb1b9e1e1af060017709871 Cassivellaunus all mounted  55 to 54 BC

army['5fb1b9e1e1af060017709871']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Cassivellaunus all mounted  55 to 54 BC',
    id='5fb1b9e1e1af060017709871',
    dateRange={
      startDate=-55,
      endDate=-54,
    },
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d323_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d323],
  g_base_definitions[g_str_5fb1ba2be1af06001770d325],
  g_base_definitions[g_str_5fb1ba2be1af06001770d327],
  g_base_definitions[g_str_5fb1ba2be1af06001770d328],
  g_base_definitions[g_str_5fb1ba2be1af06001770d32a],
  g_base_definitions[g_str_5fb1b9e1e1af060017709871_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709871"] = army["5fb1b9e1e1af060017709871"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Cassivellaunus all mounted  55 to 54 BC"] = army["5fb1b9e1e1af060017709871"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Cassivellaunus all mounted  55 to 54 BC"] = army["5fb1b9e1e1af060017709871"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709871"] = {}
army_dates["5fb1b9e1e1af060017709871"]["55 BC to 54 BC"] = {
  startDate=-55,
  endDate=-54
}
