-- 5fb1b9ede1af060017709f35 Iqshidid Egyptian  935 to 969 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3ae1af06001770ecdc='5fb1ba3ae1af06001770ecdc'
g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc]={
  id=g_str_5fb1ba3ae1af06001770ecdc,
  name='Elite Cavalary General',
  min=3,
  max=1,
  description='Turkish, Greek and Armenian ghulams',
  general=true,
}
g_str_5fb1ba3ae1af06001770ecdc_dismounted='5fb1ba3ae1af06001770ecdc_dismounted'
g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_dismounted]={
  id=g_str_5fb1ba3ae1af06001770ecdc_dismounted,
  name='Archer',
  min=3,
  max=1,
  description='Turkish, Greek and Armenian ghulams\nDeployment dismounted from Elite Cavalary General',
  points=4,
  general=true,
}
g_5fb1ba3ae1af06001770ecdc_dismounted=g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_dismounted]
g_str_5fb1ba3ae1af06001770ecdc_mounted='5fb1ba3ae1af06001770ecdc_mounted'
g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_mounted]={
  id=g_str_5fb1ba3ae1af06001770ecdc_mounted,
  name='Elite Cavalary General',
  min=3,
  max=1,
  description='Turkish, Greek and Armenian ghulams\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_5fb1ba3ae1af06001770ecdc_dismounted,
  general=true,
}
g_str_5fb1ba3ae1af06001770ecdc='5fb1ba3ae1af06001770ecdc'
g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc]={
  id=g_str_5fb1ba3ae1af06001770ecdc,
  name='Elite Cavalary',
  min=3,
  max=5,
  description='Turkish, Greek and Armenian ghulams',
}
g_str_5fb1ba3ae1af06001770ecdc_dismounted='5fb1ba3ae1af06001770ecdc_dismounted'
g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_dismounted]={
  id=g_str_5fb1ba3ae1af06001770ecdc_dismounted,
  name='Archer',
  min=3,
  max=5,
  description='Turkish, Greek and Armenian ghulams\nDeployment dismounted from Elite Cavalary',
  points=4,
}
g_5fb1ba3ae1af06001770ecdc_dismounted=g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_dismounted]
g_str_5fb1ba3ae1af06001770ecdc_mounted='5fb1ba3ae1af06001770ecdc_mounted'
g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_mounted]={
  id=g_str_5fb1ba3ae1af06001770ecdc_mounted,
  name='Elite Cavalary',
  min=3,
  max=5,
  description='Turkish, Greek and Armenian ghulams\nDeployment dismounting as Archer',
  points=4,
  dismount_as=g_5fb1ba3ae1af06001770ecdc_dismounted,
}
g_str_5fb1ba3ae1af06001770ece0='5fb1ba3ae1af06001770ece0'
g_base_definitions[g_str_5fb1ba3ae1af06001770ece0]={
  id=g_str_5fb1ba3ae1af06001770ece0,
  name='Heavy Foot',
  min=4,
  max=6,
  description='Zanj spearmen',
}
g_str_5fb1ba3ae1af06001770ece2='5fb1ba3ae1af06001770ece2'
g_base_definitions[g_str_5fb1ba3ae1af06001770ece2]={
  id=g_str_5fb1ba3ae1af06001770ece2,
  name='Bow Levy',
  min=2,
  max=4,
  description='Zanj bowmen',
}
g_str_5fb1ba3ae1af06001770ece4='5fb1ba3ae1af06001770ece4'
g_base_definitions[g_str_5fb1ba3ae1af06001770ece4]={
  id=g_str_5fb1ba3ae1af06001770ece4,
  name='Light Foot',
  min=0,
  max=2,
  description='Berber javelinmen',
}
g_str_5fb1ba3ae1af06001770ece5='5fb1ba3ae1af06001770ece5'
g_base_definitions[g_str_5fb1ba3ae1af06001770ece5]={
  id=g_str_5fb1ba3ae1af06001770ece5,
  name='Rabble',
  min=0,
  max=2,
  description='Berber javelinmen',
}
g_str_5fb1ba3ae1af06001770ece7='5fb1ba3ae1af06001770ece7'
g_base_definitions[g_str_5fb1ba3ae1af06001770ece7]={
  id=g_str_5fb1ba3ae1af06001770ece7,
  name='Skirmishers',
  min=0,
  max=1,
  description='Berber bow and sling',
}
g_str_5fb1ba3ae1af06001770ece9='5fb1ba3ae1af06001770ece9'
g_base_definitions[g_str_5fb1ba3ae1af06001770ece9]={
  id=g_str_5fb1ba3ae1af06001770ece9,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Berber skirmishing bowmen and slingers',
}
g_str_5fb1ba3ae1af06001770eceb='5fb1ba3ae1af06001770eceb'
g_base_definitions[g_str_5fb1ba3ae1af06001770eceb]={
  id=g_str_5fb1ba3ae1af06001770eceb,
  name='Horde',
  min=0,
  max=1,
  description='Egyptian levies',
}
g_str_5fb1ba3ae1af06001770eced='5fb1ba3ae1af06001770eced'
g_base_definitions[g_str_5fb1ba3ae1af06001770eced]={
  id=g_str_5fb1ba3ae1af06001770eced,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Kurdish horsemen',
  general=true,
}
g_str_5fb1ba3ae1af06001770eced='5fb1ba3ae1af06001770eced'
g_base_definitions[g_str_5fb1ba3ae1af06001770eced]={
  id=g_str_5fb1ba3ae1af06001770eced,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Kurdish horsemen',
}
g_str_5fb1ba3ae1af06001770ecf0='5fb1ba3ae1af06001770ecf0'
g_base_definitions[g_str_5fb1ba3ae1af06001770ecf0]={
  id=g_str_5fb1ba3ae1af06001770ecf0,
  name='Raiders',
  min=0,
  max=2,
  description='Dailami zupin-men',
}
g_str_5fb1b9ede1af060017709f35_camp='5fb1b9ede1af060017709f35_camp'
g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp]={
  name='Camp',
  id=g_str_5fb1b9ede1af060017709f35_camp,
  min=1,
  max=1,
}
army['5fb1b9ede1af060017709f35']={
  data={
    name='Iqshidid Egyptian  935 to 969 AD'
  },
  g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_mounted],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_dismounted],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_mounted],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecdc_dismounted],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ece0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ece2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ece4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ece5],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ece7],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ece9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770eceb],
  g_base_definitions[g_str_5fb1ba3ae1af06001770eced],
  g_base_definitions[g_str_5fb1ba3ae1af06001770eced],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ecf0],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f35"] = army["5fb1b9ede1af060017709f35"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Iqshidid Egyptian  935 to 969 AD"] = army["5fb1b9ede1af060017709f35"]
