-- 5fb1b9eee1af06001770a004 Mamluk Egyptian  1250 to 1517 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3be1af06001770f015_general='5fb1ba3be1af06001770f015_general'
g_base_definitions[g_str_5fb1ba3be1af06001770f015_general]={
  id=g_str_5fb1ba3be1af06001770f015_general,
  name='Elite Cavalary General',
  min=3,
  max=1,
  description='Royal or Amir\'s mamluks',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3be1af06001770f014",
}
g_str_5fb1ba3be1af06001770f015='5fb1ba3be1af06001770f015'
g_base_definitions[g_str_5fb1ba3be1af06001770f015]={
  id=g_str_5fb1ba3be1af06001770f015,
  name='Elite Cavalary',
  min=3,
  max=6,
  description='Royal or Amir\'s mamluks',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3be1af06001770f014",
}
g_str_5fb1ba3be1af06001770f018='5fb1ba3be1af06001770f018'
g_base_definitions[g_str_5fb1ba3be1af06001770f018]={
  id=g_str_5fb1ba3be1af06001770f018,
  name='Horse Bow',
  min=3,
  max=6,
  description='Turkoman horse archers or halqa',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f017",
}
g_str_5fb1ba3be1af06001770f01b='5fb1ba3be1af06001770f01b'
g_base_definitions[g_str_5fb1ba3be1af06001770f01b]={
  id=g_str_5fb1ba3be1af06001770f01b,
  name='Bow Levy',
  min=0,
  max=2,
  description='Deteriorated halqa',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3be1af06001770f019",
}
g_str_5fb1ba3be1af06001770f01d='5fb1ba3be1af06001770f01d'
g_base_definitions[g_str_5fb1ba3be1af06001770f01d]={
  id=g_str_5fb1ba3be1af06001770f01d,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Bedouin, Kurdish, Syrian, or Ashir horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3be1af06001770f01c",
}
g_str_5fb1ba3be1af06001770f01f='5fb1ba3be1af06001770f01f'
g_base_definitions[g_str_5fb1ba3be1af06001770f01f]={
  id=g_str_5fb1ba3be1af06001770f01f,
  name='Bow Levy',
  min=0,
  max=2,
  description='Ashir bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3be1af06001770f01e",
}
g_str_5fb1ba3be1af06001770f021='5fb1ba3be1af06001770f021'
g_base_definitions[g_str_5fb1ba3be1af06001770f021]={
  id=g_str_5fb1ba3be1af06001770f021,
  name='Light Foot',
  min=0,
  max=2,
  description='Jabaliyya or other javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3be1af06001770f020",
}
g_str_5fb1ba3be1af06001770f022='5fb1ba3be1af06001770f022'
g_base_definitions[g_str_5fb1ba3be1af06001770f022]={
  id=g_str_5fb1ba3be1af06001770f022,
  name='Rabble',
  min=0,
  max=2,
  description='Jabaliyya or other javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba3be1af06001770f020",
}
g_str_5fb1ba3be1af06001770f024='5fb1ba3be1af06001770f024'
g_base_definitions[g_str_5fb1ba3be1af06001770f024]={
  id=g_str_5fb1ba3be1af06001770f024,
  name='Skirmishers',
  min=0,
  max=1,
  description='Naffatun',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3be1af06001770f023",
}
g_str_5fb1ba3be1af06001770f026='5fb1ba3be1af06001770f026'
g_base_definitions[g_str_5fb1ba3be1af06001770f026]={
  id=g_str_5fb1ba3be1af06001770f026,
  name='Warband',
  min=0,
  max=1,
  description='Ghazis',
  troop_type="Warband",
  troop_option_id="5fb1ba3be1af06001770f025",
}
g_str_5fb1ba3be1af06001770f028='5fb1ba3be1af06001770f028'
g_base_definitions[g_str_5fb1ba3be1af06001770f028]={
  id=g_str_5fb1ba3be1af06001770f028,
  name='Horde',
  min=0,
  max=1,
  description='City rabble and \'abid',
  troop_type="Horde",
  troop_option_id="5fb1ba3be1af06001770f027",
}
g_str_5fb1ba3be1af06001770f02a='5fb1ba3be1af06001770f02a'
g_base_definitions[g_str_5fb1ba3be1af06001770f02a]={
  id=g_str_5fb1ba3be1af06001770f02a,
  name='Artillery',
  min=0,
  max=1,
  description='Rope-pull stone throwers',
  troop_type="Artillery",
  troop_option_id="5fb1ba3be1af06001770f029",
}
g_str_5fb1b9eee1af06001770a004_camp='5fb1b9eee1af06001770a004_camp'
g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp]={
  id=g_str_5fb1b9eee1af06001770a004_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9eee1af06001770a004_camp_pack_train='5fb1b9eee1af06001770a004_camp_pack_train'
g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp_pack_train]={
  id=g_str_5fb1b9eee1af06001770a004_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9eee1af06001770a004']={
  data={
    name='Mamluk Egyptian  1250 to 1517 AD'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770f015_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f015],
  g_base_definitions[g_str_5fb1ba3be1af06001770f018],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01b],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01d],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01f],
  g_base_definitions[g_str_5fb1ba3be1af06001770f021],
  g_base_definitions[g_str_5fb1ba3be1af06001770f022],
  g_base_definitions[g_str_5fb1ba3be1af06001770f024],
  g_base_definitions[g_str_5fb1ba3be1af06001770f026],
  g_base_definitions[g_str_5fb1ba3be1af06001770f028],
  g_base_definitions[g_str_5fb1ba3be1af06001770f02a],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af06001770a004"] = army["5fb1b9eee1af06001770a004"]
army['5fb1b9eee1af06001770a004_1250_1315']={
  data={
    name='Mamluk Egyptian 1250 AD to 1315 AD'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770f015_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f015],
  g_base_definitions[g_str_5fb1ba3be1af06001770f018],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01d],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01f],
  g_base_definitions[g_str_5fb1ba3be1af06001770f021],
  g_base_definitions[g_str_5fb1ba3be1af06001770f022],
  g_base_definitions[g_str_5fb1ba3be1af06001770f024],
  g_base_definitions[g_str_5fb1ba3be1af06001770f026],
  g_base_definitions[g_str_5fb1ba3be1af06001770f028],
  g_base_definitions[g_str_5fb1ba3be1af06001770f02a],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp_pack_train],
}
army['5fb1b9eee1af06001770a004_1316_1517']={
  data={
    name='Mamluk Egyptian 1316 AD to 1517 AD'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770f015_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f015],
  g_base_definitions[g_str_5fb1ba3be1af06001770f018],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01b],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01d],
  g_base_definitions[g_str_5fb1ba3be1af06001770f01f],
  g_base_definitions[g_str_5fb1ba3be1af06001770f021],
  g_base_definitions[g_str_5fb1ba3be1af06001770f022],
  g_base_definitions[g_str_5fb1ba3be1af06001770f024],
  g_base_definitions[g_str_5fb1ba3be1af06001770f026],
  g_base_definitions[g_str_5fb1ba3be1af06001770f028],
  g_base_definitions[g_str_5fb1ba3be1af06001770f02a],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp_pack_train],
}
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Mamluk Egyptian  1250 to 1517 AD"] = army["5fb1b9eee1af06001770a004"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Mamluk Egyptian  1250 to 1517 AD"] = army["5fb1b9eee1af06001770a004"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mamluk Egyptian  1250 to 1517 AD"] = army["5fb1b9eee1af06001770a004"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af06001770a004"] = {}
army_dates["5fb1b9eee1af06001770a004"]["1250 AD to 1517 AD"] ="5fb1b9eee1af06001770a004"
army_dates["5fb1b9eee1af06001770a004"]["1250 AD to 1315 AD"] ="5fb1b9eee1af06001770a004_1250_1315"
army_dates["5fb1b9eee1af06001770a004"]["1316 AD to 1517 AD"] ="5fb1b9eee1af06001770a004_1316_1517"
