-- 5fb1b9eae1af060017709df3 Post Mongol Russian  1246 to 1533 AD

army['5fb1b9eae1af060017709df3']={
  data={
    name='Post Mongol Russian  1246 to 1533 AD',
    id='5fb1b9eae1af060017709df3',
    dateRange={
      startDate=1246,
      endDate=1533,
    }
  },
  g_base_definitions[g_str_5fb1ba37e1af06001770e766_general],
  g_base_definitions[g_str_5fb1ba37e1af06001770e766],
  g_base_definitions[g_str_5fb1ba37e1af06001770e768],
  g_base_definitions[g_str_5fb1ba37e1af06001770e76a],
  g_base_definitions[g_str_5fb1ba37e1af06001770e76c],
  g_base_definitions[g_str_5fb1ba37e1af06001770e76e],
  g_base_definitions[g_str_5fb1ba37e1af06001770e771],
  g_base_definitions[g_str_5fb1ba37e1af06001770e774],
  g_base_definitions[g_str_5fb1b9eae1af060017709df3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709df3"] = army["5fb1b9eae1af060017709df3"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Post Mongol Russian  1246 to 1533 AD"] = army["5fb1b9eae1af060017709df3"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Post Mongol Russian  1246 to 1533 AD"] = army["5fb1b9eae1af060017709df3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Post Mongol Russian  1246 to 1533 AD"] = army["5fb1b9eae1af060017709df3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709df3"] = {}
army_dates["5fb1b9eae1af060017709df3"]["1246 AD to 1533 AD"] = {
  startDate=1246,
  endDate=1533
}
army_dates["5fb1b9eae1af060017709df3"]["1246 AD to 1379 AD"] = {
  startDate=1246,
  endDate=1533
}
army_dates["5fb1b9eae1af060017709df3"]["1380 AD to 1533 AD"] = {
  startDate=1246,
  endDate=1533
}
