-- 5fb1b9ece1af060017709ec2 Nobatae or Ballana  30 BC to 550 AD

army['5fb1b9ece1af060017709ec2']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Nobatae or Ballana  30 BC to 550 AD',
    id='5fb1b9ece1af060017709ec2',
    dateRange={
      startDate=-30,
      endDate=550,
    }
  },
  g_base_definitions[g_str_5fb1ba39e1af06001770eacd_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770eacd],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead0_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead0],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead3_general],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead3],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead5],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead7],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770ead9_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc],
  g_base_definitions[g_str_5fb1ba39e1af06001770eadc_light_camelry],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709ec2"] = army["5fb1b9ece1af060017709ec2"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Nobatae or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Nobatae or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Nobatae or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709ec2"] = {}
army_dates["5fb1b9ece1af060017709ec2"]["30 BC to 550 AD"] = {
  startDate=-30,
  endDate=550
}
army_dates["5fb1b9ece1af060017709ec2"]["30 BC to 500 AD"] = {
  startDate=-30,
  endDate=500
}
army_dates["5fb1b9ece1af060017709ec2"]["501 AD to 550 AD"] = {
  startDate=501,
  endDate=550
}
