-- 5fb1b9f1e1af06001770a1ba Former Qin  351 to 394 AD

army['5fb1b9f1e1af06001770a1ba']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
      'Hilly',
      'Arable',
    },
    name='Former Qin  351 to 394 AD',
    id='5fb1b9f1e1af06001770a1ba',
    dateRange={
      startDate=351,
      endDate=394,
    }
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f656_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f656],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f658_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f658],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65a_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65f],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f661],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f664],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f665],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f668],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f66c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f66d],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_fortified],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1ba"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1ba"] = {}
army_dates["5fb1b9f1e1af06001770a1ba"]["351 AD to 394 AD"] = {
  startDate=351,
  endDate=394
}
army_dates["5fb1b9f1e1af06001770a1ba"]["351 AD to 382 AD"] = {
  startDate=351,
  endDate=382
}
army_dates["5fb1b9f1e1af06001770a1ba"]["383 AD"] = {
  startDate=383,
  endDate=383
}
army_dates["5fb1b9f1e1af06001770a1ba"]["384 AD to 394 AD"] = {
  startDate=384,
  endDate=394
}
-- 5fb1b9f1e1af06001770a1ba Former Qin  351 to 394 AD

army['5fb1b9f1e1af06001770a1ba']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
      'Hilly',
      'Arable',
    },
    name='Former Qin  351 to 394 AD',
    id='5fb1b9f1e1af06001770a1ba',
    dateRange={
      startDate=351,
      endDate=394,
    }
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f656_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f656],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f658_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f658],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65a_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65f],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f661],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f664],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f665],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f668],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f66c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f66d],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_fortified],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1ba"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1ba"] = {}
army_dates["5fb1b9f1e1af06001770a1ba"]["351 AD to 394 AD"] = {
  startDate=351,
  endDate=394
}
army_dates["5fb1b9f1e1af06001770a1ba"]["351 AD to 382 AD"] = {
  startDate=351,
  endDate=382
}
army_dates["5fb1b9f1e1af06001770a1ba"]["383 AD"] = {
  startDate=383,
  endDate=383
}
army_dates["5fb1b9f1e1af06001770a1ba"]["384 AD to 394 AD"] = {
  startDate=384,
  endDate=394
}
-- 5fb1b9f1e1af06001770a1ba Former Qin  351 to 394 AD

army['5fb1b9f1e1af06001770a1ba']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
      'Hilly',
      'Arable',
    },
    name='Former Qin  351 to 394 AD',
    id='5fb1b9f1e1af06001770a1ba',
    dateRange={
      startDate=351,
      endDate=394,
    }
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f656_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f656],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f658_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f658],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65a_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f65f],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f661],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f664],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f665],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f668],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f66c],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f66d],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_fortified],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1ba"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1ba"] = {}
army_dates["5fb1b9f1e1af06001770a1ba"]["351 AD to 394 AD"] = {
  startDate=351,
  endDate=394
}
army_dates["5fb1b9f1e1af06001770a1ba"]["351 AD to 382 AD"] = {
  startDate=351,
  endDate=382
}
army_dates["5fb1b9f1e1af06001770a1ba"]["383 AD"] = {
  startDate=383,
  endDate=383
}
army_dates["5fb1b9f1e1af06001770a1ba"]["384 AD to 394 AD"] = {
  startDate=384,
  endDate=394
}
