-- 5fb1b9eae1af060017709dca Medieval Danish and Union of Kalmar  1350 to 1523 AD

army['5fb1b9eae1af060017709dca']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Marsh',
      'Arable',
      'Forest',
      'Marsh',
    },
    name='Medieval Danish and Union of Kalmar  1350 to 1523 AD',
    id='5fb1b9eae1af060017709dca',
    dateRange={
      startDate=1350,
      endDate=1523,
    }
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bd],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bf],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c5],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dca"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dca"] = {}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1523 AD"] = {
  startDate=1350,
  endDate=1523
}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1375 AD"] = {
  startDate=1350,
  endDate=1375
}
army_dates["5fb1b9eae1af060017709dca"]["1376 AD to 1390 AD"] = {
  startDate=1376,
  endDate=1390
}
army_dates["5fb1b9eae1af060017709dca"]["1391 AD to 1425 AD"] = {
  startDate=1391,
  endDate=1425
}
army_dates["5fb1b9eae1af060017709dca"]["1426 AD to 1439 AD"] = {
  startDate=1426,
  endDate=1439
}
army_dates["5fb1b9eae1af060017709dca"]["1440 AD to 1449 AD"] = {
  startDate=1440,
  endDate=1449
}
army_dates["5fb1b9eae1af060017709dca"]["1450 AD to 1462 AD"] = {
  startDate=1450,
  endDate=1462
}
army_dates["5fb1b9eae1af060017709dca"]["1463 AD to 1493 AD"] = {
  startDate=1463,
  endDate=1493
}
army_dates["5fb1b9eae1af060017709dca"]["1494 AD to 1518 AD"] = {
  startDate=1494,
  endDate=1518
}
army_dates["5fb1b9eae1af060017709dca"]["1519 AD to 1523 AD"] = {
  startDate=1519,
  endDate=1523
}
-- 5fb1b9eae1af060017709dca Medieval Danish and Union of Kalmar  1350 to 1523 AD

army['5fb1b9eae1af060017709dca']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Marsh',
      'Arable',
      'Forest',
      'Marsh',
    },
    name='Medieval Danish and Union of Kalmar  1350 to 1523 AD',
    id='5fb1b9eae1af060017709dca',
    dateRange={
      startDate=1350,
      endDate=1523,
    }
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bd],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bf],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c5],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dca"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dca"] = {}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1523 AD"] = {
  startDate=1350,
  endDate=1523
}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1375 AD"] = {
  startDate=1350,
  endDate=1375
}
army_dates["5fb1b9eae1af060017709dca"]["1376 AD to 1390 AD"] = {
  startDate=1376,
  endDate=1390
}
army_dates["5fb1b9eae1af060017709dca"]["1391 AD to 1425 AD"] = {
  startDate=1391,
  endDate=1425
}
army_dates["5fb1b9eae1af060017709dca"]["1426 AD to 1439 AD"] = {
  startDate=1426,
  endDate=1439
}
army_dates["5fb1b9eae1af060017709dca"]["1440 AD to 1449 AD"] = {
  startDate=1440,
  endDate=1449
}
army_dates["5fb1b9eae1af060017709dca"]["1450 AD to 1462 AD"] = {
  startDate=1450,
  endDate=1462
}
army_dates["5fb1b9eae1af060017709dca"]["1463 AD to 1493 AD"] = {
  startDate=1463,
  endDate=1493
}
army_dates["5fb1b9eae1af060017709dca"]["1494 AD to 1518 AD"] = {
  startDate=1494,
  endDate=1518
}
army_dates["5fb1b9eae1af060017709dca"]["1519 AD to 1523 AD"] = {
  startDate=1519,
  endDate=1523
}
-- 5fb1b9eae1af060017709dca Medieval Danish and Union of Kalmar  1350 to 1523 AD

army['5fb1b9eae1af060017709dca']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Marsh',
      'Arable',
      'Forest',
      'Marsh',
    },
    name='Medieval Danish and Union of Kalmar  1350 to 1523 AD',
    id='5fb1b9eae1af060017709dca',
    dateRange={
      startDate=1350,
      endDate=1523,
    }
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bd],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bf],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c5],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dca"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dca"] = {}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1523 AD"] = {
  startDate=1350,
  endDate=1523
}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1375 AD"] = {
  startDate=1350,
  endDate=1375
}
army_dates["5fb1b9eae1af060017709dca"]["1376 AD to 1390 AD"] = {
  startDate=1376,
  endDate=1390
}
army_dates["5fb1b9eae1af060017709dca"]["1391 AD to 1425 AD"] = {
  startDate=1391,
  endDate=1425
}
army_dates["5fb1b9eae1af060017709dca"]["1426 AD to 1439 AD"] = {
  startDate=1426,
  endDate=1439
}
army_dates["5fb1b9eae1af060017709dca"]["1440 AD to 1449 AD"] = {
  startDate=1440,
  endDate=1449
}
army_dates["5fb1b9eae1af060017709dca"]["1450 AD to 1462 AD"] = {
  startDate=1450,
  endDate=1462
}
army_dates["5fb1b9eae1af060017709dca"]["1463 AD to 1493 AD"] = {
  startDate=1463,
  endDate=1493
}
army_dates["5fb1b9eae1af060017709dca"]["1494 AD to 1518 AD"] = {
  startDate=1494,
  endDate=1518
}
army_dates["5fb1b9eae1af060017709dca"]["1519 AD to 1523 AD"] = {
  startDate=1519,
  endDate=1523
}
