troop_options['615351b003385c0016b87dde'] = {
  min=4,
  max=8,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87de2'] = {
  min=2,
  max=4,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87de7'] = {
  min=0,
  max=2,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87dea'] = {
  min=0,
  max=1,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87dec'] = {
  min=0,
  max=4,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87df0'] = {
  min=0,
  max=1,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87df3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87df5'] = {
  min=0,
  max=1,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['615351b003385c0016b87df8'] = {
  min=0,
  max=2,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
-- allies
