-- 5fb1b9eee1af060017709ffb Anatolian Turkoman  1260 to 1515 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba3be1af06001770eff3']= {
  min=0,
  max=1,
  description='Nobles with horse armor',
  core='all',
}
g_troop_entry['5fb1ba3be1af06001770eff4']= {
  troop_option='5fb1ba3be1af06001770eff3',
  troopTypeCode='ECV',
}
g_troop_option['5fb1ba3be1af06001770eff5']= {
  min=1,
  max=2,
  description='Noble horse archers',
}
g_troop_entry['5fb1ba3be1af06001770eff6']= {
  troop_option='5fb1ba3be1af06001770eff5',
  troopTypeCode='HBW',
}
g_troop_option['5fb1ba3be1af06001770eff7']= {
  min=3,
  max=8,
  description='Tribal horse archers',
}
g_troop_entry['5fb1ba3be1af06001770eff8']= {
  troop_option='5fb1ba3be1af06001770eff7',
  troopTypeCode='HBW',
}
g_troop_option['5fb1ba3be1af06001770eff9']= {
  min=0,
  max=2,
  description='Infantry spearmen',
}
g_troop_entry['5fb1ba3be1af06001770effa']= {
  troop_option='5fb1ba3be1af06001770eff9',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba3be1af06001770effb']= {
  min=0,
  max=2,
  description='Superior bowmen',
  core='all',
}
g_troop_entry['5fb1ba3be1af06001770effc']= {
  troop_option='5fb1ba3be1af06001770effb',
  troopTypeCode='ARC',
}
g_troop_option['5fb1ba3be1af06001770effd']= {
  min=0,
  max=6,
  description='Poorly equipped and trained bowmen',
  core='all',
}
g_troop_entry['5fb1ba3be1af06001770effe']= {
  troop_option='5fb1ba3be1af06001770effd',
  troopTypeCode='BLV',
}
g_troop_option['5fb1ba3be1af06001770efff']= {
  min=0,
  max=1,
  description='Town militia',
  core='all',
}
g_troop_entry['5fb1ba3be1af06001770f000']= {
  troop_option='5fb1ba3be1af06001770efff',
  troopTypeCode='HRD',
}
g_troop_option['5fb1ba3be1af06001770f001']= {
  min=0,
  max=1,
  description='Heavy and light guns',
  startDate=1381,
  endDate=1515,
}
g_troop_entry['5fb1ba3be1af06001770f003']= {
  troop_option='5fb1ba3be1af06001770f001',
  troopTypeCode='ART',
}
g_str_5fb1ba3be1af06001770eff4_general='5fb1ba3be1af06001770eff4_general'
g_base_definitions[g_str_5fb1ba3be1af06001770eff4_general]={
  id=g_str_5fb1ba3be1af06001770eff4_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Nobles with horse armor',
  general=true,
  troop_type="Elite Cavalary",
}
g_str_5fb1ba3be1af06001770eff4='5fb1ba3be1af06001770eff4'
g_base_definitions[g_str_5fb1ba3be1af06001770eff4]={
  id=g_str_5fb1ba3be1af06001770eff4,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Nobles with horse armor',
  troop_type="Elite Cavalary",
}
g_str_5fb1ba3be1af06001770eff6_general='5fb1ba3be1af06001770eff6_general'
g_base_definitions[g_str_5fb1ba3be1af06001770eff6_general]={
  id=g_str_5fb1ba3be1af06001770eff6_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Noble horse archers',
  general=true,
  troop_type="Horse Bow",
}
g_str_5fb1ba3be1af06001770eff6='5fb1ba3be1af06001770eff6'
g_base_definitions[g_str_5fb1ba3be1af06001770eff6]={
  id=g_str_5fb1ba3be1af06001770eff6,
  name='Horse Bow',
  min=1,
  max=2,
  description='Noble horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba3be1af06001770eff8_general='5fb1ba3be1af06001770eff8_general'
g_base_definitions[g_str_5fb1ba3be1af06001770eff8_general]={
  id=g_str_5fb1ba3be1af06001770eff8_general,
  name='Horse Bow General',
  min=3,
  max=1,
  description='Tribal horse archers',
  general=true,
  troop_type="Horse Bow",
}
g_str_5fb1ba3be1af06001770eff8='5fb1ba3be1af06001770eff8'
g_base_definitions[g_str_5fb1ba3be1af06001770eff8]={
  id=g_str_5fb1ba3be1af06001770eff8,
  name='Horse Bow',
  min=3,
  max=8,
  description='Tribal horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba3be1af06001770effa='5fb1ba3be1af06001770effa'
g_base_definitions[g_str_5fb1ba3be1af06001770effa]={
  id=g_str_5fb1ba3be1af06001770effa,
  name='Light Foot',
  min=0,
  max=2,
  description='Infantry spearmen',
  troop_type="Light Foot",
}
g_str_5fb1ba3be1af06001770effc='5fb1ba3be1af06001770effc'
g_base_definitions[g_str_5fb1ba3be1af06001770effc]={
  id=g_str_5fb1ba3be1af06001770effc,
  name='Archers',
  min=0,
  max=2,
  description='Superior bowmen',
  troop_type="Archers",
}
g_str_5fb1ba3be1af06001770effe='5fb1ba3be1af06001770effe'
g_base_definitions[g_str_5fb1ba3be1af06001770effe]={
  id=g_str_5fb1ba3be1af06001770effe,
  name='Bow Levy',
  min=0,
  max=6,
  description='Poorly equipped and trained bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba3be1af06001770f000='5fb1ba3be1af06001770f000'
g_base_definitions[g_str_5fb1ba3be1af06001770f000]={
  id=g_str_5fb1ba3be1af06001770f000,
  name='Horde',
  min=0,
  max=1,
  description='Town militia',
  troop_type="Horde",
}
g_str_5fb1ba3be1af06001770f003='5fb1ba3be1af06001770f003'
g_base_definitions[g_str_5fb1ba3be1af06001770f003]={
  id=g_str_5fb1ba3be1af06001770f003,
  name='Artillery',
  min=0,
  max=1,
  description='Heavy and light guns',
  troop_type="Artillery",
}
g_str_5fb1b9eee1af060017709ffb_camp='5fb1b9eee1af060017709ffb_camp'
g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp]={
  id=g_str_5fb1b9eee1af060017709ffb_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9eee1af060017709ffb_camp_pack_train='5fb1b9eee1af060017709ffb_camp_pack_train'
g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp_pack_train]={
  id=g_str_5fb1b9eee1af060017709ffb_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9eee1af060017709ffb']={
  data={
    name='Anatolian Turkoman  1260 to 1515 AD',
    id='5fb1b9eee1af060017709ffb',
    army_id='5fb1b9eee1af060017709ffb'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770eff4_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff4],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff6_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff6],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff8_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff8],
  g_base_definitions[g_str_5fb1ba3be1af06001770effa],
  g_base_definitions[g_str_5fb1ba3be1af06001770effc],
  g_base_definitions[g_str_5fb1ba3be1af06001770effe],
  g_base_definitions[g_str_5fb1ba3be1af06001770f000],
  g_base_definitions[g_str_5fb1ba3be1af06001770f003],
  g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp],
  g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af060017709ffb"] = army["5fb1b9eee1af060017709ffb"]
army['5fb1b9eee1af060017709ffb_1260_1380']={
  data={
    name='Anatolian Turkoman 1260 AD to 1380 AD',
    id='5fb1b9eee1af060017709ffb_1260_1380',
    army_id='5fb1b9eee1af060017709ffb'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770eff4_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff4],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff6_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff6],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff8_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff8],
  g_base_definitions[g_str_5fb1ba3be1af06001770effa],
  g_base_definitions[g_str_5fb1ba3be1af06001770effc],
  g_base_definitions[g_str_5fb1ba3be1af06001770effe],
  g_base_definitions[g_str_5fb1ba3be1af06001770f000],
  g_base_definitions[g_str_5fb1ba3be1af06001770f003],
  g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp],
  g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp_pack_train],
}
army['5fb1b9eee1af060017709ffb_1381_1515']={
  data={
    name='Anatolian Turkoman 1381 AD to 1515 AD',
    id='5fb1b9eee1af060017709ffb_1381_1515',
    army_id='5fb1b9eee1af060017709ffb'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770eff4_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff4],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff6_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff6],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff8_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770eff8],
  g_base_definitions[g_str_5fb1ba3be1af06001770effa],
  g_base_definitions[g_str_5fb1ba3be1af06001770effc],
  g_base_definitions[g_str_5fb1ba3be1af06001770effe],
  g_base_definitions[g_str_5fb1ba3be1af06001770f000],
  g_base_definitions[g_str_5fb1ba3be1af06001770f003],
  g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp],
  g_base_definitions[g_str_5fb1b9eee1af060017709ffb_camp_pack_train],
}
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Anatolian Turkoman  1260 to 1515 AD"] = army["5fb1b9eee1af060017709ffb"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Anatolian Turkoman  1260 to 1515 AD"] = army["5fb1b9eee1af060017709ffb"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Anatolian Turkoman  1260 to 1515 AD"] = army["5fb1b9eee1af060017709ffb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Anatolian Turkoman  1260 to 1515 AD"] = army["5fb1b9eee1af060017709ffb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af060017709ffb"] = {}
army_dates["5fb1b9eee1af060017709ffb"]["1260 AD to 1515 AD"] ="5fb1b9eee1af060017709ffb"
army_dates["5fb1b9eee1af060017709ffb"]["1260 AD to 1380 AD"] ="5fb1b9eee1af060017709ffb_1260_1380"
army_dates["5fb1b9eee1af060017709ffb"]["1381 AD to 1515 AD"] ="5fb1b9eee1af060017709ffb_1381_1515"
