-- 5fb1b9dfe1af0600177096f4 Sarmatian Tribes  310 BC to 375 AD

army['5fb1b9dfe1af0600177096f4']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Steppe',
    },
    name='Sarmatian Tribes  310 BC to 375 AD',
    id='5fb1b9dfe1af0600177096f4',
    dateRange={
      startDate=-310,
      endDate=375,
    },
  },
  g_base_definitions[g_str_615351a403385c0016b85e39_general],
  g_base_definitions[g_str_615351a403385c0016b85e39],
  g_base_definitions[g_str_615351a403385c0016b85e3b],
  g_base_definitions[g_str_615351a403385c0016b85e3d],
  g_base_definitions[g_str_615351a403385c0016b85e3f],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096f4_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af0600177096f4"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Sarmatian Tribes  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Sarmatian Tribes  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Sarmatian Tribes  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sarmatian Tribes  310 BC to 375 AD"] = army["5fb1b9dfe1af0600177096f4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af0600177096f4"] = {}
army_dates["5fb1b9dfe1af0600177096f4"]["310 BC to 375 AD"] = {
  startDate=-310,
  endDate=375
}
army_dates["5fb1b9dfe1af0600177096f4"]["310 BC to 116 BC"] = {
  startDate=-310,
  endDate=-116
}
army_dates["5fb1b9dfe1af0600177096f4"]["115 BC to 49 AD"] = {
  startDate=-115,
  endDate=49
}
army_dates["5fb1b9dfe1af0600177096f4"]["50 AD to 99 AD"] = {
  startDate=50,
  endDate=99
}
army_dates["5fb1b9dfe1af0600177096f4"]["100 AD to 199 AD"] = {
  startDate=100,
  endDate=199
}
army_dates["5fb1b9dfe1af0600177096f4"]["200 AD to 250 AD"] = {
  startDate=200,
  endDate=250
}
army_dates["5fb1b9dfe1af0600177096f4"]["251 AD to 357 AD"] = {
  startDate=251,
  endDate=357
}
army_dates["5fb1b9dfe1af0600177096f4"]["358 AD"] = {
  startDate=358,
  endDate=358
}
army_dates["5fb1b9dfe1af0600177096f4"]["359 AD to 372 AD"] = {
  startDate=359,
  endDate=372
}
army_dates["5fb1b9dfe1af0600177096f4"]["373 AD to 375 AD"] = {
  startDate=373,
  endDate=375
}
