troop_options['5fb1ba2de1af06001770d583'] = {
  min=0,
  max=1,
  dateRange={
    startDate=250,
    endDate=584,
  }
}
troop_options['5fb1ba2de1af06001770d586'] = {
  min=12,
  max=16,
  dateRange={
    startDate=250,
    endDate=584,
  }
}
troop_options['5fb1ba2de1af06001770d588'] = {
  min=0,
  max=2,
  dateRange={
    startDate=250,
    endDate=584,
  }
}
troop_options['5fb1ba2de1af06001770d58a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=250,
    endDate=584,
  }
}
-- allies
