-- 5fb1b9dce1af06001770956c Hannibal in Italy  218 to 203 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba26e1af06001770c7ea_general='5fb1ba26e1af06001770c7ea_general'
g_base_definitions[g_str_5fb1ba26e1af06001770c7ea_general]={
  id=g_str_5fb1ba26e1af06001770c7ea_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Gallic, Poeni, Libyan, or Numidian horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba26e1af06001770c7ea='5fb1ba26e1af06001770c7ea'
g_base_definitions[g_str_5fb1ba26e1af06001770c7ea]={
  id=g_str_5fb1ba26e1af06001770c7ea,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Gallic, Poeni, Libyan, or Numidian horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba26e1af06001770c7ed='5fb1ba26e1af06001770c7ed'
g_base_definitions[g_str_5fb1ba26e1af06001770c7ed]={
  id=g_str_5fb1ba26e1af06001770c7ed,
  name='Heavy Foot',
  min=2,
  max=4,
  description='Libyan heavy infantry armed with spears',
  troop_type="Heavy Foot",
}
g_str_5fb1ba26e1af06001770c7f0='5fb1ba26e1af06001770c7f0'
g_base_definitions[g_str_5fb1ba26e1af06001770c7f0]={
  id=g_str_5fb1ba26e1af06001770c7f0,
  name='Elite Foot',
  min=2,
  max=4,
  description='Veteran Libyan spearmen using captured Roman equipment',
  troop_type="Elite Foot",
}
g_str_5fb1ba26e1af06001770c7f3='5fb1ba26e1af06001770c7f3'
g_base_definitions[g_str_5fb1ba26e1af06001770c7f3]={
  id=g_str_5fb1ba26e1af06001770c7f3,
  name='Light Foot',
  min=1,
  max=2,
  description='Libyan, Moorish or Numidian javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba26e1af06001770c7f6='5fb1ba26e1af06001770c7f6'
g_base_definitions[g_str_5fb1ba26e1af06001770c7f6]={
  id=g_str_5fb1ba26e1af06001770c7f6,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt-shooters',
  troop_type="Artillery",
}
g_str_5fb1ba26e1af06001770c7f8='5fb1ba26e1af06001770c7f8'
g_base_definitions[g_str_5fb1ba26e1af06001770c7f8]={
  id=g_str_5fb1ba26e1af06001770c7f8,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Greek mercenary hoplites',
  troop_type="Heavy Foot",
}
g_str_5fb1ba26e1af06001770c7fb='5fb1ba26e1af06001770c7fb'
g_base_definitions[g_str_5fb1ba26e1af06001770c7fb]={
  id=g_str_5fb1ba26e1af06001770c7fb,
  name='Light Foot',
  min=0,
  max=1,
  description='Campanian or other Italian mercenary light infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba26e1af06001770c7fd='5fb1ba26e1af06001770c7fd'
g_base_definitions[g_str_5fb1ba26e1af06001770c7fd]={
  id=g_str_5fb1ba26e1af06001770c7fd,
  name='Raiders',
  min=0,
  max=3,
  description='Spanish mercenary infantry',
  troop_type="Raiders",
}
g_str_5fb1ba26e1af06001770c7ff='5fb1ba26e1af06001770c7ff'
g_base_definitions[g_str_5fb1ba26e1af06001770c7ff]={
  id=g_str_5fb1ba26e1af06001770c7ff,
  name='Skirmishers',
  min=0,
  max=1,
  description='Balearic slingers',
  troop_type="Skirmishers",
}
g_str_5fb1ba26e1af06001770c801='5fb1ba26e1af06001770c801'
g_base_definitions[g_str_5fb1ba26e1af06001770c801]={
  id=g_str_5fb1ba26e1af06001770c801,
  name='Elephants',
  min=0,
  max=1,
  description='African elephants',
  troop_type="Elephants",
}
g_str_5fb1ba26e1af06001770c804='5fb1ba26e1af06001770c804'
g_base_definitions[g_str_5fb1ba26e1af06001770c804]={
  id=g_str_5fb1ba26e1af06001770c804,
  name='Warriors',
  min=2,
  max=6,
  description='Gallic tribesmen fighting in native style',
  troop_type="Warriors",
}
g_str_5fb1ba26e1af06001770c807='5fb1ba26e1af06001770c807'
g_base_definitions[g_str_5fb1ba26e1af06001770c807]={
  id=g_str_5fb1ba26e1af06001770c807,
  name='Raiders',
  min=2,
  max=6,
  description='Retrained Gallic infantry',
  troop_type="Raiders",
}
g_str_5fb1ba26e1af06001770c809='5fb1ba26e1af06001770c809'
g_base_definitions[g_str_5fb1ba26e1af06001770c809]={
  id=g_str_5fb1ba26e1af06001770c809,
  name='Light Foot',
  min=0,
  max=2,
  description='Ligurian light infantry',
  troop_type="Light Foot",
}
g_str_5fb1b9dce1af06001770956c_camp='5fb1b9dce1af06001770956c_camp'
g_base_definitions[g_str_5fb1b9dce1af06001770956c_camp]={
  name='Camp',
  id=g_str_5fb1b9dce1af06001770956c_camp,
  min=1,
  max=1,
}
army['5fb1b9dce1af06001770956c']={
  data={
    name='Hannibal in Italy  218 to 203 BC'
  },
  g_base_definitions[g_str_5fb1b9dce1af06001770956c_camp],
  g_base_definitions[g_str_5fb1ba26e1af06001770c80b],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7ea_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7ea],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7ed],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7f0],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7f3],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7f6],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7f8],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7fb],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7fd],
  g_base_definitions[g_str_5fb1ba26e1af06001770c7ff],
  g_base_definitions[g_str_5fb1ba26e1af06001770c801],
  g_base_definitions[g_str_5fb1ba26e1af06001770c804],
  g_base_definitions[g_str_5fb1ba26e1af06001770c807],
  g_base_definitions[g_str_5fb1ba26e1af06001770c809],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af06001770956c"] = army["5fb1b9dce1af06001770956c"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Hannibal in Italy  218 to 203 BC"] = army["5fb1b9dce1af06001770956c"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Hannibal in Italy  218 to 203 BC"] = army["5fb1b9dce1af06001770956c"]
