-- 5fb1b9e2e1af0600177098c1 Visigoths under Alaric and Successors  408 to 419 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba2ce1af06001770d43f_general='5fb1ba2ce1af06001770d43f_general'
g_base_definitions[g_str_5fb1ba2ce1af06001770d43f_general]={
  id=g_str_5fb1ba2ce1af06001770d43f_general,
  name='Knights General',
  min=3,
  max=1,
  description='Noble horsemen and Greuthingi horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba2ce1af06001770d43e",
}
g_str_5fb1ba2ce1af06001770d43f='5fb1ba2ce1af06001770d43f'
g_base_definitions[g_str_5fb1ba2ce1af06001770d43f]={
  id=g_str_5fb1ba2ce1af06001770d43f,
  name='Knights',
  min=3,
  max=7,
  description='Noble horsemen and Greuthingi horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba2ce1af06001770d43e",
}
g_str_5fb1ba2ce1af06001770d441='5fb1ba2ce1af06001770d441'
g_base_definitions[g_str_5fb1ba2ce1af06001770d441]={
  id=g_str_5fb1ba2ce1af06001770d441,
  name='Warriors',
  min=6,
  max=12,
  description='Fierce fighting infantry',
  troop_type="Warriors",
  troop_option_id="5fb1ba2ce1af06001770d440",
}
g_str_5fb1ba2ce1af06001770d443='5fb1ba2ce1af06001770d443'
g_base_definitions[g_str_5fb1ba2ce1af06001770d443]={
  id=g_str_5fb1ba2ce1af06001770d443,
  name='Bow Levy',
  min=0,
  max=1,
  description='Close-order bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba2ce1af06001770d442",
}
g_str_5fb1ba2ce1af06001770d445='5fb1ba2ce1af06001770d445'
g_base_definitions[g_str_5fb1ba2ce1af06001770d445]={
  id=g_str_5fb1ba2ce1af06001770d445,
  name='Skirmishers',
  min=0,
  max=4,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2ce1af06001770d444",
}
g_str_5fb1ba2ce1af06001770d447='5fb1ba2ce1af06001770d447'
g_base_definitions[g_str_5fb1ba2ce1af06001770d447]={
  id=g_str_5fb1ba2ce1af06001770d447,
  name='Horde',
  min=0,
  max=4,
  description='Throngs of former slaves',
  troop_type="Horde",
  troop_option_id="5fb1ba2ce1af06001770d446",
}
g_str_5fb1b9e2e1af0600177098c1_camp='5fb1b9e2e1af0600177098c1_camp'
g_base_definitions[g_str_5fb1b9e2e1af0600177098c1_camp]={
  id=g_str_5fb1b9e2e1af0600177098c1_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af0600177098c1_camp_fortified='5fb1b9e2e1af0600177098c1_camp_fortified'
g_base_definitions[g_str_5fb1b9e2e1af0600177098c1_camp_fortified]={
  id=g_str_5fb1b9e2e1af0600177098c1_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e2e1af0600177098c1']={
  data={
    name='Visigoths under Alaric and Successors  408 to 419 AD'
  },
  g_base_definitions[g_str_5fb1ba2ce1af06001770d43f_general],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d43f],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d441],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d443],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d445],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d447],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098c1_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098c1_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098c1"] = army["5fb1b9e2e1af0600177098c1"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Visigoths under Alaric and Successors  408 to 419 AD"] = army["5fb1b9e2e1af0600177098c1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098c1"] = {}
army_dates["5fb1b9e2e1af0600177098c1"]["408 AD to 419 AD"] ="5fb1b9e2e1af0600177098c1"
