-- 5fb1b9e3e1af0600177099bf Aquitanian (from 511 AD) or Neustrian (from 561 AD) Frankish  511 to 639 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ee1af06001770d7bf_general='5fb1ba2ee1af06001770d7bf_general'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_general]={
  id=g_str_5fb1ba2ee1af06001770d7bf_general,
  name='Knights General',
  min=1,
  max=1,
  description='Frankish noble horsemen',
  general=true,
}
g_str_5fb1ba2ee1af06001770d7bf_general_dismounted='5fb1ba2ee1af06001770d7bf_general_dismounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_general_dismounted]={
  id=g_str_5fb1ba2ee1af06001770d7bf_general_dismounted,
  name='Warrior General',
  min=1,
  max=1,
  description='Frankish noble horsemen\nDeployment dismounted from Knights General',
  points=4,
  general=true,
}
g_5fb1ba2ee1af06001770d7bf_general_dismounted=g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_general_dismounted]
g_str_5fb1ba2ee1af06001770d7bf_general_mounted='5fb1ba2ee1af06001770d7bf_general_mounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_general_mounted]={
  id=g_str_5fb1ba2ee1af06001770d7bf_general_mounted,
  name='Knights General',
  min=1,
  max=1,
  description='Frankish noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2ee1af06001770d7bf_general_dismounted,
  general=true,
}
g_str_5fb1ba2ee1af06001770d7bf='5fb1ba2ee1af06001770d7bf'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf]={
  id=g_str_5fb1ba2ee1af06001770d7bf,
  name='Knights',
  min=1,
  max=3,
  description='Frankish noble horsemen',
}
g_str_5fb1ba2ee1af06001770d7bf_dismounted='5fb1ba2ee1af06001770d7bf_dismounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_dismounted]={
  id=g_str_5fb1ba2ee1af06001770d7bf_dismounted,
  name='Warrior',
  min=1,
  max=3,
  description='Frankish noble horsemen\nDeployment dismounted from Knights',
  points=4,
}
g_5fb1ba2ee1af06001770d7bf_dismounted=g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_dismounted]
g_str_5fb1ba2ee1af06001770d7bf_mounted='5fb1ba2ee1af06001770d7bf_mounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_mounted]={
  id=g_str_5fb1ba2ee1af06001770d7bf_mounted,
  name='Knights',
  min=1,
  max=3,
  description='Frankish noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2ee1af06001770d7bf_dismounted,
}
g_str_5fb1ba2ee1af06001770d7c2_general='5fb1ba2ee1af06001770d7c2_general'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_general]={
  id=g_str_5fb1ba2ee1af06001770d7c2_general,
  name='Knights General',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen',
  general=true,
}
g_str_5fb1ba2ee1af06001770d7c2_general_dismounted='5fb1ba2ee1af06001770d7c2_general_dismounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_general_dismounted]={
  id=g_str_5fb1ba2ee1af06001770d7c2_general_dismounted,
  name='Warrior General',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen\nDeployment dismounted from Knights General',
  points=4,
  general=true,
}
g_5fb1ba2ee1af06001770d7c2_general_dismounted=g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_general_dismounted]
g_str_5fb1ba2ee1af06001770d7c2_general_mounted='5fb1ba2ee1af06001770d7c2_general_mounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_general_mounted]={
  id=g_str_5fb1ba2ee1af06001770d7c2_general_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2ee1af06001770d7c2_general_dismounted,
  general=true,
}
g_str_5fb1ba2ee1af06001770d7c2='5fb1ba2ee1af06001770d7c2'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2]={
  id=g_str_5fb1ba2ee1af06001770d7c2,
  name='Knights',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen',
}
g_str_5fb1ba2ee1af06001770d7c2_dismounted='5fb1ba2ee1af06001770d7c2_dismounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_dismounted]={
  id=g_str_5fb1ba2ee1af06001770d7c2_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen\nDeployment dismounted from Knights',
  points=4,
}
g_5fb1ba2ee1af06001770d7c2_dismounted=g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_dismounted]
g_str_5fb1ba2ee1af06001770d7c2_mounted='5fb1ba2ee1af06001770d7c2_mounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_mounted]={
  id=g_str_5fb1ba2ee1af06001770d7c2_mounted,
  name='Knights',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2ee1af06001770d7c2_dismounted,
}
g_str_5fb1ba2ee1af06001770d7c3='5fb1ba2ee1af06001770d7c3'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c3]={
  id=g_str_5fb1ba2ee1af06001770d7c3,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen',
}
g_str_5fb1ba2ee1af06001770d7c3_dismounted='5fb1ba2ee1af06001770d7c3_dismounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c3_dismounted]={
  id=g_str_5fb1ba2ee1af06001770d7c3_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
}
g_5fb1ba2ee1af06001770d7c3_dismounted=g_base_definitions[g_str_5fb1ba2ee1af06001770d7c3_dismounted]
g_str_5fb1ba2ee1af06001770d7c3_mounted='5fb1ba2ee1af06001770d7c3_mounted'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c3_mounted]={
  id=g_str_5fb1ba2ee1af06001770d7c3_mounted,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Gallo-Roman noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2ee1af06001770d7c3_dismounted,
}
g_str_5fb1ba2ee1af06001770d7c6='5fb1ba2ee1af06001770d7c6'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c6]={
  id=g_str_5fb1ba2ee1af06001770d7c6,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Breton, Alan, and Basque horsemen',
}
g_str_5fb1ba2ee1af06001770d7c8='5fb1ba2ee1af06001770d7c8'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7c8]={
  id=g_str_5fb1ba2ee1af06001770d7c8,
  name='Heavy Foot',
  min=5,
  max=11,
  description='Gallo-Roman infantry',
}
g_str_5fb1ba2ee1af06001770d7ca='5fb1ba2ee1af06001770d7ca'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7ca]={
  id=g_str_5fb1ba2ee1af06001770d7ca,
  name='Warriors',
  min=0,
  max=6,
  description='Saxons',
}
g_str_5fb1ba2ee1af06001770d7cc='5fb1ba2ee1af06001770d7cc'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7cc]={
  id=g_str_5fb1ba2ee1af06001770d7cc,
  name='Warriors',
  min=0,
  max=2,
  description='Tribal fierce infantry',
}
g_str_5fb1ba2ee1af06001770d7ce='5fb1ba2ee1af06001770d7ce'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7ce]={
  id=g_str_5fb1ba2ee1af06001770d7ce,
  name='Skirmishers',
  min=0,
  max=1,
  description='Tribal skirmishing bowmen',
}
g_str_5fb1ba2ee1af06001770d7d0='5fb1ba2ee1af06001770d7d0'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7d0]={
  id=g_str_5fb1ba2ee1af06001770d7d0,
  name='Light Foot',
  min=0,
  max=2,
  description='Basque javelinmen or skirmishing slingers',
}
g_str_5fb1ba2ee1af06001770d7d1='5fb1ba2ee1af06001770d7d1'
g_base_definitions[g_str_5fb1ba2ee1af06001770d7d1]={
  id=g_str_5fb1ba2ee1af06001770d7d1,
  name='Skirmishers',
  min=0,
  max=2,
  description='Basque javelinmen or skirmishing slingers',
}
g_str_5fb1b9e3e1af0600177099bf_camp='5fb1b9e3e1af0600177099bf_camp'
g_base_definitions[g_str_5fb1b9e3e1af0600177099bf_camp]={
  name='Camp',
  id=g_str_5fb1b9e3e1af0600177099bf_camp,
  min=1,
  max=1,
}
army['5fb1b9e3e1af0600177099bf']={
  data={
    name='Aquitanian (from 511 AD) or Neustrian (from 561 AD) Frankish  511 to 639 AD'
  },
  g_base_definitions[g_str_5fb1b9e3e1af0600177099bf_camp],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7d3],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_general_mounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_general_dismounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_mounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7bf_dismounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_general_mounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_general_dismounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_mounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c2_dismounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c3],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c3_mounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c3_dismounted],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c6],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7c8],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7ca],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7cc],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7ce],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7d0],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d7d1],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af0600177099bf"] = army["5fb1b9e3e1af0600177099bf"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Aquitanian (from 511 AD) or Neustrian (from 561 AD) Frankish  511 to 639 AD"] = army["5fb1b9e3e1af0600177099bf"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Aquitanian (from 511 AD) or Neustrian (from 561 AD) Frankish  511 to 639 AD"] = army["5fb1b9e3e1af0600177099bf"]
