-- 5fb1b9f1e1af06001770a1d0 Southern Xiongnu  304 to 439 AD

army['5fb1b9f1e1af06001770a1d0']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Steppe',
    },
    name='Southern Xiongnu  304 to 439 AD',
    id='5fb1b9f1e1af06001770a1d0',
    dateRange={
      startDate=304,
      endDate=439,
    },
  },
  g_base_definitions[g_str_615351b303385c0016b88715_general],
  g_base_definitions[g_str_615351b303385c0016b88715],
  g_base_definitions[g_str_615351b303385c0016b88716_general],
  g_base_definitions[g_str_615351b303385c0016b88716],
  g_base_definitions[g_str_615351b303385c0016b88718],
  g_base_definitions[g_str_615351b303385c0016b8871a],
  g_base_definitions[g_str_615351b303385c0016b8871c],
  g_base_definitions[g_str_615351b303385c0016b8871d],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1d0_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1d0_camp_pack_train],
  g_base_definitions[g_str_6153519b03385c0016b849d4],
  g_base_definitions[g_str_6153519b03385c0016b849d6],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1d0"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Southern Xiongnu  304 to 439 AD"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Southern Xiongnu  304 to 439 AD"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Southern Xiongnu  304 to 439 AD"] = army["5fb1b9f1e1af06001770a1d0"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1d0"] = {}
army_dates["5fb1b9f1e1af06001770a1d0"]["304 AD to 439 AD"] = {
  startDate=304,
  endDate=439
}
