troop_options['5fb1ba3ae1af06001770ed5b'] = {
  min=4,
  max=8,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['5fb1ba3ae1af06001770ed5f'] = {
  min=2,
  max=4,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['5fb1ba3ae1af06001770ed64'] = {
  min=0,
  max=2,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['5fb1ba3ae1af06001770ed67'] = {
  min=0,
  max=1,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['5fb1ba3ae1af06001770ed69'] = {
  min=0,
  max=4,
  dateRange={
    startDate=946,
    endDate=1059,
  }
}
troop_options['5fb1ba3ae1af06001770ed6d'] = {
  min=0,
  max=1,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['5fb1ba3ae1af06001770ed70'] = {
  min=0,
  max=1,
  dateRange={
    startDate=927,
    endDate=1090,
  }
}
troop_options['5fb1ba3ae1af06001770ed72'] = {
  min=0,
  max=1,
  dateRange={
    startDate=946,
    endDate=1059,
  }
}
troop_options['5fb1ba3ae1af06001770ed75'] = {
  min=0,
  max=2,
  dateRange={
    startDate=946,
    endDate=1059,
  }
}
-- allies
