-- 5fb1b9d9e1af060017709313 Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba1fe1af06001770bf01']= {
  min=0,
  max=1,
  description='2-horse chariots',
  core='all',
}
g_troop_entry['5fb1ba1fe1af06001770bf02']= {
  troop_option='5fb1ba1fe1af06001770bf01',
  troopTypeCode='CHT',
}
g_troop_option['5fb1ba1fe1af06001770bf03']= {
  min=1,
  max=2,
  description='Bodyguards',
  core='all',
}
g_troop_entry['5fb1ba1fe1af06001770bf04']= {
  troop_option='5fb1ba1fe1af06001770bf03',
  troopTypeCode='RDR',
}
g_troop_entry['5fb1ba1fe1af06001770bf05']= {
  troop_option='5fb1ba1fe1af06001770bf03',
  troopTypeCode='ARC',
}
g_troop_option['5fb1ba1fe1af06001770bf06']= {
  min=6,
  max=18,
  description='Unshielded javelinmen',
}
g_troop_entry['5fb1ba1fe1af06001770bf07']= {
  troop_option='5fb1ba1fe1af06001770bf06',
  troopTypeCode='RBL',
}
g_troop_option['5fb1ba1fe1af06001770bf08']= {
  min=0,
  max=3,
  description='Javelinmen with shields',
  core='all',
  startDate=-1500,
  endDate=-950,
}
g_troop_entry['5fb1ba1fe1af06001770bf0a']= {
  troop_option='5fb1ba1fe1af06001770bf08',
  troopTypeCode='LFT',
}
g_troop_option['5fb1ba1fe1af06001770bf0b']= {
  min=4,
  max=12,
  description='Bowmen',
}
g_troop_entry['5fb1ba1fe1af06001770bf0c']= {
  troop_option='5fb1ba1fe1af06001770bf0b',
  troopTypeCode='BLV',
}
g_troop_option['5fb1ba1fe1af06001770bf0d']= {
  min=0,
  max=4,
  description='Slingers',
}
g_troop_entry['5fb1ba1fe1af06001770bf0e']= {
  troop_option='5fb1ba1fe1af06001770bf0d',
  troopTypeCode='SKM',
}
g_str_5fb1ba1fe1af06001770bf02_general='5fb1ba1fe1af06001770bf02_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf02_general]={
  id=g_str_5fb1ba1fe1af06001770bf02_general,
  name='Chariots General',
  min=0,
  max=1,
  description='2-horse chariots',
  general=true,
  troop_type="Chariots",
}
g_str_5fb1ba1fe1af06001770bf02='5fb1ba1fe1af06001770bf02'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf02]={
  id=g_str_5fb1ba1fe1af06001770bf02,
  name='Chariots',
  min=0,
  max=1,
  description='2-horse chariots',
  troop_type="Chariots",
}
g_str_5fb1ba1fe1af06001770bf04_general='5fb1ba1fe1af06001770bf04_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf04_general]={
  id=g_str_5fb1ba1fe1af06001770bf04_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Bodyguards',
  general=true,
  troop_type="Raiders",
}
g_str_5fb1ba1fe1af06001770bf04='5fb1ba1fe1af06001770bf04'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf04]={
  id=g_str_5fb1ba1fe1af06001770bf04,
  name='Raiders',
  min=1,
  max=2,
  description='Bodyguards',
  troop_type="Raiders",
}
g_str_5fb1ba1fe1af06001770bf05_general='5fb1ba1fe1af06001770bf05_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf05_general]={
  id=g_str_5fb1ba1fe1af06001770bf05_general,
  name='Archers General',
  min=1,
  max=1,
  description='Bodyguards',
  general=true,
  troop_type="Archers",
}
g_str_5fb1ba1fe1af06001770bf05='5fb1ba1fe1af06001770bf05'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf05]={
  id=g_str_5fb1ba1fe1af06001770bf05,
  name='Archers',
  min=1,
  max=2,
  description='Bodyguards',
  troop_type="Archers",
}
g_str_5fb1ba1fe1af06001770bf07='5fb1ba1fe1af06001770bf07'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf07]={
  id=g_str_5fb1ba1fe1af06001770bf07,
  name='Rabble',
  min=6,
  max=18,
  description='Unshielded javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba1fe1af06001770bf0a='5fb1ba1fe1af06001770bf0a'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf0a]={
  id=g_str_5fb1ba1fe1af06001770bf0a,
  name='Light Foot',
  min=0,
  max=3,
  description='Javelinmen with shields',
  troop_type="Light Foot",
}
g_str_5fb1ba1fe1af06001770bf0c='5fb1ba1fe1af06001770bf0c'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf0c]={
  id=g_str_5fb1ba1fe1af06001770bf0c,
  name='Bow Levy',
  min=4,
  max=12,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba1fe1af06001770bf0e='5fb1ba1fe1af06001770bf0e'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf0e]={
  id=g_str_5fb1ba1fe1af06001770bf0e,
  name='Skirmishers',
  min=0,
  max=4,
  description='Slingers',
  troop_type="Skirmishers",
}
g_str_5fb1b9d9e1af060017709313_camp='5fb1b9d9e1af060017709313_camp'
g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp]={
  id=g_str_5fb1b9d9e1af060017709313_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d9e1af060017709313_camp_pack_train='5fb1b9d9e1af060017709313_camp_pack_train'
g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp_pack_train]={
  id=g_str_5fb1b9d9e1af060017709313_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9d9e1af060017709313']={
  data={
    name='Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC',
    id='5fb1b9d9e1af060017709313',
    army_id='5fb1b9d9e1af060017709313'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf07],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0a],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0e],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709313"] = army["5fb1b9d9e1af060017709313"]
army['5fb1b9d9e1af060017709313_-1749_-1501']={
  data={
    name='Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC 1749 BC to 1501 BC',
    id='5fb1b9d9e1af060017709313_-1749_-1501',
    army_id='5fb1b9d9e1af060017709313'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf07],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0a],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0e],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp_pack_train],
}
army['5fb1b9d9e1af060017709313_-1500_-950']={
  data={
    name='Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC 1500 BC to 950 BC',
    id='5fb1b9d9e1af060017709313_-1500_-950',
    army_id='5fb1b9d9e1af060017709313'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf07],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0a],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0e],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp_pack_train],
}
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709313"] = {}
army_dates["5fb1b9d9e1af060017709313"]["1749 BC to 950 BC"] ="5fb1b9d9e1af060017709313"
army_dates["5fb1b9d9e1af060017709313"]["1749 BC to 1501 BC"] ="5fb1b9d9e1af060017709313_-1749_-1501"
army_dates["5fb1b9d9e1af060017709313"]["1500 BC to 950 BC"] ="5fb1b9d9e1af060017709313_-1500_-950"
