-- 5fb1b9ebe1af060017709e5a Komnenan Byzantine  1071 to 1142 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba38e1af06001770e8ed_general='5fb1ba38e1af06001770e8ed_general'
g_base_definitions[g_str_5fb1ba38e1af06001770e8ed_general]={
  id=g_str_5fb1ba38e1af06001770e8ed_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Kavallarioi',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8eb",
}
g_str_5fb1ba38e1af06001770e8ed='5fb1ba38e1af06001770e8ed'
g_base_definitions[g_str_5fb1ba38e1af06001770e8ed]={
  id=g_str_5fb1ba38e1af06001770e8ed,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Kavallarioi',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8eb",
}
g_str_5fb1ba38e1af06001770e8f0_general='5fb1ba38e1af06001770e8f0_general'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f0_general]={
  id=g_str_5fb1ba38e1af06001770e8f0_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Kavallarioi',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8ee",
}
g_str_5fb1ba38e1af06001770e8f0='5fb1ba38e1af06001770e8f0'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f0]={
  id=g_str_5fb1ba38e1af06001770e8f0,
  name='Elite Cavalary',
  min=1,
  max=1,
  description='Kavallarioi',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8ee",
}
g_str_5fb1ba38e1af06001770e8f3_general='5fb1ba38e1af06001770e8f3_general'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f3_general]={
  id=g_str_5fb1ba38e1af06001770e8f3_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Kavallarioi possibly detached as cursores',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8f1",
}
g_str_5fb1ba38e1af06001770e8f3='5fb1ba38e1af06001770e8f3'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f3]={
  id=g_str_5fb1ba38e1af06001770e8f3,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Kavallarioi possibly detached as cursores',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8f1",
}
g_str_5fb1ba38e1af06001770e8f4='5fb1ba38e1af06001770e8f4'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f4]={
  id=g_str_5fb1ba38e1af06001770e8f4,
  name='Horse Bow',
  min=0,
  max=1,
  description='Kavallarioi possibly detached as cursores',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba38e1af06001770e8f1",
}
g_str_5fb1ba38e1af06001770e8f6_general='5fb1ba38e1af06001770e8f6_general'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general]={
  id=g_str_5fb1ba38e1af06001770e8f6_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Kavallarioi, some poorly trained',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8f5",
}
g_str_5fb1ba38e1af06001770e8f6='5fb1ba38e1af06001770e8f6'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f6]={
  id=g_str_5fb1ba38e1af06001770e8f6,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Kavallarioi, some poorly trained',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba38e1af06001770e8f5",
}
g_str_5fb1ba38e1af06001770e8f7='5fb1ba38e1af06001770e8f7'
g_base_definitions[g_str_5fb1ba38e1af06001770e8f7]={
  id=g_str_5fb1ba38e1af06001770e8f7,
  name='Bad Horse',
  min=1,
  max=2,
  description='Kavallarioi, some poorly trained',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba38e1af06001770e8f5",
}
g_str_5fb1ba38e1af06001770e8fa='5fb1ba38e1af06001770e8fa'
g_base_definitions[g_str_5fb1ba38e1af06001770e8fa]={
  id=g_str_5fb1ba38e1af06001770e8fa,
  name='Elite Foot',
  min=0,
  max=1,
  description='Varangian guard',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba38e1af06001770e8f8",
}
g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry='5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry'
g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry='5fb1ba38e1af06001770e8fa_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry]={
  id=g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry,
  name='Elite Foot',
  min=0,
  max=1,
  description='Varangian guard\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba38e1af06001770e8f8",
}
g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry]={
  id=g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry,
  name='Elite Foot',
  min=0,
  max=1,
  description='Varangian guard\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba38e1af06001770e8f8",
}
g_str_5fb1ba38e1af06001770e8fe='5fb1ba38e1af06001770e8fe'
g_base_definitions[g_str_5fb1ba38e1af06001770e8fe]={
  id=g_str_5fb1ba38e1af06001770e8fe,
  name='Knights',
  min=0,
  max=2,
  description='Latinikon',
  troop_type="Knights",
  troop_option_id="5fb1ba38e1af06001770e8fd",
}
g_str_5fb1ba38e1af06001770e901='5fb1ba38e1af06001770e901'
g_base_definitions[g_str_5fb1ba38e1af06001770e901]={
  id=g_str_5fb1ba38e1af06001770e901,
  name='Horse Bow',
  min=0,
  max=1,
  description='Patzinak mercenaries',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba38e1af06001770e8ff",
}
g_str_5fb1ba38e1af06001770e904='5fb1ba38e1af06001770e904'
g_base_definitions[g_str_5fb1ba38e1af06001770e904]={
  id=g_str_5fb1ba38e1af06001770e904,
  name='Horse Bow',
  min=2,
  max=4,
  description='Skythikon and Vardariatoi',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba38e1af06001770e902",
}
g_str_5fb1ba38e1af06001770e906='5fb1ba38e1af06001770e906'
g_base_definitions[g_str_5fb1ba38e1af06001770e906]={
  id=g_str_5fb1ba38e1af06001770e906,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Kontaratoi',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba38e1af06001770e905",
}
g_str_5fb1ba38e1af06001770e906_plaustrella='5fb1ba38e1af06001770e906_plaustrella'
g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella]={
  id=g_str_5fb1ba38e1af06001770e906_plaustrella,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Kontaratoi\nPlaustrella',
  plaustrella=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba38e1af06001770e905",
}
g_str_5fb1ba38e1af06001770e909='5fb1ba38e1af06001770e909'
g_base_definitions[g_str_5fb1ba38e1af06001770e909]={
  id=g_str_5fb1ba38e1af06001770e909,
  name='Skirmishers',
  min=0,
  max=1,
  description='Psiloi armed with bow or sling',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba38e1af06001770e908",
}
g_str_5fb1ba38e1af06001770e90b='5fb1ba38e1af06001770e90b'
g_base_definitions[g_str_5fb1ba38e1af06001770e90b]={
  id=g_str_5fb1ba38e1af06001770e90b,
  name='Bow Levy',
  min=2,
  max=4,
  description='Poorly trained bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba38e1af06001770e90a",
}
g_str_5fb1ba38e1af06001770e90d='5fb1ba38e1af06001770e90d'
g_base_definitions[g_str_5fb1ba38e1af06001770e90d]={
  id=g_str_5fb1ba38e1af06001770e90d,
  name='Archers',
  min=0,
  max=1,
  description='Better trained and equipped bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba38e1af06001770e90c",
}
g_str_5fb1ba38e1af06001770e90f='5fb1ba38e1af06001770e90f'
g_base_definitions[g_str_5fb1ba38e1af06001770e90f]={
  id=g_str_5fb1ba38e1af06001770e90f,
  name='Horse Bow',
  min=0,
  max=1,
  description='Manichaean horsemen',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba38e1af06001770e90e",
}
g_str_5fb1ba38e1af06001770e911='5fb1ba38e1af06001770e911'
g_base_definitions[g_str_5fb1ba38e1af06001770e911]={
  id=g_str_5fb1ba38e1af06001770e911,
  name='Archers',
  min=0,
  max=2,
  description='Manichaean bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba38e1af06001770e910",
}
g_str_5fb1ba38e1af06001770e913='5fb1ba38e1af06001770e913'
g_base_definitions[g_str_5fb1ba38e1af06001770e913]={
  id=g_str_5fb1ba38e1af06001770e913,
  name='Light Foot',
  min=0,
  max=3,
  description='Serb, Vlach, or similar highlanders',
  troop_type="Light Foot",
  troop_option_id="5fb1ba38e1af06001770e912",
}
g_str_5fb1b9ebe1af060017709e5a_camp='5fb1b9ebe1af060017709e5a_camp'
g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp]={
  id=g_str_5fb1b9ebe1af060017709e5a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9ebe1af060017709e5a']={
  data={
    name='Komnenan Byzantine  1071 to 1142 AD'
  },
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f4],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fe],
  g_base_definitions[g_str_5fb1ba38e1af06001770e901],
  g_base_definitions[g_str_5fb1ba38e1af06001770e904],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella],
  g_base_definitions[g_str_5fb1ba38e1af06001770e909],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90b],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90d],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90f],
  g_base_definitions[g_str_5fb1ba38e1af06001770e911],
  g_base_definitions[g_str_5fb1ba38e1af06001770e913],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ebe1af060017709e5a"] = army["5fb1b9ebe1af060017709e5a"]
army['5fb1b9ebe1af060017709e5a_1071_1077']={
  data={
    name='Komnenan Byzantine 1071 AD to 1077 AD'
  },
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fe],
  g_base_definitions[g_str_5fb1ba38e1af06001770e901],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella],
  g_base_definitions[g_str_5fb1ba38e1af06001770e909],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90b],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90d],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90f],
  g_base_definitions[g_str_5fb1ba38e1af06001770e911],
  g_base_definitions[g_str_5fb1ba38e1af06001770e913],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp],
}
army['5fb1b9ebe1af060017709e5a_1078_1082']={
  data={
    name='Komnenan Byzantine 1078 AD to 1082 AD'
  },
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f4],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fe],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella],
  g_base_definitions[g_str_5fb1ba38e1af06001770e909],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90b],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90d],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90f],
  g_base_definitions[g_str_5fb1ba38e1af06001770e911],
  g_base_definitions[g_str_5fb1ba38e1af06001770e913],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp],
}
army['5fb1b9ebe1af060017709e5a_1083_1091']={
  data={
    name='Komnenan Byzantine 1083 AD to 1091 AD'
  },
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fe],
  g_base_definitions[g_str_5fb1ba38e1af06001770e901],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella],
  g_base_definitions[g_str_5fb1ba38e1af06001770e909],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90b],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90d],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90f],
  g_base_definitions[g_str_5fb1ba38e1af06001770e911],
  g_base_definitions[g_str_5fb1ba38e1af06001770e913],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp],
}
army['5fb1b9ebe1af060017709e5a_1092_1116']={
  data={
    name='Komnenan Byzantine 1092 AD to 1116 AD'
  },
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f4],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fe],
  g_base_definitions[g_str_5fb1ba38e1af06001770e904],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella],
  g_base_definitions[g_str_5fb1ba38e1af06001770e909],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90b],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90d],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90f],
  g_base_definitions[g_str_5fb1ba38e1af06001770e911],
  g_base_definitions[g_str_5fb1ba38e1af06001770e913],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp],
}
army['5fb1b9ebe1af060017709e5a_1117_1142']={
  data={
    name='Komnenan Byzantine 1117 AD to 1142 AD'
  },
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fe],
  g_base_definitions[g_str_5fb1ba38e1af06001770e904],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella],
  g_base_definitions[g_str_5fb1ba38e1af06001770e909],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90b],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90d],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90f],
  g_base_definitions[g_str_5fb1ba38e1af06001770e911],
  g_base_definitions[g_str_5fb1ba38e1af06001770e913],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp],
}
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Komnenan Byzantine  1071 to 1142 AD"] = army["5fb1b9ebe1af060017709e5a"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Komnenan Byzantine  1071 to 1142 AD"] = army["5fb1b9ebe1af060017709e5a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ebe1af060017709e5a"] = {}
army_dates["5fb1b9ebe1af060017709e5a"]["1071 AD to 1142 AD"] ="5fb1b9ebe1af060017709e5a"
army_dates["5fb1b9ebe1af060017709e5a"]["1071 AD to 1077 AD"] ="5fb1b9ebe1af060017709e5a_1071_1077"
army_dates["5fb1b9ebe1af060017709e5a"]["1078 AD to 1082 AD"] ="5fb1b9ebe1af060017709e5a_1078_1082"
army_dates["5fb1b9ebe1af060017709e5a"]["1083 AD to 1091 AD"] ="5fb1b9ebe1af060017709e5a_1083_1091"
army_dates["5fb1b9ebe1af060017709e5a"]["1092 AD to 1116 AD"] ="5fb1b9ebe1af060017709e5a_1092_1116"
army_dates["5fb1b9ebe1af060017709e5a"]["1117 AD to 1142 AD"] ="5fb1b9ebe1af060017709e5a_1117_1142"
