g_str_5fb1ba2fe1af06001770d95f_general='5fb1ba2fe1af06001770d95f_general'
g_base_definitions[g_str_5fb1ba2fe1af06001770d95f_general]={
  id=g_str_5fb1ba2fe1af06001770d95f_general,
  name='Javelin Cavalry General',
  min=5,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2fe1af06001770d95e",
}
g_str_5fb1ba2fe1af06001770d95f='5fb1ba2fe1af06001770d95f'
g_base_definitions[g_str_5fb1ba2fe1af06001770d95f]={
  id=g_str_5fb1ba2fe1af06001770d95f,
  name='Javelin Cavalry',
  min=5,
  max=9,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2fe1af06001770d95e",
}
g_str_5fb1ba2fe1af06001770d961='5fb1ba2fe1af06001770d961'
g_base_definitions[g_str_5fb1ba2fe1af06001770d961]={
  id=g_str_5fb1ba2fe1af06001770d961,
  name='Light Foot',
  min=0,
  max=3,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2fe1af06001770d960",
}
g_str_5fb1ba2fe1af06001770d963='5fb1ba2fe1af06001770d963'
g_base_definitions[g_str_5fb1ba2fe1af06001770d963]={
  id=g_str_5fb1ba2fe1af06001770d963,
  name='Horde',
  min=0,
  max=3,
  description='Peasants',
  troop_type="Horde",
  troop_option_id="5fb1ba2fe1af06001770d962",
}
g_str_5fb1ba2fe1af06001770d966_general='5fb1ba2fe1af06001770d966_general'
g_base_definitions[g_str_5fb1ba2fe1af06001770d966_general]={
  id=g_str_5fb1ba2fe1af06001770d966_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Unarmored horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2fe1af06001770d964",
}
g_str_5fb1ba2fe1af06001770d966='5fb1ba2fe1af06001770d966'
g_base_definitions[g_str_5fb1ba2fe1af06001770d966]={
  id=g_str_5fb1ba2fe1af06001770d966,
  name='Javelin Cavalry',
  min=1,
  max=4,
  description='Unarmored horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2fe1af06001770d964",
}
g_str_5fb1ba2fe1af06001770d969='5fb1ba2fe1af06001770d969'
g_base_definitions[g_str_5fb1ba2fe1af06001770d969]={
  id=g_str_5fb1ba2fe1af06001770d969,
  name='Warriors',
  min=0,
  max=1,
  description='Disguised Saxons {see battle card -- based as Horde}',
  troop_type="Warriors",
  troop_option_id="5fb1ba2fe1af06001770d967",
}
g_str_5fb1b9e4e1af060017709a4c_camp='5fb1b9e4e1af060017709a4c_camp'
g_base_definitions[g_str_5fb1b9e4e1af060017709a4c_camp]={
  id=g_str_5fb1b9e4e1af060017709a4c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e4e1af060017709a4c_camp_fortified='5fb1b9e4e1af060017709a4c_camp_fortified'
g_base_definitions[g_str_5fb1b9e4e1af060017709a4c_camp_fortified]={
  id=g_str_5fb1b9e4e1af060017709a4c_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
