-- 5fb1b9f4e1af06001770a319 Early Kofun Japanese  275 to 500 AD

army['5fb1b9f4e1af06001770a319']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Kofun Japanese  275 to 500 AD',
    id='5fb1b9f4e1af06001770a319',
    dateRange={
      startDate=275,
      endDate=500,
    },
  },
  g_base_definitions[g_str_615351b503385c0016b88c0a_general],
  g_base_definitions[g_str_615351b503385c0016b88c0a],
  g_base_definitions[g_str_615351b503385c0016b88c0c],
  g_base_definitions[g_str_615351b503385c0016b88c0d],
  g_base_definitions[g_str_615351b503385c0016b88c0f],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a319_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a319"] = army["5fb1b9f4e1af06001770a319"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Early Kofun Japanese  275 to 500 AD"] = army["5fb1b9f4e1af06001770a319"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Kofun Japanese  275 to 500 AD"] = army["5fb1b9f4e1af06001770a319"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a319"] = {}
army_dates["5fb1b9f4e1af06001770a319"]["275 AD to 500 AD"] = {
  startDate=275,
  endDate=500
}
army_dates["5fb1b9f4e1af06001770a319"]["275 AD to 299 AD"] = {
  startDate=275,
  endDate=299
}
army_dates["5fb1b9f4e1af06001770a319"]["300 AD to 359 AD"] = {
  startDate=300,
  endDate=359
}
army_dates["5fb1b9f4e1af06001770a319"]["360 AD to 500 AD"] = {
  startDate=360,
  endDate=500
}
