-- 5fb1b9eae1af060017709dd4 Medieval Swedish  1391 to 1523 AD

army['5fb1b9eae1af060017709dd4']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Forest',
    },
    name='Medieval Swedish  1391 to 1523 AD',
    id='5fb1b9eae1af060017709dd4',
    dateRange={
      startDate=1391,
      endDate=1523,
    },
  },
  g_base_definitions[g_str_615351ae03385c0016b87753_general],
  g_base_definitions[g_str_615351ae03385c0016b87753_general_mounted],
  g_base_definitions[g_str_615351ae03385c0016b87753_general_dismounted],
  g_base_definitions[g_str_615351ae03385c0016b87753],
  g_base_definitions[g_str_615351ae03385c0016b87753_mounted],
  g_base_definitions[g_str_615351ae03385c0016b87753_dismounted],
  g_base_definitions[g_str_615351ae03385c0016b87756_general],
  g_base_definitions[g_str_615351ae03385c0016b87756],
  g_base_definitions[g_str_615351ae03385c0016b87758_general],
  g_base_definitions[g_str_615351ae03385c0016b87758],
  g_base_definitions[g_str_615351ae03385c0016b8775b],
  g_base_definitions[g_str_615351ae03385c0016b8775e],
  g_base_definitions[g_str_615351ae03385c0016b87760],
  g_base_definitions[g_str_5fb1b9eae1af060017709dd4_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709dd4_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dd4"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Swedish  1391 to 1523 AD"] = army["5fb1b9eae1af060017709dd4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dd4"] = {}
army_dates["5fb1b9eae1af060017709dd4"]["1391 AD to 1523 AD"] = {
  startDate=1391,
  endDate=1523
}
