-- 5fb1b9efe1af06001770a089 Arab Indian  751 to 1206 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3de1af06001770f274='5fb1ba3de1af06001770f274'
g_base_definitions[g_str_5fb1ba3de1af06001770f274]={
  id=g_str_5fb1ba3de1af06001770f274,
  name='Javelin Cavalry General',
  min=2,
  max=1,
  description='Arab horsemen',
}
g_str_5fb1ba3de1af06001770f274='5fb1ba3de1af06001770f274'
g_base_definitions[g_str_5fb1ba3de1af06001770f274]={
  id=g_str_5fb1ba3de1af06001770f274,
  name='Javelin Cavalry',
  min=2,
  max=3,
  description='Arab horsemen',
}
g_str_5fb1ba3de1af06001770f277='5fb1ba3de1af06001770f277'
g_base_definitions[g_str_5fb1ba3de1af06001770f277]={
  id=g_str_5fb1ba3de1af06001770f277,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Khurasanian-style horsemen, or (after 900) ghulams',
}
g_str_5fb1ba3de1af06001770f277='5fb1ba3de1af06001770f277'
g_base_definitions[g_str_5fb1ba3de1af06001770f277]={
  id=g_str_5fb1ba3de1af06001770f277,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Khurasanian-style horsemen, or (after 900) ghulams',
}
g_str_5fb1ba3de1af06001770f27a='5fb1ba3de1af06001770f27a'
g_base_definitions[g_str_5fb1ba3de1af06001770f27a]={
  id=g_str_5fb1ba3de1af06001770f27a,
  name='Bad Horse',
  min=1,
  max=3,
  description='Sindi horsemen',
}
g_str_5fb1ba3de1af06001770f27c='5fb1ba3de1af06001770f27c'
g_base_definitions[g_str_5fb1ba3de1af06001770f27c]={
  id=g_str_5fb1ba3de1af06001770f27c,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Arab spearmen',
}
g_str_5fb1ba3de1af06001770f27f='5fb1ba3de1af06001770f27f'
g_base_definitions[g_str_5fb1ba3de1af06001770f27f]={
  id=g_str_5fb1ba3de1af06001770f27f,
  name='Skirmishers',
  min=1,
  max=3,
  description='Arab bowmen',
}
g_str_5fb1ba3de1af06001770f280='5fb1ba3de1af06001770f280'
g_base_definitions[g_str_5fb1ba3de1af06001770f280]={
  id=g_str_5fb1ba3de1af06001770f280,
  name='Archers',
  min=1,
  max=3,
  description='Arab bowmen',
}
g_str_5fb1ba3de1af06001770f283='5fb1ba3de1af06001770f283'
g_base_definitions[g_str_5fb1ba3de1af06001770f283]={
  id=g_str_5fb1ba3de1af06001770f283,
  name='Raiders',
  min=0,
  max=2,
  description='Hindu swordsmen',
}
g_str_5fb1ba3de1af06001770f285='5fb1ba3de1af06001770f285'
g_base_definitions[g_str_5fb1ba3de1af06001770f285]={
  id=g_str_5fb1ba3de1af06001770f285,
  name='Light Foot',
  min=0,
  max=2,
  description='Hindu javelinmen',
}
g_str_5fb1ba3de1af06001770f287='5fb1ba3de1af06001770f287'
g_base_definitions[g_str_5fb1ba3de1af06001770f287]={
  id=g_str_5fb1ba3de1af06001770f287,
  name='Bow Levy',
  min=2,
  max=8,
  description='Hindu bowmen',
}
g_str_5fb1ba3de1af06001770f289='5fb1ba3de1af06001770f289'
g_base_definitions[g_str_5fb1ba3de1af06001770f289]={
  id=g_str_5fb1ba3de1af06001770f289,
  name='Horde',
  min=0,
  max=1,
  description='Camp followers',
}
g_str_5fb1ba3de1af06001770f28c='5fb1ba3de1af06001770f28c'
g_base_definitions[g_str_5fb1ba3de1af06001770f28c]={
  id=g_str_5fb1ba3de1af06001770f28c,
  name='Warband',
  min=0,
  max=1,
  description='Ghazis',
}
g_str_5fb1b9efe1af06001770a089_camp='5fb1b9efe1af06001770a089_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a089_camp]={
  name='Camp',
  id=g_str_5fb1b9efe1af06001770a089_camp,
  min=1,
  max=1,
}
army['5fb1b9efe1af06001770a089']={
  data={
    name='Arab Indian  751 to 1206 AD'
  },
  g_base_definitions[g_str_5fb1b9efe1af06001770a089_camp],
  g_base_definitions[g_str_5fb1ba3de1af06001770f28e],
  g_base_definitions[g_str_5fb1ba3de1af06001770f28f],
  g_base_definitions[g_str_5fb1ba3de1af06001770f274],
  g_base_definitions[g_str_5fb1ba3de1af06001770f274],
  g_base_definitions[g_str_5fb1ba3de1af06001770f277],
  g_base_definitions[g_str_5fb1ba3de1af06001770f277],
  g_base_definitions[g_str_5fb1ba3de1af06001770f27a],
  g_base_definitions[g_str_5fb1ba3de1af06001770f27c],
  g_base_definitions[g_str_5fb1ba3de1af06001770f27f],
  g_base_definitions[g_str_5fb1ba3de1af06001770f280],
  g_base_definitions[g_str_5fb1ba3de1af06001770f283],
  g_base_definitions[g_str_5fb1ba3de1af06001770f285],
  g_base_definitions[g_str_5fb1ba3de1af06001770f287],
  g_base_definitions[g_str_5fb1ba3de1af06001770f289],
  g_base_definitions[g_str_5fb1ba3de1af06001770f28c],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a089"] = army["5fb1b9efe1af06001770a089"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Arab Indian  751 to 1206 AD"] = army["5fb1b9efe1af06001770a089"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Arab Indian  751 to 1206 AD"] = army["5fb1b9efe1af06001770a089"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Arab Indian  751 to 1206 AD"] = army["5fb1b9efe1af06001770a089"]
