-- 5fb1b9f4e1af06001770a32e Koguryo Korean  300 to 668 AD

army['5fb1b9f4e1af06001770a32e']={
  data={
    invasionRatings={
      0,
    },
    homeTopographies={
      'Hilly',
    },
    name='Koguryo Korean  300 to 668 AD',
    id='5fb1b9f4e1af06001770a32e',
    dateRange={
      startDate=300,
      endDate=668,
    }
  },
  g_base_definitions[g_str_5fb1ba42e1af06001770fbea_general],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbea],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbec],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbee],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbf0],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbf2],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbf4],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbf6],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbf8],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbfa],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbfc],
  g_base_definitions[g_str_5fb1ba42e1af06001770fbfd],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a32e_camp],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a32e_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a32e"] = army["5fb1b9f4e1af06001770a32e"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Koguryo Korean  300 to 668 AD"] = army["5fb1b9f4e1af06001770a32e"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Koguryo Korean  300 to 668 AD"] = army["5fb1b9f4e1af06001770a32e"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Koguryo Korean  300 to 668 AD"] = army["5fb1b9f4e1af06001770a32e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Koguryo Korean  300 to 668 AD"] = army["5fb1b9f4e1af06001770a32e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a32e"] = {}
army_dates["5fb1b9f4e1af06001770a32e"]["300 AD to 668 AD"] = {
  startDate=300,
  endDate=668
}
army_dates["5fb1b9f4e1af06001770a32e"]["300 AD to 307 AD"] = {
  startDate=300,
  endDate=307
}
army_dates["5fb1b9f4e1af06001770a32e"]["308 AD to 318 AD"] = {
  startDate=308,
  endDate=318
}
army_dates["5fb1b9f4e1af06001770a32e"]["319 AD"] = {
  startDate=319,
  endDate=319
}
army_dates["5fb1b9f4e1af06001770a32e"]["320 AD to 337 AD"] = {
  startDate=320,
  endDate=337
}
army_dates["5fb1b9f4e1af06001770a32e"]["338 AD to 339 AD"] = {
  startDate=338,
  endDate=339
}
army_dates["5fb1b9f4e1af06001770a32e"]["340 AD to 375 AD"] = {
  startDate=340,
  endDate=375
}
army_dates["5fb1b9f4e1af06001770a32e"]["376 AD to 405 AD"] = {
  startDate=376,
  endDate=405
}
army_dates["5fb1b9f4e1af06001770a32e"]["406 AD to 431 AD"] = {
  startDate=406,
  endDate=431
}
army_dates["5fb1b9f4e1af06001770a32e"]["432 AD to 555 AD"] = {
  startDate=432,
  endDate=555
}
army_dates["5fb1b9f4e1af06001770a32e"]["556 AD to 645 AD"] = {
  startDate=556,
  endDate=645
}
army_dates["5fb1b9f4e1af06001770a32e"]["646 AD to 662 AD"] = {
  startDate=646,
  endDate=662
}
army_dates["5fb1b9f4e1af06001770a32e"]["663 AD"] = {
  startDate=663,
  endDate=663
}
army_dates["5fb1b9f4e1af06001770a32e"]["664 AD to 668 AD"] = {
  startDate=664,
  endDate=668
}
