-- 5fb1b9dfe1af06001770971d Cleopatran Ptolemaic  53 to 30 BC

army['5fb1b9dfe1af06001770971d']={
  data={
    name='Cleopatran Ptolemaic  53 to 30 BC',
    id='5fb1b9dfe1af06001770971d',
    dateRange={
      startDate=-53,
      endDate=-30,
    }
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_general_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_mounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770cea8_dismounted],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceab_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceab],
  g_base_definitions[g_str_5fb1ba29e1af06001770cead],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceaf],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb1],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb3],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb5],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb7],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb9_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770ceb9],
  g_base_definitions[g_str_5fb1ba29e1af06001770cebb],
  g_base_definitions[g_str_5fb1ba29e1af06001770cebd],
  g_base_definitions[g_str_5fb1ba29e1af06001770cebf],
  g_base_definitions[g_str_5fb1b9dfe1af06001770971d_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770971d_camp_fortified],
  g_base_definitions[g_str_5fb1b9dfe1af06001770971d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770971d"] = army["5fb1b9dfe1af06001770971d"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Cleopatran Ptolemaic  53 to 30 BC"] = army["5fb1b9dfe1af06001770971d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Cleopatran Ptolemaic  53 to 30 BC"] = army["5fb1b9dfe1af06001770971d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Cleopatran Ptolemaic  53 to 30 BC"] = army["5fb1b9dfe1af06001770971d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af06001770971d"] = {}
army_dates["5fb1b9dfe1af06001770971d"]["53 BC to 30 BC"] = {
  startDate=-53,
  endDate=-30
}
