g_str_5fb1ba36e1af06001770e5b6_general='5fb1ba36e1af06001770e5b6_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e5b6_general]={
  id=g_str_5fb1ba36e1af06001770e5b6_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Veteran horsemen',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba36e1af06001770e5b5",
}
g_str_5fb1ba36e1af06001770e5b6='5fb1ba36e1af06001770e5b6'
g_base_definitions[g_str_5fb1ba36e1af06001770e5b6]={
  id=g_str_5fb1ba36e1af06001770e5b6,
  name='Elite Cavalary',
  min=1,
  max=1,
  description='Veteran horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba36e1af06001770e5b5",
}
g_str_5fb1ba36e1af06001770e5b9='5fb1ba36e1af06001770e5b9'
g_base_definitions[g_str_5fb1ba36e1af06001770e5b9]={
  id=g_str_5fb1ba36e1af06001770e5b9,
  name='Knights',
  min=1,
  max=1,
  description='Boyars armed with lances and bows, some with partial plate armor',
  troop_type="Knights",
  troop_option_id="5fb1ba36e1af06001770e5b7",
}
g_str_5fb1ba36e1af06001770e5bc='5fb1ba36e1af06001770e5bc'
g_base_definitions[g_str_5fb1ba36e1af06001770e5bc]={
  id=g_str_5fb1ba36e1af06001770e5bc,
  name='Knights',
  min=0,
  max=1,
  description='Italian men-at-arms and other mercenary "crusaders"',
  troop_type="Knights",
  troop_option_id="5fb1ba36e1af06001770e5ba",
}
g_str_5fb1ba36e1af06001770e5be='5fb1ba36e1af06001770e5be'
g_base_definitions[g_str_5fb1ba36e1af06001770e5be]={
  id=g_str_5fb1ba36e1af06001770e5be,
  name='Horse Bow',
  min=2,
  max=4,
  description='Lesser boyars or viteji fighting as horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba36e1af06001770e5bd",
}
g_str_5fb1ba36e1af06001770e5c0='5fb1ba36e1af06001770e5c0'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c0]={
  id=g_str_5fb1ba36e1af06001770e5c0,
  name='Elite Foot',
  min=0,
  max=1,
  description='Armored voynuks armed with polearms',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba36e1af06001770e5bf",
}
g_str_5fb1ba36e1af06001770e5c2='5fb1ba36e1af06001770e5c2'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c2]={
  id=g_str_5fb1ba36e1af06001770e5c2,
  name='Bow Levy',
  min=6,
  max=12,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba36e1af06001770e5c1",
}
g_str_5fb1ba36e1af06001770e5c4='5fb1ba36e1af06001770e5c4'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c4]={
  id=g_str_5fb1ba36e1af06001770e5c4,
  name='Archers',
  min=0,
  max=3,
  description='Curteni bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba36e1af06001770e5c3",
}
g_str_5fb1ba36e1af06001770e5c6='5fb1ba36e1af06001770e5c6'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c6]={
  id=g_str_5fb1ba36e1af06001770e5c6,
  name='Rabble',
  min=1,
  max=4,
  description='Rustici armed with spears, javelins, axes, halberds, flails, maces, and scythes',
  troop_type="Rabble",
  troop_option_id="5fb1ba36e1af06001770e5c5",
}
g_str_5fb1ba36e1af06001770e5c7='5fb1ba36e1af06001770e5c7'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c7]={
  id=g_str_5fb1ba36e1af06001770e5c7,
  name='Light Foot',
  min=1,
  max=4,
  description='Rustici armed with spears, javelins, axes, halberds, flails, maces, and scythes',
  troop_type="Light Foot",
  troop_option_id="5fb1ba36e1af06001770e5c5",
}
g_str_5fb1ba36e1af06001770e5c9='5fb1ba36e1af06001770e5c9'
g_base_definitions[g_str_5fb1ba36e1af06001770e5c9]={
  id=g_str_5fb1ba36e1af06001770e5c9,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing crossbowmen or handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba36e1af06001770e5c8",
}
g_str_5fb1ba36e1af06001770e5cc='5fb1ba36e1af06001770e5cc'
g_base_definitions[g_str_5fb1ba36e1af06001770e5cc]={
  id=g_str_5fb1ba36e1af06001770e5cc,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba36e1af06001770e5ca",
}
g_str_5fb1b9eae1af060017709d8c_camp='5fb1b9eae1af060017709d8c_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709d8c_camp]={
  id=g_str_5fb1b9eae1af060017709d8c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
