-- 5fb1b9ebe1af060017709e5a Komnenan Byzantine  1071 to 1142 AD

army['5fb1b9ebe1af060017709e5a']={
  data={
    name='Komnenan Byzantine  1071 to 1142 AD',
    id='5fb1b9ebe1af060017709e5a',
    dateRange={
      startDate=1071,
      endDate=1142,
    }
  },
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8ed],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f0],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f3],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f4],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6_general],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f6],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8f7],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fa_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba38e1af06001770e8fe],
  g_base_definitions[g_str_5fb1ba38e1af06001770e901],
  g_base_definitions[g_str_5fb1ba38e1af06001770e904],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906],
  g_base_definitions[g_str_5fb1ba38e1af06001770e906_plaustrella],
  g_base_definitions[g_str_5fb1ba38e1af06001770e909],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90b],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90d],
  g_base_definitions[g_str_5fb1ba38e1af06001770e90f],
  g_base_definitions[g_str_5fb1ba38e1af06001770e911],
  g_base_definitions[g_str_5fb1ba38e1af06001770e913],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e5a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ebe1af060017709e5a"] = army["5fb1b9ebe1af060017709e5a"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Komnenan Byzantine  1071 to 1142 AD"] = army["5fb1b9ebe1af060017709e5a"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Komnenan Byzantine  1071 to 1142 AD"] = army["5fb1b9ebe1af060017709e5a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Komnenan Byzantine  1071 to 1142 AD"] = army["5fb1b9ebe1af060017709e5a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ebe1af060017709e5a"] = {}
army_dates["5fb1b9ebe1af060017709e5a"]["1071 AD to 1142 AD"] = {
  startDate=1071,
  endDate=1142
}
army_dates["5fb1b9ebe1af060017709e5a"]["1071 AD to 1077 AD"] = {
  startDate=1071,
  endDate=1077
}
army_dates["5fb1b9ebe1af060017709e5a"]["1078 AD to 1082 AD"] = {
  startDate=1078,
  endDate=1082
}
army_dates["5fb1b9ebe1af060017709e5a"]["1083 AD to 1091 AD"] = {
  startDate=1083,
  endDate=1091
}
army_dates["5fb1b9ebe1af060017709e5a"]["1092 AD to 1116 AD"] = {
  startDate=1092,
  endDate=1116
}
army_dates["5fb1b9ebe1af060017709e5a"]["1117 AD to 1142 AD"] = {
  startDate=1117,
  endDate=1142
}
