-- 5fb1b9f1e1af06001770a1b2 Jiang and Qi  315 BC to 550 AD

army['5fb1b9f1e1af06001770a1b2']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Jiang and Qi  315 BC to 550 AD',
    id='5fb1b9f1e1af06001770a1b2',
    dateRange={
      startDate=-315,
      endDate=550,
    }
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f636_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f636],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f639],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63d_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63f],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f642_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f642],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f643],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f646],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f64a],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1b2_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1b2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1b2"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1b2"] = {}
army_dates["5fb1b9f1e1af06001770a1b2"]["315 BC to 550 AD"] = {
  startDate=-315,
  endDate=550
}
army_dates["5fb1b9f1e1af06001770a1b2"]["315 BC to 251 BC"] = {
  startDate=-315,
  endDate=-251
}
army_dates["5fb1b9f1e1af06001770a1b2"]["250 BC to 89 AD"] = {
  startDate=-250,
  endDate=89
}
army_dates["5fb1b9f1e1af06001770a1b2"]["90 AD to 109 AD"] = {
  startDate=90,
  endDate=109
}
army_dates["5fb1b9f1e1af06001770a1b2"]["110 AD to 214 AD"] = {
  startDate=110,
  endDate=214
}
army_dates["5fb1b9f1e1af06001770a1b2"]["215 AD to 302 AD"] = {
  startDate=215,
  endDate=302
}
army_dates["5fb1b9f1e1af06001770a1b2"]["303 AD to 460 AD"] = {
  startDate=303,
  endDate=460
}
army_dates["5fb1b9f1e1af06001770a1b2"]["461 AD to 550 AD"] = {
  startDate=461,
  endDate=550
}
-- 5fb1b9f1e1af06001770a1b2 Jiang and Qi  315 BC to 550 AD

army['5fb1b9f1e1af06001770a1b2']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Jiang and Qi  315 BC to 550 AD',
    id='5fb1b9f1e1af06001770a1b2',
    dateRange={
      startDate=-315,
      endDate=550,
    }
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f636_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f636],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f639],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63d_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63f],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f642_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f642],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f643],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f646],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f64a],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1b2_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1b2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1b2"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1b2"] = {}
army_dates["5fb1b9f1e1af06001770a1b2"]["315 BC to 550 AD"] = {
  startDate=-315,
  endDate=550
}
army_dates["5fb1b9f1e1af06001770a1b2"]["315 BC to 251 BC"] = {
  startDate=-315,
  endDate=-251
}
army_dates["5fb1b9f1e1af06001770a1b2"]["250 BC to 89 AD"] = {
  startDate=-250,
  endDate=89
}
army_dates["5fb1b9f1e1af06001770a1b2"]["90 AD to 109 AD"] = {
  startDate=90,
  endDate=109
}
army_dates["5fb1b9f1e1af06001770a1b2"]["110 AD to 214 AD"] = {
  startDate=110,
  endDate=214
}
army_dates["5fb1b9f1e1af06001770a1b2"]["215 AD to 302 AD"] = {
  startDate=215,
  endDate=302
}
army_dates["5fb1b9f1e1af06001770a1b2"]["303 AD to 460 AD"] = {
  startDate=303,
  endDate=460
}
army_dates["5fb1b9f1e1af06001770a1b2"]["461 AD to 550 AD"] = {
  startDate=461,
  endDate=550
}
-- 5fb1b9f1e1af06001770a1b2 Jiang and Qi  315 BC to 550 AD

army['5fb1b9f1e1af06001770a1b2']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Jiang and Qi  315 BC to 550 AD',
    id='5fb1b9f1e1af06001770a1b2',
    dateRange={
      startDate=-315,
      endDate=550,
    }
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f636_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f636],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f639],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63d_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63d],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f63f],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f642_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f642],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f643],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f646],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f64a],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1b2_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1b2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1b2"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Jiang and Qi  315 BC to 550 AD"] = army["5fb1b9f1e1af06001770a1b2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1b2"] = {}
army_dates["5fb1b9f1e1af06001770a1b2"]["315 BC to 550 AD"] = {
  startDate=-315,
  endDate=550
}
army_dates["5fb1b9f1e1af06001770a1b2"]["315 BC to 251 BC"] = {
  startDate=-315,
  endDate=-251
}
army_dates["5fb1b9f1e1af06001770a1b2"]["250 BC to 89 AD"] = {
  startDate=-250,
  endDate=89
}
army_dates["5fb1b9f1e1af06001770a1b2"]["90 AD to 109 AD"] = {
  startDate=90,
  endDate=109
}
army_dates["5fb1b9f1e1af06001770a1b2"]["110 AD to 214 AD"] = {
  startDate=110,
  endDate=214
}
army_dates["5fb1b9f1e1af06001770a1b2"]["215 AD to 302 AD"] = {
  startDate=215,
  endDate=302
}
army_dates["5fb1b9f1e1af06001770a1b2"]["303 AD to 460 AD"] = {
  startDate=303,
  endDate=460
}
army_dates["5fb1b9f1e1af06001770a1b2"]["461 AD to 550 AD"] = {
  startDate=461,
  endDate=550
}
