-- 5fb1b9dbe1af06001770949e Dark Age and Geometric Greek  1160 to 665 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba23e1af06001770c4d3']= {
  min=0,
  max=1,
  description='2-horse battle platforms with champions who usually fight on foot',
  core='all',
}
g_str_5fb1ba23e1af06001770c4d4_general='5fb1ba23e1af06001770c4d4_general'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d4_general]={
  id=g_str_5fb1ba23e1af06001770c4d4_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who usually fight on foot',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba23e1af06001770c4d3",
}
g_str_5fb1ba23e1af06001770c4d4='5fb1ba23e1af06001770c4d4'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d4]={
  id=g_str_5fb1ba23e1af06001770c4d4,
  name='Battle Taxi',
  min=0,
  max=1,
  description='2-horse battle platforms with champions who usually fight on foot',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba23e1af06001770c4d3",
}
g_troop_option['5fb1ba23e1af06001770c4d5']= {
  min=1,
  max=2,
  description='Greek horsemen',
}
g_str_5fb1ba23e1af06001770c4d6_general='5fb1ba23e1af06001770c4d6_general'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d6_general]={
  id=g_str_5fb1ba23e1af06001770c4d6_general,
  name='Bad Horse General',
  min=1,
  max=1,
  description='Greek horsemen',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba23e1af06001770c4d5",
}
g_str_5fb1ba23e1af06001770c4d6='5fb1ba23e1af06001770c4d6'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d6]={
  id=g_str_5fb1ba23e1af06001770c4d6,
  name='Bad Horse',
  min=1,
  max=2,
  description='Greek horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba23e1af06001770c4d5",
}
g_troop_option['5fb1ba23e1af06001770c4d7']= {
  min=8,
  max=14,
  description='Light infantry armed with sword or spear and dipylon shield',
  core='all',
}
g_str_5fb1ba23e1af06001770c4d8='5fb1ba23e1af06001770c4d8'
g_base_definitions[g_str_5fb1ba23e1af06001770c4d8]={
  id=g_str_5fb1ba23e1af06001770c4d8,
  name='Light Foot',
  min=8,
  max=14,
  description='Light infantry armed with sword or spear and dipylon shield',
  troop_type="Light Foot",
  troop_option_id="5fb1ba23e1af06001770c4d7",
}
g_troop_option['5fb1ba23e1af06001770c4da']= {
  min=0,
  max=14,
  description='Heavy infantry armed with a mix of dipylon and hoplon shields',
  core='all',
  startDate=-724,
  endDate=-665,
}
g_str_5fb1ba23e1af06001770c4dc='5fb1ba23e1af06001770c4dc'
g_base_definitions[g_str_5fb1ba23e1af06001770c4dc]={
  id=g_str_5fb1ba23e1af06001770c4dc,
  name='Heavy Foot',
  min=0,
  max=14,
  description='Heavy infantry armed with a mix of dipylon and hoplon shields',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba23e1af06001770c4da",
}
g_troop_option['5fb1ba23e1af06001770c4de']= {
  min=0,
  max=4,
  description='Skirmishing bowmen',
}
g_str_5fb1ba23e1af06001770c4df='5fb1ba23e1af06001770c4df'
g_base_definitions[g_str_5fb1ba23e1af06001770c4df]={
  id=g_str_5fb1ba23e1af06001770c4df,
  name='Skirmishers',
  min=0,
  max=4,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba23e1af06001770c4de",
}
g_troop_option['5fb1ba23e1af06001770c4e1']= {
  min=1,
  max=4,
  description='Javelinmen',
}
g_str_5fb1ba23e1af06001770c4e2='5fb1ba23e1af06001770c4e2'
g_base_definitions[g_str_5fb1ba23e1af06001770c4e2]={
  id=g_str_5fb1ba23e1af06001770c4e2,
  name='Rabble',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba23e1af06001770c4e1",
}
g_str_5fb1b9dbe1af06001770949e_camp='5fb1b9dbe1af06001770949e_camp'
g_base_definitions[g_str_5fb1b9dbe1af06001770949e_camp]={
  id=g_str_5fb1b9dbe1af06001770949e_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9dbe1af06001770949e']={
  data={
    name='Dark Age and Geometric Greek  1160 to 665 BC',
    id='5fb1b9dbe1af06001770949e',
    army_id='5fb1b9dbe1af06001770949e'
  },
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d4_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d4],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d6_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d6],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d8],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4dc],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4df],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4e2],
  g_base_definitions[g_str_5fb1b9dbe1af06001770949e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af06001770949e"] = army["5fb1b9dbe1af06001770949e"]
army['5fb1b9dbe1af06001770949e_-1160_-725']={
  data={
    name='Dark Age and Geometric Greek 1160 BC to 725 BC',
    id='5fb1b9dbe1af06001770949e_-1160_-725',
    army_id='5fb1b9dbe1af06001770949e'
  },
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d4_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d4],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d6_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d6],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d8],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4df],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4e2],
  g_base_definitions[g_str_5fb1b9dbe1af06001770949e_camp],
}
army['5fb1b9dbe1af06001770949e_-724_-665']={
  data={
    name='Dark Age and Geometric Greek 724 BC to 665 BC',
    id='5fb1b9dbe1af06001770949e_-724_-665',
    army_id='5fb1b9dbe1af06001770949e'
  },
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d4_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d4],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d6_general],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d6],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4d8],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4dc],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4df],
  g_base_definitions[g_str_5fb1ba23e1af06001770c4e2],
  g_base_definitions[g_str_5fb1b9dbe1af06001770949e_camp],
}
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Dark Age and Geometric Greek  1160 to 665 BC"] = army["5fb1b9dbe1af06001770949e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Dark Age and Geometric Greek  1160 to 665 BC"] = army["5fb1b9dbe1af06001770949e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af06001770949e"] = {}
army_dates["5fb1b9dbe1af06001770949e"]["1160 BC to 665 BC"] ="5fb1b9dbe1af06001770949e"
army_dates["5fb1b9dbe1af06001770949e"]["1160 BC to 725 BC"] ="5fb1b9dbe1af06001770949e_-1160_-725"
army_dates["5fb1b9dbe1af06001770949e"]["724 BC to 665 BC"] ="5fb1b9dbe1af06001770949e_-724_-665"
