-- 5fb1b9e8e1af060017709cdd Early Renaissance German Citystates  1494 to 1518 AD

army['5fb1b9e8e1af060017709cdd']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
      'Arable',
    },
    name='Early Renaissance German Citystates  1494 to 1518 AD',
    id='5fb1b9e8e1af060017709cdd',
    dateRange={
      startDate=1494,
      endDate=1518,
    },
  },
  g_base_definitions[g_str_5fb1ba34e1af06001770e2c5_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2c5],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2c7],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2c9_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2c9],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2cb],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2ce_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2ce],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2cf_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2cf],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2d2_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2d2],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2d4],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2d6_general],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2d6],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2d8],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2da],
  g_base_definitions[g_str_5fb1ba34e1af06001770e2dc],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cdd_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cdd_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cdd_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709cdd"] = army["5fb1b9e8e1af060017709cdd"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Early Renaissance German Citystates  1494 to 1518 AD"] = army["5fb1b9e8e1af060017709cdd"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Early Renaissance German Citystates  1494 to 1518 AD"] = army["5fb1b9e8e1af060017709cdd"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Renaissance German Citystates  1494 to 1518 AD"] = army["5fb1b9e8e1af060017709cdd"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Early Renaissance German Citystates  1494 to 1518 AD"] = army["5fb1b9e8e1af060017709cdd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Renaissance German Citystates  1494 to 1518 AD"] = army["5fb1b9e8e1af060017709cdd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709cdd"] = {}
army_dates["5fb1b9e8e1af060017709cdd"]["1494 AD to 1518 AD"] = {
  startDate=1494,
  endDate=1518
}
