-- 5fb1b9efe1af06001770a05c Qara-Khitan  1124 to 1211 AD

army['5fb1b9efe1af06001770a05c']={
  data={
    invasionRatings={
      2,
    },
    homeTopographies={
      'Steppe',
    },
    name='Qara-Khitan  1124 to 1211 AD',
    id='5fb1b9efe1af06001770a05c',
    dateRange={
      startDate=1124,
      endDate=1211,
    }
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a5],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a7],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1a9],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ac],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1ae],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1b0],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a05c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a05c"] = army["5fb1b9efe1af06001770a05c"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Qara-Khitan  1124 to 1211 AD"] = army["5fb1b9efe1af06001770a05c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Qara-Khitan  1124 to 1211 AD"] = army["5fb1b9efe1af06001770a05c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a05c"] = {}
army_dates["5fb1b9efe1af06001770a05c"]["1124 AD to 1211 AD"] = {
  startDate=1124,
  endDate=1211
}
army_dates["5fb1b9efe1af06001770a05c"]["1124 AD to 1129 AD"] = {
  startDate=1124,
  endDate=1129
}
army_dates["5fb1b9efe1af06001770a05c"]["1130 AD to 1131 AD"] = {
  startDate=1130,
  endDate=1131
}
army_dates["5fb1b9efe1af06001770a05c"]["1132 AD to 1175 AD"] = {
  startDate=1132,
  endDate=1175
}
army_dates["5fb1b9efe1af06001770a05c"]["1176 AD to 1185 AD"] = {
  startDate=1176,
  endDate=1185
}
army_dates["5fb1b9efe1af06001770a05c"]["1186 AD to 1206 AD"] = {
  startDate=1186,
  endDate=1206
}
army_dates["5fb1b9efe1af06001770a05c"]["1207 AD to 1210 AD"] = {
  startDate=1207,
  endDate=1210
}
army_dates["5fb1b9efe1af06001770a05c"]["1211 AD"] = {
  startDate=1211,
  endDate=1211
}
