-- 5fb1b9efe1af06001770a06e Sogdians  500 to 730 AD

army['5fb1b9efe1af06001770a06e']={
  data={
    name='Sogdians  500 to 730 AD',
    id='5fb1b9efe1af06001770a06e',
    dateRange={
      startDate=500,
      endDate=730,
    }
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f205],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f206],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f208],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20b],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f211],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a06e"] = army["5fb1b9efe1af06001770a06e"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Sogdians  500 to 730 AD"] = army["5fb1b9efe1af06001770a06e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sogdians  500 to 730 AD"] = army["5fb1b9efe1af06001770a06e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a06e"] = {}
army_dates["5fb1b9efe1af06001770a06e"]["500 AD to 730 AD"] = {
  startDate=500,
  endDate=730
}
army_dates["5fb1b9efe1af06001770a06e"]["500 AD to 649 AD"] = {
  startDate=500,
  endDate=649
}
army_dates["5fb1b9efe1af06001770a06e"]["650 AD to 730 AD"] = {
  startDate=650,
  endDate=730
}
