g_str_5fb1ba27e1af06001770c98c_general='5fb1ba27e1af06001770c98c_general'
g_base_definitions[g_str_5fb1ba27e1af06001770c98c_general]={
  id=g_str_5fb1ba27e1af06001770c98c_general,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Epilektoi',
  general=true,
  hold_the_line=true,
  hoplite_deep_formation=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba27e1af06001770c98b",
}
g_str_5fb1ba27e1af06001770c98c='5fb1ba27e1af06001770c98c'
g_base_definitions[g_str_5fb1ba27e1af06001770c98c]={
  id=g_str_5fb1ba27e1af06001770c98c,
  name='Elite Foot',
  min=0,
  max=1,
  description='Epilektoi',
  hold_the_line=true,
  hoplite_deep_formation=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba27e1af06001770c98b",
}
g_str_5fb1ba27e1af06001770c990_general='5fb1ba27e1af06001770c990_general'
g_base_definitions[g_str_5fb1ba27e1af06001770c990_general]={
  id=g_str_5fb1ba27e1af06001770c990_general,
  name='Heavy Foot General',
  min=8,
  max=1,
  description='Hoplites',
  general=true,
  hoplite_deep_formation=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba27e1af06001770c98f",
}
g_str_5fb1ba27e1af06001770c990='5fb1ba27e1af06001770c990'
g_base_definitions[g_str_5fb1ba27e1af06001770c990]={
  id=g_str_5fb1ba27e1af06001770c990,
  name='Heavy Foot',
  min=8,
  max=15,
  description='Hoplites',
  hoplite_deep_formation=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba27e1af06001770c98f",
}
g_str_5fb1ba27e1af06001770c993='5fb1ba27e1af06001770c993'
g_base_definitions[g_str_5fb1ba27e1af06001770c993]={
  id=g_str_5fb1ba27e1af06001770c993,
  name='Rabble',
  min=1,
  max=2,
  description='Psiloi armed with javelins',
  troop_type="Rabble",
  troop_option_id="5fb1ba27e1af06001770c992",
}
g_str_5fb1ba27e1af06001770c995='5fb1ba27e1af06001770c995'
g_base_definitions[g_str_5fb1ba27e1af06001770c995]={
  id=g_str_5fb1ba27e1af06001770c995,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba27e1af06001770c994",
}
g_str_5fb1ba27e1af06001770c996='5fb1ba27e1af06001770c996'
g_base_definitions[g_str_5fb1ba27e1af06001770c996]={
  id=g_str_5fb1ba27e1af06001770c996,
  name='Bad Horse',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba27e1af06001770c994",
}
g_str_5fb1ba27e1af06001770c998='5fb1ba27e1af06001770c998'
g_base_definitions[g_str_5fb1ba27e1af06001770c998]={
  id=g_str_5fb1ba27e1af06001770c998,
  name='Skirmishers',
  min=0,
  max=1,
  description='Cretan or other skirmishing mercenary bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba27e1af06001770c997",
}
g_str_5fb1ba27e1af06001770c99a='5fb1ba27e1af06001770c99a'
g_base_definitions[g_str_5fb1ba27e1af06001770c99a]={
  id=g_str_5fb1ba27e1af06001770c99a,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba27e1af06001770c999",
}
g_str_5fb1ba27e1af06001770c99c='5fb1ba27e1af06001770c99c'
g_base_definitions[g_str_5fb1ba27e1af06001770c99c]={
  id=g_str_5fb1ba27e1af06001770c99c,
  name='Light Foot',
  min=0,
  max=1,
  description='Thracian infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba27e1af06001770c99b",
}
g_str_5fb1ba27e1af06001770c99f='5fb1ba27e1af06001770c99f'
g_base_definitions[g_str_5fb1ba27e1af06001770c99f]={
  id=g_str_5fb1ba27e1af06001770c99f,
  name='Light Foot',
  min=0,
  max=2,
  description='Akarnanians',
  troop_type="Light Foot",
  troop_option_id="5fb1ba27e1af06001770c99d",
}
g_str_5fb1ba27e1af06001770c9a2='5fb1ba27e1af06001770c9a2'
g_base_definitions[g_str_5fb1ba27e1af06001770c9a2]={
  id=g_str_5fb1ba27e1af06001770c9a2,
  name='Light Foot',
  min=0,
  max=2,
  description='Sikels',
  troop_type="Light Foot",
  troop_option_id="5fb1ba27e1af06001770c9a0",
}
g_str_5fb1ba27e1af06001770c9a5='5fb1ba27e1af06001770c9a5'
g_base_definitions[g_str_5fb1ba27e1af06001770c9a5]={
  id=g_str_5fb1ba27e1af06001770c9a5,
  name='Light Spear',
  min=0,
  max=3,
  description='Iphikratean peltasts',
  troop_type="Light Spear",
  troop_option_id="5fb1ba27e1af06001770c9a3",
}
g_str_5fb1b9dde1af0600177095e3_camp='5fb1b9dde1af0600177095e3_camp'
g_base_definitions[g_str_5fb1b9dde1af0600177095e3_camp]={
  id=g_str_5fb1b9dde1af0600177095e3_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dde1af0600177095e3_camp_fortified='5fb1b9dde1af0600177095e3_camp_fortified'
g_base_definitions[g_str_5fb1b9dde1af0600177095e3_camp_fortified]={
  id=g_str_5fb1b9dde1af0600177095e3_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9dde1af0600177095e3_camp_pack_train='5fb1b9dde1af0600177095e3_camp_pack_train'
g_base_definitions[g_str_5fb1b9dde1af0600177095e3_camp_pack_train]={
  id=g_str_5fb1b9dde1af0600177095e3_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1b9dde1af0600177095e3_prepared_defenses='5fb1b9dde1af0600177095e3_prepared_defenses'
g_base_definitions[g_str_5fb1b9dde1af0600177095e3_prepared_defenses]={
  id=g_str_5fb1b9dde1af0600177095e3_prepared_defenses,
  name='Prepared Defenses',
  min=0,
  max=4,
  description='Improvised wall or palisade',
  prepared_defenses=true,
  troop_type="Prepared Defenses",
}
g_str_5fb1ba0ae1af06001770a9ac='5fb1ba0ae1af06001770a9ac'
g_base_definitions[g_str_5fb1ba0ae1af06001770a9ac]={
  id=g_str_5fb1ba0ae1af06001770a9ac,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0ae1af06001770a9ab",
}
g_str_5fb1ba0ae1af06001770a9ae='5fb1ba0ae1af06001770a9ae'
g_base_definitions[g_str_5fb1ba0ae1af06001770a9ae]={
  id=g_str_5fb1ba0ae1af06001770a9ae,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0ae1af06001770a9ad",
}
g_str_5fb1ba0be1af06001770a9b0='5fb1ba0be1af06001770a9b0'
g_base_definitions[g_str_5fb1ba0be1af06001770a9b0]={
  id=g_str_5fb1ba0be1af06001770a9b0,
  name='Rabble',
  min=3,
  max=7,
  description='Psiloi armed with javelins',
  troop_type="Rabble",
  troop_option_id="5fb1ba0ae1af06001770a9af",
}
g_str_5fb1ba0be1af06001770a9b2='5fb1ba0be1af06001770a9b2'
g_base_definitions[g_str_5fb1ba0be1af06001770a9b2]={
  id=g_str_5fb1ba0be1af06001770a9b2,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0be1af06001770a9b1",
}
g_str_5fb1ba0be1af06001770a9b4='5fb1ba0be1af06001770a9b4'
g_base_definitions[g_str_5fb1ba0be1af06001770a9b4]={
  id=g_str_5fb1ba0be1af06001770a9b4,
  name='Light Foot',
  min=0,
  max=1,
  description='Mercenary peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0be1af06001770a9b3",
}
