g_str_5fb1ba2de1af06001770d646_general='5fb1ba2de1af06001770d646_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d646_general]={
  id=g_str_5fb1ba2de1af06001770d646_general,
  name='Cataphracts General',
  min=0,
  max=1,
  description='Asvaran',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2de1af06001770d645",
}
g_str_5fb1ba2de1af06001770d646='5fb1ba2de1af06001770d646'
g_base_definitions[g_str_5fb1ba2de1af06001770d646]={
  id=g_str_5fb1ba2de1af06001770d646,
  name='Cataphracts',
  min=0,
  max=3,
  description='Asvaran',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2de1af06001770d645",
}
g_str_5fb1ba2de1af06001770d648_general='5fb1ba2de1af06001770d648_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d648_general]={
  id=g_str_5fb1ba2de1af06001770d648_general,
  name='Elite Cavalary General',
  min=4,
  max=1,
  description='Asvaran and wealthy dehquan',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba2de1af06001770d647",
}
g_str_5fb1ba2de1af06001770d648='5fb1ba2de1af06001770d648'
g_base_definitions[g_str_5fb1ba2de1af06001770d648]={
  id=g_str_5fb1ba2de1af06001770d648,
  name='Elite Cavalary',
  min=4,
  max=11,
  description='Asvaran and wealthy dehquan',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba2de1af06001770d647",
}
g_str_5fb1ba2de1af06001770d64b='5fb1ba2de1af06001770d64b'
g_base_definitions[g_str_5fb1ba2de1af06001770d64b]={
  id=g_str_5fb1ba2de1af06001770d64b,
  name='Horse Bow',
  min=1,
  max=4,
  description='Dehquan yeomanry',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2de1af06001770d64a",
}
g_str_5fb1ba2de1af06001770d64d='5fb1ba2de1af06001770d64d'
g_base_definitions[g_str_5fb1ba2de1af06001770d64d]={
  id=g_str_5fb1ba2de1af06001770d64d,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Paighan spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2de1af06001770d64c",
}
g_str_5fb1ba2de1af06001770d64d_elephant_screen='5fb1ba2de1af06001770d64d_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d64d_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d64d_elephant_screen,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Paighan spearmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2de1af06001770d64c",
}
g_str_5fb1ba2de1af06001770d64d_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d64d_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d64d_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d64d_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=2,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d650='5fb1ba2de1af06001770d650'
g_base_definitions[g_str_5fb1ba2de1af06001770d650]={
  id=g_str_5fb1ba2de1af06001770d650,
  name='Bow Levy',
  min=0,
  max=4,
  description='Paighan bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba2de1af06001770d64f",
}
g_str_5fb1ba2de1af06001770d650_elephant_screen='5fb1ba2de1af06001770d650_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d650_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d650_elephant_screen,
  name='Bow Levy',
  min=0,
  max=4,
  description='Paighan bowmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba2de1af06001770d64f",
}
g_str_5fb1ba2de1af06001770d650_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d650_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d650_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d650_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d653='5fb1ba2de1af06001770d653'
g_base_definitions[g_str_5fb1ba2de1af06001770d653]={
  id=g_str_5fb1ba2de1af06001770d653,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2de1af06001770d652",
}
g_str_5fb1ba2de1af06001770d655='5fb1ba2de1af06001770d655'
g_base_definitions[g_str_5fb1ba2de1af06001770d655]={
  id=g_str_5fb1ba2de1af06001770d655,
  name='Horde',
  min=0,
  max=4,
  description='Peasant throng',
  troop_type="Horde",
  troop_option_id="5fb1ba2de1af06001770d654",
}
g_str_5fb1ba2de1af06001770d655_elephant_screen='5fb1ba2de1af06001770d655_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d655_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d655_elephant_screen,
  name='Horde',
  min=0,
  max=4,
  description='Peasant throng\nElephant Screen',
  elephant_screen=true,
  troop_type="Horde",
  troop_option_id="5fb1ba2de1af06001770d654",
}
g_str_5fb1ba2de1af06001770d655_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d655_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d655_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d655_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d656='5fb1ba2de1af06001770d656'
g_base_definitions[g_str_5fb1ba2de1af06001770d656]={
  id=g_str_5fb1ba2de1af06001770d656,
  name='Rabble',
  min=0,
  max=4,
  description='Peasant throng',
  troop_type="Rabble",
  troop_option_id="5fb1ba2de1af06001770d654",
}
g_str_5fb1ba2de1af06001770d656_elephant_screen='5fb1ba2de1af06001770d656_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d656_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d656_elephant_screen,
  name='Rabble',
  min=0,
  max=4,
  description='Peasant throng\nElephant Screen',
  elephant_screen=true,
  troop_type="Rabble",
  troop_option_id="5fb1ba2de1af06001770d654",
}
g_str_5fb1ba2de1af06001770d656_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d656_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d656_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d656_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d659='5fb1ba2de1af06001770d659'
g_base_definitions[g_str_5fb1ba2de1af06001770d659]={
  id=g_str_5fb1ba2de1af06001770d659,
  name='Elephants',
  min=0,
  max=2,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba2de1af06001770d658",
}
g_str_5fb1ba2de1af06001770d65c='5fb1ba2de1af06001770d65c'
g_base_definitions[g_str_5fb1ba2de1af06001770d65c]={
  id=g_str_5fb1ba2de1af06001770d65c,
  name='Spears',
  min=0,
  max=1,
  description='Drafsh I Kavyan Guard',
  troop_type="Spears",
  troop_option_id="5fb1ba2de1af06001770d65b",
}
g_str_5fb1ba2de1af06001770d65d='5fb1ba2de1af06001770d65d'
g_base_definitions[g_str_5fb1ba2de1af06001770d65d]={
  id=g_str_5fb1ba2de1af06001770d65d,
  name='Pavisiers',
  min=0,
  max=1,
  description='Drafsh I Kavyan Guard',
  troop_type="Pavisiers",
  troop_option_id="5fb1ba2de1af06001770d65b",
}
g_str_5fb1ba2de1af06001770d65f='5fb1ba2de1af06001770d65f'
g_base_definitions[g_str_5fb1ba2de1af06001770d65f]={
  id=g_str_5fb1ba2de1af06001770d65f,
  name='Spears',
  min=0,
  max=1,
  description='Armenian armored infantry',
  troop_type="Spears",
  troop_option_id="5fb1ba2de1af06001770d65e",
}
g_str_5fb1ba2de1af06001770d660='5fb1ba2de1af06001770d660'
g_base_definitions[g_str_5fb1ba2de1af06001770d660]={
  id=g_str_5fb1ba2de1af06001770d660,
  name='Light Foot',
  min=0,
  max=1,
  description='Armenian armored infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2de1af06001770d65e",
}
g_str_5fb1ba2de1af06001770d663='5fb1ba2de1af06001770d663'
g_base_definitions[g_str_5fb1ba2de1af06001770d663]={
  id=g_str_5fb1ba2de1af06001770d663,
  name='Raiders',
  min=0,
  max=2,
  description='Dailami',
  troop_type="Raiders",
  troop_option_id="5fb1ba2de1af06001770d661",
}
g_str_5fb1b9e2e1af06001770994f_camp='5fb1b9e2e1af06001770994f_camp'
g_base_definitions[g_str_5fb1b9e2e1af06001770994f_camp]={
  id=g_str_5fb1b9e2e1af06001770994f_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af06001770994f_camp_fortified='5fb1b9e2e1af06001770994f_camp_fortified'
g_base_definitions[g_str_5fb1b9e2e1af06001770994f_camp_fortified]={
  id=g_str_5fb1b9e2e1af06001770994f_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af06001770994f_camp_pack_train='5fb1b9e2e1af06001770994f_camp_pack_train'
g_base_definitions[g_str_5fb1b9e2e1af06001770994f_camp_pack_train]={
  id=g_str_5fb1b9e2e1af06001770994f_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba0fe1af06001770ade5='5fb1ba0fe1af06001770ade5'
g_base_definitions[g_str_5fb1ba0fe1af06001770ade5]={
  id=g_str_5fb1ba0fe1af06001770ade5,
  name='Horse Bow',
  min=1,
  max=4,
  description='Hun horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba0fe1af06001770ade4",
}
g_str_5fb1ba0fe1af06001770ade7='5fb1ba0fe1af06001770ade7'
g_base_definitions[g_str_5fb1ba0fe1af06001770ade7]={
  id=g_str_5fb1ba0fe1af06001770ade7,
  name='Warriors',
  min=0,
  max=3,
  description='Fierce Hun infantry',
  troop_type="Warriors",
  troop_option_id="5fb1ba0fe1af06001770ade6",
}
g_str_5fb1ba0ce1af06001770abc8='5fb1ba0ce1af06001770abc8'
g_base_definitions[g_str_5fb1ba0ce1af06001770abc8]={
  id=g_str_5fb1ba0ce1af06001770abc8,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen, some with personal armor',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba0ce1af06001770abc7",
}
g_str_5fb1ba0ce1af06001770abca='5fb1ba0ce1af06001770abca'
g_base_definitions[g_str_5fb1ba0ce1af06001770abca]={
  id=g_str_5fb1ba0ce1af06001770abca,
  name='Bad Horse',
  min=0,
  max=1,
  description='Scouts on camels',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba0ce1af06001770abc9",
}
g_str_5fb1ba0ce1af06001770abcc='5fb1ba0ce1af06001770abcc'
g_base_definitions[g_str_5fb1ba0ce1af06001770abcc]={
  id=g_str_5fb1ba0ce1af06001770abcc,
  name='Light Foot',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0ce1af06001770abcb",
}
g_str_5fb1ba0ce1af06001770abce='5fb1ba0ce1af06001770abce'
g_base_definitions[g_str_5fb1ba0ce1af06001770abce]={
  id=g_str_5fb1ba0ce1af06001770abce,
  name='Archers',
  min=0,
  max=1,
  description='Bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba0ce1af06001770abcd",
}
g_str_5fb1ba0ce1af06001770abcf='5fb1ba0ce1af06001770abcf'
g_base_definitions[g_str_5fb1ba0ce1af06001770abcf]={
  id=g_str_5fb1ba0ce1af06001770abcf,
  name='Bow Levy',
  min=0,
  max=1,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba0ce1af06001770abcd",
}
g_str_5fb1ba0ce1af06001770abd1='5fb1ba0ce1af06001770abd1'
g_base_definitions[g_str_5fb1ba0ce1af06001770abd1]={
  id=g_str_5fb1ba0ce1af06001770abd1,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0ce1af06001770abd0",
}
g_str_5fb1ba0ce1af06001770abd3='5fb1ba0ce1af06001770abd3'
g_base_definitions[g_str_5fb1ba0ce1af06001770abd3]={
  id=g_str_5fb1ba0ce1af06001770abd3,
  name='Light Foot',
  min=0,
  max=2,
  description='Mercenary javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0ce1af06001770abd2",
}
g_str_5fb1ba16e1af06001770b7f1='5fb1ba16e1af06001770b7f1'
g_base_definitions[g_str_5fb1ba16e1af06001770b7f1]={
  id=g_str_5fb1ba16e1af06001770b7f1,
  name='Horse Bow',
  min=0,
  max=1,
  description='Noble horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba16e1af06001770b7f0",
}
g_str_5fb1ba16e1af06001770b7f3='5fb1ba16e1af06001770b7f3'
g_base_definitions[g_str_5fb1ba16e1af06001770b7f3]={
  id=g_str_5fb1ba16e1af06001770b7f3,
  name='Horse Bow',
  min=1,
  max=2,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba16e1af06001770b7f2",
}
