-- 5fb1b9dae1af06001770943e Later Neo-Babylonian  669 to 605 BC

army['5fb1b9dae1af06001770943e']={
  data={
    name='Later Neo-Babylonian  669 to 605 BC',
    id='5fb1b9dae1af06001770943e',
    army_id='5fb1b9dae1af06001770943e'
  },
  g_base_definitions[g_str_5fb1ba22e1af06001770c34d_general],
  g_base_definitions[g_str_5fb1ba22e1af06001770c34d],
  g_base_definitions[g_str_5fb1ba22e1af06001770c34f],
  g_base_definitions[g_str_5fb1ba22e1af06001770c351],
  g_base_definitions[g_str_5fb1ba22e1af06001770c353],
  g_base_definitions[g_str_5fb1ba22e1af06001770c356],
  g_base_definitions[g_str_5fb1b9dae1af06001770943e_camp],
  g_base_definitions[g_str_5fb1b9dae1af06001770943e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af06001770943e"] = army["5fb1b9dae1af06001770943e"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Later Neo-Babylonian  669 to 605 BC"] = army["5fb1b9dae1af06001770943e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Neo-Babylonian  669 to 605 BC"] = army["5fb1b9dae1af06001770943e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af06001770943e"] = {}
army_dates["5fb1b9dae1af06001770943e"]["669 BC to 605 BC"] ="5fb1b9dae1af06001770943e"
