troop_options['5fb1ba2ae1af06001770d0cb'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-250,
    endDate=225,
  }
}
troop_options['5fb1ba2ae1af06001770d0ce'] = {
  min=5,
  max=11,
  dateRange={
    startDate=-250,
    endDate=225,
  }
}
troop_options['5fb1ba2ae1af06001770d0d0'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-250,
    endDate=225,
  }
}
troop_options['5fb1ba2ae1af06001770d0d3'] = {
  min=0,
  max=5,
  dateRange={
    startDate=-250,
    endDate=225,
  }
}
-- allies
