-- 5fb1b9dbe1af0600177094a4 Early Villanovan Italian  1000 to 801 BC

army['5fb1b9dbe1af0600177094a4']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Villanovan Italian  1000 to 801 BC',
    id='5fb1b9dbe1af0600177094a4',
    dateRange={
      startDate=-1000,
      endDate=-801,
    },
  },
  g_base_definitions[g_str_615351a103385c0016b854ef_general],
  g_base_definitions[g_str_615351a103385c0016b854ef],
  g_base_definitions[g_str_615351a103385c0016b854f1_general],
  g_base_definitions[g_str_615351a103385c0016b854f1],
  g_base_definitions[g_str_615351a103385c0016b854f3],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094a4_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094a4"] = army["5fb1b9dbe1af0600177094a4"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Villanovan Italian  1000 to 801 BC"] = army["5fb1b9dbe1af0600177094a4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Villanovan Italian  1000 to 801 BC"] = army["5fb1b9dbe1af0600177094a4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094a4"] = {}
army_dates["5fb1b9dbe1af0600177094a4"]["1000 BC to 801 BC"] = {
  startDate=-1000,
  endDate=-801
}
