-- 5fb1b9eee1af06001770a004 Mamluk Egyptian  1250 to 1517 AD

army['5fb1b9eee1af06001770a004']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
      3,
    },
    homeTopographies={
      'Delta',
      'Dry',
    },
    name='Mamluk Egyptian  1250 to 1517 AD',
    id='5fb1b9eee1af06001770a004',
    dateRange={
      startDate=1250,
      endDate=1517,
    },
  },
  g_base_definitions[g_str_615351b103385c0016b88099_general],
  g_base_definitions[g_str_615351b103385c0016b88099_general_shower_shooting],
  g_base_definitions[g_str_615351b103385c0016b88099],
  g_base_definitions[g_str_615351b103385c0016b88099_shower_shooting],
  g_base_definitions[g_str_615351b103385c0016b8809c],
  g_base_definitions[g_str_615351b103385c0016b8809f],
  g_base_definitions[g_str_615351b103385c0016b880a1],
  g_base_definitions[g_str_615351b103385c0016b880a3],
  g_base_definitions[g_str_615351b103385c0016b880a5],
  g_base_definitions[g_str_615351b103385c0016b880a6],
  g_base_definitions[g_str_615351b103385c0016b880a8],
  g_base_definitions[g_str_615351b103385c0016b880aa],
  g_base_definitions[g_str_615351b103385c0016b880ac],
  g_base_definitions[g_str_615351b103385c0016b880ae],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp],
  g_base_definitions[g_str_5fb1b9eee1af06001770a004_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af06001770a004"] = army["5fb1b9eee1af06001770a004"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Mamluk Egyptian  1250 to 1517 AD"] = army["5fb1b9eee1af06001770a004"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Mamluk Egyptian  1250 to 1517 AD"] = army["5fb1b9eee1af06001770a004"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mamluk Egyptian  1250 to 1517 AD"] = army["5fb1b9eee1af06001770a004"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af06001770a004"] = {}
army_dates["5fb1b9eee1af06001770a004"]["1250 AD to 1517 AD"] = {
  startDate=1250,
  endDate=1517
}
army_dates["5fb1b9eee1af06001770a004"]["1250 AD to 1285 AD"] = {
  startDate=1250,
  endDate=1285
}
army_dates["5fb1b9eee1af06001770a004"]["1286 AD"] = {
  startDate=1286,
  endDate=1286
}
army_dates["5fb1b9eee1af06001770a004"]["1287 AD to 1517 AD"] = {
  startDate=1287,
  endDate=1517
}
