-- 5fb1b9e8e1af060017709c6a Free Company  1357 to 1410 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba33e1af06001770e0d1_general='5fb1ba33e1af06001770e0d1_general'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general]={
  id=g_str_5fb1ba33e1af06001770e0d1_general,
  name='Knights General',
  min=6,
  max=1,
  description='Men-at-arms of various nationalities',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0d0",
}
g_str_5fb1ba33e1af06001770e0d1_general_dismounted='5fb1ba33e1af06001770e0d1_general_dismounted'
g_str_5fb1ba33e1af06001770e0d1_general_mounted='5fb1ba33e1af06001770e0d1_general_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_dismounted]={
  id=g_str_5fb1ba33e1af06001770e0d1_general_dismounted,
  name='Elite Foot General',
  min=6,
  max=1,
  description='Men-at-arms of various nationalities\nDeployment dismounted from Knights General',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770e0d1_general_mounted,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e0d0",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_mounted]={
  id=g_str_5fb1ba33e1af06001770e0d1_general_mounted,
  name='Knights General',
  min=6,
  max=1,
  description='Men-at-arms of various nationalities\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770e0d1_general_dismounted,
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0d0",
}
g_str_5fb1ba33e1af06001770e0d1='5fb1ba33e1af06001770e0d1'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d1]={
  id=g_str_5fb1ba33e1af06001770e0d1,
  name='Knights',
  min=6,
  max=12,
  description='Men-at-arms of various nationalities',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0d0",
}
g_str_5fb1ba33e1af06001770e0d1_dismounted='5fb1ba33e1af06001770e0d1_dismounted'
g_str_5fb1ba33e1af06001770e0d1_mounted='5fb1ba33e1af06001770e0d1_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_dismounted]={
  id=g_str_5fb1ba33e1af06001770e0d1_dismounted,
  name='Elite Foot',
  min=6,
  max=12,
  description='Men-at-arms of various nationalities\nDeployment dismounted from Knights',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770e0d1_mounted,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e0d0",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_mounted]={
  id=g_str_5fb1ba33e1af06001770e0d1_mounted,
  name='Knights',
  min=6,
  max=12,
  description='Men-at-arms of various nationalities\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770e0d1_dismounted,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0d0",
}
g_str_5fb1ba33e1af06001770e0d4='5fb1ba33e1af06001770e0d4'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d4]={
  id=g_str_5fb1ba33e1af06001770e0d4,
  name='Archers',
  min=0,
  max=2,
  description='Crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e0d3",
}
g_str_5fb1ba33e1af06001770e0d6='5fb1ba33e1af06001770e0d6'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d6]={
  id=g_str_5fb1ba33e1af06001770e0d6,
  name='Archers',
  min=0,
  max=2,
  description='English longbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e0d5",
}
g_str_5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry='5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry'
g_str_5fb1ba33e1af06001770e0d6_mounted_mobile_infantry='5fb1ba33e1af06001770e0d6_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry,
  name='Archers',
  min=0,
  max=2,
  description='English longbowmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba33e1af06001770e0d6_mounted_mobile_infantry,
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e0d5",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_mounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e0d6_mounted_mobile_infantry,
  name='Archers',
  min=0,
  max=2,
  description='English longbowmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e0d5",
}
g_str_5fb1ba33e1af06001770e0d9='5fb1ba33e1af06001770e0d9'
g_base_definitions[g_str_5fb1ba33e1af06001770e0d9]={
  id=g_str_5fb1ba33e1af06001770e0d9,
  name='Light Foot',
  min=0,
  max=1,
  description='Breton javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba33e1af06001770e0d8",
}
g_str_5fb1ba33e1af06001770e0dc='5fb1ba33e1af06001770e0dc'
g_base_definitions[g_str_5fb1ba33e1af06001770e0dc]={
  id=g_str_5fb1ba33e1af06001770e0dc,
  name='Horse Bow',
  min=0,
  max=1,
  description='Hungarian horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba33e1af06001770e0da",
}
g_str_5fb1b9e8e1af060017709c6a_camp='5fb1b9e8e1af060017709c6a_camp'
g_base_definitions[g_str_5fb1b9e8e1af060017709c6a_camp]={
  id=g_str_5fb1b9e8e1af060017709c6a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e8e1af060017709c6a']={
  data={
    name='Free Company  1357 to 1410 AD',
    id='5fb1b9e8e1af060017709c6a',
    army_id='5fb1b9e8e1af060017709c6a'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d4],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d9],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0dc],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c6a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c6a"] = army["5fb1b9e8e1af060017709c6a"]
army['5fb1b9e8e1af060017709c6a_1357_1363']={
  data={
    name='Free Company 1357 AD to 1363 AD',
    id='5fb1b9e8e1af060017709c6a_1357_1363',
    army_id='5fb1b9e8e1af060017709c6a'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d4],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d9],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0dc],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c6a_camp],
}
army['5fb1b9e8e1af060017709c6a_1364_1410']={
  data={
    name='Free Company 1364 AD to 1410 AD',
    id='5fb1b9e8e1af060017709c6a_1364_1410',
    army_id='5fb1b9e8e1af060017709c6a'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d1_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d4],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d6_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0d9],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c6a_camp],
}
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Free Company  1357 to 1410 AD"] = army["5fb1b9e8e1af060017709c6a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Free Company  1357 to 1410 AD"] = army["5fb1b9e8e1af060017709c6a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Free Company  1357 to 1410 AD"] = army["5fb1b9e8e1af060017709c6a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c6a"] = {}
army_dates["5fb1b9e8e1af060017709c6a"]["1357 AD to 1410 AD"] ="5fb1b9e8e1af060017709c6a"
army_dates["5fb1b9e8e1af060017709c6a"]["1357 AD to 1363 AD"] ="5fb1b9e8e1af060017709c6a_1357_1363"
army_dates["5fb1b9e8e1af060017709c6a"]["1364 AD to 1410 AD"] ="5fb1b9e8e1af060017709c6a_1364_1410"
