-- 5fb1b9eae1af060017709dca Medieval Danish and Union of Kalmar  1350 to 1523 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba36e1af06001770e6b2']= {
  min=0,
  max=1,
  description='Fraelse',
}
g_troop_entry['5fb1ba36e1af06001770e6b3']= {
  troop_option='5fb1ba36e1af06001770e6b2',
  troopTypeCode='KNT',
}
g_troop_option['5fb1ba36e1af06001770e6b4']= {
  min=0,
  max=1,
  description='German mercenary men-at-arms',
}
g_troop_entry['5fb1ba36e1af06001770e6b5']= {
  troop_option='5fb1ba36e1af06001770e6b4',
  troopTypeCode='KNT',
}
g_troop_option['5fb1ba36e1af06001770e6b6']= {
  min=0,
  max=1,
  description='Smaasvenner',
}
g_troop_entry['5fb1ba36e1af06001770e6b7']= {
  troop_option='5fb1ba36e1af06001770e6b6',
  troopTypeCode='BAD',
}
g_troop_option['5fb1ba36e1af06001770e6b8']= {
  min=0,
  max=1,
  description='Skyttar armored crossbowmen on horses',
}
g_troop_entry['5fb1ba36e1af06001770e6b9']= {
  troop_option='5fb1ba36e1af06001770e6b8',
  troopTypeCode='BAD',
}
g_troop_option['5fb1ba36e1af06001770e6ba']= {
  min=6,
  max=13,
  description='Landevaernet',
  core='all',
}
g_troop_entry['5fb1ba36e1af06001770e6bb']= {
  troop_option='5fb1ba36e1af06001770e6ba',
  troopTypeCode='HFT',
}
g_troop_option['5fb1ba36e1af06001770e6bc']= {
  min=2,
  max=4,
  description='Obudshaer halberdiers',
}
g_troop_entry['5fb1ba36e1af06001770e6bd']= {
  troop_option='5fb1ba36e1af06001770e6bc',
  troopTypeCode='RDR',
}
g_troop_option['5fb1ba36e1af06001770e6be']= {
  min=0,
  max=2,
  description='Obudshaer crossbowmen',
}
g_troop_entry['5fb1ba36e1af06001770e6bf']= {
  troop_option='5fb1ba36e1af06001770e6be',
  troopTypeCode='ARC',
}
g_troop_option['5fb1ba36e1af06001770e6c0']= {
  min=0,
  max=1,
  description='Handgunners',
  startDate=1391,
  endDate=1523,
}
g_troop_entry['5fb1ba36e1af06001770e6c2']= {
  troop_option='5fb1ba36e1af06001770e6c0',
  troopTypeCode='SKM',
}
g_troop_option['5fb1ba36e1af06001770e6c3']= {
  min=1,
  max=4,
  description='Landsknechts',
  core='all',
  startDate=1494,
  endDate=1523,
}
g_troop_entry['5fb1ba36e1af06001770e6c5']= {
  troop_option='5fb1ba36e1af06001770e6c3',
  troopTypeCode='PIK',
}
g_str_5fb1ba36e1af06001770e6b3_general='5fb1ba36e1af06001770e6b3_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general]={
  id=g_str_5fb1ba36e1af06001770e6b3_general,
  name='Knights General',
  min=0,
  max=1,
  description='Fraelse',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba36e1af06001770e6b3='5fb1ba36e1af06001770e6b3'
g_base_definitions[g_str_5fb1ba36e1af06001770e6b3]={
  id=g_str_5fb1ba36e1af06001770e6b3,
  name='Knights',
  min=0,
  max=1,
  description='Fraelse',
  troop_type="Knights",
}
g_str_5fb1ba36e1af06001770e6b5_general='5fb1ba36e1af06001770e6b5_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general]={
  id=g_str_5fb1ba36e1af06001770e6b5_general,
  name='Knights General',
  min=0,
  max=1,
  description='German mercenary men-at-arms',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba36e1af06001770e6b5='5fb1ba36e1af06001770e6b5'
g_base_definitions[g_str_5fb1ba36e1af06001770e6b5]={
  id=g_str_5fb1ba36e1af06001770e6b5,
  name='Knights',
  min=0,
  max=1,
  description='German mercenary men-at-arms',
  troop_type="Knights",
}
g_str_5fb1ba36e1af06001770e6b7='5fb1ba36e1af06001770e6b7'
g_base_definitions[g_str_5fb1ba36e1af06001770e6b7]={
  id=g_str_5fb1ba36e1af06001770e6b7,
  name='Bad Horse',
  min=0,
  max=1,
  description='Smaasvenner',
  troop_type="Bad Horse",
}
g_str_5fb1ba36e1af06001770e6b9='5fb1ba36e1af06001770e6b9'
g_base_definitions[g_str_5fb1ba36e1af06001770e6b9]={
  id=g_str_5fb1ba36e1af06001770e6b9,
  name='Bad Horse',
  min=0,
  max=1,
  description='Skyttar armored crossbowmen on horses',
  troop_type="Bad Horse",
}
g_str_5fb1ba36e1af06001770e6bb_general='5fb1ba36e1af06001770e6bb_general'
g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general]={
  id=g_str_5fb1ba36e1af06001770e6bb_general,
  name='Heavy Foot General',
  min=6,
  max=1,
  description='Landevaernet',
  general=true,
  troop_type="Heavy Foot",
}
g_str_5fb1ba36e1af06001770e6bb='5fb1ba36e1af06001770e6bb'
g_base_definitions[g_str_5fb1ba36e1af06001770e6bb]={
  id=g_str_5fb1ba36e1af06001770e6bb,
  name='Heavy Foot',
  min=6,
  max=13,
  description='Landevaernet',
  troop_type="Heavy Foot",
}
g_str_5fb1ba36e1af06001770e6bd='5fb1ba36e1af06001770e6bd'
g_base_definitions[g_str_5fb1ba36e1af06001770e6bd]={
  id=g_str_5fb1ba36e1af06001770e6bd,
  name='Raiders',
  min=2,
  max=4,
  description='Obudshaer halberdiers',
  troop_type="Raiders",
}
g_str_5fb1ba36e1af06001770e6bf='5fb1ba36e1af06001770e6bf'
g_base_definitions[g_str_5fb1ba36e1af06001770e6bf]={
  id=g_str_5fb1ba36e1af06001770e6bf,
  name='Archers',
  min=0,
  max=2,
  description='Obudshaer crossbowmen',
  troop_type="Archers",
}
g_str_5fb1ba36e1af06001770e6c2='5fb1ba36e1af06001770e6c2'
g_base_definitions[g_str_5fb1ba36e1af06001770e6c2]={
  id=g_str_5fb1ba36e1af06001770e6c2,
  name='Skirmishers',
  min=0,
  max=1,
  description='Handgunners',
  troop_type="Skirmishers",
}
g_str_5fb1ba36e1af06001770e6c5='5fb1ba36e1af06001770e6c5'
g_base_definitions[g_str_5fb1ba36e1af06001770e6c5]={
  id=g_str_5fb1ba36e1af06001770e6c5,
  name='Pikes',
  min=1,
  max=4,
  description='Landsknechts',
  troop_type="Pikes",
}
g_str_5fb1b9eae1af060017709dca_camp='5fb1b9eae1af060017709dca_camp'
g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp]={
  id=g_str_5fb1b9eae1af060017709dca_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9eae1af060017709dca']={
  data={
    name='Medieval Danish and Union of Kalmar  1350 to 1523 AD',
    id='5fb1b9eae1af060017709dca',
    army_id='5fb1b9eae1af060017709dca'
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bd],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bf],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c5],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dca"] = army["5fb1b9eae1af060017709dca"]
army['5fb1b9eae1af060017709dca_1350_1390']={
  data={
    name='Medieval Danish and Union of Kalmar 1350 AD to 1390 AD',
    id='5fb1b9eae1af060017709dca_1350_1390',
    army_id='5fb1b9eae1af060017709dca'
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bd],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bf],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c5],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
army['5fb1b9eae1af060017709dca_1391_1493']={
  data={
    name='Medieval Danish and Union of Kalmar 1391 AD to 1493 AD',
    id='5fb1b9eae1af060017709dca_1391_1493',
    army_id='5fb1b9eae1af060017709dca'
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bd],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bf],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c5],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
army['5fb1b9eae1af060017709dca_1494_1523']={
  data={
    name='Medieval Danish and Union of Kalmar 1494 AD to 1523 AD',
    id='5fb1b9eae1af060017709dca_1494_1523',
    army_id='5fb1b9eae1af060017709dca'
  },
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b3],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b5],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b7],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6b9],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb_general],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bb],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bd],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6bf],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c2],
  g_base_definitions[g_str_5fb1ba36e1af06001770e6c5],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Danish and Union of Kalmar  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dca"] = {}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1523 AD"] ="5fb1b9eae1af060017709dca"
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1390 AD"] ="5fb1b9eae1af060017709dca_1350_1390"
army_dates["5fb1b9eae1af060017709dca"]["1391 AD to 1493 AD"] ="5fb1b9eae1af060017709dca_1391_1493"
army_dates["5fb1b9eae1af060017709dca"]["1494 AD to 1523 AD"] ="5fb1b9eae1af060017709dca_1494_1523"
