-- 5fb1b9f1e1af06001770a1c9 Rouran  308 to 555 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3fe1af06001770f694_general='5fb1ba3fe1af06001770f694_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f694_general]={
  id=g_str_5fb1ba3fe1af06001770f694_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Elite Cavalary",
}
g_str_5fb1ba3fe1af06001770f694='5fb1ba3fe1af06001770f694'
g_base_definitions[g_str_5fb1ba3fe1af06001770f694]={
  id=g_str_5fb1ba3fe1af06001770f694,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Noble horsemen',
  troop_type="Elite Cavalary",
}
g_str_5fb1ba3fe1af06001770f696='5fb1ba3fe1af06001770f696'
g_base_definitions[g_str_5fb1ba3fe1af06001770f696]={
  id=g_str_5fb1ba3fe1af06001770f696,
  name='Horse Bow',
  min=4,
  max=11,
  description='Horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba3fe1af06001770f698='5fb1ba3fe1af06001770f698'
g_base_definitions[g_str_5fb1ba3fe1af06001770f698]={
  id=g_str_5fb1ba3fe1af06001770f698,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba3fe1af06001770f69a='5fb1ba3fe1af06001770f69a'
g_base_definitions[g_str_5fb1ba3fe1af06001770f69a]={
  id=g_str_5fb1ba3fe1af06001770f69a,
  name='Horde',
  min=0,
  max=2,
  description='Serfs, slaves or camp followers',
  troop_type="Horde",
}
g_str_5fb1ba3fe1af06001770f69b='5fb1ba3fe1af06001770f69b'
g_base_definitions[g_str_5fb1ba3fe1af06001770f69b]={
  id=g_str_5fb1ba3fe1af06001770f69b,
  name='Rabble',
  min=0,
  max=2,
  description='Serfs, slaves or camp followers',
  troop_type="Rabble",
}
g_str_5fb1b9f1e1af06001770a1c9_camp='5fb1b9f1e1af06001770a1c9_camp'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1c9_camp]={
  id=g_str_5fb1b9f1e1af06001770a1c9_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f1e1af06001770a1c9_camp_pack_train='5fb1b9f1e1af06001770a1c9_camp_pack_train'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1c9_camp_pack_train]={
  id=g_str_5fb1b9f1e1af06001770a1c9_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9f1e1af06001770a1c9']={
  data={
    name='Rouran  308 to 555 AD'
  },
  g_base_definitions[g_str_5fb1ba3fe1af06001770f694_general],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f694],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f696],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f698],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f69a],
  g_base_definitions[g_str_5fb1ba3fe1af06001770f69b],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1c9_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1c9_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1c9"] = army["5fb1b9f1e1af06001770a1c9"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Rouran  308 to 555 AD"] = army["5fb1b9f1e1af06001770a1c9"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Rouran  308 to 555 AD"] = army["5fb1b9f1e1af06001770a1c9"]
