troop_options['615351b303385c0016b88731'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
troop_options['615351b303385c0016b88733'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
troop_options['615351b303385c0016b88735'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
troop_options['615351b303385c0016b88737'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
troop_options['615351b303385c0016b88739'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
troop_options['615351b303385c0016b8873b'] = {
  min=5,
  max=10,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
troop_options['615351b303385c0016b8873d'] = {
  min=2,
  max=8,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
troop_options['615351b303385c0016b8873f'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-206,
    endDate=-111,
  }
}
-- allies
