troop_options['5fb1ba31e1af06001770dc8b'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dc8d'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1181,
    endDate=1295,
  }
}
troop_options['5fb1ba31e1af06001770dc91'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1296,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dc95'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dc98'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dc9b'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dc9d'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dca0'] = {
  min=0,
  max=10,
  dateRange={
    startDate=1252,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dca3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dca5'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
troop_options['5fb1ba31e1af06001770dca7'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1180,
    endDate=1321,
  }
}
-- allies
