g_str_5fb1ba44e1af06001770fdf0_general='5fb1ba44e1af06001770fdf0_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf0_general]={
  id=g_str_5fb1ba44e1af06001770fdf0_general,
  name='Archers General',
  min=0,
  max=1,
  description='Noble bowmen',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba44e1af06001770fdef",
}
g_str_5fb1ba44e1af06001770fdf0='5fb1ba44e1af06001770fdf0'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf0]={
  id=g_str_5fb1ba44e1af06001770fdf0,
  name='Archers',
  min=0,
  max=4,
  description='Noble bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba44e1af06001770fdef",
}
g_str_5fb1ba44e1af06001770fdf2_general='5fb1ba44e1af06001770fdf2_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf2_general]={
  id=g_str_5fb1ba44e1af06001770fdf2_general,
  name='Light Spear General',
  min=8,
  max=1,
  description='Infantry armed with long spear and pike',
  general=true,
  troop_type="Light Spear",
  troop_option_id="5fb1ba44e1af06001770fdf1",
}
g_str_5fb1ba44e1af06001770fdf2='5fb1ba44e1af06001770fdf2'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf2]={
  id=g_str_5fb1ba44e1af06001770fdf2,
  name='Light Spear',
  min=8,
  max=14,
  description='Infantry armed with long spear and pike',
  troop_type="Light Spear",
  troop_option_id="5fb1ba44e1af06001770fdf1",
}
g_str_5fb1ba44e1af06001770fdf5='5fb1ba44e1af06001770fdf5'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf5]={
  id=g_str_5fb1ba44e1af06001770fdf5,
  name='Skirmishers',
  min=2,
  max=5,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fdf4",
}
g_str_5fb1ba44e1af06001770fdf8='5fb1ba44e1af06001770fdf8'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf8]={
  id=g_str_5fb1ba44e1af06001770fdf8,
  name='Skirmishers',
  min=0,
  max=2,
  description='Scouts',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fdf7",
}
g_str_5fb1b9f5e1af06001770a41c_camp='5fb1b9f5e1af06001770a41c_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a41c_camp]={
  id=g_str_5fb1b9f5e1af06001770a41c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba44e1af06001770fdf0_general='5fb1ba44e1af06001770fdf0_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf0_general]={
  id=g_str_5fb1ba44e1af06001770fdf0_general,
  name='Archers General',
  min=0,
  max=1,
  description='Noble bowmen',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba44e1af06001770fdef",
}
g_str_5fb1ba44e1af06001770fdf0='5fb1ba44e1af06001770fdf0'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf0]={
  id=g_str_5fb1ba44e1af06001770fdf0,
  name='Archers',
  min=0,
  max=4,
  description='Noble bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba44e1af06001770fdef",
}
g_str_5fb1ba44e1af06001770fdf2_general='5fb1ba44e1af06001770fdf2_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf2_general]={
  id=g_str_5fb1ba44e1af06001770fdf2_general,
  name='Light Spear General',
  min=8,
  max=1,
  description='Infantry armed with long spear and pike',
  general=true,
  troop_type="Light Spear",
  troop_option_id="5fb1ba44e1af06001770fdf1",
}
g_str_5fb1ba44e1af06001770fdf2='5fb1ba44e1af06001770fdf2'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf2]={
  id=g_str_5fb1ba44e1af06001770fdf2,
  name='Light Spear',
  min=8,
  max=14,
  description='Infantry armed with long spear and pike',
  troop_type="Light Spear",
  troop_option_id="5fb1ba44e1af06001770fdf1",
}
g_str_5fb1ba44e1af06001770fdf5='5fb1ba44e1af06001770fdf5'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf5]={
  id=g_str_5fb1ba44e1af06001770fdf5,
  name='Skirmishers',
  min=2,
  max=5,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fdf4",
}
g_str_5fb1ba44e1af06001770fdf8='5fb1ba44e1af06001770fdf8'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf8]={
  id=g_str_5fb1ba44e1af06001770fdf8,
  name='Skirmishers',
  min=0,
  max=2,
  description='Scouts',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fdf7",
}
g_str_5fb1b9f5e1af06001770a41c_camp='5fb1b9f5e1af06001770a41c_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a41c_camp]={
  id=g_str_5fb1b9f5e1af06001770a41c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba44e1af06001770fdf0_general='5fb1ba44e1af06001770fdf0_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf0_general]={
  id=g_str_5fb1ba44e1af06001770fdf0_general,
  name='Archers General',
  min=0,
  max=1,
  description='Noble bowmen',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba44e1af06001770fdef",
}
g_str_5fb1ba44e1af06001770fdf0='5fb1ba44e1af06001770fdf0'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf0]={
  id=g_str_5fb1ba44e1af06001770fdf0,
  name='Archers',
  min=0,
  max=4,
  description='Noble bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba44e1af06001770fdef",
}
g_str_5fb1ba44e1af06001770fdf2_general='5fb1ba44e1af06001770fdf2_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf2_general]={
  id=g_str_5fb1ba44e1af06001770fdf2_general,
  name='Light Spear General',
  min=8,
  max=1,
  description='Infantry armed with long spear and pike',
  general=true,
  troop_type="Light Spear",
  troop_option_id="5fb1ba44e1af06001770fdf1",
}
g_str_5fb1ba44e1af06001770fdf2='5fb1ba44e1af06001770fdf2'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf2]={
  id=g_str_5fb1ba44e1af06001770fdf2,
  name='Light Spear',
  min=8,
  max=14,
  description='Infantry armed with long spear and pike',
  troop_type="Light Spear",
  troop_option_id="5fb1ba44e1af06001770fdf1",
}
g_str_5fb1ba44e1af06001770fdf5='5fb1ba44e1af06001770fdf5'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf5]={
  id=g_str_5fb1ba44e1af06001770fdf5,
  name='Skirmishers',
  min=2,
  max=5,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fdf4",
}
g_str_5fb1ba44e1af06001770fdf8='5fb1ba44e1af06001770fdf8'
g_base_definitions[g_str_5fb1ba44e1af06001770fdf8]={
  id=g_str_5fb1ba44e1af06001770fdf8,
  name='Skirmishers',
  min=0,
  max=2,
  description='Scouts',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fdf7",
}
g_str_5fb1b9f5e1af06001770a41c_camp='5fb1b9f5e1af06001770a41c_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a41c_camp]={
  id=g_str_5fb1b9f5e1af06001770a41c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
