-- 5fb1b9dbe1af0600177094ef Early Hoplite Greek: Aitolian or Akarnanian  669 to 449 BC

army['5fb1b9dbe1af0600177094ef']={
  data={
    name='Early Hoplite Greek: Aitolian or Akarnanian  669 to 449 BC',
    id='5fb1b9dbe1af0600177094ef',
    dateRange={
      startDate=-669,
      endDate=-449,
    }
  },
  g_base_definitions[g_str_5fb1ba25e1af06001770c5c1_general],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5c1],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5c3_general],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5c3],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5c5_general],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5c5],
  g_base_definitions[g_str_5fb1ba25e1af06001770c5c7],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094ef_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094ef"] = army["5fb1b9dbe1af0600177094ef"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Hoplite Greek: Aitolian or Akarnanian  669 to 449 BC"] = army["5fb1b9dbe1af0600177094ef"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hoplite Greek: Aitolian or Akarnanian  669 to 449 BC"] = army["5fb1b9dbe1af0600177094ef"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094ef"] = {}
army_dates["5fb1b9dbe1af0600177094ef"]["669 BC to 449 BC"] = {
  startDate=-669,
  endDate=-449
}
