-- 5fb1b9e4e1af060017709a2f Feudal Serbian  799 to 1180 AD

army['5fb1b9e4e1af060017709a2f']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Feudal Serbian  799 to 1180 AD',
    id='5fb1b9e4e1af060017709a2f',
    dateRange={
      startDate=799,
      endDate=1180,
    },
  },
  g_base_definitions[g_str_615351a803385c0016b8697c_general],
  g_base_definitions[g_str_615351a803385c0016b8697c],
  g_base_definitions[g_str_615351a803385c0016b8697e],
  g_base_definitions[g_str_615351a803385c0016b86980],
  g_base_definitions[g_str_615351a803385c0016b86982],
  g_base_definitions[g_str_615351a803385c0016b86984],
  g_base_definitions[g_str_615351a803385c0016b86986],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a2f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a2f"] = army["5fb1b9e4e1af060017709a2f"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Feudal Serbian  799 to 1180 AD"] = army["5fb1b9e4e1af060017709a2f"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Feudal Serbian  799 to 1180 AD"] = army["5fb1b9e4e1af060017709a2f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Feudal Serbian  799 to 1180 AD"] = army["5fb1b9e4e1af060017709a2f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a2f"] = {}
army_dates["5fb1b9e4e1af060017709a2f"]["799 AD to 1180 AD"] = {
  startDate=799,
  endDate=1180
}
