-- 5fb1b9dae1af0600177093d1 Early Philistine  1166 to 1100 BC

army['5fb1b9dae1af0600177093d1']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Philistine  1166 to 1100 BC',
    id='5fb1b9dae1af0600177093d1',
    dateRange={
      startDate=-1166,
      endDate=-1100,
    }
  },
  g_base_definitions[g_str_5fb1ba21e1af06001770c16a_general],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16a],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16c_general],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16c],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16e],
  g_base_definitions[g_str_5fb1ba21e1af06001770c170],
  g_base_definitions[g_str_5fb1ba21e1af06001770c172],
  g_base_definitions[g_str_5fb1ba21e1af06001770c174],
  g_base_definitions[g_str_5fb1ba21e1af06001770c176],
  g_base_definitions[g_str_5fb1ba21e1af06001770c178],
  g_base_definitions[g_str_5fb1ba21e1af06001770c179],
  g_base_definitions[g_str_5fb1b9dae1af0600177093d1_camp],
  g_base_definitions[g_str_5fb1b9dae1af0600177093d1_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093d1"] = army["5fb1b9dae1af0600177093d1"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Philistine  1166 to 1100 BC"] = army["5fb1b9dae1af0600177093d1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Philistine  1166 to 1100 BC"] = army["5fb1b9dae1af0600177093d1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af0600177093d1"] = {}
army_dates["5fb1b9dae1af0600177093d1"]["1166 BC to 1100 BC"] = {
  startDate=-1166,
  endDate=-1100
}
