-- 5fb1b9f6e1af06001770a4b2 Caribbean Indians: Igneri  1200 to 1520 AD

army['5fb1b9f6e1af06001770a4b2']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Caribbean Indians: Igneri  1200 to 1520 AD',
    id='5fb1b9f6e1af06001770a4b2',
    dateRange={
      startDate=1200,
      endDate=1520,
    },
    ambush=true,  },
  g_base_definitions[g_str_615351b703385c0016b88f3f_general],
  g_base_definitions[g_str_615351b703385c0016b88f3f],
  g_base_definitions[g_str_615351b703385c0016b88f41],
  g_base_definitions[g_str_615351b703385c0016b88f43],
  g_base_definitions[g_str_615351b703385c0016b88f45],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a4b2_camp],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a4b2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a4b2"] = army["5fb1b9f6e1af06001770a4b2"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Caribbean Indians: Igneri  1200 to 1520 AD"] = army["5fb1b9f6e1af06001770a4b2"]
if nil == armies["Caribbean"] then
  armies["Caribbean"] ={}
end
armies["Caribbean"]["Caribbean Indians: Igneri  1200 to 1520 AD"] = army["5fb1b9f6e1af06001770a4b2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Caribbean Indians: Igneri  1200 to 1520 AD"] = army["5fb1b9f6e1af06001770a4b2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a4b2"] = {}
army_dates["5fb1b9f6e1af06001770a4b2"]["1200 AD to 1520 AD"] = {
  startDate=1200,
  endDate=1520
}
