-- 5fb1b9dce1af06001770957a Post-Zama Carthaginian  201 to 146 BC

army['5fb1b9dce1af06001770957a']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Post-Zama Carthaginian  201 to 146 BC',
    id='5fb1b9dce1af06001770957a',
    dateRange={
      startDate=-201,
      endDate=-146,
    }
  },
  g_base_definitions[g_str_5fb1ba26e1af06001770c828_general],
  g_base_definitions[g_str_5fb1ba26e1af06001770c828],
  g_base_definitions[g_str_5fb1ba26e1af06001770c82a],
  g_base_definitions[g_str_5fb1ba26e1af06001770c82c],
  g_base_definitions[g_str_5fb1ba26e1af06001770c82e],
  g_base_definitions[g_str_5fb1ba26e1af06001770c830],
  g_base_definitions[g_str_5fb1ba26e1af06001770c833],
  g_base_definitions[g_str_5fb1b9dce1af06001770957a_camp],
  g_base_definitions[g_str_5fb1b9dce1af06001770957a_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af06001770957a"] = army["5fb1b9dce1af06001770957a"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Post-Zama Carthaginian  201 to 146 BC"] = army["5fb1b9dce1af06001770957a"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Post-Zama Carthaginian  201 to 146 BC"] = army["5fb1b9dce1af06001770957a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Post-Zama Carthaginian  201 to 146 BC"] = army["5fb1b9dce1af06001770957a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af06001770957a"] = {}
army_dates["5fb1b9dce1af06001770957a"]["201 BC to 146 BC"] = {
  startDate=-201,
  endDate=-146
}
