-- 5fb1b9e5e1af060017709a9f Scandinavian Leidang  790 to 1280 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba30e1af06001770da73_general='5fb1ba30e1af06001770da73_general'
g_base_definitions[g_str_5fb1ba30e1af06001770da73_general]={
  id=g_str_5fb1ba30e1af06001770da73_general,
  name='Elite Foot General',
  min=1,
  max=1,
  description='Huscarles',
  general=true,
  troop_type="Elite Foot",
}
g_str_5fb1ba30e1af06001770da73='5fb1ba30e1af06001770da73'
g_base_definitions[g_str_5fb1ba30e1af06001770da73]={
  id=g_str_5fb1ba30e1af06001770da73,
  name='Elite Foot',
  min=1,
  max=3,
  description='Huscarles',
  troop_type="Elite Foot",
}
g_str_5fb1ba30e1af06001770da76_general='5fb1ba30e1af06001770da76_general'
g_base_definitions[g_str_5fb1ba30e1af06001770da76_general]={
  id=g_str_5fb1ba30e1af06001770da76_general,
  name='Knights General',
  min=0,
  max=1,
  description='Laenstropperne',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba30e1af06001770da76_general_dismounted='5fb1ba30e1af06001770da76_general_dismounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da76_general_dismounted]={
  id=g_str_5fb1ba30e1af06001770da76_general_dismounted,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Laenstropperne\nDeployment dismounted from Knights General',
  points=4,
  general=true,
  troop_type="Elite Foot",
}
g_5fb1ba30e1af06001770da76_general_dismounted=g_base_definitions[g_str_5fb1ba30e1af06001770da76_general_dismounted]
g_str_5fb1ba30e1af06001770da76_general_mounted='5fb1ba30e1af06001770da76_general_mounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da76_general_mounted]={
  id=g_str_5fb1ba30e1af06001770da76_general_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='Laenstropperne\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba30e1af06001770da76_general_dismounted,
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba30e1af06001770da76='5fb1ba30e1af06001770da76'
g_base_definitions[g_str_5fb1ba30e1af06001770da76]={
  id=g_str_5fb1ba30e1af06001770da76,
  name='Knights',
  min=0,
  max=1,
  description='Laenstropperne',
  troop_type="Knights",
}
g_str_5fb1ba30e1af06001770da76_dismounted='5fb1ba30e1af06001770da76_dismounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da76_dismounted]={
  id=g_str_5fb1ba30e1af06001770da76_dismounted,
  name='Elite Foot',
  min=0,
  max=1,
  description='Laenstropperne\nDeployment dismounted from Knights',
  points=4,
  troop_type="Elite Foot",
}
g_5fb1ba30e1af06001770da76_dismounted=g_base_definitions[g_str_5fb1ba30e1af06001770da76_dismounted]
g_str_5fb1ba30e1af06001770da76_mounted='5fb1ba30e1af06001770da76_mounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da76_mounted]={
  id=g_str_5fb1ba30e1af06001770da76_mounted,
  name='Knights',
  min=0,
  max=1,
  description='Laenstropperne\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba30e1af06001770da76_dismounted,
  troop_type="Knights",
}
g_str_5fb1ba30e1af06001770da7a_general='5fb1ba30e1af06001770da7a_general'
g_base_definitions[g_str_5fb1ba30e1af06001770da7a_general]={
  id=g_str_5fb1ba30e1af06001770da7a_general,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Huscarles on horses',
  general=true,
  troop_type="Bad Horse",
}
g_str_5fb1ba30e1af06001770da7a_general_dismounted='5fb1ba30e1af06001770da7a_general_dismounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da7a_general_dismounted]={
  id=g_str_5fb1ba30e1af06001770da7a_general_dismounted,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Huscarles on horses\nDeployment dismounted from Bad Horse General',
  points=4,
  general=true,
  troop_type="Elite Foot",
}
g_5fb1ba30e1af06001770da7a_general_dismounted=g_base_definitions[g_str_5fb1ba30e1af06001770da7a_general_dismounted]
g_str_5fb1ba30e1af06001770da7a_general_mounted='5fb1ba30e1af06001770da7a_general_mounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da7a_general_mounted]={
  id=g_str_5fb1ba30e1af06001770da7a_general_mounted,
  name='Bad Horse General',
  min=0,
  max=1,
  description='Huscarles on horses\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba30e1af06001770da7a_general_dismounted,
  general=true,
  troop_type="Bad Horse",
}
g_str_5fb1ba30e1af06001770da7a='5fb1ba30e1af06001770da7a'
g_base_definitions[g_str_5fb1ba30e1af06001770da7a]={
  id=g_str_5fb1ba30e1af06001770da7a,
  name='Bad Horse',
  min=0,
  max=1,
  description='Huscarles on horses',
  troop_type="Bad Horse",
}
g_str_5fb1ba30e1af06001770da7a_dismounted='5fb1ba30e1af06001770da7a_dismounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da7a_dismounted]={
  id=g_str_5fb1ba30e1af06001770da7a_dismounted,
  name='Elite Foot',
  min=0,
  max=1,
  description='Huscarles on horses\nDeployment dismounted from Bad Horse',
  points=4,
  troop_type="Elite Foot",
}
g_5fb1ba30e1af06001770da7a_dismounted=g_base_definitions[g_str_5fb1ba30e1af06001770da7a_dismounted]
g_str_5fb1ba30e1af06001770da7a_mounted='5fb1ba30e1af06001770da7a_mounted'
g_base_definitions[g_str_5fb1ba30e1af06001770da7a_mounted]={
  id=g_str_5fb1ba30e1af06001770da7a_mounted,
  name='Bad Horse',
  min=0,
  max=1,
  description='Huscarles on horses\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba30e1af06001770da7a_dismounted,
  troop_type="Bad Horse",
}
g_str_5fb1ba30e1af06001770da7e_general='5fb1ba30e1af06001770da7e_general'
g_base_definitions[g_str_5fb1ba30e1af06001770da7e_general]={
  id=g_str_5fb1ba30e1af06001770da7e_general,
  name='Elite Foot General',
  min=1,
  max=1,
  description='Huscarles',
  general=true,
  troop_type="Elite Foot",
}
g_str_5fb1ba30e1af06001770da7e='5fb1ba30e1af06001770da7e'
g_base_definitions[g_str_5fb1ba30e1af06001770da7e]={
  id=g_str_5fb1ba30e1af06001770da7e,
  name='Elite Foot',
  min=1,
  max=2,
  description='Huscarles',
  troop_type="Elite Foot",
}
g_str_5fb1ba30e1af06001770da80='5fb1ba30e1af06001770da80'
g_base_definitions[g_str_5fb1ba30e1af06001770da80]={
  id=g_str_5fb1ba30e1af06001770da80,
  name='Heavy Foot',
  min=5,
  max=13,
  description='Bondi spearmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba30e1af06001770da82='5fb1ba30e1af06001770da82'
g_base_definitions[g_str_5fb1ba30e1af06001770da82]={
  id=g_str_5fb1ba30e1af06001770da82,
  name='Light Foot',
  min=0,
  max=8,
  description='Finn light infantry',
  troop_type="Light Foot",
}
g_str_5fb1ba30e1af06001770da84='5fb1ba30e1af06001770da84'
g_base_definitions[g_str_5fb1ba30e1af06001770da84]={
  id=g_str_5fb1ba30e1af06001770da84,
  name='Archers',
  min=1,
  max=3,
  description='Bondi bowmen',
  troop_type="Archers",
}
g_str_5fb1ba30e1af06001770da86='5fb1ba30e1af06001770da86'
g_base_definitions[g_str_5fb1ba30e1af06001770da86]={
  id=g_str_5fb1ba30e1af06001770da86,
  name='Horde',
  min=0,
  max=1,
  description='Thralls and dregs',
  troop_type="Horde",
}
g_str_5fb1ba30e1af06001770da88='5fb1ba30e1af06001770da88'
g_base_definitions[g_str_5fb1ba30e1af06001770da88]={
  id=g_str_5fb1ba30e1af06001770da88,
  name='Raiders',
  min=0,
  max=1,
  description='Viking freelance marauders',
  troop_type="Raiders",
}
g_str_5fb1b9e5e1af060017709a9f_camp='5fb1b9e5e1af060017709a9f_camp'
g_base_definitions[g_str_5fb1b9e5e1af060017709a9f_camp]={
  name='Camp',
  id=g_str_5fb1b9e5e1af060017709a9f_camp,
  min=1,
  max=1,
}
army['5fb1b9e5e1af060017709a9f']={
  data={
    name='Scandinavian Leidang  790 to 1280 AD'
  },
  g_base_definitions[g_str_5fb1b9e5e1af060017709a9f_camp],
  g_base_definitions[g_str_5fb1ba30e1af06001770da73_general],
  g_base_definitions[g_str_5fb1ba30e1af06001770da73],
  g_base_definitions[g_str_5fb1ba30e1af06001770da76_general],
  g_base_definitions[g_str_5fb1ba30e1af06001770da76_general_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da76_general_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da76],
  g_base_definitions[g_str_5fb1ba30e1af06001770da76_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da76_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7a_general],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7a_general_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7a_general_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7a],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7a_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7a_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7e_general],
  g_base_definitions[g_str_5fb1ba30e1af06001770da7e],
  g_base_definitions[g_str_5fb1ba30e1af06001770da80],
  g_base_definitions[g_str_5fb1ba30e1af06001770da82],
  g_base_definitions[g_str_5fb1ba30e1af06001770da84],
  g_base_definitions[g_str_5fb1ba30e1af06001770da86],
  g_base_definitions[g_str_5fb1ba30e1af06001770da88],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709a9f"] = army["5fb1b9e5e1af060017709a9f"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Scandinavian Leidang  790 to 1280 AD"] = army["5fb1b9e5e1af060017709a9f"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Scandinavian Leidang  790 to 1280 AD"] = army["5fb1b9e5e1af060017709a9f"]
