troop_options['615351aa03385c0016b86cd9'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1100,
    endDate=1197,
  }
}
troop_options['615351aa03385c0016b86cdc'] = {
  min=5,
  max=10,
  dateRange={
    startDate=1100,
    endDate=1197,
  }
}
troop_options['615351aa03385c0016b86cdf'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1100,
    endDate=1197,
  }
}
troop_options['615351aa03385c0016b86ce1'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1100,
    endDate=1197,
  }
}
-- allies
