troop_options['5fb1ba26e1af06001770c74f'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
troop_options['5fb1ba26e1af06001770c751'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
troop_options['5fb1ba26e1af06001770c753'] = {
  min=6,
  max=10,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
troop_options['5fb1ba26e1af06001770c756'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
troop_options['5fb1ba26e1af06001770c758'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
troop_options['5fb1ba26e1af06001770c75a'] = {
  min=1,
  max=3,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
troop_options['5fb1ba26e1af06001770c75c'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
troop_options['5fb1ba26e1af06001770c75e'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-410,
    endDate=-210,
  }
}
-- allies
