troop_options['5fb1ba3fe1af06001770f6fd'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-202,
    endDate=-113,
  }
}
troop_options['5fb1ba3fe1af06001770f700'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f703'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f705'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f707'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f70a'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f70d'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f711'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-202,
    endDate=9,
  }
}
troop_options['5fb1ba3fe1af06001770f714'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f716'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f718'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f71a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
troop_options['5fb1ba3fe1af06001770f71c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-202,
    endDate=189,
  }
}
-- allies
