-- 5fb1b9f5e1af06001770a385 Early Settled Meso-American  1150 to 400 BC

army['5fb1b9f5e1af06001770a385']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
      'Hilly',
    },
    name='Early Settled Meso-American  1150 to 400 BC',
    id='5fb1b9f5e1af06001770a385',
    dateRange={
      startDate=-1150,
      endDate=-400,
    },
  },
  g_base_definitions[g_str_615351b603385c0016b88d66_general],
  g_base_definitions[g_str_615351b603385c0016b88d66],
  g_base_definitions[g_str_615351b603385c0016b88d68_general],
  g_base_definitions[g_str_615351b603385c0016b88d68],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a385_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a385"] = army["5fb1b9f5e1af06001770a385"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Early Settled Meso-American  1150 to 400 BC"] = army["5fb1b9f5e1af06001770a385"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Early Settled Meso-American  1150 to 400 BC"] = army["5fb1b9f5e1af06001770a385"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Settled Meso-American  1150 to 400 BC"] = army["5fb1b9f5e1af06001770a385"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a385"] = {}
army_dates["5fb1b9f5e1af06001770a385"]["1150 BC to 400 BC"] = {
  startDate=-1150,
  endDate=-400
}
