-- 5fb1b9e7e1af060017709bd9 Early Andalusian  711 to 764 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba32e1af06001770deb3_general='5fb1ba32e1af06001770deb3_general'
g_base_definitions[g_str_5fb1ba32e1af06001770deb3_general]={
  id=g_str_5fb1ba32e1af06001770deb3_general,
  name='Javelin Cavalry General',
  min=2,
  max=1,
  description='Arab, Andalusian, or Berber horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770deb3='5fb1ba32e1af06001770deb3'
g_base_definitions[g_str_5fb1ba32e1af06001770deb3]={
  id=g_str_5fb1ba32e1af06001770deb3,
  name='Javelin Cavalry',
  min=2,
  max=8,
  description='Arab, Andalusian, or Berber horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba32e1af06001770deb5='5fb1ba32e1af06001770deb5'
g_base_definitions[g_str_5fb1ba32e1af06001770deb5]={
  id=g_str_5fb1ba32e1af06001770deb5,
  name='Light Foot',
  min=0,
  max=15,
  description='Berber javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba32e1af06001770deb6='5fb1ba32e1af06001770deb6'
g_base_definitions[g_str_5fb1ba32e1af06001770deb6]={
  id=g_str_5fb1ba32e1af06001770deb6,
  name='Rabble',
  min=0,
  max=15,
  description='Berber javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba32e1af06001770deb8='5fb1ba32e1af06001770deb8'
g_base_definitions[g_str_5fb1ba32e1af06001770deb8]={
  id=g_str_5fb1ba32e1af06001770deb8,
  name='Skirmishers',
  min=0,
  max=3,
  description='Berber skirmishing bowmen or slingers',
  troop_type="Skirmishers",
}
g_str_5fb1ba32e1af06001770deba='5fb1ba32e1af06001770deba'
g_base_definitions[g_str_5fb1ba32e1af06001770deba]={
  id=g_str_5fb1ba32e1af06001770deba,
  name='Heavy Foot',
  min=3,
  max=4,
  description='Andalusian spearmen',
  troop_type="Heavy Foot",
}
g_str_5fb1ba32e1af06001770debd='5fb1ba32e1af06001770debd'
g_base_definitions[g_str_5fb1ba32e1af06001770debd]={
  id=g_str_5fb1ba32e1af06001770debd,
  name='Rabble',
  min=2,
  max=4,
  description='Andalusian bowmen and slingers',
  troop_type="Rabble",
}
g_str_5fb1b9e7e1af060017709bd9_camp='5fb1b9e7e1af060017709bd9_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709bd9_camp]={
  name='Camp',
  id=g_str_5fb1b9e7e1af060017709bd9_camp,
  min=1,
  max=1,
}
army['5fb1b9e7e1af060017709bd9']={
  data={
    name='Early Andalusian  711 to 764 AD'
  },
  g_base_definitions[g_str_5fb1b9e7e1af060017709bd9_camp],
  g_base_definitions[g_str_5fb1ba32e1af06001770dec0],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb3_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb3],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb5],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb6],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb8],
  g_base_definitions[g_str_5fb1ba32e1af06001770deba],
  g_base_definitions[g_str_5fb1ba32e1af06001770debd],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709bd9"] = army["5fb1b9e7e1af060017709bd9"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Andalusian  711 to 764 AD"] = army["5fb1b9e7e1af060017709bd9"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Early Andalusian  711 to 764 AD"] = army["5fb1b9e7e1af060017709bd9"]
