-- 5fb1b9e4e1af060017709a36 Italian Lombard  584 to 774 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba2fe1af06001770d90e_general='5fb1ba2fe1af06001770d90e_general'
g_base_definitions[g_str_5fb1ba2fe1af06001770d90e_general]={
  id=g_str_5fb1ba2fe1af06001770d90e_general,
  name='Knights General',
  min=3,
  max=1,
  description='Gastaldi, gasindii, and other first class mounted',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba2fe1af06001770d90d",
}
g_str_5fb1ba2fe1af06001770d90e='5fb1ba2fe1af06001770d90e'
g_base_definitions[g_str_5fb1ba2fe1af06001770d90e]={
  id=g_str_5fb1ba2fe1af06001770d90e,
  name='Knights',
  min=3,
  max=5,
  description='Gastaldi, gasindii, and other first class mounted',
  troop_type="Knights",
  troop_option_id="5fb1ba2fe1af06001770d90d",
}
g_str_5fb1ba2fe1af06001770d910='5fb1ba2fe1af06001770d910'
g_base_definitions[g_str_5fb1ba2fe1af06001770d910]={
  id=g_str_5fb1ba2fe1af06001770d910,
  name='Javelin Cavalry',
  min=3,
  max=5,
  description='Retainers and second class horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2fe1af06001770d90f",
}
g_str_5fb1ba2fe1af06001770d912='5fb1ba2fe1af06001770d912'
g_base_definitions[g_str_5fb1ba2fe1af06001770d912]={
  id=g_str_5fb1ba2fe1af06001770d912,
  name='Archers',
  min=2,
  max=4,
  description='Free Lombard bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba2fe1af06001770d911",
}
g_str_5fb1ba2fe1af06001770d913='5fb1ba2fe1af06001770d913'
g_base_definitions[g_str_5fb1ba2fe1af06001770d913]={
  id=g_str_5fb1ba2fe1af06001770d913,
  name='Skirmishers',
  min=2,
  max=4,
  description='Free Lombard bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2fe1af06001770d911",
}
g_str_5fb1ba2fe1af06001770d916='5fb1ba2fe1af06001770d916'
g_base_definitions[g_str_5fb1ba2fe1af06001770d916]={
  id=g_str_5fb1ba2fe1af06001770d916,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Italian town militia',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2fe1af06001770d914",
}
g_str_5fb1b9e4e1af060017709a36_camp='5fb1b9e4e1af060017709a36_camp'
g_base_definitions[g_str_5fb1b9e4e1af060017709a36_camp]={
  id=g_str_5fb1b9e4e1af060017709a36_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e4e1af060017709a36']={
  data={
    name='Italian Lombard  584 to 774 AD'
  },
  g_base_definitions[g_str_5fb1ba2fe1af06001770d90e_general],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d90e],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d910],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d912],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d913],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d916],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a36_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a36"] = army["5fb1b9e4e1af060017709a36"]
army['5fb1b9e4e1af060017709a36_584_649']={
  data={
    name='Italian Lombard 584 AD to 649 AD'
  },
  g_base_definitions[g_str_5fb1ba2fe1af06001770d90e_general],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d90e],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d910],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d912],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d913],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a36_camp],
}
army['5fb1b9e4e1af060017709a36_650_774']={
  data={
    name='Italian Lombard 650 AD to 774 AD'
  },
  g_base_definitions[g_str_5fb1ba2fe1af06001770d90e_general],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d90e],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d910],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d912],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d913],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d916],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a36_camp],
}
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Italian Lombard  584 to 774 AD"] = army["5fb1b9e4e1af060017709a36"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Italian Lombard  584 to 774 AD"] = army["5fb1b9e4e1af060017709a36"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a36"] = {}
army_dates["5fb1b9e4e1af060017709a36"]["584 AD to 774 AD"] ="5fb1b9e4e1af060017709a36"
army_dates["5fb1b9e4e1af060017709a36"]["584 AD to 649 AD"] ="5fb1b9e4e1af060017709a36_584_649"
army_dates["5fb1b9e4e1af060017709a36"]["650 AD to 774 AD"] ="5fb1b9e4e1af060017709a36_650_774"
