-- 5fb1b9e2e1af060017709923 Quadi  250 to 406 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2de1af06001770d59f='5fb1ba2de1af06001770d59f'
g_base_definitions[g_str_5fb1ba2de1af06001770d59f]={
  id=g_str_5fb1ba2de1af06001770d59f,
  name='Knights General',
  min=0,
  max=1,
  description='Noble horsemen',
  general=true,
}
g_str_5fb1ba2de1af06001770d59f_dismounted='5fb1ba2de1af06001770d59f_dismounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d59f_dismounted]={
  id=g_str_5fb1ba2de1af06001770d59f_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Knights General',
  points=4,
  general=true,
}
g_5fb1ba2de1af06001770d59f_dismounted=g_base_definitions[g_str_5fb1ba2de1af06001770d59f_dismounted]
g_str_5fb1ba2de1af06001770d59f_mounted='5fb1ba2de1af06001770d59f_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d59f_mounted]={
  id=g_str_5fb1ba2de1af06001770d59f_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2de1af06001770d59f_dismounted,
  general=true,
}
g_str_5fb1ba2de1af06001770d59f='5fb1ba2de1af06001770d59f'
g_base_definitions[g_str_5fb1ba2de1af06001770d59f]={
  id=g_str_5fb1ba2de1af06001770d59f,
  name='Knights',
  min=0,
  max=1,
  description='Noble horsemen',
}
g_str_5fb1ba2de1af06001770d59f_dismounted='5fb1ba2de1af06001770d59f_dismounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d59f_dismounted]={
  id=g_str_5fb1ba2de1af06001770d59f_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Knights',
  points=4,
}
g_5fb1ba2de1af06001770d59f_dismounted=g_base_definitions[g_str_5fb1ba2de1af06001770d59f_dismounted]
g_str_5fb1ba2de1af06001770d59f_mounted='5fb1ba2de1af06001770d59f_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d59f_mounted]={
  id=g_str_5fb1ba2de1af06001770d59f_mounted,
  name='Knights',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2de1af06001770d59f_dismounted,
}
g_str_5fb1ba2de1af06001770d5a0='5fb1ba2de1af06001770d5a0'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a0]={
  id=g_str_5fb1ba2de1af06001770d5a0,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Noble horsemen',
  general=true,
}
g_str_5fb1ba2de1af06001770d5a0_dismounted='5fb1ba2de1af06001770d5a0_dismounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_dismounted]={
  id=g_str_5fb1ba2de1af06001770d5a0_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  general=true,
}
g_5fb1ba2de1af06001770d5a0_dismounted=g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_dismounted]
g_str_5fb1ba2de1af06001770d5a0_mounted='5fb1ba2de1af06001770d5a0_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_mounted]={
  id=g_str_5fb1ba2de1af06001770d5a0_mounted,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2de1af06001770d5a0_dismounted,
  general=true,
}
g_str_5fb1ba2de1af06001770d5a0='5fb1ba2de1af06001770d5a0'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a0]={
  id=g_str_5fb1ba2de1af06001770d5a0,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen',
}
g_str_5fb1ba2de1af06001770d5a0_dismounted='5fb1ba2de1af06001770d5a0_dismounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_dismounted]={
  id=g_str_5fb1ba2de1af06001770d5a0_dismounted,
  name='Warrior',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounted from Javelin Cavalry',
  points=4,
}
g_5fb1ba2de1af06001770d5a0_dismounted=g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_dismounted]
g_str_5fb1ba2de1af06001770d5a0_mounted='5fb1ba2de1af06001770d5a0_mounted'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_mounted]={
  id=g_str_5fb1ba2de1af06001770d5a0_mounted,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen\nDeployment dismounting as Warrior',
  points=4,
  dismount_as=g_5fb1ba2de1af06001770d5a0_dismounted,
}
g_str_5fb1ba2de1af06001770d5a3='5fb1ba2de1af06001770d5a3'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a3]={
  id=g_str_5fb1ba2de1af06001770d5a3,
  name='Warriors General',
  min=12,
  max=1,
  description='Fierce fighters',
  general=true,
}
g_str_5fb1ba2de1af06001770d5a3='5fb1ba2de1af06001770d5a3'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a3]={
  id=g_str_5fb1ba2de1af06001770d5a3,
  name='Warriors',
  min=12,
  max=16,
  description='Fierce fighters',
}
g_str_5fb1ba2de1af06001770d5a5='5fb1ba2de1af06001770d5a5'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a5]={
  id=g_str_5fb1ba2de1af06001770d5a5,
  name='Light Foot',
  min=0,
  max=2,
  description='Javelinmen',
}
g_str_5fb1ba2de1af06001770d5a7='5fb1ba2de1af06001770d5a7'
g_base_definitions[g_str_5fb1ba2de1af06001770d5a7]={
  id=g_str_5fb1ba2de1af06001770d5a7,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
}
g_str_5fb1b9e2e1af060017709923_camp='5fb1b9e2e1af060017709923_camp'
g_base_definitions[g_str_5fb1b9e2e1af060017709923_camp]={
  name='Camp',
  id=g_str_5fb1b9e2e1af060017709923_camp,
  min=1,
  max=1,
}
army['5fb1b9e2e1af060017709923']={
  data={
    name='Quadi  250 to 406 AD'
  },
  g_base_definitions[g_str_5fb1b9e2e1af060017709923_camp],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a9],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5aa],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5ab],
  g_base_definitions[g_str_5fb1ba2de1af06001770d59f],
  g_base_definitions[g_str_5fb1ba2de1af06001770d59f_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d59f_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d59f],
  g_base_definitions[g_str_5fb1ba2de1af06001770d59f_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d59f_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a0],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a0],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_mounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a0_dismounted],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a3],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a3],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a5],
  g_base_definitions[g_str_5fb1ba2de1af06001770d5a7],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af060017709923"] = army["5fb1b9e2e1af060017709923"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Quadi  250 to 406 AD"] = army["5fb1b9e2e1af060017709923"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Quadi  250 to 406 AD"] = army["5fb1b9e2e1af060017709923"]
