g_str_5fb1ba39e1af06001770eb13_general='5fb1ba39e1af06001770eb13_general'
g_base_definitions[g_str_5fb1ba39e1af06001770eb13_general]={
  id=g_str_5fb1ba39e1af06001770eb13_general,
  name='Javelin Cavalry General',
  min=3,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba39e1af06001770eb12",
}
g_str_5fb1ba39e1af06001770eb13='5fb1ba39e1af06001770eb13'
g_base_definitions[g_str_5fb1ba39e1af06001770eb13]={
  id=g_str_5fb1ba39e1af06001770eb13,
  name='Javelin Cavalry',
  min=3,
  max=5,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba39e1af06001770eb12",
}
g_str_5fb1ba39e1af06001770eb15='5fb1ba39e1af06001770eb15'
g_base_definitions[g_str_5fb1ba39e1af06001770eb15]={
  id=g_str_5fb1ba39e1af06001770eb15,
  name='Warband',
  min=4,
  max=10,
  description='Tribal levy fighters',
  troop_type="Warband",
  troop_option_id="5fb1ba39e1af06001770eb14",
}
g_str_5fb1ba39e1af06001770eb17='5fb1ba39e1af06001770eb17'
g_base_definitions[g_str_5fb1ba39e1af06001770eb17]={
  id=g_str_5fb1ba39e1af06001770eb17,
  name='Bow Levy',
  min=1,
  max=5,
  description='Ethiopian or Muslim bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba39e1af06001770eb16",
}
g_str_5fb1ba39e1af06001770eb18='5fb1ba39e1af06001770eb18'
g_base_definitions[g_str_5fb1ba39e1af06001770eb18]={
  id=g_str_5fb1ba39e1af06001770eb18,
  name='Archers',
  min=1,
  max=5,
  description='Ethiopian or Muslim bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba39e1af06001770eb16",
}
g_str_5fb1ba39e1af06001770eb1a='5fb1ba39e1af06001770eb1a'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1a]={
  id=g_str_5fb1ba39e1af06001770eb1a,
  name='Raiders',
  min=0,
  max=1,
  description='Muslim dembus wielders',
  troop_type="Raiders",
  troop_option_id="5fb1ba39e1af06001770eb19",
}
g_str_5fb1ba39e1af06001770eb1c='5fb1ba39e1af06001770eb1c'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1c]={
  id=g_str_5fb1ba39e1af06001770eb1c,
  name='Rabble',
  min=1,
  max=2,
  description='Unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba39e1af06001770eb1b",
}
g_str_5fb1ba39e1af06001770eb1e='5fb1ba39e1af06001770eb1e'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1e]={
  id=g_str_5fb1ba39e1af06001770eb1e,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eb1d",
}
g_str_5fb1ba39e1af06001770eb1e_light_camelry='5fb1ba39e1af06001770eb1e_light_camelry'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1e_light_camelry]={
  id=g_str_5fb1ba39e1af06001770eb1e_light_camelry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eb1d",
}
g_str_5fb1ba39e1af06001770eb21='5fb1ba39e1af06001770eb21'
g_base_definitions[g_str_5fb1ba39e1af06001770eb21]={
  id=g_str_5fb1ba39e1af06001770eb21,
  name='Rabble',
  min=0,
  max=1,
  description='Muslim women throwing stones',
  troop_type="Rabble",
  troop_option_id="5fb1ba39e1af06001770eb20",
}
g_str_5fb1b9ece1af060017709ed1_camp='5fb1b9ece1af060017709ed1_camp'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp]={
  id=g_str_5fb1b9ece1af060017709ed1_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709ed1_camp_fortified='5fb1b9ece1af060017709ed1_camp_fortified'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_fortified]={
  id=g_str_5fb1b9ece1af060017709ed1_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709ed1_camp_pack_train='5fb1b9ece1af060017709ed1_camp_pack_train'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_pack_train]={
  id=g_str_5fb1b9ece1af060017709ed1_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba39e1af06001770eb13_general='5fb1ba39e1af06001770eb13_general'
g_base_definitions[g_str_5fb1ba39e1af06001770eb13_general]={
  id=g_str_5fb1ba39e1af06001770eb13_general,
  name='Javelin Cavalry General',
  min=3,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba39e1af06001770eb12",
}
g_str_5fb1ba39e1af06001770eb13='5fb1ba39e1af06001770eb13'
g_base_definitions[g_str_5fb1ba39e1af06001770eb13]={
  id=g_str_5fb1ba39e1af06001770eb13,
  name='Javelin Cavalry',
  min=3,
  max=5,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba39e1af06001770eb12",
}
g_str_5fb1ba39e1af06001770eb15='5fb1ba39e1af06001770eb15'
g_base_definitions[g_str_5fb1ba39e1af06001770eb15]={
  id=g_str_5fb1ba39e1af06001770eb15,
  name='Warband',
  min=4,
  max=10,
  description='Tribal levy fighters',
  troop_type="Warband",
  troop_option_id="5fb1ba39e1af06001770eb14",
}
g_str_5fb1ba39e1af06001770eb17='5fb1ba39e1af06001770eb17'
g_base_definitions[g_str_5fb1ba39e1af06001770eb17]={
  id=g_str_5fb1ba39e1af06001770eb17,
  name='Bow Levy',
  min=1,
  max=5,
  description='Ethiopian or Muslim bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba39e1af06001770eb16",
}
g_str_5fb1ba39e1af06001770eb18='5fb1ba39e1af06001770eb18'
g_base_definitions[g_str_5fb1ba39e1af06001770eb18]={
  id=g_str_5fb1ba39e1af06001770eb18,
  name='Archers',
  min=1,
  max=5,
  description='Ethiopian or Muslim bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba39e1af06001770eb16",
}
g_str_5fb1ba39e1af06001770eb1a='5fb1ba39e1af06001770eb1a'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1a]={
  id=g_str_5fb1ba39e1af06001770eb1a,
  name='Raiders',
  min=0,
  max=1,
  description='Muslim dembus wielders',
  troop_type="Raiders",
  troop_option_id="5fb1ba39e1af06001770eb19",
}
g_str_5fb1ba39e1af06001770eb1c='5fb1ba39e1af06001770eb1c'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1c]={
  id=g_str_5fb1ba39e1af06001770eb1c,
  name='Rabble',
  min=1,
  max=2,
  description='Unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba39e1af06001770eb1b",
}
g_str_5fb1ba39e1af06001770eb1e='5fb1ba39e1af06001770eb1e'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1e]={
  id=g_str_5fb1ba39e1af06001770eb1e,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eb1d",
}
g_str_5fb1ba39e1af06001770eb1e_light_camelry='5fb1ba39e1af06001770eb1e_light_camelry'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1e_light_camelry]={
  id=g_str_5fb1ba39e1af06001770eb1e_light_camelry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eb1d",
}
g_str_5fb1ba39e1af06001770eb21='5fb1ba39e1af06001770eb21'
g_base_definitions[g_str_5fb1ba39e1af06001770eb21]={
  id=g_str_5fb1ba39e1af06001770eb21,
  name='Rabble',
  min=0,
  max=1,
  description='Muslim women throwing stones',
  troop_type="Rabble",
  troop_option_id="5fb1ba39e1af06001770eb20",
}
g_str_5fb1b9ece1af060017709ed1_camp='5fb1b9ece1af060017709ed1_camp'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp]={
  id=g_str_5fb1b9ece1af060017709ed1_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709ed1_camp_fortified='5fb1b9ece1af060017709ed1_camp_fortified'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_fortified]={
  id=g_str_5fb1b9ece1af060017709ed1_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709ed1_camp_pack_train='5fb1b9ece1af060017709ed1_camp_pack_train'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_pack_train]={
  id=g_str_5fb1b9ece1af060017709ed1_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba39e1af06001770eb13_general='5fb1ba39e1af06001770eb13_general'
g_base_definitions[g_str_5fb1ba39e1af06001770eb13_general]={
  id=g_str_5fb1ba39e1af06001770eb13_general,
  name='Javelin Cavalry General',
  min=3,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba39e1af06001770eb12",
}
g_str_5fb1ba39e1af06001770eb13='5fb1ba39e1af06001770eb13'
g_base_definitions[g_str_5fb1ba39e1af06001770eb13]={
  id=g_str_5fb1ba39e1af06001770eb13,
  name='Javelin Cavalry',
  min=3,
  max=5,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba39e1af06001770eb12",
}
g_str_5fb1ba39e1af06001770eb15='5fb1ba39e1af06001770eb15'
g_base_definitions[g_str_5fb1ba39e1af06001770eb15]={
  id=g_str_5fb1ba39e1af06001770eb15,
  name='Warband',
  min=4,
  max=10,
  description='Tribal levy fighters',
  troop_type="Warband",
  troop_option_id="5fb1ba39e1af06001770eb14",
}
g_str_5fb1ba39e1af06001770eb17='5fb1ba39e1af06001770eb17'
g_base_definitions[g_str_5fb1ba39e1af06001770eb17]={
  id=g_str_5fb1ba39e1af06001770eb17,
  name='Bow Levy',
  min=1,
  max=5,
  description='Ethiopian or Muslim bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba39e1af06001770eb16",
}
g_str_5fb1ba39e1af06001770eb18='5fb1ba39e1af06001770eb18'
g_base_definitions[g_str_5fb1ba39e1af06001770eb18]={
  id=g_str_5fb1ba39e1af06001770eb18,
  name='Archers',
  min=1,
  max=5,
  description='Ethiopian or Muslim bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba39e1af06001770eb16",
}
g_str_5fb1ba39e1af06001770eb1a='5fb1ba39e1af06001770eb1a'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1a]={
  id=g_str_5fb1ba39e1af06001770eb1a,
  name='Raiders',
  min=0,
  max=1,
  description='Muslim dembus wielders',
  troop_type="Raiders",
  troop_option_id="5fb1ba39e1af06001770eb19",
}
g_str_5fb1ba39e1af06001770eb1c='5fb1ba39e1af06001770eb1c'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1c]={
  id=g_str_5fb1ba39e1af06001770eb1c,
  name='Rabble',
  min=1,
  max=2,
  description='Unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba39e1af06001770eb1b",
}
g_str_5fb1ba39e1af06001770eb1e='5fb1ba39e1af06001770eb1e'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1e]={
  id=g_str_5fb1ba39e1af06001770eb1e,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eb1d",
}
g_str_5fb1ba39e1af06001770eb1e_light_camelry='5fb1ba39e1af06001770eb1e_light_camelry'
g_base_definitions[g_str_5fb1ba39e1af06001770eb1e_light_camelry]={
  id=g_str_5fb1ba39e1af06001770eb1e_light_camelry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Light camels\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba39e1af06001770eb1d",
}
g_str_5fb1ba39e1af06001770eb21='5fb1ba39e1af06001770eb21'
g_base_definitions[g_str_5fb1ba39e1af06001770eb21]={
  id=g_str_5fb1ba39e1af06001770eb21,
  name='Rabble',
  min=0,
  max=1,
  description='Muslim women throwing stones',
  troop_type="Rabble",
  troop_option_id="5fb1ba39e1af06001770eb20",
}
g_str_5fb1b9ece1af060017709ed1_camp='5fb1b9ece1af060017709ed1_camp'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp]={
  id=g_str_5fb1b9ece1af060017709ed1_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709ed1_camp_fortified='5fb1b9ece1af060017709ed1_camp_fortified'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_fortified]={
  id=g_str_5fb1b9ece1af060017709ed1_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9ece1af060017709ed1_camp_pack_train='5fb1b9ece1af060017709ed1_camp_pack_train'
g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_pack_train]={
  id=g_str_5fb1b9ece1af060017709ed1_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
