-- 5fb1b9e1e1af06001770980d Marian Roman  105 to 25 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba2be1af06001770d1c9_general='5fb1ba2be1af06001770d1c9_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d1c9_general]={
  id=g_str_5fb1ba2be1af06001770d1c9_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Allied veteran horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d1c8",
}
g_str_5fb1ba2be1af06001770d1c9='5fb1ba2be1af06001770d1c9'
g_base_definitions[g_str_5fb1ba2be1af06001770d1c9]={
  id=g_str_5fb1ba2be1af06001770d1c9,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Allied veteran horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2be1af06001770d1c8",
}
g_str_5fb1ba2be1af06001770d1cb_general='5fb1ba2be1af06001770d1cb_general'
g_base_definitions[g_str_5fb1ba2be1af06001770d1cb_general]={
  id=g_str_5fb1ba2be1af06001770d1cb_general,
  name='Elite Foot General',
  min=4,
  max=1,
  description='Legionaries',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba2be1af06001770d1ca",
}
g_str_5fb1ba2be1af06001770d1cb='5fb1ba2be1af06001770d1cb'
g_base_definitions[g_str_5fb1ba2be1af06001770d1cb]={
  id=g_str_5fb1ba2be1af06001770d1cb,
  name='Elite Foot',
  min=4,
  max=8,
  description='Legionaries',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba2be1af06001770d1ca",
}
g_str_5fb1ba2be1af06001770d1ce='5fb1ba2be1af06001770d1ce'
g_base_definitions[g_str_5fb1ba2be1af06001770d1ce]={
  id=g_str_5fb1ba2be1af06001770d1ce,
  name='Bad Horse',
  min=0,
  max=2,
  description='Unreliable or raw Gallic or other horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba2be1af06001770d1cd",
}
g_str_5fb1ba2be1af06001770d1d0='5fb1ba2be1af06001770d1d0'
g_base_definitions[g_str_5fb1ba2be1af06001770d1d0]={
  id=g_str_5fb1ba2be1af06001770d1d0,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Raw legionaries',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2be1af06001770d1cf",
}
g_str_5fb1ba2be1af06001770d1d2='5fb1ba2be1af06001770d1d2'
g_base_definitions[g_str_5fb1ba2be1af06001770d1d2]={
  id=g_str_5fb1ba2be1af06001770d1d2,
  name='Skirmishers',
  min=0,
  max=3,
  description='Skirmishing slingers or bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2be1af06001770d1d1",
}
g_str_5fb1ba2be1af06001770d1d4='5fb1ba2be1af06001770d1d4'
g_base_definitions[g_str_5fb1ba2be1af06001770d1d4]={
  id=g_str_5fb1ba2be1af06001770d1d4,
  name='Light Foot',
  min=0,
  max=2,
  description='Velites or allied javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2be1af06001770d1d3",
}
g_str_5fb1ba2be1af06001770d1d6='5fb1ba2be1af06001770d1d6'
g_base_definitions[g_str_5fb1ba2be1af06001770d1d6]={
  id=g_str_5fb1ba2be1af06001770d1d6,
  name='Light Foot',
  min=0,
  max=1,
  description='Thureophoroi or peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2be1af06001770d1d5",
}
g_str_5fb1ba2be1af06001770d1d8='5fb1ba2be1af06001770d1d8'
g_base_definitions[g_str_5fb1ba2be1af06001770d1d8]={
  id=g_str_5fb1ba2be1af06001770d1d8,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt shooters',
  troop_type="Artillery",
  troop_option_id="5fb1ba2be1af06001770d1d7",
}
g_str_5fb1b9e1e1af06001770980d_camp='5fb1b9e1e1af06001770980d_camp'
g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp]={
  id=g_str_5fb1b9e1e1af06001770980d_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af06001770980d_camp_fortified='5fb1b9e1e1af06001770980d_camp_fortified'
g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp_fortified]={
  id=g_str_5fb1b9e1e1af06001770980d_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
g_str_5fb1b9e1e1af06001770980d_camp_pack_train='5fb1b9e1e1af06001770980d_camp_pack_train'
g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp_pack_train]={
  id=g_str_5fb1b9e1e1af06001770980d_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba0de1af06001770acb3='5fb1ba0de1af06001770acb3'
g_base_definitions[g_str_5fb1ba0de1af06001770acb3]={
  id=g_str_5fb1ba0de1af06001770acb3,
  name='Horse Bow',
  min=1,
  max=2,
  description='Thracian or client horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba0de1af06001770acb2",
}
g_str_5fb1ba0de1af06001770acb5='5fb1ba0de1af06001770acb5'
g_base_definitions[g_str_5fb1ba0de1af06001770acb5]={
  id=g_str_5fb1ba0de1af06001770acb5,
  name='Archers',
  min=0,
  max=1,
  description='Client foot bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba0de1af06001770acb4",
}
g_str_5fb1ba0de1af06001770acb6='5fb1ba0de1af06001770acb6'
g_base_definitions[g_str_5fb1ba0de1af06001770acb6]={
  id=g_str_5fb1ba0de1af06001770acb6,
  name='Bow Levy',
  min=0,
  max=1,
  description='Client foot bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba0de1af06001770acb4",
}
army['5fb1b9e1e1af06001770980d']={
  data={
    name='Marian Roman  105 to 25 BC',
    id='5fb1b9e1e1af06001770980d',
    army_id='5fb1b9e1e1af06001770980d'
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d1c9_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1c9],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1cb_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1cb],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1ce],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d0],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d2],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d4],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d6],
  g_base_definitions[g_str_5fb1ba2be1af06001770d1d8],
  g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp],
  g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af06001770980d_camp_pack_train],
  g_base_definitions[g_str_5fb1ba0de1af06001770acb3],
  g_base_definitions[g_str_5fb1ba0de1af06001770acb5],
  g_base_definitions[g_str_5fb1ba0de1af06001770acb6],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af06001770980d"] = army["5fb1b9e1e1af06001770980d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Marian Roman  105 to 25 BC"] = army["5fb1b9e1e1af06001770980d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Marian Roman  105 to 25 BC"] = army["5fb1b9e1e1af06001770980d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af06001770980d"] = {}
army_dates["5fb1b9e1e1af06001770980d"]["105 BC to 25 BC"] ="5fb1b9e1e1af06001770980d"
