troop_options['5fb1ba21e1af06001770c14d'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-1365,
    endDate=-745,
  }
}
troop_options['5fb1ba21e1af06001770c14f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-889,
    endDate=-860,
  }
}
troop_options['5fb1ba21e1af06001770c152'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-859,
    endDate=-745,
  }
}
troop_options['5fb1ba21e1af06001770c155'] = {
  min=2,
  max=3,
  dateRange={
    startDate=-1365,
    endDate=-745,
  }
}
troop_options['5fb1ba21e1af06001770c158'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-1365,
    endDate=-745,
  }
}
troop_options['5fb1ba21e1af06001770c15b'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-1365,
    endDate=-745,
  }
}
troop_options['5fb1ba21e1af06001770c15d'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-859,
    endDate=-745,
  }
}
-- allies
