-- 5fb1b9e5e1af060017709a95 Pre-Viking Scandinavian  450 to 789 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba30e1af06001770da64='5fb1ba30e1af06001770da64'
g_base_definitions[g_str_5fb1ba30e1af06001770da64]={
  id=g_str_5fb1ba30e1af06001770da64,
  name='Elite Foot General',
  min=1,
  max=1,
  description='Huscarles',
}
g_str_5fb1ba30e1af06001770da64='5fb1ba30e1af06001770da64'
g_base_definitions[g_str_5fb1ba30e1af06001770da64]={
  id=g_str_5fb1ba30e1af06001770da64,
  name='Elite Foot',
  min=1,
  max=2,
  description='Huscarles',
}
g_str_5fb1ba30e1af06001770da66='5fb1ba30e1af06001770da66'
g_base_definitions[g_str_5fb1ba30e1af06001770da66]={
  id=g_str_5fb1ba30e1af06001770da66,
  name='Heavy Foot',
  min=5,
  max=14,
  description='Bondi spearmen',
}
g_str_5fb1ba30e1af06001770da68='5fb1ba30e1af06001770da68'
g_base_definitions[g_str_5fb1ba30e1af06001770da68]={
  id=g_str_5fb1ba30e1af06001770da68,
  name='Skirmishers',
  min=0,
  max=2,
  description='Bowmen',
}
g_str_5fb1ba30e1af06001770da69='5fb1ba30e1af06001770da69'
g_base_definitions[g_str_5fb1ba30e1af06001770da69]={
  id=g_str_5fb1ba30e1af06001770da69,
  name='Bow Levy',
  min=0,
  max=2,
  description='Bowmen',
}
g_str_5fb1ba30e1af06001770da6b='5fb1ba30e1af06001770da6b'
g_base_definitions[g_str_5fb1ba30e1af06001770da6b]={
  id=g_str_5fb1ba30e1af06001770da6b,
  name='Horde',
  min=0,
  max=2,
  description='Thralls, levy, and dregs',
}
g_str_5fb1b9e5e1af060017709a95_camp='5fb1b9e5e1af060017709a95_camp'
g_base_definitions[g_str_5fb1b9e5e1af060017709a95_camp]={
  name='Camp',
  id=g_str_5fb1b9e5e1af060017709a95_camp,
  min=1,
  max=1,
}
army['5fb1b9e5e1af060017709a95']={
  data={
    name='Pre-Viking Scandinavian  450 to 789 AD'
  },
  g_base_definitions[g_str_5fb1b9e5e1af060017709a95_camp],
  g_base_definitions[g_str_5fb1ba30e1af06001770da6d],
  g_base_definitions[g_str_5fb1ba30e1af06001770da64],
  g_base_definitions[g_str_5fb1ba30e1af06001770da64],
  g_base_definitions[g_str_5fb1ba30e1af06001770da66],
  g_base_definitions[g_str_5fb1ba30e1af06001770da68],
  g_base_definitions[g_str_5fb1ba30e1af06001770da69],
  g_base_definitions[g_str_5fb1ba30e1af06001770da6b],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709a95"] = army["5fb1b9e5e1af060017709a95"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Pre-Viking Scandinavian  450 to 789 AD"] = army["5fb1b9e5e1af060017709a95"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Pre-Viking Scandinavian  450 to 789 AD"] = army["5fb1b9e5e1af060017709a95"]
