troop_options['5fb1ba3ce1af06001770f162'] = {
  min=1,
  max=2,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f164'] = {
  min=0,
  max=1,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f168'] = {
  min=1,
  max=2,
  dateRange={
    startDate=873,
    endDate=999,
  }
}
troop_options['5fb1ba3ce1af06001770f16c'] = {
  min=0,
  max=2,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f16e'] = {
  min=2,
  max=4,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f172'] = {
  min=1,
  max=4,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f176'] = {
  min=0,
  max=2,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f178'] = {
  min=1,
  max=3,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f17b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f17e'] = {
  min=0,
  max=1,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f180'] = {
  min=0,
  max=1,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f182'] = {
  min=0,
  max=1,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f184'] = {
  min=0,
  max=1,
  dateRange={
    startDate=861,
    endDate=1073,
  }
}
troop_options['5fb1ba3ce1af06001770f186'] = {
  min=0,
  max=1,
  dateRange={
    startDate=873,
    endDate=1003,
  }
}
-- allies
