-- 5fb1b9d8e1af0600177092b9 Gilgamesh Era Sumerian  2799 to 2334 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba1ee1af06001770bda1_general='5fb1ba1ee1af06001770bda1_general'
g_base_definitions[g_str_5fb1ba1ee1af06001770bda1_general]={
  id=g_str_5fb1ba1ee1af06001770bda1_general,
  name='Chariots General',
  min=1,
  max=1,
  description='4-wheeled battle cars',
  general=true,
  troop_type="Chariots",
}
g_str_5fb1ba1ee1af06001770bda1='5fb1ba1ee1af06001770bda1'
g_base_definitions[g_str_5fb1ba1ee1af06001770bda1]={
  id=g_str_5fb1ba1ee1af06001770bda1,
  name='Chariots',
  min=1,
  max=2,
  description='4-wheeled battle cars',
  troop_type="Chariots",
}
g_str_5fb1ba1ee1af06001770bda3='5fb1ba1ee1af06001770bda3'
g_base_definitions[g_str_5fb1ba1ee1af06001770bda3]={
  id=g_str_5fb1ba1ee1af06001770bda3,
  name='Raiders',
  min=0,
  max=2,
  description='Household axemen',
  troop_type="Raiders",
}
g_str_5fb1ba1ee1af06001770bda6='5fb1ba1ee1af06001770bda6'
g_base_definitions[g_str_5fb1ba1ee1af06001770bda6]={
  id=g_str_5fb1ba1ee1af06001770bda6,
  name='Light Foot',
  min=0,
  max=1,
  description='Martu mercenaries',
  troop_type="Light Foot",
}
g_str_5fb1ba1ee1af06001770bda9='5fb1ba1ee1af06001770bda9'
g_base_definitions[g_str_5fb1ba1ee1af06001770bda9]={
  id=g_str_5fb1ba1ee1af06001770bda9,
  name='Light Foot',
  min=0,
  max=2,
  description='Martu mercenaries',
  troop_type="Light Foot",
}
g_str_5fb1ba1ee1af06001770bdab='5fb1ba1ee1af06001770bdab'
g_base_definitions[g_str_5fb1ba1ee1af06001770bdab]={
  id=g_str_5fb1ba1ee1af06001770bdab,
  name='Bow Levy',
  min=1,
  max=2,
  description='Household and militia bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba1ee1af06001770bdad='5fb1ba1ee1af06001770bdad'
g_base_definitions[g_str_5fb1ba1ee1af06001770bdad]={
  id=g_str_5fb1ba1ee1af06001770bdad,
  name='Pikes',
  min=8,
  max=13,
  description='Household and militia spearmen',
  troop_type="Pikes",
}
g_str_5fb1ba1ee1af06001770bdaf='5fb1ba1ee1af06001770bdaf'
g_base_definitions[g_str_5fb1ba1ee1af06001770bdaf]={
  id=g_str_5fb1ba1ee1af06001770bdaf,
  name='Rabble',
  min=1,
  max=2,
  description='Nomadic and levy javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba1ee1af06001770bdb1='5fb1ba1ee1af06001770bdb1'
g_base_definitions[g_str_5fb1ba1ee1af06001770bdb1]={
  id=g_str_5fb1ba1ee1af06001770bdb1,
  name='Skirmishers',
  min=1,
  max=6,
  description='Nomadic and levy slingers and skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1b9d8e1af0600177092b9_camp='5fb1b9d8e1af0600177092b9_camp'
g_base_definitions[g_str_5fb1b9d8e1af0600177092b9_camp]={
  id=g_str_5fb1b9d8e1af0600177092b9_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d8e1af0600177092b9_camp_pack_train='5fb1b9d8e1af0600177092b9_camp_pack_train'
g_base_definitions[g_str_5fb1b9d8e1af0600177092b9_camp_pack_train]={
  id=g_str_5fb1b9d8e1af0600177092b9_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9d8e1af0600177092b9']={
  data={
    name='Gilgamesh Era Sumerian  2799 to 2334 BC'
  },
  g_base_definitions[g_str_5fb1ba1ee1af06001770bda1_general],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bda1],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bda3],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bda6],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bda9],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bdab],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bdad],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bdaf],
  g_base_definitions[g_str_5fb1ba1ee1af06001770bdb1],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092b9_camp],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092b9_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092b9"] = army["5fb1b9d8e1af0600177092b9"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Gilgamesh Era Sumerian  2799 to 2334 BC"] = army["5fb1b9d8e1af0600177092b9"]
