-- 5fb1b9dee1af0600177096b3 Early Galatian  280 to 228 BC

army['5fb1b9dee1af0600177096b3']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Galatian  280 to 228 BC',
    id='5fb1b9dee1af0600177096b3',
    dateRange={
      startDate=-280,
      endDate=-228,
    }
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce6],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccea],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccec],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096b3"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096b3"] = {}
army_dates["5fb1b9dee1af0600177096b3"]["280 BC to 228 BC"] = {
  startDate=-280,
  endDate=-228
}
army_dates["5fb1b9dee1af0600177096b3"]["280 BC"] = {
  startDate=-280,
  endDate=-280
}
army_dates["5fb1b9dee1af0600177096b3"]["279 BC"] = {
  startDate=-279,
  endDate=-279
}
army_dates["5fb1b9dee1af0600177096b3"]["278 BC to 245 BC"] = {
  startDate=-278,
  endDate=-245
}
army_dates["5fb1b9dee1af0600177096b3"]["244 BC to 242 BC"] = {
  startDate=-244,
  endDate=-242
}
army_dates["5fb1b9dee1af0600177096b3"]["241 BC to 228 BC"] = {
  startDate=-241,
  endDate=-228
}
-- 5fb1b9dee1af0600177096b3 Early Galatian  280 to 228 BC

army['5fb1b9dee1af0600177096b3']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Galatian  280 to 228 BC',
    id='5fb1b9dee1af0600177096b3',
    dateRange={
      startDate=-280,
      endDate=-228,
    }
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce6],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccea],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccec],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096b3"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096b3"] = {}
army_dates["5fb1b9dee1af0600177096b3"]["280 BC to 228 BC"] = {
  startDate=-280,
  endDate=-228
}
army_dates["5fb1b9dee1af0600177096b3"]["280 BC"] = {
  startDate=-280,
  endDate=-280
}
army_dates["5fb1b9dee1af0600177096b3"]["279 BC"] = {
  startDate=-279,
  endDate=-279
}
army_dates["5fb1b9dee1af0600177096b3"]["278 BC to 245 BC"] = {
  startDate=-278,
  endDate=-245
}
army_dates["5fb1b9dee1af0600177096b3"]["244 BC to 242 BC"] = {
  startDate=-244,
  endDate=-242
}
army_dates["5fb1b9dee1af0600177096b3"]["241 BC to 228 BC"] = {
  startDate=-241,
  endDate=-228
}
-- 5fb1b9dee1af0600177096b3 Early Galatian  280 to 228 BC

army['5fb1b9dee1af0600177096b3']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Galatian  280 to 228 BC',
    id='5fb1b9dee1af0600177096b3',
    dateRange={
      startDate=-280,
      endDate=-228,
    }
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce4],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce6],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cce8],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccea],
  g_base_definitions[g_str_5fb1ba29e1af06001770ccec],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096b3_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096b3"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Galatian  280 to 228 BC"] = army["5fb1b9dee1af0600177096b3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096b3"] = {}
army_dates["5fb1b9dee1af0600177096b3"]["280 BC to 228 BC"] = {
  startDate=-280,
  endDate=-228
}
army_dates["5fb1b9dee1af0600177096b3"]["280 BC"] = {
  startDate=-280,
  endDate=-280
}
army_dates["5fb1b9dee1af0600177096b3"]["279 BC"] = {
  startDate=-279,
  endDate=-279
}
army_dates["5fb1b9dee1af0600177096b3"]["278 BC to 245 BC"] = {
  startDate=-278,
  endDate=-245
}
army_dates["5fb1b9dee1af0600177096b3"]["244 BC to 242 BC"] = {
  startDate=-244,
  endDate=-242
}
army_dates["5fb1b9dee1af0600177096b3"]["241 BC to 228 BC"] = {
  startDate=-241,
  endDate=-228
}
