-- 5fb1b9ede1af060017709f83 Medieval Alan  920 to 1239 AD

army['5fb1b9ede1af060017709f83']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Steppe',
    },
    name='Medieval Alan  920 to 1239 AD',
    id='5fb1b9ede1af060017709f83',
    dateRange={
      startDate=920,
      endDate=1239,
    },
  },
  g_base_definitions[g_str_615351b003385c0016b87eb9_general],
  g_base_definitions[g_str_615351b003385c0016b87eb9],
  g_base_definitions[g_str_615351b003385c0016b87ebb_general],
  g_base_definitions[g_str_615351b003385c0016b87ebb],
  g_base_definitions[g_str_615351b003385c0016b87ebd],
  g_base_definitions[g_str_615351b003385c0016b87ebf],
  g_base_definitions[g_str_5fb1b9ede1af060017709f83_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f83_camp_fortified],
  g_base_definitions[g_str_5fb1b9ede1af060017709f83_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f83"] = army["5fb1b9ede1af060017709f83"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Medieval Alan  920 to 1239 AD"] = army["5fb1b9ede1af060017709f83"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Medieval Alan  920 to 1239 AD"] = army["5fb1b9ede1af060017709f83"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Medieval Alan  920 to 1239 AD"] = army["5fb1b9ede1af060017709f83"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Alan  920 to 1239 AD"] = army["5fb1b9ede1af060017709f83"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f83"] = {}
army_dates["5fb1b9ede1af060017709f83"]["920 AD to 1239 AD"] = {
  startDate=920,
  endDate=1239
}
army_dates["5fb1b9ede1af060017709f83"]["920 AD to 929 AD"] = {
  startDate=920,
  endDate=929
}
army_dates["5fb1b9ede1af060017709f83"]["930 AD to 965 AD"] = {
  startDate=930,
  endDate=965
}
army_dates["5fb1b9ede1af060017709f83"]["966 AD to 969 AD"] = {
  startDate=966,
  endDate=969
}
army_dates["5fb1b9ede1af060017709f83"]["970 AD to 1053 AD"] = {
  startDate=970,
  endDate=1053
}
army_dates["5fb1b9ede1af060017709f83"]["1054 AD to 1106 AD"] = {
  startDate=1054,
  endDate=1106
}
army_dates["5fb1b9ede1af060017709f83"]["1107 AD to 1221 AD"] = {
  startDate=1107,
  endDate=1221
}
army_dates["5fb1b9ede1af060017709f83"]["1222 AD"] = {
  startDate=1222,
  endDate=1222
}
army_dates["5fb1b9ede1af060017709f83"]["1223 AD to 1239 AD"] = {
  startDate=1223,
  endDate=1239
}
