troop_options['5fb1ba3ee1af06001770f502'] = {
  min=5,
  max=12,
  dateRange={
    startDate=-2000,
    endDate=-315,
  }
}
troop_options['5fb1ba3ee1af06001770f504'] = {
  min=2,
  max=8,
  dateRange={
    startDate=-2000,
    endDate=-315,
  }
}
troop_options['5fb1ba3ee1af06001770f506'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-2000,
    endDate=-315,
  }
}
troop_options['5fb1ba3ee1af06001770f508'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-2000,
    endDate=-315,
  }
}
-- allies
