-- 5fb1b9dae1af0600177093e4 Later Syro-Hittite  900 to 710 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba21e1af06001770c1b4_general='5fb1ba21e1af06001770c1b4_general'
g_base_definitions[g_str_5fb1ba21e1af06001770c1b4_general]={
  id=g_str_5fb1ba21e1af06001770c1b4_general,
  name='Chariots General',
  min=2,
  max=1,
  description='2-horse chariots with two crewmen, or 3- or 4-horse chariots with three crewmen',
  general=true,
}
g_str_5fb1ba21e1af06001770c1b4='5fb1ba21e1af06001770c1b4'
g_base_definitions[g_str_5fb1ba21e1af06001770c1b4]={
  id=g_str_5fb1ba21e1af06001770c1b4,
  name='Chariots',
  min=2,
  max=6,
  description='2-horse chariots with two crewmen, or 3- or 4-horse chariots with three crewmen',
}
g_str_5fb1ba21e1af06001770c1b6='5fb1ba21e1af06001770c1b6'
g_base_definitions[g_str_5fb1ba21e1af06001770c1b6]={
  id=g_str_5fb1ba21e1af06001770c1b6,
  name='Bad Horse',
  min=0,
  max=1,
  description='Mounted fighters',
}
g_str_5fb1ba21e1af06001770c1b8='5fb1ba21e1af06001770c1b8'
g_base_definitions[g_str_5fb1ba21e1af06001770c1b8]={
  id=g_str_5fb1ba21e1af06001770c1b8,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Spearmen',
}
g_str_5fb1ba21e1af06001770c1ba='5fb1ba21e1af06001770c1ba'
g_base_definitions[g_str_5fb1ba21e1af06001770c1ba]={
  id=g_str_5fb1ba21e1af06001770c1ba,
  name='Light Foot',
  min=4,
  max=6,
  description='Militia spearmen',
}
g_str_5fb1ba21e1af06001770c1bc='5fb1ba21e1af06001770c1bc'
g_base_definitions[g_str_5fb1ba21e1af06001770c1bc]={
  id=g_str_5fb1ba21e1af06001770c1bc,
  name='Bow Levy',
  min=1,
  max=4,
  description='Militia bowmen',
}
g_str_5fb1ba21e1af06001770c1be='5fb1ba21e1af06001770c1be'
g_base_definitions[g_str_5fb1ba21e1af06001770c1be]={
  id=g_str_5fb1ba21e1af06001770c1be,
  name='Skirmishers',
  min=1,
  max=4,
  description='Militia slingers',
}
g_str_5fb1ba21e1af06001770c1c0='5fb1ba21e1af06001770c1c0'
g_base_definitions[g_str_5fb1ba21e1af06001770c1c0]={
  id=g_str_5fb1ba21e1af06001770c1c0,
  name='Bad Horse',
  min=0,
  max=1,
  description='Aramaean or Arab camelry',
}
g_str_5fb1b9dae1af0600177093e4_camp='5fb1b9dae1af0600177093e4_camp'
g_base_definitions[g_str_5fb1b9dae1af0600177093e4_camp]={
  name='Camp',
  id=g_str_5fb1b9dae1af0600177093e4_camp,
  min=1,
  max=1,
}
army['5fb1b9dae1af0600177093e4']={
  data={
    name='Later Syro-Hittite  900 to 710 BC'
  },
  g_base_definitions[g_str_5fb1b9dae1af0600177093e4_camp],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1c3],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1b4_general],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1b4],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1b6],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1b8],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1ba],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1bc],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1be],
  g_base_definitions[g_str_5fb1ba21e1af06001770c1c0],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093e4"] = army["5fb1b9dae1af0600177093e4"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Later Syro-Hittite  900 to 710 BC"] = army["5fb1b9dae1af0600177093e4"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Later Syro-Hittite  900 to 710 BC"] = army["5fb1b9dae1af0600177093e4"]
