-- 5fb1b9e7e1af060017709c20 League of Cambrai Spanish  1504 to 1515 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba33e1af06001770dfc2='5fb1ba33e1af06001770dfc2'
g_base_definitions[g_str_5fb1ba33e1af06001770dfc2]={
  id=g_str_5fb1ba33e1af06001770dfc2,
  name='Knights General',
  min=2,
  max=1,
  description='Men-at-arms',
}
g_str_5fb1ba33e1af06001770dfc2='5fb1ba33e1af06001770dfc2'
g_base_definitions[g_str_5fb1ba33e1af06001770dfc2]={
  id=g_str_5fb1ba33e1af06001770dfc2,
  name='Knights',
  min=2,
  max=4,
  description='Men-at-arms',
}
g_str_5fb1ba33e1af06001770dfc4='5fb1ba33e1af06001770dfc4'
g_base_definitions[g_str_5fb1ba33e1af06001770dfc4]={
  id=g_str_5fb1ba33e1af06001770dfc4,
  name='Javelin Cavalry',
  min=2,
  max=4,
  description='Jinetes',
}
g_str_5fb1ba33e1af06001770dfc6='5fb1ba33e1af06001770dfc6'
g_base_definitions[g_str_5fb1ba33e1af06001770dfc6]={
  id=g_str_5fb1ba33e1af06001770dfc6,
  name='Pikes',
  min=4,
  max=8,
  description='Pikemen',
}
g_str_5fb1ba33e1af06001770dfc8='5fb1ba33e1af06001770dfc8'
g_base_definitions[g_str_5fb1ba33e1af06001770dfc8]={
  id=g_str_5fb1ba33e1af06001770dfc8,
  name='Raiders',
  min=1,
  max=3,
  description='Sword-and-buckler men',
}
g_str_5fb1ba33e1af06001770dfca='5fb1ba33e1af06001770dfca'
g_base_definitions[g_str_5fb1ba33e1af06001770dfca]={
  id=g_str_5fb1ba33e1af06001770dfca,
  name='Skirmishers',
  min=1,
  max=3,
  description='Crossbowmen and handgunners',
}
g_str_5fb1ba33e1af06001770dfcc='5fb1ba33e1af06001770dfcc'
g_base_definitions[g_str_5fb1ba33e1af06001770dfcc]={
  id=g_str_5fb1ba33e1af06001770dfcc,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
}
g_str_5fb1b9e7e1af060017709c20_camp='5fb1b9e7e1af060017709c20_camp'
g_base_definitions[g_str_5fb1b9e7e1af060017709c20_camp]={
  name='Camp',
  id=g_str_5fb1b9e7e1af060017709c20_camp,
  min=1,
  max=1,
}
army['5fb1b9e7e1af060017709c20']={
  data={
    name='League of Cambrai Spanish  1504 to 1515 AD'
  },
  g_base_definitions[g_str_5fb1b9e7e1af060017709c20_camp],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfce],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfc2],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfc2],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfc4],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfc6],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfc8],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfca],
  g_base_definitions[g_str_5fb1ba33e1af06001770dfcc],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c20"] = army["5fb1b9e7e1af060017709c20"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["League of Cambrai Spanish  1504 to 1515 AD"] = army["5fb1b9e7e1af060017709c20"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["League of Cambrai Spanish  1504 to 1515 AD"] = army["5fb1b9e7e1af060017709c20"]
