-- 5fb1b9e1e1af060017709863 Early German Cherusci or Batavian  115 BC to 250 AD

army['5fb1b9e1e1af060017709863']={
  data={
    invasionRatings={
      {
        value=2,
        note='',
      },
    },
    name='Early German Cherusci or Batavian  115 BC to 250 AD',
    id='5fb1b9e1e1af060017709863',
    dateRange={
      startDate=-115,
      endDate=250,
    }
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ff_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ff_general_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ff_general_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ff],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ff_mounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d2ff_dismounted],
  g_base_definitions[g_str_5fb1ba2be1af06001770d302_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d302],
  g_base_definitions[g_str_5fb1ba2be1af06001770d304],
  g_base_definitions[g_str_5fb1ba2be1af06001770d306],
  g_base_definitions[g_str_5fb1ba2be1af06001770d308],
  g_base_definitions[g_str_5fb1b9e1e1af060017709863_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709863_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af060017709863_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709863"] = army["5fb1b9e1e1af060017709863"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early German Cherusci or Batavian  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709863"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Early German Cherusci or Batavian  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709863"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early German Cherusci or Batavian  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709863"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709863"] = {}
army_dates["5fb1b9e1e1af060017709863"]["115 BC to 250 AD"] = {
  startDate=-115,
  endDate=250
}
