-- 5fb1b9dce1af0600177095b2 Celtiberians  240 to 20 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba27e1af06001770c8be='5fb1ba27e1af06001770c8be'
g_base_definitions[g_str_5fb1ba27e1af06001770c8be]={
  id=g_str_5fb1ba27e1af06001770c8be,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='Horsemen',
}
g_str_5fb1ba27e1af06001770c8c1='5fb1ba27e1af06001770c8c1'
g_base_definitions[g_str_5fb1ba27e1af06001770c8c1]={
  id=g_str_5fb1ba27e1af06001770c8c1,
  name='Raiders',
  min=4,
  max=8,
  description='Scutarii',
}
g_str_5fb1ba27e1af06001770c8c3='5fb1ba27e1af06001770c8c3'
g_base_definitions[g_str_5fb1ba27e1af06001770c8c3]={
  id=g_str_5fb1ba27e1af06001770c8c3,
  name='Light Foot',
  min=2,
  max=4,
  description='Caetrati',
}
g_str_5fb1ba27e1af06001770c8c5='5fb1ba27e1af06001770c8c5'
g_base_definitions[g_str_5fb1ba27e1af06001770c8c5]={
  id=g_str_5fb1ba27e1af06001770c8c5,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing slingers',
}
g_str_5fb1ba27e1af06001770c8c7='5fb1ba27e1af06001770c8c7'
g_base_definitions[g_str_5fb1ba27e1af06001770c8c7]={
  name='Javelin Cavalry General',
  id=g_str_5fb1ba27e1af06001770c8c7,
  min=1,
  max=1,
}
g_str_5fb1b9dce1af0600177095b2_camp='5fb1b9dce1af0600177095b2_camp'
g_base_definitions[g_str_5fb1b9dce1af0600177095b2_camp]={
  name='Camp',
  id=g_str_5fb1b9dce1af0600177095b2_camp,
  min=1,
  max=1,
}
army['5fb1b9dce1af0600177095b2']={
  data={
    name='Celtiberians  240 to 20 BC'
  },
  g_base_definitions[g_str_5fb1b9dce1af0600177095b2_camp],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8c7],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8be],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8c1],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8c3],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8c5],
}
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Celtiberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095b2"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Celtiberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095b2"]
