troop_options['5fb1ba44e1af06001770fec2'] = {
  min=6,
  max=9,
  dateRange={
    startDate=1200,
    endDate=1580,
  }
}
troop_options['5fb1ba44e1af06001770fec4'] = {
  min=3,
  max=6,
  dateRange={
    startDate=1200,
    endDate=1580,
  }
}
troop_options['5fb1ba44e1af06001770fec6'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1200,
    endDate=1580,
  }
}
-- allies
-- 5fb1b9f6e1af06001770a4a3 Tupi  1200 to 1580 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba44e1af06001770fec3='5fb1ba44e1af06001770fec3'
g_base_definitions[g_str_5fb1ba44e1af06001770fec3]={
  id=g_str_5fb1ba44e1af06001770fec3,
  name='Archers',
  min=6,
  max=9,
  description='Bowmen armed with powerful bows and two-handed clubs',
  troop_type="Archers",
  troop_option_id="5fb1ba44e1af06001770fec2",
}
g_str_5fb1ba44e1af06001770fec5_general='5fb1ba44e1af06001770fec5_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fec5_general]={
  id=g_str_5fb1ba44e1af06001770fec5_general,
  name='Raiders General',
  min=3,
  max=1,
  description='Fighters armed with two-handed clubs, sometimes bark or hide shields',
  general=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba44e1af06001770fec4",
}
g_str_5fb1ba44e1af06001770fec5='5fb1ba44e1af06001770fec5'
g_base_definitions[g_str_5fb1ba44e1af06001770fec5]={
  id=g_str_5fb1ba44e1af06001770fec5,
  name='Raiders',
  min=3,
  max=6,
  description='Fighters armed with two-handed clubs, sometimes bark or hide shields',
  troop_type="Raiders",
  troop_option_id="5fb1ba44e1af06001770fec4",
}
g_str_5fb1ba44e1af06001770fec7='5fb1ba44e1af06001770fec7'
g_base_definitions[g_str_5fb1ba44e1af06001770fec7]={
  id=g_str_5fb1ba44e1af06001770fec7,
  name='Skirmishers',
  min=0,
  max=1,
  description='Scouts',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fec6",
}
g_str_5fb1b9f6e1af06001770a4a3_camp='5fb1b9f6e1af06001770a4a3_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a4a3_camp]={
  id=g_str_5fb1b9f6e1af06001770a4a3_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9f6e1af06001770a4a3']={
  data={
    name='Tupi  1200 to 1580 AD',
    id='5fb1b9f6e1af06001770a4a3',
    army_id='5fb1b9f6e1af06001770a4a3'
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fec3],
  g_base_definitions[g_str_5fb1ba44e1af06001770fec5_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fec5],
  g_base_definitions[g_str_5fb1ba44e1af06001770fec7],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a4a3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a4a3"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Tupi  1200 to 1580 AD"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == armies["Caribbean"] then
  armies["Caribbean"] ={}
end
armies["Caribbean"]["Tupi  1200 to 1580 AD"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tupi  1200 to 1580 AD"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a4a3"] = {}
army_dates["5fb1b9f6e1af06001770a4a3"]["1200 AD to 1580 AD"] ="5fb1b9f6e1af06001770a4a3"
