-- 5fb1b9dee1af0600177096ce Ariariathid Kappadokian  330 BC to 17 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba29e1af06001770cd46_general='5fb1ba29e1af06001770cd46_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd46_general]={
  id=g_str_5fb1ba29e1af06001770cd46_general,
  name='Elite Cavalary General',
  min=0,
  max=1,
  description='Horsemen with armored horses',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba29e1af06001770cd45",
}
g_str_5fb1ba29e1af06001770cd46='5fb1ba29e1af06001770cd46'
g_base_definitions[g_str_5fb1ba29e1af06001770cd46]={
  id=g_str_5fb1ba29e1af06001770cd46,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Horsemen with armored horses',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba29e1af06001770cd45",
}
g_str_5fb1ba29e1af06001770cd48_general='5fb1ba29e1af06001770cd48_general'
g_base_definitions[g_str_5fb1ba29e1af06001770cd48_general]={
  id=g_str_5fb1ba29e1af06001770cd48_general,
  name='Javelin Cavalry General',
  min=3,
  max=1,
  description='Horsemen and light Horsemen, all with javelins',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd47",
}
g_str_5fb1ba29e1af06001770cd48='5fb1ba29e1af06001770cd48'
g_base_definitions[g_str_5fb1ba29e1af06001770cd48]={
  id=g_str_5fb1ba29e1af06001770cd48,
  name='Javelin Cavalry',
  min=3,
  max=6,
  description='Horsemen and light Horsemen, all with javelins',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba29e1af06001770cd47",
}
g_str_5fb1ba29e1af06001770cd4a='5fb1ba29e1af06001770cd4a'
g_base_definitions[g_str_5fb1ba29e1af06001770cd4a]={
  id=g_str_5fb1ba29e1af06001770cd4a,
  name='Light Foot',
  min=3,
  max=11,
  description='Infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cd49",
}
g_str_5fb1ba29e1af06001770cd4c='5fb1ba29e1af06001770cd4c'
g_base_definitions[g_str_5fb1ba29e1af06001770cd4c]={
  id=g_str_5fb1ba29e1af06001770cd4c,
  name='Bow Levy',
  min=1,
  max=4,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba29e1af06001770cd4b",
}
g_str_5fb1ba29e1af06001770cd4f='5fb1ba29e1af06001770cd4f'
g_base_definitions[g_str_5fb1ba29e1af06001770cd4f]={
  id=g_str_5fb1ba29e1af06001770cd4f,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Mercenary hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba29e1af06001770cd4d",
}
g_str_5fb1ba29e1af06001770cd52='5fb1ba29e1af06001770cd52'
g_base_definitions[g_str_5fb1ba29e1af06001770cd52]={
  id=g_str_5fb1ba29e1af06001770cd52,
  name='Light Foot',
  min=0,
  max=1,
  description='Thracian mercenary infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba29e1af06001770cd50",
}
g_str_5fb1ba29e1af06001770cd55='5fb1ba29e1af06001770cd55'
g_base_definitions[g_str_5fb1ba29e1af06001770cd55]={
  id=g_str_5fb1ba29e1af06001770cd55,
  name='Raiders',
  min=0,
  max=1,
  description='Mercenary thureophoroi',
  troop_type="Raiders",
  troop_option_id="5fb1ba29e1af06001770cd53",
}
g_str_5fb1b9dee1af0600177096ce_camp='5fb1b9dee1af0600177096ce_camp'
g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp]={
  id=g_str_5fb1b9dee1af0600177096ce_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dee1af0600177096ce_camp_pack_train='5fb1b9dee1af0600177096ce_camp_pack_train'
g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp_pack_train]={
  id=g_str_5fb1b9dee1af0600177096ce_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dee1af0600177096ce']={
  data={
    name='Ariariathid Kappadokian  330 BC to 17 AD'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd52],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd55],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096ce"] = army["5fb1b9dee1af0600177096ce"]
army['5fb1b9dee1af0600177096ce_-330_-322']={
  data={
    name='Ariariathid Kappadokian 330 BC to 322 BC'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd52],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp_pack_train],
}
army['5fb1b9dee1af0600177096ce_-321_-301']={
  data={
    name='Ariariathid Kappadokian 321 BC to 301 BC'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4c],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp_pack_train],
}
army['5fb1b9dee1af0600177096ce_-300_17']={
  data={
    name='Ariariathid Kappadokian 300 BC to 17 AD'
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd46],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd48],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4a],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd4c],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd55],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ce_camp_pack_train],
}
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Ariariathid Kappadokian  330 BC to 17 AD"] = army["5fb1b9dee1af0600177096ce"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Ariariathid Kappadokian  330 BC to 17 AD"] = army["5fb1b9dee1af0600177096ce"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Ariariathid Kappadokian  330 BC to 17 AD"] = army["5fb1b9dee1af0600177096ce"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Ariariathid Kappadokian  330 BC to 17 AD"] = army["5fb1b9dee1af0600177096ce"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096ce"] = {}
army_dates["5fb1b9dee1af0600177096ce"]["330 BC to 17 AD"] ="5fb1b9dee1af0600177096ce"
army_dates["5fb1b9dee1af0600177096ce"]["330 BC to 322 BC"] ="5fb1b9dee1af0600177096ce_-330_-322"
army_dates["5fb1b9dee1af0600177096ce"]["321 BC to 301 BC"] ="5fb1b9dee1af0600177096ce_-321_-301"
army_dates["5fb1b9dee1af0600177096ce"]["300 BC to 17 AD"] ="5fb1b9dee1af0600177096ce_-300_17"
