-- 5fb1b9f2e1af06001770a23f Chinese Northern Dynasties  317 to 581 AD

army['5fb1b9f2e1af06001770a23f']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Chinese Northern Dynasties  317 to 581 AD',
    id='5fb1b9f2e1af06001770a23f',
    dateRange={
      startDate=317,
      endDate=581,
    },
  },
  g_base_definitions[g_str_615351b403385c0016b8887b_general],
  g_base_definitions[g_str_615351b403385c0016b8887b],
  g_base_definitions[g_str_615351b403385c0016b8887c_general],
  g_base_definitions[g_str_615351b403385c0016b8887c],
  g_base_definitions[g_str_615351b403385c0016b8887e],
  g_base_definitions[g_str_615351b403385c0016b88880],
  g_base_definitions[g_str_615351b403385c0016b88881],
  g_base_definitions[g_str_615351b403385c0016b88883],
  g_base_definitions[g_str_615351b403385c0016b88885],
  g_base_definitions[g_str_615351b403385c0016b88887],
  g_base_definitions[g_str_615351b403385c0016b88889],
  g_base_definitions[g_str_615351b403385c0016b8888b],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a23f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a23f"] = army["5fb1b9f2e1af06001770a23f"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Chinese Northern Dynasties  317 to 581 AD"] = army["5fb1b9f2e1af06001770a23f"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Chinese Northern Dynasties  317 to 581 AD"] = army["5fb1b9f2e1af06001770a23f"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Chinese Northern Dynasties  317 to 581 AD"] = army["5fb1b9f2e1af06001770a23f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Chinese Northern Dynasties  317 to 581 AD"] = army["5fb1b9f2e1af06001770a23f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a23f"] = {}
army_dates["5fb1b9f2e1af06001770a23f"]["317 AD to 581 AD"] = {
  startDate=317,
  endDate=581
}
army_dates["5fb1b9f2e1af06001770a23f"]["317 AD to 460 AD"] = {
  startDate=317,
  endDate=460
}
army_dates["5fb1b9f2e1af06001770a23f"]["461 AD to 549 AD"] = {
  startDate=461,
  endDate=549
}
army_dates["5fb1b9f2e1af06001770a23f"]["550 AD to 581 AD"] = {
  startDate=550,
  endDate=581
}
