-- 5fb1b9f3e1af06001770a2e1 Yuan in the Steppe or Korea  1260 to 1368 AD

army['5fb1b9f3e1af06001770a2e1']={
  data={
    name='Yuan in the Steppe or Korea  1260 to 1368 AD',
    id='5fb1b9f3e1af06001770a2e1',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2e1"] = army["5fb1b9f3e1af06001770a2e1"]
army['5fb1b9f3e1af06001770a2e1_1260_1274']={
  data={
    name='Yuan in the Steppe or Korea 1260 AD to 1274 AD',
    id='5fb1b9f3e1af06001770a2e1_1260_1274',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faad],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
army['5fb1b9f3e1af06001770a2e1_1275_1300']={
  data={
    name='Yuan in the Steppe or Korea 1275 AD to 1300 AD',
    id='5fb1b9f3e1af06001770a2e1_1275_1300',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab0_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
army['5fb1b9f3e1af06001770a2e1_1301_1368']={
  data={
    name='Yuan in the Steppe or Korea 1301 AD to 1368 AD',
    id='5fb1b9f3e1af06001770a2e1_1301_1368',
    army_id='5fb1b9f3e1af06001770a2e1'
  },
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa6_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770faa9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab4_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_general_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab8_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_mounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fab9_dismounted],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc_general],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabc],
  g_base_definitions[g_str_5fb1ba41e1af06001770fabe],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2e1_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba6],
  g_base_definitions[g_str_5fb1ba19e1af06001770bba8],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbaa],
  g_base_definitions[g_str_5fb1ba19e1af06001770bbac],
}
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Yuan in the Steppe or Korea  1260 to 1368 AD"] = army["5fb1b9f3e1af06001770a2e1"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Yuan in the Steppe or Korea  1260 to 1368 AD"] = army["5fb1b9f3e1af06001770a2e1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Yuan in the Steppe or Korea  1260 to 1368 AD"] = army["5fb1b9f3e1af06001770a2e1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2e1"] = {}
army_dates["5fb1b9f3e1af06001770a2e1"]["1260 AD to 1368 AD"] ="5fb1b9f3e1af06001770a2e1"
army_dates["5fb1b9f3e1af06001770a2e1"]["1260 AD to 1274 AD"] ="5fb1b9f3e1af06001770a2e1_1260_1274"
army_dates["5fb1b9f3e1af06001770a2e1"]["1275 AD to 1300 AD"] ="5fb1b9f3e1af06001770a2e1_1275_1300"
army_dates["5fb1b9f3e1af06001770a2e1"]["1301 AD to 1368 AD"] ="5fb1b9f3e1af06001770a2e1_1301_1368"
