g_str_5fb1ba2de1af06001770d624_general='5fb1ba2de1af06001770d624_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d624_general]={
  id=g_str_5fb1ba2de1af06001770d624_general,
  name='Cataphracts General',
  min=1,
  max=1,
  description='Asvaran catafractarii',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2de1af06001770d623",
}
g_str_5fb1ba2de1af06001770d624='5fb1ba2de1af06001770d624'
g_base_definitions[g_str_5fb1ba2de1af06001770d624]={
  id=g_str_5fb1ba2de1af06001770d624,
  name='Cataphracts',
  min=1,
  max=3,
  description='Asvaran catafractarii',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2de1af06001770d623",
}
g_str_5fb1ba2de1af06001770d626_general='5fb1ba2de1af06001770d626_general'
g_base_definitions[g_str_5fb1ba2de1af06001770d626_general]={
  id=g_str_5fb1ba2de1af06001770d626_general,
  name='Elite Cavalry General',
  min=1,
  max=1,
  description='Asvaran clibinarii',
  general=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba2de1af06001770d625",
}
g_str_5fb1ba2de1af06001770d626_general_shower_shooting='5fb1ba2de1af06001770d626_general_shower_shooting'
g_base_definitions[g_str_5fb1ba2de1af06001770d626_general_shower_shooting]={
  id=g_str_5fb1ba2de1af06001770d626_general_shower_shooting,
  name='Elite Cavalry General',
  min=1,
  max=1,
  description='Asvaran clibinarii\nShower Shooting',
  general=true,
  shower_shooting=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba2de1af06001770d625",
}
g_str_5fb1ba2de1af06001770d626='5fb1ba2de1af06001770d626'
g_base_definitions[g_str_5fb1ba2de1af06001770d626]={
  id=g_str_5fb1ba2de1af06001770d626,
  name='Elite Cavalry',
  min=1,
  max=4,
  description='Asvaran clibinarii',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba2de1af06001770d625",
}
g_str_5fb1ba2de1af06001770d626_shower_shooting='5fb1ba2de1af06001770d626_shower_shooting'
g_base_definitions[g_str_5fb1ba2de1af06001770d626_shower_shooting]={
  id=g_str_5fb1ba2de1af06001770d626_shower_shooting,
  name='Elite Cavalry',
  min=1,
  max=4,
  description='Asvaran clibinarii\nShower Shooting',
  shower_shooting=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba2de1af06001770d625",
}
g_str_5fb1ba2de1af06001770d629='5fb1ba2de1af06001770d629'
g_base_definitions[g_str_5fb1ba2de1af06001770d629]={
  id=g_str_5fb1ba2de1af06001770d629,
  name='Horse Bow',
  min=4,
  max=10,
  description='Retainer horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2de1af06001770d628",
}
g_str_5fb1ba2de1af06001770d62b='5fb1ba2de1af06001770d62b'
g_base_definitions[g_str_5fb1ba2de1af06001770d62b]={
  id=g_str_5fb1ba2de1af06001770d62b,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Paighan spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2de1af06001770d62a",
}
g_str_5fb1ba2de1af06001770d62b_elephant_screen='5fb1ba2de1af06001770d62b_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d62b_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d62b_elephant_screen,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Paighan spearmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2de1af06001770d62a",
}
g_str_5fb1ba2de1af06001770d62b_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d62b_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d62b_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d62b_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=2,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d62e='5fb1ba2de1af06001770d62e'
g_base_definitions[g_str_5fb1ba2de1af06001770d62e]={
  id=g_str_5fb1ba2de1af06001770d62e,
  name='Bow Levy',
  min=0,
  max=4,
  description='Paighan bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba2de1af06001770d62d",
}
g_str_5fb1ba2de1af06001770d62e_elephant_screen='5fb1ba2de1af06001770d62e_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d62e_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d62e_elephant_screen,
  name='Bow Levy',
  min=0,
  max=4,
  description='Paighan bowmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba2de1af06001770d62d",
}
g_str_5fb1ba2de1af06001770d62e_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d62e_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d62e_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d62e_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d631='5fb1ba2de1af06001770d631'
g_base_definitions[g_str_5fb1ba2de1af06001770d631]={
  id=g_str_5fb1ba2de1af06001770d631,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2de1af06001770d630",
}
g_str_5fb1ba2de1af06001770d633='5fb1ba2de1af06001770d633'
g_base_definitions[g_str_5fb1ba2de1af06001770d633]={
  id=g_str_5fb1ba2de1af06001770d633,
  name='Horde',
  min=0,
  max=4,
  description='Peasant throng',
  troop_type="Horde",
  troop_option_id="5fb1ba2de1af06001770d632",
}
g_str_5fb1ba2de1af06001770d633_elephant_screen='5fb1ba2de1af06001770d633_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d633_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d633_elephant_screen,
  name='Horde',
  min=0,
  max=4,
  description='Peasant throng\nElephant Screen',
  elephant_screen=true,
  troop_type="Horde",
  troop_option_id="5fb1ba2de1af06001770d632",
}
g_str_5fb1ba2de1af06001770d633_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d633_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d633_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d633_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d634='5fb1ba2de1af06001770d634'
g_base_definitions[g_str_5fb1ba2de1af06001770d634]={
  id=g_str_5fb1ba2de1af06001770d634,
  name='Rabble',
  min=0,
  max=4,
  description='Peasant throng',
  troop_type="Rabble",
  troop_option_id="5fb1ba2de1af06001770d632",
}
g_str_5fb1ba2de1af06001770d634_elephant_screen='5fb1ba2de1af06001770d634_elephant_screen'
g_base_definitions[g_str_5fb1ba2de1af06001770d634_elephant_screen]={
  id=g_str_5fb1ba2de1af06001770d634_elephant_screen,
  name='Rabble',
  min=0,
  max=4,
  description='Peasant throng\nElephant Screen',
  elephant_screen=true,
  troop_type="Rabble",
  troop_option_id="5fb1ba2de1af06001770d632",
}
g_str_5fb1ba2de1af06001770d634_elephant_screen_elephant_screen_counter='5fb1ba2de1af06001770d634_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba2de1af06001770d634_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba2de1af06001770d634_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=0,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba2de1af06001770d637='5fb1ba2de1af06001770d637'
g_base_definitions[g_str_5fb1ba2de1af06001770d637]={
  id=g_str_5fb1ba2de1af06001770d637,
  name='Elephants',
  min=0,
  max=2,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba2de1af06001770d636",
}
g_str_5fb1b9e2e1af060017709948_camp='5fb1b9e2e1af060017709948_camp'
g_base_definitions[g_str_5fb1b9e2e1af060017709948_camp]={
  id=g_str_5fb1b9e2e1af060017709948_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af060017709948_camp_fortified='5fb1b9e2e1af060017709948_camp_fortified'
g_base_definitions[g_str_5fb1b9e2e1af060017709948_camp_fortified]={
  id=g_str_5fb1b9e2e1af060017709948_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9e2e1af060017709948_camp_pack_train='5fb1b9e2e1af060017709948_camp_pack_train'
g_base_definitions[g_str_5fb1b9e2e1af060017709948_camp_pack_train]={
  id=g_str_5fb1b9e2e1af060017709948_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
