g_str_5fb1ba1fe1af06001770be67_general='5fb1ba1fe1af06001770be67_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770be67_general]={
  id=g_str_5fb1ba1fe1af06001770be67_general,
  name='Battle Taxi General',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770be66",
}
g_str_5fb1ba1fe1af06001770be67='5fb1ba1fe1af06001770be67'
g_base_definitions[g_str_5fb1ba1fe1af06001770be67]={
  id=g_str_5fb1ba1fe1af06001770be67,
  name='Battle Taxi',
  min=0,
  max=1,
  description='4-wheeled battle platforms or straddle cars',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba1fe1af06001770be66",
}
g_str_5fb1ba1fe1af06001770be69_general='5fb1ba1fe1af06001770be69_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770be69_general]={
  id=g_str_5fb1ba1fe1af06001770be69_general,
  name='Archers General',
  min=0,
  max=1,
  description='Household bowmen',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770be68",
}
g_str_5fb1ba1fe1af06001770be69='5fb1ba1fe1af06001770be69'
g_base_definitions[g_str_5fb1ba1fe1af06001770be69]={
  id=g_str_5fb1ba1fe1af06001770be69,
  name='Archers',
  min=0,
  max=1,
  description='Household bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770be68",
}
g_str_5fb1ba1fe1af06001770be6b_general='5fb1ba1fe1af06001770be6b_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770be6b_general]={
  id=g_str_5fb1ba1fe1af06001770be6b_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Household retinue',
  general=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770be6a",
}
g_str_5fb1ba1fe1af06001770be6b='5fb1ba1fe1af06001770be6b'
g_base_definitions[g_str_5fb1ba1fe1af06001770be6b]={
  id=g_str_5fb1ba1fe1af06001770be6b,
  name='Raiders',
  min=1,
  max=1,
  description='Household retinue',
  troop_type="Raiders",
  troop_option_id="5fb1ba1fe1af06001770be6a",
}
g_str_5fb1ba1fe1af06001770be6e='5fb1ba1fe1af06001770be6e'
g_base_definitions[g_str_5fb1ba1fe1af06001770be6e]={
  id=g_str_5fb1ba1fe1af06001770be6e,
  name='Pikes',
  min=6,
  max=11,
  description='Household or militia spearmen with large rectangular shield',
  troop_type="Pikes",
  troop_option_id="5fb1ba1fe1af06001770be6c",
}
g_str_5fb1ba1fe1af06001770be6f='5fb1ba1fe1af06001770be6f'
g_base_definitions[g_str_5fb1ba1fe1af06001770be6f]={
  id=g_str_5fb1ba1fe1af06001770be6f,
  name='Light Spear',
  min=6,
  max=11,
  description='Household or militia spearmen with large rectangular shield',
  troop_type="Light Spear",
  troop_option_id="5fb1ba1fe1af06001770be6c",
}
g_str_5fb1ba1fe1af06001770be72='5fb1ba1fe1af06001770be72'
g_base_definitions[g_str_5fb1ba1fe1af06001770be72]={
  id=g_str_5fb1ba1fe1af06001770be72,
  name='Heavy Foot',
  min=6,
  max=11,
  description='Household or militia spearmen with Amorite shield',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba1fe1af06001770be70",
}
g_str_5fb1ba1fe1af06001770be75='5fb1ba1fe1af06001770be75'
g_base_definitions[g_str_5fb1ba1fe1af06001770be75]={
  id=g_str_5fb1ba1fe1af06001770be75,
  name='Pikes',
  min=0,
  max=6,
  description='Household or militia spearmen with large rectangular shield',
  troop_type="Pikes",
  troop_option_id="5fb1ba1fe1af06001770be73",
}
g_str_5fb1ba1fe1af06001770be76='5fb1ba1fe1af06001770be76'
g_base_definitions[g_str_5fb1ba1fe1af06001770be76]={
  id=g_str_5fb1ba1fe1af06001770be76,
  name='Light Spear',
  min=0,
  max=6,
  description='Household or militia spearmen with large rectangular shield',
  troop_type="Light Spear",
  troop_option_id="5fb1ba1fe1af06001770be73",
}
g_str_5fb1ba1fe1af06001770be78='5fb1ba1fe1af06001770be78'
g_base_definitions[g_str_5fb1ba1fe1af06001770be78]={
  id=g_str_5fb1ba1fe1af06001770be78,
  name='Bow Levy',
  min=0,
  max=2,
  description='Highlander or Elamite bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba1fe1af06001770be77",
}
g_str_5fb1ba1fe1af06001770be7a='5fb1ba1fe1af06001770be7a'
g_base_definitions[g_str_5fb1ba1fe1af06001770be7a]={
  id=g_str_5fb1ba1fe1af06001770be7a,
  name='Skirmishers',
  min=3,
  max=5,
  description='Nomadic and levy bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba1fe1af06001770be79",
}
g_str_5fb1ba1fe1af06001770be7c='5fb1ba1fe1af06001770be7c'
g_base_definitions[g_str_5fb1ba1fe1af06001770be7c]={
  id=g_str_5fb1ba1fe1af06001770be7c,
  name='Rabble',
  min=1,
  max=5,
  description='Frontier troops, levy, or nomadic javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba1fe1af06001770be7b",
}
g_str_5fb1ba1fe1af06001770be7e='5fb1ba1fe1af06001770be7e'
g_base_definitions[g_str_5fb1ba1fe1af06001770be7e]={
  id=g_str_5fb1ba1fe1af06001770be7e,
  name='Light Foot',
  min=0,
  max=4,
  description='Amurru bedouin levies and effective frontier troops',
  troop_type="Light Foot",
  troop_option_id="5fb1ba1fe1af06001770be7d",
}
g_str_5fb1b9d8e1af0600177092e5_camp='5fb1b9d8e1af0600177092e5_camp'
g_base_definitions[g_str_5fb1b9d8e1af0600177092e5_camp]={
  id=g_str_5fb1b9d8e1af0600177092e5_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d8e1af0600177092e5_camp_fortified='5fb1b9d8e1af0600177092e5_camp_fortified'
g_base_definitions[g_str_5fb1b9d8e1af0600177092e5_camp_fortified]={
  id=g_str_5fb1b9d8e1af0600177092e5_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  troop_type="Camp",
}
g_str_5fb1b9d8e1af0600177092e5_camp_pack_train='5fb1b9d8e1af0600177092e5_camp_pack_train'
g_base_definitions[g_str_5fb1b9d8e1af0600177092e5_camp_pack_train]={
  id=g_str_5fb1b9d8e1af0600177092e5_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
