g_str_5fb1ba3de1af06001770f3f2_general='5fb1ba3de1af06001770f3f2_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f2_general]={
  id=g_str_5fb1ba3de1af06001770f3f2_general,
  name='Elephants General',
  min=2,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
  troop_option_id="5fb1ba3de1af06001770f3f1",
}
g_str_5fb1ba3de1af06001770f3f2='5fb1ba3de1af06001770f3f2'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f2]={
  id=g_str_5fb1ba3de1af06001770f3f2,
  name='Elephants',
  min=2,
  max=3,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba3de1af06001770f3f1",
}
g_str_5fb1ba3de1af06001770f3f5_general='5fb1ba3de1af06001770f3f5_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f5_general]={
  id=g_str_5fb1ba3de1af06001770f3f5_general,
  name='Chariots General',
  min=0,
  max=1,
  description='2-horse chariots with bow-armed crew',
  general=true,
  troop_type="Chariots",
  troop_option_id="5fb1ba3de1af06001770f3f4",
}
g_str_5fb1ba3de1af06001770f3f5='5fb1ba3de1af06001770f3f5'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f5]={
  id=g_str_5fb1ba3de1af06001770f3f5,
  name='Chariots',
  min=0,
  max=1,
  description='2-horse chariots with bow-armed crew',
  troop_type="Chariots",
  troop_option_id="5fb1ba3de1af06001770f3f4",
}
g_str_5fb1ba3de1af06001770f3f7='5fb1ba3de1af06001770f3f7'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f7]={
  id=g_str_5fb1ba3de1af06001770f3f7,
  name='Bad Horse',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba3de1af06001770f3f6",
}
g_str_5fb1ba3de1af06001770f3f9='5fb1ba3de1af06001770f3f9'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f9]={
  id=g_str_5fb1ba3de1af06001770f3f9,
  name='Raiders',
  min=2,
  max=4,
  description='Jacketed spearmen with long shield',
  troop_type="Raiders",
  troop_option_id="5fb1ba3de1af06001770f3f8",
}
g_str_5fb1ba3de1af06001770f3f9_elephant_screen='5fb1ba3de1af06001770f3f9_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f9_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f3f9_elephant_screen,
  name='Raiders',
  min=2,
  max=4,
  description='Jacketed spearmen with long shield\nElephant Screen',
  elephant_screen=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba3de1af06001770f3f8",
}
g_str_5fb1ba3de1af06001770f3f9_elephant_screen_elephant_screen_counter='5fb1ba3de1af06001770f3f9_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3de1af06001770f3f9_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3de1af06001770f3f9_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=2,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3de1af06001770f3fd='5fb1ba3de1af06001770f3fd'
g_base_definitions[g_str_5fb1ba3de1af06001770f3fd]={
  id=g_str_5fb1ba3de1af06001770f3fd,
  name='Light Foot',
  min=2,
  max=4,
  description='Jacketed spearmen with small round shield',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3de1af06001770f3fc",
}
g_str_5fb1ba3de1af06001770f3fd_elephant_screen='5fb1ba3de1af06001770f3fd_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f3fd_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f3fd_elephant_screen,
  name='Light Foot',
  min=2,
  max=4,
  description='Jacketed spearmen with small round shield\nElephant Screen',
  elephant_screen=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba3de1af06001770f3fc",
}
g_str_5fb1ba3de1af06001770f3fd_elephant_screen_elephant_screen_counter='5fb1ba3de1af06001770f3fd_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3de1af06001770f3fd_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3de1af06001770f3fd_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=2,
  max=4,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3de1af06001770f400='5fb1ba3de1af06001770f400'
g_base_definitions[g_str_5fb1ba3de1af06001770f400]={
  id=g_str_5fb1ba3de1af06001770f400,
  name='Skirmishers',
  min=2,
  max=4,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3de1af06001770f3ff",
}
g_str_5fb1ba3de1af06001770f403='5fb1ba3de1af06001770f403'
g_base_definitions[g_str_5fb1ba3de1af06001770f403]={
  id=g_str_5fb1ba3de1af06001770f403,
  name='Archers',
  min=0,
  max=1,
  description='Bowmen protected by pavises',
  troop_type="Archers",
  troop_option_id="5fb1ba3de1af06001770f402",
}
g_str_5fb1ba3de1af06001770f405='5fb1ba3de1af06001770f405'
g_base_definitions[g_str_5fb1ba3de1af06001770f405]={
  id=g_str_5fb1ba3de1af06001770f405,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3de1af06001770f404",
}
g_str_5fb1ba3de1af06001770f407='5fb1ba3de1af06001770f407'
g_base_definitions[g_str_5fb1ba3de1af06001770f407]={
  id=g_str_5fb1ba3de1af06001770f407,
  name='Warband',
  min=0,
  max=4,
  description='Hill tribe fighters',
  troop_type="Warband",
  troop_option_id="5fb1ba3de1af06001770f406",
}
g_str_5fb1ba3de1af06001770f40a='5fb1ba3de1af06001770f40a'
g_base_definitions[g_str_5fb1ba3de1af06001770f40a]={
  id=g_str_5fb1ba3de1af06001770f40a,
  name='Bad Horse',
  min=0,
  max=1,
  description='Chinese-style armored crossbow horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba3de1af06001770f408",
}
g_str_5fb1ba3de1af06001770f40d='5fb1ba3de1af06001770f40d'
g_base_definitions[g_str_5fb1ba3de1af06001770f40d]={
  id=g_str_5fb1ba3de1af06001770f40d,
  name='Artillery',
  min=0,
  max=1,
  description='Wheeled or elephant-mounted Song-style ballista',
  troop_type="Artillery",
  troop_option_id="5fb1ba3de1af06001770f40b",
}
g_str_5fb1b9f0e1af06001770a0f0_camp='5fb1b9f0e1af06001770a0f0_camp'
g_base_definitions[g_str_5fb1b9f0e1af06001770a0f0_camp]={
  id=g_str_5fb1b9f0e1af06001770a0f0_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f0e1af06001770a0f0_camp_pack_train='5fb1b9f0e1af06001770a0f0_camp_pack_train'
g_base_definitions[g_str_5fb1b9f0e1af06001770a0f0_camp_pack_train]={
  id=g_str_5fb1b9f0e1af06001770a0f0_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1ba18e1af06001770bab8='5fb1ba18e1af06001770bab8'
g_base_definitions[g_str_5fb1ba18e1af06001770bab8]={
  id=g_str_5fb1ba18e1af06001770bab8,
  name='Rabble',
  min=1,
  max=2,
  description='Ten Circuit spearmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba18e1af06001770bab7",
}
g_str_5fb1ba18e1af06001770baba='5fb1ba18e1af06001770baba'
g_base_definitions[g_str_5fb1ba18e1af06001770baba]={
  id=g_str_5fb1ba18e1af06001770baba,
  name='Bow Levy',
  min=2,
  max=4,
  description='Ten Circuit bowmen and crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba18e1af06001770bab9",
}
g_str_5fb1ba18e1af06001770babd='5fb1ba18e1af06001770babd'
g_base_definitions[g_str_5fb1ba18e1af06001770babd]={
  id=g_str_5fb1ba18e1af06001770babd,
  name='Light Foot',
  min=0,
  max=1,
  description='Regional spearmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba18e1af06001770babb",
}
g_str_5fb1ba18e1af06001770bac0='5fb1ba18e1af06001770bac0'
g_base_definitions[g_str_5fb1ba18e1af06001770bac0]={
  id=g_str_5fb1ba18e1af06001770bac0,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Regional halberdiers or swordsmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba18e1af06001770babe",
}
g_str_5fb1ba18e1af06001770bac2='5fb1ba18e1af06001770bac2'
g_base_definitions[g_str_5fb1ba18e1af06001770bac2]={
  id=g_str_5fb1ba18e1af06001770bac2,
  name='Bow Levy',
  min=0,
  max=1,
  description='Regional bowmen and crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba18e1af06001770bac1",
}
g_str_5fb1ba18e1af06001770bac5='5fb1ba18e1af06001770bac5'
g_base_definitions[g_str_5fb1ba18e1af06001770bac5]={
  id=g_str_5fb1ba18e1af06001770bac5,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba18e1af06001770bac3",
}
