troop_options['5fb1ba28e1af06001770cb5f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
troop_options['5fb1ba28e1af06001770cb61'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
troop_options['5fb1ba28e1af06001770cb63'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-298,
  }
}
troop_options['5fb1ba28e1af06001770cb66'] = {
  min=4,
  max=8,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
troop_options['5fb1ba28e1af06001770cb68'] = {
  min=4,
  max=8,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
troop_options['5fb1ba28e1af06001770cb6a'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
troop_options['5fb1ba28e1af06001770cb6c'] = {
  min=2,
  max=3,
  dateRange={
    startDate=-317,
    endDate=-316,
  }
}
troop_options['5fb1ba28e1af06001770cb6f'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-318,
    endDate=-302,
  }
}
troop_options['5fb1ba28e1af06001770cb73'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
troop_options['5fb1ba28e1af06001770cb75'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
troop_options['5fb1ba28e1af06001770cb77'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-320,
    endDate=-279,
  }
}
-- allies
