-- 5fb1b9dfe1af0600177096de Early Rhoxolani Sarmatian  310 BC to 100 AD

army['5fb1b9dfe1af0600177096de']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Early Rhoxolani Sarmatian  310 BC to 100 AD',
    id='5fb1b9dfe1af0600177096de',
    dateRange={
      startDate=-310,
      endDate=100,
    }
  },
  g_base_definitions[g_str_5fb1ba29e1af06001770cd6f_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd6f],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd71_general],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd71],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd73],
  g_base_definitions[g_str_5fb1ba29e1af06001770cd75],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096de_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af0600177096de"] = army["5fb1b9dfe1af0600177096de"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Rhoxolani Sarmatian  310 BC to 100 AD"] = army["5fb1b9dfe1af0600177096de"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early Rhoxolani Sarmatian  310 BC to 100 AD"] = army["5fb1b9dfe1af0600177096de"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Rhoxolani Sarmatian  310 BC to 100 AD"] = army["5fb1b9dfe1af0600177096de"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Rhoxolani Sarmatian  310 BC to 100 AD"] = army["5fb1b9dfe1af0600177096de"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af0600177096de"] = {}
army_dates["5fb1b9dfe1af0600177096de"]["310 BC to 100 AD"] = {
  startDate=-310,
  endDate=100
}
army_dates["5fb1b9dfe1af0600177096de"]["310 BC to 300 BC"] = {
  startDate=-310,
  endDate=-300
}
army_dates["5fb1b9dfe1af0600177096de"]["299 BC to 100 AD"] = {
  startDate=-299,
  endDate=100
}
