-- 5fb1b9e4e1af0600177099eb Slav or Wend  580 to 1218 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ee1af06001770d84d_general='5fb1ba2ee1af06001770d84d_general'
g_base_definitions[g_str_5fb1ba2ee1af06001770d84d_general]={
  id=g_str_5fb1ba2ee1af06001770d84d_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Noble horsemen',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ee1af06001770d84d='5fb1ba2ee1af06001770d84d'
g_base_definitions[g_str_5fb1ba2ee1af06001770d84d]={
  id=g_str_5fb1ba2ee1af06001770d84d,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Noble horsemen',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ee1af06001770d84f_general='5fb1ba2ee1af06001770d84f_general'
g_base_definitions[g_str_5fb1ba2ee1af06001770d84f_general]={
  id=g_str_5fb1ba2ee1af06001770d84f_general,
  name='Light Foot General',
  min=6,
  max=1,
  description='Javelinmen',
  general=true,
  troop_type="Light Foot",
}
g_str_5fb1ba2ee1af06001770d84f='5fb1ba2ee1af06001770d84f'
g_base_definitions[g_str_5fb1ba2ee1af06001770d84f]={
  id=g_str_5fb1ba2ee1af06001770d84f,
  name='Light Foot',
  min=6,
  max=14,
  description='Javelinmen',
  troop_type="Light Foot",
}
g_str_5fb1ba2ee1af06001770d852='5fb1ba2ee1af06001770d852'
g_base_definitions[g_str_5fb1ba2ee1af06001770d852]={
  id=g_str_5fb1ba2ee1af06001770d852,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Steady foot',
  troop_type="Heavy Foot",
}
g_str_5fb1ba2ee1af06001770d854='5fb1ba2ee1af06001770d854'
g_base_definitions[g_str_5fb1ba2ee1af06001770d854]={
  id=g_str_5fb1ba2ee1af06001770d854,
  name='Skirmishers',
  min=1,
  max=5,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba2ee1af06001770d855='5fb1ba2ee1af06001770d855'
g_base_definitions[g_str_5fb1ba2ee1af06001770d855]={
  id=g_str_5fb1ba2ee1af06001770d855,
  name='Bow Levy',
  min=1,
  max=5,
  description='Skirmishing bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba2ee1af06001770d857='5fb1ba2ee1af06001770d857'
g_base_definitions[g_str_5fb1ba2ee1af06001770d857]={
  id=g_str_5fb1ba2ee1af06001770d857,
  name='Rabble',
  min=0,
  max=9,
  description='Scouts and poorly-armed infantry',
  troop_type="Rabble",
}
g_str_5fb1ba2ee1af06001770d85a='5fb1ba2ee1af06001770d85a'
g_base_definitions[g_str_5fb1ba2ee1af06001770d85a]={
  id=g_str_5fb1ba2ee1af06001770d85a,
  name='Raiders',
  min=0,
  max=2,
  description='Viking mercenaries',
  troop_type="Raiders",
}
g_str_5fb1ba2ee1af06001770d85d='5fb1ba2ee1af06001770d85d'
g_base_definitions[g_str_5fb1ba2ee1af06001770d85d]={
  id=g_str_5fb1ba2ee1af06001770d85d,
  name='Knights',
  min=0,
  max=1,
  description='Danish, Saxon, or Thuringian mercenary horsemen',
  troop_type="Knights",
}
g_str_5fb1b9e4e1af0600177099eb_camp='5fb1b9e4e1af0600177099eb_camp'
g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp]={
  id=g_str_5fb1b9e4e1af0600177099eb_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e4e1af0600177099eb_camp_fortified='5fb1b9e4e1af0600177099eb_camp_fortified'
g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp_fortified]={
  id=g_str_5fb1b9e4e1af0600177099eb_camp_fortified,
  name='Fortified Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e4e1af0600177099eb_camp_pack_train='5fb1b9e4e1af0600177099eb_camp_pack_train'
g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp_pack_train]={
  id=g_str_5fb1b9e4e1af0600177099eb_camp_pack_train,
  name='Pack Train',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e4e1af0600177099eb']={
  data={
    name='Slav or Wend  580 to 1218 AD'
  },
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84d_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84d],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84f_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84f],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d852],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d854],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d855],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d857],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d85a],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d85d],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp_fortified],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af0600177099eb"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
