-- 5fb1b9e4e1af060017709a03 Early Danube Bulgar  675 to 802 AD

army['5fb1b9e4e1af060017709a03']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Early Danube Bulgar  675 to 802 AD',
    id='5fb1b9e4e1af060017709a03',
    dateRange={
      startDate=675,
      endDate=802,
    },
  },
  g_base_definitions[g_str_615351a803385c0016b86910_general],
  g_base_definitions[g_str_615351a803385c0016b86910],
  g_base_definitions[g_str_615351a803385c0016b86912],
  g_base_definitions[g_str_615351a803385c0016b86914],
  g_base_definitions[g_str_615351a803385c0016b86914_mounted_mobile_infantry],
  g_base_definitions[g_str_615351a803385c0016b86914_dismounted_mobile_infantry],
  g_base_definitions[g_str_615351a803385c0016b86915],
  g_base_definitions[g_str_615351a803385c0016b86915_mounted_mobile_infantry],
  g_base_definitions[g_str_615351a803385c0016b86915_dismounted_mobile_infantry],
  g_base_definitions[g_str_615351a803385c0016b86918],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a03_camp],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a03_camp_pack_train],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a03_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a03"] = army["5fb1b9e4e1af060017709a03"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Early Danube Bulgar  675 to 802 AD"] = army["5fb1b9e4e1af060017709a03"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Early Danube Bulgar  675 to 802 AD"] = army["5fb1b9e4e1af060017709a03"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Danube Bulgar  675 to 802 AD"] = army["5fb1b9e4e1af060017709a03"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a03"] = {}
army_dates["5fb1b9e4e1af060017709a03"]["675 AD to 802 AD"] = {
  startDate=675,
  endDate=802
}
