-- 5fb1b9f0e1af06001770a158 Early Spring and Autumn Chinese  770 to 550 BC

army['5fb1b9f0e1af06001770a158']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
      0,
      2,
    },
    homeTopographies={
      'Hilly',
      'Arable',
      'Forest',
      'Arable',
    },
    name='Early Spring and Autumn Chinese  770 to 550 BC',
    id='5fb1b9f0e1af06001770a158',
    dateRange={
      startDate=-770,
      endDate=-550,
    }
  },
  g_base_definitions[g_str_5fb1ba3ee1af06001770f536_general],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f536],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f538],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f539],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f53c],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f53e],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a158_camp],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a158_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a158"] = army["5fb1b9f0e1af06001770a158"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Early Spring and Autumn Chinese  770 to 550 BC"] = army["5fb1b9f0e1af06001770a158"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Spring and Autumn Chinese  770 to 550 BC"] = army["5fb1b9f0e1af06001770a158"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a158"] = {}
army_dates["5fb1b9f0e1af06001770a158"]["770 BC to 550 BC"] = {
  startDate=-770,
  endDate=-550
}
