-- 5fb1b9ede1af060017709f72 Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD

army['5fb1b9ede1af060017709f72']={
  data={
    name='Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD',
    id='5fb1b9ede1af060017709f72',
    army_id='5fb1b9ede1af060017709f72'
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf8],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edfb],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edfe],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f72"] = army["5fb1b9ede1af060017709f72"]
army['5fb1b9ede1af060017709f72_1037_1096']={
  data={
    name='Great Seljuq or Seljuq Sultanate of Rum 1037 AD to 1096 AD',
    id='5fb1b9ede1af060017709f72_1037_1096',
    army_id='5fb1b9ede1af060017709f72'
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp_pack_train],
}
army['5fb1b9ede1af060017709f72_1097_1097']={
  data={
    name='Great Seljuq or Seljuq Sultanate of Rum 1097 AD',
    id='5fb1b9ede1af060017709f72_1097_1097',
    army_id='5fb1b9ede1af060017709f72'
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf8],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp_pack_train],
}
army['5fb1b9ede1af060017709f72_1098_1219']={
  data={
    name='Great Seljuq or Seljuq Sultanate of Rum 1098 AD to 1219 AD',
    id='5fb1b9ede1af060017709f72_1098_1219',
    army_id='5fb1b9ede1af060017709f72'
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp_pack_train],
}
army['5fb1b9ede1af060017709f72_1220_1243']={
  data={
    name='Great Seljuq or Seljuq Sultanate of Rum 1220 AD to 1243 AD',
    id='5fb1b9ede1af060017709f72_1220_1243',
    army_id='5fb1b9ede1af060017709f72'
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edfb],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edfe],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp_pack_train],
}
army['5fb1b9ede1af060017709f72_1244_1276']={
  data={
    name='Great Seljuq or Seljuq Sultanate of Rum 1244 AD to 1276 AD',
    id='5fb1b9ede1af060017709f72_1244_1276',
    army_id='5fb1b9ede1af060017709f72'
  },
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770ede9],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edec],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee_general],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edee],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf0],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf2],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ae1af06001770edf4_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp_pack_train],
}
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Great Seljuq or Seljuq Sultanate of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f72"] = {}
army_dates["5fb1b9ede1af060017709f72"]["1037 AD to 1276 AD"] ="5fb1b9ede1af060017709f72"
army_dates["5fb1b9ede1af060017709f72"]["1037 AD to 1096 AD"] ="5fb1b9ede1af060017709f72_1037_1096"
army_dates["5fb1b9ede1af060017709f72"]["1097 AD"] ="5fb1b9ede1af060017709f72_1097_1097"
army_dates["5fb1b9ede1af060017709f72"]["1098 AD to 1219 AD"] ="5fb1b9ede1af060017709f72_1098_1219"
army_dates["5fb1b9ede1af060017709f72"]["1220 AD to 1243 AD"] ="5fb1b9ede1af060017709f72_1220_1243"
army_dates["5fb1b9ede1af060017709f72"]["1244 AD to 1276 AD"] ="5fb1b9ede1af060017709f72_1244_1276"
