-- 5fb1b9efe1af06001770a068 Central Asian Turkish  550 to 1330 AD

army['5fb1b9efe1af06001770a068']={
  data={
    invasionRatings={
      {
        value=3,
        note='',
      },
    },
    name='Central Asian Turkish  550 to 1330 AD',
    id='5fb1b9efe1af06001770a068',
    dateRange={
      startDate=550,
      endDate=1330,
    }
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1d8_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1d8],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1d9_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1d9],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1db_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1db],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1dd_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1dd],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1df],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1df_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1df_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1e3],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f1e5],
  g_base_definitions[g_str_5fb1b9efe1af06001770a068_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a068_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a068"] = army["5fb1b9efe1af06001770a068"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Central Asian Turkish  550 to 1330 AD"] = army["5fb1b9efe1af06001770a068"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Central Asian Turkish  550 to 1330 AD"] = army["5fb1b9efe1af06001770a068"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a068"] = {}
army_dates["5fb1b9efe1af06001770a068"]["550 AD to 1330 AD"] = {
  startDate=550,
  endDate=1330
}
army_dates["5fb1b9efe1af06001770a068"]["550 AD to 558 AD"] = {
  startDate=550,
  endDate=558
}
army_dates["5fb1b9efe1af06001770a068"]["559 AD"] = {
  startDate=559,
  endDate=559
}
army_dates["5fb1b9efe1af06001770a068"]["560 AD to 564 AD"] = {
  startDate=560,
  endDate=564
}
army_dates["5fb1b9efe1af06001770a068"]["565 AD to 575 AD"] = {
  startDate=565,
  endDate=575
}
army_dates["5fb1b9efe1af06001770a068"]["576 AD"] = {
  startDate=576,
  endDate=576
}
army_dates["5fb1b9efe1af06001770a068"]["577 AD to 649 AD"] = {
  startDate=577,
  endDate=649
}
army_dates["5fb1b9efe1af06001770a068"]["650 AD to 656 AD"] = {
  startDate=650,
  endDate=656
}
army_dates["5fb1b9efe1af06001770a068"]["657 AD to 674 AD"] = {
  startDate=657,
  endDate=674
}
army_dates["5fb1b9efe1af06001770a068"]["675 AD to 716 AD"] = {
  startDate=675,
  endDate=716
}
army_dates["5fb1b9efe1af06001770a068"]["717 AD to 730 AD"] = {
  startDate=717,
  endDate=730
}
army_dates["5fb1b9efe1af06001770a068"]["731 AD to 737 AD"] = {
  startDate=731,
  endDate=737
}
army_dates["5fb1b9efe1af06001770a068"]["738 AD to 750 AD"] = {
  startDate=738,
  endDate=750
}
army_dates["5fb1b9efe1af06001770a068"]["751 AD to 906 AD"] = {
  startDate=751,
  endDate=906
}
army_dates["5fb1b9efe1af06001770a068"]["907 AD to 998 AD"] = {
  startDate=907,
  endDate=998
}
army_dates["5fb1b9efe1af06001770a068"]["999 AD to 1065 AD"] = {
  startDate=999,
  endDate=1065
}
army_dates["5fb1b9efe1af06001770a068"]["1066 AD to 1125 AD"] = {
  startDate=1066,
  endDate=1125
}
army_dates["5fb1b9efe1af06001770a068"]["1126 AD to 1212 AD"] = {
  startDate=1126,
  endDate=1212
}
army_dates["5fb1b9efe1af06001770a068"]["1213 AD to 1330 AD"] = {
  startDate=1213,
  endDate=1330
}
