-- 5fb1b9dee1af06001770966b Eumenes  320 to 316 BC

army['5fb1b9dee1af06001770966b']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Arable',
    },
    name='Eumenes  320 to 316 BC',
    id='5fb1b9dee1af06001770966b',
    dateRange={
      startDate=-320,
      endDate=-316,
    },
  },
  g_base_definitions[g_str_5fb1ba28e1af06001770cbbf_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbbf],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbc1_general],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbc1],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbc3],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbc5],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbc5_elephant_screen],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbc8],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbca],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbcd],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbcf],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbd1],
  g_base_definitions[g_str_5fb1ba28e1af06001770cbd4],
  g_base_definitions[g_str_5fb1b9dee1af06001770966b_camp],
  g_base_definitions[g_str_5fb1b9dee1af06001770966b_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af06001770966b"] = army["5fb1b9dee1af06001770966b"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Eumenes  320 to 316 BC"] = army["5fb1b9dee1af06001770966b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Eumenes  320 to 316 BC"] = army["5fb1b9dee1af06001770966b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af06001770966b"] = {}
army_dates["5fb1b9dee1af06001770966b"]["320 BC to 316 BC"] = {
  startDate=-320,
  endDate=-316
}
army_dates["5fb1b9dee1af06001770966b"]["320 BC to 318 BC"] = {
  startDate=-320,
  endDate=-318
}
army_dates["5fb1b9dee1af06001770966b"]["317 BC to 316 BC"] = {
  startDate=-317,
  endDate=-316
}
