-- 5fb1b9f5e1af06001770a3e2 West Mexican  1101 to 1400 AD

army['5fb1b9f5e1af06001770a3e2']={
  data={
    name='West Mexican  1101 to 1400 AD',
    id='5fb1b9f5e1af06001770a3e2',
    army_id='5fb1b9f5e1af06001770a3e2'
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fd9b_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fd9b],
  g_base_definitions[g_str_5fb1ba44e1af06001770fd9d],
  g_base_definitions[g_str_5fb1ba44e1af06001770fd9f],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3e2_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3e2"] = army["5fb1b9f5e1af06001770a3e2"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["West Mexican  1101 to 1400 AD"] = army["5fb1b9f5e1af06001770a3e2"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["West Mexican  1101 to 1400 AD"] = army["5fb1b9f5e1af06001770a3e2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["West Mexican  1101 to 1400 AD"] = army["5fb1b9f5e1af06001770a3e2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3e2"] = {}
army_dates["5fb1b9f5e1af06001770a3e2"]["1101 AD to 1400 AD"] ="5fb1b9f5e1af06001770a3e2"
