g_str_5fb1ba32e1af06001770dd81_general='5fb1ba32e1af06001770dd81_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dd81_general]={
  id=g_str_5fb1ba32e1af06001770dd81_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Retinue and other horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770dd80",
}
g_str_5fb1ba32e1af06001770dd81='5fb1ba32e1af06001770dd81'
g_base_definitions[g_str_5fb1ba32e1af06001770dd81]={
  id=g_str_5fb1ba32e1af06001770dd81,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Retinue and other horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba32e1af06001770dd80",
}
g_str_5fb1ba32e1af06001770dd83_general='5fb1ba32e1af06001770dd83_general'
g_base_definitions[g_str_5fb1ba32e1af06001770dd83_general]={
  id=g_str_5fb1ba32e1af06001770dd83_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Retinue infantry',
  general=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba32e1af06001770dd82",
}
g_str_5fb1ba32e1af06001770dd83='5fb1ba32e1af06001770dd83'
g_base_definitions[g_str_5fb1ba32e1af06001770dd83]={
  id=g_str_5fb1ba32e1af06001770dd83,
  name='Raiders',
  min=1,
  max=2,
  description='Retinue infantry',
  troop_type="Raiders",
  troop_option_id="5fb1ba32e1af06001770dd82",
}
g_str_5fb1ba32e1af06001770dd85='5fb1ba32e1af06001770dd85'
g_base_definitions[g_str_5fb1ba32e1af06001770dd85]={
  id=g_str_5fb1ba32e1af06001770dd85,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Shielded spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba32e1af06001770dd84",
}
g_str_5fb1ba32e1af06001770dd87='5fb1ba32e1af06001770dd87'
g_base_definitions[g_str_5fb1ba32e1af06001770dd87]={
  id=g_str_5fb1ba32e1af06001770dd87,
  name='Light Foot',
  min=1,
  max=3,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba32e1af06001770dd86",
}
g_str_5fb1ba32e1af06001770dd89='5fb1ba32e1af06001770dd89'
g_base_definitions[g_str_5fb1ba32e1af06001770dd89]={
  id=g_str_5fb1ba32e1af06001770dd89,
  name='Bow Levy',
  min=10,
  max=18,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba32e1af06001770dd88",
}
g_str_5fb1b9e6e1af060017709b6f_camp='5fb1b9e6e1af060017709b6f_camp'
g_base_definitions[g_str_5fb1b9e6e1af060017709b6f_camp]={
  id=g_str_5fb1b9e6e1af060017709b6f_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e6e1af060017709b6f_camp_fortified='5fb1b9e6e1af060017709b6f_camp_fortified'
g_base_definitions[g_str_5fb1b9e6e1af060017709b6f_camp_fortified]={
  id=g_str_5fb1b9e6e1af060017709b6f_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9e6e1af060017709b6f_camp_pack_train='5fb1b9e6e1af060017709b6f_camp_pack_train'
g_base_definitions[g_str_5fb1b9e6e1af060017709b6f_camp_pack_train]={
  id=g_str_5fb1b9e6e1af060017709b6f_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
