g_str_5fb1ba42e1af06001770fb95_general='5fb1ba42e1af06001770fb95_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb95_general]={
  id=g_str_5fb1ba42e1af06001770fb95_general,
  name='Heavy Foot General',
  min=2,
  max=1,
  description='Dagger-axe men',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba42e1af06001770fb94",
}
g_str_5fb1ba42e1af06001770fb95='5fb1ba42e1af06001770fb95'
g_base_definitions[g_str_5fb1ba42e1af06001770fb95]={
  id=g_str_5fb1ba42e1af06001770fb95,
  name='Heavy Foot',
  min=2,
  max=5,
  description='Dagger-axe men',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba42e1af06001770fb94",
}
g_str_5fb1ba42e1af06001770fb97_general='5fb1ba42e1af06001770fb97_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb97_general]={
  id=g_str_5fb1ba42e1af06001770fb97_general,
  name='Light Spear General',
  min=2,
  max=1,
  description='Spearmen',
  general=true,
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fb96",
}
g_str_5fb1ba42e1af06001770fb97='5fb1ba42e1af06001770fb97'
g_base_definitions[g_str_5fb1ba42e1af06001770fb97]={
  id=g_str_5fb1ba42e1af06001770fb97,
  name='Light Spear',
  min=2,
  max=5,
  description='Spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fb96",
}
g_str_5fb1ba42e1af06001770fb99='5fb1ba42e1af06001770fb99'
g_base_definitions[g_str_5fb1ba42e1af06001770fb99]={
  id=g_str_5fb1ba42e1af06001770fb99,
  name='Bow Levy',
  min=9,
  max=18,
  description='Formed bowmen, skirmishing bowmen, or skirmishing slingers',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba42e1af06001770fb98",
}
g_str_5fb1ba42e1af06001770fb9a='5fb1ba42e1af06001770fb9a'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9a]={
  id=g_str_5fb1ba42e1af06001770fb9a,
  name='Skirmishers',
  min=9,
  max=18,
  description='Formed bowmen, skirmishing bowmen, or skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba42e1af06001770fb98",
}
g_str_5fb1ba42e1af06001770fb9c_general='5fb1ba42e1af06001770fb9c_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9c_general]={
  id=g_str_5fb1ba42e1af06001770fb9c_general,
  name='Archers General',
  min=0,
  max=1,
  description='Superior bowmen with shields',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba42e1af06001770fb9b",
}
g_str_5fb1ba42e1af06001770fb9c='5fb1ba42e1af06001770fb9c'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9c]={
  id=g_str_5fb1ba42e1af06001770fb9c,
  name='Archers',
  min=0,
  max=2,
  description='Superior bowmen with shields',
  troop_type="Archers",
  troop_option_id="5fb1ba42e1af06001770fb9b",
}
g_str_5fb1b9f4e1af06001770a313_camp='5fb1b9f4e1af06001770a313_camp'
g_base_definitions[g_str_5fb1b9f4e1af06001770a313_camp]={
  id=g_str_5fb1b9f4e1af06001770a313_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba42e1af06001770fb95_general='5fb1ba42e1af06001770fb95_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb95_general]={
  id=g_str_5fb1ba42e1af06001770fb95_general,
  name='Heavy Foot General',
  min=2,
  max=1,
  description='Dagger-axe men',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba42e1af06001770fb94",
}
g_str_5fb1ba42e1af06001770fb95='5fb1ba42e1af06001770fb95'
g_base_definitions[g_str_5fb1ba42e1af06001770fb95]={
  id=g_str_5fb1ba42e1af06001770fb95,
  name='Heavy Foot',
  min=2,
  max=5,
  description='Dagger-axe men',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba42e1af06001770fb94",
}
g_str_5fb1ba42e1af06001770fb97_general='5fb1ba42e1af06001770fb97_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb97_general]={
  id=g_str_5fb1ba42e1af06001770fb97_general,
  name='Light Spear General',
  min=2,
  max=1,
  description='Spearmen',
  general=true,
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fb96",
}
g_str_5fb1ba42e1af06001770fb97='5fb1ba42e1af06001770fb97'
g_base_definitions[g_str_5fb1ba42e1af06001770fb97]={
  id=g_str_5fb1ba42e1af06001770fb97,
  name='Light Spear',
  min=2,
  max=5,
  description='Spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fb96",
}
g_str_5fb1ba42e1af06001770fb99='5fb1ba42e1af06001770fb99'
g_base_definitions[g_str_5fb1ba42e1af06001770fb99]={
  id=g_str_5fb1ba42e1af06001770fb99,
  name='Bow Levy',
  min=9,
  max=18,
  description='Formed bowmen, skirmishing bowmen, or skirmishing slingers',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba42e1af06001770fb98",
}
g_str_5fb1ba42e1af06001770fb9a='5fb1ba42e1af06001770fb9a'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9a]={
  id=g_str_5fb1ba42e1af06001770fb9a,
  name='Skirmishers',
  min=9,
  max=18,
  description='Formed bowmen, skirmishing bowmen, or skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba42e1af06001770fb98",
}
g_str_5fb1ba42e1af06001770fb9c_general='5fb1ba42e1af06001770fb9c_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9c_general]={
  id=g_str_5fb1ba42e1af06001770fb9c_general,
  name='Archers General',
  min=0,
  max=1,
  description='Superior bowmen with shields',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba42e1af06001770fb9b",
}
g_str_5fb1ba42e1af06001770fb9c='5fb1ba42e1af06001770fb9c'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9c]={
  id=g_str_5fb1ba42e1af06001770fb9c,
  name='Archers',
  min=0,
  max=2,
  description='Superior bowmen with shields',
  troop_type="Archers",
  troop_option_id="5fb1ba42e1af06001770fb9b",
}
g_str_5fb1b9f4e1af06001770a313_camp='5fb1b9f4e1af06001770a313_camp'
g_base_definitions[g_str_5fb1b9f4e1af06001770a313_camp]={
  id=g_str_5fb1b9f4e1af06001770a313_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba42e1af06001770fb95_general='5fb1ba42e1af06001770fb95_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb95_general]={
  id=g_str_5fb1ba42e1af06001770fb95_general,
  name='Heavy Foot General',
  min=2,
  max=1,
  description='Dagger-axe men',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba42e1af06001770fb94",
}
g_str_5fb1ba42e1af06001770fb95='5fb1ba42e1af06001770fb95'
g_base_definitions[g_str_5fb1ba42e1af06001770fb95]={
  id=g_str_5fb1ba42e1af06001770fb95,
  name='Heavy Foot',
  min=2,
  max=5,
  description='Dagger-axe men',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba42e1af06001770fb94",
}
g_str_5fb1ba42e1af06001770fb97_general='5fb1ba42e1af06001770fb97_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb97_general]={
  id=g_str_5fb1ba42e1af06001770fb97_general,
  name='Light Spear General',
  min=2,
  max=1,
  description='Spearmen',
  general=true,
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fb96",
}
g_str_5fb1ba42e1af06001770fb97='5fb1ba42e1af06001770fb97'
g_base_definitions[g_str_5fb1ba42e1af06001770fb97]={
  id=g_str_5fb1ba42e1af06001770fb97,
  name='Light Spear',
  min=2,
  max=5,
  description='Spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba42e1af06001770fb96",
}
g_str_5fb1ba42e1af06001770fb99='5fb1ba42e1af06001770fb99'
g_base_definitions[g_str_5fb1ba42e1af06001770fb99]={
  id=g_str_5fb1ba42e1af06001770fb99,
  name='Bow Levy',
  min=9,
  max=18,
  description='Formed bowmen, skirmishing bowmen, or skirmishing slingers',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba42e1af06001770fb98",
}
g_str_5fb1ba42e1af06001770fb9a='5fb1ba42e1af06001770fb9a'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9a]={
  id=g_str_5fb1ba42e1af06001770fb9a,
  name='Skirmishers',
  min=9,
  max=18,
  description='Formed bowmen, skirmishing bowmen, or skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba42e1af06001770fb98",
}
g_str_5fb1ba42e1af06001770fb9c_general='5fb1ba42e1af06001770fb9c_general'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9c_general]={
  id=g_str_5fb1ba42e1af06001770fb9c_general,
  name='Archers General',
  min=0,
  max=1,
  description='Superior bowmen with shields',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba42e1af06001770fb9b",
}
g_str_5fb1ba42e1af06001770fb9c='5fb1ba42e1af06001770fb9c'
g_base_definitions[g_str_5fb1ba42e1af06001770fb9c]={
  id=g_str_5fb1ba42e1af06001770fb9c,
  name='Archers',
  min=0,
  max=2,
  description='Superior bowmen with shields',
  troop_type="Archers",
  troop_option_id="5fb1ba42e1af06001770fb9b",
}
g_str_5fb1b9f4e1af06001770a313_camp='5fb1b9f4e1af06001770a313_camp'
g_base_definitions[g_str_5fb1b9f4e1af06001770a313_camp]={
  id=g_str_5fb1b9f4e1af06001770a313_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
