g_str_5fb1ba3fe1af06001770f6d6_general='5fb1ba3fe1af06001770f6d6_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6d6_general]={
  id=g_str_5fb1ba3fe1af06001770f6d6_general,
  name='Elephants General',
  min=0,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
  troop_option_id="5fb1ba3fe1af06001770f6d4",
}
g_str_5fb1ba3fe1af06001770f6d6='5fb1ba3fe1af06001770f6d6'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6d6]={
  id=g_str_5fb1ba3fe1af06001770f6d6,
  name='Elephants',
  min=0,
  max=1,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba3fe1af06001770f6d4",
}
g_str_5fb1ba3fe1af06001770f6d8_general='5fb1ba3fe1af06001770f6d8_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6d8_general]={
  id=g_str_5fb1ba3fe1af06001770f6d8_general,
  name='Knights General',
  min=0,
  max=1,
  description='Nobles',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba3fe1af06001770f6d7",
}
g_str_5fb1ba3fe1af06001770f6d8='5fb1ba3fe1af06001770f6d8'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6d8]={
  id=g_str_5fb1ba3fe1af06001770f6d8,
  name='Knights',
  min=0,
  max=1,
  description='Nobles',
  troop_type="Knights",
  troop_option_id="5fb1ba3fe1af06001770f6d7",
}
g_str_5fb1ba3fe1af06001770f6da_general='5fb1ba3fe1af06001770f6da_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6da_general]={
  id=g_str_5fb1ba3fe1af06001770f6da_general,
  name='Heavy Foot General',
  min=1,
  max=1,
  description='Chinese-style close-fighting foot',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3fe1af06001770f6d9",
}
g_str_5fb1ba3fe1af06001770f6da='5fb1ba3fe1af06001770f6da'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6da]={
  id=g_str_5fb1ba3fe1af06001770f6da,
  name='Heavy Foot',
  min=1,
  max=4,
  description='Chinese-style close-fighting foot',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3fe1af06001770f6d9",
}
g_str_5fb1ba3fe1af06001770f6dd='5fb1ba3fe1af06001770f6dd'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6dd]={
  id=g_str_5fb1ba3fe1af06001770f6dd,
  name='Bow Levy',
  min=2,
  max=5,
  description='Chinese-style bowmen and crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3fe1af06001770f6dc",
}
g_str_5fb1ba3fe1af06001770f6e0='5fb1ba3fe1af06001770f6e0'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6e0]={
  id=g_str_5fb1ba3fe1af06001770f6e0,
  name='Warband',
  min=4,
  max=12,
  description='Fierce infantry armed with spear and boot-shaped axe',
  troop_type="Warband",
  troop_option_id="5fb1ba3fe1af06001770f6df",
}
g_str_5fb1ba3fe1af06001770f6e2='5fb1ba3fe1af06001770f6e2'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6e2]={
  id=g_str_5fb1ba3fe1af06001770f6e2,
  name='Bow Levy',
  min=2,
  max=8,
  description='Bowmen and crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3fe1af06001770f6e1",
}
g_str_5fb1ba3fe1af06001770f6e4='5fb1ba3fe1af06001770f6e4'
g_base_definitions[g_str_5fb1ba3fe1af06001770f6e4]={
  id=g_str_5fb1ba3fe1af06001770f6e4,
  name='Rabble',
  min=0,
  max=4,
  description='Unshielded spearmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba3fe1af06001770f6e3",
}
g_str_5fb1b9f1e1af06001770a1e6_camp='5fb1b9f1e1af06001770a1e6_camp'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1e6_camp]={
  id=g_str_5fb1b9f1e1af06001770a1e6_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
