-- 5fb1b9dfe1af06001770975f Later Pre-Islamic Arab Nomad  312 BC to 633 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ae1af06001770cfbb='5fb1ba2ae1af06001770cfbb'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfbb]={
  id=g_str_5fb1ba2ae1af06001770cfbb,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen, some with personal armor',
}
g_str_5fb1ba2ae1af06001770cfbb='5fb1ba2ae1af06001770cfbb'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfbb]={
  id=g_str_5fb1ba2ae1af06001770cfbb,
  name='Javelin Cavalry',
  min=1,
  max=4,
  description='Horsemen, some with personal armor',
}
g_str_5fb1ba2ae1af06001770cfbd='5fb1ba2ae1af06001770cfbd'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfbd]={
  id=g_str_5fb1ba2ae1af06001770cfbd,
  name='Bad Horse',
  min=1,
  max=6,
  description='Camel-mounted scouts, or camel-mounted swordsmen',
}
g_str_5fb1ba2ae1af06001770cfc0='5fb1ba2ae1af06001770cfc0'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfc0]={
  id=g_str_5fb1ba2ae1af06001770cfc0,
  name='Heavy Foot',
  min=4,
  max=11,
  description='Swordsmen',
}
g_str_5fb1ba2ae1af06001770cfc2='5fb1ba2ae1af06001770cfc2'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfc2]={
  id=g_str_5fb1ba2ae1af06001770cfc2,
  name='Archers',
  min=1,
  max=4,
  description='Bowmen',
}
g_str_5fb1ba2ae1af06001770cfc3='5fb1ba2ae1af06001770cfc3'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfc3]={
  id=g_str_5fb1ba2ae1af06001770cfc3,
  name='Bow Levy',
  min=1,
  max=4,
  description='Bowmen',
}
g_str_5fb1ba2ae1af06001770cfc5='5fb1ba2ae1af06001770cfc5'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfc5]={
  id=g_str_5fb1ba2ae1af06001770cfc5,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
}
g_str_5fb1ba2ae1af06001770cfc7='5fb1ba2ae1af06001770cfc7'
g_base_definitions[g_str_5fb1ba2ae1af06001770cfc7]={
  id=g_str_5fb1ba2ae1af06001770cfc7,
  name='Light Foot',
  min=0,
  max=5,
  description='Mercenary javelinmen',
}
g_str_5fb1b9dfe1af06001770975f_camp='5fb1b9dfe1af06001770975f_camp'
g_base_definitions[g_str_5fb1b9dfe1af06001770975f_camp]={
  name='Camp',
  id=g_str_5fb1b9dfe1af06001770975f_camp,
  min=1,
  max=1,
}
army['5fb1b9dfe1af06001770975f']={
  data={
    name='Later Pre-Islamic Arab Nomad  312 BC to 633 AD'
  },
  g_base_definitions[g_str_5fb1b9dfe1af06001770975f_camp],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfc9],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfbb],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfbb],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfbd],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfc0],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfc2],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfc3],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfc5],
  g_base_definitions[g_str_5fb1ba2ae1af06001770cfc7],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770975f"] = army["5fb1b9dfe1af06001770975f"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Pre-Islamic Arab Nomad  312 BC to 633 AD"] = army["5fb1b9dfe1af06001770975f"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Pre-Islamic Arab Nomad  312 BC to 633 AD"] = army["5fb1b9dfe1af06001770975f"]
