-- 5fb1b9efe1af06001770a06e Sogdians  500 to 730 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba3ce1af06001770f202']= {
  min=3,
  max=7,
  description='Chakar',
}
g_troop_entry['5fb1ba3ce1af06001770f203']= {
  troop_option='5fb1ba3ce1af06001770f202',
  troopTypeCode='KNT',
}
g_troop_option['5fb1ba3ce1af06001770f204']= {
  min=0,
  max=2,
  description='Dihqan armored horsemen',
}
g_troop_entry['5fb1ba3ce1af06001770f205']= {
  troop_option='5fb1ba3ce1af06001770f204',
  troopTypeCode='ECV',
}
g_troop_entry['5fb1ba3ce1af06001770f206']= {
  troop_option='5fb1ba3ce1af06001770f204',
  troopTypeCode='HBW',
}
g_troop_option['5fb1ba3ce1af06001770f207']= {
  min=1,
  max=2,
  description='Scout or local nomad horse archers',
}
g_troop_entry['5fb1ba3ce1af06001770f208']= {
  troop_option='5fb1ba3ce1af06001770f207',
  troopTypeCode='HBW',
}
g_troop_option['5fb1ba3ce1af06001770f209']= {
  min=0,
  max=1,
  description='Exiled Persian noble horsemen',
  startDate=650,
  endDate=730,
}
g_troop_entry['5fb1ba3ce1af06001770f20b']= {
  troop_option='5fb1ba3ce1af06001770f209',
  troopTypeCode='ECV',
}
g_troop_entry['5fb1ba3ce1af06001770f20c']= {
  troop_option='5fb1ba3ce1af06001770f209',
  troopTypeCode='HBW',
}
g_troop_option['5fb1ba3ce1af06001770f20d']= {
  min=2,
  max=4,
  description='Bowmen',
  core='all',
}
g_troop_entry['5fb1ba3ce1af06001770f20e']= {
  troop_option='5fb1ba3ce1af06001770f20d',
  troopTypeCode='ARC',
}
g_troop_entry['5fb1ba3ce1af06001770f20f']= {
  troop_option='5fb1ba3ce1af06001770f20d',
  troopTypeCode='BLV',
}
g_troop_option['5fb1ba3ce1af06001770f210']= {
  min=0,
  max=2,
  description='Levy spearmen',
  core='all',
}
g_troop_entry['5fb1ba3ce1af06001770f211']= {
  troop_option='5fb1ba3ce1af06001770f210',
  troopTypeCode='HRD',
}
g_str_5fb1ba3ce1af06001770f203_general='5fb1ba3ce1af06001770f203_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f203_general]={
  id=g_str_5fb1ba3ce1af06001770f203_general,
  name='Knights General',
  min=3,
  max=1,
  description='Chakar',
  general=true,
  troop_type="Knights",
}
g_str_5fb1ba3ce1af06001770f203='5fb1ba3ce1af06001770f203'
g_base_definitions[g_str_5fb1ba3ce1af06001770f203]={
  id=g_str_5fb1ba3ce1af06001770f203,
  name='Knights',
  min=3,
  max=7,
  description='Chakar',
  troop_type="Knights",
}
g_str_5fb1ba3ce1af06001770f205='5fb1ba3ce1af06001770f205'
g_base_definitions[g_str_5fb1ba3ce1af06001770f205]={
  id=g_str_5fb1ba3ce1af06001770f205,
  name='Elite Cavalary',
  min=0,
  max=2,
  description='Dihqan armored horsemen',
  troop_type="Elite Cavalary",
}
g_str_5fb1ba3ce1af06001770f206='5fb1ba3ce1af06001770f206'
g_base_definitions[g_str_5fb1ba3ce1af06001770f206]={
  id=g_str_5fb1ba3ce1af06001770f206,
  name='Horse Bow',
  min=0,
  max=2,
  description='Dihqan armored horsemen',
  troop_type="Horse Bow",
}
g_str_5fb1ba3ce1af06001770f208='5fb1ba3ce1af06001770f208'
g_base_definitions[g_str_5fb1ba3ce1af06001770f208]={
  id=g_str_5fb1ba3ce1af06001770f208,
  name='Horse Bow',
  min=1,
  max=2,
  description='Scout or local nomad horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba3ce1af06001770f20b='5fb1ba3ce1af06001770f20b'
g_base_definitions[g_str_5fb1ba3ce1af06001770f20b]={
  id=g_str_5fb1ba3ce1af06001770f20b,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Exiled Persian noble horsemen',
  troop_type="Elite Cavalary",
}
g_str_5fb1ba3ce1af06001770f20c='5fb1ba3ce1af06001770f20c'
g_base_definitions[g_str_5fb1ba3ce1af06001770f20c]={
  id=g_str_5fb1ba3ce1af06001770f20c,
  name='Horse Bow',
  min=0,
  max=1,
  description='Exiled Persian noble horsemen',
  troop_type="Horse Bow",
}
g_str_5fb1ba3ce1af06001770f20e='5fb1ba3ce1af06001770f20e'
g_base_definitions[g_str_5fb1ba3ce1af06001770f20e]={
  id=g_str_5fb1ba3ce1af06001770f20e,
  name='Archers',
  min=2,
  max=4,
  description='Bowmen',
  troop_type="Archers",
}
g_str_5fb1ba3ce1af06001770f20f='5fb1ba3ce1af06001770f20f'
g_base_definitions[g_str_5fb1ba3ce1af06001770f20f]={
  id=g_str_5fb1ba3ce1af06001770f20f,
  name='Bow Levy',
  min=2,
  max=4,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba3ce1af06001770f211='5fb1ba3ce1af06001770f211'
g_base_definitions[g_str_5fb1ba3ce1af06001770f211]={
  id=g_str_5fb1ba3ce1af06001770f211,
  name='Horde',
  min=0,
  max=2,
  description='Levy spearmen',
  troop_type="Horde",
}
g_str_5fb1b9efe1af06001770a06e_camp='5fb1b9efe1af06001770a06e_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp]={
  id=g_str_5fb1b9efe1af06001770a06e_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9efe1af06001770a06e_camp_pack_train='5fb1b9efe1af06001770a06e_camp_pack_train'
g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp_pack_train]={
  id=g_str_5fb1b9efe1af06001770a06e_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9efe1af06001770a06e']={
  data={
    name='Sogdians  500 to 730 AD',
    id='5fb1b9efe1af06001770a06e',
    army_id='5fb1b9efe1af06001770a06e'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f205],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f206],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f208],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20b],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f211],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a06e"] = army["5fb1b9efe1af06001770a06e"]
army['5fb1b9efe1af06001770a06e_500_649']={
  data={
    name='Sogdians 500 AD to 649 AD',
    id='5fb1b9efe1af06001770a06e_500_649',
    army_id='5fb1b9efe1af06001770a06e'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f205],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f206],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f208],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20b],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f211],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp_pack_train],
}
army['5fb1b9efe1af06001770a06e_650_730']={
  data={
    name='Sogdians 650 AD to 730 AD',
    id='5fb1b9efe1af06001770a06e_650_730',
    army_id='5fb1b9efe1af06001770a06e'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f203],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f205],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f206],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f208],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20b],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20e],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f20f],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f211],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a06e_camp_pack_train],
}
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Sogdians  500 to 730 AD"] = army["5fb1b9efe1af06001770a06e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sogdians  500 to 730 AD"] = army["5fb1b9efe1af06001770a06e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a06e"] = {}
army_dates["5fb1b9efe1af06001770a06e"]["500 AD to 730 AD"] ="5fb1b9efe1af06001770a06e"
army_dates["5fb1b9efe1af06001770a06e"]["500 AD to 649 AD"] ="5fb1b9efe1af06001770a06e_500_649"
army_dates["5fb1b9efe1af06001770a06e"]["650 AD to 730 AD"] ="5fb1b9efe1af06001770a06e_650_730"
