troop_options['5fb1ba32e1af06001770de89'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1054,
    endDate=1152,
  }
}
troop_options['5fb1ba32e1af06001770de8b'] = {
  min=3,
  max=9,
  dateRange={
    startDate=1054,
    endDate=1152,
  }
}
troop_options['5fb1ba32e1af06001770de8d'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1054,
    endDate=1152,
  }
}
troop_options['5fb1ba32e1af06001770de8f'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1054,
    endDate=1152,
  }
}
troop_options['5fb1ba32e1af06001770de92'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1054,
    endDate=1152,
  }
}
troop_options['5fb1ba32e1af06001770de94'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1054,
    endDate=1152,
  }
}
-- allies
