troop_options['615351ab03385c0016b8713f'] = {
  min=6,
  max=12,
  dateRange={
    startDate=1357,
    endDate=1410,
  }
}
troop_options['615351ab03385c0016b87142'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1357,
    endDate=1410,
  }
}
troop_options['615351ab03385c0016b87144'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1357,
    endDate=1410,
  }
}
troop_options['615351ab03385c0016b87147'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1357,
    endDate=1410,
  }
}
troop_options['615351ab03385c0016b87149'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1357,
    endDate=1410,
  }
}
-- allies
