-- 5fb1b9d9e1af060017709313 Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba1fe1af06001770bf02_general='5fb1ba1fe1af06001770bf02_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf02_general]={
  id=g_str_5fb1ba1fe1af06001770bf02_general,
  name='Chariots General',
  min=0,
  max=1,
  description='2-horse chariots',
  general=true,
  troop_type="Chariots",
}
g_str_5fb1ba1fe1af06001770bf02='5fb1ba1fe1af06001770bf02'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf02]={
  id=g_str_5fb1ba1fe1af06001770bf02,
  name='Chariots',
  min=0,
  max=1,
  description='2-horse chariots',
  troop_type="Chariots",
}
g_str_5fb1ba1fe1af06001770bf04_general='5fb1ba1fe1af06001770bf04_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf04_general]={
  id=g_str_5fb1ba1fe1af06001770bf04_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Bodyguards',
  general=true,
  troop_type="Raiders",
}
g_str_5fb1ba1fe1af06001770bf04='5fb1ba1fe1af06001770bf04'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf04]={
  id=g_str_5fb1ba1fe1af06001770bf04,
  name='Raiders',
  min=1,
  max=2,
  description='Bodyguards',
  troop_type="Raiders",
}
g_str_5fb1ba1fe1af06001770bf05_general='5fb1ba1fe1af06001770bf05_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf05_general]={
  id=g_str_5fb1ba1fe1af06001770bf05_general,
  name='Archers General',
  min=1,
  max=1,
  description='Bodyguards',
  general=true,
  troop_type="Archers",
}
g_str_5fb1ba1fe1af06001770bf05='5fb1ba1fe1af06001770bf05'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf05]={
  id=g_str_5fb1ba1fe1af06001770bf05,
  name='Archers',
  min=1,
  max=2,
  description='Bodyguards',
  troop_type="Archers",
}
g_str_5fb1ba1fe1af06001770bf07='5fb1ba1fe1af06001770bf07'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf07]={
  id=g_str_5fb1ba1fe1af06001770bf07,
  name='Rabble',
  min=6,
  max=18,
  description='Unshielded javelinmen',
  troop_type="Rabble",
}
g_str_5fb1ba1fe1af06001770bf0a='5fb1ba1fe1af06001770bf0a'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf0a]={
  id=g_str_5fb1ba1fe1af06001770bf0a,
  name='Light Foot',
  min=0,
  max=3,
  description='Javelinmen with shields',
  troop_type="Light Foot",
}
g_str_5fb1ba1fe1af06001770bf0c='5fb1ba1fe1af06001770bf0c'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf0c]={
  id=g_str_5fb1ba1fe1af06001770bf0c,
  name='Bow Levy',
  min=4,
  max=12,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba1fe1af06001770bf0e='5fb1ba1fe1af06001770bf0e'
g_base_definitions[g_str_5fb1ba1fe1af06001770bf0e]={
  id=g_str_5fb1ba1fe1af06001770bf0e,
  name='Skirmishers',
  min=0,
  max=4,
  description='Slingers',
  troop_type="Skirmishers",
}
g_str_5fb1b9d9e1af060017709313_camp='5fb1b9d9e1af060017709313_camp'
g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp]={
  name='Camp',
  id=g_str_5fb1b9d9e1af060017709313_camp,
  min=1,
  max=1,
}
army['5fb1b9d9e1af060017709313']={
  data={
    name='Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC'
  },
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf10],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf11],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf12],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf02],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf04],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf05],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf07],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0a],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0c],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bf0e],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709313"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Early Kassites or Nairi 1649-950 BC, or Hurrians 1779-950 BC  1749 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
