-- 5fb1b9eee1af06001770a014 Trapezuntine Byzantine  1204 to 1461 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3be1af06001770f055_general='5fb1ba3be1af06001770f055_general'
g_base_definitions[g_str_5fb1ba3be1af06001770f055_general]={
  id=g_str_5fb1ba3be1af06001770f055_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Trapezuntine stratiotai lancers',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3be1af06001770f053",
}
g_str_5fb1ba3be1af06001770f055='5fb1ba3be1af06001770f055'
g_base_definitions[g_str_5fb1ba3be1af06001770f055]={
  id=g_str_5fb1ba3be1af06001770f055,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Trapezuntine stratiotai lancers',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3be1af06001770f053",
}
g_str_5fb1ba3be1af06001770f058_general='5fb1ba3be1af06001770f058_general'
g_base_definitions[g_str_5fb1ba3be1af06001770f058_general]={
  id=g_str_5fb1ba3be1af06001770f058_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Trapezuntine stratiotai horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f056",
}
g_str_5fb1ba3be1af06001770f058='5fb1ba3be1af06001770f058'
g_base_definitions[g_str_5fb1ba3be1af06001770f058]={
  id=g_str_5fb1ba3be1af06001770f058,
  name='Horse Bow',
  min=1,
  max=2,
  description='Trapezuntine stratiotai horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f056",
}
g_str_5fb1ba3be1af06001770f05a='5fb1ba3be1af06001770f05a'
g_base_definitions[g_str_5fb1ba3be1af06001770f05a]={
  id=g_str_5fb1ba3be1af06001770f05a,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Trapezuntine or mercenary spearmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3be1af06001770f059",
}
g_str_5fb1ba3be1af06001770f05c='5fb1ba3be1af06001770f05c'
g_base_definitions[g_str_5fb1ba3be1af06001770f05c]={
  id=g_str_5fb1ba3be1af06001770f05c,
  name='Skirmishers',
  min=2,
  max=4,
  description='Trapezuntine bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3be1af06001770f05b",
}
g_str_5fb1ba3be1af06001770f05d='5fb1ba3be1af06001770f05d'
g_base_definitions[g_str_5fb1ba3be1af06001770f05d]={
  id=g_str_5fb1ba3be1af06001770f05d,
  name='Archers',
  min=2,
  max=4,
  description='Trapezuntine bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba3be1af06001770f05b",
}
g_str_5fb1ba3be1af06001770f05f_general='5fb1ba3be1af06001770f05f_general'
g_base_definitions[g_str_5fb1ba3be1af06001770f05f_general]={
  id=g_str_5fb1ba3be1af06001770f05f_general,
  name='Horse Bow General',
  min=2,
  max=1,
  description='Laz or Tzan horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f05e",
}
g_str_5fb1ba3be1af06001770f05f='5fb1ba3be1af06001770f05f'
g_base_definitions[g_str_5fb1ba3be1af06001770f05f]={
  id=g_str_5fb1ba3be1af06001770f05f,
  name='Horse Bow',
  min=2,
  max=4,
  description='Laz or Tzan horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f05e",
}
g_str_5fb1ba3be1af06001770f061='5fb1ba3be1af06001770f061'
g_base_definitions[g_str_5fb1ba3be1af06001770f061]={
  id=g_str_5fb1ba3be1af06001770f061,
  name='Light Foot',
  min=2,
  max=4,
  description='Laz or Tzan tribal close-combat infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3be1af06001770f060",
}
g_str_5fb1ba3be1af06001770f063='5fb1ba3be1af06001770f063'
g_base_definitions[g_str_5fb1ba3be1af06001770f063]={
  id=g_str_5fb1ba3be1af06001770f063,
  name='Bow Levy',
  min=0,
  max=2,
  description='Laz or Tzan tribal bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3be1af06001770f062",
}
g_str_5fb1ba3be1af06001770f065_general='5fb1ba3be1af06001770f065_general'
g_base_definitions[g_str_5fb1ba3be1af06001770f065_general]={
  id=g_str_5fb1ba3be1af06001770f065_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Turk horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f064",
}
g_str_5fb1ba3be1af06001770f065='5fb1ba3be1af06001770f065'
g_base_definitions[g_str_5fb1ba3be1af06001770f065]={
  id=g_str_5fb1ba3be1af06001770f065,
  name='Horse Bow',
  min=0,
  max=2,
  description='Turk horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f064",
}
g_str_5fb1ba3be1af06001770f067_general='5fb1ba3be1af06001770f067_general'
g_base_definitions[g_str_5fb1ba3be1af06001770f067_general]={
  id=g_str_5fb1ba3be1af06001770f067_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Alan horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f066",
}
g_str_5fb1ba3be1af06001770f067='5fb1ba3be1af06001770f067'
g_base_definitions[g_str_5fb1ba3be1af06001770f067]={
  id=g_str_5fb1ba3be1af06001770f067,
  name='Horse Bow',
  min=0,
  max=2,
  description='Alan horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3be1af06001770f066",
}
g_str_5fb1b9eee1af06001770a014_camp='5fb1b9eee1af06001770a014_camp'
g_base_definitions[g_str_5fb1b9eee1af06001770a014_camp]={
  id=g_str_5fb1b9eee1af06001770a014_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9eee1af06001770a014']={
  data={
    name='Trapezuntine Byzantine  1204 to 1461 AD',
    id='5fb1b9eee1af06001770a014',
    army_id='5fb1b9eee1af06001770a014'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770f055_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f055],
  g_base_definitions[g_str_5fb1ba3be1af06001770f058_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f058],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05a],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05c],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05d],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05f_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05f],
  g_base_definitions[g_str_5fb1ba3be1af06001770f061],
  g_base_definitions[g_str_5fb1ba3be1af06001770f063],
  g_base_definitions[g_str_5fb1ba3be1af06001770f065_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f065],
  g_base_definitions[g_str_5fb1ba3be1af06001770f067_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f067],
  g_base_definitions[g_str_5fb1b9eee1af06001770a014_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af06001770a014"] = army["5fb1b9eee1af06001770a014"]
army['5fb1b9eee1af06001770a014_1204_1360']={
  data={
    name='Trapezuntine Byzantine 1204 AD to 1360 AD',
    id='5fb1b9eee1af06001770a014_1204_1360',
    army_id='5fb1b9eee1af06001770a014'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770f055_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f055],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05a],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05c],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05d],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05f_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05f],
  g_base_definitions[g_str_5fb1ba3be1af06001770f061],
  g_base_definitions[g_str_5fb1ba3be1af06001770f063],
  g_base_definitions[g_str_5fb1ba3be1af06001770f065_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f065],
  g_base_definitions[g_str_5fb1ba3be1af06001770f067_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f067],
  g_base_definitions[g_str_5fb1b9eee1af06001770a014_camp],
}
army['5fb1b9eee1af06001770a014_1361_1461']={
  data={
    name='Trapezuntine Byzantine 1361 AD to 1461 AD',
    id='5fb1b9eee1af06001770a014_1361_1461',
    army_id='5fb1b9eee1af06001770a014'
  },
  g_base_definitions[g_str_5fb1ba3be1af06001770f058_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f058],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05a],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05c],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05d],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05f_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f05f],
  g_base_definitions[g_str_5fb1ba3be1af06001770f061],
  g_base_definitions[g_str_5fb1ba3be1af06001770f063],
  g_base_definitions[g_str_5fb1ba3be1af06001770f065_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f065],
  g_base_definitions[g_str_5fb1ba3be1af06001770f067_general],
  g_base_definitions[g_str_5fb1ba3be1af06001770f067],
  g_base_definitions[g_str_5fb1b9eee1af06001770a014_camp],
}
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Trapezuntine Byzantine  1204 to 1461 AD"] = army["5fb1b9eee1af06001770a014"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Trapezuntine Byzantine  1204 to 1461 AD"] = army["5fb1b9eee1af06001770a014"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Trapezuntine Byzantine  1204 to 1461 AD"] = army["5fb1b9eee1af06001770a014"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Trapezuntine Byzantine  1204 to 1461 AD"] = army["5fb1b9eee1af06001770a014"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af06001770a014"] = {}
army_dates["5fb1b9eee1af06001770a014"]["1204 AD to 1461 AD"] ="5fb1b9eee1af06001770a014"
army_dates["5fb1b9eee1af06001770a014"]["1204 AD to 1360 AD"] ="5fb1b9eee1af06001770a014_1204_1360"
army_dates["5fb1b9eee1af06001770a014"]["1361 AD to 1461 AD"] ="5fb1b9eee1af06001770a014_1361_1461"
