g_str_5fb1ba2ae1af06001770cf75_general='5fb1ba2ae1af06001770cf75_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf75_general]={
  id=g_str_5fb1ba2ae1af06001770cf75_general,
  name='Javelin Cavalry General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2ae1af06001770cf74",
}
g_str_5fb1ba2ae1af06001770cf75='5fb1ba2ae1af06001770cf75'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf75]={
  id=g_str_5fb1ba2ae1af06001770cf75,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2ae1af06001770cf74",
}
g_str_5fb1ba2ae1af06001770cf76_general='5fb1ba2ae1af06001770cf76_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf76_general]={
  id=g_str_5fb1ba2ae1af06001770cf76_general,
  name='Cataphracts General',
  min=0,
  max=1,
  description='Horsemen',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2ae1af06001770cf74",
}
g_str_5fb1ba2ae1af06001770cf76='5fb1ba2ae1af06001770cf76'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf76]={
  id=g_str_5fb1ba2ae1af06001770cf76,
  name='Cataphracts',
  min=0,
  max=1,
  description='Horsemen',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2ae1af06001770cf74",
}
g_str_5fb1ba2ae1af06001770cf78_general='5fb1ba2ae1af06001770cf78_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf78_general]={
  id=g_str_5fb1ba2ae1af06001770cf78_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2ae1af06001770cf77",
}
g_str_5fb1ba2ae1af06001770cf78='5fb1ba2ae1af06001770cf78'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf78]={
  id=g_str_5fb1ba2ae1af06001770cf78,
  name='Horse Bow',
  min=1,
  max=4,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba2ae1af06001770cf77",
}
g_str_5fb1ba2ae1af06001770cf7a='5fb1ba2ae1af06001770cf7a'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf7a]={
  id=g_str_5fb1ba2ae1af06001770cf7a,
  name='Bad Horse',
  min=0,
  max=1,
  description='Scouts on camels',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba2ae1af06001770cf79",
}
g_str_5fb1ba2ae1af06001770cf7a_light_camelry='5fb1ba2ae1af06001770cf7a_light_camelry'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf7a_light_camelry]={
  id=g_str_5fb1ba2ae1af06001770cf7a_light_camelry,
  name='Bad Horse',
  min=0,
  max=1,
  description='Scouts on camels\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba2ae1af06001770cf79",
}
g_str_5fb1ba2ae1af06001770cf7d='5fb1ba2ae1af06001770cf7d'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf7d]={
  id=g_str_5fb1ba2ae1af06001770cf7d,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Swordsmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2ae1af06001770cf7c",
}
g_str_5fb1ba2ae1af06001770cf7f='5fb1ba2ae1af06001770cf7f'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf7f]={
  id=g_str_5fb1ba2ae1af06001770cf7f,
  name='Light Foot',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2ae1af06001770cf7e",
}
g_str_5fb1ba2ae1af06001770cf81='5fb1ba2ae1af06001770cf81'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf81]={
  id=g_str_5fb1ba2ae1af06001770cf81,
  name='Archers',
  min=5,
  max=16,
  description='Bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba2ae1af06001770cf80",
}
g_str_5fb1ba2ae1af06001770cf82='5fb1ba2ae1af06001770cf82'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf82]={
  id=g_str_5fb1ba2ae1af06001770cf82,
  name='Bow Levy',
  min=5,
  max=16,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba2ae1af06001770cf80",
}
g_str_5fb1ba2ae1af06001770cf84='5fb1ba2ae1af06001770cf84'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf84]={
  id=g_str_5fb1ba2ae1af06001770cf84,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2ae1af06001770cf83",
}
g_str_5fb1ba2ae1af06001770cf87_general='5fb1ba2ae1af06001770cf87_general'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf87_general]={
  id=g_str_5fb1ba2ae1af06001770cf87_general,
  name='Cataphracts General',
  min=0,
  max=1,
  description='Fully armored camels and riders',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2ae1af06001770cf85",
}
g_str_5fb1ba2ae1af06001770cf87_general_armored_camelry='5fb1ba2ae1af06001770cf87_general_armored_camelry'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf87_general_armored_camelry]={
  id=g_str_5fb1ba2ae1af06001770cf87_general_armored_camelry,
  name='Cataphracts General',
  min=0,
  max=1,
  description='Fully armored camels and riders\nArmored Camelry',
  general=true,
  armored_camelry=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2ae1af06001770cf85",
}
g_str_5fb1ba2ae1af06001770cf87='5fb1ba2ae1af06001770cf87'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf87]={
  id=g_str_5fb1ba2ae1af06001770cf87,
  name='Cataphracts',
  min=0,
  max=1,
  description='Fully armored camels and riders',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2ae1af06001770cf85",
}
g_str_5fb1ba2ae1af06001770cf87_armored_camelry='5fb1ba2ae1af06001770cf87_armored_camelry'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf87_armored_camelry]={
  id=g_str_5fb1ba2ae1af06001770cf87_armored_camelry,
  name='Cataphracts',
  min=0,
  max=1,
  description='Fully armored camels and riders\nArmored Camelry',
  armored_camelry=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba2ae1af06001770cf85",
}
g_str_5fb1ba2ae1af06001770cf8b='5fb1ba2ae1af06001770cf8b'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf8b]={
  id=g_str_5fb1ba2ae1af06001770cf8b,
  name='Artillery',
  min=0,
  max=1,
  description='Stone-throwers',
  troop_type="Artillery",
  troop_option_id="5fb1ba2ae1af06001770cf89",
}
g_str_5fb1ba2ae1af06001770cf8e='5fb1ba2ae1af06001770cf8e'
g_base_definitions[g_str_5fb1ba2ae1af06001770cf8e]={
  id=g_str_5fb1ba2ae1af06001770cf8e,
  name='Raiders',
  min=0,
  max=1,
  description='Roman auxiliaries',
  troop_type="Raiders",
  troop_option_id="5fb1ba2ae1af06001770cf8c",
}
g_str_5fb1b9dfe1af060017709752_camp='5fb1b9dfe1af060017709752_camp'
g_base_definitions[g_str_5fb1b9dfe1af060017709752_camp]={
  id=g_str_5fb1b9dfe1af060017709752_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dfe1af060017709752_camp_pack_train='5fb1b9dfe1af060017709752_camp_pack_train'
g_base_definitions[g_str_5fb1b9dfe1af060017709752_camp_pack_train]={
  id=g_str_5fb1b9dfe1af060017709752_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
