-- 5fb1b9efe1af06001770a044 Islamic Persian  1245 to 1393 AD

army['5fb1b9efe1af06001770a044']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
      'Dry',
    },
    name='Islamic Persian  1245 to 1393 AD',
    id='5fb1b9efe1af06001770a044',
    dateRange={
      startDate=1245,
      endDate=1393,
    },
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f11d_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f11d_general_shower_shooting],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f11d],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f11d_shower_shooting],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f120_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f120],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f122_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f122],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f124],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f127],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f129],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f12c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f12d],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f130],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f133],
  g_base_definitions[g_str_5fb1b9efe1af06001770a044_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a044_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a044"] = army["5fb1b9efe1af06001770a044"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Islamic Persian  1245 to 1393 AD"] = army["5fb1b9efe1af06001770a044"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Islamic Persian  1245 to 1393 AD"] = army["5fb1b9efe1af06001770a044"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a044"] = {}
army_dates["5fb1b9efe1af06001770a044"]["1245 AD to 1393 AD"] = {
  startDate=1245,
  endDate=1393
}
army_dates["5fb1b9efe1af06001770a044"]["1245 AD to 1302 AD"] = {
  startDate=1245,
  endDate=1302
}
army_dates["5fb1b9efe1af06001770a044"]["1303 AD to 1336 AD"] = {
  startDate=1303,
  endDate=1336
}
army_dates["5fb1b9efe1af06001770a044"]["1337 AD to 1381 AD"] = {
  startDate=1337,
  endDate=1381
}
army_dates["5fb1b9efe1af06001770a044"]["1382 AD to 1389 AD"] = {
  startDate=1382,
  endDate=1389
}
army_dates["5fb1b9efe1af06001770a044"]["1390 AD to 1393 AD"] = {
  startDate=1390,
  endDate=1393
}
