-- 5fb1b9f6e1af06001770a484 Vilcabamba Neo-Inca Empire  1535 to 1572 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba44e1af06001770fe9a_general='5fb1ba44e1af06001770fe9a_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fe9a_general]={
  id=g_str_5fb1ba44e1af06001770fe9a_general,
  name='Light Foot General',
  min=2,
  max=1,
  description='Inca Huaminca regulars',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba44e1af06001770fe99",
}
g_str_5fb1ba44e1af06001770fe9a='5fb1ba44e1af06001770fe9a'
g_base_definitions[g_str_5fb1ba44e1af06001770fe9a]={
  id=g_str_5fb1ba44e1af06001770fe9a,
  name='Light Foot',
  min=2,
  max=6,
  description='Inca Huaminca regulars',
  troop_type="Light Foot",
  troop_option_id="5fb1ba44e1af06001770fe99",
}
g_str_5fb1ba44e1af06001770fe9c='5fb1ba44e1af06001770fe9c'
g_base_definitions[g_str_5fb1ba44e1af06001770fe9c]={
  id=g_str_5fb1ba44e1af06001770fe9c,
  name='Skirmishers',
  min=2,
  max=6,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770fe9b",
}
g_str_5fb1ba44e1af06001770fe9e='5fb1ba44e1af06001770fe9e'
g_base_definitions[g_str_5fb1ba44e1af06001770fe9e]={
  id=g_str_5fb1ba44e1af06001770fe9e,
  name='Rabble',
  min=4,
  max=12,
  description='Ineffective foot',
  troop_type="Rabble",
  troop_option_id="5fb1ba44e1af06001770fe9d",
}
g_str_5fb1ba44e1af06001770fea0='5fb1ba44e1af06001770fea0'
g_base_definitions[g_str_5fb1ba44e1af06001770fea0]={
  id=g_str_5fb1ba44e1af06001770fea0,
  name='Bow Levy',
  min=0,
  max=8,
  description='Anti tribal bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba44e1af06001770fe9f",
}
g_str_5fb1b9f6e1af06001770a484_camp='5fb1b9f6e1af06001770a484_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a484_camp]={
  id=g_str_5fb1b9f6e1af06001770a484_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f6e1af06001770a484_camp_pack_train='5fb1b9f6e1af06001770a484_camp_pack_train'
g_base_definitions[g_str_5fb1b9f6e1af06001770a484_camp_pack_train]={
  id=g_str_5fb1b9f6e1af06001770a484_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9f6e1af06001770a484']={
  data={
    name='Vilcabamba Neo-Inca Empire  1535 to 1572 AD',
    id='5fb1b9f6e1af06001770a484'
  },
  g_base_definitions[g_str_5fb1ba44e1af06001770fe9a_general],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe9a],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe9c],
  g_base_definitions[g_str_5fb1ba44e1af06001770fe9e],
  g_base_definitions[g_str_5fb1ba44e1af06001770fea0],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a484_camp],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a484_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a484"] = army["5fb1b9f6e1af06001770a484"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Vilcabamba Neo-Inca Empire  1535 to 1572 AD"] = army["5fb1b9f6e1af06001770a484"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Vilcabamba Neo-Inca Empire  1535 to 1572 AD"] = army["5fb1b9f6e1af06001770a484"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a484"] = {}
army_dates["5fb1b9f6e1af06001770a484"]["1535 AD to 1572 AD"] ="5fb1b9f6e1af06001770a484"
