-- 5fb1b9f3e1af06001770a29a Mongol Conquest  1206 to 1266 AD

army['5fb1b9f3e1af06001770a29a']={
  data={
    name='Mongol Conquest  1206 to 1266 AD',
    id='5fb1b9f3e1af06001770a29a',
    dateRange={
      startDate=1206,
      endDate=1266,
    }
  },
  g_base_definitions[g_str_5fb1ba40e1af06001770f979_general],
  g_base_definitions[g_str_5fb1ba40e1af06001770f979_general_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f979_general_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f979],
  g_base_definitions[g_str_5fb1ba40e1af06001770f979_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f979_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f97c_general],
  g_base_definitions[g_str_5fb1ba40e1af06001770f97c_general_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f97c_general_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f97c],
  g_base_definitions[g_str_5fb1ba40e1af06001770f97c_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f97c_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f97f],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a29a_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a29a_camp_pack_train],
  g_base_definitions[g_str_5fb1ba19e1af06001770bc4b],
  g_base_definitions[g_str_5fb1ba19e1af06001770bc4d],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a29a"] = army["5fb1b9f3e1af06001770a29a"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Mongol Conquest  1206 to 1266 AD"] = army["5fb1b9f3e1af06001770a29a"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Mongol Conquest  1206 to 1266 AD"] = army["5fb1b9f3e1af06001770a29a"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Mongol Conquest  1206 to 1266 AD"] = army["5fb1b9f3e1af06001770a29a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mongol Conquest  1206 to 1266 AD"] = army["5fb1b9f3e1af06001770a29a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a29a"] = {}
army_dates["5fb1b9f3e1af06001770a29a"]["1206 AD to 1266 AD"] = {
  startDate=1206,
  endDate=1266
}
