-- 5fb1b9f0e1af06001770a123 Xia Chinese  2000 to 1750 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba3ee1af06001770f4aa_general='5fb1ba3ee1af06001770f4aa_general'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4aa_general]={
  id=g_str_5fb1ba3ee1af06001770f4aa_general,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Guard axemen',
  general=true,
  troop_type="Elite Foot",
}
g_str_5fb1ba3ee1af06001770f4aa='5fb1ba3ee1af06001770f4aa'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4aa]={
  id=g_str_5fb1ba3ee1af06001770f4aa,
  name='Elite Foot',
  min=0,
  max=1,
  description='Guard axemen',
  troop_type="Elite Foot",
}
g_str_5fb1ba3ee1af06001770f4ac_general='5fb1ba3ee1af06001770f4ac_general'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4ac_general]={
  id=g_str_5fb1ba3ee1af06001770f4ac_general,
  name='Heavy Foot General',
  min=5,
  max=1,
  description='Dagger-axe men',
  general=true,
  troop_type="Heavy Foot",
}
g_str_5fb1ba3ee1af06001770f4ac='5fb1ba3ee1af06001770f4ac'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4ac]={
  id=g_str_5fb1ba3ee1af06001770f4ac,
  name='Heavy Foot',
  min=5,
  max=15,
  description='Dagger-axe men',
  troop_type="Heavy Foot",
}
g_str_5fb1ba3ee1af06001770f4ae='5fb1ba3ee1af06001770f4ae'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4ae]={
  id=g_str_5fb1ba3ee1af06001770f4ae,
  name='Light Foot',
  min=0,
  max=4,
  description='Spearmen',
  troop_type="Light Foot",
}
g_str_5fb1ba3ee1af06001770f4af='5fb1ba3ee1af06001770f4af'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4af]={
  id=g_str_5fb1ba3ee1af06001770f4af,
  name='Rabble',
  min=0,
  max=4,
  description='Spearmen',
  troop_type="Rabble",
}
g_str_5fb1ba3ee1af06001770f4b1='5fb1ba3ee1af06001770f4b1'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4b1]={
  id=g_str_5fb1ba3ee1af06001770f4b1,
  name='Bow Levy',
  min=2,
  max=8,
  description='Bowmen',
  troop_type="Bow Levy",
}
g_str_5fb1ba3ee1af06001770f4b3='5fb1ba3ee1af06001770f4b3'
g_base_definitions[g_str_5fb1ba3ee1af06001770f4b3]={
  id=g_str_5fb1ba3ee1af06001770f4b3,
  name='Rabble',
  min=0,
  max=2,
  description='Convict or conscript slave foot',
  troop_type="Rabble",
}
g_str_5fb1b9f0e1af06001770a123_camp='5fb1b9f0e1af06001770a123_camp'
g_base_definitions[g_str_5fb1b9f0e1af06001770a123_camp]={
  name='Camp',
  id=g_str_5fb1b9f0e1af06001770a123_camp,
  min=1,
  max=1,
}
army['5fb1b9f0e1af06001770a123']={
  data={
    name='Xia Chinese  2000 to 1750 BC'
  },
  g_base_definitions[g_str_5fb1b9f0e1af06001770a123_camp],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4aa_general],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4aa],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4ac_general],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4ac],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4ae],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4af],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4b1],
  g_base_definitions[g_str_5fb1ba3ee1af06001770f4b3],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a123"] = army["5fb1b9f0e1af06001770a123"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Xia Chinese  2000 to 1750 BC"] = army["5fb1b9f0e1af06001770a123"]
