troop_options['615351ac03385c0016b87358'] = {
  min=2,
  max=5,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b8735b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b8735d'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b8735f'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b87361'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b87364'] = {
  min=2,
  max=4,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b87368'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b8736b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b8736e'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b87371'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b87374'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
troop_options['615351ac03385c0016b87377'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1321,
    endDate=1439,
  }
}
-- allies
