g_str_5fb1ba35e1af06001770e529_general='5fb1ba35e1af06001770e529_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e529_general]={
  id=g_str_5fb1ba35e1af06001770e529_general,
  name='War Wagons General',
  min=3,
  max=1,
  description='War wagons manned by crossbowmen, handgunners, and light guns',
  general=true,
  troop_type="War Wagons",
  troop_option_id="5fb1ba35e1af06001770e528",
}
g_str_5fb1ba35e1af06001770e529='5fb1ba35e1af06001770e529'
g_base_definitions[g_str_5fb1ba35e1af06001770e529]={
  id=g_str_5fb1ba35e1af06001770e529,
  name='War Wagons',
  min=3,
  max=6,
  description='War wagons manned by crossbowmen, handgunners, and light guns',
  troop_type="War Wagons",
  troop_option_id="5fb1ba35e1af06001770e528",
}
g_str_5fb1ba35e1af06001770e52b='5fb1ba35e1af06001770e52b'
g_base_definitions[g_str_5fb1ba35e1af06001770e52b]={
  id=g_str_5fb1ba35e1af06001770e52b,
  name='Bad Horse',
  min=0,
  max=1,
  description='Crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba35e1af06001770e52a",
}
g_str_5fb1ba35e1af06001770e52d_general='5fb1ba35e1af06001770e52d_general'
g_base_definitions[g_str_5fb1ba35e1af06001770e52d_general]={
  id=g_str_5fb1ba35e1af06001770e52d_general,
  name='Heavy Foot General',
  min=7,
  max=1,
  description='Mixed flailmen and halberdiers',
  general=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba35e1af06001770e52c",
}
g_str_5fb1ba35e1af06001770e52d='5fb1ba35e1af06001770e52d'
g_base_definitions[g_str_5fb1ba35e1af06001770e52d]={
  id=g_str_5fb1ba35e1af06001770e52d,
  name='Heavy Foot',
  min=7,
  max=12,
  description='Mixed flailmen and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba35e1af06001770e52c",
}
g_str_5fb1b9e9e1af060017709d69_camp='5fb1b9e9e1af060017709d69_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709d69_camp]={
  id=g_str_5fb1b9e9e1af060017709d69_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709d69_prepared_defenses='5fb1b9e9e1af060017709d69_prepared_defenses'
g_base_definitions[g_str_5fb1b9e9e1af060017709d69_prepared_defenses]={
  id=g_str_5fb1b9e9e1af060017709d69_prepared_defenses,
  name='Prepared Defenses',
  min=0,
  max=16,
  description='Ditches',
  prepared_defenses=true,
  troop_type="Prepared Defenses",
}
