-- 5fb1b9d8e1af0600177092fa Proto-Elamite  3000 to 2601 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_troop_option['5fb1ba1fe1af06001770beb9']= {
  min=1,
  max=1,
  description='Retainers',
  core='all',
}
g_str_5fb1ba1fe1af06001770beba_general='5fb1ba1fe1af06001770beba_general'
g_base_definitions[g_str_5fb1ba1fe1af06001770beba_general]={
  id=g_str_5fb1ba1fe1af06001770beba_general,
  name='Archers General',
  min=1,
  max=1,
  description='Retainers',
  general=true,
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770beb9",
}
g_str_5fb1ba1fe1af06001770beba='5fb1ba1fe1af06001770beba'
g_base_definitions[g_str_5fb1ba1fe1af06001770beba]={
  id=g_str_5fb1ba1fe1af06001770beba,
  name='Archers',
  min=1,
  max=1,
  description='Retainers',
  troop_type="Archers",
  troop_option_id="5fb1ba1fe1af06001770beb9",
}
g_troop_option['5fb1ba1fe1af06001770bebb']= {
  min=16,
  max=22,
  description='Bowmen',
}
g_str_5fb1ba1fe1af06001770bebc='5fb1ba1fe1af06001770bebc'
g_base_definitions[g_str_5fb1ba1fe1af06001770bebc]={
  id=g_str_5fb1ba1fe1af06001770bebc,
  name='Bow Levy',
  min=16,
  max=22,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba1fe1af06001770bebb",
}
g_str_5fb1b9d8e1af0600177092fa_camp='5fb1b9d8e1af0600177092fa_camp'
g_base_definitions[g_str_5fb1b9d8e1af0600177092fa_camp]={
  id=g_str_5fb1b9d8e1af0600177092fa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9d8e1af0600177092fa_camp_pack_train='5fb1b9d8e1af0600177092fa_camp_pack_train'
g_base_definitions[g_str_5fb1b9d8e1af0600177092fa_camp_pack_train]={
  id=g_str_5fb1b9d8e1af0600177092fa_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9d8e1af0600177092fa']={
  data={
    name='Proto-Elamite  3000 to 2601 BC',
    id='5fb1b9d8e1af0600177092fa',
    army_id='5fb1b9d8e1af0600177092fa'
  },
  g_base_definitions[g_str_5fb1ba1fe1af06001770beba_general],
  g_base_definitions[g_str_5fb1ba1fe1af06001770beba],
  g_base_definitions[g_str_5fb1ba1fe1af06001770bebc],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092fa_camp],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092fa_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092fa"] = army["5fb1b9d8e1af0600177092fa"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Proto-Elamite  3000 to 2601 BC"] = army["5fb1b9d8e1af0600177092fa"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Proto-Elamite  3000 to 2601 BC"] = army["5fb1b9d8e1af0600177092fa"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d8e1af0600177092fa"] = {}
army_dates["5fb1b9d8e1af0600177092fa"]["3000 BC to 2601 BC"] ="5fb1b9d8e1af0600177092fa"
