-- 5fb1b9dce1af0600177095ab Iberians  240 to 20 BC

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba27e1af06001770c8ae='5fb1ba27e1af06001770c8ae'
g_base_definitions[g_str_5fb1ba27e1af06001770c8ae]={
  id=g_str_5fb1ba27e1af06001770c8ae,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='',
  general=true,
}
g_str_5fb1ba27e1af06001770c8ae_dismounted='5fb1ba27e1af06001770c8ae_dismounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_dismounted]={
  id=g_str_5fb1ba27e1af06001770c8ae_dismounted,
  name='Light Foot',
  min=1,
  max=1,
  description='\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  general=true,
}
g_5fb1ba27e1af06001770c8ae_dismounted=g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_dismounted]
g_str_5fb1ba27e1af06001770c8ae_mounted='5fb1ba27e1af06001770c8ae_mounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_mounted]={
  id=g_str_5fb1ba27e1af06001770c8ae_mounted,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='\nDeployment dismounting as Light Foot',
  points=4,
  dismount_as=g_5fb1ba27e1af06001770c8ae_dismounted,
  general=true,
}
g_str_5fb1ba27e1af06001770c8ae='5fb1ba27e1af06001770c8ae'
g_base_definitions[g_str_5fb1ba27e1af06001770c8ae]={
  id=g_str_5fb1ba27e1af06001770c8ae,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='',
}
g_str_5fb1ba27e1af06001770c8ae_dismounted='5fb1ba27e1af06001770c8ae_dismounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_dismounted]={
  id=g_str_5fb1ba27e1af06001770c8ae_dismounted,
  name='Light Foot',
  min=1,
  max=3,
  description='\nDeployment dismounted from Javelin Cavalry',
  points=4,
}
g_5fb1ba27e1af06001770c8ae_dismounted=g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_dismounted]
g_str_5fb1ba27e1af06001770c8ae_mounted='5fb1ba27e1af06001770c8ae_mounted'
g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_mounted]={
  id=g_str_5fb1ba27e1af06001770c8ae_mounted,
  name='Javelin Cavalry',
  min=1,
  max=3,
  description='\nDeployment dismounting as Light Foot',
  points=4,
  dismount_as=g_5fb1ba27e1af06001770c8ae_dismounted,
}
g_str_5fb1ba27e1af06001770c8b1='5fb1ba27e1af06001770c8b1'
g_base_definitions[g_str_5fb1ba27e1af06001770c8b1]={
  id=g_str_5fb1ba27e1af06001770c8b1,
  name='Light Foot',
  min=4,
  max=12,
  description='Scutarii',
}
g_str_5fb1ba27e1af06001770c8b3='5fb1ba27e1af06001770c8b3'
g_base_definitions[g_str_5fb1ba27e1af06001770c8b3]={
  id=g_str_5fb1ba27e1af06001770c8b3,
  name='Light Foot',
  min=2,
  max=4,
  description='Caetrati',
}
g_str_5fb1ba27e1af06001770c8b5='5fb1ba27e1af06001770c8b5'
g_base_definitions[g_str_5fb1ba27e1af06001770c8b5]={
  id=g_str_5fb1ba27e1af06001770c8b5,
  name='Skirmishers',
  min=1,
  max=2,
  description='Skirmishing slingers',
}
g_str_5fb1ba27e1af06001770c8b7='5fb1ba27e1af06001770c8b7'
g_base_definitions[g_str_5fb1ba27e1af06001770c8b7]={
  id=g_str_5fb1ba27e1af06001770c8b7,
  name='Raiders',
  min=0,
  max=3,
  description='Mercenary Celtiberian scutarii',
}
g_str_5fb1b9dce1af0600177095ab_camp='5fb1b9dce1af0600177095ab_camp'
g_base_definitions[g_str_5fb1b9dce1af0600177095ab_camp]={
  name='Camp',
  id=g_str_5fb1b9dce1af0600177095ab_camp,
  min=1,
  max=1,
}
army['5fb1b9dce1af0600177095ab']={
  data={
    name='Iberians  240 to 20 BC'
  },
  g_base_definitions[g_str_5fb1b9dce1af0600177095ab_camp],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b9],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_mounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8ae_dismounted],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b1],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b3],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b5],
  g_base_definitions[g_str_5fb1ba27e1af06001770c8b7],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af0600177095ab"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
