troop_options['5fb1ba32e1af06001770ddb6'] = {
  min=1,
  max=3,
  dateRange={
    startDate=1235,
    endDate=1255,
  }
}
troop_options['5fb1ba32e1af06001770ddb9'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1256,
    endDate=1430,
  }
}
troop_options['5fb1ba32e1af06001770ddbc'] = {
  min=1,
  max=4,
  dateRange={
    startDate=1235,
    endDate=1430,
  }
}
troop_options['5fb1ba32e1af06001770ddbe'] = {
  min=9,
  max=20,
  dateRange={
    startDate=1235,
    endDate=1430,
  }
}
troop_options['5fb1ba32e1af06001770ddc0'] = {
  min=0,
  max=2,
  dateRange={
    startDate=1235,
    endDate=1430,
  }
}
-- allies
