-- 5fb1b9dae1af0600177093d1 Early Philistine  1166 to 1100 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba21e1af06001770c16a_general='5fb1ba21e1af06001770c16a_general'
g_base_definitions[g_str_5fb1ba21e1af06001770c16a_general]={
  id=g_str_5fb1ba21e1af06001770c16a_general,
  name='Battle Taxi General',
  min=1,
  max=1,
  description='2-wheeled battle platforms with teams of a driver and 2 javelinmen',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba21e1af06001770c169",
}
g_str_5fb1ba21e1af06001770c16a='5fb1ba21e1af06001770c16a'
g_base_definitions[g_str_5fb1ba21e1af06001770c16a]={
  id=g_str_5fb1ba21e1af06001770c16a,
  name='Battle Taxi',
  min=1,
  max=3,
  description='2-wheeled battle platforms with teams of a driver and 2 javelinmen',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba21e1af06001770c169",
}
g_str_5fb1ba21e1af06001770c16c_general='5fb1ba21e1af06001770c16c_general'
g_base_definitions[g_str_5fb1ba21e1af06001770c16c_general]={
  id=g_str_5fb1ba21e1af06001770c16c_general,
  name='Elite Foot General',
  min=0,
  max=1,
  description='Elite swordsmen',
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba21e1af06001770c16b",
}
g_str_5fb1ba21e1af06001770c16c='5fb1ba21e1af06001770c16c'
g_base_definitions[g_str_5fb1ba21e1af06001770c16c]={
  id=g_str_5fb1ba21e1af06001770c16c,
  name='Elite Foot',
  min=0,
  max=1,
  description='Elite swordsmen',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba21e1af06001770c16b",
}
g_str_5fb1ba21e1af06001770c16e='5fb1ba21e1af06001770c16e'
g_base_definitions[g_str_5fb1ba21e1af06001770c16e]={
  id=g_str_5fb1ba21e1af06001770c16e,
  name='Raiders',
  min=4,
  max=10,
  description='Swordsmen',
  troop_type="Raiders",
  troop_option_id="5fb1ba21e1af06001770c16d",
}
g_str_5fb1ba21e1af06001770c170='5fb1ba21e1af06001770c170'
g_base_definitions[g_str_5fb1ba21e1af06001770c170]={
  id=g_str_5fb1ba21e1af06001770c170,
  name='Light Foot',
  min=0,
  max=2,
  description='Light infantry armed with javelins, some with shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba21e1af06001770c16f",
}
g_str_5fb1ba21e1af06001770c172='5fb1ba21e1af06001770c172'
g_base_definitions[g_str_5fb1ba21e1af06001770c172]={
  id=g_str_5fb1ba21e1af06001770c172,
  name='Rabble',
  min=2,
  max=4,
  description='Javelinmen largely without shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba21e1af06001770c171",
}
g_str_5fb1ba21e1af06001770c174='5fb1ba21e1af06001770c174'
g_base_definitions[g_str_5fb1ba21e1af06001770c174]={
  id=g_str_5fb1ba21e1af06001770c174,
  name='Skirmishers',
  min=0,
  max=1,
  description='Slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba21e1af06001770c173",
}
g_str_5fb1ba21e1af06001770c176='5fb1ba21e1af06001770c176'
g_base_definitions[g_str_5fb1ba21e1af06001770c176]={
  id=g_str_5fb1ba21e1af06001770c176,
  name='Bow Levy',
  min=0,
  max=2,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba21e1af06001770c175",
}
g_str_5fb1ba21e1af06001770c178='5fb1ba21e1af06001770c178'
g_base_definitions[g_str_5fb1ba21e1af06001770c178]={
  id=g_str_5fb1ba21e1af06001770c178,
  name='Skirmishers',
  min=0,
  max=1,
  description='Kharu bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba21e1af06001770c177",
}
g_str_5fb1ba21e1af06001770c179='5fb1ba21e1af06001770c179'
g_base_definitions[g_str_5fb1ba21e1af06001770c179]={
  id=g_str_5fb1ba21e1af06001770c179,
  name='Archers',
  min=0,
  max=1,
  description='Kharu bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba21e1af06001770c177",
}
g_str_5fb1b9dae1af0600177093d1_camp='5fb1b9dae1af0600177093d1_camp'
g_base_definitions[g_str_5fb1b9dae1af0600177093d1_camp]={
  id=g_str_5fb1b9dae1af0600177093d1_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dae1af0600177093d1_camp_pack_train='5fb1b9dae1af0600177093d1_camp_pack_train'
g_base_definitions[g_str_5fb1b9dae1af0600177093d1_camp_pack_train]={
  id=g_str_5fb1b9dae1af0600177093d1_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dae1af0600177093d1']={
  data={
    name='Early Philistine  1166 to 1100 BC'
  },
  g_base_definitions[g_str_5fb1ba21e1af06001770c16a_general],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16a],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16c_general],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16c],
  g_base_definitions[g_str_5fb1ba21e1af06001770c16e],
  g_base_definitions[g_str_5fb1ba21e1af06001770c170],
  g_base_definitions[g_str_5fb1ba21e1af06001770c172],
  g_base_definitions[g_str_5fb1ba21e1af06001770c174],
  g_base_definitions[g_str_5fb1ba21e1af06001770c176],
  g_base_definitions[g_str_5fb1ba21e1af06001770c178],
  g_base_definitions[g_str_5fb1ba21e1af06001770c179],
  g_base_definitions[g_str_5fb1b9dae1af0600177093d1_camp],
  g_base_definitions[g_str_5fb1b9dae1af0600177093d1_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093d1"] = army["5fb1b9dae1af0600177093d1"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Philistine  1166 to 1100 BC"] = army["5fb1b9dae1af0600177093d1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af0600177093d1"] = {}
army_dates["5fb1b9dae1af0600177093d1"]["1166 BC to 1100 BC"] ="5fb1b9dae1af0600177093d1"
