g_str_5fb1ba24e1af06001770c565_general='5fb1ba24e1af06001770c565_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c565_general]={
  id=g_str_5fb1ba24e1af06001770c565_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen or battle platforms with two or four horses',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c565='5fb1ba24e1af06001770c565'
g_base_definitions[g_str_5fb1ba24e1af06001770c565]={
  id=g_str_5fb1ba24e1af06001770c565,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Horsemen or battle platforms with two or four horses',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c566_general='5fb1ba24e1af06001770c566_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c566_general]={
  id=g_str_5fb1ba24e1af06001770c566_general,
  name='Battle Taxi General',
  min=1,
  max=1,
  description='Horsemen or battle platforms with two or four horses',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c566='5fb1ba24e1af06001770c566'
g_base_definitions[g_str_5fb1ba24e1af06001770c566]={
  id=g_str_5fb1ba24e1af06001770c566,
  name='Battle Taxi',
  min=1,
  max=2,
  description='Horsemen or battle platforms with two or four horses',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c568='5fb1ba24e1af06001770c568'
g_base_definitions[g_str_5fb1ba24e1af06001770c568]={
  id=g_str_5fb1ba24e1af06001770c568,
  name='Spears',
  min=1,
  max=2,
  description='Armored hoplites',
  troop_type="Spears",
  troop_option_id="5fb1ba24e1af06001770c567",
}
g_str_5fb1ba24e1af06001770c56b='5fb1ba24e1af06001770c56b'
g_base_definitions[g_str_5fb1ba24e1af06001770c56b]={
  id=g_str_5fb1ba24e1af06001770c56b,
  name='Heavy Foot',
  min=3,
  max=12,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba24e1af06001770c56a",
}
g_str_5fb1ba24e1af06001770c56d='5fb1ba24e1af06001770c56d'
g_base_definitions[g_str_5fb1ba24e1af06001770c56d]={
  id=g_str_5fb1ba24e1af06001770c56d,
  name='Skirmishers',
  min=1,
  max=1,
  description='Skirmishing bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba24e1af06001770c56c",
}
g_str_5fb1ba24e1af06001770c56f='5fb1ba24e1af06001770c56f'
g_base_definitions[g_str_5fb1ba24e1af06001770c56f]={
  id=g_str_5fb1ba24e1af06001770c56f,
  name='Rabble',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba24e1af06001770c56e",
}
g_str_5fb1ba24e1af06001770c571='5fb1ba24e1af06001770c571'
g_base_definitions[g_str_5fb1ba24e1af06001770c571]={
  id=g_str_5fb1ba24e1af06001770c571,
  name='Horde',
  min=0,
  max=2,
  description='Peasant militia',
  troop_type="Horde",
  troop_option_id="5fb1ba24e1af06001770c570",
}
g_str_5fb1b9dbe1af0600177094d7_camp='5fb1b9dbe1af0600177094d7_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094d7_camp]={
  id=g_str_5fb1b9dbe1af0600177094d7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dbe1af0600177094d7_camp_fortified='5fb1b9dbe1af0600177094d7_camp_fortified'
g_base_definitions[g_str_5fb1b9dbe1af0600177094d7_camp_fortified]={
  id=g_str_5fb1b9dbe1af0600177094d7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba0be1af06001770a9c8='5fb1ba0be1af06001770a9c8'
g_base_definitions[g_str_5fb1ba0be1af06001770a9c8]={
  id=g_str_5fb1ba0be1af06001770a9c8,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0be1af06001770a9c7",
}
g_str_5fb1ba0be1af06001770a9ca='5fb1ba0be1af06001770a9ca'
g_base_definitions[g_str_5fb1ba0be1af06001770a9ca]={
  id=g_str_5fb1ba0be1af06001770a9ca,
  name='Rabble',
  min=0,
  max=1,
  description='Psiloi armed with javelins',
  troop_type="Rabble",
  troop_option_id="5fb1ba0be1af06001770a9c9",
}
g_str_5fb1ba0be1af06001770a9cc='5fb1ba0be1af06001770a9cc'
g_base_definitions[g_str_5fb1ba0be1af06001770a9cc]={
  id=g_str_5fb1ba0be1af06001770a9cc,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba0be1af06001770a9cb",
}
g_str_5fb1ba0be1af06001770a9ce='5fb1ba0be1af06001770a9ce'
g_base_definitions[g_str_5fb1ba0be1af06001770a9ce]={
  id=g_str_5fb1ba0be1af06001770a9ce,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0be1af06001770a9cd",
}
g_str_5fb1ba0be1af06001770a9d0='5fb1ba0be1af06001770a9d0'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d0]={
  id=g_str_5fb1ba0be1af06001770a9d0,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Mercenary hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0be1af06001770a9cf",
}
g_str_5fb1ba0be1af06001770a9d2='5fb1ba0be1af06001770a9d2'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d2]={
  id=g_str_5fb1ba0be1af06001770a9d2,
  name='Light Foot',
  min=0,
  max=1,
  description='Mercenary peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0be1af06001770a9d1",
}
g_str_5fb1ba0be1af06001770a9d4='5fb1ba0be1af06001770a9d4'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d4]={
  id=g_str_5fb1ba0be1af06001770a9d4,
  name='Light Foot',
  min=0,
  max=1,
  description='Sikels',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0be1af06001770a9d3",
}
g_str_5fb1ba09e1af06001770a87d='5fb1ba09e1af06001770a87d'
g_base_definitions[g_str_5fb1ba09e1af06001770a87d]={
  id=g_str_5fb1ba09e1af06001770a87d,
  name='Raiders',
  min=2,
  max=4,
  description='Infantry',
  troop_type="Raiders",
  troop_option_id="5fb1ba09e1af06001770a87c",
}
g_str_5fb1ba09e1af06001770a87f='5fb1ba09e1af06001770a87f'
g_base_definitions[g_str_5fb1ba09e1af06001770a87f]={
  id=g_str_5fb1ba09e1af06001770a87f,
  name='Rabble',
  min=0,
  max=1,
  description='Scouts and javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a87e",
}
g_str_5fb1ba09e1af06001770a7cf='5fb1ba09e1af06001770a7cf'
g_base_definitions[g_str_5fb1ba09e1af06001770a7cf]={
  id=g_str_5fb1ba09e1af06001770a7cf,
  name='Spears',
  min=1,
  max=1,
  description='Armored hoplites',
  troop_type="Spears",
  troop_option_id="5fb1ba09e1af06001770a7ce",
}
g_str_5fb1ba09e1af06001770a7d1='5fb1ba09e1af06001770a7d1'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d1]={
  id=g_str_5fb1ba09e1af06001770a7d1,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Scutum and spear',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba09e1af06001770a7d0",
}
g_str_5fb1ba09e1af06001770a7d3='5fb1ba09e1af06001770a7d3'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d3]={
  id=g_str_5fb1ba09e1af06001770a7d3,
  name='Rabble',
  min=1,
  max=1,
  description='Light infantry armed with spear and javelin, possibly some with shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a7d2",
}
g_str_5fb1ba09e1af06001770a7d4='5fb1ba09e1af06001770a7d4'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d4]={
  id=g_str_5fb1ba09e1af06001770a7d4,
  name='Light Foot',
  min=1,
  max=1,
  description='Light infantry armed with spear and javelin, possibly some with shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba09e1af06001770a7d2",
}
g_str_5fb1ba09e1af06001770a7d6='5fb1ba09e1af06001770a7d6'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d6]={
  id=g_str_5fb1ba09e1af06001770a7d6,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba09e1af06001770a7d5",
}
g_str_5fb1ba09e1af06001770a7d8='5fb1ba09e1af06001770a7d8'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d8]={
  id=g_str_5fb1ba09e1af06001770a7d8,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers or unshielded javelinmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba09e1af06001770a7d7",
}
g_str_5fb1ba09e1af06001770a7d9='5fb1ba09e1af06001770a7d9'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d9]={
  id=g_str_5fb1ba09e1af06001770a7d9,
  name='Rabble',
  min=0,
  max=1,
  description='Skirmishing slingers or unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a7d7",
}
g_str_5fb1ba24e1af06001770c565_general='5fb1ba24e1af06001770c565_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c565_general]={
  id=g_str_5fb1ba24e1af06001770c565_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen or battle platforms with two or four horses',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c565='5fb1ba24e1af06001770c565'
g_base_definitions[g_str_5fb1ba24e1af06001770c565]={
  id=g_str_5fb1ba24e1af06001770c565,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Horsemen or battle platforms with two or four horses',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c566_general='5fb1ba24e1af06001770c566_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c566_general]={
  id=g_str_5fb1ba24e1af06001770c566_general,
  name='Battle Taxi General',
  min=1,
  max=1,
  description='Horsemen or battle platforms with two or four horses',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c566='5fb1ba24e1af06001770c566'
g_base_definitions[g_str_5fb1ba24e1af06001770c566]={
  id=g_str_5fb1ba24e1af06001770c566,
  name='Battle Taxi',
  min=1,
  max=2,
  description='Horsemen or battle platforms with two or four horses',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c568='5fb1ba24e1af06001770c568'
g_base_definitions[g_str_5fb1ba24e1af06001770c568]={
  id=g_str_5fb1ba24e1af06001770c568,
  name='Spears',
  min=1,
  max=2,
  description='Armored hoplites',
  troop_type="Spears",
  troop_option_id="5fb1ba24e1af06001770c567",
}
g_str_5fb1ba24e1af06001770c56b='5fb1ba24e1af06001770c56b'
g_base_definitions[g_str_5fb1ba24e1af06001770c56b]={
  id=g_str_5fb1ba24e1af06001770c56b,
  name='Heavy Foot',
  min=3,
  max=12,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba24e1af06001770c56a",
}
g_str_5fb1ba24e1af06001770c56d='5fb1ba24e1af06001770c56d'
g_base_definitions[g_str_5fb1ba24e1af06001770c56d]={
  id=g_str_5fb1ba24e1af06001770c56d,
  name='Skirmishers',
  min=1,
  max=1,
  description='Skirmishing bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba24e1af06001770c56c",
}
g_str_5fb1ba24e1af06001770c56f='5fb1ba24e1af06001770c56f'
g_base_definitions[g_str_5fb1ba24e1af06001770c56f]={
  id=g_str_5fb1ba24e1af06001770c56f,
  name='Rabble',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba24e1af06001770c56e",
}
g_str_5fb1ba24e1af06001770c571='5fb1ba24e1af06001770c571'
g_base_definitions[g_str_5fb1ba24e1af06001770c571]={
  id=g_str_5fb1ba24e1af06001770c571,
  name='Horde',
  min=0,
  max=2,
  description='Peasant militia',
  troop_type="Horde",
  troop_option_id="5fb1ba24e1af06001770c570",
}
g_str_5fb1b9dbe1af0600177094d7_camp='5fb1b9dbe1af0600177094d7_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094d7_camp]={
  id=g_str_5fb1b9dbe1af0600177094d7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dbe1af0600177094d7_camp_fortified='5fb1b9dbe1af0600177094d7_camp_fortified'
g_base_definitions[g_str_5fb1b9dbe1af0600177094d7_camp_fortified]={
  id=g_str_5fb1b9dbe1af0600177094d7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba0be1af06001770a9c8='5fb1ba0be1af06001770a9c8'
g_base_definitions[g_str_5fb1ba0be1af06001770a9c8]={
  id=g_str_5fb1ba0be1af06001770a9c8,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0be1af06001770a9c7",
}
g_str_5fb1ba0be1af06001770a9ca='5fb1ba0be1af06001770a9ca'
g_base_definitions[g_str_5fb1ba0be1af06001770a9ca]={
  id=g_str_5fb1ba0be1af06001770a9ca,
  name='Rabble',
  min=0,
  max=1,
  description='Psiloi armed with javelins',
  troop_type="Rabble",
  troop_option_id="5fb1ba0be1af06001770a9c9",
}
g_str_5fb1ba0be1af06001770a9cc='5fb1ba0be1af06001770a9cc'
g_base_definitions[g_str_5fb1ba0be1af06001770a9cc]={
  id=g_str_5fb1ba0be1af06001770a9cc,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba0be1af06001770a9cb",
}
g_str_5fb1ba0be1af06001770a9ce='5fb1ba0be1af06001770a9ce'
g_base_definitions[g_str_5fb1ba0be1af06001770a9ce]={
  id=g_str_5fb1ba0be1af06001770a9ce,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0be1af06001770a9cd",
}
g_str_5fb1ba0be1af06001770a9d0='5fb1ba0be1af06001770a9d0'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d0]={
  id=g_str_5fb1ba0be1af06001770a9d0,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Mercenary hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0be1af06001770a9cf",
}
g_str_5fb1ba0be1af06001770a9d2='5fb1ba0be1af06001770a9d2'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d2]={
  id=g_str_5fb1ba0be1af06001770a9d2,
  name='Light Foot',
  min=0,
  max=1,
  description='Mercenary peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0be1af06001770a9d1",
}
g_str_5fb1ba0be1af06001770a9d4='5fb1ba0be1af06001770a9d4'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d4]={
  id=g_str_5fb1ba0be1af06001770a9d4,
  name='Light Foot',
  min=0,
  max=1,
  description='Sikels',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0be1af06001770a9d3",
}
g_str_5fb1ba09e1af06001770a87d='5fb1ba09e1af06001770a87d'
g_base_definitions[g_str_5fb1ba09e1af06001770a87d]={
  id=g_str_5fb1ba09e1af06001770a87d,
  name='Raiders',
  min=2,
  max=4,
  description='Infantry',
  troop_type="Raiders",
  troop_option_id="5fb1ba09e1af06001770a87c",
}
g_str_5fb1ba09e1af06001770a87f='5fb1ba09e1af06001770a87f'
g_base_definitions[g_str_5fb1ba09e1af06001770a87f]={
  id=g_str_5fb1ba09e1af06001770a87f,
  name='Rabble',
  min=0,
  max=1,
  description='Scouts and javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a87e",
}
g_str_5fb1ba09e1af06001770a7cf='5fb1ba09e1af06001770a7cf'
g_base_definitions[g_str_5fb1ba09e1af06001770a7cf]={
  id=g_str_5fb1ba09e1af06001770a7cf,
  name='Spears',
  min=1,
  max=1,
  description='Armored hoplites',
  troop_type="Spears",
  troop_option_id="5fb1ba09e1af06001770a7ce",
}
g_str_5fb1ba09e1af06001770a7d1='5fb1ba09e1af06001770a7d1'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d1]={
  id=g_str_5fb1ba09e1af06001770a7d1,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Scutum and spear',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba09e1af06001770a7d0",
}
g_str_5fb1ba09e1af06001770a7d3='5fb1ba09e1af06001770a7d3'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d3]={
  id=g_str_5fb1ba09e1af06001770a7d3,
  name='Rabble',
  min=1,
  max=1,
  description='Light infantry armed with spear and javelin, possibly some with shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a7d2",
}
g_str_5fb1ba09e1af06001770a7d4='5fb1ba09e1af06001770a7d4'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d4]={
  id=g_str_5fb1ba09e1af06001770a7d4,
  name='Light Foot',
  min=1,
  max=1,
  description='Light infantry armed with spear and javelin, possibly some with shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba09e1af06001770a7d2",
}
g_str_5fb1ba09e1af06001770a7d6='5fb1ba09e1af06001770a7d6'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d6]={
  id=g_str_5fb1ba09e1af06001770a7d6,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba09e1af06001770a7d5",
}
g_str_5fb1ba09e1af06001770a7d8='5fb1ba09e1af06001770a7d8'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d8]={
  id=g_str_5fb1ba09e1af06001770a7d8,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers or unshielded javelinmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba09e1af06001770a7d7",
}
g_str_5fb1ba09e1af06001770a7d9='5fb1ba09e1af06001770a7d9'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d9]={
  id=g_str_5fb1ba09e1af06001770a7d9,
  name='Rabble',
  min=0,
  max=1,
  description='Skirmishing slingers or unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a7d7",
}
g_str_5fb1ba24e1af06001770c565_general='5fb1ba24e1af06001770c565_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c565_general]={
  id=g_str_5fb1ba24e1af06001770c565_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Horsemen or battle platforms with two or four horses',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c565='5fb1ba24e1af06001770c565'
g_base_definitions[g_str_5fb1ba24e1af06001770c565]={
  id=g_str_5fb1ba24e1af06001770c565,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Horsemen or battle platforms with two or four horses',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c566_general='5fb1ba24e1af06001770c566_general'
g_base_definitions[g_str_5fb1ba24e1af06001770c566_general]={
  id=g_str_5fb1ba24e1af06001770c566_general,
  name='Battle Taxi General',
  min=1,
  max=1,
  description='Horsemen or battle platforms with two or four horses',
  general=true,
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c566='5fb1ba24e1af06001770c566'
g_base_definitions[g_str_5fb1ba24e1af06001770c566]={
  id=g_str_5fb1ba24e1af06001770c566,
  name='Battle Taxi',
  min=1,
  max=2,
  description='Horsemen or battle platforms with two or four horses',
  troop_type="Battle Taxi",
  troop_option_id="5fb1ba24e1af06001770c564",
}
g_str_5fb1ba24e1af06001770c568='5fb1ba24e1af06001770c568'
g_base_definitions[g_str_5fb1ba24e1af06001770c568]={
  id=g_str_5fb1ba24e1af06001770c568,
  name='Spears',
  min=1,
  max=2,
  description='Armored hoplites',
  troop_type="Spears",
  troop_option_id="5fb1ba24e1af06001770c567",
}
g_str_5fb1ba24e1af06001770c56b='5fb1ba24e1af06001770c56b'
g_base_definitions[g_str_5fb1ba24e1af06001770c56b]={
  id=g_str_5fb1ba24e1af06001770c56b,
  name='Heavy Foot',
  min=3,
  max=12,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba24e1af06001770c56a",
}
g_str_5fb1ba24e1af06001770c56d='5fb1ba24e1af06001770c56d'
g_base_definitions[g_str_5fb1ba24e1af06001770c56d]={
  id=g_str_5fb1ba24e1af06001770c56d,
  name='Skirmishers',
  min=1,
  max=1,
  description='Skirmishing bowmen and slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba24e1af06001770c56c",
}
g_str_5fb1ba24e1af06001770c56f='5fb1ba24e1af06001770c56f'
g_base_definitions[g_str_5fb1ba24e1af06001770c56f]={
  id=g_str_5fb1ba24e1af06001770c56f,
  name='Rabble',
  min=1,
  max=4,
  description='Javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba24e1af06001770c56e",
}
g_str_5fb1ba24e1af06001770c571='5fb1ba24e1af06001770c571'
g_base_definitions[g_str_5fb1ba24e1af06001770c571]={
  id=g_str_5fb1ba24e1af06001770c571,
  name='Horde',
  min=0,
  max=2,
  description='Peasant militia',
  troop_type="Horde",
  troop_option_id="5fb1ba24e1af06001770c570",
}
g_str_5fb1b9dbe1af0600177094d7_camp='5fb1b9dbe1af0600177094d7_camp'
g_base_definitions[g_str_5fb1b9dbe1af0600177094d7_camp]={
  id=g_str_5fb1b9dbe1af0600177094d7_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dbe1af0600177094d7_camp_fortified='5fb1b9dbe1af0600177094d7_camp_fortified'
g_base_definitions[g_str_5fb1b9dbe1af0600177094d7_camp_fortified]={
  id=g_str_5fb1b9dbe1af0600177094d7_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba0be1af06001770a9c8='5fb1ba0be1af06001770a9c8'
g_base_definitions[g_str_5fb1ba0be1af06001770a9c8]={
  id=g_str_5fb1ba0be1af06001770a9c8,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0be1af06001770a9c7",
}
g_str_5fb1ba0be1af06001770a9ca='5fb1ba0be1af06001770a9ca'
g_base_definitions[g_str_5fb1ba0be1af06001770a9ca]={
  id=g_str_5fb1ba0be1af06001770a9ca,
  name='Rabble',
  min=0,
  max=1,
  description='Psiloi armed with javelins',
  troop_type="Rabble",
  troop_option_id="5fb1ba0be1af06001770a9c9",
}
g_str_5fb1ba0be1af06001770a9cc='5fb1ba0be1af06001770a9cc'
g_base_definitions[g_str_5fb1ba0be1af06001770a9cc]={
  id=g_str_5fb1ba0be1af06001770a9cc,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba0be1af06001770a9cb",
}
g_str_5fb1ba0be1af06001770a9ce='5fb1ba0be1af06001770a9ce'
g_base_definitions[g_str_5fb1ba0be1af06001770a9ce]={
  id=g_str_5fb1ba0be1af06001770a9ce,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba0be1af06001770a9cd",
}
g_str_5fb1ba0be1af06001770a9d0='5fb1ba0be1af06001770a9d0'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d0]={
  id=g_str_5fb1ba0be1af06001770a9d0,
  name='Heavy Foot',
  min=0,
  max=4,
  description='Mercenary hoplites',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba0be1af06001770a9cf",
}
g_str_5fb1ba0be1af06001770a9d2='5fb1ba0be1af06001770a9d2'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d2]={
  id=g_str_5fb1ba0be1af06001770a9d2,
  name='Light Foot',
  min=0,
  max=1,
  description='Mercenary peltasts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0be1af06001770a9d1",
}
g_str_5fb1ba0be1af06001770a9d4='5fb1ba0be1af06001770a9d4'
g_base_definitions[g_str_5fb1ba0be1af06001770a9d4]={
  id=g_str_5fb1ba0be1af06001770a9d4,
  name='Light Foot',
  min=0,
  max=1,
  description='Sikels',
  troop_type="Light Foot",
  troop_option_id="5fb1ba0be1af06001770a9d3",
}
g_str_5fb1ba09e1af06001770a87d='5fb1ba09e1af06001770a87d'
g_base_definitions[g_str_5fb1ba09e1af06001770a87d]={
  id=g_str_5fb1ba09e1af06001770a87d,
  name='Raiders',
  min=2,
  max=4,
  description='Infantry',
  troop_type="Raiders",
  troop_option_id="5fb1ba09e1af06001770a87c",
}
g_str_5fb1ba09e1af06001770a87f='5fb1ba09e1af06001770a87f'
g_base_definitions[g_str_5fb1ba09e1af06001770a87f]={
  id=g_str_5fb1ba09e1af06001770a87f,
  name='Rabble',
  min=0,
  max=1,
  description='Scouts and javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a87e",
}
g_str_5fb1ba09e1af06001770a7cf='5fb1ba09e1af06001770a7cf'
g_base_definitions[g_str_5fb1ba09e1af06001770a7cf]={
  id=g_str_5fb1ba09e1af06001770a7cf,
  name='Spears',
  min=1,
  max=1,
  description='Armored hoplites',
  troop_type="Spears",
  troop_option_id="5fb1ba09e1af06001770a7ce",
}
g_str_5fb1ba09e1af06001770a7d1='5fb1ba09e1af06001770a7d1'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d1]={
  id=g_str_5fb1ba09e1af06001770a7d1,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Scutum and spear',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba09e1af06001770a7d0",
}
g_str_5fb1ba09e1af06001770a7d3='5fb1ba09e1af06001770a7d3'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d3]={
  id=g_str_5fb1ba09e1af06001770a7d3,
  name='Rabble',
  min=1,
  max=1,
  description='Light infantry armed with spear and javelin, possibly some with shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a7d2",
}
g_str_5fb1ba09e1af06001770a7d4='5fb1ba09e1af06001770a7d4'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d4]={
  id=g_str_5fb1ba09e1af06001770a7d4,
  name='Light Foot',
  min=1,
  max=1,
  description='Light infantry armed with spear and javelin, possibly some with shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba09e1af06001770a7d2",
}
g_str_5fb1ba09e1af06001770a7d6='5fb1ba09e1af06001770a7d6'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d6]={
  id=g_str_5fb1ba09e1af06001770a7d6,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba09e1af06001770a7d5",
}
g_str_5fb1ba09e1af06001770a7d8='5fb1ba09e1af06001770a7d8'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d8]={
  id=g_str_5fb1ba09e1af06001770a7d8,
  name='Skirmishers',
  min=0,
  max=1,
  description='Skirmishing slingers or unshielded javelinmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba09e1af06001770a7d7",
}
g_str_5fb1ba09e1af06001770a7d9='5fb1ba09e1af06001770a7d9'
g_base_definitions[g_str_5fb1ba09e1af06001770a7d9]={
  id=g_str_5fb1ba09e1af06001770a7d9,
  name='Rabble',
  min=0,
  max=1,
  description='Skirmishing slingers or unshielded javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba09e1af06001770a7d7",
}
