g_str_5fb1ba3de1af06001770f443_general='5fb1ba3de1af06001770f443_general'
g_base_definitions[g_str_5fb1ba3de1af06001770f443_general]={
  id=g_str_5fb1ba3de1af06001770f443_general,
  name='Elephants General',
  min=1,
  max=1,
  description='War elephants',
  general=true,
  troop_type="Elephants",
  troop_option_id="5fb1ba3de1af06001770f442",
}
g_str_5fb1ba3de1af06001770f443='5fb1ba3de1af06001770f443'
g_base_definitions[g_str_5fb1ba3de1af06001770f443]={
  id=g_str_5fb1ba3de1af06001770f443,
  name='Elephants',
  min=1,
  max=2,
  description='War elephants',
  troop_type="Elephants",
  troop_option_id="5fb1ba3de1af06001770f442",
}
g_str_5fb1ba3de1af06001770f446='5fb1ba3de1af06001770f446'
g_base_definitions[g_str_5fb1ba3de1af06001770f446]={
  id=g_str_5fb1ba3de1af06001770f446,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Noble horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3de1af06001770f445",
}
g_str_5fb1ba3de1af06001770f448='5fb1ba3de1af06001770f448'
g_base_definitions[g_str_5fb1ba3de1af06001770f448]={
  id=g_str_5fb1ba3de1af06001770f448,
  name='Warriors',
  min=6,
  max=14,
  description='Tribesmen',
  troop_type="Warriors",
  troop_option_id="5fb1ba3de1af06001770f447",
}
g_str_5fb1ba3de1af06001770f448_elephant_screen='5fb1ba3de1af06001770f448_elephant_screen'
g_base_definitions[g_str_5fb1ba3de1af06001770f448_elephant_screen]={
  id=g_str_5fb1ba3de1af06001770f448_elephant_screen,
  name='Warriors',
  min=6,
  max=14,
  description='Tribesmen\nElephant Screen',
  elephant_screen=true,
  troop_type="Warriors",
  troop_option_id="5fb1ba3de1af06001770f447",
}
g_str_5fb1ba3de1af06001770f448_elephant_screen_elephant_screen_counter='5fb1ba3de1af06001770f448_elephant_screen_elephant_screen_counter'
g_base_definitions[g_str_5fb1ba3de1af06001770f448_elephant_screen_elephant_screen_counter]={
  id=g_str_5fb1ba3de1af06001770f448_elephant_screen_elephant_screen_counter,
  name='Elephant Screen',
  min=6,
  max=14,
  description='',
  troop_type="Elephant Screen Counter",
}
g_str_5fb1ba3de1af06001770f44b='5fb1ba3de1af06001770f44b'
g_base_definitions[g_str_5fb1ba3de1af06001770f44b]={
  id=g_str_5fb1ba3de1af06001770f44b,
  name='Bow Levy',
  min=1,
  max=5,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3de1af06001770f44a",
}
g_str_5fb1ba3de1af06001770f44d='5fb1ba3de1af06001770f44d'
g_base_definitions[g_str_5fb1ba3de1af06001770f44d]={
  id=g_str_5fb1ba3de1af06001770f44d,
  name='Rabble',
  min=0,
  max=3,
  description='Javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba3de1af06001770f44c",
}
g_str_5fb1ba3de1af06001770f450='5fb1ba3de1af06001770f450'
g_base_definitions[g_str_5fb1ba3de1af06001770f450]={
  id=g_str_5fb1ba3de1af06001770f450,
  name='Artillery',
  min=0,
  max=1,
  description='Heavy guns manned by Turkish mercenaries',
  troop_type="Artillery",
  troop_option_id="5fb1ba3de1af06001770f44e",
}
g_str_5fb1b9f0e1af06001770a100_camp='5fb1b9f0e1af06001770a100_camp'
g_base_definitions[g_str_5fb1b9f0e1af06001770a100_camp]={
  id=g_str_5fb1b9f0e1af06001770a100_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
