troop_options['5fb1ba2de1af06001770d59e'] = {
  min=0,
  max=1,
  dateRange={
    startDate=250,
    endDate=406,
  }
}
troop_options['5fb1ba2de1af06001770d5a2'] = {
  min=12,
  max=16,
  dateRange={
    startDate=250,
    endDate=406,
  }
}
troop_options['5fb1ba2de1af06001770d5a4'] = {
  min=0,
  max=2,
  dateRange={
    startDate=250,
    endDate=406,
  }
}
troop_options['5fb1ba2de1af06001770d5a6'] = {
  min=0,
  max=2,
  dateRange={
    startDate=250,
    endDate=406,
  }
}
-- allies
