troop_options['615351b303385c0016b8855a'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-1100,
    endDate=-800,
  }
}
troop_options['615351b303385c0016b8855c'] = {
  min=8,
  max=14,
  dateRange={
    startDate=-1100,
    endDate=-800,
  }
}
troop_options['615351b303385c0016b8855e'] = {
  min=2,
  max=6,
  dateRange={
    startDate=-1100,
    endDate=-800,
  }
}
troop_options['615351b303385c0016b88560'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-1100,
    endDate=-800,
  }
}
-- allies
