troop_options['615351a103385c0016b8561c'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['615351a103385c0016b8561f'] = {
  min=4,
  max=13,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['615351a103385c0016b85621'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['615351a103385c0016b85624'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
troop_options['615351a103385c0016b85627'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-669,
    endDate=-449,
  }
}
-- allies
