-- 5fb1b9e7e1af060017709bd9 Early Andalusian  711 to 764 AD

army['5fb1b9e7e1af060017709bd9']={
  data={
    invasionRatings={
      {
        value=3,
        note='',
      },
    },
    name='Early Andalusian  711 to 764 AD',
    id='5fb1b9e7e1af060017709bd9',
    dateRange={
      startDate=711,
      endDate=764,
    }
  },
  g_base_definitions[g_str_5fb1ba32e1af06001770deb3_general],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb3],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb5],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb6],
  g_base_definitions[g_str_5fb1ba32e1af06001770deb8],
  g_base_definitions[g_str_5fb1ba32e1af06001770deba],
  g_base_definitions[g_str_5fb1ba32e1af06001770debd],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bd9_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bd9_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709bd9"] = army["5fb1b9e7e1af060017709bd9"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Andalusian  711 to 764 AD"] = army["5fb1b9e7e1af060017709bd9"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Early Andalusian  711 to 764 AD"] = army["5fb1b9e7e1af060017709bd9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Andalusian  711 to 764 AD"] = army["5fb1b9e7e1af060017709bd9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709bd9"] = {}
army_dates["5fb1b9e7e1af060017709bd9"]["711 AD to 764 AD"] = {
  startDate=711,
  endDate=764
}
