troop_options['5fb1ba28e1af06001770cc5f'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-251,
    endDate=-208,
  }
}
troop_options['5fb1ba28e1af06001770cc61'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-251,
    endDate=-208,
  }
}
troop_options['5fb1ba28e1af06001770cc63'] = {
  min=4,
  max=10,
  dateRange={
    startDate=-251,
    endDate=-208,
  }
}
troop_options['5fb1ba28e1af06001770cc65'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-251,
    endDate=-208,
  }
}
troop_options['5fb1ba28e1af06001770cc67'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-251,
    endDate=-208,
  }
}
troop_options['5fb1ba28e1af06001770cc69'] = {
  min=0,
  max=3,
  dateRange={
    startDate=-251,
    endDate=-208,
  }
}
-- allies
