-- 5fb1b9e8e1af060017709c78 Franco-Scottish  1419 to 1424 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba33e1af06001770e0f8_general='5fb1ba33e1af06001770e0f8_general'
g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_general]={
  id=g_str_5fb1ba33e1af06001770e0f8_general,
  name='Knights General',
  min=1,
  max=1,
  description='Scots men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0f7",
}
g_str_5fb1ba33e1af06001770e0f8_general_dismounted='5fb1ba33e1af06001770e0f8_general_dismounted'
g_str_5fb1ba33e1af06001770e0f8_general_mounted='5fb1ba33e1af06001770e0f8_general_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_general_dismounted]={
  id=g_str_5fb1ba33e1af06001770e0f8_general_dismounted,
  name='Elite Foot General',
  min=1,
  max=1,
  description='Scots men-at-arms\nDeployment dismounted from Knights General',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770e0f8_general_mounted,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e0f7",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_general_mounted]={
  id=g_str_5fb1ba33e1af06001770e0f8_general_mounted,
  name='Knights General',
  min=1,
  max=1,
  description='Scots men-at-arms\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770e0f8_general_dismounted,
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0f7",
}
g_str_5fb1ba33e1af06001770e0f8='5fb1ba33e1af06001770e0f8'
g_base_definitions[g_str_5fb1ba33e1af06001770e0f8]={
  id=g_str_5fb1ba33e1af06001770e0f8,
  name='Knights',
  min=1,
  max=2,
  description='Scots men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0f7",
}
g_str_5fb1ba33e1af06001770e0f8_dismounted='5fb1ba33e1af06001770e0f8_dismounted'
g_str_5fb1ba33e1af06001770e0f8_mounted='5fb1ba33e1af06001770e0f8_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_dismounted]={
  id=g_str_5fb1ba33e1af06001770e0f8_dismounted,
  name='Elite Foot',
  min=1,
  max=2,
  description='Scots men-at-arms\nDeployment dismounted from Knights',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770e0f8_mounted,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e0f7",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_mounted]={
  id=g_str_5fb1ba33e1af06001770e0f8_mounted,
  name='Knights',
  min=1,
  max=2,
  description='Scots men-at-arms\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770e0f8_dismounted,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0f7",
}
g_str_5fb1ba33e1af06001770e0fb_general='5fb1ba33e1af06001770e0fb_general'
g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_general]={
  id=g_str_5fb1ba33e1af06001770e0fb_general,
  name='Knights General',
  min=2,
  max=1,
  description='Chevaliers',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0fa",
}
g_str_5fb1ba33e1af06001770e0fb_general_dismounted='5fb1ba33e1af06001770e0fb_general_dismounted'
g_str_5fb1ba33e1af06001770e0fb_general_mounted='5fb1ba33e1af06001770e0fb_general_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_general_dismounted]={
  id=g_str_5fb1ba33e1af06001770e0fb_general_dismounted,
  name='Elite Foot General',
  min=2,
  max=1,
  description='Chevaliers\nDeployment dismounted from Knights General',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770e0fb_general_mounted,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e0fa",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_general_mounted]={
  id=g_str_5fb1ba33e1af06001770e0fb_general_mounted,
  name='Knights General',
  min=2,
  max=1,
  description='Chevaliers\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770e0fb_general_dismounted,
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0fa",
}
g_str_5fb1ba33e1af06001770e0fb='5fb1ba33e1af06001770e0fb'
g_base_definitions[g_str_5fb1ba33e1af06001770e0fb]={
  id=g_str_5fb1ba33e1af06001770e0fb,
  name='Knights',
  min=2,
  max=3,
  description='Chevaliers',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0fa",
}
g_str_5fb1ba33e1af06001770e0fb_dismounted='5fb1ba33e1af06001770e0fb_dismounted'
g_str_5fb1ba33e1af06001770e0fb_mounted='5fb1ba33e1af06001770e0fb_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_dismounted]={
  id=g_str_5fb1ba33e1af06001770e0fb_dismounted,
  name='Elite Foot',
  min=2,
  max=3,
  description='Chevaliers\nDeployment dismounted from Knights',
  points=4,
  dismounted_from=g_str_5fb1ba33e1af06001770e0fb_mounted,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e0fa",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_mounted]={
  id=g_str_5fb1ba33e1af06001770e0fb_mounted,
  name='Knights',
  min=2,
  max=3,
  description='Chevaliers\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba33e1af06001770e0fb_dismounted,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e0fa",
}
g_str_5fb1ba33e1af06001770e0fe='5fb1ba33e1af06001770e0fe'
g_base_definitions[g_str_5fb1ba33e1af06001770e0fe]={
  id=g_str_5fb1ba33e1af06001770e0fe,
  name='Archers',
  min=0,
  max=2,
  description='Scots feudal bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e0fd",
}
g_str_5fb1ba33e1af06001770e0fe_dismounted_mobile_infantry='5fb1ba33e1af06001770e0fe_dismounted_mobile_infantry'
g_str_5fb1ba33e1af06001770e0fe_mounted_mobile_infantry='5fb1ba33e1af06001770e0fe_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e0fe_dismounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e0fe_dismounted_mobile_infantry,
  name='Archers',
  min=0,
  max=2,
  description='Scots feudal bowmen\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba33e1af06001770e0fe_mounted_mobile_infantry,
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e0fd",
}
g_base_definitions[g_str_5fb1ba33e1af06001770e0fe_mounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e0fe_mounted_mobile_infantry,
  name='Archers',
  min=0,
  max=2,
  description='Scots feudal bowmen\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba33e1af06001770e0fe_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e0fd",
}
g_str_5fb1ba33e1af06001770e101='5fb1ba33e1af06001770e101'
g_base_definitions[g_str_5fb1ba33e1af06001770e101]={
  id=g_str_5fb1ba33e1af06001770e101,
  name='Heavy Foot',
  min=1,
  max=3,
  description='Scots axemen or Highland bowmen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba33e1af06001770e100",
}
g_str_5fb1ba33e1af06001770e102='5fb1ba33e1af06001770e102'
g_base_definitions[g_str_5fb1ba33e1af06001770e102]={
  id=g_str_5fb1ba33e1af06001770e102,
  name='Archers',
  min=1,
  max=3,
  description='Scots axemen or Highland bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e100",
}
g_str_5fb1ba33e1af06001770e104='5fb1ba33e1af06001770e104'
g_base_definitions[g_str_5fb1ba33e1af06001770e104]={
  id=g_str_5fb1ba33e1af06001770e104,
  name='Bow Levy',
  min=2,
  max=4,
  description='French bowmen and crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e103",
}
g_str_5fb1ba33e1af06001770e106='5fb1ba33e1af06001770e106'
g_base_definitions[g_str_5fb1ba33e1af06001770e106]={
  id=g_str_5fb1ba33e1af06001770e106,
  name='Archers',
  min=0,
  max=3,
  description='Genoese crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e105",
}
g_str_5fb1ba33e1af06001770e108='5fb1ba33e1af06001770e108'
g_base_definitions[g_str_5fb1ba33e1af06001770e108]={
  id=g_str_5fb1ba33e1af06001770e108,
  name='Skirmishers',
  min=0,
  max=1,
  description='Spanish crossbowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba33e1af06001770e107",
}
g_str_5fb1ba33e1af06001770e10a='5fb1ba33e1af06001770e10a'
g_base_definitions[g_str_5fb1ba33e1af06001770e10a]={
  id=g_str_5fb1ba33e1af06001770e10a,
  name='Spears',
  min=1,
  max=3,
  description='Spearmen with pavise',
  troop_type="Spears",
  troop_option_id="5fb1ba33e1af06001770e109",
}
g_str_5fb1ba33e1af06001770e10c='5fb1ba33e1af06001770e10c'
g_base_definitions[g_str_5fb1ba33e1af06001770e10c]={
  id=g_str_5fb1ba33e1af06001770e10c,
  name='Heavy Foot',
  min=0,
  max=1,
  description='Voulgier',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba33e1af06001770e10b",
}
g_str_5fb1ba33e1af06001770e10e='5fb1ba33e1af06001770e10e'
g_base_definitions[g_str_5fb1ba33e1af06001770e10e]={
  id=g_str_5fb1ba33e1af06001770e10e,
  name='Rabble',
  min=0,
  max=2,
  description='Ribauds',
  troop_type="Rabble",
  troop_option_id="5fb1ba33e1af06001770e10d",
}
g_str_5fb1ba33e1af06001770e110='5fb1ba33e1af06001770e110'
g_base_definitions[g_str_5fb1ba33e1af06001770e110]={
  id=g_str_5fb1ba33e1af06001770e110,
  name='Horde',
  min=0,
  max=3,
  description='Peasant levy',
  troop_type="Horde",
  troop_option_id="5fb1ba33e1af06001770e10f",
}
g_str_5fb1b9e8e1af060017709c78_camp='5fb1b9e8e1af060017709c78_camp'
g_base_definitions[g_str_5fb1b9e8e1af060017709c78_camp]={
  id=g_str_5fb1b9e8e1af060017709c78_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e8e1af060017709c78']={
  data={
    name='Franco-Scottish  1419 to 1424 AD',
    id='5fb1b9e8e1af060017709c78'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0f8],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0f8_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fb],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fb_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fe],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fe_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e0fe_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e101],
  g_base_definitions[g_str_5fb1ba33e1af06001770e102],
  g_base_definitions[g_str_5fb1ba33e1af06001770e104],
  g_base_definitions[g_str_5fb1ba33e1af06001770e106],
  g_base_definitions[g_str_5fb1ba33e1af06001770e108],
  g_base_definitions[g_str_5fb1ba33e1af06001770e10a],
  g_base_definitions[g_str_5fb1ba33e1af06001770e10c],
  g_base_definitions[g_str_5fb1ba33e1af06001770e10e],
  g_base_definitions[g_str_5fb1ba33e1af06001770e110],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c78_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c78"] = army["5fb1b9e8e1af060017709c78"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Franco-Scottish  1419 to 1424 AD"] = army["5fb1b9e8e1af060017709c78"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Franco-Scottish  1419 to 1424 AD"] = army["5fb1b9e8e1af060017709c78"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Franco-Scottish  1419 to 1424 AD"] = army["5fb1b9e8e1af060017709c78"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c78"] = {}
army_dates["5fb1b9e8e1af060017709c78"]["1419 AD to 1424 AD"] ="5fb1b9e8e1af060017709c78"
