troop_options['615351ae03385c0016b87765'] = {
  min=0,
  max=1,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['615351ae03385c0016b87769'] = {
  min=7,
  max=12,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['615351ae03385c0016b8776d'] = {
  min=0,
  max=3,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['615351ae03385c0016b87770'] = {
  min=0,
  max=1,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
troop_options['615351ae03385c0016b87772'] = {
  min=0,
  max=1,
  dateRange={
    startDate=860,
    endDate=1054,
  }
}
-- allies
