g_str_5fb1ba2ce1af06001770d482_general='5fb1ba2ce1af06001770d482_general'
g_base_definitions[g_str_5fb1ba2ce1af06001770d482_general]={
  id=g_str_5fb1ba2ce1af06001770d482_general,
  name='Knights General',
  min=0,
  max=1,
  description='Roman Equites',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba2ce1af06001770d481",
}
g_str_5fb1ba2ce1af06001770d482='5fb1ba2ce1af06001770d482'
g_base_definitions[g_str_5fb1ba2ce1af06001770d482]={
  id=g_str_5fb1ba2ce1af06001770d482,
  name='Knights',
  min=0,
  max=1,
  description='Roman Equites',
  troop_type="Knights",
  troop_option_id="5fb1ba2ce1af06001770d481",
}
g_str_5fb1ba2ce1af06001770d484='5fb1ba2ce1af06001770d484'
g_base_definitions[g_str_5fb1ba2ce1af06001770d484]={
  id=g_str_5fb1ba2ce1af06001770d484,
  name='Elite Foot',
  min=0,
  max=1,
  description='Primani',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba2ce1af06001770d483",
}
g_str_5fb1ba2ce1af06001770d487_general='5fb1ba2ce1af06001770d487_general'
g_base_definitions[g_str_5fb1ba2ce1af06001770d487_general]={
  id=g_str_5fb1ba2ce1af06001770d487_general,
  name='Bad Horse General',
  min=1,
  max=1,
  description='Alae',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba2ce1af06001770d486",
}
g_str_5fb1ba2ce1af06001770d487='5fb1ba2ce1af06001770d487'
g_base_definitions[g_str_5fb1ba2ce1af06001770d487]={
  id=g_str_5fb1ba2ce1af06001770d487,
  name='Bad Horse',
  min=1,
  max=1,
  description='Alae',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba2ce1af06001770d486",
}
g_str_5fb1ba2ce1af06001770d489='5fb1ba2ce1af06001770d489'
g_base_definitions[g_str_5fb1ba2ce1af06001770d489]={
  id=g_str_5fb1ba2ce1af06001770d489,
  name='Heavy Foot',
  min=1,
  max=2,
  description='Legionaries',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2ce1af06001770d488",
}
g_str_5fb1ba2ce1af06001770d48c='5fb1ba2ce1af06001770d48c'
g_base_definitions[g_str_5fb1ba2ce1af06001770d48c]={
  id=g_str_5fb1ba2ce1af06001770d48c,
  name='Light Foot',
  min=1,
  max=4,
  description='Border auxiliary cohorts',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2ce1af06001770d48b",
}
g_str_5fb1ba2ce1af06001770d48f='5fb1ba2ce1af06001770d48f'
g_base_definitions[g_str_5fb1ba2ce1af06001770d48f]={
  id=g_str_5fb1ba2ce1af06001770d48f,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing legionary and auxiliary bow',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba2ce1af06001770d48e",
}
g_str_5fb1ba2ce1af06001770d492='5fb1ba2ce1af06001770d492'
g_base_definitions[g_str_5fb1ba2ce1af06001770d492]={
  id=g_str_5fb1ba2ce1af06001770d492,
  name='Heavy Foot',
  min=6,
  max=13,
  description='Pedyt',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba2ce1af06001770d491",
}
g_str_5fb1ba2ce1af06001770d494='5fb1ba2ce1af06001770d494'
g_base_definitions[g_str_5fb1ba2ce1af06001770d494]={
  id=g_str_5fb1ba2ce1af06001770d494,
  name='Rabble',
  min=0,
  max=1,
  description='Militia with sling, bow, or javelin',
  troop_type="Rabble",
  troop_option_id="5fb1ba2ce1af06001770d493",
}
g_str_5fb1ba2ce1af06001770d496='5fb1ba2ce1af06001770d496'
g_base_definitions[g_str_5fb1ba2ce1af06001770d496]={
  id=g_str_5fb1ba2ce1af06001770d496,
  name='Light Foot',
  min=0,
  max=1,
  description='Irish mercenaries',
  troop_type="Light Foot",
  troop_option_id="5fb1ba2ce1af06001770d495",
}
g_str_5fb1ba2ce1af06001770d497='5fb1ba2ce1af06001770d497'
g_base_definitions[g_str_5fb1ba2ce1af06001770d497]={
  id=g_str_5fb1ba2ce1af06001770d497,
  name='Javelin Cavalry',
  min=0,
  max=1,
  description='Irish mercenaries',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba2ce1af06001770d495",
}
g_str_5fb1b9e2e1af0600177098db_camp='5fb1b9e2e1af0600177098db_camp'
g_base_definitions[g_str_5fb1b9e2e1af0600177098db_camp]={
  id=g_str_5fb1b9e2e1af0600177098db_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e2e1af0600177098db_camp_pack_train='5fb1b9e2e1af0600177098db_camp_pack_train'
g_base_definitions[g_str_5fb1b9e2e1af0600177098db_camp_pack_train]={
  id=g_str_5fb1b9e2e1af0600177098db_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
