-- 5fb1b9e4e1af060017709a3d Carolingian Italy and Lombard Benevento  775 to 1076 AD

army['5fb1b9e4e1af060017709a3d']={
  data={
    name='Carolingian Italy and Lombard Benevento  775 to 1076 AD',
    id='5fb1b9e4e1af060017709a3d',
    dateRange={
      startDate=775,
      endDate=1076,
    }
  },
  g_base_definitions[g_str_5fb1ba2fe1af06001770d920_general],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d920],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d922],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d924],
  g_base_definitions[g_str_5fb1ba2fe1af06001770d926],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a3d_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a3d"] = army["5fb1b9e4e1af060017709a3d"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Carolingian Italy and Lombard Benevento  775 to 1076 AD"] = army["5fb1b9e4e1af060017709a3d"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Carolingian Italy and Lombard Benevento  775 to 1076 AD"] = army["5fb1b9e4e1af060017709a3d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Carolingian Italy and Lombard Benevento  775 to 1076 AD"] = army["5fb1b9e4e1af060017709a3d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a3d"] = {}
army_dates["5fb1b9e4e1af060017709a3d"]["775 AD to 1076 AD"] = {
  startDate=775,
  endDate=1076
}
