-- 5fb1b9dae1af06001770942a Neo-Elamite  800 to 639 BC

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba22e1af06001770c307_general='5fb1ba22e1af06001770c307_general'
g_base_definitions[g_str_5fb1ba22e1af06001770c307_general]={
  id=g_str_5fb1ba22e1af06001770c307_general,
  name='Chariots General',
  min=0,
  max=1,
  description='4-horse chariots with three crewmen',
  general=true,
  troop_type="Chariots",
  troop_option_id="5fb1ba22e1af06001770c306",
}
g_str_5fb1ba22e1af06001770c307='5fb1ba22e1af06001770c307'
g_base_definitions[g_str_5fb1ba22e1af06001770c307]={
  id=g_str_5fb1ba22e1af06001770c307,
  name='Chariots',
  min=0,
  max=1,
  description='4-horse chariots with three crewmen',
  troop_type="Chariots",
  troop_option_id="5fb1ba22e1af06001770c306",
}
g_str_5fb1ba22e1af06001770c309='5fb1ba22e1af06001770c309'
g_base_definitions[g_str_5fb1ba22e1af06001770c309]={
  id=g_str_5fb1ba22e1af06001770c309,
  name='Horse Bow',
  min=1,
  max=3,
  description='Unarmored horse archers armed with bow, long spear, and sword',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba22e1af06001770c308",
}
g_str_5fb1ba22e1af06001770c30b_general='5fb1ba22e1af06001770c30b_general'
g_base_definitions[g_str_5fb1ba22e1af06001770c30b_general]={
  id=g_str_5fb1ba22e1af06001770c30b_general,
  name='Bow Levy General',
  min=1,
  max=1,
  description='Kallapani',
  general=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c30a",
}
g_str_5fb1ba22e1af06001770c30b_general_dismounted_mobile_infantry='5fb1ba22e1af06001770c30b_general_dismounted_mobile_infantry'
g_str_5fb1ba22e1af06001770c30b_general_mounted_mobile_infantry='5fb1ba22e1af06001770c30b_general_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba22e1af06001770c30b_general_dismounted_mobile_infantry]={
  id=g_str_5fb1ba22e1af06001770c30b_general_dismounted_mobile_infantry,
  name='Bow Levy General',
  min=1,
  max=1,
  description='Kallapani\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba22e1af06001770c30b_general_mounted_mobile_infantry,
  general=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c30a",
}
g_base_definitions[g_str_5fb1ba22e1af06001770c30b_general_mounted_mobile_infantry]={
  id=g_str_5fb1ba22e1af06001770c30b_general_mounted_mobile_infantry,
  name='Bow Levy General',
  min=1,
  max=1,
  description='Kallapani\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba22e1af06001770c30b_general_dismounted_mobile_infantry,
  general=true,
  mobile_infantry=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c30a",
}
g_str_5fb1ba22e1af06001770c30b='5fb1ba22e1af06001770c30b'
g_base_definitions[g_str_5fb1ba22e1af06001770c30b]={
  id=g_str_5fb1ba22e1af06001770c30b,
  name='Bow Levy',
  min=1,
  max=6,
  description='Kallapani',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c30a",
}
g_str_5fb1ba22e1af06001770c30b_dismounted_mobile_infantry='5fb1ba22e1af06001770c30b_dismounted_mobile_infantry'
g_str_5fb1ba22e1af06001770c30b_mounted_mobile_infantry='5fb1ba22e1af06001770c30b_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba22e1af06001770c30b_dismounted_mobile_infantry]={
  id=g_str_5fb1ba22e1af06001770c30b_dismounted_mobile_infantry,
  name='Bow Levy',
  min=1,
  max=6,
  description='Kallapani\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba22e1af06001770c30b_mounted_mobile_infantry,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c30a",
}
g_base_definitions[g_str_5fb1ba22e1af06001770c30b_mounted_mobile_infantry]={
  id=g_str_5fb1ba22e1af06001770c30b_mounted_mobile_infantry,
  name='Bow Levy',
  min=1,
  max=6,
  description='Kallapani\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba22e1af06001770c30b_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c30a",
}
g_str_5fb1ba22e1af06001770c30e='5fb1ba22e1af06001770c30e'
g_base_definitions[g_str_5fb1ba22e1af06001770c30e]={
  id=g_str_5fb1ba22e1af06001770c30e,
  name='Light Foot',
  min=0,
  max=1,
  description='Spearmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba22e1af06001770c30d",
}
g_str_5fb1ba22e1af06001770c310='5fb1ba22e1af06001770c310'
g_base_definitions[g_str_5fb1ba22e1af06001770c310]={
  id=g_str_5fb1ba22e1af06001770c310,
  name='Archers',
  min=0,
  max=1,
  description='Shielded bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba22e1af06001770c30f",
}
g_str_5fb1ba22e1af06001770c312_general='5fb1ba22e1af06001770c312_general'
g_base_definitions[g_str_5fb1ba22e1af06001770c312_general]={
  id=g_str_5fb1ba22e1af06001770c312_general,
  name='Bow Levy General',
  min=6,
  max=1,
  description='Bowmen',
  general=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c311",
}
g_str_5fb1ba22e1af06001770c312='5fb1ba22e1af06001770c312'
g_base_definitions[g_str_5fb1ba22e1af06001770c312]={
  id=g_str_5fb1ba22e1af06001770c312,
  name='Bow Levy',
  min=6,
  max=20,
  description='Bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba22e1af06001770c311",
}
g_str_5fb1ba22e1af06001770c314='5fb1ba22e1af06001770c314'
g_base_definitions[g_str_5fb1ba22e1af06001770c314]={
  id=g_str_5fb1ba22e1af06001770c314,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba22e1af06001770c313",
}
g_str_5fb1b9dae1af06001770942a_camp='5fb1b9dae1af06001770942a_camp'
g_base_definitions[g_str_5fb1b9dae1af06001770942a_camp]={
  id=g_str_5fb1b9dae1af06001770942a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9dae1af06001770942a_camp_pack_train='5fb1b9dae1af06001770942a_camp_pack_train'
g_base_definitions[g_str_5fb1b9dae1af06001770942a_camp_pack_train]={
  id=g_str_5fb1b9dae1af06001770942a_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9dae1af06001770942a']={
  data={
    name='Neo-Elamite  800 to 639 BC'
  },
  g_base_definitions[g_str_5fb1ba22e1af06001770c307_general],
  g_base_definitions[g_str_5fb1ba22e1af06001770c307],
  g_base_definitions[g_str_5fb1ba22e1af06001770c309],
  g_base_definitions[g_str_5fb1ba22e1af06001770c30b_general],
  g_base_definitions[g_str_5fb1ba22e1af06001770c30b_general_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba22e1af06001770c30b_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba22e1af06001770c30b],
  g_base_definitions[g_str_5fb1ba22e1af06001770c30b_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba22e1af06001770c30b_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba22e1af06001770c30e],
  g_base_definitions[g_str_5fb1ba22e1af06001770c310],
  g_base_definitions[g_str_5fb1ba22e1af06001770c312_general],
  g_base_definitions[g_str_5fb1ba22e1af06001770c312],
  g_base_definitions[g_str_5fb1ba22e1af06001770c314],
  g_base_definitions[g_str_5fb1b9dae1af06001770942a_camp],
  g_base_definitions[g_str_5fb1b9dae1af06001770942a_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af06001770942a"] = army["5fb1b9dae1af06001770942a"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Neo-Elamite  800 to 639 BC"] = army["5fb1b9dae1af06001770942a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Neo-Elamite  800 to 639 BC"] = army["5fb1b9dae1af06001770942a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af06001770942a"] = {}
army_dates["5fb1b9dae1af06001770942a"]["800 BC to 639 BC"] ="5fb1b9dae1af06001770942a"
