-- 5fb1b9ede1af060017709f1b Middle Abbasid  837 to 879 AD

army['5fb1b9ede1af060017709f1b']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Delta',
      'Dry',
      'Hilly',
    },
    name='Middle Abbasid  837 to 879 AD',
    id='5fb1b9ede1af060017709f1b',
    dateRange={
      startDate=837,
      endDate=879,
    },
  },
  g_base_definitions[g_str_615351af03385c0016b87cb7_general],
  g_base_definitions[g_str_615351af03385c0016b87cb7_general_mounted],
  g_base_definitions[g_str_615351af03385c0016b87cb7_general_dismounted],
  g_base_definitions[g_str_615351af03385c0016b87cb7_general_shower_shooting],
  g_base_definitions[g_str_615351af03385c0016b87cb7],
  g_base_definitions[g_str_615351af03385c0016b87cb7_mounted],
  g_base_definitions[g_str_615351af03385c0016b87cb7_dismounted],
  g_base_definitions[g_str_615351af03385c0016b87cb7_shower_shooting],
  g_base_definitions[g_str_615351af03385c0016b87cbb],
  g_base_definitions[g_str_615351af03385c0016b87cbb_mounted],
  g_base_definitions[g_str_615351af03385c0016b87cbb_dismounted],
  g_base_definitions[g_str_615351af03385c0016b87cbe],
  g_base_definitions[g_str_615351af03385c0016b87cbe_mounted],
  g_base_definitions[g_str_615351af03385c0016b87cbe_dismounted],
  g_base_definitions[g_str_615351af03385c0016b87cc1_general],
  g_base_definitions[g_str_615351af03385c0016b87cc1],
  g_base_definitions[g_str_615351af03385c0016b87cc3],
  g_base_definitions[g_str_615351af03385c0016b87cc5],
  g_base_definitions[g_str_615351af03385c0016b87cc8],
  g_base_definitions[g_str_615351af03385c0016b87ccb],
  g_base_definitions[g_str_615351af03385c0016b87ccc],
  g_base_definitions[g_str_615351af03385c0016b87ccf],
  g_base_definitions[g_str_615351af03385c0016b87cd1],
  g_base_definitions[g_str_615351af03385c0016b87cd3],
  g_base_definitions[g_str_615351af03385c0016b87cd5],
  g_base_definitions[g_str_615351af03385c0016b87cd7],
  g_base_definitions[g_str_615351af03385c0016b87cd8],
  g_base_definitions[g_str_615351af03385c0016b87cda],
  g_base_definitions[g_str_5fb1b9ede1af060017709f1b_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f1b_camp_fortified],
  g_base_definitions[g_str_5fb1b9ede1af060017709f1b_camp_pack_train],
  g_base_definitions[g_str_5fb1b9ede1af060017709f1b_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f1b"] = army["5fb1b9ede1af060017709f1b"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Middle Abbasid  837 to 879 AD"] = army["5fb1b9ede1af060017709f1b"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Middle Abbasid  837 to 879 AD"] = army["5fb1b9ede1af060017709f1b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Middle Abbasid  837 to 879 AD"] = army["5fb1b9ede1af060017709f1b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f1b"] = {}
army_dates["5fb1b9ede1af060017709f1b"]["837 AD to 879 AD"] = {
  startDate=837,
  endDate=879
}
