troop_options['5fb1ba40e1af06001770f7d8'] = {
  min=1,
  max=3,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7db'] = {
  min=0,
  max=1,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7dd'] = {
  min=1,
  max=2,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7df'] = {
  min=0,
  max=1,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7e1'] = {
  min=2,
  max=6,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7e3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7e5'] = {
  min=0,
  max=1,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7e7'] = {
  min=1,
  max=3,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7e9'] = {
  min=1,
  max=2,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7eb'] = {
  min=0,
  max=1,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
troop_options['5fb1ba40e1af06001770f7ed'] = {
  min=0,
  max=1,
  dateRange={
    startDate=192,
    endDate=221,
  }
}
-- allies
