g_str_5fb1ba34e1af06001770e316_general='5fb1ba34e1af06001770e316_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e316_general]={
  id=g_str_5fb1ba34e1af06001770e316_general,
  name='Cataphracts General',
  min=2,
  max=1,
  description='Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba34e1af06001770e315",
}
g_str_5fb1ba34e1af06001770e316='5fb1ba34e1af06001770e316'
g_base_definitions[g_str_5fb1ba34e1af06001770e316]={
  id=g_str_5fb1ba34e1af06001770e316,
  name='Cataphracts',
  min=2,
  max=5,
  description='Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba34e1af06001770e315",
}
g_str_5fb1ba34e1af06001770e318='5fb1ba34e1af06001770e318'
g_base_definitions[g_str_5fb1ba34e1af06001770e318]={
  id=g_str_5fb1ba34e1af06001770e318,
  name='Bad Horse',
  min=0,
  max=1,
  description='Armored crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba34e1af06001770e317",
}
g_str_5fb1ba34e1af06001770e31a='5fb1ba34e1af06001770e31a'
g_base_definitions[g_str_5fb1ba34e1af06001770e31a]={
  id=g_str_5fb1ba34e1af06001770e31a,
  name='Elite Cavalry',
  min=0,
  max=1,
  description='Petronels',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba34e1af06001770e319",
}
g_str_5fb1ba34e1af06001770e31c='5fb1ba34e1af06001770e31c'
g_base_definitions[g_str_5fb1ba34e1af06001770e31c]={
  id=g_str_5fb1ba34e1af06001770e31c,
  name='Horde',
  min=0,
  max=4,
  description='Feudal retainers or heerban',
  troop_type="Horde",
  troop_option_id="5fb1ba34e1af06001770e31b",
}
g_str_5fb1ba34e1af06001770e31e='5fb1ba34e1af06001770e31e'
g_base_definitions[g_str_5fb1ba34e1af06001770e31e]={
  id=g_str_5fb1ba34e1af06001770e31e,
  name='Bow Levy',
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e31d",
}
g_str_5fb1ba34e1af06001770e320='5fb1ba34e1af06001770e320'
g_base_definitions[g_str_5fb1ba34e1af06001770e320]={
  id=g_str_5fb1ba34e1af06001770e320,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e31f",
}
g_str_5fb1ba34e1af06001770e323='5fb1ba34e1af06001770e323'
g_base_definitions[g_str_5fb1ba34e1af06001770e323]={
  id=g_str_5fb1ba34e1af06001770e323,
  name='Archers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen or handgunners',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e322",
}
g_str_5fb1ba34e1af06001770e324='5fb1ba34e1af06001770e324'
g_base_definitions[g_str_5fb1ba34e1af06001770e324]={
  id=g_str_5fb1ba34e1af06001770e324,
  name='Skirmishers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen or handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e322",
}
g_str_5fb1ba34e1af06001770e327='5fb1ba34e1af06001770e327'
g_base_definitions[g_str_5fb1ba34e1af06001770e327]={
  id=g_str_5fb1ba34e1af06001770e327,
  name='Bow Levy',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e326",
}
g_str_5fb1ba34e1af06001770e328='5fb1ba34e1af06001770e328'
g_base_definitions[g_str_5fb1ba34e1af06001770e328]={
  id=g_str_5fb1ba34e1af06001770e328,
  name='Archers',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e326",
}
g_str_5fb1ba34e1af06001770e32a='5fb1ba34e1af06001770e32a'
g_base_definitions[g_str_5fb1ba34e1af06001770e32a]={
  id=g_str_5fb1ba34e1af06001770e32a,
  name='Heavy Foot',
  min=0,
  max=2,
  description='City militia spearmen or pikemen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e329",
}
g_str_5fb1ba34e1af06001770e32d='5fb1ba34e1af06001770e32d'
g_base_definitions[g_str_5fb1ba34e1af06001770e32d]={
  id=g_str_5fb1ba34e1af06001770e32d,
  name='Skirmishers',
  min=0,
  max=1,
  description='City militia skirmishing bowmen or handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e32c",
}
g_str_5fb1ba34e1af06001770e330='5fb1ba34e1af06001770e330'
g_base_definitions[g_str_5fb1ba34e1af06001770e330]={
  id=g_str_5fb1ba34e1af06001770e330,
  name='Pikes',
  min=0,
  max=4,
  description='Mercenary pikemen',
  troop_type="Pikes",
  troop_option_id="5fb1ba34e1af06001770e32f",
}
g_str_5fb1ba34e1af06001770e332='5fb1ba34e1af06001770e332'
g_base_definitions[g_str_5fb1ba34e1af06001770e332]={
  id=g_str_5fb1ba34e1af06001770e332,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba34e1af06001770e331",
}
g_str_5fb1b9e9e1af060017709cf0_camp='5fb1b9e9e1af060017709cf0_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp]={
  id=g_str_5fb1b9e9e1af060017709cf0_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709cf0_camp_fortified='5fb1b9e9e1af060017709cf0_camp_fortified'
g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp_fortified]={
  id=g_str_5fb1b9e9e1af060017709cf0_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba12e1af06001770b276='5fb1ba12e1af06001770b276'
g_base_definitions[g_str_5fb1ba12e1af06001770b276]={
  id=g_str_5fb1ba12e1af06001770b276,
  name='Knights',
  min=1,
  max=1,
  description='Ordonnance gendarmes and their coustilliers',
  troop_type="Knights",
  troop_option_id="5fb1ba12e1af06001770b275",
}
g_str_5fb1ba12e1af06001770b278='5fb1ba12e1af06001770b278'
g_base_definitions[g_str_5fb1ba12e1af06001770b278]={
  id=g_str_5fb1ba12e1af06001770b278,
  name='Artillery',
  min=0,
  max=1,
  description='Organ guns, bombards, and various other pieces',
  troop_type="Artillery",
  troop_option_id="5fb1ba12e1af06001770b277",
}
g_str_5fb1ba12e1af06001770b27a='5fb1ba12e1af06001770b27a'
g_base_definitions[g_str_5fb1ba12e1af06001770b27a]={
  id=g_str_5fb1ba12e1af06001770b27a,
  name='Archers',
  min=1,
  max=1,
  description='Ordonnance longbowmen and crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba12e1af06001770b279",
}
g_str_5fb1ba12e1af06001770b27c='5fb1ba12e1af06001770b27c'
g_base_definitions[g_str_5fb1ba12e1af06001770b27c]={
  id=g_str_5fb1ba12e1af06001770b27c,
  name='Pikes',
  min=2,
  max=4,
  description='Low Countries militia pikemen',
  troop_type="Pikes",
  troop_option_id="5fb1ba12e1af06001770b27b",
}
g_str_5fb1ba12e1af06001770b27e='5fb1ba12e1af06001770b27e'
g_base_definitions[g_str_5fb1ba12e1af06001770b27e]={
  id=g_str_5fb1ba12e1af06001770b27e,
  name='Skirmishers',
  min=0,
  max=1,
  description='Militia or mercenary handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba12e1af06001770b27d",
}
g_str_5fb1ba34e1af06001770e316_general='5fb1ba34e1af06001770e316_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e316_general]={
  id=g_str_5fb1ba34e1af06001770e316_general,
  name='Cataphracts General',
  min=2,
  max=1,
  description='Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba34e1af06001770e315",
}
g_str_5fb1ba34e1af06001770e316='5fb1ba34e1af06001770e316'
g_base_definitions[g_str_5fb1ba34e1af06001770e316]={
  id=g_str_5fb1ba34e1af06001770e316,
  name='Cataphracts',
  min=2,
  max=5,
  description='Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba34e1af06001770e315",
}
g_str_5fb1ba34e1af06001770e318='5fb1ba34e1af06001770e318'
g_base_definitions[g_str_5fb1ba34e1af06001770e318]={
  id=g_str_5fb1ba34e1af06001770e318,
  name='Bad Horse',
  min=0,
  max=1,
  description='Armored crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba34e1af06001770e317",
}
g_str_5fb1ba34e1af06001770e31a='5fb1ba34e1af06001770e31a'
g_base_definitions[g_str_5fb1ba34e1af06001770e31a]={
  id=g_str_5fb1ba34e1af06001770e31a,
  name='Elite Cavalry',
  min=0,
  max=1,
  description='Petronels',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba34e1af06001770e319",
}
g_str_5fb1ba34e1af06001770e31c='5fb1ba34e1af06001770e31c'
g_base_definitions[g_str_5fb1ba34e1af06001770e31c]={
  id=g_str_5fb1ba34e1af06001770e31c,
  name='Horde',
  min=0,
  max=4,
  description='Feudal retainers or heerban',
  troop_type="Horde",
  troop_option_id="5fb1ba34e1af06001770e31b",
}
g_str_5fb1ba34e1af06001770e31e='5fb1ba34e1af06001770e31e'
g_base_definitions[g_str_5fb1ba34e1af06001770e31e]={
  id=g_str_5fb1ba34e1af06001770e31e,
  name='Bow Levy',
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e31d",
}
g_str_5fb1ba34e1af06001770e320='5fb1ba34e1af06001770e320'
g_base_definitions[g_str_5fb1ba34e1af06001770e320]={
  id=g_str_5fb1ba34e1af06001770e320,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e31f",
}
g_str_5fb1ba34e1af06001770e323='5fb1ba34e1af06001770e323'
g_base_definitions[g_str_5fb1ba34e1af06001770e323]={
  id=g_str_5fb1ba34e1af06001770e323,
  name='Archers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen or handgunners',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e322",
}
g_str_5fb1ba34e1af06001770e324='5fb1ba34e1af06001770e324'
g_base_definitions[g_str_5fb1ba34e1af06001770e324]={
  id=g_str_5fb1ba34e1af06001770e324,
  name='Skirmishers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen or handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e322",
}
g_str_5fb1ba34e1af06001770e327='5fb1ba34e1af06001770e327'
g_base_definitions[g_str_5fb1ba34e1af06001770e327]={
  id=g_str_5fb1ba34e1af06001770e327,
  name='Bow Levy',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e326",
}
g_str_5fb1ba34e1af06001770e328='5fb1ba34e1af06001770e328'
g_base_definitions[g_str_5fb1ba34e1af06001770e328]={
  id=g_str_5fb1ba34e1af06001770e328,
  name='Archers',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e326",
}
g_str_5fb1ba34e1af06001770e32a='5fb1ba34e1af06001770e32a'
g_base_definitions[g_str_5fb1ba34e1af06001770e32a]={
  id=g_str_5fb1ba34e1af06001770e32a,
  name='Heavy Foot',
  min=0,
  max=2,
  description='City militia spearmen or pikemen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e329",
}
g_str_5fb1ba34e1af06001770e32d='5fb1ba34e1af06001770e32d'
g_base_definitions[g_str_5fb1ba34e1af06001770e32d]={
  id=g_str_5fb1ba34e1af06001770e32d,
  name='Skirmishers',
  min=0,
  max=1,
  description='City militia skirmishing bowmen or handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e32c",
}
g_str_5fb1ba34e1af06001770e330='5fb1ba34e1af06001770e330'
g_base_definitions[g_str_5fb1ba34e1af06001770e330]={
  id=g_str_5fb1ba34e1af06001770e330,
  name='Pikes',
  min=0,
  max=4,
  description='Mercenary pikemen',
  troop_type="Pikes",
  troop_option_id="5fb1ba34e1af06001770e32f",
}
g_str_5fb1ba34e1af06001770e332='5fb1ba34e1af06001770e332'
g_base_definitions[g_str_5fb1ba34e1af06001770e332]={
  id=g_str_5fb1ba34e1af06001770e332,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba34e1af06001770e331",
}
g_str_5fb1b9e9e1af060017709cf0_camp='5fb1b9e9e1af060017709cf0_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp]={
  id=g_str_5fb1b9e9e1af060017709cf0_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709cf0_camp_fortified='5fb1b9e9e1af060017709cf0_camp_fortified'
g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp_fortified]={
  id=g_str_5fb1b9e9e1af060017709cf0_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba12e1af06001770b276='5fb1ba12e1af06001770b276'
g_base_definitions[g_str_5fb1ba12e1af06001770b276]={
  id=g_str_5fb1ba12e1af06001770b276,
  name='Knights',
  min=1,
  max=1,
  description='Ordonnance gendarmes and their coustilliers',
  troop_type="Knights",
  troop_option_id="5fb1ba12e1af06001770b275",
}
g_str_5fb1ba12e1af06001770b278='5fb1ba12e1af06001770b278'
g_base_definitions[g_str_5fb1ba12e1af06001770b278]={
  id=g_str_5fb1ba12e1af06001770b278,
  name='Artillery',
  min=0,
  max=1,
  description='Organ guns, bombards, and various other pieces',
  troop_type="Artillery",
  troop_option_id="5fb1ba12e1af06001770b277",
}
g_str_5fb1ba12e1af06001770b27a='5fb1ba12e1af06001770b27a'
g_base_definitions[g_str_5fb1ba12e1af06001770b27a]={
  id=g_str_5fb1ba12e1af06001770b27a,
  name='Archers',
  min=1,
  max=1,
  description='Ordonnance longbowmen and crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba12e1af06001770b279",
}
g_str_5fb1ba12e1af06001770b27c='5fb1ba12e1af06001770b27c'
g_base_definitions[g_str_5fb1ba12e1af06001770b27c]={
  id=g_str_5fb1ba12e1af06001770b27c,
  name='Pikes',
  min=2,
  max=4,
  description='Low Countries militia pikemen',
  troop_type="Pikes",
  troop_option_id="5fb1ba12e1af06001770b27b",
}
g_str_5fb1ba12e1af06001770b27e='5fb1ba12e1af06001770b27e'
g_base_definitions[g_str_5fb1ba12e1af06001770b27e]={
  id=g_str_5fb1ba12e1af06001770b27e,
  name='Skirmishers',
  min=0,
  max=1,
  description='Militia or mercenary handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba12e1af06001770b27d",
}
g_str_5fb1ba34e1af06001770e316_general='5fb1ba34e1af06001770e316_general'
g_base_definitions[g_str_5fb1ba34e1af06001770e316_general]={
  id=g_str_5fb1ba34e1af06001770e316_general,
  name='Cataphracts General',
  min=2,
  max=1,
  description='Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks',
  general=true,
  troop_type="Cataphracts",
  troop_option_id="5fb1ba34e1af06001770e315",
}
g_str_5fb1ba34e1af06001770e316='5fb1ba34e1af06001770e316'
g_base_definitions[g_str_5fb1ba34e1af06001770e316]={
  id=g_str_5fb1ba34e1af06001770e316,
  name='Cataphracts',
  min=2,
  max=5,
  description='Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks',
  troop_type="Cataphracts",
  troop_option_id="5fb1ba34e1af06001770e315",
}
g_str_5fb1ba34e1af06001770e318='5fb1ba34e1af06001770e318'
g_base_definitions[g_str_5fb1ba34e1af06001770e318]={
  id=g_str_5fb1ba34e1af06001770e318,
  name='Bad Horse',
  min=0,
  max=1,
  description='Armored crossbowmen on horses',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba34e1af06001770e317",
}
g_str_5fb1ba34e1af06001770e31a='5fb1ba34e1af06001770e31a'
g_base_definitions[g_str_5fb1ba34e1af06001770e31a]={
  id=g_str_5fb1ba34e1af06001770e31a,
  name='Elite Cavalry',
  min=0,
  max=1,
  description='Petronels',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba34e1af06001770e319",
}
g_str_5fb1ba34e1af06001770e31c='5fb1ba34e1af06001770e31c'
g_base_definitions[g_str_5fb1ba34e1af06001770e31c]={
  id=g_str_5fb1ba34e1af06001770e31c,
  name='Horde',
  min=0,
  max=4,
  description='Feudal retainers or heerban',
  troop_type="Horde",
  troop_option_id="5fb1ba34e1af06001770e31b",
}
g_str_5fb1ba34e1af06001770e31e='5fb1ba34e1af06001770e31e'
g_base_definitions[g_str_5fb1ba34e1af06001770e31e]={
  id=g_str_5fb1ba34e1af06001770e31e,
  name='Bow Levy',
  min=0,
  max=2,
  description='Heerban crossbowmen or bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e31d",
}
g_str_5fb1ba34e1af06001770e320='5fb1ba34e1af06001770e320'
g_base_definitions[g_str_5fb1ba34e1af06001770e320]={
  id=g_str_5fb1ba34e1af06001770e320,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Mercenary axemen, swordsmen, and halberdiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e31f",
}
g_str_5fb1ba34e1af06001770e323='5fb1ba34e1af06001770e323'
g_base_definitions[g_str_5fb1ba34e1af06001770e323]={
  id=g_str_5fb1ba34e1af06001770e323,
  name='Archers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen or handgunners',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e322",
}
g_str_5fb1ba34e1af06001770e324='5fb1ba34e1af06001770e324'
g_base_definitions[g_str_5fb1ba34e1af06001770e324]={
  id=g_str_5fb1ba34e1af06001770e324,
  name='Skirmishers',
  min=2,
  max=4,
  description='Mercenary bowmen or crossbowmen or handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e322",
}
g_str_5fb1ba34e1af06001770e327='5fb1ba34e1af06001770e327'
g_base_definitions[g_str_5fb1ba34e1af06001770e327]={
  id=g_str_5fb1ba34e1af06001770e327,
  name='Bow Levy',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba34e1af06001770e326",
}
g_str_5fb1ba34e1af06001770e328='5fb1ba34e1af06001770e328'
g_base_definitions[g_str_5fb1ba34e1af06001770e328]={
  id=g_str_5fb1ba34e1af06001770e328,
  name='Archers',
  min=0,
  max=1,
  description='City militia crossbowmen, possibly with pavises',
  troop_type="Archers",
  troop_option_id="5fb1ba34e1af06001770e326",
}
g_str_5fb1ba34e1af06001770e32a='5fb1ba34e1af06001770e32a'
g_base_definitions[g_str_5fb1ba34e1af06001770e32a]={
  id=g_str_5fb1ba34e1af06001770e32a,
  name='Heavy Foot',
  min=0,
  max=2,
  description='City militia spearmen or pikemen',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba34e1af06001770e329",
}
g_str_5fb1ba34e1af06001770e32d='5fb1ba34e1af06001770e32d'
g_base_definitions[g_str_5fb1ba34e1af06001770e32d]={
  id=g_str_5fb1ba34e1af06001770e32d,
  name='Skirmishers',
  min=0,
  max=1,
  description='City militia skirmishing bowmen or handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba34e1af06001770e32c",
}
g_str_5fb1ba34e1af06001770e330='5fb1ba34e1af06001770e330'
g_base_definitions[g_str_5fb1ba34e1af06001770e330]={
  id=g_str_5fb1ba34e1af06001770e330,
  name='Pikes',
  min=0,
  max=4,
  description='Mercenary pikemen',
  troop_type="Pikes",
  troop_option_id="5fb1ba34e1af06001770e32f",
}
g_str_5fb1ba34e1af06001770e332='5fb1ba34e1af06001770e332'
g_base_definitions[g_str_5fb1ba34e1af06001770e332]={
  id=g_str_5fb1ba34e1af06001770e332,
  name='Artillery',
  min=0,
  max=1,
  description='Bombards',
  troop_type="Artillery",
  troop_option_id="5fb1ba34e1af06001770e331",
}
g_str_5fb1b9e9e1af060017709cf0_camp='5fb1b9e9e1af060017709cf0_camp'
g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp]={
  id=g_str_5fb1b9e9e1af060017709cf0_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e9e1af060017709cf0_camp_fortified='5fb1b9e9e1af060017709cf0_camp_fortified'
g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp_fortified]={
  id=g_str_5fb1b9e9e1af060017709cf0_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1ba12e1af06001770b276='5fb1ba12e1af06001770b276'
g_base_definitions[g_str_5fb1ba12e1af06001770b276]={
  id=g_str_5fb1ba12e1af06001770b276,
  name='Knights',
  min=1,
  max=1,
  description='Ordonnance gendarmes and their coustilliers',
  troop_type="Knights",
  troop_option_id="5fb1ba12e1af06001770b275",
}
g_str_5fb1ba12e1af06001770b278='5fb1ba12e1af06001770b278'
g_base_definitions[g_str_5fb1ba12e1af06001770b278]={
  id=g_str_5fb1ba12e1af06001770b278,
  name='Artillery',
  min=0,
  max=1,
  description='Organ guns, bombards, and various other pieces',
  troop_type="Artillery",
  troop_option_id="5fb1ba12e1af06001770b277",
}
g_str_5fb1ba12e1af06001770b27a='5fb1ba12e1af06001770b27a'
g_base_definitions[g_str_5fb1ba12e1af06001770b27a]={
  id=g_str_5fb1ba12e1af06001770b27a,
  name='Archers',
  min=1,
  max=1,
  description='Ordonnance longbowmen and crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba12e1af06001770b279",
}
g_str_5fb1ba12e1af06001770b27c='5fb1ba12e1af06001770b27c'
g_base_definitions[g_str_5fb1ba12e1af06001770b27c]={
  id=g_str_5fb1ba12e1af06001770b27c,
  name='Pikes',
  min=2,
  max=4,
  description='Low Countries militia pikemen',
  troop_type="Pikes",
  troop_option_id="5fb1ba12e1af06001770b27b",
}
g_str_5fb1ba12e1af06001770b27e='5fb1ba12e1af06001770b27e'
g_base_definitions[g_str_5fb1ba12e1af06001770b27e]={
  id=g_str_5fb1ba12e1af06001770b27e,
  name='Skirmishers',
  min=0,
  max=1,
  description='Militia or mercenary handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba12e1af06001770b27d",
}
