-- 5fb1b9e8e1af060017709c53 French Ordonnance  1445 to 1480 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba33e1af06001770e07f_general='5fb1ba33e1af06001770e07f_general'
g_base_definitions[g_str_5fb1ba33e1af06001770e07f_general]={
  id=g_str_5fb1ba33e1af06001770e07f_general,
  name='Knights General',
  min=2,
  max=1,
  description='Ordonnance gendarmes',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e07e",
}
g_str_5fb1ba33e1af06001770e07f_general_dismounted='5fb1ba33e1af06001770e07f_general_dismounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e07f_general_dismounted]={
  id=g_str_5fb1ba33e1af06001770e07f_general_dismounted,
  name='Elite Foot General',
  min=2,
  max=1,
  description='Ordonnance gendarmes\nDeployment dismounted from Knights General',
  points=4,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e07e",
}
g_5fb1ba33e1af06001770e07f_general_dismounted=g_base_definitions[g_str_5fb1ba33e1af06001770e07f_general_dismounted]
g_str_5fb1ba33e1af06001770e07f_general_mounted='5fb1ba33e1af06001770e07f_general_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e07f_general_mounted]={
  id=g_str_5fb1ba33e1af06001770e07f_general_mounted,
  name='Knights General',
  min=2,
  max=1,
  description='Ordonnance gendarmes\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba33e1af06001770e07f_general_dismounted,
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e07e",
}
g_str_5fb1ba33e1af06001770e07f='5fb1ba33e1af06001770e07f'
g_base_definitions[g_str_5fb1ba33e1af06001770e07f]={
  id=g_str_5fb1ba33e1af06001770e07f,
  name='Knights',
  min=2,
  max=3,
  description='Ordonnance gendarmes',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e07e",
}
g_str_5fb1ba33e1af06001770e07f_dismounted='5fb1ba33e1af06001770e07f_dismounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e07f_dismounted]={
  id=g_str_5fb1ba33e1af06001770e07f_dismounted,
  name='Elite Foot',
  min=2,
  max=3,
  description='Ordonnance gendarmes\nDeployment dismounted from Knights',
  points=4,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba33e1af06001770e07e",
}
g_5fb1ba33e1af06001770e07f_dismounted=g_base_definitions[g_str_5fb1ba33e1af06001770e07f_dismounted]
g_str_5fb1ba33e1af06001770e07f_mounted='5fb1ba33e1af06001770e07f_mounted'
g_base_definitions[g_str_5fb1ba33e1af06001770e07f_mounted]={
  id=g_str_5fb1ba33e1af06001770e07f_mounted,
  name='Knights',
  min=2,
  max=3,
  description='Ordonnance gendarmes\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba33e1af06001770e07f_dismounted,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e07e",
}
g_str_5fb1ba33e1af06001770e082='5fb1ba33e1af06001770e082'
g_base_definitions[g_str_5fb1ba33e1af06001770e082]={
  id=g_str_5fb1ba33e1af06001770e082,
  name='Archers',
  min=2,
  max=3,
  description='Ordonnance bowmen: mostly equipped with longbows, but some crossbows',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e081",
}
g_str_5fb1ba33e1af06001770e082_mounted_mobile_infantry='5fb1ba33e1af06001770e082_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e082_mounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e082_mounted_mobile_infantry,
  name='Archers',
  min=2,
  max=3,
  description='Ordonnance bowmen: mostly equipped with longbows, but some crossbows\nmounted mobile infantry',
  dismount_as=g_5fb1ba33e1af06001770e082_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e081",
}
g_str_5fb1ba33e1af06001770e082_dismounted_mobile_infantry='5fb1ba33e1af06001770e082_dismounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e082_dismounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e082_dismounted_mobile_infantry,
  name='Archers',
  min=2,
  max=3,
  description='Ordonnance bowmen: mostly equipped with longbows, but some crossbows\nDismounted mobile infantry',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e081",
}
g_str_5fb1ba33e1af06001770e085_general='5fb1ba33e1af06001770e085_general'
g_base_definitions[g_str_5fb1ba33e1af06001770e085_general]={
  id=g_str_5fb1ba33e1af06001770e085_general,
  name='Knights General',
  min=0,
  max=1,
  description='Savoyard, Italian, or Arriere-ban men-at-arms',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e084",
}
g_str_5fb1ba33e1af06001770e085='5fb1ba33e1af06001770e085'
g_base_definitions[g_str_5fb1ba33e1af06001770e085]={
  id=g_str_5fb1ba33e1af06001770e085,
  name='Knights',
  min=0,
  max=2,
  description='Savoyard, Italian, or Arriere-ban men-at-arms',
  troop_type="Knights",
  troop_option_id="5fb1ba33e1af06001770e084",
}
g_str_5fb1ba33e1af06001770e087='5fb1ba33e1af06001770e087'
g_base_definitions[g_str_5fb1ba33e1af06001770e087]={
  id=g_str_5fb1ba33e1af06001770e087,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Arriere-ban, garrison, or militia voulgiers',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba33e1af06001770e086",
}
g_str_5fb1ba33e1af06001770e087_mounted_mobile_infantry='5fb1ba33e1af06001770e087_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e087_mounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e087_mounted_mobile_infantry,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Arriere-ban, garrison, or militia voulgiers\nmounted mobile infantry',
  dismount_as=g_5fb1ba33e1af06001770e087_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba33e1af06001770e086",
}
g_str_5fb1ba33e1af06001770e087_dismounted_mobile_infantry='5fb1ba33e1af06001770e087_dismounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e087_dismounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e087_dismounted_mobile_infantry,
  name='Heavy Foot',
  min=0,
  max=2,
  description='Arriere-ban, garrison, or militia voulgiers\nDismounted mobile infantry',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba33e1af06001770e086",
}
g_str_5fb1ba33e1af06001770e08a='5fb1ba33e1af06001770e08a'
g_base_definitions[g_str_5fb1ba33e1af06001770e08a]={
  id=g_str_5fb1ba33e1af06001770e08a,
  name='Bow Levy',
  min=4,
  max=8,
  description='Francs bowmen with some arriere-ban, garrison, or militia bowmen or crossbowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e089",
}
g_str_5fb1ba33e1af06001770e08a_mounted_mobile_infantry='5fb1ba33e1af06001770e08a_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e08a_mounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e08a_mounted_mobile_infantry,
  name='Bow Levy',
  min=0,
  max=1,
  description='Francs bowmen with some arriere-ban, garrison, or militia bowmen or crossbowmen\nmounted mobile infantry',
  dismount_as=g_5fb1ba33e1af06001770e08a_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e089",
}
g_str_5fb1ba33e1af06001770e08a_dismounted_mobile_infantry='5fb1ba33e1af06001770e08a_dismounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e08a_dismounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e08a_dismounted_mobile_infantry,
  name='Bow Levy',
  min=0,
  max=1,
  description='Francs bowmen with some arriere-ban, garrison, or militia bowmen or crossbowmen\nDismounted mobile infantry',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba33e1af06001770e089",
}
g_str_5fb1ba33e1af06001770e08d='5fb1ba33e1af06001770e08d'
g_base_definitions[g_str_5fb1ba33e1af06001770e08d]={
  id=g_str_5fb1ba33e1af06001770e08d,
  name='Archers',
  min=0,
  max=1,
  description='Mercenary crossbowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e08c",
}
g_str_5fb1ba33e1af06001770e08d_mounted_mobile_infantry='5fb1ba33e1af06001770e08d_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e08d_mounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e08d_mounted_mobile_infantry,
  name='Archers',
  min=0,
  max=1,
  description='Mercenary crossbowmen\nmounted mobile infantry',
  dismount_as=g_5fb1ba33e1af06001770e08d_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e08c",
}
g_str_5fb1ba33e1af06001770e08d_dismounted_mobile_infantry='5fb1ba33e1af06001770e08d_dismounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba33e1af06001770e08d_dismounted_mobile_infantry]={
  id=g_str_5fb1ba33e1af06001770e08d_dismounted_mobile_infantry,
  name='Archers',
  min=0,
  max=1,
  description='Mercenary crossbowmen\nDismounted mobile infantry',
  troop_type="Archers",
  troop_option_id="5fb1ba33e1af06001770e08c",
}
g_str_5fb1ba33e1af06001770e090='5fb1ba33e1af06001770e090'
g_base_definitions[g_str_5fb1ba33e1af06001770e090]={
  id=g_str_5fb1ba33e1af06001770e090,
  name='Light Foot',
  min=0,
  max=1,
  description='Gascon bidets or Bretons',
  troop_type="Light Foot",
  troop_option_id="5fb1ba33e1af06001770e08f",
}
g_str_5fb1ba33e1af06001770e092='5fb1ba33e1af06001770e092'
g_base_definitions[g_str_5fb1ba33e1af06001770e092]={
  id=g_str_5fb1ba33e1af06001770e092,
  name='Skirmishers',
  min=0,
  max=1,
  description='Handgunners',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba33e1af06001770e091",
}
g_str_5fb1ba33e1af06001770e094='5fb1ba33e1af06001770e094'
g_base_definitions[g_str_5fb1ba33e1af06001770e094]={
  id=g_str_5fb1ba33e1af06001770e094,
  name='Artillery',
  min=0,
  max=2,
  description='Bombards and other big guns',
  troop_type="Artillery",
  troop_option_id="5fb1ba33e1af06001770e093",
}
g_str_5fb1b9e8e1af060017709c53_camp='5fb1b9e8e1af060017709c53_camp'
g_base_definitions[g_str_5fb1b9e8e1af060017709c53_camp]={
  id=g_str_5fb1b9e8e1af060017709c53_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
army['5fb1b9e8e1af060017709c53']={
  data={
    name='French Ordonnance  1445 to 1480 AD'
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e07f_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e07f_general_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e07f_general_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e07f],
  g_base_definitions[g_str_5fb1ba33e1af06001770e07f_mounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e07f_dismounted],
  g_base_definitions[g_str_5fb1ba33e1af06001770e082],
  g_base_definitions[g_str_5fb1ba33e1af06001770e082_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e082_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e085_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e085],
  g_base_definitions[g_str_5fb1ba33e1af06001770e087],
  g_base_definitions[g_str_5fb1ba33e1af06001770e087_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e087_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e08a],
  g_base_definitions[g_str_5fb1ba33e1af06001770e08a_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e08a_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e08d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e08d_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e08d_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e090],
  g_base_definitions[g_str_5fb1ba33e1af06001770e092],
  g_base_definitions[g_str_5fb1ba33e1af06001770e094],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c53_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c53"] = army["5fb1b9e8e1af060017709c53"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["French Ordonnance  1445 to 1480 AD"] = army["5fb1b9e8e1af060017709c53"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["French Ordonnance  1445 to 1480 AD"] = army["5fb1b9e8e1af060017709c53"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["French Ordonnance  1445 to 1480 AD"] = army["5fb1b9e8e1af060017709c53"]
