troop_options['5fb1ba3ae1af06001770ee4b'] = {
  min=2,
  max=5,
  dateRange={
    startDate=1008,
    endDate=1120,
  }
}
troop_options['5fb1ba3ae1af06001770ee4d'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1008,
    endDate=1120,
  }
}
troop_options['5fb1ba3ae1af06001770ee4f'] = {
  min=2,
  max=6,
  dateRange={
    startDate=1090,
    endDate=1120,
  }
}
troop_options['5fb1ba3ae1af06001770ee52'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1008,
    endDate=1120,
  }
}
troop_options['5fb1ba3ae1af06001770ee54'] = {
  min=1,
  max=2,
  dateRange={
    startDate=1008,
    endDate=1120,
  }
}
troop_options['5fb1ba3ae1af06001770ee56'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1008,
    endDate=1120,
  }
}
troop_options['5fb1ba3ae1af06001770ee58'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1008,
    endDate=1120,
  }
}
troop_options['5fb1ba3ae1af06001770ee5b'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1008,
    endDate=1120,
  }
}
-- allies
