-- 5fb1b9d9e1af060017709349 Ancient Libyan  3000 to 2160 BC

army['5fb1b9d9e1af060017709349']={
  data={
    name='Ancient Libyan  3000 to 2160 BC',
    id='5fb1b9d9e1af060017709349',
    dateRange={
      startDate=-3000,
      endDate=-2160,
    }
  },
  g_base_definitions[g_str_5fb1ba20e1af06001770bfbf_general],
  g_base_definitions[g_str_5fb1ba20e1af06001770bfbf],
  g_base_definitions[g_str_5fb1ba20e1af06001770bfc1_general],
  g_base_definitions[g_str_5fb1ba20e1af06001770bfc1],
  g_base_definitions[g_str_5fb1ba20e1af06001770bfc3],
  g_base_definitions[g_str_5fb1b9d9e1af060017709349_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709349_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709349"] = army["5fb1b9d9e1af060017709349"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Ancient Libyan  3000 to 2160 BC"] = army["5fb1b9d9e1af060017709349"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Ancient Libyan  3000 to 2160 BC"] = army["5fb1b9d9e1af060017709349"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709349"] = {}
army_dates["5fb1b9d9e1af060017709349"]["3000 BC to 2160 BC"] = {
  startDate=-3000,
  endDate=-2160
}
