g_str_5fb1ba44e1af06001770fecb_general='5fb1ba44e1af06001770fecb_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fecb_general]={
  id=g_str_5fb1ba44e1af06001770fecb_general,
  name='Raiders General',
  min=1,
  max=1,
  description='Noble fighters unarmoured and often naked, armed with spears, macanas and sometimes with bow',
  general=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba44e1af06001770feca",
}
g_str_5fb1ba44e1af06001770fecb='5fb1ba44e1af06001770fecb'
g_base_definitions[g_str_5fb1ba44e1af06001770fecb]={
  id=g_str_5fb1ba44e1af06001770fecb,
  name='Raiders',
  min=1,
  max=2,
  description='Noble fighters unarmoured and often naked, armed with spears, macanas and sometimes with bow',
  troop_type="Raiders",
  troop_option_id="5fb1ba44e1af06001770feca",
}
g_str_5fb1ba44e1af06001770fecc_general='5fb1ba44e1af06001770fecc_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fecc_general]={
  id=g_str_5fb1ba44e1af06001770fecc_general,
  name='Bow Levy General',
  min=1,
  max=1,
  description='Noble fighters unarmoured and often naked, armed with spears, macanas and sometimes with bow',
  general=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba44e1af06001770feca",
}
g_str_5fb1ba44e1af06001770fecc='5fb1ba44e1af06001770fecc'
g_base_definitions[g_str_5fb1ba44e1af06001770fecc]={
  id=g_str_5fb1ba44e1af06001770fecc,
  name='Bow Levy',
  min=1,
  max=2,
  description='Noble fighters unarmoured and often naked, armed with spears, macanas and sometimes with bow',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba44e1af06001770feca",
}
g_str_5fb1ba44e1af06001770fece_general='5fb1ba44e1af06001770fece_general'
g_base_definitions[g_str_5fb1ba44e1af06001770fece_general]={
  id=g_str_5fb1ba44e1af06001770fece_general,
  name='Bow Levy General',
  min=0,
  max=1,
  description='Bowmen shooting unfletched arrows',
  general=true,
  troop_type="Bow Levy",
  troop_option_id="5fb1ba44e1af06001770fecd",
}
g_str_5fb1ba44e1af06001770fece='5fb1ba44e1af06001770fece'
g_base_definitions[g_str_5fb1ba44e1af06001770fece]={
  id=g_str_5fb1ba44e1af06001770fece,
  name='Bow Levy',
  min=0,
  max=2,
  description='Bowmen shooting unfletched arrows',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba44e1af06001770fecd",
}
g_str_5fb1ba44e1af06001770fed0='5fb1ba44e1af06001770fed0'
g_base_definitions[g_str_5fb1ba44e1af06001770fed0]={
  id=g_str_5fb1ba44e1af06001770fed0,
  name='Light Foot',
  min=4,
  max=6,
  description='Light infantry armed with small spear, darts, and javelin',
  troop_type="Light Foot",
  troop_option_id="5fb1ba44e1af06001770fecf",
}
g_str_5fb1ba44e1af06001770fed2='5fb1ba44e1af06001770fed2'
g_base_definitions[g_str_5fb1ba44e1af06001770fed2]={
  id=g_str_5fb1ba44e1af06001770fed2,
  name='Rabble',
  min=9,
  max=14,
  description='Foot armed with javelins, sticks, and rocks',
  troop_type="Rabble",
  troop_option_id="5fb1ba44e1af06001770fed1",
}
g_str_5fb1b9f6e1af06001770a4aa_camp='5fb1b9f6e1af06001770a4aa_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a4aa_camp]={
  id=g_str_5fb1b9f6e1af06001770a4aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f6e1af06001770a4aa_camp_pack_train='5fb1b9f6e1af06001770a4aa_camp_pack_train'
g_base_definitions[g_str_5fb1b9f6e1af06001770a4aa_camp_pack_train]={
  id=g_str_5fb1b9f6e1af06001770a4aa_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
