-- 5fb1b9e9e1af060017709d76 Later Hungarian  1245 to 1441 AD

army['5fb1b9e9e1af060017709d76']={
  data={
    name='Later Hungarian  1245 to 1441 AD',
    id='5fb1b9e9e1af060017709d76',
    dateRange={
      startDate=1245,
      endDate=1441,
    }
  },
  g_base_definitions[g_str_5fb1ba35e1af06001770e54d_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e54d],
  g_base_definitions[g_str_5fb1ba35e1af06001770e550_general],
  g_base_definitions[g_str_5fb1ba35e1af06001770e550],
  g_base_definitions[g_str_5fb1ba35e1af06001770e552],
  g_base_definitions[g_str_5fb1ba35e1af06001770e554],
  g_base_definitions[g_str_5fb1ba35e1af06001770e557],
  g_base_definitions[g_str_5fb1ba35e1af06001770e558],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d76_camp],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d76_camp_fortified],
  g_base_definitions[g_str_5fb1ba13e1af06001770b3f5],
  g_base_definitions[g_str_5fb1ba13e1af06001770b3f6],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d76"] = army["5fb1b9e9e1af060017709d76"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Later Hungarian  1245 to 1441 AD"] = army["5fb1b9e9e1af060017709d76"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Later Hungarian  1245 to 1441 AD"] = army["5fb1b9e9e1af060017709d76"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Hungarian  1245 to 1441 AD"] = army["5fb1b9e9e1af060017709d76"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d76"] = {}
army_dates["5fb1b9e9e1af060017709d76"]["1245 AD to 1441 AD"] = {
  startDate=1245,
  endDate=1441
}
army_dates["5fb1b9e9e1af060017709d76"]["1245 AD to 1394 AD"] = {
  startDate=1245,
  endDate=1441
}
army_dates["5fb1b9e9e1af060017709d76"]["1395 AD to 1441 AD"] = {
  startDate=1245,
  endDate=1441
}
