troop_options['615351a503385c0016b85f90'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85f92'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85f94'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85f96'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85f98'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85f9a'] = {
  min=1,
  max=5,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85f9c'] = {
  min=4,
  max=6,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85f9f'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85fa2'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85fa5'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85fa7'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85fa9'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85fab'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
troop_options['615351a503385c0016b85fad'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-110,
    endDate=-47,
  }
}
-- allies
