-- 5fb1b9f3e1af06001770a2a9 Xixia (all mounted)  982 to 1227 AD

army['5fb1b9f3e1af06001770a2a9']={
  data={
    name='Xixia (all mounted)  982 to 1227 AD',
    id='5fb1b9f3e1af06001770a2a9',
    dateRange={
      startDate=982,
      endDate=1227,
    }
  },
  g_base_definitions[g_str_5fb1ba40e1af06001770f9ce],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9ce_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9ce_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_general_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_mounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d1_dismounted],
  g_base_definitions[g_str_5fb1ba40e1af06001770f9d4],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2a9"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Xixia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Xixia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Xixia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2a9"] = {}
army_dates["5fb1b9f3e1af06001770a2a9"]["982 AD to 1227 AD"] = {
  startDate=982,
  endDate=1227
}
