-- 5fb1b9e5e1af060017709abd Dark Ages Welsh  580 to 1149 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba30e1af06001770dad7_general='5fb1ba30e1af06001770dad7_general'
g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general]={
  id=g_str_5fb1ba30e1af06001770dad7_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Uchelwyr',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba30e1af06001770dad6",
}
g_str_5fb1ba30e1af06001770dad7_general_dismounted='5fb1ba30e1af06001770dad7_general_dismounted'
g_str_5fb1ba30e1af06001770dad7_general_mounted='5fb1ba30e1af06001770dad7_general_mounted'
g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_dismounted]={
  id=g_str_5fb1ba30e1af06001770dad7_general_dismounted,
  name='Elite Foot General',
  min=1,
  max=1,
  description='Uchelwyr\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  dismounted_from=g_str_5fb1ba30e1af06001770dad7_general_mounted,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba30e1af06001770dad6",
}
g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_mounted]={
  id=g_str_5fb1ba30e1af06001770dad7_general_mounted,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='Uchelwyr\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba30e1af06001770dad7_general_dismounted,
  general=true,
  deployment_dismounting=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba30e1af06001770dad6",
}
g_str_5fb1ba30e1af06001770dad7='5fb1ba30e1af06001770dad7'
g_base_definitions[g_str_5fb1ba30e1af06001770dad7]={
  id=g_str_5fb1ba30e1af06001770dad7,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Uchelwyr',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba30e1af06001770dad6",
}
g_str_5fb1ba30e1af06001770dad7_dismounted='5fb1ba30e1af06001770dad7_dismounted'
g_str_5fb1ba30e1af06001770dad7_mounted='5fb1ba30e1af06001770dad7_mounted'
g_base_definitions[g_str_5fb1ba30e1af06001770dad7_dismounted]={
  id=g_str_5fb1ba30e1af06001770dad7_dismounted,
  name='Elite Foot',
  min=1,
  max=2,
  description='Uchelwyr\nDeployment dismounted from Javelin Cavalry',
  points=4,
  dismounted_from=g_str_5fb1ba30e1af06001770dad7_mounted,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba30e1af06001770dad6",
}
g_base_definitions[g_str_5fb1ba30e1af06001770dad7_mounted]={
  id=g_str_5fb1ba30e1af06001770dad7_mounted,
  name='Javelin Cavalry',
  min=1,
  max=2,
  description='Uchelwyr\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_str_5fb1ba30e1af06001770dad7_dismounted,
  deployment_dismounting=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba30e1af06001770dad6",
}
g_str_5fb1ba30e1af06001770dada='5fb1ba30e1af06001770dada'
g_base_definitions[g_str_5fb1ba30e1af06001770dada]={
  id=g_str_5fb1ba30e1af06001770dada,
  name='Warband',
  min=8,
  max=14,
  description='Unruly spearmen',
  troop_type="Warband",
  troop_option_id="5fb1ba30e1af06001770dad9",
}
g_str_5fb1ba30e1af06001770dadc='5fb1ba30e1af06001770dadc'
g_base_definitions[g_str_5fb1ba30e1af06001770dadc]={
  id=g_str_5fb1ba30e1af06001770dadc,
  name='Rabble',
  min=1,
  max=2,
  description='Javelinmen without shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba30e1af06001770dadb",
}
g_str_5fb1ba30e1af06001770dadf='5fb1ba30e1af06001770dadf'
g_base_definitions[g_str_5fb1ba30e1af06001770dadf]={
  id=g_str_5fb1ba30e1af06001770dadf,
  name='Elite Foot',
  min=0,
  max=3,
  description='Viking mercenaries or allies',
  troop_type="Elite Foot",
  troop_option_id="5fb1ba30e1af06001770dadd",
}
g_str_5fb1ba30e1af06001770dae0='5fb1ba30e1af06001770dae0'
g_base_definitions[g_str_5fb1ba30e1af06001770dae0]={
  id=g_str_5fb1ba30e1af06001770dae0,
  name='Heavy Foot',
  min=0,
  max=3,
  description='Viking mercenaries or allies',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba30e1af06001770dadd",
}
g_str_5fb1ba30e1af06001770dae4='5fb1ba30e1af06001770dae4'
g_base_definitions[g_str_5fb1ba30e1af06001770dae4]={
  id=g_str_5fb1ba30e1af06001770dae4,
  name='Light Foot',
  min=0,
  max=4,
  description='Welsh skilled javelinmen with shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba30e1af06001770dae2",
}
g_str_5fb1ba30e1af06001770dae8='5fb1ba30e1af06001770dae8'
g_base_definitions[g_str_5fb1ba30e1af06001770dae8]={
  id=g_str_5fb1ba30e1af06001770dae8,
  name='Skirmishers',
  min=0,
  max=1,
  description='Welsh bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba30e1af06001770dae6",
}
g_str_5fb1b9e5e1af060017709abd_camp='5fb1b9e5e1af060017709abd_camp'
g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp]={
  id=g_str_5fb1b9e5e1af060017709abd_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e5e1af060017709abd_camp_pack_train='5fb1b9e5e1af060017709abd_camp_pack_train'
g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp_pack_train]={
  id=g_str_5fb1b9e5e1af060017709abd_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e5e1af060017709abd']={
  data={
    name='Dark Ages Welsh  580 to 1149 AD',
    id='5fb1b9e5e1af060017709abd',
    army_id='5fb1b9e5e1af060017709abd'
  },
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dada],
  g_base_definitions[g_str_5fb1ba30e1af06001770dadc],
  g_base_definitions[g_str_5fb1ba30e1af06001770dadf],
  g_base_definitions[g_str_5fb1ba30e1af06001770dae0],
  g_base_definitions[g_str_5fb1ba30e1af06001770dae4],
  g_base_definitions[g_str_5fb1ba30e1af06001770dae8],
  g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709abd"] = army["5fb1b9e5e1af060017709abd"]
army['5fb1b9e5e1af060017709abd_580_841']={
  data={
    name='Dark Ages Welsh 580 AD to 841 AD',
    id='5fb1b9e5e1af060017709abd_580_841',
    army_id='5fb1b9e5e1af060017709abd'
  },
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dada],
  g_base_definitions[g_str_5fb1ba30e1af06001770dadc],
  g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp_pack_train],
}
army['5fb1b9e5e1af060017709abd_842_1149']={
  data={
    name='Dark Ages Welsh 842 AD to 1149 AD',
    id='5fb1b9e5e1af060017709abd_842_1149',
    army_id='5fb1b9e5e1af060017709abd'
  },
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_general_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_mounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dad7_dismounted],
  g_base_definitions[g_str_5fb1ba30e1af06001770dada],
  g_base_definitions[g_str_5fb1ba30e1af06001770dadc],
  g_base_definitions[g_str_5fb1ba30e1af06001770dadf],
  g_base_definitions[g_str_5fb1ba30e1af06001770dae0],
  g_base_definitions[g_str_5fb1ba30e1af06001770dae4],
  g_base_definitions[g_str_5fb1ba30e1af06001770dae8],
  g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709abd_camp_pack_train],
}
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Dark Ages Welsh  580 to 1149 AD"] = army["5fb1b9e5e1af060017709abd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Dark Ages Welsh  580 to 1149 AD"] = army["5fb1b9e5e1af060017709abd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e5e1af060017709abd"] = {}
army_dates["5fb1b9e5e1af060017709abd"]["580 AD to 1149 AD"] ="5fb1b9e5e1af060017709abd"
army_dates["5fb1b9e5e1af060017709abd"]["580 AD to 841 AD"] ="5fb1b9e5e1af060017709abd_580_841"
army_dates["5fb1b9e5e1af060017709abd"]["842 AD to 1149 AD"] ="5fb1b9e5e1af060017709abd_842_1149"
