-- 5fb1b9e6e1af060017709b2a Early Hundred-Years War English  1322 to 1349 AD

army['5fb1b9e6e1af060017709b2a']={
  data={
    name='Early Hundred-Years War English  1322 to 1349 AD',
    id='5fb1b9e6e1af060017709b2a',
    army_id='5fb1b9e6e1af060017709b2a'
  },
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb3_general],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb3_general_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb3_general_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb3],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb3_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb3_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb6],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb6_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb6_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcb9],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcbb],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcbb_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcbb_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcbe],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcc0],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcc2],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcc2_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba31e1af06001770dcc2_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b2a_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b2a_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b2a"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b2a"] = {}
army_dates["5fb1b9e6e1af060017709b2a"]["1322 AD to 1349 AD"] ="5fb1b9e6e1af060017709b2a"
