troop_options['5fb1ba42e1af06001770fb94'] = {
  min=2,
  max=5,
  dateRange={
    startDate=-500,
    endDate=274,
  }
}
troop_options['5fb1ba42e1af06001770fb96'] = {
  min=2,
  max=5,
  dateRange={
    startDate=-500,
    endDate=274,
  }
}
troop_options['5fb1ba42e1af06001770fb98'] = {
  min=9,
  max=18,
  dateRange={
    startDate=-500,
    endDate=274,
  }
}
troop_options['5fb1ba42e1af06001770fb9b'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-500,
    endDate=274,
  }
}
-- allies
