-- 5fb1b9e1e1af060017709819 Second Servile War  103 to 99 BC

army['5fb1b9e1e1af060017709819']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Second Servile War  103 to 99 BC',
    id='5fb1b9e1e1af060017709819',
    dateRange={
      startDate=-103,
      endDate=-99,
    },
  },
  g_base_definitions[g_str_5fb1ba2be1af06001770d208_general],
  g_base_definitions[g_str_5fb1ba2be1af06001770d208],
  g_base_definitions[g_str_5fb1ba2be1af06001770d20a],
  g_base_definitions[g_str_5fb1ba2be1af06001770d20c],
  g_base_definitions[g_str_5fb1ba2be1af06001770d20e],
  g_base_definitions[g_str_5fb1b9e1e1af060017709819_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709819"] = army["5fb1b9e1e1af060017709819"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Second Servile War  103 to 99 BC"] = army["5fb1b9e1e1af060017709819"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Second Servile War  103 to 99 BC"] = army["5fb1b9e1e1af060017709819"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709819"] = {}
army_dates["5fb1b9e1e1af060017709819"]["103 BC to 99 BC"] = {
  startDate=-103,
  endDate=-99
}
