-- 5fb1b9e4e1af0600177099eb Slav or Wend  580 to 1218 AD

army['5fb1b9e4e1af0600177099eb']={
  data={
    invasionRatings={
      1,
    },
    homeTopographies={
      'Forest',
      'Marsh',
    },
    name='Slav or Wend  580 to 1218 AD',
    id='5fb1b9e4e1af0600177099eb',
    dateRange={
      startDate=580,
      endDate=1218,
    }
  },
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84d_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84d],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84f_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d84f],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d852],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d854],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d855],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d857],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d85a],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d85d],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp_fortified],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099eb_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af0600177099eb"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Slav or Wend  580 to 1218 AD"] = army["5fb1b9e4e1af0600177099eb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af0600177099eb"] = {}
army_dates["5fb1b9e4e1af0600177099eb"]["580 AD to 1218 AD"] = {
  startDate=580,
  endDate=1218
}
army_dates["5fb1b9e4e1af0600177099eb"]["580 AD to 740 AD"] = {
  startDate=580,
  endDate=740
}
army_dates["5fb1b9e4e1af0600177099eb"]["741 AD to 772 AD"] = {
  startDate=741,
  endDate=772
}
army_dates["5fb1b9e4e1af0600177099eb"]["773 AD to 803 AD"] = {
  startDate=773,
  endDate=803
}
army_dates["5fb1b9e4e1af0600177099eb"]["804 AD"] = {
  startDate=804,
  endDate=804
}
army_dates["5fb1b9e4e1af0600177099eb"]["805 AD to 829 AD"] = {
  startDate=805,
  endDate=829
}
army_dates["5fb1b9e4e1af0600177099eb"]["830 AD to 1056 AD"] = {
  startDate=830,
  endDate=1056
}
army_dates["5fb1b9e4e1af0600177099eb"]["1057 AD to 1218 AD"] = {
  startDate=1057,
  endDate=1218
}
