g_str_5fb1ba41e1af06001770fb73_general='5fb1ba41e1af06001770fb73_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fb73_general]={
  id=g_str_5fb1ba41e1af06001770fb73_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Chinese horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fb72",
}
g_str_5fb1ba41e1af06001770fb73='5fb1ba41e1af06001770fb73'
g_base_definitions[g_str_5fb1ba41e1af06001770fb73]={
  id=g_str_5fb1ba41e1af06001770fb73,
  name='Horse Bow',
  min=0,
  max=2,
  description='Chinese horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fb72",
}
g_str_5fb1ba41e1af06001770fb75='5fb1ba41e1af06001770fb75'
g_base_definitions[g_str_5fb1ba41e1af06001770fb75]={
  id=g_str_5fb1ba41e1af06001770fb75,
  name='Elite Cavalary',
  min=0,
  max=1,
  description='Mongol or Jurchen guard horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba41e1af06001770fb74",
}
g_str_5fb1ba41e1af06001770fb77_general='5fb1ba41e1af06001770fb77_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fb77_general]={
  id=g_str_5fb1ba41e1af06001770fb77_general,
  name='Horse Bow General',
  min=0,
  max=1,
  description='Mongol or Jurchen horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fb76",
}
g_str_5fb1ba41e1af06001770fb77='5fb1ba41e1af06001770fb77'
g_base_definitions[g_str_5fb1ba41e1af06001770fb77]={
  id=g_str_5fb1ba41e1af06001770fb77,
  name='Horse Bow',
  min=0,
  max=2,
  description='Mongol or Jurchen horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba41e1af06001770fb76",
}
g_str_5fb1ba41e1af06001770fb79_general='5fb1ba41e1af06001770fb79_general'
g_base_definitions[g_str_5fb1ba41e1af06001770fb79_general]={
  id=g_str_5fb1ba41e1af06001770fb79_general,
  name='Bad Horse General',
  min=1,
  max=1,
  description='Chinese mercenary horsemen',
  general=true,
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fb78",
}
g_str_5fb1ba41e1af06001770fb79='5fb1ba41e1af06001770fb79'
g_base_definitions[g_str_5fb1ba41e1af06001770fb79]={
  id=g_str_5fb1ba41e1af06001770fb79,
  name='Bad Horse',
  min=1,
  max=2,
  description='Chinese mercenary horsemen',
  troop_type="Bad Horse",
  troop_option_id="5fb1ba41e1af06001770fb78",
}
g_str_5fb1ba41e1af06001770fb7b='5fb1ba41e1af06001770fb7b'
g_base_definitions[g_str_5fb1ba41e1af06001770fb7b]={
  id=g_str_5fb1ba41e1af06001770fb7b,
  name='Heavy Foot',
  min=3,
  max=5,
  description='Chinese close-fighting infantry armed with mixed halberd-type weapons',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba41e1af06001770fb7a",
}
g_str_5fb1ba41e1af06001770fb7d='5fb1ba41e1af06001770fb7d'
g_base_definitions[g_str_5fb1ba41e1af06001770fb7d]={
  id=g_str_5fb1ba41e1af06001770fb7d,
  name='Archers',
  min=2,
  max=3,
  description='Chinese bowmen or crossbowmen, separate or protected behind men armed with shield and spear',
  troop_type="Archers",
  troop_option_id="5fb1ba41e1af06001770fb7c",
}
g_str_5fb1ba41e1af06001770fb7e='5fb1ba41e1af06001770fb7e'
g_base_definitions[g_str_5fb1ba41e1af06001770fb7e]={
  id=g_str_5fb1ba41e1af06001770fb7e,
  name='Pavisiers',
  min=2,
  max=3,
  description='Chinese bowmen or crossbowmen, separate or protected behind men armed with shield and spear',
  troop_type="Pavisiers",
  troop_option_id="5fb1ba41e1af06001770fb7c",
}
g_str_5fb1ba41e1af06001770fb80='5fb1ba41e1af06001770fb80'
g_base_definitions[g_str_5fb1ba41e1af06001770fb80]={
  id=g_str_5fb1ba41e1af06001770fb80,
  name='Raiders',
  min=0,
  max=1,
  description='"Dare to die" troops with halberds, swords, handguns, or fire-lances',
  troop_type="Raiders",
  troop_option_id="5fb1ba41e1af06001770fb7f",
}
g_str_5fb1ba41e1af06001770fb81='5fb1ba41e1af06001770fb81'
g_base_definitions[g_str_5fb1ba41e1af06001770fb81]={
  id=g_str_5fb1ba41e1af06001770fb81,
  name='Skirmishers',
  min=0,
  max=1,
  description='"Dare to die" troops with halberds, swords, handguns, or fire-lances',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba41e1af06001770fb7f",
}
g_str_5fb1ba41e1af06001770fb83='5fb1ba41e1af06001770fb83'
g_base_definitions[g_str_5fb1ba41e1af06001770fb83]={
  id=g_str_5fb1ba41e1af06001770fb83,
  name='Artillery',
  min=0,
  max=2,
  description='Various guns, rockets, bombards, and wheelbarrow multiple-rocket launchers',
  troop_type="Artillery",
  troop_option_id="5fb1ba41e1af06001770fb82",
}
g_str_5fb1ba42e1af06001770fb85='5fb1ba42e1af06001770fb85'
g_base_definitions[g_str_5fb1ba42e1af06001770fb85]={
  id=g_str_5fb1ba42e1af06001770fb85,
  name='Light Foot',
  min=0,
  max=2,
  description='Zhuang or similar southern tribesmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba42e1af06001770fb84",
}
g_str_5fb1ba42e1af06001770fb88='5fb1ba42e1af06001770fb88'
g_base_definitions[g_str_5fb1ba42e1af06001770fb88]={
  id=g_str_5fb1ba42e1af06001770fb88,
  name='Horde',
  min=0,
  max=4,
  description='Chinese militia',
  troop_type="Horde",
  troop_option_id="5fb1ba42e1af06001770fb86",
}
g_str_5fb1ba42e1af06001770fb8b='5fb1ba42e1af06001770fb8b'
g_base_definitions[g_str_5fb1ba42e1af06001770fb8b]={
  id=g_str_5fb1ba42e1af06001770fb8b,
  name='War Wagons',
  min=0,
  max=2,
  description='War wagons',
  troop_type="War Wagons",
  troop_option_id="5fb1ba42e1af06001770fb89",
}
g_str_5fb1b9f3e1af06001770a30a_camp='5fb1b9f3e1af06001770a30a_camp'
g_base_definitions[g_str_5fb1b9f3e1af06001770a30a_camp]={
  id=g_str_5fb1b9f3e1af06001770a30a_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
