-- 5fb1b9e6e1af060017709b57 Kanem-Bornu  900 to 1600 AD

army['5fb1b9e6e1af060017709b57']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Steppe',
    },
    name='Kanem-Bornu  900 to 1600 AD',
    id='5fb1b9e6e1af060017709b57',
    dateRange={
      startDate=900,
      endDate=1600,
    },
  },
  g_base_definitions[g_str_615351aa03385c0016b86dcc_general],
  g_base_definitions[g_str_615351aa03385c0016b86dcc],
  g_base_definitions[g_str_615351aa03385c0016b86dcf_general],
  g_base_definitions[g_str_615351aa03385c0016b86dcf],
  g_base_definitions[g_str_615351aa03385c0016b86dd2_general],
  g_base_definitions[g_str_615351aa03385c0016b86dd2],
  g_base_definitions[g_str_615351aa03385c0016b86dd3],
  g_base_definitions[g_str_615351aa03385c0016b86dd5],
  g_base_definitions[g_str_615351aa03385c0016b86dd7],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b57_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b57_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b57"] = army["5fb1b9e6e1af060017709b57"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Kanem-Bornu  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b57"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Kanem-Bornu  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b57"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b57"] = {}
army_dates["5fb1b9e6e1af060017709b57"]["900 AD to 1600 AD"] = {
  startDate=900,
  endDate=1600
}
