troop_options['615351aa03385c0016b86cc1'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1124,
    endDate=1513,
  }
}
troop_options['615351aa03385c0016b86cc3'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1124,
    endDate=1513,
  }
}
troop_options['615351aa03385c0016b86cc6'] = {
  min=8,
  max=16,
  dateRange={
    startDate=1124,
    endDate=1513,
  }
}
troop_options['615351aa03385c0016b86cc9'] = {
  min=0,
  max=3,
  dateRange={
    startDate=1124,
    endDate=1513,
  }
}
troop_options['615351aa03385c0016b86ccb'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1124,
    endDate=1513,
  }
}
troop_options['615351aa03385c0016b86ccd'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1124,
    endDate=1513,
  }
}
troop_options['615351aa03385c0016b86cd0'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1124,
    endDate=1513,
  }
}
-- allies
