troop_options['5fb1ba2fe1af06001770d8b4'] = {
  min=1,
  max=5,
  dateRange={
    startDate=853,
    endDate=1018,
  }
}
troop_options['5fb1ba2fe1af06001770d8b6'] = {
  min=3,
  max=5,
  dateRange={
    startDate=853,
    endDate=1018,
  }
}
troop_options['5fb1ba2fe1af06001770d8b8'] = {
  min=4,
  max=8,
  dateRange={
    startDate=853,
    endDate=1018,
  }
}
troop_options['5fb1ba2fe1af06001770d8ba'] = {
  min=0,
  max=2,
  dateRange={
    startDate=853,
    endDate=1018,
  }
}
-- allies
