-- 5fb1b9e7e1af060017709c3a Feudal French  1086 to 1330 AD

army['5fb1b9e7e1af060017709c3a']={
  data={
    invasionRatings={
      1,
      2,
    },
    maneuverRatings={
      0,
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Feudal French  1086 to 1330 AD',
    id='5fb1b9e7e1af060017709c3a',
    dateRange={
      startDate=1086,
      endDate=1330,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e020_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e020],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022],
  g_base_definitions[g_str_5fb1ba33e1af06001770e023],
  g_base_definitions[g_str_5fb1ba33e1af06001770e025],
  g_base_definitions[g_str_5fb1ba33e1af06001770e026],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02b],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02f],
  g_base_definitions[g_str_5fb1ba33e1af06001770e031],
  g_base_definitions[g_str_5fb1ba33e1af06001770e033],
  g_base_definitions[g_str_5fb1ba33e1af06001770e036],
  g_base_definitions[g_str_5fb1ba33e1af06001770e039],
  g_base_definitions[g_str_5fb1ba33e1af06001770e03c],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c3a"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c3a"] = {}
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1330 AD"] = {
  startDate=1086,
  endDate=1330
}
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1127 AD"] = {
  startDate=1086,
  endDate=1127
}
army_dates["5fb1b9e7e1af060017709c3a"]["1128 AD to 1149 AD"] = {
  startDate=1128,
  endDate=1149
}
army_dates["5fb1b9e7e1af060017709c3a"]["1150 AD"] = {
  startDate=1150,
  endDate=1150
}
army_dates["5fb1b9e7e1af060017709c3a"]["1151 AD to 1190 AD"] = {
  startDate=1151,
  endDate=1190
}
army_dates["5fb1b9e7e1af060017709c3a"]["1191 AD to 1221 AD"] = {
  startDate=1191,
  endDate=1221
}
army_dates["5fb1b9e7e1af060017709c3a"]["1222 AD to 1248 AD"] = {
  startDate=1222,
  endDate=1248
}
army_dates["5fb1b9e7e1af060017709c3a"]["1249 AD to 1250 AD"] = {
  startDate=1249,
  endDate=1250
}
army_dates["5fb1b9e7e1af060017709c3a"]["1251 AD to 1265 AD"] = {
  startDate=1251,
  endDate=1265
}
army_dates["5fb1b9e7e1af060017709c3a"]["1266 AD to 1303 AD"] = {
  startDate=1266,
  endDate=1303
}
army_dates["5fb1b9e7e1af060017709c3a"]["1304 AD to 1320 AD"] = {
  startDate=1304,
  endDate=1320
}
army_dates["5fb1b9e7e1af060017709c3a"]["1321 AD to 1330 AD"] = {
  startDate=1321,
  endDate=1330
}
-- 5fb1b9e7e1af060017709c3a Feudal French  1086 to 1330 AD

army['5fb1b9e7e1af060017709c3a']={
  data={
    invasionRatings={
      1,
      2,
    },
    maneuverRatings={
      0,
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Feudal French  1086 to 1330 AD',
    id='5fb1b9e7e1af060017709c3a',
    dateRange={
      startDate=1086,
      endDate=1330,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e020_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e020],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022],
  g_base_definitions[g_str_5fb1ba33e1af06001770e023],
  g_base_definitions[g_str_5fb1ba33e1af06001770e025],
  g_base_definitions[g_str_5fb1ba33e1af06001770e026],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02b],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02f],
  g_base_definitions[g_str_5fb1ba33e1af06001770e031],
  g_base_definitions[g_str_5fb1ba33e1af06001770e033],
  g_base_definitions[g_str_5fb1ba33e1af06001770e036],
  g_base_definitions[g_str_5fb1ba33e1af06001770e039],
  g_base_definitions[g_str_5fb1ba33e1af06001770e03c],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c3a"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c3a"] = {}
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1330 AD"] = {
  startDate=1086,
  endDate=1330
}
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1127 AD"] = {
  startDate=1086,
  endDate=1127
}
army_dates["5fb1b9e7e1af060017709c3a"]["1128 AD to 1149 AD"] = {
  startDate=1128,
  endDate=1149
}
army_dates["5fb1b9e7e1af060017709c3a"]["1150 AD"] = {
  startDate=1150,
  endDate=1150
}
army_dates["5fb1b9e7e1af060017709c3a"]["1151 AD to 1190 AD"] = {
  startDate=1151,
  endDate=1190
}
army_dates["5fb1b9e7e1af060017709c3a"]["1191 AD to 1221 AD"] = {
  startDate=1191,
  endDate=1221
}
army_dates["5fb1b9e7e1af060017709c3a"]["1222 AD to 1248 AD"] = {
  startDate=1222,
  endDate=1248
}
army_dates["5fb1b9e7e1af060017709c3a"]["1249 AD to 1250 AD"] = {
  startDate=1249,
  endDate=1250
}
army_dates["5fb1b9e7e1af060017709c3a"]["1251 AD to 1265 AD"] = {
  startDate=1251,
  endDate=1265
}
army_dates["5fb1b9e7e1af060017709c3a"]["1266 AD to 1303 AD"] = {
  startDate=1266,
  endDate=1303
}
army_dates["5fb1b9e7e1af060017709c3a"]["1304 AD to 1320 AD"] = {
  startDate=1304,
  endDate=1320
}
army_dates["5fb1b9e7e1af060017709c3a"]["1321 AD to 1330 AD"] = {
  startDate=1321,
  endDate=1330
}
-- 5fb1b9e7e1af060017709c3a Feudal French  1086 to 1330 AD

army['5fb1b9e7e1af060017709c3a']={
  data={
    invasionRatings={
      1,
      2,
    },
    maneuverRatings={
      0,
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Feudal French  1086 to 1330 AD',
    id='5fb1b9e7e1af060017709c3a',
    dateRange={
      startDate=1086,
      endDate=1330,
    }
  },
  g_base_definitions[g_str_5fb1ba33e1af06001770e020_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e020],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022_general],
  g_base_definitions[g_str_5fb1ba33e1af06001770e022],
  g_base_definitions[g_str_5fb1ba33e1af06001770e023],
  g_base_definitions[g_str_5fb1ba33e1af06001770e025],
  g_base_definitions[g_str_5fb1ba33e1af06001770e026],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e028_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02b],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02d],
  g_base_definitions[g_str_5fb1ba33e1af06001770e02f],
  g_base_definitions[g_str_5fb1ba33e1af06001770e031],
  g_base_definitions[g_str_5fb1ba33e1af06001770e033],
  g_base_definitions[g_str_5fb1ba33e1af06001770e036],
  g_base_definitions[g_str_5fb1ba33e1af06001770e039],
  g_base_definitions[g_str_5fb1ba33e1af06001770e03c],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c3a_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c3a"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Feudal French  1086 to 1330 AD"] = army["5fb1b9e7e1af060017709c3a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c3a"] = {}
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1330 AD"] = {
  startDate=1086,
  endDate=1330
}
army_dates["5fb1b9e7e1af060017709c3a"]["1086 AD to 1127 AD"] = {
  startDate=1086,
  endDate=1127
}
army_dates["5fb1b9e7e1af060017709c3a"]["1128 AD to 1149 AD"] = {
  startDate=1128,
  endDate=1149
}
army_dates["5fb1b9e7e1af060017709c3a"]["1150 AD"] = {
  startDate=1150,
  endDate=1150
}
army_dates["5fb1b9e7e1af060017709c3a"]["1151 AD to 1190 AD"] = {
  startDate=1151,
  endDate=1190
}
army_dates["5fb1b9e7e1af060017709c3a"]["1191 AD to 1221 AD"] = {
  startDate=1191,
  endDate=1221
}
army_dates["5fb1b9e7e1af060017709c3a"]["1222 AD to 1248 AD"] = {
  startDate=1222,
  endDate=1248
}
army_dates["5fb1b9e7e1af060017709c3a"]["1249 AD to 1250 AD"] = {
  startDate=1249,
  endDate=1250
}
army_dates["5fb1b9e7e1af060017709c3a"]["1251 AD to 1265 AD"] = {
  startDate=1251,
  endDate=1265
}
army_dates["5fb1b9e7e1af060017709c3a"]["1266 AD to 1303 AD"] = {
  startDate=1266,
  endDate=1303
}
army_dates["5fb1b9e7e1af060017709c3a"]["1304 AD to 1320 AD"] = {
  startDate=1304,
  endDate=1320
}
army_dates["5fb1b9e7e1af060017709c3a"]["1321 AD to 1330 AD"] = {
  startDate=1321,
  endDate=1330
}
