-- 5fb1b9f5e1af06001770a3b1 Middle Horizon Period Maya  601 to 987 AD

army['5fb1b9f5e1af06001770a3b1']={
  data={
    name='Middle Horizon Period Maya  601 to 987 AD',
    id='5fb1b9f5e1af06001770a3b1',
    army_id='5fb1b9f5e1af06001770a3b1'
  },
  g_base_definitions[g_str_5fb1ba43e1af06001770fd35_general],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd35],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd37],
  g_base_definitions[g_str_5fb1ba43e1af06001770fd39],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3b1_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3b1"] = army["5fb1b9f5e1af06001770a3b1"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Middle Horizon Period Maya  601 to 987 AD"] = army["5fb1b9f5e1af06001770a3b1"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Middle Horizon Period Maya  601 to 987 AD"] = army["5fb1b9f5e1af06001770a3b1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Middle Horizon Period Maya  601 to 987 AD"] = army["5fb1b9f5e1af06001770a3b1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3b1"] = {}
army_dates["5fb1b9f5e1af06001770a3b1"]["601 AD to 987 AD"] ="5fb1b9f5e1af06001770a3b1"
