-- 5fb1b9e6e1af060017709b1c North Welsh  1150 to 1420 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba31e1af06001770dc6c_general='5fb1ba31e1af06001770dc6c_general'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_general]={
  id=g_str_5fb1ba31e1af06001770dc6c_general,
  name='Knights General',
  min=0,
  max=1,
  description='North Welsh highborn',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba31e1af06001770dc6b",
}
g_str_5fb1ba31e1af06001770dc6c_general_dismounted='5fb1ba31e1af06001770dc6c_general_dismounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_general_dismounted]={
  id=g_str_5fb1ba31e1af06001770dc6c_general_dismounted,
  name='Elite Foot General',
  min=0,
  max=1,
  description='North Welsh highborn\nDeployment dismounted from Knights General',
  points=4,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba31e1af06001770dc6b",
}
g_5fb1ba31e1af06001770dc6c_general_dismounted=g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_general_dismounted]
g_str_5fb1ba31e1af06001770dc6c_general_mounted='5fb1ba31e1af06001770dc6c_general_mounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_general_mounted]={
  id=g_str_5fb1ba31e1af06001770dc6c_general_mounted,
  name='Knights General',
  min=0,
  max=1,
  description='North Welsh highborn\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba31e1af06001770dc6c_general_dismounted,
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba31e1af06001770dc6b",
}
g_str_5fb1ba31e1af06001770dc6c='5fb1ba31e1af06001770dc6c'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6c]={
  id=g_str_5fb1ba31e1af06001770dc6c,
  name='Knights',
  min=0,
  max=1,
  description='North Welsh highborn',
  troop_type="Knights",
  troop_option_id="5fb1ba31e1af06001770dc6b",
}
g_str_5fb1ba31e1af06001770dc6c_dismounted='5fb1ba31e1af06001770dc6c_dismounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_dismounted]={
  id=g_str_5fb1ba31e1af06001770dc6c_dismounted,
  name='Elite Foot',
  min=0,
  max=1,
  description='North Welsh highborn\nDeployment dismounted from Knights',
  points=4,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba31e1af06001770dc6b",
}
g_5fb1ba31e1af06001770dc6c_dismounted=g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_dismounted]
g_str_5fb1ba31e1af06001770dc6c_mounted='5fb1ba31e1af06001770dc6c_mounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_mounted]={
  id=g_str_5fb1ba31e1af06001770dc6c_mounted,
  name='Knights',
  min=0,
  max=1,
  description='North Welsh highborn\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba31e1af06001770dc6c_dismounted,
  troop_type="Knights",
  troop_option_id="5fb1ba31e1af06001770dc6b",
}
g_str_5fb1ba31e1af06001770dc6f_general='5fb1ba31e1af06001770dc6f_general'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_general]={
  id=g_str_5fb1ba31e1af06001770dc6f_general,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='North Welsh uchelwyr',
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dc6e",
}
g_str_5fb1ba31e1af06001770dc6f_general_dismounted='5fb1ba31e1af06001770dc6f_general_dismounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_general_dismounted]={
  id=g_str_5fb1ba31e1af06001770dc6f_general_dismounted,
  name='Elite Foot General',
  min=1,
  max=1,
  description='North Welsh uchelwyr\nDeployment dismounted from Javelin Cavalry General',
  points=4,
  general=true,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba31e1af06001770dc6e",
}
g_5fb1ba31e1af06001770dc6f_general_dismounted=g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_general_dismounted]
g_str_5fb1ba31e1af06001770dc6f_general_mounted='5fb1ba31e1af06001770dc6f_general_mounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_general_mounted]={
  id=g_str_5fb1ba31e1af06001770dc6f_general_mounted,
  name='Javelin Cavalry General',
  min=1,
  max=1,
  description='North Welsh uchelwyr\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba31e1af06001770dc6f_general_dismounted,
  general=true,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dc6e",
}
g_str_5fb1ba31e1af06001770dc6f='5fb1ba31e1af06001770dc6f'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6f]={
  id=g_str_5fb1ba31e1af06001770dc6f,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='North Welsh uchelwyr',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dc6e",
}
g_str_5fb1ba31e1af06001770dc6f_dismounted='5fb1ba31e1af06001770dc6f_dismounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_dismounted]={
  id=g_str_5fb1ba31e1af06001770dc6f_dismounted,
  name='Elite Foot',
  min=1,
  max=1,
  description='North Welsh uchelwyr\nDeployment dismounted from Javelin Cavalry',
  points=4,
  troop_type="Elite Foot",
  troop_option_id="5fb1ba31e1af06001770dc6e",
}
g_5fb1ba31e1af06001770dc6f_dismounted=g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_dismounted]
g_str_5fb1ba31e1af06001770dc6f_mounted='5fb1ba31e1af06001770dc6f_mounted'
g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_mounted]={
  id=g_str_5fb1ba31e1af06001770dc6f_mounted,
  name='Javelin Cavalry',
  min=1,
  max=1,
  description='North Welsh uchelwyr\nDeployment dismounting as Elite Foot',
  points=4,
  dismount_as=g_5fb1ba31e1af06001770dc6f_dismounted,
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba31e1af06001770dc6e",
}
g_str_5fb1ba31e1af06001770dc72='5fb1ba31e1af06001770dc72'
g_base_definitions[g_str_5fb1ba31e1af06001770dc72]={
  id=g_str_5fb1ba31e1af06001770dc72,
  name='Light Spear',
  min=5,
  max=14,
  description='North Welsh spearmen',
  troop_type="Light Spear",
  troop_option_id="5fb1ba31e1af06001770dc71",
}
g_str_5fb1ba31e1af06001770dc74='5fb1ba31e1af06001770dc74'
g_base_definitions[g_str_5fb1ba31e1af06001770dc74]={
  id=g_str_5fb1ba31e1af06001770dc74,
  name='Archers',
  min=0,
  max=1,
  description='North Welsh bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba31e1af06001770dc73",
}
g_str_5fb1ba31e1af06001770dc76='5fb1ba31e1af06001770dc76'
g_base_definitions[g_str_5fb1ba31e1af06001770dc76]={
  id=g_str_5fb1ba31e1af06001770dc76,
  name='Rabble',
  min=1,
  max=2,
  description='North Welsh javelinmen',
  troop_type="Rabble",
  troop_option_id="5fb1ba31e1af06001770dc75",
}
g_str_5fb1b9e6e1af060017709b1c_camp='5fb1b9e6e1af060017709b1c_camp'
g_base_definitions[g_str_5fb1b9e6e1af060017709b1c_camp]={
  id=g_str_5fb1b9e6e1af060017709b1c_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e6e1af060017709b1c_camp_pack_train='5fb1b9e6e1af060017709b1c_camp_pack_train'
g_base_definitions[g_str_5fb1b9e6e1af060017709b1c_camp_pack_train]={
  id=g_str_5fb1b9e6e1af060017709b1c_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9e6e1af060017709b1c']={
  data={
    name='North Welsh  1150 to 1420 AD'
  },
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_general],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_general_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_general_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6c],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6c_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_general],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_general_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_general_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6f],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_mounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc6f_dismounted],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc72],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc74],
  g_base_definitions[g_str_5fb1ba31e1af06001770dc76],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b1c_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b1c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b1c"] = army["5fb1b9e6e1af060017709b1c"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["North Welsh  1150 to 1420 AD"] = army["5fb1b9e6e1af060017709b1c"]
