troop_options['5fb1ba44e1af06001770fe1c'] = {
  min=0,
  max=1,
  dateRange={
    startDate=1100,
    endDate=1701,
  }
}
troop_options['5fb1ba44e1af06001770fe1e'] = {
  min=1,
  max=3,
  dateRange={
    startDate=1100,
    endDate=1701,
  }
}
troop_options['5fb1ba44e1af06001770fe20'] = {
  min=7,
  max=20,
  dateRange={
    startDate=1100,
    endDate=1701,
  }
}
troop_options['5fb1ba44e1af06001770fe22'] = {
  min=0,
  max=4,
  dateRange={
    startDate=1100,
    endDate=1701,
  }
}
troop_options['5fb1ba44e1af06001770fe24'] = {
  min=3,
  max=6,
  dateRange={
    startDate=1100,
    endDate=1701,
  }
}
-- allies
