g_str_5fb1ba43e1af06001770fd2c_general='5fb1ba43e1af06001770fd2c_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c_general]={
  id=g_str_5fb1ba43e1af06001770fd2c_general,
  name='Light Foot General',
  min=2,
  max=1,
  description='Nobles and elite infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2c='5fb1ba43e1af06001770fd2c'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c]={
  id=g_str_5fb1ba43e1af06001770fd2c,
  name='Light Foot',
  min=2,
  max=6,
  description='Nobles and elite infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2e_general='5fb1ba43e1af06001770fd2e_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e_general]={
  id=g_str_5fb1ba43e1af06001770fd2e_general,
  name='Light Foot General',
  min=12,
  max=1,
  description='Commoners, some carrying roll-up shields',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2e='5fb1ba43e1af06001770fd2e'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e]={
  id=g_str_5fb1ba43e1af06001770fd2e,
  name='Light Foot',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2f='5fb1ba43e1af06001770fd2f'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2f]={
  id=g_str_5fb1ba43e1af06001770fd2f,
  name='Rabble',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd31='5fb1ba43e1af06001770fd31'
g_base_definitions[g_str_5fb1ba43e1af06001770fd31]={
  id=g_str_5fb1ba43e1af06001770fd31,
  name='Skirmishers',
  min=0,
  max=4,
  description='Peasant skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd30",
}
g_str_5fb1b9f5e1af06001770a3aa_camp='5fb1b9f5e1af06001770a3aa_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3aa_camp]={
  id=g_str_5fb1b9f5e1af06001770a3aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba43e1af06001770fd2c_general='5fb1ba43e1af06001770fd2c_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c_general]={
  id=g_str_5fb1ba43e1af06001770fd2c_general,
  name='Light Foot General',
  min=2,
  max=1,
  description='Nobles and elite infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2c='5fb1ba43e1af06001770fd2c'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c]={
  id=g_str_5fb1ba43e1af06001770fd2c,
  name='Light Foot',
  min=2,
  max=6,
  description='Nobles and elite infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2e_general='5fb1ba43e1af06001770fd2e_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e_general]={
  id=g_str_5fb1ba43e1af06001770fd2e_general,
  name='Light Foot General',
  min=12,
  max=1,
  description='Commoners, some carrying roll-up shields',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2e='5fb1ba43e1af06001770fd2e'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e]={
  id=g_str_5fb1ba43e1af06001770fd2e,
  name='Light Foot',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2f='5fb1ba43e1af06001770fd2f'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2f]={
  id=g_str_5fb1ba43e1af06001770fd2f,
  name='Rabble',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd31='5fb1ba43e1af06001770fd31'
g_base_definitions[g_str_5fb1ba43e1af06001770fd31]={
  id=g_str_5fb1ba43e1af06001770fd31,
  name='Skirmishers',
  min=0,
  max=4,
  description='Peasant skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd30",
}
g_str_5fb1b9f5e1af06001770a3aa_camp='5fb1b9f5e1af06001770a3aa_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3aa_camp]={
  id=g_str_5fb1b9f5e1af06001770a3aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba43e1af06001770fd2c_general='5fb1ba43e1af06001770fd2c_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c_general]={
  id=g_str_5fb1ba43e1af06001770fd2c_general,
  name='Light Foot General',
  min=2,
  max=1,
  description='Nobles and elite infantry',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2c='5fb1ba43e1af06001770fd2c'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2c]={
  id=g_str_5fb1ba43e1af06001770fd2c,
  name='Light Foot',
  min=2,
  max=6,
  description='Nobles and elite infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2b",
}
g_str_5fb1ba43e1af06001770fd2e_general='5fb1ba43e1af06001770fd2e_general'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e_general]={
  id=g_str_5fb1ba43e1af06001770fd2e_general,
  name='Light Foot General',
  min=12,
  max=1,
  description='Commoners, some carrying roll-up shields',
  general=true,
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2e='5fb1ba43e1af06001770fd2e'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2e]={
  id=g_str_5fb1ba43e1af06001770fd2e,
  name='Light Foot',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Light Foot",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd2f='5fb1ba43e1af06001770fd2f'
g_base_definitions[g_str_5fb1ba43e1af06001770fd2f]={
  id=g_str_5fb1ba43e1af06001770fd2f,
  name='Rabble',
  min=12,
  max=21,
  description='Commoners, some carrying roll-up shields',
  troop_type="Rabble",
  troop_option_id="5fb1ba43e1af06001770fd2d",
}
g_str_5fb1ba43e1af06001770fd31='5fb1ba43e1af06001770fd31'
g_base_definitions[g_str_5fb1ba43e1af06001770fd31]={
  id=g_str_5fb1ba43e1af06001770fd31,
  name='Skirmishers',
  min=0,
  max=4,
  description='Peasant skirmishing slingers',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba43e1af06001770fd30",
}
g_str_5fb1b9f5e1af06001770a3aa_camp='5fb1b9f5e1af06001770a3aa_camp'
g_base_definitions[g_str_5fb1b9f5e1af06001770a3aa_camp]={
  id=g_str_5fb1b9f5e1af06001770a3aa_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
