-- 5fb1b9e3e1af060017709980 Early Patrician Roman East  408 to 466 AD

army['5fb1b9e3e1af060017709980']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Early Patrician Roman East  408 to 466 AD',
    id='5fb1b9e3e1af060017709980',
    dateRange={
      startDate=408,
      endDate=466,
    }
  },
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6df_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6df],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6e1],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6e3_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6e3],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6e5_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6e5],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6e7],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6eb],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6ee],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6f0],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6f3],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6f6],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6f7],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6f9],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6fb_general],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6fb],
  g_base_definitions[g_str_5fb1ba2ee1af06001770d6fd],
  g_base_definitions[g_str_5fb1b9e3e1af060017709980_camp],
  g_base_definitions[g_str_5fb1b9e3e1af060017709980_camp_fortified],
  g_base_definitions[g_str_5fb1b9e3e1af060017709980_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af060017709980"] = army["5fb1b9e3e1af060017709980"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Early Patrician Roman East  408 to 466 AD"] = army["5fb1b9e3e1af060017709980"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Patrician Roman East  408 to 466 AD"] = army["5fb1b9e3e1af060017709980"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af060017709980"] = {}
army_dates["5fb1b9e3e1af060017709980"]["408 AD to 466 AD"] = {
  startDate=408,
  endDate=466
}
army_dates["5fb1b9e3e1af060017709980"]["408 AD to 422 AD"] = {
  startDate=408,
  endDate=422
}
army_dates["5fb1b9e3e1af060017709980"]["423 AD to 439 AD"] = {
  startDate=423,
  endDate=439
}
army_dates["5fb1b9e3e1af060017709980"]["440 AD to 466 AD"] = {
  startDate=440,
  endDate=466
}
