-- 5fb1b9efe1af06001770a050 Tahirid  821 to 873 AD

if army == nil then
  army = {}
end
if g_base_definitions == nil then
  g_base_definitions = {}
end
g_str_5fb1ba3ce1af06001770f148_general='5fb1ba3ce1af06001770f148_general'
g_base_definitions[g_str_5fb1ba3ce1af06001770f148_general]={
  id=g_str_5fb1ba3ce1af06001770f148_general,
  name='Elite Cavalary General',
  min=1,
  max=1,
  description='Khurasani noble horsemen',
  general=true,
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f147",
}
g_str_5fb1ba3ce1af06001770f148='5fb1ba3ce1af06001770f148'
g_base_definitions[g_str_5fb1ba3ce1af06001770f148]={
  id=g_str_5fb1ba3ce1af06001770f148,
  name='Elite Cavalary',
  min=1,
  max=2,
  description='Khurasani noble horsemen',
  troop_type="Elite Cavalary",
  troop_option_id="5fb1ba3ce1af06001770f147",
}
g_str_5fb1ba3ce1af06001770f14a='5fb1ba3ce1af06001770f14a'
g_base_definitions[g_str_5fb1ba3ce1af06001770f14a]={
  id=g_str_5fb1ba3ce1af06001770f14a,
  name='Horse Bow',
  min=0,
  max=2,
  description='Khurasani or Turkish mercenary horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3ce1af06001770f149",
}
g_str_5fb1ba3ce1af06001770f14c='5fb1ba3ce1af06001770f14c'
g_base_definitions[g_str_5fb1ba3ce1af06001770f14c]={
  id=g_str_5fb1ba3ce1af06001770f14c,
  name='Spears',
  min=3,
  max=5,
  description='Khurasani armored spearmen',
  troop_type="Spears",
  troop_option_id="5fb1ba3ce1af06001770f14b",
}
g_str_5fb1ba3ce1af06001770f150='5fb1ba3ce1af06001770f150'
g_base_definitions[g_str_5fb1ba3ce1af06001770f150]={
  id=g_str_5fb1ba3ce1af06001770f150,
  name='Archers',
  min=2,
  max=5,
  description='Khurasani infantry bowmen',
  troop_type="Archers",
  troop_option_id="5fb1ba3ce1af06001770f14f",
}
g_str_5fb1ba3ce1af06001770f151='5fb1ba3ce1af06001770f151'
g_base_definitions[g_str_5fb1ba3ce1af06001770f151]={
  id=g_str_5fb1ba3ce1af06001770f151,
  name='Skirmishers',
  min=2,
  max=5,
  description='Khurasani infantry bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3ce1af06001770f14f",
}
g_str_5fb1ba3ce1af06001770f154='5fb1ba3ce1af06001770f154'
g_base_definitions[g_str_5fb1ba3ce1af06001770f154]={
  id=g_str_5fb1ba3ce1af06001770f154,
  name='Javelin Cavalry',
  min=0,
  max=2,
  description='Bedouin arab or Aiyar horsemen',
  troop_type="Javelin Cavalry",
  troop_option_id="5fb1ba3ce1af06001770f153",
}
g_str_5fb1ba3ce1af06001770f156='5fb1ba3ce1af06001770f156'
g_base_definitions[g_str_5fb1ba3ce1af06001770f156]={
  id=g_str_5fb1ba3ce1af06001770f156,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami zupin-men',
  troop_type="Raiders",
  troop_option_id="5fb1ba3ce1af06001770f155",
}
g_str_5fb1ba3ce1af06001770f156_dismounted_mobile_infantry='5fb1ba3ce1af06001770f156_dismounted_mobile_infantry'
g_str_5fb1ba3ce1af06001770f156_mounted_mobile_infantry='5fb1ba3ce1af06001770f156_mounted_mobile_infantry'
g_base_definitions[g_str_5fb1ba3ce1af06001770f156_dismounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f156_dismounted_mobile_infantry,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami zupin-men\nDismounted mobile infantry',
  dismounted_from=g_str_5fb1ba3ce1af06001770f156_mounted_mobile_infantry,
  troop_type="Raiders",
  troop_option_id="5fb1ba3ce1af06001770f155",
}
g_base_definitions[g_str_5fb1ba3ce1af06001770f156_mounted_mobile_infantry]={
  id=g_str_5fb1ba3ce1af06001770f156_mounted_mobile_infantry,
  name='Raiders',
  min=0,
  max=1,
  description='Dailami zupin-men\nmounted mobile infantry',
  dismount_as=g_str_5fb1ba3ce1af06001770f156_dismounted_mobile_infantry,
  mobile_infantry=true,
  troop_type="Raiders",
  troop_option_id="5fb1ba3ce1af06001770f155",
}
g_str_5fb1ba3ce1af06001770f159='5fb1ba3ce1af06001770f159'
g_base_definitions[g_str_5fb1ba3ce1af06001770f159]={
  id=g_str_5fb1ba3ce1af06001770f159,
  name='Light Foot',
  min=0,
  max=2,
  description='Kumajis or other hillmen',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3ce1af06001770f158",
}
g_str_5fb1ba3ce1af06001770f15b='5fb1ba3ce1af06001770f15b'
g_base_definitions[g_str_5fb1ba3ce1af06001770f15b]={
  id=g_str_5fb1ba3ce1af06001770f15b,
  name='Horde',
  min=0,
  max=2,
  description='Hashariyan levies',
  troop_type="Horde",
  troop_option_id="5fb1ba3ce1af06001770f15a",
}
g_str_5fb1b9efe1af06001770a050_camp='5fb1b9efe1af06001770a050_camp'
g_base_definitions[g_str_5fb1b9efe1af06001770a050_camp]={
  id=g_str_5fb1b9efe1af06001770a050_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9efe1af06001770a050_camp_pack_train='5fb1b9efe1af06001770a050_camp_pack_train'
g_base_definitions[g_str_5fb1b9efe1af06001770a050_camp_pack_train]={
  id=g_str_5fb1b9efe1af06001770a050_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
army['5fb1b9efe1af06001770a050']={
  data={
    name='Tahirid  821 to 873 AD'
  },
  g_base_definitions[g_str_5fb1ba3ce1af06001770f148_general],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f148],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f14a],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f14c],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f150],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f151],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f154],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f156],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f156_mounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f156_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f159],
  g_base_definitions[g_str_5fb1ba3ce1af06001770f15b],
  g_base_definitions[g_str_5fb1b9efe1af06001770a050_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a050_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a050"] = army["5fb1b9efe1af06001770a050"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Tahirid  821 to 873 AD"] = army["5fb1b9efe1af06001770a050"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tahirid  821 to 873 AD"] = army["5fb1b9efe1af06001770a050"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a050"] = {}
army_dates["5fb1b9efe1af06001770a050"]["821 AD to 873 AD"] ="5fb1b9efe1af06001770a050"
