troop_options['5fb1ba3fe1af06001770f5e5'] = {
  min=1,
  max=2,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5e7'] = {
  min=1,
  max=1,
  dateRange={
    startDate=-355,
    endDate=-296,
  }
}
troop_options['5fb1ba3fe1af06001770f5ea'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5ec'] = {
  min=1,
  max=4,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5ef'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5f1'] = {
  min=2,
  max=4,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5f3'] = {
  min=0,
  max=6,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5f6'] = {
  min=0,
  max=4,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5f8'] = {
  min=0,
  max=1,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
troop_options['5fb1ba3fe1af06001770f5fa'] = {
  min=0,
  max=2,
  dateRange={
    startDate=-355,
    endDate=-307,
  }
}
-- allies
