-- 5fb1b9ebe1af060017709eb9 Desert Blemmye or Beja  30 BC to 1500 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba39e1af06001770eab9='5fb1ba39e1af06001770eab9'
g_base_definitions[g_str_5fb1ba39e1af06001770eab9]={
  id=g_str_5fb1ba39e1af06001770eab9,
  name='Horse Bow',
  min=1,
  max=2,
  description='Horse archers',
}
g_str_5fb1ba39e1af06001770eabb='5fb1ba39e1af06001770eabb'
g_base_definitions[g_str_5fb1ba39e1af06001770eabb]={
  id=g_str_5fb1ba39e1af06001770eabb,
  name='Bow Levy',
  min=9,
  max=19,
  description='Bowmen',
}
g_str_5fb1ba39e1af06001770eabd='5fb1ba39e1af06001770eabd'
g_base_definitions[g_str_5fb1ba39e1af06001770eabd]={
  id=g_str_5fb1ba39e1af06001770eabd,
  name='Light Foot',
  min=2,
  max=4,
  description='Spearmen',
}
g_str_5fb1ba39e1af06001770eac0='5fb1ba39e1af06001770eac0'
g_base_definitions[g_str_5fb1ba39e1af06001770eac0]={
  id=g_str_5fb1ba39e1af06001770eac0,
  name='Bad Horse',
  min=0,
  max=2,
  description='Camel-mounted spearmen',
}
g_str_5fb1ba39e1af06001770eac3='5fb1ba39e1af06001770eac3'
g_base_definitions[g_str_5fb1ba39e1af06001770eac3]={
  name='Horse Bow General',
  min=1,
  max=1,
}
g_str_5fb1b9ebe1af060017709eb9_camp='5fb1b9ebe1af060017709eb9_camp'
g_base_definitions[g_str_5fb1b9ebe1af060017709eb9_camp]={
  name='Camp',
  min=1,
  max=1,
}
army['5fb1b9ebe1af060017709eb9']={
  data={
    name='Desert Blemmye or Beja  30 BC to 1500 AD'
  },
  g_base_definitions[g_str_5fb1b9ebe1af060017709eb9_camp],
  g_base_definitions[g_str_5fb1ba39e1af06001770eac3],
  g_base_definitions[g_str_5fb1ba39e1af06001770eab9],
  g_base_definitions[g_str_5fb1ba39e1af06001770eabb],
  g_base_definitions[g_str_5fb1ba39e1af06001770eabd],
  g_base_definitions[g_str_5fb1ba39e1af06001770eac0],
}
