g_str_5fb1ba44e1af06001770feb5_general='5fb1ba44e1af06001770feb5_general'
g_base_definitions[g_str_5fb1ba44e1af06001770feb5_general]={
  id=g_str_5fb1ba44e1af06001770feb5_general,
  name='Warband General',
  min=14,
  max=1,
  description='Fierce tribesmen',
  general=true,
  troop_type="Warband",
  troop_option_id="5fb1ba44e1af06001770feb4",
}
g_str_5fb1ba44e1af06001770feb5='5fb1ba44e1af06001770feb5'
g_base_definitions[g_str_5fb1ba44e1af06001770feb5]={
  id=g_str_5fb1ba44e1af06001770feb5,
  name='Warband',
  min=14,
  max=16,
  description='Fierce tribesmen',
  troop_type="Warband",
  troop_option_id="5fb1ba44e1af06001770feb4",
}
g_str_5fb1ba44e1af06001770feb7='5fb1ba44e1af06001770feb7'
g_base_definitions[g_str_5fb1ba44e1af06001770feb7]={
  id=g_str_5fb1ba44e1af06001770feb7,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing blowpipe men',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770feb6",
}
g_str_5fb1b9f6e1af06001770a496_camp='5fb1b9f6e1af06001770a496_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a496_camp]={
  id=g_str_5fb1b9f6e1af06001770a496_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba44e1af06001770feb5_general='5fb1ba44e1af06001770feb5_general'
g_base_definitions[g_str_5fb1ba44e1af06001770feb5_general]={
  id=g_str_5fb1ba44e1af06001770feb5_general,
  name='Warband General',
  min=14,
  max=1,
  description='Fierce tribesmen',
  general=true,
  troop_type="Warband",
  troop_option_id="5fb1ba44e1af06001770feb4",
}
g_str_5fb1ba44e1af06001770feb5='5fb1ba44e1af06001770feb5'
g_base_definitions[g_str_5fb1ba44e1af06001770feb5]={
  id=g_str_5fb1ba44e1af06001770feb5,
  name='Warband',
  min=14,
  max=16,
  description='Fierce tribesmen',
  troop_type="Warband",
  troop_option_id="5fb1ba44e1af06001770feb4",
}
g_str_5fb1ba44e1af06001770feb7='5fb1ba44e1af06001770feb7'
g_base_definitions[g_str_5fb1ba44e1af06001770feb7]={
  id=g_str_5fb1ba44e1af06001770feb7,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing blowpipe men',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770feb6",
}
g_str_5fb1b9f6e1af06001770a496_camp='5fb1b9f6e1af06001770a496_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a496_camp]={
  id=g_str_5fb1b9f6e1af06001770a496_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1ba44e1af06001770feb5_general='5fb1ba44e1af06001770feb5_general'
g_base_definitions[g_str_5fb1ba44e1af06001770feb5_general]={
  id=g_str_5fb1ba44e1af06001770feb5_general,
  name='Warband General',
  min=14,
  max=1,
  description='Fierce tribesmen',
  general=true,
  troop_type="Warband",
  troop_option_id="5fb1ba44e1af06001770feb4",
}
g_str_5fb1ba44e1af06001770feb5='5fb1ba44e1af06001770feb5'
g_base_definitions[g_str_5fb1ba44e1af06001770feb5]={
  id=g_str_5fb1ba44e1af06001770feb5,
  name='Warband',
  min=14,
  max=16,
  description='Fierce tribesmen',
  troop_type="Warband",
  troop_option_id="5fb1ba44e1af06001770feb4",
}
g_str_5fb1ba44e1af06001770feb7='5fb1ba44e1af06001770feb7'
g_base_definitions[g_str_5fb1ba44e1af06001770feb7]={
  id=g_str_5fb1ba44e1af06001770feb7,
  name='Skirmishers',
  min=0,
  max=2,
  description='Skirmishing blowpipe men',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba44e1af06001770feb6",
}
g_str_5fb1b9f6e1af06001770a496_camp='5fb1b9f6e1af06001770a496_camp'
g_base_definitions[g_str_5fb1b9f6e1af06001770a496_camp]={
  id=g_str_5fb1b9f6e1af06001770a496_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
