g_str_5fb1ba3fe1af06001770f656_general='5fb1ba3fe1af06001770f656_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f656_general]={
  id=g_str_5fb1ba3fe1af06001770f656_general,
  name='Elite Cavalry General',
  min=1,
  max=1,
  description='Fully armored and barded horsemen',
  general=true,
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba3fe1af06001770f655",
}
g_str_5fb1ba3fe1af06001770f656='5fb1ba3fe1af06001770f656'
g_base_definitions[g_str_5fb1ba3fe1af06001770f656]={
  id=g_str_5fb1ba3fe1af06001770f656,
  name='Elite Cavalry',
  min=1,
  max=3,
  description='Fully armored and barded horsemen',
  troop_type="Elite Cavalry",
  troop_option_id="5fb1ba3fe1af06001770f655",
}
g_str_5fb1ba3fe1af06001770f658_general='5fb1ba3fe1af06001770f658_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f658_general]={
  id=g_str_5fb1ba3fe1af06001770f658_general,
  name='Knights General',
  min=0,
  max=1,
  description='Hard-charging Chinese noble horsemen',
  general=true,
  troop_type="Knights",
  troop_option_id="5fb1ba3fe1af06001770f657",
}
g_str_5fb1ba3fe1af06001770f658='5fb1ba3fe1af06001770f658'
g_base_definitions[g_str_5fb1ba3fe1af06001770f658]={
  id=g_str_5fb1ba3fe1af06001770f658,
  name='Knights',
  min=0,
  max=1,
  description='Hard-charging Chinese noble horsemen',
  troop_type="Knights",
  troop_option_id="5fb1ba3fe1af06001770f657",
}
g_str_5fb1ba3fe1af06001770f65a_general='5fb1ba3fe1af06001770f65a_general'
g_base_definitions[g_str_5fb1ba3fe1af06001770f65a_general]={
  id=g_str_5fb1ba3fe1af06001770f65a_general,
  name='Horse Bow General',
  min=1,
  max=1,
  description='Horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3fe1af06001770f659",
}
g_str_5fb1ba3fe1af06001770f65a='5fb1ba3fe1af06001770f65a'
g_base_definitions[g_str_5fb1ba3fe1af06001770f65a]={
  id=g_str_5fb1ba3fe1af06001770f65a,
  name='Horse Bow',
  min=1,
  max=2,
  description='Horse archers',
  troop_type="Horse Bow",
  troop_option_id="5fb1ba3fe1af06001770f659",
}
g_str_5fb1ba3fe1af06001770f65c='5fb1ba3fe1af06001770f65c'
g_base_definitions[g_str_5fb1ba3fe1af06001770f65c]={
  id=g_str_5fb1ba3fe1af06001770f65c,
  name='Light Foot',
  min=2,
  max=6,
  description='Chinese conscripts armed with spear or halberd',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3fe1af06001770f65b",
}
g_str_5fb1ba3fe1af06001770f65d='5fb1ba3fe1af06001770f65d'
g_base_definitions[g_str_5fb1ba3fe1af06001770f65d]={
  id=g_str_5fb1ba3fe1af06001770f65d,
  name='Heavy Foot',
  min=2,
  max=6,
  description='Chinese conscripts armed with spear or halberd',
  troop_type="Heavy Foot",
  troop_option_id="5fb1ba3fe1af06001770f65b",
}
g_str_5fb1ba3fe1af06001770f65f='5fb1ba3fe1af06001770f65f'
g_base_definitions[g_str_5fb1ba3fe1af06001770f65f]={
  id=g_str_5fb1ba3fe1af06001770f65f,
  name='Skirmishers',
  min=0,
  max=1,
  description='Chinese conscript skirmishing bowmen',
  troop_type="Skirmishers",
  troop_option_id="5fb1ba3fe1af06001770f65e",
}
g_str_5fb1ba3fe1af06001770f661='5fb1ba3fe1af06001770f661'
g_base_definitions[g_str_5fb1ba3fe1af06001770f661]={
  id=g_str_5fb1ba3fe1af06001770f661,
  name='Light Foot',
  min=2,
  max=6,
  description='Unarmored tribal infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3fe1af06001770f660",
}
g_str_5fb1ba3fe1af06001770f664='5fb1ba3fe1af06001770f664'
g_base_definitions[g_str_5fb1ba3fe1af06001770f664]={
  id=g_str_5fb1ba3fe1af06001770f664,
  name='Raiders',
  min=2,
  max=6,
  description='Armored tribal infantry',
  troop_type="Raiders",
  troop_option_id="5fb1ba3fe1af06001770f663",
}
g_str_5fb1ba3fe1af06001770f665='5fb1ba3fe1af06001770f665'
g_base_definitions[g_str_5fb1ba3fe1af06001770f665]={
  id=g_str_5fb1ba3fe1af06001770f665,
  name='Light Foot',
  min=2,
  max=6,
  description='Armored tribal infantry',
  troop_type="Light Foot",
  troop_option_id="5fb1ba3fe1af06001770f663",
}
g_str_5fb1ba3fe1af06001770f668='5fb1ba3fe1af06001770f668'
g_base_definitions[g_str_5fb1ba3fe1af06001770f668]={
  id=g_str_5fb1ba3fe1af06001770f668,
  name='Bow Levy',
  min=1,
  max=6,
  description='Former Qin bowmen or Chinese conscript levy bowmen',
  troop_type="Bow Levy",
  troop_option_id="5fb1ba3fe1af06001770f667",
}
g_str_5fb1ba3fe1af06001770f66c='5fb1ba3fe1af06001770f66c'
g_base_definitions[g_str_5fb1ba3fe1af06001770f66c]={
  id=g_str_5fb1ba3fe1af06001770f66c,
  name='Horde',
  min=0,
  max=2,
  description='Hastily armed Chinese laborers',
  troop_type="Horde",
  troop_option_id="5fb1ba3fe1af06001770f66a",
}
g_str_5fb1ba3fe1af06001770f66d='5fb1ba3fe1af06001770f66d'
g_base_definitions[g_str_5fb1ba3fe1af06001770f66d]={
  id=g_str_5fb1ba3fe1af06001770f66d,
  name='Rabble',
  min=0,
  max=2,
  description='Hastily armed Chinese laborers',
  troop_type="Rabble",
  troop_option_id="5fb1ba3fe1af06001770f66a",
}
g_str_5fb1b9f1e1af06001770a1ba_camp='5fb1b9f1e1af06001770a1ba_camp'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp]={
  id=g_str_5fb1b9f1e1af06001770a1ba_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9f1e1af06001770a1ba_camp_fortified='5fb1b9f1e1af06001770a1ba_camp_fortified'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_fortified]={
  id=g_str_5fb1b9f1e1af06001770a1ba_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9f1e1af06001770a1ba_camp_pack_train='5fb1b9f1e1af06001770a1ba_camp_pack_train'
g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_pack_train]={
  id=g_str_5fb1b9f1e1af06001770a1ba_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
