-- 5fb1b9e1e1af06001770987e Severan Middle Imperial Roman  193 to 284 AD

if g_base_definitions == nil then
  g_base_definitions = {}
end
if army == nil then
  army = {}
end
g_str_5fb1ba2ce1af06001770d33c_general='5fb1ba2ce1af06001770d33c_general'
g_base_definitions[g_str_5fb1ba2ce1af06001770d33c_general]={
  id=g_str_5fb1ba2ce1af06001770d33c_general,
  name='Javelin Cavalry General',
  min=2,
  max=1,
  description='Equites alares',
  general=true,
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ce1af06001770d33c='5fb1ba2ce1af06001770d33c'
g_base_definitions[g_str_5fb1ba2ce1af06001770d33c]={
  id=g_str_5fb1ba2ce1af06001770d33c,
  name='Javelin Cavalry',
  min=2,
  max=3,
  description='Equites alares',
  troop_type="Javelin Cavalry",
}
g_str_5fb1ba2ce1af06001770d33e='5fb1ba2ce1af06001770d33e'
g_base_definitions[g_str_5fb1ba2ce1af06001770d33e]={
  id=g_str_5fb1ba2ce1af06001770d33e,
  name='Cataphracts',
  min=0,
  max=1,
  description='Equites catafractarii',
  troop_type="Cataphracts",
}
g_str_5fb1ba2ce1af06001770d340='5fb1ba2ce1af06001770d340'
g_base_definitions[g_str_5fb1ba2ce1af06001770d340]={
  id=g_str_5fb1ba2ce1af06001770d340,
  name='Elite Foot',
  min=3,
  max=6,
  description='Legionaries',
  troop_type="Elite Foot",
}
g_str_5fb1ba2ce1af06001770d344='5fb1ba2ce1af06001770d344'
g_base_definitions[g_str_5fb1ba2ce1af06001770d344]={
  id=g_str_5fb1ba2ce1af06001770d344,
  name='Raiders',
  min=3,
  max=6,
  description='Auxiliary infantry with or without armor',
  troop_type="Raiders",
}
g_str_5fb1ba2ce1af06001770d345='5fb1ba2ce1af06001770d345'
g_base_definitions[g_str_5fb1ba2ce1af06001770d345]={
  id=g_str_5fb1ba2ce1af06001770d345,
  name='Light Foot',
  min=3,
  max=6,
  description='Auxiliary infantry with or without armor',
  troop_type="Light Foot",
}
g_str_5fb1ba2ce1af06001770d348='5fb1ba2ce1af06001770d348'
g_base_definitions[g_str_5fb1ba2ce1af06001770d348]={
  id=g_str_5fb1ba2ce1af06001770d348,
  name='Archers',
  min=0,
  max=3,
  description='Auxiliary bowmen',
  troop_type="Archers",
}
g_str_5fb1ba2ce1af06001770d349='5fb1ba2ce1af06001770d349'
g_base_definitions[g_str_5fb1ba2ce1af06001770d349]={
  id=g_str_5fb1ba2ce1af06001770d349,
  name='Skirmishers',
  min=0,
  max=3,
  description='Auxiliary bowmen',
  troop_type="Skirmishers",
}
g_str_5fb1ba2ce1af06001770d34c='5fb1ba2ce1af06001770d34c'
g_base_definitions[g_str_5fb1ba2ce1af06001770d34c]={
  id=g_str_5fb1ba2ce1af06001770d34c,
  name='Artillery',
  min=0,
  max=1,
  description='Bolt shooters or stone throwers',
  troop_type="Artillery",
}
g_str_5fb1ba2ce1af06001770d34e='5fb1ba2ce1af06001770d34e'
g_base_definitions[g_str_5fb1ba2ce1af06001770d34e]={
  id=g_str_5fb1ba2ce1af06001770d34e,
  name='Horse Bow',
  min=0,
  max=1,
  description='border horse archers',
  troop_type="Horse Bow",
}
g_str_5fb1ba2ce1af06001770d350='5fb1ba2ce1af06001770d350'
g_base_definitions[g_str_5fb1ba2ce1af06001770d350]={
  id=g_str_5fb1ba2ce1af06001770d350,
  name='Bad Horse',
  min=0,
  max=1,
  description='dromedarii',
  troop_type="Bad Horse",
}
g_str_5fb1ba2ce1af06001770d350_light_camelry='5fb1ba2ce1af06001770d350_light_camelry'
g_base_definitions[g_str_5fb1ba2ce1af06001770d350_light_camelry]={
  id=g_str_5fb1ba2ce1af06001770d350_light_camelry,
  name='Bad Horse Light camelry',
  min=0,
  max=1,
  description='dromedarii\nLight Camelry',
  light_camelry=true,
  troop_type="Bad Horse",
}
g_str_5fb1b9e1e1af06001770987e_camp='5fb1b9e1e1af06001770987e_camp'
g_base_definitions[g_str_5fb1b9e1e1af06001770987e_camp]={
  name='Camp',
  id=g_str_5fb1b9e1e1af06001770987e_camp,
  min=1,
  max=1,
}
army['5fb1b9e1e1af06001770987e']={
  data={
    name='Severan Middle Imperial Roman  193 to 284 AD'
  },
  g_base_definitions[g_str_5fb1b9e1e1af06001770987e_camp],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d33c_general],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d33c],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d33e],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d340],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d344],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d345],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d348],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d349],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d34c],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d34e],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d350],
  g_base_definitions[g_str_5fb1ba2ce1af06001770d350_light_camelry],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af06001770987e"] = army["5fb1b9e1e1af06001770987e"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Severan Middle Imperial Roman  193 to 284 AD"] = army["5fb1b9e1e1af06001770987e"]
