-- 6153509003385c0016b82754 Coastal Mountain First Nations  1100 to 1770 AD

army['6153509003385c0016b82754']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
      'Hilly',
    },
    name='Coastal Mountain First Nations  1100 to 1770 AD',
    id='6153509003385c0016b82754',
    dateRange={
      startDate=1100,
      endDate=1770,
    },
  },
  g_base_definitions[g_str_615351b703385c0016b88f85_general],
  g_base_definitions[g_str_615351b703385c0016b88f85],
  g_base_definitions[g_str_615351b703385c0016b88f87],
  g_base_definitions[g_str_6153509003385c0016b82754_camp],
  g_base_definitions[g_str_6153509003385c0016b82754_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["6153509003385c0016b82754"] = army["6153509003385c0016b82754"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Coastal Mountain First Nations  1100 to 1770 AD"] = army["6153509003385c0016b82754"]
if nil == armies["North America"] then
  armies["North America"] ={}
end
armies["North America"]["Coastal Mountain First Nations  1100 to 1770 AD"] = army["6153509003385c0016b82754"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Coastal Mountain First Nations  1100 to 1770 AD"] = army["6153509003385c0016b82754"]
if nil == army_dates then
  army_dates={}
end
army_dates["6153509003385c0016b82754"] = {}
army_dates["6153509003385c0016b82754"]["1100 AD to 1770 AD"] = {
  startDate=1100,
  endDate=1770
}
