image: Visual Studio 2015
shallow_clone: true

# create a build matrix to use various Lua and LuaJIT versions
environment:
  matrix:
    - LUAENV: luajit20
    - LUAENV: luajit21
    - LUAENV: lua51
    - LUAENV: lua51_64
    - LUAENV: lua52
    - LUAENV: lua52_64
    - LUAENV: lua53
    - LUAENV: lua53_64
    - LUAENV: lua54
    - LUAENV: lua54_64


# install required binaries via batch file (also sets %LUA% path)
install:
- cmd: .appveyor\install-lua.cmd

cache:
  # each directory resulting from the previous download/build is cached
  - lua51       -> .appveyor\install-lua.cmd
  - lua51-64    -> .appveyor\install-lua.cmd
  - lua52       -> .appveyor\install-lua.cmd
  - lua52-64    -> .appveyor\install-lua.cmd
  - lua53       -> .appveyor\install-lua.cmd
  - lua53-64    -> .appveyor\install-lua.cmd
  - lua54       -> .appveyor\install-lua.cmd
  - lua54-64    -> .appveyor\install-lua.cmd
  - luajit20    -> .appveyor\install-lua.cmd
  - luajit21    -> .appveyor\install-lua.cmd

build: off

test_script:
- cmd: >-
    %LUA% -v run_unit_tests.lua --shuffle

    %LUA% run_functional_tests.lua
