-- Early German
army['5fb1b9e1e1af060017709849'].data.has_models = true
army['5fb1b9e1e1af060017709849'].data.base = "tile_grass"
-- Early German Marcomanni
army['5fb1b9e1e1af060017709857'].data.has_models = true
army['5fb1b9e1e1af060017709857'].data.base = "tile_grass"

-- Early German
-- 115 BC to 250 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e1e1af060017709849/explore
-- As of: 20210407

    --Horsemen - JavCav General
    g_models[g_str_5fb1ba2be1af06001770d2ae_general] = g_models[g_str_5fb1ba27e1af06001770c887_general]
    g_models[g_str_5fb1ba2be1af06001770d2ae_general_mounted] = g_models[g_str_5fb1ba27e1af06001770c887_general]

    --Horsemen - Warriors General Dismounting
    g_models[g_str_5fb1ba2be1af06001770d2ae_general_dismounted] = g_models[g_str_5fb1ba27e1af06001770c87f_general_dismounted]

    --Horsemen - JavCav
    g_models[g_str_5fb1ba2be1af06001770d2ae] = g_models[g_str_5fb1ba27e1af06001770c887]
    g_models[g_str_5fb1ba2be1af06001770d2ae_mounted] = g_models[g_str_5fb1ba27e1af06001770c887]

    --Horsemen - Warriors  Dismounting
    g_models[g_str_5fb1ba2be1af06001770d2ae_dismounted] = {
      {
        model_data = 'troop_gallic_warriors'
      }
    }
    -- Fierce fighters - Warriors General
    g_models[g_str_5fb1ba2be1af06001770d2b1_general] = g_models[g_str_5fb1ba27e1af06001770c87f_dismounted]

    -- Fierce fighters - Warriors
    g_models[g_str_5fb1ba2be1af06001770d2b1] = g_models[g_str_5fb1ba2be1af06001770d2ae_dismounted]

    -- Fighters armed with sword, shield, and wooden club - Raiders
    g_models[g_str_5fb1ba2be1af06001770d2b3] = {
      {
        model_data = 'troop_gallatian_bd'
      }
    }

    -- Foot skirmishers armed with many fire-hardened untipped throwing spears - Rabble
    g_models[g_str_5fb1ba2be1af06001770d2b5] = {
    {
      model_data = 'troop_gallic_ps_javelin',
      loose = true
    }
  }

    -- Skirmishing bowmen
    g_models[g_str_5fb1ba2be1af06001770d2b7] = {
    {
      model_data = 'troop_gallic_ps_archer',
      loose = true
    }
  }

    -- Early German Camp
    g_models[g_str_5fb1b9e1e1af060017709849_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    -- Early German Camp Fortified
    g_models[g_str_5fb1b9e1e1af060017709849_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]

    -- Early German Camp Pack Trains
    g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Early German Marcomanni
-- 9 BC to 19 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e1e1af060017709857/explore
-- As of: 20210407

    --Horsemen - JavCav General
    g_models[g_str_5fb1ba2be1af06001770d2db_general] = g_models[g_str_5fb1ba27e1af06001770c887_general]
    g_models[g_str_5fb1ba2be1af06001770d2db_general_mounted] = g_models[g_str_5fb1ba27e1af06001770c887_general]

    --Horsemen - Warriors General Dismounting
    g_models[g_str_5fb1ba2be1af06001770d2db_general_dismounted] = g_models[g_str_5fb1ba27e1af06001770c87f_general_dismounted]

    --Horsemen - JavCav
    g_models[g_str_5fb1ba2be1af06001770d2db] = g_models[g_str_5fb1ba27e1af06001770c887_general]
    g_models[g_str_5fb1ba2be1af06001770d2db_mounted] = g_models[g_str_5fb1ba27e1af06001770c887_general]

    --Horsemen - Warriors  Dismounting
    g_models[g_str_5fb1ba2be1af06001770d2db_dismounted] = g_models[g_str_5fb1ba2be1af06001770d2ae_dismounted]

    -- Fierce fighters - Warriors
    g_models[g_str_5fb1ba2be1af06001770d2de] = g_models[g_str_5fb1ba2be1af06001770d2b1]

    -- Drilled foot tribesmen - HF
    g_models[g_str_5fb1ba2be1af06001770d2e0] = g_models[g_str_5fb1ba27e1af06001770c87f_dismounted]

    -- Foot skirmishers armed with many fire-hardened untipped throwing spears - Rabble
    g_models[g_str_5fb1ba2be1af06001770d2e2] = g_models[g_str_5fb1ba2be1af06001770d2b5]

    -- Skirmishing bowmen
    g_models[g_str_5fb1ba2be1af06001770d2e4] = g_models[g_str_5fb1ba2be1af06001770d2b7]

    -- Early German Camp
    g_models[g_str_5fb1b9e1e1af060017709857_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    -- Early German Camp Fortified
    g_models[g_str_5fb1b9e1e1af060017709857_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]

    -- Early German Camp Pack Trains
    g_models[g_str_5fb1b9e1e1af060017709857_camp_pack_train] = g_models[g_str_5fb1b9dce1af06001770959d_camp_pack_train]
