-- Thracian Hill Tribes
army['5fb1b9dde1af060017709640'].data.has_models = true
army['5fb1b9dde1af060017709640'].data.base="tile_grass"

-- Thracian Hill Tribes
-- 700 BC to 46 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dde1af060017709640/explore
-- As of: 20210408

    -- Horsemen JavCav General
    g_models[g_str_615351a303385c0016b85b8e_general] = {
      {
        n_models = 2,
        fixed_models = {
            [1] = 'troop_thracian_cv',
            [2] = 'troop_thracian_cv_gen'
        }
      }
    }

    -- Horsemen JavCav
    g_models[g_str_615351a303385c0016b85b8e] = {
      {
        model_data = 'troop_thracian_lh'
      }
    }

    -- Peltasts LF General
    g_models[g_str_615351a303385c0016b85b90_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_thracian_axgen',
          [2] = 'troop_thracian_cv_gen',
          [3] = 'troop_thracian_ax1'
        }
      }
    }

    -- Peltasts LF
    g_models[g_str_615351a303385c0016b85b90] = {
      {
        model_data = 'troop_thracian_ax1'
      }
    }

    -- Peltasts armed with long spear - Light Spear
    g_models[g_str_615351a303385c0016b85b92] = {
      {
        model_data = 'troop_thracian_axgen'
      }
    }


    -- Skirmishing bowmen or slingers - General
    g_models[g_str_615351a303385c0016b85b94_general] = {
      {
        n_models = 2,
        fixed_models = {
            [1] = 'troop_thracian_lh',
            [2] = 'troop_successors_skirmishers'
        }
      }
    }

    -- Skirmishing bowmen or slingers
    g_models[g_str_615351a303385c0016b85b94] = {
      {
        loose = true,
        random_models = {
          'troop_successors_skirmishers',
          'troop_successors_skirmishers_archers'
        }
      }
    }

    -- Gymnetes (naked men armed with javelins or stones) - Rabble
    g_models[g_str_615351a303385c0016b85b96] = {
      {
        loose = true,
        model_data = 'troop_thracian_ps'
      }
    }

    --Thracian Camp
    g_models[g_str_5fb1b9dde1af060017709640_camp] = g_models[g_str_5fb1b9dce1af0600177095ab_camp]

    --Thracian Camp Fortified
    g_models[g_str_5fb1b9dde1af060017709640_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_ancient_spanish_camp',
            scale=0.7
          }
        }
      }
    }
