

-- Models that can be used to represent a base definition.
-- key is the base definition identifier.
-- value is a list of model definitions.  Any model definition is
-- a valid representation of the base definition.
-- A model defintion is a table:
-- TODO fill in the details.
-- Split the file and use #include to make it more managable

-- Armies that are considered to have models.
--

-- Post-Zama Carthaginian
army['5fb1b9dce1af06001770957a'].data.has_models = true
-- Burgundian Ordonnance
army['5fb1b9e8e1af060017709c95'].data.has_models = true

g_models = {}

-- Post-Zama Carthaginian
-- 201 BC to 146 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af06001770957a/explore
-- As of: 20210331

-- 'Libyan heavy infantry armed with spears'
g_models[g_str_5fb1ba26e1af06001770c82a] = {
  {
    base = 'tile_grass_40x15',
    n_models = 4,
    random_models = {
      'troop_carthaginian_spearmen_aspis',
      'troop_carthaginian_spearmen_imitation'
    }
  }
}

-- Burgundian Ordonnance
-- 1471 AD to 1477 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e8e1af060017709c95/explore
-- As of: 20210315



-- burgundian_ordannances_1471_to_1477_ad_knights_gen =
g_models[g_str_5fb1ba34e1af06001770e198] = {
  {
    base = 'tile_grass_40x30',
    n_models = 3,
    fixed_models = {
        'troop_knight_burgundian_ordonnances',
        'troop_knight_burgundian_ordonnances_captain',
        'troop_knight_burgundian_ordonnances_bannerman'
    },
  }
}

-- burgundian_ordannances_1471_to_1477_ad_artillery
g_models[g_str_5fb1ba34e1af06001770e186] = {
  {
    base = 'tile_grass_40x40',
    n_models = 3,
    fixed_models = {
      'troop_artillery_crew_burgundian_ordonnances',
      'troop_artillery_pieces_burgundian_ordonnances',
      'troop_artillery_crew_burgundian_ordonnances'
    }
  }
}
