-- West Frankish
army['5fb1b9e4e1af060017709a53'].data.has_models = true
army['5fb1b9e4e1af060017709a53'].data.base = "tile_grass"
-- Duke William's Norman Invasion
army['5fb1b9e4e1af060017709a59'].data.has_models = true
army['5fb1b9e4e1af060017709a59'].data.base = "tile_grass"
-- Anglo-Norman
army['5fb1b9e5e1af060017709b08'].data.has_models = true
army['5fb1b9e5e1af060017709b08'].data.base = "tile_grass"

-- West Frankish
-- 888 AD to 1072 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e4e1af060017709a53/explore
-- As of: 20210418

    -- Milites - Kn General
    g_models[g_str_615351a903385c0016b869f8_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_norman_knight_lance_pennat',
            [2] = 'troop_norman_knight_sword',
            [3] = 'troop_frank_knight_flag'
        }
      }
    }

    -- Milites\nDeployment dismounted from Knights General - EF General
    g_models[g_str_615351a903385c0016b869f8_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_norman_armor_foot_sword',
            [2] = 'troop_norman_armor_foot_sword',
            [3] = 'troop_frank_armor_foot_flag',
            [4] = 'troop_norman_armor_foot_sword'
        }
      }
    }

    -- Milites\nDeployment dismounting as Elite Foot - Kn General
    g_models[g_str_615351a903385c0016b869f8_general_mounted] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_norman_knight_lance_pennat',
            [2] = 'troop_norman_knight_sword',
            [3] = 'troop_frank_knight_flag'
        }
      }
    }

    -- Milites - Kn
    g_models[g_str_615351a903385c0016b869f8] = {
      {
        model_data = 'troop_norman_milite_mounted'
      }
    }

    -- Milites\nDeployment dismounted from Knights - EF
    g_models[g_str_615351a903385c0016b869f8_dismounted] = {
      {
        model_data = 'troop_norman_armor_foot_sword'
      }
    }

    -- Milites\nDeployment dismounting as Elite Foot - Kn
    g_models[g_str_615351a903385c0016b869f8_mounted] = {
      {
        model_data = 'troop_norman_milite_mounted'
      }
    }

    -- Milites - Kn General
    g_models[g_str_615351a903385c0016b869fb_general] = g_models[g_str_615351a903385c0016b869f8_general]

    -- Milites - Kn
    g_models[g_str_615351a903385c0016b869fb] = g_models[g_str_615351a903385c0016b869f8]

    -- Milites who removed their armor to scout - JavCav
    g_models[g_str_615351a903385c0016b869fc] = {
      {
        model_data = 'troop_norman_lightcav',
        loose = true
      }
    }

    -- Pedites - HF
    g_models[g_str_615351a903385c0016b869fe] = {
      {
        model_data = 'troop_norman_levy_shield'
      }
    }

    -- Mercenary spearmen - Spears
    g_models[g_str_615351a903385c0016b86a00] = {
      {
        model_data = 'troop_norman_pikemen'
      }
    }

    -- Massed levy bowmen - Bow Levy
    g_models[g_str_615351a903385c0016b86a02] = {
      {
        model_data = 'troop_norman_archer'
      }
    }

    -- Crossbowmen or staff slingers - Archers
    g_models[g_str_615351a903385c0016b86a04] = {
      {
        model_data = 'troop_norman_crossbow'
      }
    }

    -- Crossbowmen or staff slingers - Sk
    g_models[g_str_615351a903385c0016b86a05] = {
      {
        model_data = 'troop_norman_crossbow'
      }
    }

    -- Cottereaux - LF
    g_models[g_str_615351a903385c0016b86a07] = {
      {
        model_data = 'troop_norman_levy'
      }
    }
    -- THIS HAS TO BE CHANGED
    -- Sicilian Greek infantry - LF
    g_models[g_str_615351a903385c0016b86a0a] = {
      {
        model_data = 'troop_norman_levy'
      }
    }

    -- Servants, grooms, or peasants - Horde
    g_models[g_str_615351a903385c0016b86a0c] = {
      {
        model_data = 'troop_norman_levy',
        loose = true
      }
    }

    --West Frankish Camp
    g_models[g_str_5fb1b9e4e1af060017709a53_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    --West Frankish Pack Trains
    g_models[g_str_5fb1b9e4e1af060017709a53_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Duke William's Norman Invasion
-- 1066 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e4e1af060017709a59/explore
-- As of: 20210418

    -- Milites - Kn General
    g_models[g_str_615351a903385c0016b86a1a_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_norman_knight_lance_pennat',
          [2] = 'troop_norman_knight_sword',
          [3] = 'troop_norman_knight_flag'
        }
      }
    }

    -- Milites\nDeployment dismounted from Knights General - EF General
    g_models[g_str_615351a903385c0016b86a1a_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_norman_armor_foot_sword',
          [2] = 'troop_norman_armor_foot_sword',
          [3] = 'troop_norman_armor_foot_flag',
          [4] = 'troop_norman_armor_foot_sword'
        }
      }
    }

    -- Milites\nDeployment dismounting as Elite Foot - Kn General
    g_models[g_str_615351a903385c0016b86a1a_general_mounted] = g_models[g_str_615351a903385c0016b86a1a_general]

    -- Milites - Kn
    g_models[g_str_615351a903385c0016b86a1a] = g_models[g_str_615351a903385c0016b869f8]

    -- Milites\nDeployment dismounted from Knights - EF
    g_models[g_str_615351a903385c0016b86a1a_dismounted] = g_models[g_str_615351a903385c0016b869f8_dismounted]

    -- Milites\nDeployment dismounting as Elite Foot - Kn
    g_models[g_str_615351a903385c0016b86a1a_mounted] = g_models[g_str_615351a903385c0016b86a1a]

    -- Milites\nDeployment dismounted from Knights - EF
    g_models[g_str_615351a903385c0016b86a1d] = g_models[g_str_615351a903385c0016b86a1a_dismounted]

    -- Milites - Kn General
    g_models[g_str_615351a903385c0016b86a1f_general] = g_models[g_str_615351a903385c0016b86a1a_general]

    -- Milites - Kn
    g_models[g_str_615351a903385c0016b86a1f] = g_models[g_str_615351a903385c0016b86a1a]

    -- Milites who removed their armor to scout - JavCav
    g_models[g_str_615351a903385c0016b86a20] = g_models[g_str_615351a903385c0016b869fc]

    --THIS HAS TO BE CHANGED
    -- Breton horsemen - JavCav
    g_models[g_str_615351a903385c0016b86a22] = g_models[g_str_615351a903385c0016b869fc]

    -- Pedites - HF
    g_models[g_str_615351a903385c0016b86a24] = g_models[g_str_615351a903385c0016b869fe]

    -- Mercenary spearmen - Spears
    g_models[g_str_615351a903385c0016b86a26] = g_models[g_str_615351a903385c0016b86a00]

    -- Massed levy bowmen - Bow Levy
    g_models[g_str_615351a903385c0016b86a28] = g_models[g_str_615351a903385c0016b86a02]

    -- Crossbowmen or staff slingers - Sk
    g_models[g_str_615351a903385c0016b86a2a] = g_models[g_str_615351a903385c0016b86a05]

    -- Servants, grooms, or peasants - Horde
    g_models[g_str_615351a903385c0016b86a2c] = g_models[g_str_615351a903385c0016b86a0c]

    --West Frankish Camp
    g_models[g_str_5fb1b9e4e1af060017709a59_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

-- Anglo-Norman
-- 1072 AD to 1180 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709b08/explore
-- As of: 20230109

    -- Men-at-arms and mounted sergeants - Kn General
    g_models[g_str_615351aa03385c0016b86ca5_general] = g_models[g_str_615351a903385c0016b86a1a_general]

    -- Men-at-arms and mounted sergeants\nDeployment dismounted from Knights General - EF General
    g_models[g_str_615351aa03385c0016b86ca5_general_dismounted] = g_models[g_str_615351a903385c0016b86a1a_general_dismounted]

    -- Men-at-arms and mounted sergeants\nDeployment dismounting as Elite Foot - Kn General
    g_models[g_str_615351aa03385c0016b86ca5_general_mounted] = g_models[g_str_615351aa03385c0016b86ca5_general]

    -- Men-at-arms and mounted sergeants - Kn
    g_models[g_str_615351aa03385c0016b86ca5] = g_models[g_str_615351a903385c0016b86a1a]

    -- Men-at-arms and mounted sergeants\nDeployment dismounted from Knights - EF
    g_models[g_str_615351aa03385c0016b86ca5_dismounted] = g_models[g_str_615351a903385c0016b86a1a_dismounted]

    -- Men-at-arms and mounted sergeants\nDeployment dismounting as Elite Foot - Kn
    g_models[g_str_615351aa03385c0016b86ca5_mounted] = g_models[g_str_615351aa03385c0016b86ca5]

    -- Sergeants, town militia, fyrd, and mercenaries - HF
    g_models[g_str_615351aa03385c0016b86ca8] = {
      {
        random_models = {
          'troop_norman_armor_foot_sword',
          'troop_norman_spear',
          'troop_norman_levy_shield'
        }
      }
    }

    -- Bowmen - Bow Levy
    g_models[g_str_615351aa03385c0016b86cab] = g_models[g_str_615351a903385c0016b86a28]

    -- Welsh bowmen - Archers
    g_models[g_str_615351aa03385c0016b86caf] = {
      {
        model_data = 'troop_norman_archer'
      }
    }

    -- Genoese or other mercenary crossbowmen - Archers
    g_models[g_str_615351aa03385c0016b86cb2] = {
      {
        model_data = 'troop_norman_archer'
      }
    }

    -- Flemish mercenary pikemen - Pikes
    g_models[g_str_615351aa03385c0016b86cb5] = {
      {
        model_data = 'troop_norman_pikemen'
      }
    }

    --Anglo-Norman Camp
    g_models[g_str_5fb1b9e5e1af060017709b08_camp] = g_models[g_str_5fb1b9e4e1af060017709a59_camp]

    --Anglo-Norman Standard Wagon
    g_models[g_str_5fb1b9e5e1af060017709b08_camp_standard_wagon] = {
      {
        base = 'tile_grass_80x40',
        n_models = 1,
        model_data = 'troop_anglonorman_wagon'
      }
    }

    -- Muntatores - Jav Cav
    g_models[g_str_6153519603385c0016b83fea] = g_models[g_str_615351a903385c0016b86a20] 

    -- Marcher Welshry - Light Foot
    g_models[g_str_6153519603385c0016b83fec] = {
      {
        random_models = {
          'troop_norman_levy',
          'troop_norman_levy_shield'
        }
      }
    }