-- Rise of Macedon
-- 359 BC to 336 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dde1af06001770961d/explore
-- As of: 20210411

-- Rise of Macedon
army['5fb1b9dde1af06001770961d'].data.has_models = true
-- Alexandrian Macedonian
army['5fb1b9dde1af060017709623'].data.has_models = true
-- Diadachoii in Macedon
army['5fb1b9dee1af060017709659'].data.has_models = true
-- Lysimachid
army['5fb1b9dee1af060017709671'].data.has_models = true
-- Antigonid
army['5fb1b9dee1af060017709665'].data.has_models = true
-- Early Ptolemaic
army['5fb1b9dfe1af06001770970f'].data.has_models = true


    --Companions - Kn General
    g_models[g_str_5fb1ba27e1af06001770ca7c_general] = {
      {
        base = 'tile_grass_40x30',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard',
            [2] = 'troop_successors_cavalry_general_yellow',
            [3] = 'troop_successors_cavalry_bodyguard'
        }
      }
    }

    --Companions - Kn
    g_models[g_str_5fb1ba27e1af06001770ca7c] = {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_cavalry_bodyguard'
      }
    }

    --Prodomoi - JavCav
    g_models[g_str_5fb1ba27e1af06001770ca7e] = {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_cav'
      }
    }

    --Thessalian Horsemen - JavCav
    g_models[g_str_5fb1ba27e1af06001770ca80] = {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_thracian_cv'
      }
    }

    --Hypaspists - Raiders
    g_models[g_str_5fb1ba27e1af06001770ca82] = {
      {
        base = 'tile_grass_40x20',
        model_data = 'troop_successors_hypaspist_black'
      }
    }

    --Hypaspists - Pikes General
    g_models[g_str_5fb1ba27e1af06001770ca83_general] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike2_black',
          [3] = 'troop_successors_cavalry_general',
          [4] = 'troop_successors_pike2_black'
      }
      }
    }

    --Hypaspists - Pikes
    g_models[g_str_5fb1ba27e1af06001770ca83] = {
      {
        base = 'tile_grass_40x15',
        model_data = 'troop_successors_pike2_black'
      }
    }

    --Phalanx - Pikes General
    g_models[g_str_5fb1ba27e1af06001770ca86_general] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1',
          [2] = 'troop_successors_pike2',
          [3] = 'troop_successors_cavalry_general',
          [4] = 'troop_successors_pike1'
      }
      }
    }

    --Phalanx - Pikes
    g_models[g_str_5fb1ba27e1af06001770ca86] = {
      {
        base = 'tile_grass_40x15',
        random_models = {
          'troop_successors_pike1',
          'troop_successors_pike2'
        }
      }
    }

    --Macedonian light infantry not yet trained with pike - LF
    g_models[g_str_5fb1ba27e1af06001770ca89] = {
      {
        base = 'tile_grass_40x20',
        model_data = 'troop_successors_ax'
      }
    }

    --Cretan or Macedonian skirmishing bowmen - Sk
    g_models[g_str_5fb1ba27e1af06001770ca8b] = {
      {
        base = 'tile_grass_40x20',
        model_data = 'troop_successors_skirmishers_archers'
      }
    }

    --Greek allied hoplites - HF
    g_models[g_str_5fb1ba27e1af06001770ca8d] = {
      {
        base = 'tile_grass_40x15',
        random_models = {
          'troop_successors_spear2',
          'troop_successors_spear1',
          'troop_successors_spear2_black',
          'troop_successors_spear1_black',
          'troop_successors_spear2_red',
          'troop_successors_spear1_red',
          'troop_successors_spear2_blue',
          'troop_successors_spear1_blue',
          'troop_successors_spear2_green',
          'troop_successors_spear1_green',
          'troop_successors_spear2_yellow',
        }
      }
    }

    --Greek mercenary peltasts - LF
    g_models[g_str_5fb1ba27e1af06001770ca91] = {
      {
        base = 'tile_grass_40x20',
        random_models = {
          'troop_successors_psiloi',
          'troop_successors_psiloi_black',
          'troop_successors_psiloi_red',
          'troop_successors_psiloi_blue',
          'troop_successors_psiloi_green'
        }
      }
    }

    --Bolt-shooters - Art
    g_models[g_str_5fb1ba27e1af06001770ca94] = {
      {
        base = 'tile_grass_40x40',
        n_models = 1,
        model_data = 'troop_successors_art'
      }
    }

    --Macedonian Camp
    g_models[g_str_5fb1b9dde1af06001770961d_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    --Macedonian Camp Fort
    g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified] = {
      {
        base = 'tile_grass_40x40',
        n_models = 1,
        model_data = 'troop_carthaginian_camp'
      }
    }

    --Macedonian Camp Trains and Herds - NOT YET
    --g_models[g_str_5fb1b9dde1af06001770961d_camp_pack_train] =


-- Alexandrian Macedonian
-- 335 BC to 319 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dde1af060017709623/explore
-- As of: 20210412

    --Companions - Kn General
    g_models[g_str_5fb1ba27e1af06001770ca9e_general] = g_models[g_str_5fb1ba27e1af06001770ca7c_general]

    --Companions - Kn
    g_models[g_str_5fb1ba27e1af06001770ca9e] = g_models[g_str_5fb1ba27e1af06001770ca7c]

    --Prodomoi - JavCav
    g_models[g_str_5fb1ba27e1af06001770caa0] = g_models[g_str_5fb1ba27e1af06001770ca7e]

    --Thessalian Horsemen - JavCav
    g_models[g_str_5fb1ba27e1af06001770caa3] = {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_thracian_cv'
      }
    }
    --Allied or mercenary Greek horsemen - Bad Horse
    g_models[g_str_5fb1ba27e1af06001770caa5] = {
      {
        base = 'tile_grass_40x30',
        n_models = 3,
        fixed_models = {
          [1] = 'troop_successors_cavalry_bodyguard',
          [2] = 'troop_successors_cavalry_general_black',
          [3] = 'troop_successors_cavalry_bodyguard'
      }
      }
    }

    --Thracian or Paionian horsemen - JavCav
    g_models[g_str_5fb1ba27e1af06001770caa7] = {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_thracian_lh'
      }
    }

    --Hypaspists - Raiders
    g_models[g_str_5fb1ba27e1af06001770caaa] = g_models[g_str_5fb1ba27e1af06001770ca82]

    --Hypaspists - Pikes
    g_models[g_str_5fb1ba27e1af06001770caab] = g_models[g_str_5fb1ba27e1af06001770ca83]

    --Phalanx - Pikes
    g_models[g_str_5fb1ba27e1af06001770caae] = g_models[g_str_5fb1ba27e1af06001770ca86]

    --Cretan or Macedonian skirmishing bowmen - Sk
    g_models[g_str_5fb1ba27e1af06001770cab0] = g_models[g_str_5fb1ba27e1af06001770ca8b]

    --Greek allied hoplites - HF
    g_models[g_str_5fb1ba27e1af06001770cab2] = g_models[g_str_5fb1ba27e1af06001770ca8d]

    --Greek mercenary, Thracian, or Agrianian peltasts and javelinmen - LF
    g_models[g_str_5fb1ba27e1af06001770cab5] = {
      {
        base = 'tile_grass_40x20',
        model_data = 'troop_successors_psiloi'
      },
      {
        base = 'tile_grass_40x20',
        random_models = {
          'troop_thracian_ax1',
          'troop_thracian_axgen'
        }
      }
    }

    --Bolt-shooters - Art
    g_models[g_str_5fb1ba27e1af06001770cab7] = g_models[g_str_5fb1ba27e1af06001770ca94]

    --War elephants
    g_models[g_str_5fb1ba27e1af06001770caba] = {
        {
          base = 'tile_grass_40x40',
          n_models = 1,
          model_data = 'troop_successors_el'
        }
    }

    --Macedonian Camp
    g_models[g_str_5fb1b9dde1af060017709623_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Macedonian Camp Fort
    g_models[g_str_5fb1b9dde1af060017709623_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]

    --Macedonian Camp Trains and Herds - NOT YET
    --g_models[g_str_5fb1b9dde1af060017709623_camp_pack_train] = 


-- Diadachoii in Macedon
-- 320 BC to 279 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af060017709659/explore
-- As of: 20210412

    --Xystophoroi - Kn General
    g_models[g_str_5fb1ba28e1af06001770cb60_general] =  {
      {
        base = 'tile_grass_40x30',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_blue',
            [2] = 'troop_successors_cavalry_general_red',
            [3] = 'troop_successors_cavalry_bodyguard_blue'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_5fb1ba28e1af06001770cb60] =  {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_cavalry_bodyguard_blue'
      }
    }

    --Greek mercenary horsemen - JavCav General
    g_models[g_str_5fb1ba28e1af06001770cb62_general] ={
      {
        base = 'tile_grass_40x30',
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_black',
          [2] = 'troop_successors_cavalry_general_red'
      }
      }
    }

    --Greek mercenary horsemen - JavCav
    g_models[g_str_5fb1ba28e1af06001770cb62] ={
      {
        base = 'tile_grass_40x30',
        random_models = {
          'troop_successors_lh',
          'troop_successors_lh_blue',
          'troop_successors_lh_red',
          'troop_successors_lh_black',
          'troop_successors_lh_yellow',
          'troop_successors_lh_green'
        }
      }
    }

    --Thessalian Horsemen - JavCav General
    g_models[g_str_5fb1ba28e1af06001770cb65_general] = {
      {
        base = 'tile_grass_40x30',
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_cavalry_general_red',
          [2] = 'troop_thracian_cv'
      }
      }
    }

    --Thessalian Horsemen - JavCav
    g_models[g_str_5fb1ba28e1af06001770cb65] = g_models[g_str_5fb1ba27e1af06001770ca80]

    --Phalanx - Pikes General
    g_models[g_str_5fb1ba28e1af06001770cb67_general] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_blue',
          [2] = 'troop_successors_pike2_blue',
          [3] = 'troop_successors_cavalry_general',
          [4] = 'troop_successors_pike1_blue'
      }
      }
    }

    --Phalanx - Pikes
    g_models[g_str_5fb1ba28e1af06001770cb67] = {
      {
        base = 'tile_grass_40x15',
        random_models = {
          'troop_successors_pike1_blue',
          'troop_successors_pike2_blue'
        }
      }
    }

    --Mercenary peltasts - LF General
    g_models[g_str_5fb1ba28e1af06001770cb69_general] = {
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_psiloi',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_successors_psiloi'
        }
      }
    }

    --Mercenary peltasts - LF
    g_models[g_str_5fb1ba28e1af06001770cb69] = g_models[g_str_5fb1ba27e1af06001770ca91]

    --Thracian, Illyrian, or Paionian light infantry - LF General
    g_models[g_str_5fb1ba28e1af06001770cb6b_general] = {
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_ax1',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_thracian_ax1'
        }
      },
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_axgen',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_thracian_axgen'
        }
      }
    }

    --Thracian, Illyrian, or Paionian light infantry - LF
    g_models[g_str_5fb1ba28e1af06001770cb6b] = {
      {
        base = 'tile_grass_40x20',
        random_models = {
          'troop_thracian_ax1',
          'troop_thracian_axgen'
        }
      }
    }

    --Epeirote allied light infantry - LF General
    g_models[g_str_5fb1ba28e1af06001770cb6e_general] = {
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_ax_green',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_successors_ax_red'
        }
      },
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_general',
            [2] = 'troop_successors_ax_blue',
            [3] = 'troop_successors_ax'
        }
      },
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_ax_black',
            [2] = 'troop_successors_ax',
            [3] = 'troop_successors_cavalry_general'
        }
      }
    }

    --Epeirote allied light infantry - LF
    g_models[g_str_5fb1ba28e1af06001770cb6e] = {
      {
        base = 'tile_grass_40x20',
        random_models = {
          'troop_successors_ax_red',
          'troop_successors_ax_blue',
          'troop_successors_ax_green',
          'troop_successors_ax_black',
          'troop_successors_ax',
        }
      }
    }

    --Greek subject hoplites - HF
    g_models[g_str_5fb1ba28e1af06001770cb71] = g_models[g_str_5fb1ba27e1af06001770ca8d]

    --Cretan or Macedonian skirmishing bowmen - Sk
    g_models[g_str_5fb1ba28e1af06001770cb74] = g_models[g_str_5fb1ba27e1af06001770ca8b]

    --War elephants
    g_models[g_str_5fb1ba28e1af06001770cb76_general] = {
      {
        base = 'tile_grass_40x40',
        n_models = 1,
        model_data = 'troop_successors_el_red'
      }
    }

    --War elephants
    g_models[g_str_5fb1ba28e1af06001770cb76] = {
        {
          base = 'tile_grass_40x40',
          n_models = 1,
          model_data = 'troop_successors_el_blue'
        }
    }

    --Bolt-shooters - Art
    g_models[g_str_5fb1ba28e1af06001770cb78] = g_models[g_str_5fb1ba27e1af06001770ca94]

    --Diadachoii Camp
    g_models[g_str_5fb1b9dee1af060017709659_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Diadachoiin Camp Fort
    g_models[g_str_5fb1b9dee1af060017709659_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]


--  Lysimachid
-- 320 BC to 281 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af060017709671/explore
-- As of: 20210412

    --Macedonian charging horsemen - Kn General
    g_models[g_str_5fb1ba28e1af06001770cbdc_general] =  {
      {
        base = 'tile_grass_40x30',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_yellow',
            [2] = 'troop_successors_cavalry_general_blue',
            [3] = 'troop_successors_cavalry_bodyguard_yellow'
        }
      }
    }

    --Macedonian charging horsemen - Kn
    g_models[g_str_5fb1ba28e1af06001770cbdc] =  {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_cavalry_bodyguard_yellow'
      }
    }

    --Paionian, Greek, or Thracian horsemen - JavCav
    g_models[g_str_5fb1ba28e1af06001770cbde] ={
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_thracian_cv'
      },
      {
        base = 'tile_grass_40x30',
        random_models = {
          'troop_successors_lh',
          'troop_successors_lh_blue',
          'troop_successors_lh_red',
          'troop_successors_lh_black',
          'troop_successors_lh_yellow',
          'troop_successors_lh_green'
        }
      },
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_thracian_lh'
      }
    }

    --Phalanx - Pikes
    g_models[g_str_5fb1ba28e1af06001770cbe0] = {
      {
        base = 'tile_grass_40x15',
        random_models = {
          'troop_successors_pike1_yellow',
          'troop_successors_pike2_yellow'
        }
      }
    }

    --Macedonian Phalanx - Pikes
    g_models[g_str_5fb1ba28e1af06001770cbe3] = g_models[g_str_5fb1ba27e1af06001770ca86]

    --Mercenary Greek foot - LF
    g_models[g_str_5fb1ba28e1af06001770cbe5] = g_models[g_str_5fb1ba28e1af06001770cb6e]

    --Greek coastal city hoplites - HF
    g_models[g_str_5fb1ba28e1af06001770cbe7] = g_models[g_str_5fb1ba27e1af06001770ca8d]

    --Mercenary skirmishing bowmen and slingers - Sk
    g_models[g_str_5fb1ba28e1af06001770cbea] = {
      {
        base = 'tile_grass_40x20',
        random_models = {
          'troop_successors_skirmishers',
          'troop_successors_skirmishers_archers'
        }
      }
    }
    --Thracian peltasts - LF
    g_models[g_str_5fb1ba28e1af06001770cbec] = g_models[g_str_5fb1ba28e1af06001770cb6b]

    --Illyrian or Paionian javelinmen - LF
    g_models[g_str_5fb1ba28e1af06001770cbee] = g_models[g_str_5fb1ba27e1af06001770ca91]

    --Captured Antigonid war elephants
    g_models[g_str_5fb1ba28e1af06001770cbf1] = {
        {
          base = 'tile_grass_40x40',
          n_models = 1,
          model_data = 'troop_successors_el_yellow'
        }
    }

    --Lykian or Pamphylian vassal javelinmen - LF
    g_models[g_str_5fb1ba28e1af06001770cbf4] =  {
      {
        base = 'tile_grass_40x20',
        model_data = 'troop_ancient_spanish_caetrati'
      }
    }

    --Lysimachid Camp
    g_models[g_str_5fb1b9dee1af060017709671_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Lysimachid Camp Fort
    g_models[g_str_5fb1b9dee1af060017709671_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]


-- Antigonid
-- 320 BC to 285 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af060017709665/explore
-- As of: 20210412

    --Xystophoroi - Kn General
    g_models[g_str_5fb1ba28e1af06001770cb9b_general] =  {
      {
        base = 'tile_grass_40x30',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_black',
            [2] = 'troop_successors_cavalry_general_green',
            [3] = 'troop_successors_cavalry_bodyguard_black'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_5fb1ba28e1af06001770cb9b] =  {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_cavalry_bodyguard_black'
      }
    }

    --Macedonian Phalanx - Pikes General
    g_models[g_str_5fb1ba28e1af06001770cb9d_general] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1',
          [2] = 'troop_successors_pike2',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1'
      }
      }
    }

    --Macedonian Phalanx - Pikes
    g_models[g_str_5fb1ba28e1af06001770cb9d] = g_models[g_str_5fb1ba27e1af06001770ca86]

    --War elephants
    g_models[g_str_5fb1ba28e1af06001770cb9f] = {
      {
        base = 'tile_grass_40x40',
        n_models = 1,
        model_data = 'troop_successors_el_black'
      }
    }

    --Persian or Thracian horsemen armed with javelins - JavCav General
    g_models[g_str_5fb1ba28e1af06001770cba2_general] ={
      {
        base = 'tile_grass_40x30',
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_black',
          [2] = 'troop_successors_cavalry_general_green'
      }
      }
    }

    --Persian or Thracian horsemen armed with javelins - JavCav
    g_models[g_str_5fb1ba28e1af06001770cba2] = g_models[g_str_5fb1ba28e1af06001770cb62]

    --Pantodapoi phalanx - Pikes General
    g_models[g_str_5fb1ba28e1af06001770cba4_general] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike1_black',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1_black'
      }
      }
    }

    --Pantodapoi phalanx - Pikes General with Elephant Screen
    g_models[g_str_5fb1ba28e1af06001770cba4_general_elephant_screen] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike1_black',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1_black'
      }
      }
    }

    --Pantodapoi phalanx - Pikes
    g_models[g_str_5fb1ba28e1af06001770cba4] = {
      {
        base = 'tile_grass_40x15',
        random_models = {
          'troop_successors_pike1_black',
          'troop_successors_pike2_black'
        }
      }
    }

    --Pantodapoi phalanx - Pikes with Elephant Screen
    g_models[g_str_5fb1ba28e1af06001770cba4_elephant_screen] = {
      {
        base = 'tile_plain_40x10_El_Screen',
        n_models = 0
      }
    }

    --Mercenary peltasts - LF General
    g_models[g_str_5fb1ba28e1af06001770cb69_general] = {
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_psiloi',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_successors_psiloi'
        }
      }
    }

    --Greek mercenary peltasts - LF
    g_models[g_str_5fb1ba28e1af06001770cba7] = g_models[g_str_5fb1ba27e1af06001770ca91]

    --Greek mercenary hoplites - HF
    g_models[g_str_5fb1ba28e1af06001770cba9] = g_models[g_str_5fb1ba27e1af06001770ca8d]

    --Macedonian or mercenary skirmishing bowmen and slingers - Sk
    g_models[g_str_5fb1ba28e1af06001770cbac] = g_models[g_str_5fb1ba28e1af06001770cbea]

    --Akontistai - Rabble
    g_models[g_str_5fb1ba28e1af06001770cbae] = {
      {
        base = 'tile_grass_40x30',
        loose = true,
        random_models = {
          'troop_successors_ax_red',
          'troop_successors_ax_blue',
          'troop_successors_ax_green',
          'troop_successors_ax_black',
          'troop_successors_ax',
        }
      }
    }

    --Lykian or Pamphylian foot - Rabble
    g_models[g_str_5fb1ba28e1af06001770cbb1] = {
      {
        base = 'tile_grass_40x30',
        loose = true,
        model_data = 'troop_ancient_spanish_caetrati'
      }
    }
    --Greek allies hoplites - HF
    g_models[g_str_5fb1ba28e1af06001770cbb4] = {
      {
        base = 'tile_grass_40x15',
        random_models = {
          'troop_successors_hypaspist',
          'troop_successors_hypaspist_black',
          'troop_successors_hypaspist_blue',
          'troop_successors_hypaspist_green',
          'troop_successors_hypaspist_yellow',
        }
      }
    }

    --Stone throwers and ballistae - Art
    g_models[g_str_5fb1ba28e1af06001770cbb7] = g_models[g_str_5fb1ba27e1af06001770ca94]

    --Antigonid Camp
    g_models[g_str_5fb1b9dee1af060017709665_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Antigonid Camp Fort
    g_models[g_str_5fb1b9dee1af060017709665_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]


-- Early Ptolemaic
-- 320 BC to 275 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dfe1af06001770970f/explore
-- As of: 20210414

    --Xystophoroi - Kn General
    g_models[g_str_5fb1ba29e1af06001770ce5b_general] =  {
      {
        base = 'tile_grass_40x30',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_red',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_successors_cavalry_bodyguard_red'
        }
      }
    }

    --Xystophoroi\nDeployment dismounted from Knights General - Pikes General
    g_models[g_str_5fb1ba29e1af06001770ce5b_general_dismounted] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_red',
          [2] = 'troop_successors_pike1_red',
          [3] = 'troop_successors_cavalry_general_black',
          [4] = 'troop_successors_pike1_red'
        }
      }
    }

    --Xystophoroi\nDeployment dismounting as Pikes - Kn General
    g_models[g_str_5fb1ba29e1af06001770ce5b_general_mounted] =  {
      {
        base = 'tile_grass_40x30',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_red',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_successors_cavalry_bodyguard_red'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_5fb1ba29e1af06001770ce5b] =  {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_cavalry_bodyguard_red'
      }
    }

    --Xystophoroi\nDeployment dismounted from Knights - Pikes
    g_models[g_str_5fb1ba29e1af06001770ce5b_dismounted] =  {
      {
        base = 'tile_grass_40x15',
        model_data = 'troop_successors_pike1_red'
      }
    }

    --Xystophoroi\nDeployment dismounting as Pikes - Kn
    g_models[g_str_5fb1ba29e1af06001770ce5b_mounted] =  {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_cavalry_bodyguard_red'
      }
    }

    --Greek mercenaries, Tarentines, or similar horsemen - JavCav General
    g_models[g_str_5fb1ba29e1af06001770ce5e_general] ={
      {
        base = 'tile_grass_40x30',
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_red',
          [2] = 'troop_successors_cavalry_general_black'
       }
      }
    }

    --Greek mercenaries, Tarentines, or similar horsemen - JavCav
    g_models[g_str_5fb1ba29e1af06001770ce5e] = {
      {
        base = 'tile_grass_40x30',
        model_data = 'troop_successors_lh_red'
      }
    }

    --Phalanx - Pikes General
    g_models[g_str_5fb1ba29e1af06001770ce60_general] = {
      {
        base = 'tile_grass_40x15',
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike1_black',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1_black'
        }
      }
    }

    --Phalanx - Pikes General with Elephant Screen
    g_models[g_str_5fb1ba29e1af06001770ce60_general_elephant_screen] = {
      {
        base = 'tile_plain_40x10_El_Screen',
        n_models = 0
      }
    }

    --Phalanx - Pikes
    g_models[g_str_5fb1ba29e1af06001770ce60] = {
      {
        base = 'tile_grass_40x15',
        model_data = 'troop_successors_pike1_black'
      }
    }

    --Phalanx - Pikes with Elephant Screen
    g_models[g_str_5fb1ba29e1af06001770ce60_elephant_screen] = {
      {
        base = 'tile_plain_40x10_El_Screen',
        n_models = 0
      }
    }

    --Mercenary peltasts - LF General
    g_models[g_str_5fb1ba29e1af06001770ce63_general] = g_models[g_str_5fb1ba28e1af06001770cb69_general]

    --Greek mercenary peltasts - LF
    g_models[g_str_5fb1ba29e1af06001770ce63] = g_models[g_str_5fb1ba27e1af06001770ca91]

    --Thracian light infantry - LF
    g_models[g_str_5fb1ba29e1af06001770ce65_general] = {
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_ax1',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_thracian_ax1'
        }
      },
      {
        base = 'tile_grass_40x20',
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_axgen',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_thracian_axgen'
        }
      }
    }
    --Thracian light infantry - LF
    g_models[g_str_5fb1ba29e1af06001770ce65] = g_models[g_str_5fb1ba28e1af06001770cb6b]

    --Indian war elephants
    g_models[g_str_5fb1ba29e1af06001770ce68] = {
      {
        base = 'tile_grass_40x40',
        n_models = 1,
        model_data = 'troop_carthaginian_elephant'
      }
    }

    --Cretan skirmishing bowmen - Sk
    g_models[g_str_5fb1ba29e1af06001770ce6b] = g_models[g_str_5fb1ba27e1af06001770ca8b]

    --Akontistai - Rabble
    g_models[g_str_5fb1ba29e1af06001770ce6d] = g_models[g_str_5fb1ba28e1af06001770cbae]

    --Bolt-shooters - Art
    g_models[g_str_5fb1ba29e1af06001770ce6f] = g_models[g_str_5fb1ba27e1af06001770ca94]

    --Early Ptolemaic Camp
    g_models[g_str_5fb1b9dfe1af06001770970f_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Early Ptolemaic Camp Fort
    g_models[g_str_5fb1b9dfe1af06001770970f_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]

    --Early Ptolemaic Camp  Trains
    --g_models[g_str_5fb1b9dfe1af06001770970f_camp_pack_train] =