g_assets =
{
  dir="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/",
  counter_background="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/images/counter_background.png",
  token_no_camp="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/images/no_camp_token/no_camp.png",
  token_charge_through="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/images/charge_through_token/charge_through.png",
  token_hold_the_line="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/images/hold_the_line/hold_the_line.png",
  prepared_defenses_2d_diffuse_url="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/prepared_defenses/prepared_defenses_2d.png",
  prepared_defenses_2d_mesh_url="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/prepared_defenses/prepared_defenses_2d.obj",
  flank_march_card_red="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/flank_march_card/flank_march_card_red.png",
  flank_march_card_blue="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/flank_march_card/flank_march_card_blue.png",
  rock_1_obj="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/terrain/terrain_rock_grey/terrain_rock_grey_1.obj",
  rock_2_obj="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/terrain/terrain_rock_grey/terrain_rock_grey_2.obj",
  rock_3_obj="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/terrain/terrain_rock_grey/terrain_rock_grey_3.obj",
  rock_4_obj="https://raw.githubusercontent.com/marcpawl/Triumph_TTS/5fff50b3196b82708e3d0b620092f0c62800430e/assets/terrain/terrain_rock_grey/terrain_rock_grey_4.obj",
}
