g_assets =
{
  dir="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/",
  counter_background="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/images/counter_background.png",
  token_no_camp="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/images/no_camp_token/no_camp.png",
  token_charge_through="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/images/charge_through_token/charge_through.png",
  token_hold_the_line="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/images/hold_the_line/hold_the_line.png",
  prepared_defenses_2d_diffuse_url="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/prepared_defenses/prepared_defenses_2d.png",
  prepared_defenses_2d_mesh_url="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/prepared_defenses/prepared_defenses_2d.obj",
  flank_march_card_red="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/flank_march_card/flank_march_card_red.png",
  flank_march_card_blue="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/flank_march_card/flank_march_card_blue.png",
  rock_1_obj="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/terrain/terrain_rock_grey/terrain_rock_grey_1.obj",
  rock_2_obj="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/terrain/terrain_rock_grey/terrain_rock_grey_2.obj",
  rock_3_obj="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/terrain/terrain_rock_grey/terrain_rock_grey_3.obj",
  rock_4_obj="file:///D:/Tabletop Simulator Mods/new_triumph_tts/assets/terrain/terrain_rock_grey/terrain_rock_grey_4.obj",
}
