
on: push

jobs:
  unittest_job:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt-get update && sudo apt-get install -y lua5.2 make
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run unit tests
        run: make submodules check
        working-directory: unittests



